### ISSUE TITLE
[BUG]: Failed to call method

### ISSUE THREAD

**Issue by iaoxuesheng** [Mintplex-Labs/anything-llm#1000]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Updating location Prisma binaries for linux builds.
[21700:0331/163659.380261:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: 未找到请求的设置
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/can/.config/anythingllm-desktop/storage/anythingllm.db"

Error: Schema engine error:

Prisma schema loaded from prisma/schema.prisma
Error: 
EROFS: read-only file system, unlink '/tmp/.mount_Anythi2fjdh3/resources/backend/node_modules/.prisma/client/index.js'

[OllamaProcessManager] Ollama will bind on port 36215 when booted.

**Comment by timothycarambat** [comment]
What distro is this for? Additionally is this even stopping the app from launching or is it just an error message? Searching up  this message it apparently is innocuous
