### ISSUE TITLE
[FEAT]: Import unknown format as text file

### ISSUE THREAD

**Issue by nekopep** [Mintplex-Labs/anything-llm#1001]
### What would you like to see?

Hello,
I wanted to upload a qml file (basically a javascript equivalent for QT framework). 
https://doc.qt.io/qt-6/qtqml-documents-topic.html
Sadly anything-llm desktop refused it.
Perhaps it could be interesting for unsupported files, to ask the user if it ok to interpret is as js or txt or whatever is ever supported?
![image](https://github.com/Mintplex-Labs/anything-llm/assets/2825997/80b73066-7055-4a34-9e68-27ab8572a2ba)

**Comment by timothycarambat** [comment]
Good idea! In the meantime, leaving this as a note for PR so i dont forget:
https://github.com/Mintplex-Labs/anything-llm/blob/df054eb8d7b0d0dff3751f3aaef535861000c770/collector/utils/files/mime.js#L24

Just add the relevant file extensions here and they will be passes as text/plain.

I have never heard of this file format before!

**Comment by nekopep** [comment]
Continuing my exploration, you can also add ".sh" files for bash script analysis. Can be interpreted as.txt files.

https://ryanstutorials.net/bash-scripting-tutorial/bash-script.php

**Comment by nekopep** [comment]
Oups, Forget this, my file did not had extension, ".sh" files are well recognised.
Is it possible to apply something like "file" on the uploaded files to find possible hidden extension or perhaps anaylsing first line shebang?

**Comment by timothycarambat** [comment]
We currently do this with parsing of the mime-type, which can be spoofed or broken, but its more of a convenience wrapper for forcing "unknown" files being parsed as text. SH should be handled under this as its mime should be covered? It may be `text/x-shellscript`
