### ISSUE TITLE
[BUG]: Embedding ollama+llama2-chinese , chinese docx failed

### ISSUE THREAD

**Issue by wilsonlv** [Mintplex-Labs/anything-llm#1002]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![微信图片_20240401162520](https://github.com/Mintplex-Labs/anything-llm/assets/17563749/f46296f3-a839-49b7-8458-c35037a08686)
![微信图片_20240401162525](https://github.com/Mintplex-Labs/anything-llm/assets/17563749/7cb79beb-bec0-450a-8ee8-239d0791ad8e)

**Comment by timothycarambat** [comment]
It would seem to indicate that the Ollama embedder returned a zero-length vector. Can you confirm if this embedder is processing text chunks properly manually first?

**Comment by wilsonlv** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/17563749/6eafffad-4426-456e-b03e-20baaa76bea3)
Yea, if I add a English docx，it successes

**Comment by timothycarambat** [comment]
Closing as wontfix, I did not notice prior but you have an LLM **chat** model `llama2-chinese` as your embedding model.
LLMs cannot embed text.  Please use an embedding model like `nomic-text-embed` or `mxbai` for Chinese lang support embeddings
