### ISSUE TITLE
[BUG]: AnythingLLM desktop app fails to connect to running binary LocalAI instance

### ISSUE THREAD

**Issue by lebedov** [Mintplex-Labs/anything-llm#1003]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I'm running LocalAI 2.10.1 locally built as a binary (i.e., not in a Docker image) on an Intel MacBook running MacOS 14.4.1. I can query the running instance via curl (e.g., `curl http://localhost:8080/v1/models` lists the luna-ai-llama2 model I have stored in the instance's model storage folder), but AnythingLLM doesn't seem to be able to access that instance to let me choose an available model when I select LocalAI on the LLM Preference screen (and if I run the LocalAI instance with the --debug flag, I don't see the app ever make a GET call to the instance when I navigate the the LLM Preference screen and select LocalAI).

### Are there known steps to reproduce?

- Install AnythingLLM 1.4.1 on an Intel MacBook running MacOS 14.4.1. 
- Clone LocalAI 2.10.1 and build on the same system. 
- While in the LocalAI source repo folder, download and install luna-ai-llama2 using `wget https://huggingface.co/TheBloke/Luna-AI-Llama2-Uncensored-GGUF/resolve/main/luna-ai-llama2-uncensored.Q4_0.gguf -O models/luna-ai-llama2`
- Start LocalAI by running the local-ai binary in the above folder.
- Verify that one can see the saved model by running `curl http://localhost:8080/v1/models` (which should return something like `{"object":"list","data":[{"id":"luna-ai-llama2","object":"model"}]}`).
- Start the AnythingLLM desktop app, navigate to the LLM Preference screen, select LocalAI from the LLM Providers menu, and try to select a model from the Chat Model Selection dropdown menu; the menu will not open.

**Comment by lebedov** [comment]
When I tried changing the endpoint from the default http://localhost:8080/v1 to http://127.0.0.1/v1, the app was able to make a GET call to the LocalAI instance and list the saved luna-ai-llama2 model. The fact that the default didn't work seems like a bug.

**Comment by timothycarambat** [comment]
This is certainly some kind of networking layer resolution on your OS, likely related to it being linux based so somehow localhost does not seem to connect or map to 127.0.0.1. Informative but will mark as wonfix for the time being,

**Comment by lebedov** [comment]
Just to be clear, other apps on my laptop such as curl, wget, Firefox, etc. Can resolve localhost to 127.0.0.1 with no problems, so I'm not sure this is due to name resolution issues.
