### ISSUE TITLE
[BUG]: addDocumentToNamespace Ollama Failed to embed: [undefined]: undefined

### ISSUE THREAD

**Issue by shikeqiang** [Mintplex-Labs/anything-llm#1006]
### How are you running AnythingLLM?

Docker (local)

### What happened?

i'm use ollama nomic-embed-text,upload word get errors.

**Comment by timothycarambat** [comment]
Please post any relevant error logs as this is too non-descript to help debug.

**Comment by timothycarambat** [comment]
> INVALID OLLAMA SETUP. No embedding engine has been set. Go to instance settings and set up an embedding interface to use Ollama as your LLM.

This is pretty self-explainatory here. Please go to the embedder setting and select one and be sure to click save when done setting up the connection

**Comment by shikeqiang** [comment]
I choose local ollama as the Embedding Providers and nomic-embed-text:last. In addition, the LLM Preference is correctly configured on ollma to enable normal dialogue

Chunks created from document: 1
[OllamaEmbedder] Embedding 1 chunks of text with nomic-embed-text:latest.
addDocumentToNamespace Ollama Failed to embed: [undefined]: undefined
Failed to vectorize search_jd.com-Search.html
[TELEMETRY SENT] {
  event: 'documents_embedded_in_workspace',
  distinctId: 'a96b4397-166e-423c-84a1-4c972833b6c3',
  properties: {
    LLMSelection: 'ollama',
    Embedder: 'ollama',
    VectorDbSelection: 'lancedb',
    runtime: 'docker'
  }
}

**Comment by diamsa** [comment]
I had the same issue, even though i did not use Docker, and it was because the Ollama server wasn't running. I forgot to launch it. But as you are using docker, make sure your containers don't have a networking problem when they try to use the Ollama service locally.

**Comment by timothycarambat** [comment]
That checks out. Will attempt to replicate it with that information now. If anything we should handle that error then
