### ISSUE TITLE
[FEAT]: multilangual

### ISSUE THREAD

**Issue by Kofangun** [Mintplex-Labs/anything-llm#1009]
### What would you like to see?

hi, i ve tried to use multilingual models with instruction in that language and still the bot try to answer in english. is it hard coded ?

**Comment by timothycarambat** [comment]
Modify the system prompt of the workspace and just tell it to respond in a specific language

**Comment by Kofangun** [comment]
Yes the best I get is both languages mixed up. when I talk directly to the model with ollama run, I don't have this issue.
