### ISSUE TITLE
Use Ollama to reload the model each time

### ISSUE THREAD

**Issue by 17Reset** [Mintplex-Labs/anything-llm#1011]
When I use ollama as LLM preference in Anythingllm, every time I ask a question, the model in ollama will be reloaded, which will take a lot of time. But when I use ollama's api alone to make a model call to ollama, ollama can load the model into the GPU's memory, and asking the question at the next time will be very fast.

**Comment by timothycarambat** [comment]
Are you using Ollama via the regular integration or the built-in Ollama on desktop?

Seems like this can be solved by passing `mlock` during chat requests

**Comment by 17Reset** [comment]
My solution was to start two ollama api's and put LLM and Embedding in two separate api's so that it doesn't cause memory resident interruptions in LLM.
