### ISSUE TITLE
[FEAT]: Add Embed customization option for chat bubble icon location 

### ISSUE THREAD

**Issue by jaschadub** [Mintplex-Labs/anything-llm#1012]
### What would you like to see?

Add a customization option to place the embed chat bubble icon bottom-right (current only option), bottom-left, top-right, or top-left. Perhaps a drag-able option as well.

**Comment by timothycarambat** [comment]
We will not do draggable, but we can do all the normal locations in the corners 👍

**Comment by timothycarambat** [comment]
Related: https://github.com/Mintplex-Labs/anything-llm/pull/976
