### ISSUE TITLE
[BUG]: Pinecone::Invalid ENV settings error

### ISSUE THREAD

**Issue by carsam2021** [Mintplex-Labs/anything-llm#1018]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

whatever prompt I use I keep getting error: **Pinecone::Invalid ENV settings**

### Are there known steps to reproduce?

install on MacOS, created a workspace called wp1, try to ask anything
![Screenshot 2024-04-02 at 22 35 33](https://github.com/Mintplex-Labs/anything-llm/assets/96111234/49759e13-d5b3-4cf5-9e0b-9a66224d623a)

**Comment by timothycarambat** [comment]
Go to vector database and either swap to `LanceDB` or if you are using `Pinecone` you can use the proper ENV keys if using that provider. LanceDB is the default, so if it says pinecone and you dont want that as your vector db, that would have probably been a misclick during onboarding
