### ISSUE TITLE
[FEAT]: Include CSS selectors on all HTML elements in ChatUI

### ISSUE THREAD

**Issue by simonives** [Mintplex-Labs/anything-llm#1019]
### What would you like to see?

Currently the ChatUI JavaScript generates HTML elements that are un-named (e.g. wrapping everything in an unnamed DIV, p elements un-named, etc.).

In order to facilitate end-user styling, consideration should be given to naming all, or as many, HTML elements as possible. Every HTML element should be able to be selected by end-user CSS.

The current workaround is to save a copy of the JavaScript file locally, make the required HTML naming changes, and load from the saved JavaScript file. This introduces stability issues when changes are made to the main application, or updates are made to ChatUI functionality.

**Comment by simonives** [comment]
E.G.:
- Main DIV could simply be: <div id="anythingllm">
- Chat Bubble DIV could simply be: <div id="anythingllm_bubble">
- User chat could simply be: <p id="input" class="user"> and <p id="output" class="ai">
etc.

**Comment by timothycarambat** [comment]
Great idea!
