### ISSUE TITLE
[FEAT]: Load documents from online locations

### ISSUE THREAD

**Issue by simonives** [Mintplex-Labs/anything-llm#1020]
### What would you like to see?

Presently documents can be added to a workspace via the UI by dragging-and-dropping, or uploading from a location on the user's computer.

Consider adding online locations to source documents as well (e.g. http/s, SFTP, ownCloud, Nextcloud, Dropbox, Google Drive, etc.).

Could even monitor these locations for changes and update AnythingLLM accordingly.

**Comment by timothycarambat** [comment]
Drag and drop has been live since https://github.com/Mintplex-Labs/anything-llm/pull/1995
Online locations will be supported via external plugins for ultimate flexibility
Automatic file change watching is supported via: https://docs.anythingllm.com/beta-preview/active-features/live-document-sync
