### ISSUE TITLE
[FEAT]: Allow user to change the HTML title and Favicon

### ISSUE THREAD

**Issue by CharlesBdg** [Mintplex-Labs/anything-llm#1026]
### What would you like to see?

In Appearance tab, allow the user to change the HTML title and Favicon. ("head" section of the HTML page)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/73182771/25f29484-f32c-4015-b584-54dcd46d22e9)

**Comment by timothycarambat** [comment]
moving to #1373
