### ISSUE TITLE
OpenAI API Key seems to not be read by AnythingLLM

### ISSUE THREAD

**Issue by pligor** [Mintplex-Labs/anything-llm#104]
I tried to type the open ai key in  the .env file  with three different ways:
1) OPEN_AI_KEY=xxxxxxxx
2) OPEN_AI_KEY='xxxxxxxx'
3) OPEN_AI_KEY="xxxxxxxx"

I do not think it makes a difference but every time we see this error in Anything LLM:

<img width="668" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/1448173/29b10cfe-8165-44a8-ac9e-fe48e8d99206">
and also cannot send prompts to anythingllm

Note that in addition ChromaDB server is up and running at localhost:8000 (pinecone and lancedb are disabled)

Any ideas of what is wrong ? How exactly to write the Open AI Api key in the .env file ?

**Comment by vikas94** [comment]
did you rebuild the docker after changing the environment variables?
you should rebuild the docker and try again!
hope it works.

**Comment by hillct** [comment]
The .env.example file erroneously has quotes around variable values which causes problems in cases like the Dockerfile groupadd command which uses GID='1000' interpreted without shell substitutions so groupadd fails saying "'1000' is no a valid GID (number)" and likewise, The OpenAI API key must be added to the .env file without quotes, that's no he only issue here, unfortunately. I seems there's an underlying parsing issue as well.

**Comment by pligor** [comment]
hi @vikas94 fyi I am in Macbook M2 Pro
The README notes should mention that the full rebuild is with this:
`docker-compose down && docker-compose build --no-cache && docker-compose up -d`
And by removing all double or single quotes that where wrapping the values, things seems to be working ok now
