### ISSUE TITLE
[BUG]: Quadruple Download Notifications

### ISSUE THREAD

**Issue by elibroftw** [Mintplex-Labs/anything-llm#1040]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/21298211/993fcab1-44ff-4770-bbb8-d73bd946158a)

**Comment by timothycarambat** [comment]
@shatfield4

**Comment by timothycarambat** [comment]
Closed by #1048
