### ISSUE TITLE
Add a way to update docs

### ISSUE THREAD

**Issue by simonSlamka** [Mintplex-Labs/anything-llm#105]
Hey,

I have recently tried updating a doc, but ended up with creating a new one instead, which did have the same name, but the id after the name differed. As such, I had to manually remove the original and then embed the new one. There could be a way to simply overwrite (after confirming such action in a modal) a file that has the same name within a given workspace.

Thank you

**Comment by AntonioCiolino** [comment]
i want this too, but keep in mind when you change the doc, you have to re-embed it anyway - so it's going to get a new guid/name.

**Comment by simonSlamka** [comment]
> i want this too, but keep in mind when you change the doc, you have to re-embed it anyway - so it's going to get a new guid/name.

@AntonioCiolino Yes, but the process could be more streamlined, not requiring manual removal of the old doc. It could be an optional switch.

**Comment by timothycarambat** [comment]
This is something that would be a massive breakthrough in the space (and something we have a solution for) so that you can more easily manage and modify documents in place without a re-embed totally.

**Comment by mrlopezco** [comment]
@timothycarambat 
Is there a solution for this? Whenever I upload the same document per API, or a github repo, it always creates a new file.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/22092667/e9068b3b-02c8-414d-89e9-8f6458cb6a0e)

**Comment by simonSlamka** [comment]
> I’m so confused. This seems like a feature request. The repo author agreed it is a good idea. They said there was a solution. Then, the issue was closed without outlining what the solution is, or where the feature went in terms of roadmap. A little more context would be appreciated. It would complement the product nicely.

Agreed
