### ISSUE TITLE
  My Documents move to workspace error

### ISSUE THREAD

**Issue by Alcie1227** [Mintplex-Labs/anything-llm#1053]
### Description

![image](https://github.com/Mintplex-Labs/anything-llm/assets/165271084/4d13d5f8-822b-4609-9f66-7c18bbcb1468)

**Comment by CatInCloud** [comment]
@Alcie1227 Has this issue been solved? How did it be solved?I havethe same issue

**Comment by timothycarambat** [comment]
See pinned issue. Its at the top https://github.com/Mintplex-Labs/anything-llm/issues/821. IP is blocked by hugging face

**Comment by Alcie1227** [comment]
> 请参阅固定问题。它位于[顶部 #821](https://github.com/Mintplex-Labs/anything-llm/issues/821)。IP被拥抱的脸挡住了

Thans，but I installed the Windows version of AnythingLLMDesktop.exe.

**Comment by Alcie1227** [comment]
> @Alcie1227 Has this issue been solved? How did it be solved?I havethe same issue

not yet
