### ISSUE TITLE
[FEAT]: More connectors, like whatsapp

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1054]
### What would you like to see?

Nowadays, integration with applications such as whatsapp is a 'must' for a chatbot.
Are you planning to integrate it?
Do you have an idea of what the timeframe will eventually be?

**Comment by timothycarambat** [comment]
Can be done with Custom agent skills (for actions): https://docs.anythingllm.com/agent/custom/introduction

Loading data will be available via plugins as well for data connectors : TBD

**Comment by musfandi** [comment]
May i know how to do it using custom agent...
