### ISSUE TITLE
[DOCS]: How to adjust the size of chunk?

### ISSUE THREAD

**Issue by FrankTseng168** [Mintplex-Labs/anything-llm#1055]
### Description

In general, smaller chunk sizes yield better result. How to adjust the size of chunk in AnythingLLM?

**Comment by timothycarambat** [comment]
Will be tracked in https://github.com/Mintplex-Labs/anything-llm/issues/490. Chunk size depends on use case to get better performance, so it will be customizable. That issue is tracking that
