### ISSUE TITLE
[BUG]: Ollama Failed to embed: [undefined]: undefined  // TypeError: fetch failed  cause: Error: read ECONNRESET

### ISSUE THREAD

**Issue by CatInCloud** [Mintplex-Labs/anything-llm#1060]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

linux+docker:
if i dont upload files,everthing is ok
when i upload a file succeed ,then local model cant use
![issue](https://github.com/Mintplex-Labs/anything-llm/assets/45314758/a3d997a1-7bcd-4da4-b45c-998dd336d1b8)

**Comment by LuciAkirami** [comment]
I'm getting the same error in the UI. It works fine without uploading documents. But when I upload a document and try to chat it gives the following error

**Comment by FarVision2** [comment]
Gwen 14 is not an embedding model. Try
https://ollama.com/library/mxbai-embed-large
or
https://ollama.com/library/nomic-embed-text

**Comment by timothycarambat** [comment]
Your ollama instance is not running or unreachable.
https://github.com/Mintplex-Labs/anything-llm/issues/1006

`ollama serve` not `ollama run`

**Comment by CatInCloud** [comment]
> Gwen 14 is not an embedding model. Try https://ollama.com/library/mxbai-embed-large or https://ollama.com/library/nomic-embed-text

tried,didnt work

**Comment by CatInCloud** [comment]
> Your ollama instance is not running or unreachable. #1006
> 
> `ollama serve` not `ollama run`

ollama server is running , when i do instance settings then click "save changes" , it show me green , means instance is runing and reachable. 
ollama deploy remote linux , access ip:ports with proxy machines. maybe it dont support linux or proxy stuff ablout query mode

**Comment by timothycarambat** [comment]
> ollama server is running , when i do instance settings then click "save changes" , it show me green , means instance is runing and reachable.

We do not ping the instance once you save credentials, so it still very well be unreachable. If ollama is deployed on a different remote linux machine and you cant reach it from AnythingLLM, its almost certainly a networking issues in the setup between those two machine
