### ISSUE TITLE
[BUG]: addDocumentToNamespace SystemSettings is not defined

### ISSUE THREAD

**Issue by tanranuncle** [Mintplex-Labs/anything-llm#1061]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

When I was about to upload the file to workspace, it encountered an error: SystemSettings is not defined.
<img width="1308" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/26816446/99b92a8e-f69d-4dca-b489-16669396b7a6">

### anythingllm
>mintplexlabs/anythingllm:master
### localai
>localai/localai:latest-aio-cpu
### chroma
>chromadb/chroma:0.4.24

### k8s log: 
<img width="1006" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/26816446/bd6b12ca-e6b0-4f2f-833b-f82be779085b">

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/pull/1066
