### ISSUE TITLE
[BUG]: failed to save LLM 

### ISSUE THREAD

**Issue by sidneyz139** [Mintplex-Labs/anything-llm#1063]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/53903688/657e8f3b-7fe6-447e-975a-79e26d23c731)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/53903688/4674e549-43e3-4e0c-a404-b69135c7fbd9)
can not save LLM setting, when using ollama. no matter use IP address or use host.docker.internal
on ubuntu 20.04

### Are there known steps to reproduce?

export STORAGE_LOCATION="/var/lib/anythingllm" && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d --name anythingllm -h "anythingllm" -p 3001:3001 \
--add-host=host.docker.internal:host-gateway \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm

**Comment by timothycarambat** [comment]
1. Are you able to save _any_ LLM provider?
2. In the chrome inspector for network, what response are you getting from the backend once attempting to update?
3. Are you able to view the docker logs while attempting this save? That may lead to a more informative debug.

**Comment by timothycarambat** [comment]
Unable to replicate on `latest` docker on `MacOS Sonoma`. Used `http://host.docker.internal:11434` as base URL and was able to view models and set token size and continue onboarding.

`host.docker.internal` may not be available on Ubuntu, but that does not seem to be the current issue.

**Comment by gabesan21** [comment]
I'm having this issue on desktop app as well. Docker version seems to be fine.

**Comment by long-woo** [comment]
Use `docker logs [YOU_CONTAINER]` to look at the error log. What I encountered was that the `.env` file did not have write permissions.

**Comment by gabesan21** [comment]
So, I'm not having the issue on Docker Version. I'm using both, Docker on raspberry PI and desktop on my computer.
The problem is on Desktop version 1.4.4, docker seems fine.

I changed back to 1.4.2 because of that

**Comment by timothycarambat** [comment]
@gabesan21 On desktop you are running ollama on the same host machine right? What connection URL are you using for that because I cannot replicate this on 1.4.4 desktop either using `http://127.0.0.1:11434`

Clearly, at some point the connection worked because it shows the models in the dropdown, so this was only occurring on save?
