### ISSUE TITLE
Needs excel files.  [FEAT]: 

### ISSUE THREAD

**Issue by stuinfla** [Mintplex-Labs/anything-llm#1065]
### What would you like to see?

A huge amount of info is loaded into Microsoft Excel files, yet you do not allow them in your document set.    That DRAMATICALLY reduces the value of this solution.  Solving that would increase your TAM greatly.

**Comment by timothycarambat** [comment]
You can do this already. RAG on an excel is just a whole different use case but can be solved by document pinning or via agents. Agents are not supported yet.
