### ISSUE TITLE
addToNamespace fails with limited dimensionality

### ISSUE THREAD

**Issue by Tdarra** [Mintplex-Labs/anything-llm#107]
Trying to add seemingly small local txt files into `hotdir`. UI suggests that the article is a mere 360 tokens yet vector dimensionality ends up being 1536. Other than upgrading Pinecone pods, is there a workaround?

`Adding new vectorized document into namespace demo
Chunks created from document: 3
Inserting vectorized chunks into Pinecone.
addDocumentToNamespace PineconeClient: Error calling upsert: PineconeError: Vector dimension 1536 does not match the dimension of the index 512
Failed to vectorize website-ww2.arb.ca.gov/article-_.json
`

**Comment by timothycarambat** [comment]
Pinecone dimensionality is not a limiting factor and is a setting you set when you create the index. Simply create an index in Pinecone with 1536 dimensions. Token count and dimensions are not related as one is a metric for LLMs and the other is a metric for vector-space embeddings. Even a single token can be 1536 dimensions.

In your pinecone account just create a new index with 1536 dimensions so it can accept openAI embeddings and you are good! A 360 token doc will probably only amount to like <10 vectors.
