### ISSUE TITLE
[BUG]: Embed firefox doesn't work

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1070]
### How are you running AnythingLLM?

Docker (local)

### What happened?

If I insert the iframe of a workspace into a page and type a message, it works with Chrome, Edge and Safari.
But on Firefox the page opens correctly, but when I type something it goes into error and the iframe disappears.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/22151717/d7b9c80c-dc88-4778-86c8-d75dfa5f4b25)

### Are there known steps to reproduce?

With firefox browser

**Comment by timothycarambat** [comment]
We do not support iframing of the entire website in another website, so that will be marked as wontfix.

However, i think more explanation is required as the error you show is from the embed script, not from the workspace chat page.

Does this error occur in the _emebeddable widget_? That is something different and very well may be a bug

**Comment by Mirgiacomo** [comment]
Sorry, I misunderstood, @timothycarambat 

The problem exists when I take the workspace integration html code (taken from the 'embedding' section of anything) and put it into an html page.
If I now open this html page with chrome or edge, I see my chatbot correctly in the bottom right-hand corner. If I try to write on it, it works.
However, if I open it from firefox and write something, it disappears and the error I wrote earlier appears in the console.

**Comment by shatfield4** [comment]
I cannot replicate this bug. I see that you are using the Docker version of AnythingLLM, can you give me any more info on how I can replicate this? What version of Firefox are you using? Is your AnythingLLM instance running on a VPS or are you running it locally on your machine?

**Comment by timothycarambat** [comment]
Closing as stale
