### ISSUE TITLE
[BUG]: Error uploading link: A processing error occurred When trying to fetch website

### ISSUE THREAD

**Issue by troymroberts** [Mintplex-Labs/anything-llm#1071]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Can upload documents to a workspace just fine, however when i try to add a website via fetch website get the following error:

Error uploading link: A processing error occurred

**Comment by timothycarambat** [comment]
> Docker (local)

Assuming you are using docker then. You should be using the command found in our [Docker docs](https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md#how-to-use-dockerized-anything-llm). The command for starting a container 

```
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

Here, the critical item is `--cap-add SYS_ADMIN` as without this argument we cannot open Puppeteer in a sandboxed environment and it will fail to execute the scraping of a website.

Worth noting that some "one-click docker deployment" sites like Render and Railway intentionally block this command or do not allow running custom docker commands. So this functionality does not work.

**Comment by flijun** [comment]
我发现我上传的文件名里有引号，删除就好了
