### ISSUE TITLE
[FEAT]: Option for user to delete specific question and its reply.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#1076]
### What would you like to see?

Since the LLM chat can be correctly used when a user keeps on discussing a particular topic. Some times when a answer is not acceptable the user has to start again since the LLM may reply the same answer to any other similar question.
In this case there should be an option to delete the answer by the user so that he can continue in the same chat.
![delete chat](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/22d02930-14e8-44f0-9618-ac6151d8fe87)

**Comment by ybabel** [comment]
This feature is priority n°1 for me. I'm astonished there is so few votes on it.

**Comment by timothycarambat** [comment]
This has been live for a while now: https://github.com/Mintplex-Labs/anything-llm/pull/1812
