### ISSUE TITLE
[BUG]: Cannot select txt file in a folder

### ISSUE THREAD

**Issue by UserName-wang** [Mintplex-Labs/anything-llm#1079]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Cannot select txt file in a folder.
AnythingLLM can display the folder "txt" correctly. but cannot display the txt file inside this folder which file name is ros.txt.
See the screenshot below:
![Screenshot from 2024-04-10 21-42-24](https://github.com/Mintplex-Labs/anything-llm/assets/57220346/52e146d3-de2e-46e4-8803-1e6cf66d9540)

or which folder I should mount into docker?

**Comment by timothycarambat** [comment]
Did you upload the file ros.txt or did you just put a file in `storage/documents/txt/ros.txt`? If so, that is not how the storage works, the files need to be processed and put in the standardized metadata format.

If you click on upload and choose ros.txt it will then show under `custom documents` which can then be moved to `txt` folder.

**Comment by UserName-wang** [comment]
Thank you for your reply!

I just put a file in storage/documents/txt/ros.txt

Because I want to try if there any way to upload the file more easily. Like upload a folder. Then the files in that folder can be upload automatically. Instead of one by one.

> 在 2024年4月11日，00:23，Timothy Carambat ***@***.***> 写道：
> just put a file in storage/documents/txt/ros.txt

**Comment by timothycarambat** [comment]
Then this would not be a bug, instead i think this would do better as another feature request, but this is already covered by https://github.com/Mintplex-Labs/anything-llm/issues/674 👍

**Comment by timothycarambat** [comment]
You have to upload documents via the uploader, they will not be found if you just place them in documents! That is not how the system works!
