### ISSUE TITLE
Has anyone tried setting this up for multiple users?

### ISSUE THREAD

**Issue by AlexanderMoen** [Mintplex-Labs/anything-llm#108]
This isn't so much an issue as a question for others that may have implemented AnythingLLM for multiple people (or this may become an enhancement request if there's no good, easy, and inexpensive way to do it). 

I essentially want to be able to run this remotely on AWS but potentially have multiple users access it. Is the only way to do this without users stepping on each others' toes, to set up a separate AWS instance for each one? Or, perhaps create a separate workspace and each user sticks to their own workspace?

I'm just curious if others have attempted to do such a thing and what the best way might be to give this a whirl.

**Comment by timothycarambat** [comment]
Multiple user support _is coming soon_ on the roadmap that will be published this week.

This will be native in the app for specifically cloud-hosted users who will have their own logins and workspaces they are allowed to access and/or create.

**Comment by AlexanderMoen** [comment]
awesome to hear, @timothycarambat. I can't seem to find a current roadmap and don't want to miss the posting. Where will it be posted exactly?

Also, do you have a Patreon or some sort of way to chip in for this? I really like the work you've done so far and want to do a small monthly contribution to help keep up the amazing work.

**Comment by timothycarambat** [comment]
@AlexanderMoen The roadmap is planning to be published tomorrow evening PST since we are working on it currently!

Appreciate the thought of a donation a **ton**, right now nothing is set up so just the vocalized support will have to suffice 😄

**Comment by timothycarambat** [comment]
moved to #115
