### ISSUE TITLE
[BUG]: Repositories with dots in their names can't be added via Data Connectors

### ISSUE THREAD

**Issue by CLBarajas** [Mintplex-Labs/anything-llm#1083]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When using a GitHub Pages repository site, the repository fails to load with a warning:

> Could not prepare Github repo for loading! Check URL

### Are there known steps to reproduce?

1. Search GitHub for any public GitHub Pages site, by using the search term [`github.io`](https://github.com/search?q=github.io&type=repositories).
2. Copy any repository URL.
3. Open a Workspace in AnythingLLM.
4. Click the document upload button to open the documents area
5. Navigate to the "Data Connectors" tab
6. Paste the URL into the "GitHub Repo URL" field
7. Click the Submit button

**Comment by timothycarambat** [comment]
Could you not just put that URL into the web scraper since that is a website, and not a repo now? Repo links should be 
https://github.com/academicpages/academicpages.github.io
While its page (which can be scraped) is
https://academicpages.github.io/

**Comment by CLBarajas** [comment]
I previously assumed GitHub Pages repositories were the only ones that would permit having a dot in their URL. I have re-tested against https://github.com/karpathy/llm.c, and it also fails, so I've updated the title to better reflect what I think is happening here.
