### ISSUE TITLE
[BUG]: LanceDBError with nomic-embed-text

### ISSUE THREAD

**Issue by ZiHAO-LI-cmd** [Mintplex-Labs/anything-llm#1088]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I deployed `nomic-embed-text:last` embedding model on server but met an error when using it.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/83964237/f1064f25-089f-4d06-99be-fe0b28a357b9)

If I switch to AnythingLLM Embedder, it works well. The  `nomic-embed-text` model works well in server because I tested it and it can return embedding vectors. So, I think it maybe the incompatibility problem with LanceDB.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/83964237/e38f3929-ad79-4a5c-b6f7-e2495da68b9e)

### Are there known steps to reproduce?

Same error from others: https://github.com/ollama/ollama/issues/2778

**Comment by timothycarambat** [comment]
On latest ollama:
- `ollama serve` is running
- `ollama pull nomic-embed-text`
Set up embedder connection
<img width="815" alt="Screenshot 2024-04-15 at 10 27 48 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/9929effb-bc5b-4863-9f78-ba94ee061577">

- Create new workspace
- Upload fresh document and move into workspace
- Document is embedded successfully
- Send Chat - complete response (openAi as LLM)
<img width="1158" alt="Screenshot 2024-04-15 at 10 28 58 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/a9966cdd-8562-4a65-aeda-e35666bdd50a">

Confirm DB has vectors
<img width="1158" alt="Screenshot 2024-04-15 at 10 28 58 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/4365e9be-7aba-4f1a-9069-513b89eeae05">

**Comment by timothycarambat** [comment]
Close this issue. This error results from swapping embedder providers or models after you already have cached documents or active embeddings.

When you change embedders - the dimensions between previously embedded content and new content or queries will not work. That is just how it works. We have now set a warning telling you this to prevent running into this issue #1131
