### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by maxdraki** [Mintplex-Labs/anything-llm#1092]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I get the failed to fetch error when submitting any chat

`
~/Desktop/AnythingLLMDesktop.AppImage
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)

(process:539731): GLib-CRITICAL **: 19:01:34.027: g_file_test: assertion 'filename != NULL' failed
Updating location Prisma binaries for linux builds.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/max/.config/anythingllm-desktop/storage/anythingllm.db"

Already in sync, no schema change or pending migration was found.

EROFS: read-only file system, unlink '/tmp/.mount_Anythil7um8Y/resources/backend/node_modules/.prisma/client/index.js'

Prisma schema loaded from prisma/schema.prisma
Error: 
EROFS: read-only file system, unlink '/tmp/.mount_Anythil7um8Y/resources/backend/node_modules/.prisma/client/index.js'

[OllamaProcessManager] Ollama will bind on port 32987 when booted.
`
I'm running Ubuntu 23.10
I'm using OpenAI for LLM and embedding..

I also have a Mac and it works fine there.
I have no Xenova and I'm not sure why it's asking about Ollama..

When I ping the server it returns `{"online":true}`

**Comment by timothycarambat** [comment]
This is a client side issue with how your OS runs AppImages and not in scope of our software
```
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
```

This is where you should begin looking but this is most likely related to your FUSE installation version, or lack thereof
https://github.com/AppImage/AppImageKit/wiki/FUSE
