### ISSUE TITLE
Question: What is answerKey in the Anthropic index.js file

### ISSUE THREAD

**Issue by wallartup** [Mintplex-Labs/anything-llm#1096]
### What happened?

Trying to figure out what the Answer Key does as no other LLM requires it. What is the functionality of it? Can't find anything in the anthropic documentation.

### Are there known steps to reproduce?

Go to the index file in Anthropic

**Comment by timothycarambat** [comment]
It can be removed. When Anthropic first had their API available there was no "chat completion" only "completion" so one clever workaround was using a dynamic answer key so that you could easily parse the response.

eg:
Prompt
```
<prompt>hello model, I'm asking my question...</prompt>
<context><context>
<ai> response</ai>
<user>user text</user>
.....

Reply would go here and you would just need to "grep" it out, but what if the answer was a question about HTML? Now you have tags in tags..

A random <answerKey123> </answerkey123> would ensure that anything between those tags is what the real completion output was.

```

This can be deleted since that is no longer how their API works.
