### ISSUE TITLE
[BUG]: how to choose windows install location?

### ISSUE THREAD

**Issue by 4cecoder** [Mintplex-Labs/anything-llm#1097]
### How are you running AnythingLLM?

AnythingLLM Desktop App (Windows)

### What happened?

it just installs and doesn't ask my install path... i want to put it on D:\ Drive on windows not C:\ drive for example!

### Are there known steps to reproduce?
Just run the install file from anything llm `https://useanything.com/download`
_No response_

**Comment by timothycarambat** [comment]
Not a bug, it is intentional at this time. We may enable it in the future, but for now you can copy it to a new drive if desired and it will work the same.

**Comment by benoitrolland** [comment]
`mklink /d c:\Users\MyUser\AppData\Roaming\anythingllm-desktop\storage D:\path\on\other\drive\anythingllm-desktop\storage` did the trick for me.
