### ISSUE TITLE
[BUG]: [CollectorApi] fetch failed

### ISSUE THREAD

**Issue by help4bis** [Mintplex-Labs/anything-llm#1098]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Document processing API is no online.docoument this happens with uploading MP4 documents. 

In the log I see
-- Working Chapter6_part2_AssemblingProcess.mp4 --
[LocalWhisper] Initialized.
[LocalWhisper] File conversion required! .mp4 file detected - converting to .wav
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[LocalWhisper] Conversion Processing! 4KB converted
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[Embedding - Downloading Model Files] onnx/decoder_model_merged_quantized.onnx 0%
[Embedding - Downloading Model Files] onnx/encoder_model_quantized.onnx 1%
[CollectorApi] fetch failed

### Are there known steps to reproduce?

Upload MP4 file

**Comment by timothycarambat** [comment]
Could not download the `whisper-small` model from hugging face. Related to https://github.com/Mintplex-Labs/anything-llm/issues/821 root cause.
