### ISSUE TITLE
[BUG]: LLM Preference page blank

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1104]
### How are you running AnythingLLM?

Local development

### What happened?

If I use anythingLLM, I have no particular problems.
However, if I want to change something on the 'LLM Preference' page, it has problems.

<img width="1509" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/22151717/19f9b1bf-a447-4927-a908-e91cc96403de">

Into terminal log there isn't errors log, but into web console:

<img width="1493" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/22151717/6b221d48-b1a0-480d-adea-2444ee7fc473">

(I have already tried updating libraries and dependencies)

**Comment by timothycarambat** [comment]
You are working locally and you did not set an `LLM_PROVIDER` in the `.env` or `.env.development` (if in dev mode). In normal use of the app you would go through onboarding and that env would be set. Not a bug since this is out of process

**Comment by santini-cyber** [comment]
Thank you for that Tim! I was running into the same issue. For anyone who wants to follow my fix to a live build running in a docker container on a Linux server:
Step 1:  Connect in to anything-llm as root
docker exec -u 0 -it anything-llm /bin/bash
Step 2:  Backup .env file and add provider
cd /app/server && cp .env bak.env
cat cat >> bak.env << EOF
LLM_PROVIDER='<insert your provider here>'
EOF
Step 3: Copy backup to running
cp bak.env .env
Step 4: Exit container
Ctrl-P Ctrl-Q
Step 5:  Restart docker container
docker ps -a  
docker restart <anything-ll container id>
This worked for me.
