### ISSUE TITLE
[DOCS]: How to reset anything LLM

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1105]
### Description

Hi, it is not clear to me from the documentation (I have tried but it doesn't seem to work) how to totally reset anything LLM.

I've tried deleting and recreating the file anythingllm.db and running the prism:setup etc commands but it doesn't seem to work.

What can I do to be able to do a fresh installation of the platform? That is, starting at the very beginning of the initial setup (where it asks for logo, multiuser etc)?

**Comment by timothycarambat** [comment]
- delete `server/.env` && `cp server/.env.example .env`
- `rm -rf server/anythingllm.db && touch server/anythingllm.db && yarn prisma:reset`
