### ISSUE TITLE
[BUG]: Ollama embedding encountered no error messages, but the resulting number of vectors is 0.

### ISSUE THREAD

**Issue by FrankTseng168** [Mintplex-Labs/anything-llm#1107]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/41764310/b8e82ab5-bdc8-4847-9a1c-adca1bcb2ef5)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/41764310/176bee50-3cb3-4345-8f52-fd85b5e64926)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/41764310/b00f32a4-2c7f-4ccb-ac92-ca799a0a8af0)

### Are there known steps to reproduce?

the LLM Providers using Ollama is fine, when the Embedding Providers using Ollama generates o vectors.  On the other side, the Embedding Providers using OpenAI generates 17 vectors. 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/41764310/41efb72c-98ed-4922-a3be-08ea876f2a28)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/41764310/839f3f22-d02b-4108-8254-31b47fff9ce6)

**Comment by timothycarambat** [comment]
Unable to replicate:
- On latest ollama
- `ollama pull mxbai-embed-large`
Set up connection
<img width="1160" alt="Screenshot 2024-04-15 at 10 23 48 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/e028c353-7da0-481d-a1df-58b0f48b2aa0">

Embed new document:
<img width="1326" alt="Screenshot 2024-04-15 at 10 24 52 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/17ecd535-7d12-4d70-b499-a1a32f7f616f">

<img width="838" alt="Screenshot 2024-04-15 at 10 25 03 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/82442a1a-5b4c-4867-93ee-08d7615fa53c">

**Comment by timothycarambat** [comment]
If you have a document having this issue right now, you can link it here so we can be sure it is not document related.

**Comment by FrankTseng168** [comment]
Thank you for your reply, this problem will be solved after updating anythingllm docker image.
