### ISSUE TITLE
[BUG]: Getting error on desktop AnythingLLM error code 400

### ISSUE THREAD

**Issue by kvelland** [Mintplex-Labs/anything-llm#1108]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When I start a chat I'm getting: AnythingLLM:streaming - could not stream chat. Ollama call failed with status code 400: model is required.

I'm on M3 Mac.

### Are there known steps to reproduce?

I'm using ollama and are able to chat with that from the terminal, also it looks like it's running properly on 127.0.0.1:11434. In prefferences of Anything LLM it also looks like I'm able to connect to the Ollama.

**Comment by timothycarambat** [comment]
Looks like while the endpoint may be correct with `http://127.0.0.1:11434` that error indicates that a model was not selected. When you go to the LLM preference what model is selected in the dropdown?

**Comment by kvelland** [comment]
Thanks, actually it was selected, just restarted the service (Ollama) a couple of times and it worked.
