### ISSUE TITLE
[FEAT]: Gemini 1.5 Pro support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1109]
### What would you like to see?

https://github.com/Mintplex-Labs/anything-llm/issues/489#issuecomment-2058564050

**Comment by RahSwe** [comment]
Very exciting

**Comment by RahSwe** [comment]
What a way to end the week, big thank you Tim!Med vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.19 apr. 2024 kl. 18:00 skrev Timothy Carambat ***@***.***>:﻿
Closed #1109 as completed via #1134.
