### ISSUE TITLE
[BUG]: Embed chat does not seem to use the workspace prompt

### ISSUE THREAD

**Issue by jaschadub** [Mintplex-Labs/anything-llm#1117]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

It appears when make an embedded widget from a workspace it seems to not be using that prompt.

### Are there known steps to reproduce?

Make a workspace with some docs added to vector db.
Create a custom prompt that would be obvious when using it.
Create a embed code based on that workspace. 
Put script code in a test.html file and chat with it. 
If take same prompt and place in txt file, add and pin in documents list works.

**Comment by shatfield4** [comment]
I cannot replicate this bug. I have created a workspace and an embed tied to the workspace with a prompt that is obvious and it responds as it should in the embed and workspace. In your embed settings, do you have the Enable Prompt Override option enabled? In order to use the workspace prompt, that switch needs to be off.

**Comment by zwtesterzone** [comment]
> I cannot replicate this bug. I have created a workspace and an embed tied to the workspace with a prompt that is obvious and it responds as it should in the embed and workspace. In your embed settings, do you have the Enable Prompt Override option enabled? In order to use the workspace prompt, that switch needs to be off.

I looked through the settings and didn't see an "Enable Prompt Override" option, is that currently on the release version or is that just adjusting the Chat setting's Prompt option?

![Screenshot (118)](https://github.com/Mintplex-Labs/anything-llm/assets/164853383/f0870709-7b09-4022-a017-55314528e20d)
![Screenshot (119)](https://github.com/Mintplex-Labs/anything-llm/assets/164853383/4d902cd4-6639-44c3-8ee4-e6524aaef133)

**Comment by jaschadub** [comment]
I created new env and was unable to replicate the issue.
