### ISSUE TITLE
[FEAT]: Embedding model - LM Studio

### ISSUE THREAD

**Issue by ShadowAlyxia** [Mintplex-Labs/anything-llm#1118]
### Description

Hi!

On the readme file https://github.com/Mintplex-Labs/anything-llm/blob/master/README.md Supported Embedding models list mentions "LM Studio" but on AnythingLLM v1.4.4 (macOS) I can't see the LM Studio as the Embedding Provider.

So **Embedding model - LM Studio** is removed from AnythingLLM?

(Asking this to confirm if LM Studio is removed or not, If yes then I can Update the Readme file)

**Comment by timothycarambat** [comment]
That is a good point, it is _not_ available as an **embedder** provider. But it should be added for support:
https://lmstudio.ai/docs/text-embeddings
