### ISSUE TITLE
[BUG]: "Workspace Chat model" cannot be choosed or be empty if the provider is HuggingFace

### ISSUE THREAD

**Issue by hrchu** [Mintplex-Labs/anything-llm#1123]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/3183314/fb31e27c-2472-445e-a789-b024caff1452)

Cannot use huggingface Inference Endpoint (dedicated, paid) as model, since "Workspace Chat model" cannot be choosed or be empty if the provider is HuggingFace

### Are there known steps to reproduce?

1. setup HuggingFace in system config: LLM preference => Inference Endpoint, enter HuggingFace Inference Endpoint, HuggingFace Access Token, Model Token Limit

2. workspace setting => chat settings => choose huggingface as provider => workspace chat model list is empty => click update workspace botton shows "please select an item from list"

**Comment by Bahramks** [comment]
issue persists on 1.5.7
![image](https://github.com/Mintplex-Labs/anything-llm/assets/33008771/1a20b87d-d674-488e-9ac4-731b0348ffd6)

**Comment by timothycarambat** [comment]
@Bahramks Ollama requires a model. This issue does not persist. Pull an ollama model so the options show
