### ISSUE TITLE
Vector DB not Connecting after docker container restart

### ISSUE THREAD

**Issue by mdibiaso152** [Mintplex-Labs/anything-llm#1127]
### How are you running AnythingLLM?

Docker (local)

### What happened?

After I restarted my docker container, I was unable to upload new documents to the instance, and my old files aren't showing the UI. I am sometimes given this error:

LanceDBError: LanceError(IO): Error parsing Path "/app/server/"/app/server/storage"/lancedb": Encountered illegal character sequence """ whilst parsing path segment """

![Screen Shot 2024-04-18 at 2 32 16 PM](https://github.com/Mintplex-Labs/anything-llm/assets/165839376/b0359f44-4fa6-425c-93be-56f5ad70ca2b)

**Comment by timothycarambat** [comment]
You need to check your `STORAGE_DIR` env that is in the folder of wherever you can binding docker storage to. It seems to have two strings saved to it and it should just be `STORAGE_DIR="/app/server/storage"`
