### ISSUE TITLE
[FEAT]: Live file sync

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1129]
### What would you like to see?

As a user, I want to be able to upload some file or link and then have that content automatically be "refreshed" when changes are introduced to the original file without having to upload a new version.

Note: Due to browser limitation and security issues this may have to be invoked manually

**Comment by krishhh16** [comment]
@timothycarambat Can you assign me this issue? 
I am pretty sure I can work on this one!

**Comment by timothycarambat** [comment]
@krishhh16 this is not a trivial issue and would require a substantial amount of work and implementation across the entire system. We will reserve this for the core team
