### ISSUE TITLE
[BUG]: Could not respond to message. LanceDBError: No vector column found to create index

### ISSUE THREAD

**Issue by Ikaros-521** [Mintplex-Labs/anything-llm#1131]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

workspace ask question，return error：
```
Could not respond to message.
LanceDBError: No vector column found to create index
```

### Are there known steps to reproduce?

embedding model used local ollama，qwen1.5b

**Comment by timothycarambat** [comment]
This happens when you embed your files with some previous embedder model, and then at a later date swap the embedder model but still continue to use the previously cached files. Your query dimensions will not be congruent and this error is the result.

Un embed all documents from the workspace and even delete the existing cached documents. Then reupload and embed the documents. 

We will be adding an error message to prevent this from accidentally occurring in the future.

**Comment by Ikaros-521** [comment]
> This happens when you embed your files with some previous embedder model, and then at a later date swap the embedder model but still continue to use the previously cached files. Your query dimensions will not be congruent and this error is the result.
> 
> Un embed all documents from the workspace and even delete the existing cached documents. Then reupload and embed the documents. 
> 
> We will be adding an error message to prevent this from accidentally occurring in the future.

Thank you for the answer. It was very helpful. THX. 
Looking forward to optimization~

**Comment by rickywu** [comment]
I have the same, and tried remove and upload again,but not work
I use one embedding model and changed to another

**Comment by llwwei168** [comment]
"I'm experiencing the same issue, I've uploaded relevant documents to my workspace, and when doing RAG, this prompt appeared:"
My configuration:
LLM Provider：Ollama  
Models: qiwen2
Embedding Model Selection: qiwen2
Vector Database Provider: LnaceDB

**Comment by timothycarambat** [comment]
@llwwei168 this occurs when you changed your embedder after either inserting a single document into a workspace or have documents in a workspace and have a cached document that was embedded by a previous embedder.

Depending on which one you are effect by:
- Workspace -> Reset vector database -> then embed
- Documents -> Unembed + delete all docs and reupload and embed so you can be sure all are on the same embedder
