### ISSUE TITLE
[BUG]: Error: Unexpected token 'U', "Unauthorized" is not valid JSON

### ISSUE THREAD

**Issue by Sakura4036** [Mintplex-Labs/anything-llm#1132]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Error when adding users, unable to add new users：

![image](https://github.com/Mintplex-Labs/anything-llm/assets/42060616/ebad39dc-f01b-4515-96f5-117cfdeb7ddb)

**Comment by timothycarambat** [comment]
You likely need to log out and back in as the role you currently are on either does not allow that permission or was changed during the session
