### ISSUE TITLE
Is there a Resful api which can be used to upload PDF or textfile ? 

### ISSUE THREAD

**Issue by themoneyevo** [Mintplex-Labs/anything-llm#1144]
Is there a Resful api which can be used to upload PDF or textfile?

**Comment by timothycarambat** [comment]
Yes, on a running instance or even on Desktop you can go to "API Keys" and you can generate an API key and also view the docs and endpoints for uploading documents.

HTTP://localhost:3001/api/docs is usually the endpoint
