### ISSUE TITLE
Multi-user support for AnythingLLM instances

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#115]
Add support for the owner of an AnythingLLM instance to create sub-users who can have their own workspaces.

Sub-Users can add and use all documents in the workspace and passwords. The root account can see all workspaces, conversations, and manage workspaces. Each sub-user should have their own specific password that they can set on login.

**Comment by realnoob007** [comment]
Really need it

**Comment by timothycarambat** [comment]
@realnoob007 this feature is live and merged now.
