### ISSUE TITLE
[BUG]: Does not locate models on local ollama

### ISSUE THREAD

**Issue by fmotta** [Mintplex-Labs/anything-llm#1150]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![Untitled](https://github.com/Mintplex-Labs/anything-llm/assets/877390/753a3a98-71f2-4826-ac30-eed4e9bdae2d)
I can use ollama locally using wsl
I can access it using the URL
Yet, Anything will not present model options

**Comment by timothycarambat** [comment]
**127.0.0.1**

You have 127.0.0.0 typed in

**Comment by fmotta** [comment]
Thanks for finding that error in my report. 
I took that pic as I was trying to work around.

Here is the one with 127.0.0.1 
(I also tried localhost, the host IP, and several other things)
![Screenshot_545](https://github.com/Mintplex-Labs/anything-llm/assets/877390/b7711bc5-72c9-4e58-aff1-994043a26434)

**Comment by fmotta** [comment]
How do I reopen this?

**Comment by fmotta** [comment]
Note:
I turned off firewall as well as allowed all access for the app
