### ISSUE TITLE
[BUG]:  Embedding local ollama fails to present models available in local ollama server (see issue 1150)

### ISSUE THREAD

**Issue by fmotta** [Mintplex-Labs/anything-llm#1152]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Here is corrected picture with more information
![Screenshot_547](https://github.com/Mintplex-Labs/anything-llm/assets/877390/1802ccff-7efd-4304-b503-595804623e85)

**Comment by flefevre** [comment]
I have just tested and i do not have any problem.
I have putted in the field http://ollama:11434 , ollama is the name of my container in docker.
So for me no bug

**Comment by fmotta** [comment]
Thanks for checking.
It worked once... and only once.  When i wanted to change the model. All went wonky

If not obvious, this is windows 10/wsl2 with ubuntu.
I am using chrome browser.
A reboot and it remains.
A reinstall Anything and it remains.

**Comment by fmotta** [comment]
ollama companion sees it
![Screenshot_3](https://github.com/Mintplex-Labs/anything-llm/assets/877390/12af7458-8e37-4e20-9a5a-de10e6ed0874)

**Comment by fmotta** [comment]
OK... IMO... this may be a bug, but; that is your decision.
It worked on a different computer (same physical hardware and OS installed using 'dd' - so a clone)

Thanks for your work on this and your time

**Comment by timothycarambat** [comment]
You are using 127.0.0.1:11434 for Ollama connection but are using LocalAI as the LLM provider. Use Ollama, because LocalAI is a totally different project and their APIs are not the same.
