### ISSUE TITLE
[BUG]: desktop v1.4.4 /v1/workspace/{slug}/update-embeddings dosen't  work

### ISSUE THREAD

**Issue by themoneyevo** [Mintplex-Labs/anything-llm#1156]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I use /v1/document/upload  api to upload a file. I can see it successful both from the front view and the /v1/documents api.
But, use /v1/workspace/llama3/update-embeddings it return 
```
{
  "workspace": null
}
```
I can use /v1/workspace/llama3 to get the workspace infomation correctly.

**Comment by timothycarambat** [comment]
Good catch, patched and will be in next desktop version.

**Comment by AvaxAPS** [comment]
Hi! v1.8.1-r2 upload a file by API, works good.
/system/local-files works, shows to me all my files. 

But, use /workspace/:slug/update-embeddings dont work.

name of my workspace - "MySpc"
I tried POST /workspace/MySpc/update-embeddings, /workspace/:MySpc/update-embeddings,

{
    "adds": ["custom-documents/infollm2.txt-663067b9-fe35-4f43-9855-d65d9b39aac1.json"],
    "deletes": []
}

and I get "400 Bad Request" in all cases.
what am I doing wrong?
