### ISSUE TITLE
[FEAT]: Add New OpenAI model to Workspace Agent LLM provider and ability to enter any model name

### ISSUE THREAD

**Issue by Neoony** [Mintplex-Labs/anything-llm#1167]
### What would you like to see?

Add new OpenAI model to Workspace Agent LLM provider:
Model: gpt-4-turbo-2024-04-09

Pointer to the latest version: gpt-4-turbo

However, this needs to manually happen every time they add or update models.

Why not either grab the models list from the API, or just give ability to write any model name?
And then this is maintenance free?

Thanks!

**Comment by Neoony** [comment]
So, why is it not on the list?

v1.5.0
![https://i.imgur.com/BjbJpEv.png](https://i.imgur.com/BjbJpEv.png)

OpenAI Playground:
![https://i.imgur.com/TEtcqHq.png](https://i.imgur.com/TEtcqHq.png)

**Comment by timothycarambat** [comment]
Shows up for me

Docker
<img width="768" alt="Screenshot 2024-04-22 at 3 01 23 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/535819dd-20f2-4cc9-ac7c-4a96e41d3e1b">

Desktop 1.5
<img width="803" alt="Screenshot 2024-04-22 at 3 02 12 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/c840526c-9f6c-4a56-84b0-acd6e31791dc">

**Comment by Neoony** [comment]
in WorkSpace LLM provider, I was just using System default (using LM Studio)

If I select OpenAI there, the model shows up
![image](https://github.com/Mintplex-Labs/anything-llm/assets/24975075/2d722a1e-9c4f-4223-8301-f47c017fe642)

But if I go to the Agent Config
Its not there:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/24975075/a4a4e985-7f80-4ff9-b001-c59310b1edca)

huh?

**Comment by timothycarambat** [comment]
gpt-4-2024-04-09 does not work with tool-calling. It is intentionally omitted to prevent people from filing issues saying it is broken when it is not supported [even with OpenAI docs say it is](https://platform.openai.com/docs/guides/function-calling). We tested it explicitly, but it does not work and says that function is not available via the API.

This is where we intentionally omit it while it is unavailable: https://github.com/Mintplex-Labs/anything-llm/blob/b50f1e747908085bd12dccc94cdb8ee15353fd88/frontend/src/pages/WorkspaceSettings/AgentConfig/AgentModelSelection/index.jsx#L9

**Comment by timothycarambat** [comment]
gpt-4-turbo-preview _does_ work, for some reason.
