### ISSUE TITLE
Local LLM Support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#118]
Add support for someone to be able to use a Locally hosted LLM.

- The LocalLLM must have an API wrapper like GPT4ALL
- This will not allow an arbitrary LLM running inferences to just interact with the system, we will not be building API wrappers for LLMs.

References for easier integration:
https://docs.gpt4all.io/
[LocalAI](https://localai.io)
[Replicant](https://replicate.com/)
[OLLama](https://github.com/jmorganca/ollama)
[LLMStudio](https://github.com/h2oai/h2o-llmstudio)
[HuggingFace](https://huggingface.co)

**Comment by AntonioCiolino** [comment]
LocalAI?

**Comment by AntonioCiolino** [comment]
The moderations endpoint will need to be managed. I had to comment it out to make this work.

**Comment by CK-Daniel** [comment]
@AntonioCiolino Have you successfully managed to use LocalAI? Changing the the endpoints did the the trick? and if it does does the embbeding work?

**Comment by franzbischoff** [comment]
PR #335

**Comment by timothycarambat** [comment]
LMStudio integration is live: f499f1ba59f2e9f8be5e44c89a951e859382e005

**Comment by timothycarambat** [comment]
Supporting LMStudio and LocalAI currently - which should be enough as this time. Other providers will be their own issue.

**Comment by amorimds** [comment]
Is there any tutorial on how to set up a LocalAI Model for anything LLM? 

I was able to set up a model on LocalAI I can prompt it via cmd. But when I put the endpoint on anythingllm it never loads the model options.

**Comment by timothycarambat** [comment]
Are you running LocalAI and AnythingLLM on the same machine using Docker? @amorimds
