### ISSUE TITLE
[QUESTION] Switching Embedding Model

### ISSUE THREAD

**Issue by ShadowAlyxia** [Mintplex-Labs/anything-llm#1182]
I tried to change the Embedding Provider from **AnythingLLM Embedder** to **Ollama** and it showed me a popup with a warning **"Switching the vector database will ignore previously embedded documents and future similarity search results. They will need to be re-added to each workspace."**

I am trying to change the Embedding Provider not Vector Database so why the warning is saying **"Switching the vector database....."**

![image](https://github.com/Mintplex-Labs/anything-llm/assets/162910371/970eae2a-be18-4926-8d8c-d690b6e6a9a7)

I'm new to this so a explanation with less technical terms would be much appreciated

AnythingLLM Version - v1.5.0 (macOS Desktop App)

**Comment by timothycarambat** [comment]
Oh that is a typo, if you attempt to change your vector database _or_ embedder you are likely to have issues with already embedded content. Will fix!

**Comment by timothycarambat** [comment]
Weird it is currently correct in the main branch https://github.com/Mintplex-Labs/anything-llm/blob/ff5d7d83726f43e77257773efb9996eb653df896/frontend/src/pages/GeneralSettings/EmbeddingPreference/index.jsx#L317

But yes it is wrong in desktop!
https://github.com/Mintplex-Labs/anything-llm/blob/bf165f2ab25b873581edcacac934ebff3f429d8d/frontend/src/pages/GeneralSettings/EmbeddingPreference/index.jsx#L289

**Comment by timothycarambat** [comment]
This was patched in 1.5.1
