### ISSUE TITLE
[BUG]: Error for LLAMA 70B，but it's ok for 8B

### ISSUE THREAD

**Issue by syunjiang126** [Mintplex-Labs/anything-llm#1186]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Could not respond to message.
LanceDBError: No vector column found to create index

**Comment by timothycarambat** [comment]
You get that bug if you are trying to send a chat while using an embedder that is different from the one that you uploaded the document with.

Do not change embedder models as this impacts all workspaces and documents that were using that model. This error has nothing to do with your LLM.

For the workspace which you get the issue with, un-embed any files, delete them totally from the system, then re-upload and re-embed.
