### ISSUE TITLE
[Draft] Google Drive Support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#119]
We should add a connector for Google Drive support.

This may not be possible when running on a local instance so this needs to be specified. This may not be possible due to not HTTPS URLs or using IP based hostnames

**Comment by jignnsd** [comment]
Hey @timothycarambat is this idea going forward? 
Many thanks for this project.

**Comment by timothycarambat** [comment]
@jignnsd yes. However timeline is estimated to Mid-Nov at best. This is a rough estimate but can be done by anyone if they wanted

**Comment by timothycarambat** [comment]
Will be moving to `plugins` issue when created

**Comment by pharmacologic** [comment]
> ﻿This may not be possible when running on a local instance so this needs to be specified. This may not be possible due to not HTTPS URLs or using IP based hostnames

if a self-hosted instance has a public HTTPS URL w/ domain name, would it be expected to work then?

**Comment by timothycarambat** [comment]
@pharmacologic yes

**Comment by svliantiss** [comment]
Has this been made yet?

**Comment by TheAlex25** [comment]
Any updates @timothycarambat ? Google integration would make this a NotebookLM killer.
