### ISSUE TITLE
[FEAT]: Website scraping depth

### ISSUE THREAD

**Issue by shatfield4** [Mintplex-Labs/anything-llm#1190]
### What would you like to see?

We should create a data connector that allows scraping websites with a configurable depth

- Should scrape all `<a>` tags on the site and look for all links that match the original domain name then scrape X levels deep
- Should all be done using the existing puppeteer instance that is already used for scraping links

**Comment by flefevre** [comment]
Is there any documentation on website querying?
I have seen anythingllm is compatible with Web site but no way to find the documentation.
Thanks for the links/help
