### ISSUE TITLE
[FEAT]: change deafult answer

### ISSUE THREAD

**Issue by ELBEQQAL94** [Mintplex-Labs/anything-llm#1197]
### What would you like to see?

How to change default answer, "There is no relevant information in this workspace to answer your query."?

**Comment by timothycarambat** [comment]
It cannot be modified at this time.
Would be a configuration here 
https://github.com/Mintplex-Labs/anything-llm/blob/2e813846dca07f363af9914950526f7507292609/server/utils/chats/embed.js#L140

**Comment by ELBEQQAL94** [comment]
Thanks @timothycarambat
