### ISSUE TITLE
[FEAT]: Sort chat models

### ISSUE THREAD

**Issue by ErykCh** [Mintplex-Labs/anything-llm#1198]
### What would you like to see?

Sort model names ascending.

Currently after selecting OpenRouter it's hard to find for example Mistral 8x22B.

There are few places with Mistral.ai models:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/d81e164a-60f1-4824-95f0-9a5042e085a1)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/bd9c6de9-b550-4ead-b50e-08f5094d0e4d)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/6dee492b-57a6-485c-af91-553d5b875575)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/fa346b65-af5a-4f6f-8b89-878f38a260a4)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/5a1d7ef9-a53d-440f-84fb-562e26fc09c5)

**Comment by ErykCh** [comment]
Screenshots are from Chat Settings connected with workspace.

And model selection should be the same as it is in LLM Preference and Chat Model Selection
![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/c62607be-9b7e-4d9e-a4ee-6d94de4cd4b9)

**Comment by timothycarambat** [comment]
I dont understand where the first screenshot came from
LLM Preference in system settings
<img width="428" alt="Screenshot 2024-04-26 at 3 50 33 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/ddb8df43-08f8-42e2-ba97-aeb4b7a3d7a4">

In Chat settings per workspace
<img width="796" alt="Screenshot 2024-04-26 at 3 50 48 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/986365ce-dd91-4fdd-ae47-3fbed0740fbe">

Are you using an old version?

**Comment by ErykCh** [comment]
I'm using 1.5.0 version.

If you added this feature you can close a ticket.

**Comment by timothycarambat** [comment]
I believe we did with 1.5.1 - it was a previously know issue for OpenRouter though and should be resolved, if not please reopen!
