### ISSUE TITLE
[BUG]: Don't filter model names when OpenRouter is selected

### ISSUE THREAD

**Issue by ErykCh** [Mintplex-Labs/anything-llm#1199]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

See all models hosted by OpenRouter.

### Are there known steps to reproduce?

After selecting OpenRouter as LLM Provider I don't see all models.

I don't see for example Llama 3 models 8B or 70B.

I don't see Mixtral 8x22B.

I don't see Wizardlm2 8x22b

**Comment by ErykCh** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/b031e192-32ea-4494-a0d0-325512238930)

**Comment by timothycarambat** [comment]
I am in LLM Preference on v.1.5.1 and i see both of those models
<img width="360" alt="Screenshot 2024-04-26 at 3 53 21 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/ec0d6654-6492-44fb-95a0-eea0588cfbed">

**Comment by ErykCh** [comment]
I'm using 1.5.0

So I see that you pushed many changes in 1.5.1.

So I will close a ticket.
