### ISSUE TITLE
[BUG]: Could not respond to message. AnythingLLM:streaming - could not stream chat. Error: read ECONNRESET

### ISSUE THREAD

**Issue by niyeyedi110** [Mintplex-Labs/anything-llm#1208]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/79386975/68d2a3c6-8144-4eea-989f-5a9b7a7df162
Could not respond to message.
AnythingLLM:streaming - could not stream chat. Error: read ECONNRESET

**Comment by timothycarambat** [comment]
Please ensure `ollama serve` is running.

**Comment by josersleal** [comment]
why is this closed?
why is "ollama serve" needed,
I am using all default, so no need to run externall ollama.

however, running ollama serve on externall ollama causes:
"AnythingLLM:404: llama3.1:latest has not completed downloading. Please wait for it to complete to send a chat."

basically it deleted all the models I had downloaded from ollama lib.

**Comment by timothycarambat** [comment]
@josersleal AnythingLLM's default LLM on the desktop is totally separate from _your Ollama_. Use the external ollama LLM provider if you want to connect to your existing install. Not everyone has Ollama already installed - your models are fine.

**Comment by jlsilicon** [comment]
I have the same problem.
After spending 90 minutes installing it,
-- this is all I get.

Basically this SW is Trash.
