### ISSUE TITLE
[QUESTION]: Function Calling

### ISSUE THREAD

**Issue by shehanmkg** [Mintplex-Labs/anything-llm#1209]
### Description
I am interested in understanding whether AnythingLLM supports function calling capabilities.

### Context
- I am looking to integrate AnythingLLM with external APIs or custom functions to enhance its functionality.
- My use case involves to get some data from already implemented backend.

### Question
- Does AnythingLLM currently support function calling?
- If so, could you provide documentation or examples on how to implement this feature?
- If not, are there plans to include this feature in the future?

### Additional Information
- I am running AnythingLLM locally.
- I have checked the existing issues and did not find an answer to this question.

Thank you for your assistance.

**Comment by timothycarambat** [comment]
> Does AnythingLLM currently support function calling?
yes, but only via our built-in agent skills. We are currently working on custom agent skills. What specifically are you trying to do (general API requests, SQL, etc)

> If so, could you provide documentation or examples on how to implement this feature?
https://docs.anythingllm.com/agent/overview

**Comment by bhazzard** [comment]
I am also interested in this feature. I'd like to be able to call local code snippets so that I can expand the capability of AnythingLLM to include Calendar Management, Email Reference, and more

**Comment by timothycarambat** [comment]
Can be done with custom skills via: https://github.com/Mintplex-Labs/anything-llm/pull/2202
