### ISSUE TITLE
Support Image Uploading

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#121]
The document processor should support the uploading and embedding of images like PNG, JPEG, and other static formats.

Ideally, this should describe the image and return that text for embedding instead of trying to do a multi-modal embedding which will be impossible to search textually over.

**Comment by AntonioCiolino** [comment]
Are you thinking that it should use something like a  BERT or Deepdanbooru to extract info from?

**Comment by timothycarambat** [comment]
> Are you thinking that it should use something like a BERT or Deepdanbooru to extract info from?

Both of these would be an issue to run locally since they require some big resources. Deepdanbooru is also specific to anime-girls image tagging and tends to give more NSFW results so honestly easiest implementation is just using something simple like OpenAIs CLIP which can run on replicate pretty easily (but will still cost money)

**Comment by AntonioCiolino** [comment]
If you are calling out to external resources, there’s lots of choices of course.

**Comment by phicha20224** [comment]
it return anythingllm File extension .jpg not supported for parsing and cannot be assumed as text file type.

**Comment by timothycarambat** [comment]
@phicha20224 - that is because we dont support uploading images right now

**Comment by timothycarambat** [comment]
@phicha20224 - that is because we dont support uploading images right now

**Comment by rainbowkode** [comment]
what i need to do for the support on images?
