### ISSUE TITLE
[FEAT]: Ability to copy message text sent by user.

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1210]
### What would you like to see?

This is possible to do with the clipboard icon on responses from the LLM, but not from users. What if I want to copy what I previously sent to the LLM easily and quickly and paste that back into a message to avoid context overflow? Not sure why that button wouldn’t be included on all messages. 

Also it is impossible to highlight text and click it to copy. Why is that?

**Comment by atljoseph** [comment]
Gotta be honest. This is a MAJOR annoyance for me. Copy/paste won’t work, and there isn’t a button to copy. This would be so simple to implement that it’s crazy.

**Comment by timothycarambat** [comment]
The "reason" for that oddity in behavior is that we basically wrap the `master` branch, which ships as docker, in an Electron app. Electron _does not ship_ with a context-menu built in. So you have to build this back in manually, whereas in a browser the right-click context menu is just a native thing - so nothing to do!

So really, this is just a thing that should be added for the desktop app specifically, along with spellcheck!

**Comment by timothycarambat** [comment]
I will say though, your second comment reads as non-constructive to "requesting" for a feature. We are balancing many features and other chunks of work and while you are clearly passionate about using the product, which we appreciate, this is not a place to vent and maybe the intended tone was lost in the text.

> This would be so simple to implement that it’s crazy.
I don't even know what to say to this tbh.

**Comment by timothycarambat** [comment]
Just added to desktop, will be released in the next desktop version. This is a non-issue in Docker/browser env.
