### ISSUE TITLE
[BUG]: When pasting in Python code, thinks Agent Session is needed. Fails asking for OpenAI key. 

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1211]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Error when sending message containing copy/pasted code that was generated in same chat session.

![IMG_1734](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/e3cb4182-e739-454a-abbf-a294abccef57)

### Are there known steps to reproduce?

Reliably, every time a paste in this python code, there is an error about an OpenAI API key. I’m connected locally to Ollama. I’m not trying to connect to OpenAI. I’m not sure where that’s coming from in your app. Got to this situation by simply copying output, the LLM generated and asking it a question. Without fail it always has this error. Folks should be able to take code generated and paste it back in and ask questions about it without running into random errors.

**Comment by timothycarambat** [comment]
regression of https://github.com/Mintplex-Labs/anything-llm/issues/1151
