### ISSUE TITLE
[BUG]: Styles of Embed Chat Widget Are Conflicting with Website Styles

### ISSUE THREAD

**Issue by vdamov** [Mintplex-Labs/anything-llm#1213]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

The embedded chat widget's CSS styles are conflicting with the existing styles on our website, leading to display and layout issues. To resolve this, we suggest making the widget's CSS selectors more specific to prevent them from overriding the website's global styles. This adjustment will help ensure that both the widget and the website maintain their intended visual presentation without interference.

### Are there known steps to reproduce?

Just follow the regular installation instructions for embed chatbot widget from the documentation.

**Comment by timothycarambat** [comment]
This is a known issue right now. Tracking it on #919
