### ISSUE TITLE
[FEAT] Implement Width and Height Resizing Options for Embed Chat Widget

### ISSUE THREAD

**Issue by vdamov** [Mintplex-Labs/anything-llm#1214]
### What would you like to see?

The chat widget is currently overlapping with a fixed header (z-index: 99) on 720p resolutions and mobile devices. To address this issue, I propose adding functionality to adjust the width and height of the chat widget. This feature would allow users to customize the widget size to better fit their specific layout needs without interference from other page elements.

**Comment by krishhh16** [comment]
Hey @timothycarambat 
Please assign me this issue

**Comment by stagezero-42** [comment]
I would add font size to this as well, mainly an issue on mobile devices but useful for tweaking the look on desktop as well.

**Comment by timothycarambat** [comment]
@shatfield4 lets do dimensions + font
dimensions are `data-` attribs
font is user setting
