### ISSUE TITLE
[BUG]: Unable to call model through Ollama

### ISSUE THREAD

**Issue by hcl27** [Mintplex-Labs/anything-llm#1215]
### How are you running AnythingLLM?

Docker (local)

###  Local deployment of ollama  +  anythinglm (Docker)
![bug1](https://github.com/Mintplex-Labs/anything-llm/assets/168281399/ee0cc0f8-17c8-406c-974a-0b67f23364d8)
I tried the following settings, but it still shows:
127.0.0.1:11434
172.17.0.1:11434
localhost:11434
host.docker.interal:11434

ollama serve      ollama normal operation

Who can help me solve this problem? Thank you very much

**Comment by vdamov** [comment]
Do you have docker instance of Ollama server with the default port running on your machine ?

**Comment by timothycarambat** [comment]
I am assuming you have `ollama serve` running on the host? Also which operating system as `host.docker.internal` does not work on Linux Docker, if that is the case. Otherwise, you should be fine.

The only other caveat is Docker on Windows trying to communicate with Ollama running on WSL. WSL does not allow the connection to bridge.

**Comment by hcl27** [comment]
> Do you have docker instance of Ollama server with the default port running on your machine ?

Sorry, I may not have expressed it accurately.
Ollama runs locally on the server, not on Docker,
Anything llm runs on Docker
Curl http://127.0.0.1:11434 Display Ollama is running

**Comment by hcl27** [comment]
> I am assuming you have `ollama serve` running on the host? Also which operating system as `host.docker.internal` does not work on Linux Docker, if that is the case. Otherwise, you should be fine.
> 
> The only other caveat is Docker on Windows trying to communicate with Ollama running on WSL. WSL does not allow the connection to bridge.

yes，Ollama runs on host, and the local system is Ubuntu.

**Comment by timothycarambat** [comment]
Where are you running Ollama? On the same server as AnythingLLM? If so what operating system

**Comment by mmsrubar** [comment]
Hi, I was having the very same issue. The problem for me was that the docker container was trying to connect to docker interface IP address when using http://host.docker.internal:11434 and ollama was listening on 127.0.0.1:11434 (localhost) on the host. So I think the solution is either to configure the ollama to listen also on the docker IP or use for example socat to redirect all packets from 172.17.0.1:11434  to 127.0.0.1:11434 where 172.17.0.1 was IP of my docker0 interface.

socat TCP4-LISTEN:11434,bind=172.17.0.1,fork TCP4:127.0.0.1:11434

**Comment by timothycarambat** [comment]
Additionally, Linux does not support `host.docker.internal` as I mentioned previously and there is already a doc for this
https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/ollama/README.md#common-issues-with-ollama

**Comment by hcl27** [comment]
> Hi, I was having the very same issue. The problem for me was that the docker container was trying to connect to docker interface IP address when using http://host.docker.internal:11434 and ollama was listening on 127.0.0.1:11434 (localhost) on the host. So I think the solution is either to configure the ollama to listen also on the docker IP or use for example socat to redirect all packets from 172.17.0.1:11434 to 127.0.0.1:11434 where 172.17.0.1 was IP of my docker0 interface.
> 
> socat TCP4-LISTEN:11434,bind=172.17.0.1,fork TCP4:127.0.0.1:11434

Thank you very much. I'll give it a try

**Comment by hcl27** [comment]
> Hi, I was having the very same issue. The problem for me was that the docker container was trying to connect to docker interface IP address when using http://host.docker.internal:11434 and ollama was listening on 127.0.0.1:11434 (localhost) on the host. So I think the solution is either to configure the ollama to listen also on the docker IP or use for example socat to redirect all packets from 172.17.0.1:11434 to 127.0.0.1:11434 where 172.17.0.1 was IP of my docker0 interface.
> 
> socat TCP4-LISTEN:11434,bind=172.17.0.1,fork TCP4:127.0.0.1:11434

Thank you very much. I'll give it a try

**Comment by hcl27** [comment]
> Additionally, Linux does not support `host.docker.internal` as I mentioned previously and there is already a doc for this https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/ollama/README.md#common-issues-with-ollama

Thank you for your help. Based on the documentation you provided, I have resolved this issue
