### ISSUE TITLE
[FEAT]: Add "Deep Import" Option to GitHub Repo Data Connector

### ISSUE THREAD

**Issue by vdamov** [Mintplex-Labs/anything-llm#1217]
### What would you like to see?

When utilizing the GitHub Repo Data Connector, it currently only retrieves files from the top directory, without mirroring the nested folder structure or including the files contained within these folders. I propose the introduction of a "deep import" checkbox. This would provide users with the option to include the entire directory structure and all nested files in their imports.

**Comment by timothycarambat** [comment]
Please refer to https://github.com/Mintplex-Labs/anything-llm/issues/1165#issuecomment-2070854014 for why only top-level files are being referred to.
