### ISSUE TITLE
[BUG]: Options in Agent Configuration are disabled

### ISSUE THREAD

**Issue by maxdraki** [Mintplex-Labs/anything-llm#1219]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Some options in agent configuration are disabled. I can't find any documentation so am not sure if this is expected or not. I tried searching for news and the agent said it was scraping BBC website, it then said it was a long site and it was going to summarise and then returned saying it didn't have current information.. I then noticed that options like 'View & summarize documents' and 'Scrape websites' were actually disabled..
Is this expected?
![image](https://github.com/Mintplex-Labs/anything-llm/assets/3703338/629db629-0fc1-4b18-9906-cbe9379be9c5)

**Comment by timothycarambat** [comment]
Those skills are enabled by default because they are what people typically "expect" it to be able to do at a minimum. We have yet to write all the docs for agents  on https://github.com/Mintplex-Labs/anythingllm-docs
