### ISSUE TITLE
[QUESTION]: Cannot boot with docker

### ISSUE THREAD

**Issue by krishhh16** [Mintplex-Labs/anything-llm#1221]
### How are you running AnythingLLM?

Docker (local)

### What happened?

i am not seeing the website up and running after  docker-compose up -d --build is completed at localhost:3001

### Are there known steps to reproduce?

go to docker folder, copy .env.example to .env, changing the environment variables

And then running  docker-compose up -d --build

**Comment by timothycarambat** [comment]
What are the logs you see for why the container can not boot? Are the ports already in use?
