### ISSUE TITLE
[BUG]: Windows, Can't change the Chat mode, update error

### ISSUE THREAD

**Issue by la2yyu** [Mintplex-Labs/anything-llm#1222]
### How are you running AnythingLLM?

Local development

### What happened?

SYSTEM：Windows server 2022

When I try to change the workspace chat mode, then AnythingLLM send the warning about prisma.workspaces.update()
![25A172CA-1620-4ec5-8B0C-8D0AFB2D4F73](https://github.com/Mintplex-Labs/anything-llm/assets/44995781/8db5a282-af25-4cc2-a9ba-eae75d09c66c)

**Comment by timothycarambat** [comment]
`yarn prisma:migrate` and `yarn prisma:generate` from the root of the repo/

**Comment by la2yyu** [comment]
> `yarn prisma:migrate` and `yarn prisma:generate` from the root of the repo/

sorry, I cant understand

**Comment by 13829386012** [comment]
> > `yarn prisma:migrate` and `yarn prisma:generate` from the root of the repo/
> 
> sorry, I cant understand

请问你解决这个问题了吗？

**Comment by la2yyu** [comment]
> > > `yarn prisma:migrate` and `yarn prisma:generate` from the root of the repo/
> > 
> > 
> > sorry, I cant understand
> 
> 请问你解决这个问题了吗？

没有，我不能理解作者的回复

**Comment by wood001** [comment]
@la2yyu  Uninstall app completely. Reinstall anythingllm, and make sure anythingllm can access network when you first startup anythingllm.

**Comment by la2yyu** [comment]
> @la2yyu Uninstall app completely. Reinstall anythingllm, and make sure anythingllm can access network when you first startup anythingllm.

not work, but there is no this issue in the lastest version of anythingllm
