### ISSUE TITLE
[DOCS]: Have I overlooked the relationship in Document-Folder-Workspace-User in the document?

### ISSUE THREAD

**Issue by cuihee** [Mintplex-Labs/anything-llm#1223]
### Description

https://docs.useanything.com/

There are four concepts that I am not very clear about： Document Folder Workspace User

I guess One User has Some Workspaces, One Workspace has Some Folders, One Folder has Some Documents?
Is that true? How to manage(CRUD) them?

**Comment by timothycarambat** [comment]
Workspaces have a user _or_ users. Each workspace has embedded documents. The file system is outside of all of those objects and is just showing you what is in `storage/custom-documents`

**Comment by cuihee** [comment]
> Workspaces have a user _or_ users. Each workspace has embedded documents. The file system is outside of all of those objects and is just showing you what is in `storage/custom-documents`

Thanks a lot. "Workspaces " maybe the key concept.
