### ISSUE TITLE
How to access embeddings within database?

### ISSUE THREAD

**Issue by abcnow** [Mintplex-Labs/anything-llm#1232]
### What would you like to see?

I have been trying for a few days to retrieve/access embeddings on database without success.. I wonder what's the best way to accomplish this?

**Comment by timothycarambat** [comment]
Which vector database are you using?

**Comment by abcnow** [comment]
I am using "lancedb" and "chroma" (on 2 different macbook pros)..

**Comment by abcnow** [comment]
I got it man.. it was under my ac/library/Application Support/anythingllm-desktop/storage
