### ISSUE TITLE
[BUG]: ErrorCode: IllegalArgument. Reason: Invalid collection name: 2794eac1_66e6_4072_886f_32418c75e130. the first character of a collection name must be an underscore or letter: invalid parameter

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#1235]
### How are you running AnythingLLM?

Local development

### What happened?

If the workspace is in Chinese, when selecting Milvus as the vector database and choosing file embedding, the following error is prompted.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/c64bc955-334f-4b1c-b4af-4960bfef4b7b)

**Comment by timothycarambat** [comment]
Are you on an old version, this was patched a long time ago
https://github.com/Mintplex-Labs/anything-llm/commit/718062d0333dff1c8266183c24e755f424f9ccd7
