### ISSUE TITLE
[BUG]: 回答的答案一直重複

### ISSUE THREAD

**Issue by ddimit2020** [Mintplex-Labs/anything-llm#1236]
### How are you running AnythingLLM?

Docker (local)

### What happened?

不知道為何,我詢問不同的問題,但都回答相同的答案
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/503633b8-ebde-4e5d-8b4b-4f28df7067c1)

另外我有upload共四份文件,但為何回答之後總只能看到兩份文件?
這是再workspace的詢問的文件只看到兩個
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/02b8eda9-551a-4893-83a0-7237975f93bc)

但實際上有四份文件我再測試
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/06e020e9-1eb5-4487-be26-693ceeda3b01)

p.s.我試過重啟dokcer-compose up -d了,也將文檔pin了

並且有時會出現cloud noy stream chat
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/46be2412-5922-4238-8c73-71e089c5c610)

是有什麼我miss_config or 需要修正的地方嗎?

**Comment by jingnorth** [comment]
同样的问题，workspace的詢問的文件是否是与回答相关的文档，其它embed的文件不显示。
另外文件embed选取系统自带和其他选择比如Ollama,虽然分割字数设置的不同，但是基本都是1000字符以内，没有变化
准确性如何提高，目前只能试不同提示词

**Comment by timothycarambat** [comment]
https://docs.useanything.com/faq/why-is-llm-not-using-docs
