### ISSUE TITLE
[FEAT]: Ollama Agent support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1242]
### What would you like to see?

Add support for agents when using `Ollama` (or built-in AnythingLLM LLM on desktop)

**Comment by masonjames** [comment]
Have you used the Desktop app? You can download it. Go to Settings>LLM Preferences and under LLM Provider choose Ollama.

From there you point to the base URL (typically http://127.0.0.1:11434) and choose your model.

**Comment by timothycarambat** [comment]
yes i know, i built the app 👍
