### ISSUE TITLE
[FEAT]: Slash `/` templates

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1245]
### What would you like to see?

A user should be able to define a custom `/` command that can be invoked in the chat and will be automatically "expanded" during inferencing.

**Comment by mptyl** [comment]
My suggestion is to implement the same functionality that you find in Open WebUi when you digit a /. A list of prompts, "names," appears. If you choose one of them, the content of the associated file—a text—is put into the user window, filling in the prompt. 

So what could be implemented are:
a CRUD for creating, editing, and delating a text file (saved in a local database, I suppose, using sqllite, postgresql, or mongodb). The file could be "pointed" by a record in a table where the name and description of the file could be used to select the text to be used.
a "filter" on the character "/" in the prompt. When a / is intercepted, the application should propose a list of the saved prompts, waiting for a selection. The selection event should fill the prompt window with the text present in the pointed file, as it is. It's user's responsibility to engineer the right prompt to be queried. The file can even include a short "command" to be executed.

Marco Pancotti (from Italy)

**Comment by DaCeige** [comment]
+1
