### ISSUE TITLE
[FEAT]: "White label" possibility

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1256]
### What would you like to see?

An option to white label an ALLM instance:

1. Remove ALLM references on login screen (instead using the custom logo)
2. Remove ALLM buttons on the bottom of the workspace field

**Comment by timothycarambat** [comment]
> Remove ALLM buttons on the bottom of the workspace field

Where is this?

**Comment by RahSwe** [comment]
Here (could for example be viewable only for administrators)

<img width="166" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/9942e737-2e77-4640-b8f3-15bb4a8ba773">

**Comment by timothycarambat** [comment]
Footer icons are already customizable
<img width="1228" alt="Screenshot 2024-05-01 at 4 52 55 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/632186bb-4b48-4a40-accd-01b7939021f2">

The login screen icon is for sure a regression, we need to add the custom logo back to the screen like it used to work

**Comment by RahSwe** [comment]
Sorry, did not realize you could remove them by those options, will try out

**Comment by RahSwe** [comment]
Edit: I can not remove them completely but can add another icons and other links. Would be nice to have the option to remove them by setting a blank/unpressable button instead of the standard or such, to avoid having to use dummy links

**Comment by timothycarambat** [comment]
Moving this to https://github.com/Mintplex-Labs/anything-llm/issues/1373
