### ISSUE TITLE
[BUG]: Websocket not being upgraded with manual HTTP certificate set

### ISSUE THREAD

**Issue by man2004** [Mintplex-Labs/anything-llm#1257]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

When I typed @agent to launch it, it showed following and the agent session ended immediately:

```
Agent @agent invoked.
Swapping over to agent chat. Type /exit to exit agent execution loop early.

Agent session complete.
```

I am using docker image I pulled today.

**Comment by man2004** [comment]
I have just found it might be because of SSL. With same docker image, after I enabled SSL and accessed with https://domain_name, then agent ended immediately. If I disabled SSL and accessed with http://ip_address, then agent worked.

**Comment by timothycarambat** [comment]
Relevant line where if on https, we assume the backend has SSL as well so we upgrade WS to WSS
https://github.com/Mintplex-Labs/anything-llm/blob/9feaad79cc69c826001b36d0e129da403a695d23/frontend/src/utils/chat/agent.js#L18

If using nginx as a proxy
https://github.com/Mintplex-Labs/anything-llm/blob/9feaad79cc69c826001b36d0e129da403a695d23/cloud-deployments/aws/cloudformation/aws_https_instructions.md?plain=1#L68-L73

**Comment by man2004** [comment]
Thanks. I originally used the SSL feature in AnythingLLM and did not use nginx as proxy. After changing to use nginx as proxy, problem solved.

**Comment by Anto79-ops** [comment]
I'm also experiecing the same because I have AnythingLLM using https: to server with these lines in my `.env` file

```
ENABLE_HTTPS='true'
HTTPS_CERT_PATH='path to/server.crt'
HTTPS_KEY_PATH='path to /docker$
```
I'd rather not remove the `https` encryption. Is there a workaround? thanks

**Comment by timothycarambat** [comment]
When you have the network inspector open, can you tell me what happens to the socket and what URL it tries to reach?
If the frontend is running https it should upgrade the socket to `wss` automatically

**Comment by Anto79-ops** [comment]
sure, I'd be happy to share that. When expanding the netwrok information in Chrome, what would you like to me expand here?
 
 ![image](https://github.com/Mintplex-Labs/anything-llm/assets/79593761/69b64564-f740-4887-a414-54e17568244b)


also, here's the error from Chrome, it does open `wss`

![image](https://github.com/Mintplex-Labs/anything-llm/assets/79593761/878872ec-b267-4097-be0d-03506a8f6638)

**Comment by timothycarambat** [comment]
Okay, so it looks like it does upgrade the Websocket connection. What do the docker logs say on the backend when the agent is invoked - if anything? Im thinking maybe the websocket does not inherit the SSL cert like the whole express server does.

**Comment by Anto79-ops** [comment]
That is correct. The docker logs do not say anything while all this is happening.

**Comment by timothycarambat** [comment]
Resolved via https://github.com/Mintplex-Labs/anything-llm/pull/1429
