### ISSUE TITLE
[FEAT]: Retain failed upload information

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1258]
### What would you like to see?

In the upload window, successful uploads are now removed when finished which is an improvement.
However, failed uploads are also removed, making it harder to identify which files need to be re-uploaded when doing batch uploads.

**Comment by timothycarambat** [comment]
Wont be fixing this, its an endless request queue back and forth on people not knowing you can upload documents when that modal is filled and wanting everything gone or keeping it there. We are finished iterating on it now

**Comment by RahSwe** [comment]
I understand =)
I have been meddling with new upload and it works pretty efficiently if you limit batch uploads to the max amount of files shown at once in the upload window (6). A UX improvement could possibly be to adjust the upload window to the screen, not capped, so you can see more uploads in parallel without scrolling to catch failed uploads.
