### ISSUE TITLE
[BUG]: Citations not reflecting custom sized embedding

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1259]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Having started a fresh instance of ALLM and setting the custom chunk size to 800 tokens, the citations shown are much shorter than the actual vector size. As an example:

<img width="626" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/3eec075f-e798-4171-98e7-3579ea166da4">

### Are there known steps to reproduce?

See above

**Comment by Propheticus** [comment]
It's unexpected, but the chunk length value is in characters not in tokens. So it smaller by a factor 3 to 4.

**Comment by timothycarambat** [comment]
@Propheticus is correct, the spit size is by chars, not tokens. This is actually intentional and known as counting tokens depends on the tokenizer of the model, which we cannot really replicate since we only have access to the tokenizer that comes with `tiktoken` and the reason we dont rely on that is that it can be expensive to calculate for each embedding.

I do think though we are at a point where we can probably rely on that library more as we for sure "underestimate" the token length since we count by chars, which is indeed off by some factor depending on tokenizer

**Comment by RahSwe** [comment]
@Propheticus @timothycarambat 

Wouldn’t it then make sense to to change the spit size to characters x 3 or such? If it cannoy exactly match the chunk it would be better to be closer to the chunk size rather than being much too small.

**Comment by RahSwe** [comment]
@Propheticus @timothycarambat 

Further testing, it seems that something is off:

* I increased the chunk size from 800 characters to 4 000 characters (using OpenAI embedding model and LanceDB).
* I then deleted all vectors using the workspace option
* I then made new vectors
* I then made test queries. The citations show numbers of characters in the range 700-900 characters.

**Comment by RahSwe** [comment]
@Propheticus @timothycarambat 

Further testing:
* I tried not only resetting the workspace vector database but also **deleting all the files**, **re-upload the files** and then embed.
* I now get chunks and citations approximately corresponding to the custom chunk size. However it is not exactly corresponding to the 4 000 character setting, as an example:

<img width="605" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/7a08d579-1e0a-47eb-883d-761515e7bc14">

**Comment by timothycarambat** [comment]
This is due to the "Overlap" setting, that is why you are short of the total amount

**Comment by RahSwe** [comment]
Hi Tim,
I think the reason was that LangChain creates chunks of equal sizes, which means that the chunk size will rarely correspond to the exakt chunk size applied (then the last chunk would differ a lot).
This is probably more noticeable when using larger chunks but nevertheless is not a bug but a mathematical necessity.
