### ISSUE TITLE
[FEAT]: Add search bar and sort for documents 

### ISSUE THREAD

**Issue by Milor123** [Mintplex-Labs/anything-llm#1263]
### What would you like to see?

Hello everyone, how are you doing?

Before anything else, I just wanted to express my heartfelt gratitude for your amazing work.

However, I’m having a problem that’s been bothering me every time I need to use the documents.

I’m unable to click and sort them by date or name, nor do I have a search box. Many of my documents have long names, and searching for them is quite frustrating.

![Screenshot_20240502_075332](https://github.com/Mintplex-Labs/anything-llm/assets/14153649/9d3589d2-b557-4ccb-b35e-f310d29ea3ad)

Thank u very much guys !

**Comment by JawHawk** [comment]
@timothycarambat @shatfield4 Can you please assign me ? I want to work on this

**Comment by Milor123** [comment]
@timothycarambat bro, is not completed really, it new feature not work well, 

try search "skip" in search bar, but not found the file, nothing related
![image](https://github.com/Mintplex-Labs/anything-llm/assets/14153649/1ad52982-a4f2-4d99-b7ce-650fc9fa2581)

The file exits here
![image](https://github.com/Mintplex-Labs/anything-llm/assets/14153649/ae093fe1-dacd-4757-a2cf-01178e793b45)
