### ISSUE TITLE
[FEAT]: Add fast delete for chat

### ISSUE THREAD

**Issue by Milor123** [Mintplex-Labs/anything-llm#1264]
### What would you like to see?

Hi again guys !!!

The other problem I’m facing is that AnythingLLM fills up with threads, many threads, and it takes me too long to delete them.

For example, in LMSTUDIO, they solve this issue by allowing the user to delete the chat without confirmation by pressing Ctrl+Click on an X. I think that would be a good way to quickly delete chats safely, or also a checkbox where I can select them by workspace.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/14153649/4ba660b8-ef3a-440e-b569-6f1640ebb3ca)

I propose a bulk deletion using hotkeys and also the option to quickly select with checkboxes and the Shift button.

Thank you very much!

**Comment by imtiazmehmood** [comment]
I have created a pull request for a new feature addition: fast chat deletion. Attached is a screenshot showcasing the feature.
![Cadapture](https://github.com/Mintplex-Labs/anything-llm/assets/116969564/883202c1-9a4c-4891-ab3c-f31d8aaabc06)

**Comment by Milor123** [comment]
> I have created a pull request for a new feature addition: fast chat deletion. Attached is a screenshot showcasing the feature. ![Cadapture](https://private-user-images.githubusercontent.com/116969564/328668088-883202c1-9a4c-4891-ab3c-f31d8aaabc06.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMTQ1NDMsIm5iZiI6MTcxNTExNDI0MywicGF0aCI6Ii8xMTY5Njk1NjQvMzI4NjY4MDg4LTg4MzIwMmMxLTlhNGMtNDg5MS1hYjNjLWYzMWQ4YWFhYmMwNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QyMDM3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTE1ZmUwYzc4YmQ3MTI1MTk4ZTY2YjE1NzgzNDJkMDE3YmIwZmMzOTlhZGNhOTg4NzhiMDcxODc4NDJkOTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kKlwwe4giKRz4v671zUf9GVus_anvhX8wxlyT85SLJ4)

Ohhh Greaaaat !!! It will be useful, thank u very much bro !

**Comment by aikidovation** [comment]
This is great but I can't find anything in the documentation that describes how to invoke this mass-delete mode!

**Comment by timothycarambat** [comment]
Hold CMD (or CTRL on windows) and hover over the threads and the mass delete "X" appears next to each thread. @aikidovation

**Comment by aikidovation** [comment]
> Hold CMD (or CTRL on windows) and hover over the threads and the mass delete "X" appears next to each thread. [@aikidovation](https://github.com/aikidovation)

Oh that's too easy.  Thank you!
