### ISSUE TITLE
[BUG]: Docker Compose crashes on getting response or opening workspace settings

### ISSUE THREAD

**Issue by iFloris** [Mintplex-Labs/anything-llm#1265]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Since a few days my docker compose AnythingLLM setup crashes, whenever I ask for an LLM response in a thread or open workspace settings.

The following is shown in the docker logs:
anythingllm-1  | /usr/local/bin/docker-entrypoint.sh: line 7:   164 Illegal instruction     (core dumped) node /app/server/index.js
anythingllm-1 exited with code 0

Docker compose restarts the container, but it keeps happening.
I use groq, but it also happens when connected to a local ollama.

What did I do to break things?

### Are there known steps to reproduce?

This happens when I ask for any response in a thread or when I open workspace settings (url/workspace/workspace-name/settings/general-appearance).

**Comment by timothycarambat** [comment]
What does your docker-compose look like? This seems like some directory or something is being mounted that should not be. Likely some library that should exist but isn't?

**Comment by timothycarambat** [comment]
This has been reported before and this was the case [https://stackoverflow.com/a/42159385](see this SO comment)

**Comment by timothycarambat** [comment]
No that seems correct to me. Are you building on and ARM device? I think by default, unless specified, docker compose will build in compatibility mode, but since our dockerfile supports both arch's it should enable autodetection.

What chip arch are you on?

**Comment by iFloris** [comment]
Hello @timothycarambat this is on a Xeon server.

**Comment by timothycarambat** [comment]
Then that makes sense, Xeon is x86, not arm so it makes sense to only build for amd64

**Comment by iFloris** [comment]
So this is interesting, I copied my (original, simple) docker compose file to another server and AnythingLLM works there.
The difference:

This currently works:
```
OS: Debian GNU/Linux 10 (buster) x86_64
Host: KVM RHEL-8.6.0 PC (Q35 + ICH9, 2009)
CPU: Intel Xeon Silver 4216 (24) @ 2.099GHz
Memory: 10240MiB / 257696 MiB
Docker Compose version v2.27.0
Docker version 26.1.1, build 4cf5afa
```

This does not:
```
OS: Proxmox VE 8.2.2 x86_64
Host: BANFF12 [baremetal]
CPU: Intel Xeon E5-2670 0 (64) @ 2.600GHz
Memory: 92153MiB / 257572 MiB
Docker Compose version v2.27.0
Docker version 26.1.1, build 4cf5afa
```

**Comment by timothycarambat** [comment]
While i cant nail down exactly why this occurs i can say that we have had issues reported with Proxmox before, but i dont have that system available to us so i cannot replicate to debug remotely, but i recall is was either permissions or port related

**Comment by sbrosl** [comment]
Hi Tim,

I am also experiencing this issue in a VM but using Hyper-V. This showed up when I pulled the :latest docker image two days ago. I don't build the project just use the image. I tried removing the /app/server/storage volume from the docker-compose file to be sure its not my folder giving permission issues and the issue persist with that being freshly populated by the image.

I've turned on debug logging for node, here are the last lines before the error

```
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/apache-arrow"]
anything-llm  | MODULE 102: Module._load REQUEST ./util/buffer.js parent: /app/server/node_modules/apache-arrow/Arrow.js
anything-llm  | MODULE 102: RELATIVE: requested: ./util/buffer.js from parent.id /app/server/node_modules/apache-arrow/Arrow.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/apache-arrow"]
anything-llm  | MODULE 102: Module._load REQUEST ./util/vector.js parent: /app/server/node_modules/apache-arrow/Arrow.js
anything-llm  | MODULE 102: Module._load REQUEST ./util/pretty.js parent: /app/server/node_modules/apache-arrow/Arrow.js
anything-llm  | MODULE 102: RELATIVE: requested: ./util/pretty.js from parent.id /app/server/node_modules/apache-arrow/Arrow.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/apache-arrow"]
anything-llm  | MODULE 102: Module._load REQUEST ./visitor/typecomparator.js parent: /app/server/node_modules/apache-arrow/Arrow.js
anything-llm  | MODULE 102: Module._load REQUEST ./Arrow.js parent: /app/server/node_modules/apache-arrow/Arrow.dom.js
anything-llm  | MODULE 102: Module._load REQUEST ./arrow parent: /app/server/node_modules/vectordb/dist/index.js
anything-llm  | MODULE 102: RELATIVE: requested: ./arrow from parent.id /app/server/node_modules/vectordb/dist/index.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/vectordb/dist"]
anything-llm  | MODULE 102: load "/app/server/node_modules/vectordb/dist/arrow.js" for module "/app/server/node_modules/vectordb/dist/arrow.js"
anything-llm  | MODULE 102: Module._load REQUEST apache-arrow parent: /app/server/node_modules/vectordb/dist/arrow.js
anything-llm  | MODULE 102: Module._load REQUEST ./remote parent: /app/server/node_modules/vectordb/dist/index.js
anything-llm  | MODULE 102: RELATIVE: requested: ./remote from parent.id /app/server/node_modules/vectordb/dist/index.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/vectordb/dist"]
anything-llm  | MODULE 102: load "/app/server/node_modules/vectordb/dist/remote/index.js" for module "/app/server/node_modules/vectordb/dist/remote/index.js"
anything-llm  | MODULE 102: Module._load REQUEST ../index parent: /app/server/node_modules/vectordb/dist/remote/index.js
anything-llm  | MODULE 102: RELATIVE: requested: ../index from parent.id /app/server/node_modules/vectordb/dist/remote/index.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/vectordb/dist/remote"]
anything-llm  | MODULE 102: Module._load REQUEST ../query parent: /app/server/node_modules/vectordb/dist/remote/index.js
anything-llm  | MODULE 102: RELATIVE: requested: ../query from parent.id /app/server/node_modules/vectordb/dist/remote/index.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/vectordb/dist/remote"]
anything-llm  | MODULE 102: load "/app/server/node_modules/vectordb/dist/query.js" for module "/app/server/node_modules/vectordb/dist/query.js"
anything-llm  | MODULE 102: Module._load REQUEST apache-arrow parent: /app/server/node_modules/vectordb/dist/query.js
anything-llm  | MODULE 102: Module._load REQUEST ../native.js parent: /app/server/node_modules/vectordb/dist/query.js
anything-llm  | MODULE 102: RELATIVE: requested: ../native.js from parent.id /app/server/node_modules/vectordb/dist/query.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/vectordb/dist"]
anything-llm  | MODULE 102: load "/app/server/node_modules/vectordb/native.js" for module "/app/server/node_modules/vectordb/native.js"
anything-llm  | MODULE 102: Module._load REQUEST @neon-rs/load parent: /app/server/node_modules/vectordb/native.js
anything-llm  | MODULE 102: looking for "@neon-rs/load" in ["/app/server/node_modules/vectordb/node_modules","/app/server/node_modules","/app/node_modules","/node_modules","/app/.node_modules","/app/.node_libraries","/usr/lib/node"]
anything-llm  | MODULE 102: load "/app/server/node_modules/@neon-rs/load/dist/index.js" for module "/app/server/node_modules/@neon-rs/load/dist/index.js"
anything-llm  | MODULE 102: Module._load REQUEST ./index.node parent: /app/server/node_modules/vectordb/native.js
anything-llm  | MODULE 102: RELATIVE: requested: ./index.node from parent.id /app/server/node_modules/vectordb/native.js
anything-llm  | MODULE 102: looking for ["/app/server/node_modules/vectordb"]
anything-llm  | MODULE 102: Module._load REQUEST @lancedb/vectordb-linux-x64-gnu parent: /app/server/node_modules/vectordb/native.js
anything-llm  | MODULE 102: looking for "@lancedb/vectordb-linux-x64-gnu" in ["/app/server/node_modules/vectordb/node_modules","/app/server/node_modules","/app/node_modules","/node_modules","/app/.node_modules","/app/.node_libraries","/usr/lib/node"]
anything-llm  | MODULE 102: load "/app/server/node_modules/@lancedb/vectordb-linux-x64-gnu/index.node" for module "/app/server/node_modules/@lancedb/vectordb-linux-x64-gnu/index.node"
anything-llm  | /usr/local/bin/docker-entrypoint.sh: line 7:   102 Illegal instruction     (core dumped) node /app/server/index.js
anything-llm exited with code 132
```

Let me know if there's anything you'd like me to run or test to help figure out the issue
Thanks!

**Comment by timothycarambat** [comment]
This issue is because the default `lancedb` vector db does not have support (or can determine) which binary it needs to run lancedb.
```
vectordb@0.4.11:
  version "0.4.11"
  resolved "https://registry.yarnpkg.com/vectordb/-/vectordb-0.4.11.tgz#e5b209fc15fb100d8495c132d0e4cc817dc9065a"
  integrity sha512-hbN1qO08xdhEpoGecWR6UuvfnNFYDgZLvuEDvgq5nFVbA4er5qXTcEyxjnlTzKsVqFGLlPF+91I+JIigneX24w==
  dependencies:
    "@apache-arrow/ts" "^14.0.2"
    "@neon-rs/load" "^0.0.74"
    apache-arrow "^14.0.2"
    axios "^1.4.0"
  optionalDependencies:
    "@lancedb/vectordb-darwin-arm64" "0.4.11"
    "@lancedb/vectordb-darwin-x64" "0.4.11"
    "@lancedb/vectordb-linux-arm64-gnu" "0.4.11"
    "@lancedb/vectordb-linux-x64-gnu" "0.4.11"
    "@lancedb/vectordb-win32-x64-msvc" "0.4.11"
```

i would imagine linux x64 would be right?

**Comment by iFloris** [comment]
> This issue is because the default `lancedb` vector db does not have support (or can determine) which binary it needs to run lancedb.
That's interesting, so the problem originated in the vectordb. That would explain why the web ui crashed when opening workspace settings.

> i would imagine linux x64 would be right?
Yes, I imagine so as well.
The machine that doesn't work (bare metal):
`Linux 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux`
and the KVM that does work:
`Linux 4.19.0-26-amd64 #1 SMP Debian 4.19.304-1 (2024-01-09) x86_64 GNU/Linux`

**Comment by timothycarambat** [comment]
This seems like now more of a support issue for https://github.com/lancedb/lancedb

That being said, we are on package `0.4.11` so it is possible could have been fixed since in the SDK. Obviously such a critical piece like the vectordb we have to bump very carefull.

**Comment by iFloris** [comment]
Yes, I think you are right @timothycarambat. Thanks for the help investigating and the great tool!

**Comment by sbrosl** [comment]
Hi Tim,

I can confirm that I am on Linux x64 as well and the project is running in a podman container.

Could I suggest tagging the docker images with release versions like the desktop app? Simply so we could roll back in case of issues like this arising. Right now our instance is broken; even with no documents uploaded it crashes because of the default integrated LanceDB. The best option to "fix" this seems to be setting up an alternative vectordb (which is the route I am currently taking, two issues throwing the same error are currently open on the LanceDB repo since oct-nov of 2023 (https://github.com/lancedb/lancedb/issues/592 and https://github.com/lancedb/lancedb/issues/631) so I'm not sure Anything-LLM will start working for us with lancedb anytime soon).

Let me know if there is anything I can do to help. I'd like to echo iFloris and thank you and your community for the amazing open source project that is Anything-LLM!

**Comment by computersrmyfriends** [comment]
I have the same issue. Does not work on XEON E5 2660

![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/50d533d3-33af-4857-828b-e4ea67e9e82a)

**Comment by timothycarambat** [comment]
@computersrmyfriends use the non-native embedder. ONNX cannot run on your CPU, so native model running will not work.

**Comment by computersrmyfriends** [comment]
Thank you for the response @timothycarambat . I will try that

**Comment by computersrmyfriends** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/bf050863-f666-4cab-8cfd-d7e597766563)

I think you meant this ☝ @timothycarambat . I changed it.

But,even after that, once I send a message "hi" to the model on the workspace, it crashes,,,,

![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/ec805272-0289-4cf2-b7fb-98e5dfc5c596)


![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/b9a130bd-57db-43f9-a049-243547677cf7)

**Comment by timothycarambat** [comment]
Does sending a chat on an empty workspace work? Should not run any command on the embedder or vectordb. Referring to the thread, it looks like an invalid binary from lanceDB if the embedder can be ruled out

**Comment by computersrmyfriends** [comment]
Thanks for the super quick response.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/cfdf677b-1597-4f97-87c7-f0c39e1ff920)

The moment i created the workspace, it crashed again.

Then, i sent hi to the new workspace after restarting the container..., it crashed again..
![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/9f212643-efe1-456d-a6e3-b4b1a7325d14)

**Comment by computersrmyfriends** [comment]
@timothycarambat  Now, I tried chromadb...

It does not crash now. So, the crashing issue was due to the inbuilt Vectordb.

But, it gives me this error:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/d08229c1-3da9-4b73-b0d3-b340577dbe8e)

**Comment by computersrmyfriends** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/a5c3c880-8ead-4ab3-a079-a3e30f0ed039)

@timothycarambat  I tried creating another new workspace. With chromadb, it seems to be some different issue. it was giving an error twice and then it crashed.

**Comment by computersrmyfriends** [comment]
Also errors from chromadb container if it might help:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/323931/9750a3dd-387b-4ae2-9d0b-3b291acdec9f)
