### ISSUE TITLE
[FEAT]: Open the OpenAI endpoint for customization for embedding modells

### ISSUE THREAD

**Issue by alexanderMal** [Mintplex-Labs/anything-llm#1269]
### What would you like to see?

Dear AnythingLLM team thank you for your quick responses and good work!
As the community is pretty new and still in its finding phase standards are rare and as of now only determined by OpenAI it seems. More and more endpoints support the OpenAI standard for example the [huggingface text-embeddings-inference](https://github.com/huggingface/text-embeddings-inference/tree/main). As the AnythingLLM Application already provides the OpenAPI endpoint it might be very beneficial to allow a bit more customization like the URL for this endpoint. This would allow for a major growth of the compatible ecosystem and might be especially beneficial for embedding models.

My reason for requesting this feature is the rapid innovation in embedding models also focused on non-English speakers.

Keep up the good work!

P.S. As i mistakenly closed this feature without a comment:

If this also includes the embedding model than https://github.com/Mintplex-Labs/anything-llm/pull/1178 is the feature I would like to have. Yes!
I did not find this request before sorry for that and thank you for letting me know!

**Comment by timothycarambat** [comment]
Does the `Generic OpenAi` LLM provider not fill that gap at this time?
https://github.com/Mintplex-Labs/anything-llm/pull/1178

All the fields are open input and will just get used the OpenAI wrapper SDK - so this should be okay?

**Comment by alexanderMal** [comment]
If this also includes the embedding model than  #1178 is the feature I would like to have. Yes!
I did not find this request before sorry for that and thank you for letting me know!

**Comment by alexanderMal** [comment]
I just took a deeper look into feature #1178 and found this is not the feature I would like to have. My specific usecase is using the OpenAI kommunication protocoll for other embedding models.

**Comment by Vladimir-Va** [comment]
Hello gentlemens, I'm trying to configure Generic OpenAI and I get an error:
`400 Invalid type for 'max_tokens': expected an integer, but got a string instead.`

**Comment by timothycarambat** [comment]
@Vladimir-Va resolved via https://github.com/Mintplex-Labs/anything-llm/pull/1445
(not in most recent desktop version until 1.5.5+)
