### ISSUE TITLE
[FEAT]: User leads 

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1273]
### What would you like to see?

Add the possibility of collecting user data.

Example: before starting a conversation with the chatbot, the user is asked for an e-mail and first and last name, which will be saved at the conversation level.

**Comment by timothycarambat** [comment]
On the embed chat, right?

**Comment by Mirgiacomo** [comment]
> On the embed chat, right?

Yes
