### ISSUE TITLE
[FEAT]: Human response during chatbot conversation

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1275]
### What would you like to see?

A very useful and important feature for everyone is to be able to interact with the end user during a conversation.

Let me explain:
The user from an iframe embed dialogues with the chatbot
At a certain point he/she can ask for assistance from an operator (e.g. cannot find the answer or needs support)
On the anything panel he is notified that a user is asking for help.
The operator using anything can enter the conversation and answer instead of the chatbot as a real assistant.

So, i mean, integrate the ability to switch between chabot response and human response.

**Comment by timothycarambat** [comment]
I can say that human intervention or HIL in the chatbot, especially the embed will fall out of scope of our project. This would be an entire application on its own and require significant development as essentially this would be building a whole new Intercom/Crisp with an AI widget.
