### ISSUE TITLE
Does not load in browser after installation

### ISSUE THREAD

**Issue by vinaypri** [Mintplex-Labs/anything-llm#1283]
### How are you running AnythingLLM?

Not listed

### What happened?

I have used the non docker installation of Anything LLM on my server. Completed the setup steps as per your documentation and started the server and collector. However when I browse to the address - http://128.199.28.108:3001/ it just keeps loading infinitely.

I have enabled Together AI model in the below steps in the .env file
LLM_PROVIDER='togetherai'
TOGETHER_AI_API_KEY='<key-given-here>'
TOGETHER_AI_MODEL_PREF='01.AI/01-ai YI Chat(34B)'

The same key and model work fine in the desktop app. Please help.

### Are there known steps to reproduce?

Server address given, you may try to load.

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/blob/master/BARE_METAL.md

> [!WARNING]
> This method of deployment is **not supported** by the core-team and is to be used as a reference for your deployment.
> You are fully responsible for securing your deployment and data in this mode.
> **Any issues** experienced from bare-metal or non-containerized deployments will be **not** answered or supported.

Im sorry, we really cannot aide in non-containarized deployments, there are simply far too many places someone could go wrong or configure something improperly.

Common areas people look over going this route:
- Not compiling frontend and copying it to `server/public`
- Setting for `VITE_BASE_API` not being `/api` in `frontend/.env`
- No `STORAGE_DIR` in `server/.env`

**Comment by vinaypri** [comment]
Hi Timothy,

Thanks for the suggestions. The problem was indeed about not having /api in
frontend/.env. Incidentally this step is not mentioned in your
documentation at
https://github.com/Mintplex-Labs/anything-llm/blob/master/BARE_METAL.md

It would help in future, if you can add it.

Regards

**Comment by timothycarambat** [comment]
👍 
c0625c5cd625fbcb144d2f596edccc245f5d2a7c
