### ISSUE TITLE
[BUG]: Workspace setting fields not showing current configuration

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1284]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

When updating a parameter (such as system prompt), then switching to another tab in the workspace settings to change a parameter, then switching back to the previous tab, the old parameter information in that tab is shown.

Also, when switching between work spaces having changed a parameter in the previous workspace (such as preset chat messages), the current work space sometimes incorrectly show the settings of the previous workspace.

### Are there known steps to reproduce?

See above

**Comment by Propheticus** [comment]
It indeed does this when you don't save your changes using the `update workspace` button.
A bit clumsy UX-wise.

**Comment by timothycarambat** [comment]
Then save the changes

**Comment by Propheticus** [comment]
@timothycarambat I think I noticed what I think @RahSwe meant by their report. (tested on latest docker image) 
When you change settings + save/update the workspace (!) and then navigate to other tabs of the settings and back the previously used settings are still shown. When you close the settings and open them you see the newly saved settings.
So feels like a cache (invalidation) thingy / local variables not being updated from their initialised value.

**Comment by RahSwe** [comment]
Yes, that is what I tried to describe, sorry if I was being unclear.

**Comment by Propheticus** [comment]
> Yes, that is what I tried to describe, sorry if I was being unclear.

Reading it back now, you pretty much described it literally. Maybe just me/us not following 🦆

**Comment by timothycarambat** [comment]
Ah, okay that went totally over my head. Sorry about that
