### ISSUE TITLE
[DOCS] Question about newly added LLMs

### ISSUE THREAD

**Issue by ShadowArcanist** [Mintplex-Labs/anything-llm#1286]
On the update v1.5.3 we have added 2 new LLMs and 1 new Embedding model.

LLMs:
- Cohere
- KoboldCPP

Embedding Model:
- Cohere

I am going to add these new models to https://docs.useanything.com/anythingllm-setup/llm-configuration/overview but I am little confused about the LLMs and Embeding model like which one comes under the Cloud Provider Category and Local Provider Category.

I did some google search and ended up getting confused even more, it would be great if anyone can tell me which are these providers comes under which category.

**Comment by timothycarambat** [comment]
Cohere is cloud and LLM + Embedder
KobaldCPP is local and only LLM!
