### ISSUE TITLE
[BUG]: Won't launch on OS's that use libfuse3

### ISSUE THREAD

**Issue by genefyx** [Mintplex-Labs/anything-llm#1288]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

### Are there known steps to reproduce?

Currently using Vanilla OS, immutable OS, that that uses the updated libfuse3

**Comment by timothycarambat** [comment]
https://github.com/AppImage/AppImageKit/issues/1120

Wont be fixing this as it is out of scope. We provide the AppImage as a nice way to hopefully make Linux users lives easier, but that comes with its own issues already. You can use libfuse2 or the docker image to avoid FUSE altogether
