### ISSUE TITLE
[BUG]: Setting Workspace LLM Provider or Workspace Agent LLM Provider fails.

### ISSUE THREAD

**Issue by GoldenCaesar** [Mintplex-Labs/anything-llm#1294]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

After setting up a workspace and choosing any LLM I can get started chatting in a new thread. however, anything llm is overwriting my modelfile and preset system prompt (when using Ollama) So I go to workshop settings to add a system prompt, change my llm to the one I want and add openai agent llm.

I cannot make any changes in the Workspace LLM Provider or Workspace Agent LLM Provider without causing this error:

Error:
Invalid `prisma.workspaces.update()` invocation:

{
where: {
id: 1
},
data: {
chatProvider: "ollama",
~~~~~~~~~~~~
chatModel: "demicube_tablereader:latest",
chatMode: "chat",
openAiHistory: 20,
openAiPrompt: "Given the following conversation, relevant context, and a follow up question, reply with an answer to the current question the user is asking. Return only your response to the question given the above information following the users instructions as needed.",
queryRefusalResponse: "There is no relevant information in this workspace to answer your query.",
openAiTemp: 0.7,
? name?: String | StringFieldUpdateOperationsInput,
? slug?: String | StringFieldUpdateOperationsInput,
? vectorTag?: String | NullableStringFieldUpdateOperationsInput | Null,
? createdAt?: DateTime | DateTimeFieldUpdateOperationsInput,
? lastUpdatedAt?: DateTime | DateTimeFieldUpdateOperationsInput,
? similarityThreshold?: Float | NullableFloatFieldUpdateOperationsInput | Null,
? topN?: Int | NullableIntFieldUpdateOperationsInput | Null,
? pfpFilename?: String | NullableStringFieldUpdateOperationsInput | Null,
? workspace_users?: workspace_usersUpdateManyWithoutWorkspacesNestedInput,
? documents?: workspace_documentsUpdateManyWithoutWorkspaceNestedInput,
? workspace_suggested_messages?: workspace_suggested_messagesUpdateManyWithoutWorkspaceNestedInput,
? embed_configs?: embed_configsUpdateManyWithoutWorkspaceNestedInput,
? threads?: workspace_threadsUpdateManyWithoutWorkspaceNestedInput
}
}

Unknown argument `chatProvider`. Available options are listed in green.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/80002617/7680d23c-4992-4905-8283-6581a520aef8)


### Are there known steps to reproduce?

1. set up new workspace
2. try to change any settings in Workspace LLM Provider or Workspace Agent LLM Provider

**Comment by shatfield4** [comment]
This is most likely caused by your database schema not being migrated when you updated your version of AnythingLLM. I see you're on Windows and if you don't have an issue resetting your AnythingLLM instance, you can try these steps to resetting your desktop app.

1. Close the AnythingLLM desktop app.
2. Open File Explorer/Windows Explorer. Type `%AppData%` into the address bar and hit enter.
3. Delete the `anythingllm-desktop` folder.
4. Restart the app and this should reset your desktop app and migrate the database properly.

**Comment by timothycarambat** [comment]
Also which OS are you one?

**Comment by mooreezen** [comment]
I meet same issue, and I am using AnythingLLM desktop app Windows OS. I can't do any change in "Chat Settings".

Error:
Invalid `prisma.workspaces.update()` invocation:

{
where: {
id: 1
},
data: {
chatProvider: "openai",
~~~~~~~~~~~~
chatModel: "gpt-4o",
chatMode: "query",
openAiHistory: 20,
openAiPrompt: "Reply with an answer to the current question the user is asking. Return only your response to the question given the above information following the users instructions as needed.",
queryRefusalResponse: "There is no relevant information in this workspace to answer your query.",
openAiTemp: 0.7,
? name?: String | StringFieldUpdateOperationsInput,
? slug?: String | StringFieldUpdateOperationsInput,
? vectorTag?: String | NullableStringFieldUpdateOperationsInput | Null,
? createdAt?: DateTime | DateTimeFieldUpdateOperationsInput,
? lastUpdatedAt?: DateTime | DateTimeFieldUpdateOperationsInput,
? similarityThreshold?: Float | NullableFloatFieldUpdateOperationsInput | Null,
? topN?: Int | NullableIntFieldUpdateOperationsInput | Null,
? pfpFilename?: String | NullableStringFieldUpdateOperationsInput | Null,
? workspace_users?: workspace_usersUpdateManyWithoutWorkspacesNestedInput,
? documents?: workspace_documentsUpdateManyWithoutWorkspaceNestedInput,
? workspace_suggested_messages?: workspace_suggested_messagesUpdateManyWithoutWorkspaceNestedInput,
? embed_configs?: embed_configsUpdateManyWithoutWorkspaceNestedInput,
? threads?: workspace_threadsUpdateManyWithoutWorkspaceNestedInput
}
}

Unknown argument `chatProvider`. Available options are listed in green.

**Comment by timothycarambat** [comment]
This is related to permissions on the machine most likely. Additionally, if there is no internet connection on the first boot and a migration is required the prisma engine will fail to download and migrate. After which, no migrations will be needed. We pre-migrate the client before packaging anyway so this should be extraneous. 

@mooreezen what version are you on?

**Comment by mooreezen** [comment]
Hi. I'm on version 1.5.3.

**Comment by mooreezen** [comment]
Hello, it seems ok now after upgrading to version 1.5.5.

**Comment by josersleal** [comment]
> This is most likely caused by your database schema not being migrated when you updated your version of AnythingLLM. I see you're on Windows and if you don't have an issue resetting your AnythingLLM instance, you can try these steps to resetting your desktop app.
> 
> 1. Close the AnythingLLM desktop app.
> 2. Open File Explorer/Windows Explorer. Type `%AppData%` into the address bar and hit enter.
> 3. Delete the `anythingllm-desktop` folder.
> 4. Restart the app and this should reset your desktop app and migrate the database properly.

this deletes the storage folder and all your documents
