### ISSUE TITLE
[BUG]: Error importing Github repository 

### ISSUE THREAD

**Issue by giovanniscalar** [Mintplex-Labs/anything-llm#1296]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When you use data connector for import an entire Github repository, the folders on the repo aren't imported.

### Are there known steps to reproduce?

<img width="1423" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/149009837/ed10e7b6-6fe0-49f6-bfcb-25d527d25d6a">

**Comment by timothycarambat** [comment]
If you hover over the triangle icon you will see why that is the case. if you do not define a PAT for this connector only the top-level files are retrieved as to prevent a rate-limiting error from deep-nesting of the repo

**Comment by giovanniscalar** [comment]
Sorry I thought the access token was required for private repositories only. I will try that.

**Comment by Freffles** [comment]
FYI, you can get your PAT via this link (assuming you are logged in 😁) [https://github.com/settings/tokens?type=beta](url)

**Comment by mer0mingian** [comment]
Replicated this issue with AnythinLLM Desktop on Linux.

**Comment by gberger-panda** [comment]
Replicate also with AnythingLLM Desktop on macbook pro

**Comment by timothycarambat** [comment]
Everyone who is getting this issue, it would be helpful to know:
- Link to repo (if public)
- Using PAT or not
- How you provisioned the PAT in Github

The core functionality works, it ultimately comes down to the token and rate limits.
