### ISSUE TITLE
[FEAT]: Add a "SQL Talk Agent"

### ISSUE THREAD

**Issue by giovanniscalar** [Mintplex-Labs/anything-llm#1298]
### What would you like to see?

Add a new data agent, to interact with datasets in AWS, GCP, local and others.
This new agent needs to have at least 4 function callings:
- `list_datasets`: Get a list of datasets that will help answer the user's question
- `list_tables`: List tables in a dataset that will help answer the user's question
- `get_table`: Get information about a table, including the description, schema, and number of rows that will help answer the user's question. Always use the fully qualified dataset and table names.
- `sql_query`: Get information from data in BigQuery using SQL queries

the user should be able to add an API Key for the cloud service, and the source for the dataset in Google Cloud BigQuery or AWS Athena, etc

gemini example: https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/function-calling/sql-talk-app/app.py
example: https://youtu.be/pj5mRDy9lG8

**Comment by nileshtrivedi** [comment]
Are long-running persisted operations supported at all? If the agent is performing a task that takes more than a few minutes, will it survive if say, the user closes the HTTP connection or the server is shutdown and then is restarted for some reason.

**Comment by timothycarambat** [comment]
@nileshtrivedi no, if the client closes the connection while the agent is doing something it halts the agent to prevent runaway llms. If you kill/reboot the server there there is absolutely no way for it to continue for sure. It is not a cron so it would not continue on reboot.

**Comment by miladhatami1393** [comment]
to have a feature like this would be great! We need something like this

**Comment by broichan** [comment]
I agree as well 👍🏻
