### ISSUE TITLE
how to update knowledge files and ollama model

### ISSUE THREAD

**Issue by ddimit2020** [Mintplex-Labs/anything-llm#1299]
Gretting~
i use the docker-compose up to bulid anything llm,also use the local ollama llm bound on anything
but when i update the knowledge and ollama model,actually i can't find the newer knowledge and ollama models
**### 1.knowledge e.g.**
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/683ed822-7248-40d0-8377-17d61ce8f50b)
i already upload the 5 files,but when i ask anying and get the answer just the 2 files
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/74e33dca-4ed9-4985-9c88-7bea953fd7c0)

### ### 2.ollama model e.g.
the local ollama model include the 6 models
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/51d95f9e-edc9-4a5e-bc3d-5f3458c2f71a)
but the anything webui can't find the all models
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/f44eda78-4f1d-426c-b9de-f4344a1504f6)
if i want choose the llama3, can't choose this model on anything

anything command i shoud command update or any tips?
tks

**Comment by timothycarambat** [comment]
I see you have all your documents pinned, you cannot pin 10K of context into an 8K context window, so in this case, i am pretty sure that is what is preventing the rest of the files from showing during retrieval. Unless all of those file together result in < 8K context that is what is going on there.

As for the second item, did you scroll the input - it may be below `phi`? I am assuming you did, in which case you are able to see `llama3` in the main LLM preference but **not** in workspace? Correct?

**Comment by ddimit2020** [comment]
@timothycarambat 
Gretting~
1.so the major reason it's over 8k, later will not pinned after try it.
2.yes,i pretty sure scroll the input ,can't find match all Model on workspace,also finally checklist again
local ollama list model---->Model have 6 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/cb33fe0e-2962-4a58-9011-3ce3ed51ce37)
but the workspace---->Model have 6
![image](https://github.com/Mintplex-Labs/anything-llm/assets/164116068/61b0c9d2-e457-4e80-822f-d40683d6795d)
but something different,
may i know the workspace the config choose the Ollama should be concurrent match the true all-config,
but actually not really,and i'm make sure when i install the anything llm from docker install,
after something modify the local ollama models del or add,
so after result the Model can't really match ,but i don't have idea how to update the anytingllm to match local Model

**Comment by timothycarambat** [comment]
Is it possible you have two ollama instances running? One on the host and one in docker? Im going to close & mark this as unable to replicate as nobody else has reported this issue so I'm unsure how you can get two different model responses from the same ollama instance since we ping the provider URL directly. The fact we get responses at all means that the AnythingLLM side of things is working, but there is something going on with your setup/configuration as it is clearly pulling some other set of models?
