### ISSUE TITLE
[FEAT]: i18n, it's time for this

### ISSUE THREAD

**Issue by getofferhelp** [Mintplex-Labs/anything-llm#1304]
### What would you like to see?

Hi, creators of this GREAT Project,

Would you like to add i18n to anything lm?

If so, I could do the part of Chinese version.

**Comment by timothycarambat** [comment]
This would be a massive help, it is indeed time to i18n. Let us get it set up first so we know where we will put all the translation files and we can do that.

If you would like to contribute sooner, creation a README.zh.md would be a fantastic start and we can then link it at the top of the readme to nav between the two

**Comment by getofferhelp** [comment]
Sure, I would do this part today: 'creation a README.zh.md'.

**Comment by timothycarambat** [comment]
@getofferhelp if you are able to even just past in approximate translations of all the `null` fields in [frontend/src/locales/zh/common.js](https://github.com/Mintplex-Labs/anything-llm/pull/1317/files#diff-97a4081f97ab6605c54a1b981d08b1615c3d2786ab761d6868037e46d4e429ed) we can get started with first merge of translations

**Comment by getofferhelp** [comment]
> @getofferhelp if you are able to even just paste in approximate translations of all the `null` fields in [frontend/src/locales/zh/common.js](https://github.com/Mintplex-Labs/anything-llm/pull/1317/files#diff-97a4081f97ab6605c54a1b981d08b1615c3d2786ab761d6868037e46d4e429ed) we can get started with first merge of translations

ok, I would do it today.

**Comment by getofferhelp** [comment]
@timothycarambat how is the translation of the Setting UI of workspace , like General setting, Chat setting etc

**Comment by giovaborgogno** [comment]
Hi there, I can do the Spanish version if you want to add it.

**Comment by zjcurtis** [comment]
Possibly silly suggestion - for languages we don't have a native speaker offering to do the i18n for that language, might it be worthwhile to do llm translations (using one of the more linguistically capable) until somebody can come and offer native corrections? I think a bad translation is probably better than no translation so long as it's not indecipherable.

**Comment by timothycarambat** [comment]
@zjcurtis it absolutely would, the first issue prior to that is getting the list of "items" that require translation. There are a lot of areas for static text in the app so its a lot of work to set up initially, but then much easier to maintain as time goes one
