### ISSUE TITLE
Cannot seem to get a "data connection" to a github repo

### ISSUE THREAD

**Issue by Freffles** [Mintplex-Labs/anything-llm#1305]
Trying to create a data connection, will not accept the git clone URL and returns "Unable to fetch repository files: 404 {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"}" 

If I just paste in the url from the address bar then it will import 2 files only, .gitignore and readme.md

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/1296

With no PAT the repo grabber will only get the top-level files and will not deep-read the files because of API rate-limits
