### ISSUE TITLE
[BUG]: Cannot copy code and no scroll bar

### ISSUE THREAD

**Issue by hdavy2002** [Mintplex-Labs/anything-llm#1310]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I asked Ai to print me a simple code. Its displays in a code format with the option to copy code. However, when I click on Copy code. Nothing happens. Also after a lenthgy talk, there was no scroll bar. I have a brand new install.
![anythingllm](https://github.com/Mintplex-Labs/anything-llm/assets/1983384/bcdd2a74-8a47-4cf5-b16d-cabeb9d8cde1)

### Are there known steps to reproduce?

See screenshot for reference

**Comment by man2004** [comment]
Hi @timothycarambat , the copy option is browser limitation but how about the scroll bar? Copy works with my docker installation but scroll bar still does not work. I can use mouse wheel or keyboard to scroll up and down, though.

**Comment by timothycarambat** [comment]
@man2004  We don't display the scroll bars in the Ui because they get so messy and can sometimes hide controls. Do you need access to them for accessibility reasons?

**Comment by man2004** [comment]
I think it is OK not to have scroll bar. But then the showing of the arrow and bar may be a little bit misleading.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/150382/e2c44196-0ec9-4a69-8a15-3d25bbcb2064)
