### ISSUE TITLE
[BUG]: Error: 1 documents failed to add.  Ollama Failed to embed: [undefined]: undefined

### ISSUE THREAD

**Issue by hydrogen1222** [Mintplex-Labs/anything-llm#1311]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I got an error when uploading a document in AnythingLLM.

LLM Provider :Ollama
ChatModel Selection:Llama-3-Chinese-8B-Instruct(from https://github.com/ymcui/Chinese-LLaMA-Alpaca-3)
Transcription model :AnythingLLM-Built-in
Embedding preference:Ollama
Embedding Model Selection:Llama-3-Chinese-8B-Instruct(from https://github.com/ymcui/Chinese-LLaMA-Alpaca-3)
Vector DataBase:LanceDB

Error: 1 documents failed to add.

Ollama Failed to embed: [undefined]: undefined

Token context window:4096
Max embedding chunk length:8192

![image](https://github.com/Mintplex-Labs/anything-llm/assets/126487811/054a606e-36ce-41c7-bf15-d4fbee157b66)
I am not a computer-related major, so I may make some stupid mistakes. The document I want to upload is a Chinese document, 186kb, about two thousand words. I tried uploading it several times and got this error.
Looking forward to getting your answer, thank you very much!!!

### Are there known steps to reproduce?

I got an error when uploading a document in AnythingLLM.

LLM Provider :Ollama
ChatModel Selection:Llama-3-Chinese-8B-Instruct(from https://github.com/ymcui/Chinese-LLaMA-Alpaca-3)
Transcription model :AnythingLLM-Built-in
Embedding preference:Ollama
Embedding Model Selection:Llama-3-Chinese-8B-Instruct(from https://github.com/ymcui/Chinese-LLaMA-Alpaca-3)
Vector DataBase:LanceDB

Error: 1 documents failed to add.

Ollama Failed to embed: [undefined]: undefined

Token context window:4096
Max embedding chunk length:8192

![image](https://github.com/Mintplex-Labs/anything-llm/assets/126487811/054a606e-36ce-41c7-bf15-d4fbee157b66)
I am not a computer-related major, so I may make some stupid mistakes. The document I want to upload is a Chinese document, 186kb, about two thousand words. I tried uploading it several times and got this error.
Looking forward to getting your answer, thank you very much!!!

**Comment by timothycarambat** [comment]
`Embedding Model Selection:Llama-3-Chinese-8B-Instruct` 

Llama3 is **not and embeddeding model**

You have an LLM model selected. Ollama embedding models all have the word `embed` in them
[snowflake-arctic-embed](https://ollama.com/library/snowflake-arctic-embed)
[mxbai-embed-large](https://ollama.com/library/mxbai-embed-large)
[nomic-embed-text](https://ollama.com/library/nomic-embed-text)

Ollama does not discern between LLMs and Embedders and we cannot prevent this from occurring, you just need to know what the model you want to use is capable of
