### ISSUE TITLE
[BUG]: Webpage https://docs.useanything.com/managed-deployment/private-managed-anythingllm does not work

### ISSUE THREAD

**Issue by CellCS** [Mintplex-Labs/anything-llm#1318]
### How are you running AnythingLLM?

Not listed

### What happened?

when check "Learn more" from [pricing-page](https://useanything.com/pricing) <img width="620" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/16886624/b689ed6d-0fca-47af-8764-c0ca9a636781">
<img width="953" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/16886624/114980d5-4f89-4102-8276-ea418114928d">

### Are there known steps to reproduce?

click 
https://docs.useanything.com/managed-deployment/private-managed-anythingllm

**Comment by timothycarambat** [comment]
Thank you for pointing this out, fixed
