### ISSUE TITLE
Cannot configure Ollama embeddings

### ISSUE THREAD

**Issue by Freffles** [Mintplex-Labs/anything-llm#1319]
I had already downloaded nomic-embed-text to my windows system. Regardless of what I enter as the Ollama Base URL, the embedding model selection never updates.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/122719748/5b2b15cf-709d-4ff7-a839-c12719e4603a)

**Comment by timothycarambat** [comment]
Localhost does not work for [Ollama unless specifically set up](https://github.com/Mintplex-Labs/anything-llm/blob/0f981abd40bb3d4904bbf996bb22273f0f92c865/server/utils/AiProviders/ollama/README.md#L4)

You also dont need the full endpoint. just `http://127.0.0.1:11434`
