### ISSUE TITLE
[BUG]:  Hard lockup of Windows 11 computer when using native embeddings option in AnythingLLM v1.5.3 to encode PDFs for a Milvus DB 

### ISSUE THREAD

**Issue by LindsayRex** [Mintplex-Labs/anything-llm#1322]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Issue: Hard lockup of Windows 11 computer when using native embeddings option in AnythingLLM v1.5.3 to encode PDFs for a Milvus DB

Description:
Whenever I attempt to utilize the native embeddings option in AnythingLLM v1.5.3 to encode PDFs for a Milvus DB, my Windows 11 computer experiences a hard lockup. There are no blue screens or debug messages; instead, the entire system abruptly reboots after approximately one minute of running the embedding process. This issue does not occur with previous versions of the software. It seems like the CPU is being overloaded during the process.

Alternative Solutions Attempted:
I also tried using LM Studio Nomic 1.5 embeddings with local services, but encountered errors. Despite witnessing GPU activity, indicating processing of PDF files, there is no interaction with the Milvus server, as evidenced by the absence of network traffic, unlike when utilizing the native embeddings option.

System Information:

Operating System: Windows 11 (latest edition)
CPU: Intel Core i7 12900k
GPU: Nvidia RTX 4070 Super
Request:
I'm seeking guidance on how to capture relevant logs or troubleshoot this issue, as the current version of the software appears to be unusable on Window

**Comment by timothycarambat** [comment]
I specifically think this is related to the Milvus integration as no other vectorstores cause this issue. The native works fine with 20K files embedded and no issue. To run the program in an observable manner you can run it via powershell
`C:\Users\user\AppData\Programs\anythingllm-desktop\AnythingLLMDesktop.exe` and it will print all logs to the terminal window and should show _something_ when attempting to upsert the vectors.

**Comment by miladhatami1393** [comment]
specifically

**Comment by LindsayRex** [comment]
Hi Gents, I tried just using the native lance vector db. Same problem. i.e i removed the milvus db.. 

I wasn't sure how to get any verbose login out of the app. 

"C:\Users\user\AppData\Programs\anythingllm-desktop\AnythingLLMDesktop.exe and it will print all logs to the terminal window and should show something when attempting to upsert the vectors." 

this idea didnt work either. 

 I wil be clearer. My computer hard resets the power. What is even more astonishing is its win 11 VM running on linux proxmox host which also resets. I have never ever seen anything like this. 

I need to stream verbose logs to files that write somehow, maybe using transaction logs ? as the a log file will get corrupted, when the power resets. 

Cheers,

Lindsay

**Comment by LindsayRex** [comment]
Ok, so the fix after googling for 'embedding files in ollama into lancedb crashing windows 11' seems to be for some people to turn off cpu overclocking.. so I tried turning on off intel turbo frequency  in my bios.  Bingo, no more hard power resets when i embed lots of files in bulk.
