### ISSUE TITLE
[BUG]: network error

### ISSUE THREAD

**Issue by SyuanYo** [Mintplex-Labs/anything-llm#1323]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Hello, I tried to run AnythingLLM using Docker on Ubuntu and encountered the following issues. I would appreciate any advice you could provide. Thank you very much.

1.After creating a new Workspace, an error occurs when sending a message.
![1715247155099](https://github.com/Mintplex-Labs/anything-llm/assets/154793038/32a90043-1b2f-43c5-b303-9ae336b58333)
F12 Console
![1715247216643](https://github.com/Mintplex-Labs/anything-llm/assets/154793038/03608392-0294-4dae-bef7-40f0a0c4de0c)

2.Enter the workspace settings screen (gear icon).
![1715247394795](https://github.com/Mintplex-Labs/anything-llm/assets/154793038/f15ea594-ea28-4187-8d2e-6dbe375aa0ce)

3.docker logs
![1715247628836](https://github.com/Mintplex-Labs/anything-llm/assets/154793038/301bc476-2a2d-491d-9bf2-54ee1c9b0fad)

### Are there known steps to reproduce?

os & docker Info
![1715248401224](https://github.com/Mintplex-Labs/anything-llm/assets/154793038/9c3a7a65-1f88-4502-9420-6aa171f4cc16)
![1715248436063](https://github.com/Mintplex-Labs/anything-llm/assets/154793038/908d808c-25d8-4683-a4ad-9d870c14491f)

Below are the steps I took:

export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm

**Comment by timothycarambat** [comment]
Likely the same issue as https://github.com/Mintplex-Labs/anything-llm/issues/1290
I know you are on ubuntu but appears to be the same thing here

**Comment by SyuanYo** [comment]
HI @timothycarambat. Thank you for your response.
I saw in the text that the author suggests using Docker v4.30.0 as a solution.
However, I am using Docker engine V26.1.1, which uses the same engine as Docker v4.30.0, and the issue still hasn't been resolved.

docker logs:
"/usr/local/bin/docker-entrypoint.sh: line 7: 115 Illegal instruction (core dumped) node /app/server/index.js"
