### ISSUE TITLE
[BUG]: 1 documents failed toadd. Ollama Failed to embed:[undefined]: undefined 

### ISSUE THREAD

**Issue by jillong** [Mintplex-Labs/anything-llm#1324]
I've manually added Xenova/all-MiniLM-L6-v2. Why is this problem occurring?

**Comment by jillong** [comment]
![微信图片_20240509195055](https://github.com/Mintplex-Labs/anything-llm/assets/161576113/77e0a40e-1786-464a-a82a-a8269494c490)

**Comment by timothycarambat** [comment]
>  I've manually added Xenova/all-MiniLM-L6-v2. Why is this problem occurring?


The error clearly shows you are attempting to embed with Ollama. If you manually downloaded the Xenova all-mini-lm embedder you should be using the default native embedder. The first option on embedder preferences

**Comment by jillong** [comment]
how to embed with Ollama ?

**Comment by timothycarambat** [comment]
Use one of their embedders 
nomic-text-embed
snowflake-embed
mxbai-large-embed

**Comment by jillong** [comment]
When I choose mxbai-large-embed, the file is saved and embed if it's only a few grams in size; But when the file is larger, it still prompts 'Olamarfeld Thorn Bade: [Undefined]: Undefined'. why? How much can handle the file size limit？

**Comment by s-kostyaev** [comment]
> When I choose mxbai-large-embed, the file is saved and embed if it's only a few grams in size; But when the file is larger, it still prompts 'Olamarfeld Thorn Bade: [Undefined]: Undefined'. why? How much can handle the file size limit？

Same here

**Comment by chanshunli** [comment]
how resolve?
Error: 1 documents failed to add.
Ollama Failed to embed: [undefined]: undefined
<img width="984" alt="erro" src="https://github.com/user-attachments/assets/23866591-233a-4388-a5b4-41fcde1bed92">
