### ISSUE TITLE
[FEAT]: More search engines

### ISSUE THREAD

**Issue by chllei** [Mintplex-Labs/anything-llm#1327]
I am extremely grateful for creating such an excellent tool which enables me to utilize my local Large Language Models and explore the potential of agents. Given that Google is inaccessible for me due to certain reasons, could you consider adding more search engine options? For instance, [this project](https://github.com/n4ze3m/page-assist) offers a choice for Sogou Search Engine.

**Comment by timothycarambat** [comment]
Is that the one specifically you would like to use? Is Serper.dev also unavailable for you? (2,500 free requests only)

**Comment by Vinitrajputt** [comment]
We have the option to utilize the Yahoo search engine. I recall incorporating it as a secondary search engine in one of my projects, especially when I reached the limit of my free tier in the Google search engine.

**Comment by chllei** [comment]
> Is that the one specifically you would like to use? Is Serper.dev also unavailable for you? (2,500 free requests only)

@Vinitrajputt @timothycarambat We commonly use search engines such as Bing, Baidu, and Sogou. However, like Yahoo and Google are inaccessible to us.

**Comment by chllei** [comment]
> Then Bing could be a viable option. I will explore the possibility of integrating it into the project.

Thank you very much! I believe that using local LLMs for online question answering is a fantastic tool, which can effectively unleash the capabilities of 7B-level models.

**Comment by cope** [comment]
[Glean](https://www.glean.com/) would be awesome - especially custom ones like mycustomgroup.glean.com :)

**Comment by EverettCMarm** [comment]
is there a way now to use Brave Search ?

**Comment by timothycarambat** [comment]
https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#using-as-a-search-engine
