### ISSUE TITLE
[FEAT]: Depth scraping merge

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#1332]
### What would you like to see?

I saw that there is a pending merge request (1190-feat-website-scraping-depth) related to the depth scraping functionality, when will it be possible to merge into master?
I do not understand whether the changes in that branch are actually working or not. Because alternatively I have developed the same recursive scraping functionality (with different libraries) and could upload them.

**Comment by timothycarambat** [comment]
It has not been merged yet as we had some other PRs to merge first and that PR also will need to be handled basically twice because that is not how scraping works on desktop. That is why its been sitting out there for a minute
