### ISSUE TITLE
[FEAT]: Show supported documents type when uploading files

### ISSUE THREAD

**Issue by jazelly** [Mintplex-Labs/anything-llm#1333]
### What would you like to see?

Hi, this is such amazing repo. 

Wouldn't it be great to show supported documents types?

**Comment by timothycarambat** [comment]
We used to, but then there were dozens of filetypes and it got really messy. Now we just allow any file types because there are basically unlimited amounts of them.

Anything that can be text is turned to text now. Anything that requires a special handlers is handled via the `asXYZ.js` in `collector/utils/convert`

**Comment by LvargaDS** [comment]
I do see that text types are being detected using this source file https://github.com/Mintplex-Labs/anything-llm/blob/master/collector/utils/files/mime.js

My guess is that only text types are being parsed now https://github.com/Mintplex-Labs/anything-llm/blob/master/collector/utils/files/index.js#L31

Or do I see it wrong?

PS: I was trying to find out, whenever tar archive with text files (without any extensions!) are being recognized.

**Comment by timothycarambat** [comment]
@LvargaDS if we dont have a dedicated mapping for a file then we will attempt to read it as text. This handles the majority of files but `.tar` will for sure fail and [`.zip` is explicitly blocked](https://github.com/Mintplex-Labs/anything-llm/blob/baab837b5886190f951e9958a049bf0ca6948573/collector/utils/files/mime.js#L6C5-L6C23) for security and zip-bombing

**Comment by LvargaDS** [comment]
It is a bit unfortunate, that there is currently no way, how to provide local knowledge base scattered in many files...
My best approach is currently to import those "wiki like" pages into a git repo and than use git connector to import whole list of files. Zip (or tar, or even tar.gz) would be a bit easier to use for my usecase, but I think git workaround is ok).
Please let me know, if there is better way to achieve this.

**Comment by kaydol** [comment]
> It is a bit unfortunate, that there is currently no way, how to provide local knowledge base scattered in many files... My best approach is currently to import those "wiki like" pages into a git repo and than use git connector to import whole list of files. Zip (or tar, or even tar.gz) would be a bit easier to use for my usecase, but I think git workaround is ok). Please let me know, if there is better way to achieve this.

I was able to temporarily serve a local folder as a website with the help of https://github.com/dector/serv , then scraped said website (http://localhost:port or http://host.docker.internal:port). The only problem is that the scraper does not allow to scrape more than 5 folders deep

EDIT: that didn't quite work, the resulting json files of the pages have a 404 not found text in them
