### ISSUE TITLE
[BUG]: DOCKER stopped when input message.

### ISSUE THREAD

**Issue by xqinshan** [Mintplex-Labs/anything-llm#1334]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I follow the two step instruction like
~~~
docker pull mintplexlabs/anythingllm

$env:STORAGE_LOCATION="$HOME\Documents\anythingllm"; `
If(!(Test-Path $env:STORAGE_LOCATION)) {New-Item $env:STORAGE_LOCATION -ItemType Directory}; `
If(!(Test-Path "$env:STORAGE_LOCATION\.env")) {New-Item "$env:STORAGE_LOCATION\.env" -ItemType File}; `
docker run -d -p 3001:3001 `
--cap-add SYS_ADMIN `
-v "$env:STORAGE_LOCATION`:/app/server/storage" `
-v "$env:STORAGE_LOCATION\.env:/app/server/.env" `
-e STORAGE_DIR="/app/server/storage" `
mintplexlabs/anythingllm

~~~

to install anthingllm in the docker(windows 11) and can run at http://localhost:3001  and can set LLM model.   But when I input message in the chatbox or embed files(error message: cannot fetch), it stopped. The docker messages are:

- fatal: not a git repository (or any of the parent directories): .git
- getGitVersion Command failed: git rev-parse HEAD
-  /usr/local/bin/docker-entrypoint.sh: line 7:   185 Illegal instruction     node /app/server/index.js

I donot understand the message "not a git repository", I donot set any repository. The container storage volume is a fold on my local computer.
 
I also check the  docker-entrypoint.sh, it seems node can run without any error message.
- # node /app/collector/ondex.js
- #  

Maybe that's a bug or not,  but I cannot access discord and have to ask for help here. How can I do to solve the problem? Thank you.

**Comment by timothycarambat** [comment]
These messages are extraneous and not killing the container:
```
fatal: not a git repository (or any of the parent directories): .git
getGitVersion Command failed: git rev-parse HEAD
``

So we can ignore those. We have seen some people getting this core-dumped segfault with node. This is the related issue where it has been fixed. it is a client-side issue so out of scope for the repo

https://github.com/Mintplex-Labs/anything-llm/issues/1290#issuecomment-2101960232

Seems to be a docker engine thing?
