### ISSUE TITLE
[DOCS]: Wrong volumes in `docker run` command

### ISSUE THREAD

**Issue by cope** [Mintplex-Labs/anything-llm#1337]
### Description

Took me a while to figure out why I kept getting this error:
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/db/anythingllm/env" to rootfs at "/app/server/.env": mount /run/desktop/mnt/host/d/db/anythingllm/env:/app/server/.env (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

But, it turns out that the docker `run command` I copied from https://docs.useanything.com/getting-started/installation/self-hosted/local-docker was wrong. There is no `app` directory in the container, so I needed to remove all 3 instances of `app/` from the `docker run` command and then it worked.

**Comment by timothycarambat** [comment]
This was a typo in you run command
> /run/desktop/mnt/host/d/db/anythingllm/env:/app/server/.env (via /proc/self/fd/6), flags: 0x5000: not a directory:

Should be `run/desktop/mnt/host/d/db/anythingllm/.env`
`-v ${STORAGE_LOCATION}/.env:/app/server/.env` mounts file to file in container

What you have was essentially 
`-v ${STORAGE_LOCATION}/env:/app/server/.env` which tries to mount a directory to a file and will fail

**Comment by cope** [comment]
I didn't have `run/desktop/mnt/host/d/db/anythingllm/.env` anywhere in my command.

My command was `docker run -d --restart unless-stopped -p 3001:3001 --cap-add SYS_ADMIN -e STORAGE_DIR="/app/server/storage" -v "D:/db/anythingllm:/app/server/storage" -v "D:/db/anythingllm/env:/app/server/.env" --name anything-llm mintplexlabs/anythingllm:master` and that threw the above error.

When I removed `app/` from the command and had `docker run -d --restart unless-stopped -p 3001:3001 --cap-add SYS_ADMIN -e STORAGE_DIR="/server/storage" -v "D:/db/anythingllm:/server/storage" -v "D:/db/anythingllm/env:/server/.env" --name anything-llm mintplexlabs/anythingllm:master` instead, then it worked.

**Comment by cope** [comment]
btw, I find it quite disrespectful to close an issue without allowing the requestor some _reasonable_ time to respond.

**Comment by timothycarambat** [comment]
```
docker run -d --restart unless-stopped \
-p 3001:3001 \
--cap-add SYS_ADMIN \
-e STORAGE_DIR="/app/server/storage" \
-v "D:/db/anythingllm:/app/server/storage" \
-v "D:/db/anythingllm/.env:/app/server/.env" \ <-- right here. You forgot a period
--name anything-llm \
mintplexlabs/anythingllm:master
```

**Comment by timothycarambat** [comment]
@cope im not being disrespectful, im just trying to address the issue and this issue is not qualified as a bug or a documentation update. It was just a simple typo and that is all i am addressing

**Comment by timothycarambat** [comment]
Actually, on second glance i now see this does not even have the full storage path set. in our docs we have the command to run as 
```
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

Assuming you dont want to use an env and your folder on the host machine is `/home/user/anythingllm/` the command should look like this:

_you might need to also `touch /home/user/anythingllm/.env`_ prior

```
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p /home/user/anythingllm/ && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v /home/user/anythingllm/:/app/server/storage \
-v /home/user/anythingllm/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

**Comment by cope** [comment]
Wait, please wait.

This command **works**:
```
docker run -d --restart unless-stopped /
-p 3001:3001 /
--cap-add SYS_ADMIN /
-e STORAGE_DIR="/server/storage" /
-v "D:/db/anythingllm:/server/storage" /
-v "D:/db/anythingllm/env:/server/.env" / <-- No period on the left and it works
--name anything-llm /
mintplexlabs/anythingllm:master/
```

This command _does not work_:
```
docker run -d --restart unless-stopped /
-p 3001:3001 /
--cap-add SYS_ADMIN /
-e STORAGE_DIR="/app/server/storage" /
-v "D:/db/anythingllm:/app/server/storage" /
-v "D:/db/anythingllm/env:/app/server/.env" / <-- No period on the left and it works
--name anything-llm /
mintplexlabs/anythingllm:master/
```

The difference between the one working and the one not working is just the existence/absence of `/app`.

Now, should I change it from "D:/db/anythingllm/env" to "D:/db/anythingllm/.env" - entirely possible for other reasons, but again, the first one above with "D:/db/anythingllm/env" works fine.

**Comment by cope** [comment]
I will gladly change to .env to test.

**Comment by timothycarambat** [comment]
This makes sense since `D:/db/anythingllm/env` probably exists in the folder while `D:/db/anythingllm/.env` may not. If you create that file (`D:/db/anythingllm/.env`) and run the command with the `.env` in it should work.It may have been crashing because the file was never `touch`'d and the docker container does not create it. 

In its current state, when the program tries to write to `.env` and it is mounted to a folder on the host, that fails because the `node:fs` write command can only write to a file - otherwise it will throw.

**Comment by cope** [comment]
As expected:
```
docker run -d --restart unless-stopped \
-p 3001:3001 \
--cap-add SYS_ADMIN \
-e STORAGE_DIR="/app/server/storage" \
-v "D:/db/anythingllm:/app/server/storage" \
-v "D:/db/anythingllm/.env:/app/server/.env" \
--name anything-llm \
mintplexlabs/anythingllm:master
```
Errors:
```
8cb44225bace9924cb8ea422096e221a4169a9e3b9710b8435ca363f63e304c4
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/d/db/anythingllm/.env" to rootfs at "/app/server/.env": mount /run/desktop/mnt/host/d/db/anythingllm/.env:/app/server/.env (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

While
```
docker run -d --restart unless-stopped \
-p 3001:3001 \
--cap-add SYS_ADMIN \
-e STORAGE_DIR="/server/storage" \
-v "D:/db/anythingllm:/server/storage" \
-v "D:/db/anythingllm/.env:/server/.env" \
--name anything-llm \
mintplexlabs/anythingllm:master
```
works:
```
24bdc02959b37f229f3ac2cbc3330e5de35531c96b2e15fbd1530911f6ce7e4a
```

**Comment by cope** [comment]
AAAA, .env is a file??

**Comment by cope** [comment]
```
docker run -d --restart unless-stopped \
-p 3001:3001 \
--cap-add SYS_ADMIN \
-e STORAGE_DIR="/app/server/storage" \
-v "D:/db/anythingllm:/app/server/storage" \
-v "D:/db/anythingllm/.env:/app/server/.env" \
--name anything-llm \
mintplexlabs/anythingllm:master
```
works when .env is a file............

**Comment by cope** [comment]
But, OK - I get why it failed - makes sense.

But WHY did the one without `/app` work, though???

**Comment by timothycarambat** [comment]
I feel like we were talking around the same thing but just weren't communicating effectively haha. yes `.env` is a **file**.

Im sorry, I look at this code too much and start making assumptions.

Also to reiterate, i really did mean no offense from closing the issue. I think i was just on a different page when I was answering the original issue.


**how** the one without `/app` worked is honestly confusing. The app layout in container is like
```
/app
- /server
--/storage
---.env
- /collector
```

So maybe by pure luck the paths work?

**Comment by cope** [comment]
> Im sorry, I look at this code too much and start making assumptions.
Believe me, I get that 😄

> Also to reiterate, i really did mean no offense from closing the issue. I think i was just on a different page when I was answering the original issue.
No worries. It's my pet peeve :bowtie:

> **how** the one without `/app` worked is honestly confusing.
> So maybe by pure luck the paths work?
Actually, bad luck since it caused me to frame into the very wrong "solution" and be like "_why is he telling me to add the damn period when it works without it_" 😄😄😄

But, also glad we got it sorted :relaxed:
