### ISSUE TITLE
[FEAT]: Be able to set max tokens generated in LLM setup

### ISSUE THREAD

**Issue by pst2154** [Mintplex-Labs/anything-llm#1342]
### What would you like to see?

In the Generic OpenI - Unfortunately im dealing with an endpoint with a default max tokens of 16 but I need to increase that manually to something like 1024.

**Comment by timothycarambat** [comment]
16!!! 

We can expose this as a parameter for sure. 16 max_tokens is crazy. We might just patch it right now to be at least 1024
