### ISSUE TITLE
[BUG]: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY

### ISSUE THREAD

**Issue by chalitguza** [Mintplex-Labs/anything-llm#1348]
### How are you running AnythingLLM?

All versions

### What happened?

gemini 1.5 pro
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/f6b45f7f-fb2d-4521-bb4a-9f853aab74ee)

**Comment by timothycarambat** [comment]
Yeah, this is because Google found it a violation of their content policy. We can only set it to LOW, but cannot disable it. You need special permission to do so

**Comment by timothycarambat** [comment]
https://ai.google.dev/gemini-api/docs/safety-settings

**Comment by RahSwe** [comment]
@timothycarambat 

Is this the current setting for all content categories with Gemini?

<img width="785" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/ebb30447-9c6d-4811-a8b2-f57e1b365ba6">

**Comment by RahSwe** [comment]
@timothycarambat 

Not knowing what I am doing, but this seems to be the settings to use in the Gemini javascript file:

safety_settings: [
    {
      category: HarmCategory.HARM_CATEGORY_HARASSMENT,
      threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH,

      category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
      threshold: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,

      category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
      threshold: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,

      category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
      threshold: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
    },

**Comment by timothycarambat** [comment]
That is the default, so yes
