### ISSUE TITLE
unable to convert json files 

### ISSUE THREAD

**Issue by rabeeqasem** [Mintplex-Labs/anything-llm#135]
I'm currently using the watch.py to convert JSON file as the tutorial shows and give me this error

```

Upload files into this directory while this script is running to convert them.
Press enter or crtl+c to exit script.
.json not a supported file type for conversion. Removing from hot directory.


```

**Comment by franzbischoff** [comment]
Hello,

JSON files may contain about any structure... Can you give an example of where the collector would expect to have data or metadata of this JSON file? 

Thanks
