### ISSUE TITLE
[FEAT]: Edit chat interaction

### ISSUE THREAD

**Issue by chalitbkb** [Mintplex-Labs/anything-llm#1357]
### What would you like to see?

Is it possible to add these two features to the chat interface: 'Embedded Chat Widgets' and 'workspace chat'?

- Pencil Icon: This would allow users to edit a conversation or any particular question. Once the save button is pressed, it will clear all the text in the conversation below, but it will not clear the text above. The conversation will then restart from the edited sequence.

- Regenerate Icon: This would enable users to request a new response.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/c1ab8341-8959-4fe3-9777-201bcd266dd4)

*Additionally, I would like to be able to display 'Suggested Chat Messages' on 'Embedded Chat Widgets'.

**Comment by JosephHalter** [comment]
You should also be able to edit the responses without regenerating anything, otherwise once one answer contains something strange, it'll become part of the chat history and derail the rest of the conversation.

**Comment by timothycarambat** [comment]
We have already done answer regeneration https://github.com/Mintplex-Labs/anything-llm/pull/1341 which was merged yesterday so it is not on the desktop version, but is in docker as of the writing of this comment

As for editing the original prompt, that indeed does not exist

**Comment by chalitguza** [comment]
> * Regenerate

I've noticed that the 'Regenerate' icon has been updated to allow for new responses, but is it possible to also add an icon for editing previous messages? This would enable users to revise and resubmit their questions, similar to the feature available on chatgpt.com, where users can edit their queries in any conversation.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/3d0d249f-f87a-44d5-849c-af732ba03129)

**Comment by chalitguza** [comment]
> We have already done answer regeneration #1341 which was merged yesterday so it is not on the desktop version, but is in docker as of the writing of this comment
> 
> As for editing the original prompt, that indeed does not exist
