### ISSUE TITLE
[BUG]: There are issues with adding user accounts.

### ISSUE THREAD

**Issue by chalitguza** [Mintplex-Labs/anything-llm#1358]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

The issue arises only when selecting the 'Default' option. After adding a user and logging in with that account, no Workspaces are found at all. Please note that this problem occurs solely with the 'Default' option.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/f68fccca-5629-4978-90a1-ef6a93ba6897)

Login 'test12345'
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/e2fd752e-2264-43f4-a6ac-40007a4e2f8e)

However, using the method of sending an invitation link does not encounter this problem.

**Comment by RahSwe** [comment]
Default users do not have access to all workspaces. You need to assign workspaces to the user account.

**Comment by timothycarambat** [comment]
This is stated in the user role for default 
> Can only send or access workspaces they are added to by managers or admins

This is intentional
