### ISSUE TITLE
GitHub Repo URL Feature Not Working

### ISSUE THREAD

**Issue by jcapshaw** [Mintplex-Labs/anything-llm#1361]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I am trying to link my GitHub Repo to my AnythingLLM Desktop App. I have tried 10 to 15 different repos, including my own and all have public access. I tried using the Github Access Token (classic) and also tried without a token and continue to see the same error: "Unable to fetch repository files: 404 {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"}. Anyone else have this issue or know a work around?
![image](https://github.com/Mintplex-Labs/anything-llm/assets/51003293/bce7fdc8-0e4d-4d93-954d-69c948c7efcd)

**Comment by timothycarambat** [comment]
Does not seem to be replicated on Docker or desktop.
Example repo URL: https://github.com/Mintplex-Labs/openai-assistant-swarm
<img width="1423" alt="Screenshot 2024-05-11 at 12 30 36 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/20785c22-8678-49d1-a620-9b8435d86f3a">

You are getting a PAT from https://github.com/settings/personal-access-tokens/new?

**Comment by timothycarambat** [comment]
will reopen if we can repro

**Comment by Myia828** [comment]
Hola! yo tengo el mismo error y no he encontrado manera. Alguien la encontró?

**Comment by doobidoo** [comment]
I'm observing the same issue as reported in https://github.com/Mintplex-Labs/anything-llm/issues/1361#issue-2290991783 by @jcapshaw with a repo and access token.
The repo in scope is private btw.

**Comment by KODIKAS-NL** [comment]
I had the same thing with a (private) repo, turns out my problem was that, when you just copy/paste the url from github it has the ".git" at the end. But the data connector needs you to remove that, even though it reads the branches with the ".git" at the end.

**Comment by KODIKAS-NL** [comment]
> Does not seem to be replicated on Docker or desktop. Example repo URL: https://github.com/Mintplex-Labs/openai-assistant-swarm <img alt="Screenshot 2024-05-11 at 12 30 36 PM" width="1423" src="https://private-user-images.githubusercontent.com/16845892/329809410-20785c22-8678-49d1-a620-9b8435d86f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzM0NTMsIm5iZiI6MTczMTI3MzE1MywicGF0aCI6Ii8xNjg0NTg5Mi8zMjk4MDk0MTAtMjA3ODVjMjItODY3OC00OWQxLWE2MjAtOWI4NDM1ZDg2ZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDIxMTIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MjAwM2Q1ZWVhYjI4MDA2NWNjMmJkZDZhYzAxMGQxMDBkMDFjNjNkMjI0ZjA1YTgxMjA3NjcxYjk2YTVkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5RpeWvtEmeRrFB6hub8ugWnhdryXIlbKMcTOriLQ7jA">
> 
> You are getting a PAT from https://github.com/settings/personal-access-tokens/new?

I had the same thing with a (private) repo, turns out my problem was that, when you just copy/paste the url from github it has the ".git" at the end. But the data connector needs you to remove that, even though it reads the branches with the ".git" at the end.

**Comment by timothycarambat** [comment]
You just paste in the repo URL, not the clone/SSH/HTTP URL in the "Code" button
