### ISSUE TITLE
[BUG]: GitHub subfolders not followed. 

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1364]
### How are you running AnythingLLM?

Docker (local)

### What happened?

See the pictures. The GitHub url has a lot of subfolders and none of them ever made it into the documents. 

### Are there known steps to reproduce?

![IMG_1761](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/0cbd9541-6f33-4b7b-94b5-8f20cfcd718f)
![IMG_1759](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/7f4a741c-c4bf-4b14-b704-41a781c1e0eb)
![IMG_1760](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/52e782b1-5803-4476-8b60-fd768756c5f9)

Also, is this button supposed to do anything? Nothing happens when clicking it. 
![IMG_1762](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/b0044ab0-e721-4360-9f2b-1bbf2a032e4c)

Can you elevate data connections so that they are saved on their own, and at the click of a button, someone can refresh those data sources… not sure how that would affect other workspaces, but I’d be ok with a side effect from that.

**Comment by atljoseph** [comment]
Same with https://github.com/ollama/ollama

**Comment by timothycarambat** [comment]
You need a PAT to access sub-folders due to rate-limiting
https://github.com/Mintplex-Labs/anything-llm/issues/1305#issuecomment-2100972013

**Comment by atljoseph** [comment]
Can you add that to the information displayed on the page? It mentions that
token and why it is needed, but doesn’t mention or infer sub folders.

**Comment by atljoseph** [comment]
And when you enter a token, is that somehow remembered?

**Comment by atljoseph** [comment]
Had to do this about 4-5 times right now, and yeah… can you have a way for
things like this to be initialized from an environment variable? That
wouldn’t fix everything, but it would make things pretty easy for folks who
use this locally. Should be pretty easy to just put a process.env in on
startup to inject a value.
