### ISSUE TITLE
[FEAT]: Database System Import/Export

### ISSUE THREAD

**Issue by chalitguza** [Mintplex-Labs/anything-llm#1365]
### What would you like to see?

Is it possible to export and import the entire system database (in JSON format) including system prompts, all system settings, and even the complete list of user accounts, various API key configurations and Instance Workspaces?

** With just one button, all data can be easily exported and imported. I've noticed that only certain parts can do this. It would be quite beneficial if it were possible to export and import with a single click.
**
Note: There are some tasks that occasionally require me to switch 'railway' user accounts, but I want to use the same system database for another account.

**Comment by timothycarambat** [comment]
You can accomplish the same end-result by copy-pasting in the same `anythingllm.db`, `.env`, and entire `/storage` folder. Would this not suffice? Any particular reason it needs to be JSON? Or am i misreading the issue at hand?

**Comment by chalitguza** [comment]
I need to transfer all the DB databases from one account to another, and I want to completely delete the old account.
