### ISSUE TITLE
[FEAT]: Add Searxng as web search provider for agent to use (free and unrestricted)

### ISSUE THREAD

**Issue by savareyhano** [Mintplex-Labs/anything-llm#1367]
### What would you like to see?

Add Searxng as the web search provider for agent to use, it is used in popular github projects like [Perplexica](https://github.com/ItzCrazyKns/Perplexica), and [LLocalSearch](https://github.com/nilsherzig/LLocalSearch).
I think this would be great alternative to Google and Serper, because if i'm not mistaken it is free and not restricted with maybe a caveat (after seeing how Perplexica works) it need to be locally hosted (more resource usage probably).

**Comment by timothycarambat** [comment]
The best we could do here is connect to someones running instance of `Seachxng`. So it would basically just be a third party provider for search support.

**Comment by savareyhano** [comment]
> The best we could do here is connect to someones running instance of `Seachxng`. So it would basically just be a third party provider for search support.

Yeah i think that would be good too, because creating own searxng instances would require docker (correct me if i'm wrong) and all stuff that might complicate the application unnecessarily.

**Comment by jaschadub** [comment]
I run a local docker container of searxng since most public ones do not provide json results. Plus I can customize which search engines it queries in config.

**Comment by timothycarambat** [comment]
connect #1327

**Comment by olariuromeo** [comment]
Nice, so how we can add this search to the app?
