### ISSUE TITLE
[FEAT]: Select specific pages from document to embed

### ISSUE THREAD

**Issue by wparuch** [Mintplex-Labs/anything-llm#1368]
### What would you like to see?

I'm testing working with documents. I have single, 9 pages pdf. Context from pdf that is send to local LLM is irrelevant. I found no specific settings in LM Studio to tune this behavior. 

The idea is to select specific pages to embed in order to skip irrelevant content.

**Comment by timothycarambat** [comment]
This should be done prior to upload into AnythingLLM and is considered to be "Document preparation". If you would like better RAG answers it is also best to at least curate the data being fed into the workspace
