### ISSUE TITLE
Modifying Embedded Documents

### ISSUE THREAD

**Issue by SKRohit** [Mintplex-Labs/anything-llm#137]
What happens when we modify the documents that have been embedded once? Are they embedded again and new embeddings are overwritten?

**Comment by SKRohit** [comment]
@timothycarambat What happens currently in anything-llm to handle this? If this is not available now what is the plan to adding this feature?

**Comment by timothycarambat** [comment]
_for now_ you would delete the document totally and re-embed

_in the future_ there will be a UI to "sync" or edit docs and embeddings, but not soon.

**Comment by timothycarambat** [comment]
See [VectorAdmin](https://github.com/Mintplex-Labs/vector-admin) for this + more

**Comment by timothycarambat** [comment]
Closing this for now as Vector Admin is the solution for this detail at this time.
