### ISSUE TITLE
[FEAT]: Light mode or copy button for text reproduction

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1370]
### What would you like to see?

Currently, the characters in the prompt response are white on a black background. When the text is copied to an application such as Word, the characters are "invisible" and have to be changed to black to be visible.

A solution would be
a) Enabling a light mode in which characters are black, or
b) Adding a "copy" button in connection with each response, in which the text is copied as black characters.

**Comment by timothycarambat** [comment]
This is a system thing. All you would need to do to alleviate this is to `Paste without formatting`
windows: Alt+Shift+V
mac: cmd+shift+V
