### ISSUE TITLE
Can it be set to a language in a non-English speaking country?

### ISSUE THREAD

**Issue by MRQJsfhf** [Mintplex-Labs/anything-llm#1371]

**Comment by timothycarambat** [comment]
This issue does not use the issue template and is not descriptive enough for me to answer.

If you mean the LLM, just tell it to respond in a specific language in its system prompt
If you mean the application interface: https://github.com/Mintplex-Labs/anything-llm/pull/1317

That PR will enable other languages as well once set up

**Comment by bleriot14** [comment]
Hello @timothycarambat. I apprisiate your works, thank you alot. 
I would like to know are there any mechanism that let specific workspace works with desired non-english language ? 
I would like to direct all reguest and response to any translate service/api. 

My desired scheme like =

user-request-box -> translate service -> llm/rag_pipeline -> translate service -> user-response-box

**Comment by ejgutierrez74** [comment]
+1 Is there anyway to change the worksapace llm language to other than english ? Spanish or catalan ?

**Comment by timothycarambat** [comment]
Use a system prompt to drive a language behavior like that. That is where those kind of behavioral rules should go. Some models are smart enough to infer it from your prompt language, but is the system prompt is in English (default) and the prompt is in Spanish, it may still respond in english.
