### ISSUE TITLE
[BUG]: upload endpoint missing in api

### ISSUE THREAD

**Issue by vinaypri** [Mintplex-Labs/anything-llm#1372]
### How are you running AnythingLLM?

Not listed

### What happened?

When I try to upload a document, browser inspect shows that http://128.199.28.108:3001/api/workspace/workspace-test/upload is not found. I checked the server/endpoints/api/workspace/index.js file and I don't find the upload endpoint defined in it. Am I missing anything?
This is a non docker server installation.

### Are there known steps to reproduce?

You may try at http://128.199.28.108:3001/

**Comment by timothycarambat** [comment]
Uploading is in document, not workspace. 
We _embed_ a document into a workspace. You dont upload a document into a workspace

https://github.com/Mintplex-Labs/anything-llm/blob/948ac8a3ddd61919b1f333c544b3b593d6b61343/server/endpoints/api/document/index.js#L24

Also, you can visit `http://YOUR_IP_URL:3001/api/docs` and see every endpoint and its explaination

**Comment by vinaypri** [comment]
But inspect shows that the call is made to workspace/upload when I place a
document in the upload area. Attached screenshot shows it.

**Comment by vinaypri** [comment]
You may ignore my message. It was a settings issue, have sorted it out.
Thanks and sorry to bother.
