### ISSUE TITLE
[BUG]: copy code button has js console error and doesn’t work. 

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1376]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![IMG_1771](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/f28aa135-14b9-4374-9193-628f95fd3965)
![IMG_1770](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/9cf8a420-8fb8-47aa-9597-75224356b94b)

### Are there known steps to reproduce?

Host on docker. Visit from another computer via browser. Inference. Copy code button. Paste. Nothing was copied. Console error.

**Comment by timothycarambat** [comment]
Not a bug. You either have clipboard permission denied or your browser does not support the clipboard API. 
https://github.com/Mintplex-Labs/anything-llm/issues/1136

**Comment by atljoseph** [comment]
Am accessing a home server from chrome on Mac. We use js clipboard for
work. It works fine on our website. I don’t guess having built from
dockerfile manually would have changed anything there? Guessing not at all.
So, not sure what to say. If it works on one site, then is not permissions
issue. And clipboard is at home with chrome. Anyways, thanks for responding
