### ISSUE TITLE
[BUG]: Security vulnerability

### ISSUE THREAD

**Issue by mnqazi** [Mintplex-Labs/anything-llm#1384]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I've reported 2 vulnerabilities on [huntr.com](http://huntr.com/)

Please have a look and validate the same.

1. https://huntr.com/bounties/f786481c-5837-40ca-b830-6f327a47d9da
2. https://huntr.com/bounties/8ec14991-ee35-493d-a8d3-21a1cfd57869

**Comment by timothycarambat** [comment]
Please **do not** make a bug issue for us to just check the Huntr bug bounty. This is considered spam. We check it at least once a month and will be assessed and triaged then. The Huntr team emails us about the reports, so we do not need any other reminder or notification
