### ISSUE TITLE
[FEAT]: GPT-4o support

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1389]
### What would you like to see?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/163884933/c27032fa-9a8c-4d1f-9511-0e9582f7c8d3)

**Comment by timothycarambat** [comment]
It is already live in the App and you can select it via the dropdown. When OpenAI opens up a model it automatically appears in the dropdown!

We probably will need to add a specific context window though

**Comment by RahSwe** [comment]
@timothycarambat Thank you! Now testing and it is really speedy. Think this will be great and a great combo with embeddings by Voyage AI-models
