### ISSUE TITLE
[BUG]: Document Processor Unavailable

### ISSUE THREAD

**Issue by lpapm** [Mintplex-Labs/anything-llm#1396]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I have installed the desktop app on windows 11. However, I can not upload files as it says "Document Processor Unavailable". I have checked and there seems to be no other app locking the port 8888 (i saw this issue in another case). This is the log that I get:
[Preferences] preference config stored at C:\Users\pmarcial\AppData\Roaming\anythingllm-desktop\config.json
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:C:/Users/pmarcial/AppData/Roaming/anythingllm-desktop/storage/anythingllm.db"

Already in sync, no schema change or pending migration was found.

Running generate... (Use --skip-generate to skip the generators)
Error: request to https://binaries.prisma.sh/all_commits/61e140623197a131c2a6189271ffee05a7aa9a59/windows/query_engine.dll.node.gz.sha256 failed, reason: unable to get local issuer certificate
Prisma schema loaded from prisma\schema.prisma
Error: request to https://binaries.prisma.sh/all_commits/61e140623197a131c2a6189271ffee05a7aa9a59/windows/query_engine.dll.node.sha256 failed, reason: unable to get local issuer certificate
[OllamaProcessManager] Ollama will bind on port 11434 when booted.
[Preferences] Will load window with last know bounds.
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'uc.micro'
Require stack:
- C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\linkify-it\build\index.cjs.js
- C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mailparser\lib\mail-parser.js
- C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mailparser\index.js
- C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mbox-parser\dist\Parser.js
- C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mbox-parser\dist\index.js
- C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\collector.js
-
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/utility_init:2:3040)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\pmarcial\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\linkify-it\build\index.cjs.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pmarcial\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\linkify-it\\build\\index.cjs.js',
    'C:\\Users\\pmarcial\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mailparser\\lib\\mail-parser.js',
    'C:\\Users\\pmarcial\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mailparser\\index.js',
    'C:\\Users\\pmarcial\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mbox-parser\\dist\\Parser.js',
    'C:\\Users\\pmarcial\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mbox-parser\\dist\\index.js',
    'C:\\Users\\pmarcial\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\collector.js',
    undefined
  ]
}

Node.js v18.16.1
[TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
prisma:info Starting a sqlite pool with 13 connections.
[TELEMETRY SENT] {
  event: 'server_boot',
  distinctId: '7db27ce0-ff71-4c25-aa82-62f048e8d0f7',
  properties: { runtime: 'desktop' }
}
Hot loading of AnythingLLMOllama - LLM_PROVIDER is anythingllm_ollama.
[NativeEmbedder] Initialized
[CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.
[production] AnythingLLM Standalone Backend listening on port 3001
[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.
[OllamaProcessManager] [windows] Ollama subprocess running. Port 11434. PID 20328.
OllamaAPI offline - retrying. 1/3

**Comment by timothycarambat** [comment]
Does your Windows machine have internet access? Nobody else has these issues on windows so I'm thinking this must be environment-related to some degree. Considering that the prisma binaries also fail, I'm thinking its related to why uc.micro also is not resolving

**Comment by lpapm** [comment]
Thanks Timothy for your reply. Windows has access to internet but I'am thinking that security system installed by my company must be blocking the access of the app to internet :(
I am going to install the app in a different computer without the company's security system.

**Comment by timothycarambat** [comment]
This has occurred before and it was due to some obscure anti-virus on the machine, when installed on a "normal" consumer device without crazy corporate controls it worked fine! Continue to comment if you keep running into issues on a more consumer-level machine
