### ISSUE TITLE
[BUG]: LLAMA3 not using GPU 

### ISSUE THREAD

**Issue by kalilfagundes** [Mintplex-Labs/anything-llm#1398]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hello, everyone!
I installed the desktop app today (Windows) and runned it using llama3 7b. The question is that the model isn't using my GPU, but my CPU and I can't find the reason why. I already setted the executable to run on GPU in Nvidia Control Panel, but it didn't worked.
My GPU is Nvidia GeForce RTX 3050.

**Comment by timothycarambat** [comment]
The built in LLM engine for AnythingLLM is [actually Ollama](https://ollama.com). Do you have Ollama on the same machine and does ollama outside of AnythingLLM use GPU?

If not, I'm thinking you may not have CUDA installed and the bindings are not being found to load and run models with GPU-layers

**Comment by kalilfagundes** [comment]
> The built in LLM engine for AnythingLLM is [actually Ollama](https://ollama.com). Do you have Ollama on the same machine and does ollama outside of AnythingLLM use GPU?
> 
> If not, I'm thinking you may not have CUDA installed and the bindings are not being found to load and run models with GPU-layers

That's correct, I misspelled it! I don't have other Ollama installed in my machine and I'm not running any other instance of Ollama in my computer. I have CUDA installed!

![image](https://github.com/Mintplex-Labs/anything-llm/assets/92411438/2588c7c0-205a-4da5-8baf-91e9bb0473b4)

**Comment by kalilfagundes** [comment]
> Title

I have no other Ollama instances and I have CUDA installed!

**Comment by timothycarambat** [comment]
This seems like something Ollama needs to work on and not something we can manipulate directly via the built-in
https://github.com/ollama/ollama/issues/3201

It may be worth installing Ollama separately and using that as your LLM to fully leverage the GPU since it seems there is some kind of issues with that card/CUDA combination for native pickup. I'm on an NVIDIA 4090 and it finds my GPU and offloads accordingly

**Comment by kalilfagundes** [comment]
> This seems like something Ollama needs to work on and not something we can manipulate directly via the built-in [ollama/ollama#3201](https://github.com/ollama/ollama/issues/3201)
> 
> It may be worth installing Ollama separately and using that as your LLM to fully leverage the GPU since it seems there is some kind of issues with that card/CUDA combination for native pickup. I'm on an NVIDIA 4090 and it finds my GPU and offloads accordingly

I did installed it separately and it seems that it's using my GPU now and acting faster. Good thing also since I will also integrate the Ollama with other softwares, it was the right decision.

Thanks, timothy.

**Comment by timothycarambat** [comment]
@kalilfagundes No problem, im sorry you came across that. The native GPU stuff can be tricky and our built-in makes things easy to get going but is certainly not foolproof, but there is always a way forward while staying local

**Comment by Nododot** [comment]
Same problem here, on Windows 11.
Ollama installed on WSL2 uses my Nvidia GPU, but AnythingLLM doesn't.
Tried llama3 and mistral, same outcome.
All software is up-to-date.
Nvidia GTX 1070, Ryzen 5600x.

**Comment by timothycarambat** [comment]
@Nododot - the issue here is almost certainly being on WSL. If you use the Ollama windows app on the host machine outside WSL it will bind to GPUs, otherwise raise an issue on [Ollama's repo](https://github.com/ollama/ollama) as that would be out of scope for us anyway on this repo

**Comment by byzheng** [comment]
anything-llm will use GPU for ollama just adding `C:\Users\<user-name>\AppData\Local\Programs\AnythingLLM\resources\ollama` to the TOP of environment variable `PATH`.

**Comment by GF-Huang** [comment]
Is this work as expected? High CPU high RAM high VRAM usage, but low GPU usage. Is it working on GPU?

![image](https://github.com/user-attachments/assets/4748b174-13c2-493d-89b1-e869ba0ccde3)

**Comment by 1314XIAN** [comment]
I also have the same problem, so I want to know how to using the GPU.
Because this I buy a new card, but it's using the cpu right now.

**Comment by timothycarambat** [comment]
We use Ollama to run on the GPU - did the ollama_lib files during installation install? You should have seen them download - this enables NVIDIA/AMD GPUs to work. Otherwise it will be stuck on CPU

**Comment by Aleksahek** [comment]
how to use 100% gpu and 100% memory?
```
     
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC       |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+============|
|   0  NVIDIA GeForce RTX 2060        On  |   00000000:03:00.0  On |                  N/A |
| 29%   45C    P2             44W /  172W |    3992MiB /   6144MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=====================================================|
|    0   N/A  N/A     42153      C   ...rs/cuda_v12_avx/ollama_llama_server       3980MiB |
+-----------------------------------------------------------------------------------------+

```
