### ISSUE TITLE
port 5000 is in use by default in macOS Monterey

### ISSUE THREAD

**Issue by wouterverweirder** [Mintplex-Labs/anything-llm#14]
in macOS Monterey, port 5000 is used by default (Airplay Receiver). This causes the dev server not to launch, and the frontend to receive 403 errors (from the Monterey Airplay service).

My suggestion would be to set the default / fallback port of the server process to 3001 instead of 5000.

**Comment by timothycarambat** [comment]
Good call, patched now. Wasnt aware that was the case!
