### ISSUE TITLE
[FEAT]: Ability to delete messages from conversation history 

### ISSUE THREAD

**Issue by frost19k** [Mintplex-Labs/anything-llm#1408]
### What would you like to see?

Ability to delete messages from the conversation history, both user and assistant. 

Sometimes the assistant will spaz out and...

```
    {
      "role": "assistant",
      "content": "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    },
```

Every prompt after that will result in nonsense. But if I ask the same question in a new thread I get a good response. So I figure if that particular prompt and response pair were removed I can salvage the conversation history.

**Comment by igmarketing** [comment]
+1 for this... also a feature to edit and resubmit a different message. Better ChatGPT have this, even ChatGPT. It's a must-have feature!

**Comment by timothycarambat** [comment]
@igmarketing 
> +1 for this... also a feature to edit and resubmit a different message

we already have this
- edit user message and resubmit from that message (any) - just hover over any user message
- Edit LLM response for correctness - shown via pencil icon on any LLM response

Deletion is covered by this issue

**Comment by yhslai** [comment]
+1 for this.

No, editing isn't the same as deleting.

**Comment by timothycarambat** [comment]
@yhslai I wasn't implying editing === deleting. That is why this issue remains open! It is to track that specific feature. All I was commenting on what the other chat functions are since this issue covered a request for both editing and deleting. We did editing so this issue is not solely on deletion 👍
