### ISSUE TITLE
[Question] LLM Context Window per Workspace

### ISSUE THREAD

**Issue by ShadowArcanist** [Mintplex-Labs/anything-llm#1413]
Let's say I am using Olllama as LLM Provider and have following models installed:
- Yarn Mistral >> 128K Context Window
- Mistral 7B >> 32K Context Window
- Llama 3 8B  >> 8K Context Window

So I have 3 Workspaces -- A, B, C and I use:
- Yarn Mistral 128K on Workspace A
- Mistral 32K on Workspace B
- Llama 8K on Workspace C

AnythingLLM only have option to set model context window on LLM Preference on settings menu but on Workspace Settings I only have option to choose the Model. 

So if I set 8K context window limit on LLM Preference on settings menu and use "Yarn Mistral 128K on Workspace A" then I will be only using 8K context window since it is what I set on Settings, I can't use the rest of 120K when using Yarn Mistral.

What should I do in this situation? 🤔

**Comment by timothycarambat** [comment]
Would need to be done via https://github.com/Mintplex-Labs/anything-llm/issues/970
