### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by yongshengma** [Mintplex-Labs/anything-llm#1419]
Hello

I followed this info to setup on Ubuntu 22:

 https://github.com/Mintplex-Labs/anything-llm?tab=readme-ov-file#how-to-setup-for-development 

When I access the the browser, it gives error: SSL_ERROR_RX_RECORD_TOO_LONG

node -v
v18.20.2

Any idea please?

Sincerely,

Yongsheng

**Comment by atljoseph** [comment]
Don’t use localhost when using docker

**Comment by atljoseph** [comment]
See markdown file in docker dir

**Comment by atljoseph** [comment]
This really is not an issue with anything LLM. It is just how networking works in general for docker containers. I understand your frustration as I too lost time to this error recently.

**Comment by atljoseph** [comment]
No idea sorry

**Comment by timothycarambat** [comment]
@yongshengma 
Are you using NGINX? This is an NGINX error, not AnythingLLM.

In your server block for HTTP are you using `listen 443 ssl;`? Some people just put `listen 443` which listens on the port but is the SSL port standard and will lead to issues like that.

**Comment by yongshengma** [comment]
> @yongshengma Are you using NGINX? This is an NGINX error, not AnythingLLM.
> 
> In your server block for HTTP are you using `listen 443 ssl;`? Some people just put `listen 443` which listens on the port but is the SSL port standard and will lead to issues like that.

it could be somewhere I didn't config correctly.  I didn't use nginx. 

Please let me give more details.

1. env
cd anything-llm-master
cat frontend/.env
      VITE_API_BASE='/api' 

2. yarn setup
3. yarn dev:server 

yarn run v1.22.22
$ cd server && yarn dev
$ NODE_ENV=development nodemon --ignore documents --ignore vector-cache --ignore storage --ignore swagger --trace-warnings index.js
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --trace-warnings index.js`
$ node ./swagger/init.js
[TELEMETRY STUBBED] Anonymous Telemetry stubbed in development.
[CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.
Primary server in HTTP mode listening on port 3001
Swagger-autogen:  Success ✔ 
Swagger-autogen:  Patched servers.url ✔

4. yarn dev:frontend
5. yarn dev:collector
6. http://192.168.6.116:3001/

When I access the URL, it responds: 404 Not Found

No nginx.  

Thanks!

**Comment by timothycarambat** [comment]
Are you trying to run the service in production or in development? Looks like you are running the server in development mode in which case the frontend needs to be run separately and will be on port 3000 `yarn dev:frontend`.

If you are trying to run this in production you should only be running `yarn prod:server` and only be running this after `yarn prod:frontend && cp -R frontend/dist server/public`.

Then the frontend will be bundled and present in `server/public` and the whole app will live on 3001

**Comment by yongshengma** [comment]
> Are you trying to run the service in production or in development? Looks like you are running the server in development mode in which case the frontend needs to be run separately and will be on port 3000 `yarn dev:frontend`.
> 
> If you are trying to run this in production you should only be running `yarn prod:server` and only be running this after `yarn prod:frontend && cp -R frontend/dist server/public`.
> 
> Then the frontend will be bundled and present in `server/public` and the whole app will live on 3001

Hi Timothy

I was trying to run in development and I can access localhost:3000 now. Thanks!

But when I run in production, I get an issue:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/17973897/9afc4144-0fd1-4d9b-971b-948932a90a32)

Any idea please?

**Comment by yongshengma** [comment]
@timothycarambat 

I find it's caused by STORAGE_DIR. Now I can start it up in production by following the steps you gave. Appreciate!

Sorry to abuse this post as a newbie. Just one more question. Where's the login page or user front?

**Comment by atljoseph** [comment]
The way the storage dir works between the normal and the render image is a
bit odd. I fought and fought with the normal image the longest time. Tim
mentioned the render image, and that worked great, but not 100% sure why
both images are needed. Maybe the render image is helpful to you. Maybe
not.

**Comment by yongshengma** [comment]
@atljoseph

**Comment by yongshengma** [comment]
@atljoseph 
The error points clearly to the storage dir. I guess we are talking about different things. Anyway I still have the problem on remote access 3000 or 3001 even though I modified in frontend/.env as:
 
```
# VITE_API_BASE='http://localhost:3001/api' # Use this URL when developing locally
# VITE_API_BASE="https://$CODESPACE_NAME-3001.$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN/api" # for Github Codespaces
VITE_API_BASE='/api' # Use this URL deploying on non-localhost address OR in docker.
```
i'm trying to do more research before ask new questions.
