### ISSUE TITLE
[Improvements]: Embedding documents should not be blocked by LLM settings

### ISSUE THREAD

**Issue by jazelly** [Mintplex-Labs/anything-llm#1420]
### What would you like to see?

When a workspace using default settings, embedding documents from `stroage` is prevented due to missing setup OpenAI key.
Correct me if I'm wrong, but my understanding is embedding documents shouldn't involve a language model but an embedding model, which is pulled from HF.

**Comment by jazelly** [comment]
@timothycarambat I didn't select any LLM so I think it's the system default LLM, which I suppose it's the OpenAI one?

**Comment by timothycarambat** [comment]
How did you get past onboarding without selecting an LLM?

**Comment by jazelly** [comment]
You can create a new workspace without specifying any LLM, and I was embedding documents on the new workspace.
