### ISSUE TITLE
How can I make the workspace and documents persist across different environments?

### ISSUE THREAD

**Issue by ajosegun** [Mintplex-Labs/anything-llm#143]
I noticed it always create brand new instance whenever I install it on different environments.

For example, I initially installed anything-llm on my local machine, created workspaces and documents but when I had to install anything-llm on GCP, I had to recreate the workspaces and documents again. Then, I moved to Digital Ocean, I had to recreate the workspaces and documents once again.

Note that I used the same .env details across each installation.

Am I doing something wrong?

Expected result:
I should automatically find the workspaces and documents I created on a new environment

**Comment by TychoML** [comment]
@ajosegun I was thinking of implementing your clear instruction on how to use anything-llm on GCP. Is there a notable benefit for deploying it on Digital Ocean instead? If so I would be much interested to know more if that is OK with you. Thanks in advance!

**Comment by timothycarambat** [comment]
> @ajosegun I was thinking of implementing your clear instruction on how to use anything-llm on GCP. Is there a notable benefit for deploying it on Digital Ocean instead? If so I would be much interested to know more if that is OK with you. Thanks in advance!

Deploying on AWS v GCP v XYZ is just a matter of preference

**Comment by timothycarambat** [comment]
@ajosegun Just want to clarify you basically would like a way to backup/upload an entire environment from instance to instance - correct?

**Comment by ajosegun** [comment]
@timothycarambat yes, a way to backup/upload an entire environment from instance to instance

**Comment by ajosegun** [comment]
> @ajosegun Just want to clarify you basically would like a way to backup/upload an entire environment from instance to instance - correct?

Yes

**Comment by ajosegun** [comment]
Maybe a way to persist the Workspace DB outside the volume.

**Comment by timothycarambat** [comment]
@ajosegun roger that

https://github.com/Mintplex-Labs/anything-llm/issues/145

Working on it now

**Comment by ajosegun** [comment]
Thanks for working on this so fast.

I just tried it and I am getting "{"error":"No auth token found."}" 
Note that I hosted it on GCP with AUTH_TOKEN and JWT_SECRET set in the .env file

<img width="228" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/94995067/3d4a9394-c82e-4afd-a1cf-0ec4178c8f66">
