### ISSUE TITLE
[BUG]: Embedding Chat talks to Useanything hosted website

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#1431]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The embedding chat feature which should ideally talk to my locally running model is actually talking to the useanything website. Though I liked the response time, I still need it to be secure and local. Thanks

**Comment by timothycarambat** [comment]
> The embedding chat feature 

Are you referring to the HTML widget that can be embedded? I am unsure what you mean by saying "is actually talking to the useanything website" and " I still need it to be secure and local"
