### ISSUE TITLE
[FEAT]: Custom login screen icon

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#1432]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Earlier logo as uploaded by the administrator was being used but now anythingllm logo is being displayed. The reference to anythingllm can be made a little more subtle.
![Screenshot 2024-05-17 104902](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/2e655a1e-cdb7-4a2b-8e4a-7c12bf93d028)

**Comment by timothycarambat** [comment]
This is known, it was part of the new redesign, there will be a separate icon for the new login page now since its container is smaller

**Comment by cmarina** [comment]
An option to customize the text and background image would be nice too!
