### ISSUE TITLE
[BUG]: Gemini Encountering 500 Internal Server Error on Content Generation

### ISSUE THREAD

**Issue by chalitguza** [Mintplex-Labs/anything-llm#1433]
### How are you running AnythingLLM?

All versions

### What happened?

I ran into an issue while trying to generate some content. I got the following error message:

`[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [500 Internal Server Error] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting`

It seems like an internal server error. Could someone look into this and let me know what might be causing it or if there's something I should do on my end?

Thanks!

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/be54397d-9b5d-4164-9a7d-3aa2d96a0362)

**Comment by timothycarambat** [comment]
Bizarrely enough, this is **not** from AnythingLLM. It's directly from Google! Did they have downtime recently? As the error message suggests this might need to be posted or better answered on 

> Please retry or report in https://developers.generativeai.google/guide/troubleshooting

**Comment by bestZwei** [comment]
Gemini's problem

**Comment by lekte** [comment]
how did you fix this?
