### ISSUE TITLE
[Question] - Keeping files in sync

### ISSUE THREAD

**Issue by dazinator** [Mintplex-Labs/anything-llm#1435]
I use `logseq` for note taking.
It has a notes directory on my machine, and inside it has `markdown` files for all my pages etc.
I am running on docker.

At the moment, as my notes change, I have to manually re-upload the markdown files through the web ui.

Is there some sort of file based sync mechanism available, so for example, I could detect changes to files from a directory and "update" them in anything-llm?

**Comment by timothycarambat** [comment]
This will be accomplished via https://github.com/Mintplex-Labs/anything-llm/issues/1129!

Agreed it would be great to have, currently, you need to manually update them. That issue, when closed will enable you to select files to be auto-synced locally on some `cron`-like scheduler that can run.
