### ISSUE TITLE
[FEAT]: Generic OpenAI API for embeddings

### ISSUE THREAD

**Issue by frost19k** [Mintplex-Labs/anything-llm#1436]
### What would you like to see?

Currently, we have an option to select a Generic OpenAI API server, let's say `huggingface/text-generation-inference`, but there's no option for a generic API server for embeddings, e.g. `huggingface/text-embeddings-inference`.

**Comment by alexanderMal** [comment]
Hey this is the feature I already mentioned in Ticket #1269.
Somehow the other ticket got missused and closed. So Upvote for this one here.

**Comment by timothycarambat** [comment]
@alexanderMal I must have typed in the wrong issue number and closed it by mistake!
