### ISSUE TITLE
[FEAT]: a Number: Agent persistance, Store of prompts, Delete Workspaces, a repeat function which can be used on timer

### ISSUE THREAD

**Issue by PietFourie** [Mintplex-Labs/anything-llm#1437]
### What would you like to see?

I would like to suggest the following features:
1) Once an agent has been activate, say for scraping the web, it should remain in "agent" mode and a toggle can be used to switch between agent mode or LLM mode. Using agent does not always result in immediate success and hence it is cumberson to always select @agent. Call this persistent "agent" mode
2) I can not find the button nor option to delete a  workspace.
3)  If one would like to daily download a web site then one would like to store prompts or a library of prompts.
4) A schedule or timer can be added to do the action, research or actuate the prompt each day/week/month at a specific time
5) I run the Linux  appimage file but I have no control on where the database or files are stored. I would like to have control over that since HDD get sometimes full.
All in all it is a brilliant program. Thanks a lot for the effort. :-)

**Comment by timothycarambat** [comment]
REF: Points 1,3,& 4
- This is going to be accomplished via in https://github.com/Mintplex-Labs/anything-llm/issues/1129
Will have the ability to auto-sync local and website data connections on some interval basis

> 2. I can not find the button nor option to delete a workspace.
Click on the gear icon on the workspace
<img width="822" alt="Screenshot 2024-05-17 at 10 41 34 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/79f8f7b4-be42-4a0b-ba42-7d8fc152ec00">


> I run the Linux appimage file but I have no control on where the database or files are stored. I would like to have control over that since HDD get sometimes full.

Usually, this is located in `~/.config/anything-llm/storage`!
