### ISSUE TITLE
[BUG]: Issues with Recording Knowledge in the Database

### ISSUE THREAD

**Issue by chalitguza** [Mintplex-Labs/anything-llm#1441]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The content contains special characters, making it impossible to save in the knowledge database.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/5891b774-9fbc-4ab9-9b5f-5f8295810cf1)

**Comment by timothycarambat** [comment]
This is not what that error means. This means the backend crashed while processing the document. Are you running this locally on Docker or using some other service like Render or Railway to run this?

Often, this can happen if the container reaches its CPU/memory limit and kills the background process for the collector script.

**Comment by chalitguza** [comment]
> This is not what that error means. This means the backend crashed while processing the document. Are you running this locally on Docker or using some other service like Render or Railway to run this?
> 
> Often, this can happen if the container reaches its CPU/memory limit and kills the background process for the collector script.

Okay.

But!

It seems that when an unexpected error occurred, the data was not deleted, even though I had already removed it from the "My Documents" page. Perhaps some additional conditions need to be added to the process.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/992b7b3d-d392-4802-ab17-4a53dee0a4c1)


![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/8545c735-8ba2-4e75-8d8e-4f2964ad2372)
