### ISSUE TITLE
How to use embedding models downloaded from hugging face

### ISSUE THREAD

**Issue by guijuzhejiang** [Mintplex-Labs/anything-llm#1446]
Nice work!when loading the models, I have to go through such encapsulated models like openAI, Ollama, etc. before I can load them, how do you call them directly if they are downloaded from hugging face?

**Comment by timothycarambat** [comment]
You have downloaded a model, probably a GGUF? You should use some kind of LLM provider to "run" it and AnythingLLM can connect to it. LocalAI and LMStudio both have setups where you can easily install and run any HF Model and AnythingLLM integrates with both 👍

**Comment by guijuzhejiang** [comment]
@timothycarambat Thanks, I will try LMStudio
