### ISSUE TITLE
[FEAT]: General UI Feedback

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1454]
### What would you like to see?

Apologies for the novel here. Stick with it though :) Isn’t as big of an ask as it seems. Thanks

![wimage](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/124ec743-c5de-4205-9500-04ded419f589)

First. 
New threads get the title of New Thread. That’s fine by itself. But not when the button to create a new thread goes by the same call sign on the screen. It’s too repetitive, and too close together. One thing *is* something while another *does* something… in the same spot. Not everybody takes the time to rename the threads. It would serve folks better to have a pretty timestamp as the initial name of the thread. That way, they can tell a bit more context than New Thread. This would take very little time to tweak. Moment to the rescue. This week, I must have clicked the New Thread button 50 times to open an existing thread only to find out it opened another thread. They multiply like rabbits because the eyes can’t tell them apart. 

Second. 
The button named New Thread isn’t so bad by itself. It *is* clunky & redundant verbiage, though, and paired with the plus sign, and being a chat, it is very obvious what it does. In fact, the 2 extra words contribute to a more busy ui. If that is desired, then hey, whatever. It isn’t my product. But after using it a while, honestly, seeing “New Thread” “New Thread” all over the place… it’s a bit tiring to look at and use. I’m sure that is not the feeling you want it to invoke. The New Workspace button’s core color is a perfect starting color for the button to add a new thread. If you’re looking for an alternative or another riff to my suggestion above, maybe wrap the New Thread text up inside a white button with the plus sign (exactly like the New Workspace button - hey theming!) and then extend the workspace “tree” down to the button. 

Third. 
The new workspace button color is great, but for being such a big button in the top of the screen it is a little “loud” and top-heavy feeling. It makes all the other buttons not as interesting, especially when it precedes them . Could you keep the color but mute it a bit? To be completely honest, I think the best thing to do here is swap the color scheme of the new workspace button with the color scheme of the currently selected workspace. That way a user’s eye is drawn to the thing they are working on instead of distracting them. 

Welp, there’s my thoughts after spending a week straight looking at it every day. And hopefully you have some ideas flowing for making things look more polished. 

I have a lot more feelings on the ui in general too, if you’re interested. Dropped some suggestions into discord, focused on the document indexing/upload modal. 

We are about to deploy a customer chat bot using anythingLLM this summer, so looking forward to using it more and getting set up in k8s. 

![image](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/502daca9-63b1-4219-886c-d72863fbcfcb)

**Comment by chalitguza** [comment]
I completely agree with your points regarding the UI, especially on the need for improvements. The repetition of the "New Thread" title and button is indeed confusing and can make navigation cumbersome. An initial timestamp for new threads would definitely provide more context and reduce unnecessary confusion.

The suggestion to streamline the button labeling and adjust color schemes to draw attention more effectively is spot-on. Simplifying the "New Thread" button while aligning it with existing themes can make the interface cleaner and more user-friendly.

Overall, these enhancements would certainly make the user experience more intuitive and visually appealing. Looking forward to seeing these improvements!

**Comment by atljoseph** [comment]
Wow those are pretty slick tools that are self hostable. I’m gonna check those out tonight for the fun of it. Not sure if they have all the features of anything LLM but they are def good to draw inspiration from. 

Not really in the exact same space, but have been using plandex recently. Badass, if you like CLI-only tools. Am always curious down much ai devs use to bootstrap their ai tools.
