### ISSUE TITLE
[FEAT]:  RAG with Graph

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1456]
### What would you like to see?

Support for RAG with graph functionality.

https://python.langchain.com/v0.1/docs/use_cases/graph/constructing/
https://neo4j.com/labs/genai-ecosystem/llm-graph-builder/

**Comment by timothycarambat** [comment]
Moved to https://github.com/Mintplex-Labs/anything-llm/issues/1008
