### ISSUE TITLE
[BUG]: openai embedding does not work

### ISSUE THREAD

**Issue by YuchenGUOGYC** [Mintplex-Labs/anything-llm#1462]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

After I set up the Openai text-embedding-ada-002 as Embedding Provider, 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/42795847/19bc711d-36d0-4edd-97bb-61b4126d676b)
then I upload a PDF  into the workshop, then I save and embed.
then I ask what is the context in the pdf, it return error like below:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/42795847/bc719d28-6887-475d-8a39-59352da499e4)
it seem local lanceDB does not support the openai embedding?

**Comment by timothycarambat** [comment]
This is not a bug, this occurs when the following occurs:
- You create a workspace
- Embed a document with native embedder into the workspace (creates vector table with 384 dimensions)
- You remove document from workspace, change embedder, and upload new document with new embedder (1536 dimensions)
- This upsert is successfully, but now the table schema and the embedded dimensions do not match and LanceDB does not error on this
- You send a chat, which is embed searched with the same new embedder, and now the column is unknown.

Solution: Go to workspace settings -> Vector Database -> Reset Vector database
Re-embed document and it will be OK

**Comment by YuchenGUOGYC** [comment]
thanks for the help, it works this time!
