### ISSUE TITLE
[BUG]: Microsoft Defender SmartScreen blocking Windows installation

### ISSUE THREAD

**Issue by scign** [Mintplex-Labs/anything-llm#1469]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Attempted install on Windows and got the following message:

<html><body><div class="main-title" id="messageTitle" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 28px; font-style: normal; font-variant: normal; font-weight: bold; letter-spacing: normal; margin-bottom: 20px; margin-left: 0px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">Windows protected your PC</div><span style="display: inline !important; float: none; background-color: rgb(0, 90, 158); color: rgb(255, 255, 255); direction: ltr; font-family: &quot;Segoe UI light&quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; overflow-wrap: break-word; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
</span><div class="main-desc" id="messageBody" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 15px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0px; margin-left: 2px; margin-right: 0px; margin-top: 0px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.</div><span style="display: inline !important; float: none; background-color: rgb(0, 90, 158); color: rgb(255, 255, 255); direction: ltr; font-family: &quot;Segoe UI light&quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; overflow-wrap: break-word; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
</span><div id="moreBtnContainer" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        
</div><span style="display: inline !important; float: none; background-color: rgb(0, 90, 158); color: rgb(255, 255, 255); direction: ltr; font-family: &quot;Segoe UI light&quot;; font-size: 16px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; orphans: 2; overflow-wrap: break-word; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
</span><div id="moreInfoContainer" style="color: rgb(255, 255, 255); direction: ltr; font-family: &amp;quot;Segoe UI light&amp;quot;; font-size: 15px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-top: 10px; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; width: 75%; word-spacing: 0px;">
        
App: | AnythingLLMDesktop.exe
-- | --
Publisher: | Unknown publisher

</div></body></html>

Possibly related:
* https://github.com/ModOrganizer2/modorganizer/issues/2005
* https://www.theregister.com/2020/06/05/windows_10_microsoft_defender_smartscreen/

### Are there known steps to reproduce?

Attempt installation with Microsoft Defender SmartScreen installed

**Comment by timothycarambat** [comment]
We say this right at the top for Windows install
https://docs.useanything.com/getting-started/installation/desktop/windows

The app is unsigned, which is why you see this message

**Comment by timothycarambat** [comment]
We updated the docs a long time ago https://docs.anythingllm.com/installation/desktop/windows

**Comment by b-a0** [comment]
https://docs.anythingllm.com/installation/desktop/windows now also 404's  
New link is: https://docs.anythingllm.com/installation-desktop/windows
