### ISSUE TITLE
[BUG]: 'max_tokens' is String in Generic OpenAI, but the api requires Integer.

### ISSUE THREAD

**Issue by buptsad** [Mintplex-Labs/anything-llm#1471]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I try to set the qwen-long model, which is the model in Issue #1308 
However after setting up using Generic OpenAI setting max_tokens to 1024, it returns `400 'max_tokens' is must be Integer`.

**Comment by timothycarambat** [comment]
This has been fixed already but is not in the desktop app and will be in the next version. If you need this urgently edit the file in
`/Users/<usr>/Library/Application Support/anythingllm-desktop/storage/.env` on Mac
`/Users/<usr>/AppData/Roaming/anythingllm-desktop/storage/.env` on Windows

edit `GENERIC_OPEN_AI_MAX_TOKENS` to be a number - no quotations and save. Restart App.

**Comment by lchyn** [comment]
change /Users/<usr>/AppData/Roaming/anythingllm-desktop/storage/.env， it doesn't work.

Found a temporary solution that worked：
\Users\***\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js
at line 9060:  this.maxTokens = process.env.GENERIC_OPEN_AI_MAX_TOKENS ?? 1024;
change to : this.maxTokens = 1024; 

restart application.
