### ISSUE TITLE
[FEAT]: Search feature for "My Documents" section

### ISSUE THREAD

**Issue by dctmfoo** [Mintplex-Labs/anything-llm#1474]
### What would you like to see?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/128729140/bfbabed3-4baf-484d-abcc-2aacbdeef73d)
I would like to have a search feature somewhere on the "My Documents" section so i can do a search based on name or extension of a document. Full Text search might be an overkill though but nice to have.

**Comment by timothycarambat** [comment]
This is something we already have designed internally and was going to be done soon anyway.
<img width="1512" alt="Settings Search Bar" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/b3428416-70b6-40a3-b8e4-329003e35c65">
