### ISSUE TITLE
[FEAT]: API in swagger for agents

### ISSUE THREAD

**Issue by Nurai1** [Mintplex-Labs/anything-llm#1488]
### What would you like to see?

I would like to webscrapping from api, not only from the Aythin LLM UI

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anythingllm-docs/issues/27
See https://github.com/Mintplex-Labs/anything-llm/issues/1484

> The @agent directive is not available in the API because there is no way to halt the worker since there is no "Stop generation" via the API to prevent runaway agents, which can occur with Open-source models, we don't have agents in the API yet.
> 
> They would be able to be used via a separate endpoint or body parameter so we can be sure you have the controls needed to prevent any kind of agent runaways!

Unless you are simply just asking to be able to scrape a link via the API, which does exist via `/documents/upload-link`

**Comment by Nurai1** [comment]
Thank you @timothycarambat
