### ISSUE TITLE
[BUG]: AnythingLLM Appimage not working on Kubuntu 24.04 after upgrade

### ISSUE THREAD

**Issue by zorin1** [Mintplex-Labs/anything-llm#1490]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When I run the appimage this the error that I get:
./AnythingLLMDesktop.AppImage 
[5392:0522/123545.151532:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Anythipva25Z/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

### Are there known steps to reproduce?

Just running the appimage.

**Comment by timothycarambat** [comment]
This is not a bug with AnythingLLM and is a client-side config issue on your OS + Electron (what the app uses)
https://github.com/electron/electron/issues/17972

Also, since you are trying to run the AppImage, you should be aware of https://github.com/Mintplex-Labs/anything-llm/issues/898 which effects all Linux distros

**Comment by Uzo-Felix** [comment]
# Verify Ownership and Permissions

```
ls -l /path/to/anythingllm/chrome-sandbox
```

> Replace `/path/to/anythingllm/chrome-sandbox` with the actual path to the `chrome-sandbox` binary within your AnythingLLM installation. The output should show `root` as the owner and `rwsr-xr-x` as the permissions (which corresponds to `4755`).

---

## Correct Permissions and Ownership (if needed)

If the ownership or permissions are incorrect, use the following commands:

```
sudo chown root /path/to/anythingllm/chrome-sandbox
sudo chmod 4755 /path/to/anythingllm/chrome-sandbox
```

> Ensure you replace `/path/to/anythingllm/chrome-sandbox` with the actual path to the binary on your system.
