### ISSUE TITLE
[BUG]: Voyage AI embedding failure

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1491]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Trying to embed with different embed models, getting this error every time:

<img width="307" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/b5ae083d-48ce-4619-ba63-cdb7b8f87752">

**Comment by timothycarambat** [comment]
Is the API key correct and/or has credits?

**Comment by RahSwe** [comment]
@timothycarambat Tried adding the API key again and got it working. Seems to be an issue with my Arc browser filling in saved password in settings fields (not an issue with Safari).

Very slow embedding however, but I suppose this has nothing to with ALLM =)
Thanks for the quick feedback
