### ISSUE TITLE
[FEAT]: Add model support to Oobabooga Web UI

### ISSUE THREAD

**Issue by Matti-Koopa** [Mintplex-Labs/anything-llm#1503]
### What would you like to see?

Add a text box for `model` configuration to Oobabooga text generation web ui.
`model` is already in "Generic OpenAI" and as such could immediatly be copied over (as it's the same JSON syntax as well).

**Comment by timothycarambat** [comment]
Can `Oobabooga` serve more than a single model at once? The reason the field does not exist is because when integrating we did not see that option to hot-load multiple models at once

**Comment by shatfield4** [comment]
Oobabooga Web UI still does not support multiple models.
