### ISSUE TITLE
[BUG]: Having issues with "LLM Preferences"

### ISSUE THREAD

**Issue by Kamichimi** [Mintplex-Labs/anything-llm#1507]
### How are you running AnythingLLM?

Local development

### What happened?

So my main goal was to deploy AnythingLLM on my laptop without using Docker, I followed every steps, I booted up the server and the collector using the 2 commands and I can access `http://localhost:3001` without any problems. The thing is when I go to the settings and then I click on **LLM Preferences**, there's only a white page with nothing on it. And when I look at the console it there's an error saying : 
```js
index-551b4748.js:40  Uncaught TypeError: Cannot read properties of undefined (reading 'logo')
    at ke (index-3f139e57.js:1:8459)
    at Ps (index-551b4748.js:38:19514)
    at Ei (index-551b4748.js:40:3139)
    at Pm (index-551b4748.js:40:44689)
    at Nm (index-551b4748.js:40:39696)
    at D1 (index-551b4748.js:40:39624)
    at Al (index-551b4748.js:40:39479)
    at Ri (index-551b4748.js:40:35862)
    at Em (index-551b4748.js:40:34813)
    at E (index-551b4748.js:25:1584)
```
Does someone know what happened and if you have a solution to fix this ? 
It only happens on `http://localhost:3001/settings/llm-preference` and other pages seem to work fine.

**Comment by timothycarambat** [comment]
Either set an `LLM_PROVIDER` in `/server.env.development` or make sure that all `LLM_PROVIDER`, `EMBEDDING_ENGINE` and `VECTOR_DATABASE` are not set so you can onboard and set those vars
