### ISSUE TITLE
[BUG]: The system operates in a Docker environment (there are no issues in the Windows development environment), but when I click the copy button, it does not copy successfully

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#1509]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

The system operates in a Docker environment (there are no issues in the Windows development environment), but when I click the copy button, it does not copy successfully, and there is an error message in the console as follows:
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at s (index-86a57767.js:68:115)
    at Object.sh (index-86a57767.js:37:9855)
    at ch (index-86a57767.js:37:10009)
    at dh (index-86a57767.js:37:10066)
    at Wu (index-86a57767.js:37:31459)
    at Lf (index-86a57767.js:37:31876)
    at index-86a57767.js:37:36789
    at Fs (index-86a57767.js:40:36880)
    at Yd (index-86a57767.js:37:8991)
    at Ea (index-86a57767.js:37:33163)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/b1ea298d-84ac-479d-9035-366316cd2317)

**Comment by timothycarambat** [comment]
Browser does not have clipboard support and/or Docker URL is on insecure HTTP connection and is prevented from being used 
https://github.com/Mintplex-Labs/anything-llm/issues/1136
