### ISSUE TITLE
[BUG]: small typo in web-scraping function

### ISSUE THREAD

**Issue by Propheticus** [Mintplex-Labs/anything-llm#1510]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The web-scraping function description says "ur**l**":   while the examples below say "ur**i**": 
```
Function name: web-scraping
Function Description: Scrapes the content of a webpage or online resource from a provided URL.
Function parameters in JSON format:
{
    \"url\": {
        \"type\": \"string\",
        \"format\": \"uri\",
        \"description\": \"A complete web address URL including protocol. Assumes https if not provided.\"
    }
}
Query: \"What is useanything.com about?\"
JSON: {\"uri\":\"https://useanything.com\"}
Query: \"Scrape https://example.com\"
JSON: {\"uri\":\"https://example.com\"}
```

When a model follows the example using `uri` the call is invalid `Invalid function tool call: Invalid argument schema match`
When a model follows the parameter definition using `url` (with an L) the call is valid `Valid tool call found - running web-scraping.`

**Comment by timothycarambat** [comment]
resolved by 96c658b9
