### ISSUE TITLE
[FEAT]: HTML Embeds - Please add a way to give the generated div a specific class name or ID?

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1511]
### What would you like to see?

When I use the html chat embedding feature, it works, but at some points we would like to manipulate the div position or visibility or existence of the div that is generated by the embed js script. It turns out that the div doesn’t have a class name or other identifying features. Was able to write a script to go a few layers deep and find one class named anything-LLM-chat, but it’s kind of a hacky thing to do. Would be nice to have a configuration for the outputted div. Thanks for the other configurations that are there. Just looking for one more :)

**Comment by timothycarambat** [comment]
Which element? The toggle to open the window or the window itself?
The window has a tag:
https://github.com/Mintplex-Labs/anything-llm/blob/acbad2f2cf7c13e03e0a0dc1067041ba4c59930c/embed/src/App.jsx#L43

**Comment by atljoseph** [comment]
Was looking at the top level document body div it makes. I guess we could just do a remove for that selector

**Comment by timothycarambat** [comment]
I think if anything we can add one to the floating button as well, that should be there as well

**Comment by timothycarambat** [comment]
@atljoseph lets make that a new issue for feature request - it will get lost  in a closed comment thread

**Comment by atljoseph** [comment]
Moved to https://github.com/Mintplex-Labs/anything-llm/issues/1544
