### ISSUE TITLE
[FEAT]: Lock down embedded chat with API Key. Want to be able to revoke API key from individual services that consume embeds.

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1512]
### What would you like to see?

There a way to Lock this feature down with an API Key? Will be calling this from a service in the same cluster, but would be nice to be able to cut it off by revoking API Key (if needed) on a per-service basis. Seeing API Keys for interacting with the main API, but not with the embedded chat feature, and it seems like the API Keys for the embedded feature would need a different scope of permission than those under "API Keys" in setting.

This is the only thing preventing us from promoting the feature into PROD right now, and really don't know enough about k8s ops to delegate this to k8s service/user permissions, let alone manage those. :) 

Thank you!

**Comment by timothycarambat** [comment]
In the embed chat config you want to revoke you can disable it on screen. Which is the same as "revoking" its key. No chat will succeed and the embed will not function
<img width="1407" alt="Screenshot 2024-05-23 at 8 24 23 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/79033fc0-cfbe-4b86-9020-cdb5d5d7ff31">

**Comment by atljoseph** [comment]
Oh, i guess that does the same thing. Just multiple embeds. Maybe doable that way.

**Comment by timothycarambat** [comment]
The chat can render `markdown` so if you instruct the system prompt of the workspace to inject that, it should. Obviously you are depending on an LLM to follow instructions to your milage may vary
