### ISSUE TITLE
[FEAT]: Build Link Scraper - Be able to specify a list of Whilelisted domains.

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1515]
### What would you like to see?

Need to have this feature focus on a singe domain, or a limited number of domains.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/25017621/5739d036-bab5-4156-b958-36ce39765241)

I don't want this to link down to 4chan for some reason LOL.
Is facing customers.

**Comment by timothycarambat** [comment]
That is what this feature does. It does not leave the parent origin that you assign. For example linking reddit will only scrape child links that also resolve on `reddit.com` hostnames. It will not child-follow every post on the main page

**Comment by atljoseph** [comment]
Oh ok cool. I thought it might be the case, but couldn’t find anything in
the app stating that fact. Cool!!

**Comment by atljoseph** [comment]
Curious. What happens to pdf files or other documents encountered while scraping? I presume video files are skipped (maybe a way to send that to gpt4o in the future to embed).

**Comment by timothycarambat** [comment]
If you enter in a direct PDF link, it wont download it and parse it - it would just ignore it. I would like to add the ability to get the mime and parse automatically, would probably be a nice to have

**Comment by atljoseph** [comment]
Can’t have everything… yet. Appreciate it :)
