### ISSUE TITLE
[FEAT]: ChromaDB Support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1522]
### What would you like to see?

The current version of Chroma introduced some breaking changes and rules that make the current support of AnythingLLM for ChromaDB incompatible, we should revamp this connector to work with the latest version of Chroma

**Comment by Phuzzled** [comment]
Seems to be attempting to retrive from chromadb just fine.. except it isn't creating new collections or storing properly (ValueError: Collection luminav2 does not exist.)

(luminav2) is the workspace name and the above ValueError is from chromadb output when ALLM tries to engage.

**Comment by timothycarambat** [comment]
Requires support for collection name pre-flight check:
https://github.com/Mintplex-Labs/anything-llm/issues/1481
