### ISSUE TITLE
[QUESTION]: How can I sign in as a default role user via API?

### ISSUE THREAD

**Issue by Kevinoup** [Mintplex-Labs/anything-llm#1524]
### What would you like to see?

I’m experiencing some difficulties utilizing the APIs provided by AnythingLLM. Firstly, I’m trying to figure out how to sign in as a default-level role user using API.  But I can't find it.

Next, I’d like to create a new user with a specific role and add them to a workspace. Once the new user is created through API, how do I initiate this new user a chat or query session by API? 

Lastly, if I want to retrieve the chat or query records for a specific user within a workspace, what’s the best approach using AnythingLLM’s API? Can I specify the user ID or username to filter the results and only retrieve their chat or query history, rather than getting all records from all users in that workspace?

Any guidance on these issues would be greatly appreciated.

**Comment by Kevinoup** [comment]
@timothycarambat Hi, thanks for changed the title. But I don't believe this is a question; rather, I think it as missing features or potentially a bug, since the API lacks functionalities at the user level for login, retrieve chats, or executing queries.

**Comment by timothycarambat** [comment]
Ah then this is the same issue as https://github.com/Mintplex-Labs/anything-llm/issues/512, basically the API needs to be a user themselves as well as "impersonate" a user via the API
