### ISSUE TITLE
[DOCS]: How to run frontend and backend in dev mode?

### ISSUE THREAD

**Issue by thiagobutignon** [Mintplex-Labs/anything-llm#1525]
### Description

Hey guys,

I am trying to run in dev mode the Frontend and backend. The Frontend is infinite reloading after yarn and yarn dev

could you clarify how to run it locally to make changes and collaborate to the project.

thanks

**Comment by timothycarambat** [comment]
After a clean clone the process is:
- `yarn setup` - install all deps in all folders, migrates DB, and creates `frontend/.env` and `server/.env`

Next: make sure that 
`server/.env.development` has the the keys you want set. When you edit server-side code and the backend hot-reloads anything you saved in the ENV prior will be lost and all that will remain is what is in the file. So ensure that VECTOR_DATABASE, LLM_PROVIDER, and EMBEDDING_ENGINE are all set.

`frontend/.env` has a single useful key. If you are building on localhost the API_BASE (server) runs on 3001 so
`VITE_API_BASE='http://localhost:3001/api'`

Then next all that that should be needed is from root:
`yarn dev:server` to run backend with hot-reloading - port :3001
`yarn dev:frontend` to run frontend with hot-reloading - port :3000
`yarn dev:collector` to run document processor with hot-reloading - port : 8888

**Comment by thiagobutignon** [comment]
@timothycarambat thank you so much
