### ISSUE TITLE
[DOCS]: Regarding reseting onboarding

### ISSUE THREAD

**Issue by clipod** [Mintplex-Labs/anything-llm#1531]
### Description

Hi, I am playing with the tool and one thing I am not able to figure out was, if I want to reset everything and go back to onboarding page, how can I do it. For example, right now i set this up for an individual and now I want to change this experience for a team.

**Comment by timothycarambat** [comment]
There was no description on how you are using AnythingLLM so ill provide the ususal suspects:

**Docker**
- When you started the container you attached some `STORAGE` location from the HOW_TO_USE_DOCKER.md file we have. To reset everything, delete that folder

**Desktop**
Mac: `/Library/Application Support/anythingllm-desktop` You can just delete this whole folder. On reboot it will be re-created
Windows: `C:\Users\usr\AppData\Roaming\anythingllm-dekstop` - same as above
Linux: `~/.config/anythingllm-desktop`

**Local Development**
- `yarn prisma:reset`
- make sure no `LLM_PROVIDER`, `EMBEDDING_ENGINE`, or `VECTOR_DATABASE` env keys are set.

**Comment by clipod** [comment]
Ah thanks. Ya I was running on Docker. I deleted everything inside the folder but not the .env file. Though if anythingllm.db is wiped of completely, it will take me to the initial step.
