### ISSUE TITLE
[BUG]: tried to load a PDF book of size 383MB. It worked fine in an i7 Windows (16GB RAM), but it failed to embed the doc in Mac i7 (intel mac) 16GB RAM

### ISSUE THREAD

**Issue by annamalaiarunachalam** [Mintplex-Labs/anything-llm#1534]
### How are you running AnythingLLM?

Docker (local)

### What happened?

in the mac (16GB RAM, i7 processor with 4 core), I am able to load the pdf doc (383MB size), I moved it to the workspace. when I clicked embed and save, it takes 5 to 6 mins, then throws the message below:
[1 doc failed to load
cannot embed doc]
I think it has nothing to do with the embed model and the LLM. I chose nomic-1.5 as embedding model. Both these models are served by ollama server which was running. 

I used LM Studio in windows, but there is no Intel Mac version of LM studio, hence chose ollama for Intel MAC

### Are there known steps to reproduce?

adding a 383MB size PDF - for chatting with pdf locally - embed and save throwing error - in a i7 intel based MAC with 16GB RAM, using Nomic-1.5 embedding model served by ollama from the same mac instance.

**Comment by timothycarambat** [comment]
In this particular circumstance I think that the ollama process is running out of memory processing all the document chunks at once - resulting in too many concurrent chunks. What do the ollama logs say? It should be exiting with some kind of OOM memory error.

Also, I have a similar setup (windows comp with GPU and Intel Mac) and all i do is run `ngrok http 1234` after starting the windows LMStudio server, and then use that URL in my Intel Mac LMStudio integration in AnythingLLM and you get the best of both worlds.
