### ISSUE TITLE
[AZURE] Add support for OpenAI on Azure

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#154]
AnythingLLM should support the option for someone to use their own custom URL for openAI library since the code is functionally the exact same but the base API needs to change.

Requires investigation to see how this can be done easily without overloading the configuration of the application.

**Comment by iokinpardo** [comment]
This is a key feature for many companies. Working with Azure is becoming a must from security side so a barrier if Azure is not available.

**Comment by timothycarambat** [comment]
We have applied for Azure OpenAI support and have not received a response yet. Until then implementation is blocked since we dont have a way to validate requests.

**Comment by timothycarambat** [comment]
We have gotten access to the Azure OpenAI support. Unblocking this issue and will work tomorrow.
