### ISSUE TITLE
[FEAT]: Provide guidance on approximate document handling capability based on hardware

### ISSUE THREAD

**Issue by OrcVole** [Mintplex-Labs/anything-llm#1541]
### What would you like to see?

To many users, it might be helpful to have statement indicating approximately how many documents could be analysed at one time. Some hardware might be able to handle many more .pdf and .epub files than others. Also, providing some idea of how long it might take to ingest/upload a document might be reassuring, too. 

Something like this, for example: If you have 8GB VRAM and 16GB RAM, then your device could probably handle one ebook.... If the ebook is about 200 pages and includes illustrations, it might take about 10 minutes to ingest.

**Comment by timothycarambat** [comment]
This is so dependent on hardware that benchmarking this would be a guesstimate at best, and flat out wrong at worst. This also depends on the specific document being collected. EPUBS, as you mentioned at more complex to parse than regular text files, but things like mp3/mp4 as insanely resource intensive as it runs a whole whipser model locally to make that work.

Its just too dependent on hardware, setup, RAM, and file types that makes documenting something like this so specifically  a rabbithole. Obviously there is a standard window of time that is acceptable, but again that being resource dependent we would like to assume the user would be aware that parsing a 4K page PDF on a Raspberry Pi would not be instant!
