### ISSUE TITLE
[BUG]: QDRANT "There is no relevant information in this workspace to answer your query."

### ISSUE THREAD

**Issue by gandolfi974** [Mintplex-Labs/anything-llm#1549]
### How are you running AnythingLLM?

Docker (local)

### What happened?

hello,
i want to use Qdrant to vectorize document. I can create new collection with anythingLLM but in "vector Databse" the number of vector is bloqued on zero. In query mode i have this error for all my questions "There is no relevant information in this workspace to answer your query." thanks for your help

![image](https://github.com/Mintplex-Labs/anything-llm/assets/25908976/c4c78b32-6524-42bc-9104-6126826495f3)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/25908976/d386d897-206e-43c3-8438-31afc950cfae)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/25908976/1a2501cd-0548-441d-bab1-b4c6e18a500c)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/25908976/0f225489-dd58-40fd-b8e2-bad17fc67851)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/25908976/a3cce91f-2eba-4e52-aaf8-d858bb8fc8e7)

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/1220
