### ISSUE TITLE
RAG implementation with user-roles getting different results?

### ISSUE THREAD

**Issue by thebaldgeek** [Mintplex-Labs/anything-llm#1551]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Trained system from about 100 pdf and text documents. Using default and built-in database. Windows 11. Docker image pulled around 18 hours ago.

Admin user gets answers from trained docs as expected.
Non-admin users get raw Ollama llama3.0 LLM answers with correct citations.
Tested with exact same questions and other basic questions. 100% of the time the Admin user gets the correct answer text that shows the trained docs have been accessed and 4 citations contain parts of the answer text as expected.
Default user gets raw LLM answer (often comically wrong) with 'correct' 4 citations that contain question text listed (for those questions that are the same).

Tested in Firefox, Chrome and Edge, both regular browser and incognito sessions.
User is set as 'Default'. User is added to workspace.

Work around is to have all users log in as Admins and requested not to change any settings.

**Comment by timothycarambat** [comment]
This is not how the implementation of the RAG system works, or should work. Everyone has the same access to documents in the same workspace, so sending a prompt in a workspace the only user-specific information is the current chat/thread history sent by that specific user.

I think there is either a misunderstanding or some other detail missing from this issue that is leading to worse RAG performance at this time.

This part:
> Default user gets raw LLM answer (often comically wrong) with 'correct' 4 citations that contain question text listed (for those questions that are the same).

is quite odd as the citation should not exist at all unless it was explicitly used in the response generation 🤔

**Comment by omaralagouz** [comment]
I have a similar issue where I've added documents to a workspace that have all been embedded and all seems to be fine, but when a question is asked, RAG is never used to answer the questions. Is there a specific configuration for this that i've missed? I tried with many users and with a different thread in the same workspace but still no luck in getting RAG to work at all. (I'm using groq with Llama 8b as my LLM)

**Comment by omaralagouz** [comment]
Okay, problem solved, it happened to be due to the 'Document similarity threshold' setting i had which was [> .75]. All citations that are returned are almost always less than .75, so changing it to [>.50] fixed my issue completely.

**Comment by thebaldgeek** [comment]
I am stunned that this bug is closed as 'not planned'.
Since I discovered this issue on May 27, my team of 20 people have been in limbo.
Since they cant log in as anything other than admin, they have been emailing me their LLM questions, I copy/paste into the interface, and copy/paste/email the results back while we wait for this function to be fixed.
Since its now clear that multi user accounts is not a planed feature, I feel the rug has been pulled out from under myself and the entire team.
I hope the docs and features etc for this project are updated and made clear that everyone must log in as ADMIN.

**Comment by timothycarambat** [comment]
> Since its now clear that multi user accounts is not a planed feature, I feel the rug has been pulled out from under myself and the entire team.

We have multi-user accounts.

The issue was closed because the user said it was solved by changing their similarity score.

@thebaldgeek If you have made everyone an admin you are doing something very wrong. The queries someone sends have _zero impact on what documents_ they can see. If you are able to provide any reproducible example of the same query being sent in the same workspace and the only difference being a user role - I would like to review it myself.

Documents are not even partitioned by userspace or role, everyone chats with the same documents in a workspace regardless of role. The role simply limits who can _manage_ the documents in a workspace. If you want users to be able to make their own workspaces, make them a manager, not an admin. Then they can make their own workspaces and upload their own documents.
