### ISSUE TITLE
[FEAT]: API endpoints to create/delete threads within workspace

### ISSUE THREAD

**Issue by shatfield4** [Mintplex-Labs/anything-llm#1552]
### What would you like to see?

- Create API endpoints with the ability to create and delete threads via API
- Create API endpoints to chat with workspace threads

**Comment by Realkek** [comment]
I support this, it would be very useful, because now it seems that it is impossible to access, for example, a unique chat instance using the user ID through the API.

**Comment by atomlg** [comment]
This is really a very useful functionality, I hope you add it as soon as possible, I'll be looking forward to it.

**Comment by 111Mihail111** [comment]
Wow, that would be really cool! I'm looking forward to it!

**Comment by viktara** [comment]
excellent, this is something we need to use in our project. @shatfield4 anything you need help with?

**Comment by pedrovelmo** [comment]
Really need this for my project as well!

**Comment by zixitimbaldwin** [comment]
I just created a Slack app that connects to AnythingLLM via API.  It would be very cool to be able to pass the slack unique user ID over and keep threads separate between different Slack users.
