### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by babyldm** [Mintplex-Labs/anything-llm#1553]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![无标题](https://github.com/Mintplex-Labs/anything-llm/assets/12437265/4ff0bcd9-fc54-4ddd-8011-561832cadb98)
Anythingllm snowflake arc embedded cannot work, only nomo embedded test can work. How to set it up?
![无标题](https://github.com/Mintplex-Labs/anything-llm/assets/12437265/2634c7c3-7492-4745-b32d-c496410b0677)

**Comment by timothycarambat** [comment]
This error occurs under these conditions usually:
- The workspace has had something embedded prior using some other embedder - usually the native one
- The document was embedded with an old embedder, you change embedders and sent a chat - now columns dont match.

Solution:
- Ensure embedder is set to desired settings
- Remove document + delete
- Reset workspace vector db (workspace settings > vector db > Reset
- Reupload and embed file
- Send chat
