### ISSUE TITLE
[BUG]: File not found "save-file-to-browser"

### ISSUE THREAD

**Issue by AIbottesting** [Mintplex-Labs/anything-llm#1556]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Used agent with Google API to web search and collect user guide data (worked). Used agent to save information to file and the link opens the web browser, but file not found. Windows 10 latest, 64bit, AnthingLLM v1.5.5

### Are there known steps to reproduce?

Tell agent to save information to file
![Screenshot 2024-05-28 062128](https://github.com/Mintplex-Labs/anything-llm/assets/124838865/cd6643ef-7384-481e-acb5-62f63a8c7f03)
![Screenshot 2024-05-28 062151](https://github.com/Mintplex-Labs/anything-llm/assets/124838865/6e3a524c-efe3-480d-b348-a24a19a10f26)

**Comment by timothycarambat** [comment]
This is the LLM hallucinating the answer, it cannot provide a link to a local file. If the tool was _actually_ called and not the LLM pretending to call the tool it would show a "Save to" to select the destination.

This is a hallucination from the OSS LLM and tool calling!

**Comment by AIbottesting** [comment]
I am sorry to waste your time. My temperature was way to high, I adjusted to 0.1, and got an even weirder response, and your YouTube video was right about quant sizes. My Llama-3-8B-Instruct-Q5_K_M is not smart enough to save a file. It tried to save a file to so cloud service! LOL!
![Screenshot 2024-05-28 063806](https://github.com/Mintplex-Labs/anything-llm/assets/124838865/aced376b-0419-493a-a19d-0bf4cd6edfdc)
![Screenshot 2024-05-28 063858](https://github.com/Mintplex-Labs/anything-llm/assets/124838865/bf564858-50f4-4870-80bf-d71a90f4f68b)

**Comment by AIbottesting** [comment]
This is the result without @agent web search activated
![Screenshot 2024-05-28 071748](https://github.com/Mintplex-Labs/anything-llm/assets/124838865/e19d8c15-57fa-47a6-bd93-84ab5928c94f)
