### ISSUE TITLE
[FEAT]: LiteLLM Embedding Provider support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1559]
### What would you like to see?

Add support for LiteLLM as an embedding provider if available and possible to be done.

**Comment by avinashkurup** [comment]
Thanks, @timothycarambat and @shatfield4.

As discussed earlier [here](https://discord.com/channels/1114740394715004990/1243445914316574802/1243445914316574802), we've added new models (Ollama) to LiteLLM. We would like to request modifications to the anything-llm UI to allow us to add these new models for embedding documents.

Specifically, we need changes in **Settings > Embedding Provider > Embedding Provider** to enable the selection of a custom embedding provider from LiteLLM.

Thank you!
