### ISSUE TITLE
[FEAT]: Generic LLM provider preference

### ISSUE THREAD

**Issue by wcwong** [Mintplex-Labs/anything-llm#1566]
### What would you like to see?

I'd like to be able to create "generic" LLM providers.  So, for example, Azure recently introduced pay as you go endpoints for other models where it's basically just a URL + API key with no other configuration bits.

**Comment by timothycarambat** [comment]
This is the Generic OpenAI provider that we already support. Includes this exact kind of configuration and set up

**Comment by wcwong** [comment]
Hi @timothycarambat. Thanks for the quick reply. The problem with the Generic OpenAI provider appears to be that it requires a model name. What if the endpoint does not accept the model name?

**Comment by timothycarambat** [comment]
You can just put anything, beccause then your API will probably just ignore it or drop it, like how LMStudio does
