### ISSUE TITLE
Anthropic Claude 2 API Integration

### ISSUE THREAD

**Issue by jignnsd** [Mintplex-Labs/anything-llm#157]
Hey Tim, thank you for this work, it works very good so far on my tests. 
I have one question, is it possible to have support (using the same DB and Embeddings API) of the just introduced AnthropIc Claude 2 to use it instead of Openai chat API on an easy way, or it will implicate a lot of changes to be done? 
I’m curios because I just compare the answers between openai (on anything-llm) and claude 2 with the same pdf file, and the answer was much better on claude 2, maybe because of the bigger token limit, so maybe will be a good thing to try if this does not implicate a huge change.
Also, the pricing drop using Claude 2 instead of Openai is important, like half of the price.
Again, many thanks for the good work and hopefully you can add a link to make a donation to compensate this great effort.
Javier

**Comment by timothycarambat** [comment]
Oh, that sounds very cool. The LLM side of things needs to diversity (even beyond Azure which is just OpenAI anyway).

If they have a support JS client it should keep things even more simple. Otherwise rolling our own internal API might be a pain. I do think that embedding will still have to be done with OpenAI though, as I don't think Anthropic has an embedded yet?

Chat should be straighforward

**Comment by jignnsd** [comment]
You are right, should keept openai for embeddings and also same vectordb, just the chat part will be changed to have the option of Anthropic.

**Comment by timothycarambat** [comment]
For Implementation:
Node client: https://www.npmjs.com/package/@anthropic-ai/sdk
API: https://docs.anthropic.com/claude/reference/getting-started-with-the-api

Will require some new ENV keys in settings to support this config.

**Comment by timothycarambat** [comment]
Mintplex Labs has applied to the Anthropic Claude 2 API access so we can integrate it fully. This issue is blocked until we or someone else can provide an API key for development (do not share key in issue please)

**Comment by ishaan-jaff** [comment]
Hi @jignnsd @timothycarambat I believe I can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm - we allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 

You can use LiteLLM in the following ways:

## With your own API KEY:
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
os.environ["COHERE_API_KEY"] = "your-key" # 

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

## Using the LiteLLM Proxy with a LiteLLM Key 
this is great if you don’t have access to claude but want to use the open source LiteLLM proxy to access claude


```python
from litellm import completion
import os

## set ENV variables 
os.environ["OPENAI_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your openai key
os.environ["COHERE_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your cohere key

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```
