### ISSUE TITLE
[BUG]: LLM giving response in hindsight.

### ISSUE THREAD

**Issue by jainpradeep** [Mintplex-Labs/anything-llm#1571]
### How are you running AnythingLLM?

All versions

### What happened?

I used Mistra7B/Llamma 3 etc for QA on PDFs. LLM answers are very poor. I tried with different embedding engines. I have a 16 GB GPU. PDF size ~10 MB (150 Pages) Please suggest ways to improve this. 

### Are there known steps to reproduce?

Upload PDF. Ask questions.

**Comment by timothycarambat** [comment]
Please read the docs - a lot of this often comes down to "garbage in => garbage out" among other things
https://docs.useanything.com/llm-not-using-my-docs
