### ISSUE TITLE
[BUG]: Gemini/Flash recitation issue

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1573]
### How are you running AnythingLLM?

Docker (local)

### What happened?

With some prompts, this error message appears:

<img width="567" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/5e4efc59-8518-468a-aa5c-451ec04846f7">

In the link below, the issue is discussed and seems to be resolvable with adjustments to the code:

https://github.com/google-gemini/generative-ai-js/issues/138

**Comment by timothycarambat** [comment]
That thread unfortunately does not provide any resolution at all, we already use streaming and that is the default and it does not seem you can "turn off" Recitation as a rule for reply - which is just horrible design on Googles part, but not something we can resolve within AnythingLLM
