### ISSUE TITLE
[FEAT]: Pin citations

### ISSUE THREAD

**Issue by BenjaminStular** [Mintplex-Labs/anything-llm#1576]
### What would you like to see?

First, THANK YOU Timothy & team for opening the world of local RAG to us mere mortals, a.k.a. non-developers.
Similarly, AnythingLLM could easily be used as a vectorDB client with a simple additional feature: to pin / permanently display the citations which are in fact the vectorDB search results.
There might even be a use case for suppressing the generation of the answer (to save the tokens) because the user might only be interested in searching the vectorDB.

Cheers
Benjamin

**Comment by timothycarambat** [comment]
Thank you for the kind words. As for your issue, we have pinning available via the API, but as for using AnythingLLM as basically a "Vector db wrapper" this is something we will be handling via https://github.com/Mintplex-Labs/anything-llm/issues/881 - which would give you the intended output you are looking for once completed :)
