### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Leectan** [Mintplex-Labs/anything-llm#1580]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Found no where in anythingllm-chat-widget.min.js to update the chatbot widget icon 
<img width="381" alt="SyntifyAI" src="https://github.com/Mintplex-Labs/anything-llm/assets/24819052/0b784d0f-b496-4e30-9e09-38ece50d16bf">
<img width="320" alt="Cursor_and_SyntifyAI" src="https://github.com/Mintplex-Labs/anything-llm/assets/24819052/bcfe2f5b-a2a5-4639-9ffe-17fb399c550b">

### Are there known steps to reproduce?

Please provide steps to fix so. Much appreciated.

**Comment by shatfield4** [comment]
You can find the documentation for the embedded chat here: [embedded chat docs](https://github.com/Mintplex-Labs/anything-llm/tree/master/embed).

Adding the `data-assistant-icon` attribute to the script code you are adding to your website will allow you to change the icon.

**Comment by Leectan** [comment]
Added, does not see it rendered, what am I missing? Appreciate your help Sean.



`
<script
  data-embed-id="c029ef00-9949-40d3-82cc-d7e1f55daa7b"
  data-base-api-url="http://localhost:3001/api/embed"
  src="http://localhost:3001/embed/anythingllm-chat-widget.min.js">
  data-assistant-icon="http://localhost:3001/embed/favicon.png"
</script>


`

**Comment by timothycarambat** [comment]
@shatfield4 can you replicate this? Latest script built should be published and have this in it.

**Comment by Leectan** [comment]
@shatfield4 @timothycarambat, I understand you guys have alot to maintain this awesome tool and have alot to answer, but I've looked through all the docs and issues and tried to find a workaround in the min.js file but haven't found one yet. Would appreciate if yall can replicate and find a fix for this. Thanks in advance
