### ISSUE TITLE
[BUG]: LM Studio does not allow for different model selection

### ISSUE THREAD

**Issue by mrdjohnson** [Mintplex-Labs/anything-llm#1582]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When trying to select a different model based on the workspace, LM Studio does not show up in the list
Based on the code I see this : `Some providers can only be associated with a single model.`

This lmstudio should not be in that list? (see screenshot of my server  with two models loadedl) 

<img width="534" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/6767910/52635073-9764-4d52-a21e-4f0c65c3f605">

### Are there known steps to reproduce?

- Set up LM Studio server
- tell Anything LLM to use LM Studio
- create new workspace, see LM Studio not in list

**Comment by wallartup** [comment]
Yes, we should reactivate LMstudio now that you can run playground successfully with multiple models. :)

**Comment by timothycarambat** [comment]
moving to #1569
