### ISSUE TITLE
Does running @agWhy does the agent have to configure the model separately, and will it eventually hand it over to a system-configured model?ent AnythingLLM call only the model in the ai agent session and not the model configured by the system?

### ISSUE THREAD

**Issue by mingLvft** [Mintplex-Labs/anything-llm#1583]
### Description

Why does the agent have to configure the model separately, and will it eventually hand it over to a system-configured model?

**Comment by shatfield4** [comment]
This is because not all models support function calling so we disable some providers from being used with agents. We are working toward supporting every LLM model that the system LLM providers support for agents as well.
