### ISSUE TITLE
[BUG]: AnythingLLM Desktop not loading in my Windows 11 (Its been 5 to 7 hours)

### ISSUE THREAD

**Issue by Kazooki123** [Mintplex-Labs/anything-llm#1584]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Its been **8 hours** and oh boy the desktop app is not even loading and I don't even know why.

I've disabled my anti-viruses and config windows security firewall and so as running the app on administrator, it still won't load.

Please help me how to fix this or just be fixed. Thanks.

**Comment by shatfield4** [comment]
When you say it's not loading, is it just getting stuck on the loading/splash screen? Are you running the docker or local development version of AnythingLLM at the same time?

**Comment by timothycarambat** [comment]
This is 100% a client-side issue as if this was a _bug_ in the traditional sense, every windows user would have it. More information is need to help debug this. We can continue the conversation in this thread, but will close the issue as a bug.

**Comment by kalle07** [comment]
same to me load screen and 10min i break

**Comment by kalle07** [comment]
and why the downloadlink is 
https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop.exe

amazonaws is blocked by ALL blocking-list !

**Comment by DavidGil-dagg** [comment]
The same for me, the API works but the graphical interface is not loading. I think it's due to a RAM or CPU issue, because I have another computer where it works, and the difference is that it has better specs.

![Image](https://github.com/user-attachments/assets/01eb31bb-2cbf-45a6-8dc4-a0110d910694)

**Comment by timothycarambat** [comment]
@DavidGil-dagg What kind of machine is it not loading on?

**Comment by DavidGil-dagg** [comment]
Is a Azure virtual machine.

![Image](https://github.com/user-attachments/assets/b635256e-d01c-4ef9-81f3-70d1f453c77a)

**Comment by QuiQiJingFeng** [comment]
debug log show some config error

[OllamaProcessManager] Ollama will bind on port 18774 when booted.
[Preferences] Will load window with last know bounds.
[collector] info: [TikTokenTokenizer] Initialized new TikTokenTokenizer instance.
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
[backend] info: [TokenManager] Initialized new TokenManager instance for model: gpt-3.5-turbo
[collector] info: Collector hot directory and tmp storage wiped!
[collector] info: [production] AnythingLLM Standalone Document processor listening on port 8888.
[backend] info: [TokenManager] Returning existing instance for model: gpt-3.5-turbo
[backend] info: [TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
[backend] info: prisma:info Starting a sqlite pool with 17 connections.
[backend] info: [TELEMETRY SENT] {"event":"server_boot","distinctId":"57979887-9363-4ba1-b8da-0018132cc4f7","properties":{"runtime":"desktop","distribution":"windows-x64"}}
[backend] info: Hot loading of AnythingLLMOllama - LLM_PROVIDER is anythingllm_ollama.
[backend] info: [NativeEmbedder] Initialized
[backend] info: [CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
[backend] info: [production] AnythingLLM Standalone Backend listening on port 3001. Network discovery is disabled.
[backend] info: [BackgroundWorkerService] Feature is not enabled and will not be started.
[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.
[OllamaProcessManager] [windows] Ollama subprocess running. Port 18774. PID 46852.
[backend] info: OllamaAPI offline - retrying. 1/3
[backend] error: Cannot read properties of null (reading 'toString') TypeError: Cannot read properties of null (reading 'toString')
    at s.getWSLWorkbenchContainer (D:\anythingLLM\resources\backend\server.js:41:2179)
    at s.getConfig (D:\anythingLLM\resources\backend\server.js:72:3937)
    at Object.currentSettings (D:\anythingLLM\resources\backend\server.js:72:10687)
    at async D:\anythingLLM\resources\backend\server.js:235:11280
[Preferences] Saving last_bounds preference.
[OllamaProcessManager] Ollama parent process 46852 killed.

**Comment by QuiQiJingFeng** [comment]
![Image](https://github.com/user-attachments/assets/6c3dc29f-1d9e-47ed-8650-c0aaf092780e)    操作系统名称  Microsoft Windows 10 企业版
版本  10.0.18363 内部版本 18363
其他操作系统描述    没有资料
操作系统制造商 Microsoft Corporation
系统名称    PWRD-20200604PO
系统制造商   System manufacturer
系统型号    System Product Name
系统类型    基于 x64 的电脑
系统 SKU  SKU
处理器 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz，3000 Mhz，8 个内核，8 个逻辑处理器
BIOS 版本/日期  American Megatrends Inc. 0804, 2019/9/20
SMBIOS 版本   3.1
嵌入式控制器版本    255.255
BIOS 模式 传统
主板制造商   ASUSTeK COMPUTER INC.
主板产品    PRIME B365-PLUS
主板版本    Rev X.0x
平台角色    台式机
安全启动状态  不支持
PCR7 配置 无法绑定
Windows 目录  C:\Windows
系统目录    C:\Windows\system32
启动设备    \Device\HarddiskVolume1
区域设置    中国
硬件抽象层   版本 = "10.0.18362.1679"
用户名 PWRD-20200604PO\Administrator
时区  中国标准时间
已安装的物理内存(RAM)   32.0 GB
总的物理内存  31.9 GB
可用物理内存  17.0 GB
总的虚拟内存  34.0 GB
可用虚拟内存  13.0 GB
页面文件空间  2.11 GB
页面文件    C:\pagefile.sys
内核 DMA 保护   关闭
基于虚拟化的安全性   未启用
设备加密支持  设备自动加密失败的原因: TPM 不可用, 不支持 PCR7 绑定, 硬件安全测试界面失败，设备未处于现代待机模式, 检测到不允许使用的具有 DMA 功能的总线/设备, TPM 不可用
Hyper-V - 虚拟机监视模式扩展 是
Hyper-V - 第二级地址转换扩展 是
Hyper-V - 固件中启用的虚拟化 否
Hyper-V - 数据扩展保护    是

**Comment by timothycarambat** [comment]
> backend] error: Cannot read properties of null (reading 'toString') TypeError: Cannot read properties of null (reading 'toString')
at s.getWSLWorkbenchContainer (D:\anythingLLM\resources\backend\server.js:41:2179)
at s.getConfig (D:\anythingLLM\resources\backend\server.js:72:3937)
at Object.currentSettings (D:\anythingLLM\resources\backend\server.js:72:10687)
at async D:\anythingLLM\resources\backend\server.js:235:11280

You must be trying to use `nvidia-nim` as your `LLM_PROVIDER` + the `NVIDIA_NIM_LLM_MODE` key set to `managed`. NIM is probably not available on your device because WSL is not available either.

Open the storage folder for the desktop app and edit the .env file and remove the `NVIDIA_NIM_LLM_MODE` value from he env. Then save and reopen the app.
https://docs.anythingllm.com/installation-desktop/storage#where-is-my-data-located

You cannot use NVIDIA NIM on platforms that dont have WSL support.

**Comment by thkey** [comment]
I can open it normally now after installing WSL.
https://blog.csdn.net/weixin_45144684/article/details/140425641
