### ISSUE TITLE
[CHORE]: Increase Ollama timeout

### ISSUE THREAD

**Issue by Nathan8489** [Mintplex-Labs/anything-llm#1585]
### How are you running AnythingLLM?

Docker (local)

### What happened?

os: linux
version: `mintplexlabs/anythingllm@sha256:1d994f027b5519d4bc5e1299892e7d0be1405308f10d0350ecefc8e717d3154f` (latest version before lancedb dep bump )

problem from: `server/utils/EmbeddingEngines/ollama/index.js` 

The function `embedChunks` tries to send all text chunks in one connection. However, if all fetches cannot complete within 5 minutes, something (possibly Node.js) determines that the connection has timed out and terminates it, causing it to fail.

I temporarily resolved this by awaiting each chunk fetch individually (40 seconds per chunk, 8192 tokens).

### Are there known steps to reproduce?

- Get a really slow Ollama service (CPU).
- Set the embedding provider to Ollama.
- Try to move a large document to the workspace.
- Wait for the embedding process...
- It failed exactly after 5 minutes.

**Comment by mingLvft** [comment]
Has the problem been solved？

**Comment by timothycarambat** [comment]
There is no PR and the issue is open - so no.

**Comment by travisgu** [comment]
I encountered same issue. The Ollama service returned 500 error at exact 5 mintues because the http request was cancelled. So it can only embedding small PDF files.

**Comment by timothycarambat** [comment]
Moving conversation to #1585
