### ISSUE TITLE
[FEAT]: zscaler block connection to internet please add a configuration for certificate

### ISSUE THREAD

**Issue by norman003** [Mintplex-Labs/anything-llm#1587]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/33376952/8e3f86ca-05ba-4d88-b899-dabb79ab64fd)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/33376952/f3620deb-eb62-4689-a0ef-22039e3fb094)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/33376952/9510b3ee-320c-4052-9be4-e8907dece725)

when turn off, worked

**Comment by timothycarambat** [comment]
This is out of scope for AnythingLLM as this is entirely a client configuration set up issue and is something you or an IT team would need to manage.

**Comment by norman003** [comment]
This is postman, is posible to implemenrt in AnythingLLM.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/33376952/69481f08-1505-4fdb-bb3b-0d4d94969005)
