### ISSUE TITLE
How to share Pinecone vectors with different computers?

### ISSUE THREAD

**Issue by hcchengithub** [Mintplex-Labs/anything-llm#159]
I successfully run on one computer at work. Then go home and found that I have to create a workspace again and upload documents to Pinecone again. I expect since index is on Pinecone therefore the workspace can be shared too. I found this repo today, I am new, Just a little hint would be very much appreciated.

**Comment by timothycarambat** [comment]
Currently `syncing` vectors to a vector db that wasn't created on the instance is not supported.

__however!__
You can export the DB from the instance on the instance which created the vectors and import it into your new instance. That will keep everything up to date cross-instance.

**Comment by hcchengithub** [comment]
Hi there,

I gratfully have reviewed the answer, but I still require more hints on how to carry out the export/import process within this Docker container. Would someone be able to provide me with further clarification or point me in the direction of any relevant documentation?

Thank you for your help!

**Comment by timothycarambat** [comment]
Clicking the `Key` Icon in the top right of sidebar should display a modal with a tab for `Import/Export Database` which is what you would need to do.

Once the DB is exported you can then upload that `.zip` file into the new instance that has no information and the data will be synced. The Pinecone data is stored on the Pinecone.io cloud so there is nothing to migrate - you just need to have your instance know about it

**Comment by hcchengithub** [comment]
![anthingllm- 2023-08-01 093512](https://github.com/Mintplex-Labs/anything-llm/assets/1297015/2bf00860-ecb1-4350-99c4-048ef8910a45)
