### ISSUE TITLE
[DOCS]: "AnythingLLM Debug mode on MacOS" instructions

### ISSUE THREAD

**Issue by devdanke** [Mintplex-Labs/anything-llm#1591]
### Description

I'm running MacOS 14.3.1.

When I started AnythingLLM from its Contents/MacOS, with `open -a AnythingLLM`, no stdout or stderr was written to my console.  I wondered if my console lost its connection to the running AnythingLLM process, so I tried `open --wait-apps -a AnythingLLM`.  Still nothing was written to my console.  Then I tried using the `--stderr` and `--stdout` switches to redirect them to the current dir `Contents/MacOS`, but the app wouldn't even start.  I could only see AnythingLLM's stdout and stderr logging when I redirected them to a file in my home dir.  

Providing an example command-line, in the "AnythingLLM Debug mode on MacOS" section, might help non-command-line savvy users to see AnythingLLM log info more easily. Something like:

`open -a AnythingLLM --stdout ~/anyout.txt --stderr ~/anyerr.txt`

**Comment by timothycarambat** [comment]
https://docs.useanything.com/debug#anythingllm-debug-mode-on-macos
