### ISSUE TITLE
[BUG]: uninstall issue v 1.4..4

### ISSUE THREAD

**Issue by kalle07** [Mintplex-Labs/anything-llm#1592]
### How are you running AnythingLLM?

Docker (local)

### What happened?
(win10)

cant uninstall
cant delete
\AppData\Local\Programs\anythingllm-desktop\
cant instll new (ERROR: please shut down manula LLM)

BUG

### Are there known steps to reproduce?

kill task
uninstall dont work

go to 
\AppData\Local\Programs\anythingllm-desktop
delete all i can (some files proctected)
restart
now i can delete all files

now install new version (1.5.5)
it starts ... hanging 10min on black window "AnythingLLM - loading workspace"
now 2 tasks open i cant kill them

ITS A VIRUS !!!

OMG

**Comment by timothycarambat** [comment]
This is because the app is running and you are trying to delete files while the app is running and/or you lack the permissions on the file.

There is literally an uninstall exe you can run.
https://docs.useanything.com/uninstall#uninstalling-on-windows

**Comment by kalle07** [comment]
![grafik](https://github.com/Mintplex-Labs/anything-llm/assets/118767589/d27ca62d-6185-4466-80cf-8a168730c9b6)

and no "APP" and no "process"  is running named "AnythingLLM "

**Comment by kalle07** [comment]
same bug 1.5.5
