### ISSUE TITLE
[BUG]: Youtube transcript retrieves an empty file o some channels

### ISSUE THREAD

**Issue by brianorca** [Mintplex-Labs/anything-llm#1593]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I can get transcripts for some channels, such as https://www.youtube.com/watch?v=O5GY7_aVBtk

But other channels fail, such as https://www.youtube.com/watch?v=V9KJ7nvhRWk
This results in a zero-byte file in the AppData\Roaming\anythingllm-desktop\storage\documents[channelname] folder.

I did confirm that Youtube shows a transcript for that video. This seems to be across all videos in a channel.

### Are there known steps to reproduce?

Select data connectors-Youtube Trascript in the document upload.
use https://www.youtube.com/watch?v=V9KJ7nvhRWk as the video link.
Check if it found any data in the file.

**Comment by shatfield4** [comment]
Have you tried this again recently? I have tried both links you provided and I'm able to get the transcript for both videos. I think you may have been rate limited from pulling in too many video transcripts, too quickly. This might happen because we are leveraging a hidden/undocumented API by YouTube in order to pull in all the transcripts (with unknown rate limits).

**Comment by RamonMF** [comment]
same issue. I'm just installed AnythingLLM desktop. the same videos that @brianorca uses, the exactly same issue. 

I have no transcription of many other videos, i.e.

https://www.youtube.com/watch?v=61rCf7INomY

**Comment by timothycarambat** [comment]
<img width="406" alt="Screenshot 2025-01-03 at 3 51 18 PM" src="https://github.com/user-attachments/assets/3c263cab-067b-454c-bd4f-e081f1bd9eb9" />
Just pasted that exact link into AnythingLLM and it worked @RamonMF

**Comment by RamonMF** [comment]
yes, I can see this, but then in Documents there is no transcription file

![image](https://github.com/user-attachments/assets/d4ec7240-05ba-4e43-a96c-89833d99d9e9)
