### ISSUE TITLE
[BUG]: Unable to get "Live web search and browsing" agent working using google custom search engine. Error: getaddrinfo ENOTFOUND - http errno: -3008 

### ISSUE THREAD

**Issue by tugzii** [Mintplex-Labs/anything-llm#1595]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Running ollama locally/manually on Windows 11 Pro manual (manually built ollama to support my RX 6750 XT)

.\ollama.exe run llama3:8b-instruct-q8_0

Chat works fine. Embedded Document works. Embedded Scrapper works.

Setup "Live web search and browsing" agent using Google Custom Search (setup new api key and tested in browser url that it worked)

Run: @agent Can you scrape useanything.com and tell me the key features

[AgentHandler] Attached websocket plugin to Agent cluster
[AgentHandler] Attached chat-history plugin to Agent cluster
[AgentHandler] Attaching user and default agent to Agent cluster.
[AgentHandler] Attached rag-memory plugin to Agent cluster
[AgentHandler] Attached document-summarizer plugin to Agent cluster
[AgentHandler] Attached web-scraping plugin to Agent cluster
[AgentHandler] Attached web-browsing plugin to Agent cluster
fetch failed TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async post (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\ollama\dist\shared\ollama.05b0f34c.cjs:81:20)
    at async Ollama.processStreamableRequest (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\ollama\dist\shared\ollama.05b0f34c.cjs:183:22)
    at async #handleFunctionCallChat (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js:20839:26)
    at async OllamaProvider.functionCall (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js:20668:26)
    at async OllamaProvider.complete (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js:20859:40)
    at async AIbitat.handleExecution (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js:22536:28)
    at async AIbitat.reply (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js:22526:25)
    at async AIbitat.chat (C:\Users\sshar\AppData\Local\Programs\anythingllm-desktop\resources\backend\server.js:22377:19) {
  cause: Error: getaddrinfo ENOTFOUND http
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'http'
  }
}
[AgentHandler] End

**Comment by Tuggax** [comment]
Note:

When setting up Google Custom Search I generated API under the following section (not sure if this is correct but didn't see another way to generate API):

### **Programmatic Access**
Custom Search JSON API
Limit of 10,000 queries per day.

**Comment by tugzii** [comment]
Note:

I was running AnythingLLM as "standard user" when I submitted this issue. But have since confirmed same error if I run AnythingLLMDesktop.exe from "admin" terminal.

**Comment by shatfield4** [comment]
Do you have another device you could try testing this on using the same API keys? Also when you ask it to scrape/tell you key features, does the agent chat show a message similar to `@agent: Searching on Google for "useanything.com key features"`? 

It sounds like it may be your firewall blocking the google search endpoints. I have tried to replicate this using an invalid search engine ID and API key and cannot get the same error, so I don't think your keys are wrong.

**Comment by timothycarambat** [comment]
@tugzii and to confirm you _can_ send a chat - just a normal chat without `@agent` to the workspace with no issue? This error is coming from `ollama` not being able to connect to the Ollama instance you are using for chatting. If it is broken in agents it should _also_ be broken in regular chatting as well.

There is a slight difference with ollama in regular chat vs agent chat (fetch api vs Ollama SDK), but the connection information provided should be all the same.

**Comment by tugzii** [comment]
I'm new to Ollama and AnythingLLM but yes, chat seems to be connecting to my local instance of Ollama to answer me.

As mentioned in initial post, I did have to build the Ollama code using the following instructions and run it manually from the cmd prompt (i.e. not as a service and I never downloaded and installed the original Ollama using their installer)

https://github.com/ollama/ollama/issues/3107#issuecomment-2144741411

See attach screenshots to confirm

![admin_anythingLLM_1](https://github.com/Mintplex-Labs/anything-llm/assets/29587732/e01b9ed0-b583-4392-87c7-7c3f17715141)
![admin_anythingLLM_2](https://github.com/Mintplex-Labs/anything-llm/assets/29587732/4d64391b-4c19-4654-850c-0b1b7b4d34f2)
![admin_anythingLLM_3](https://github.com/Mintplex-Labs/anything-llm/assets/29587732/af29bb45-78cc-4a63-979b-e9e8adf1b5cc)

**Comment by tugzii** [comment]
I officially installed Ollama (for windows) and copied my compiled files to the official install location (instead of running from c:\Documents\Ollama):

C:\Users\[username]\AppData\Local\Programs\Ollama 

The errors above went away and I did get a response.

However, the response was not good as even thou it stated that it had scraped the website it gave me data from 2022.

Closing this bug report for now as the above issue no longer appears (but may raise a separate issue for the old scrape data)
