### ISSUE TITLE
Input length, input text colors

### ISSUE THREAD

**Issue by mkammes** [Mintplex-Labs/anything-llm#16]
It appears any text entered gets truncated after 240 characters (?)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/8660699/52c76e07-359e-4b14-9e5a-8df0c3e30ca2)

Edit:

Looks like the textarea maxlength is limited to 240 characters.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/8660699/64030c2f-e1bc-4bff-99af-4c711dc71531)

Also, unless you have a dark mode setting, my text in the same input textbox is white - with a white background - so I can't see what I'm typing.

**Comment by timothycarambat** [comment]
Fixed!
f9015df903c98f8afbc7612b95663ac364f0d06f

Thank you for finding this!

**Comment by DaveLak** [comment]
For anyone in the future that lands here after searching for issues related to "Input length":

The reason for the 240 character limit is described here https://github.com/Mintplex-Labs/anything-llm/pull/62#issuecomment-1594303461.
