### ISSUE TITLE
Is there a limit to the content length of the application's ability to crawl the site? Is the crawling content accurate and comprehensive? Because I need to extract the information from the text accurately and that's very important

### ISSUE THREAD

**Issue by mingLvft** [Mintplex-Labs/anything-llm#1605]
### What would you like to see?

Is there a limit to the content length of the application's ability to crawl the site? Is the crawling content accurate and comprehensive? Because I need to extract the information from the text accurately and that's very important

**Comment by timothycarambat** [comment]
There is no "limit" per se, it is dictated by your LLM's context window. RAG is not perfect and no system has 100% recall even if you put the entire document into the context window there is no guarantee that any LLM will not hallucinate information.
