### ISSUE TITLE
[BUG]: Could not respond to message. fetch failed

### ISSUE THREAD

**Issue by dgaddis11235** [Mintplex-Labs/anything-llm#1613]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I was trying different embedding models with LM Studio and started getting output that was nothing but gibberish. The output then turned into only triangles with a question mark in it. Now, I do not get any responses and only get the message "Could not respond to message. fetch failed" Before this everything seemed to work fine, this issue only started a few hours ago.

**Comment by dgaddis11235** [comment]
I solved the issue and feel like an idiot for even posting this. I will close the issue, and hope that is enough.

**Comment by timothycarambat** [comment]
@dgaddis11235 thank you for at least solving it and cleaning the issue up - very much appreciated and there are no dumb questions here. We are all trying to help!
