### ISSUE TITLE
[BUG]: 10 - 20% gpu being used when embedding files into anything llm in win desktop manager

### ISSUE THREAD

**Issue by LindsayRex** [Mintplex-Labs/anything-llm#1620]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![desktop embedding usage 01](https://github.com/Mintplex-Labs/anything-llm/assets/122247996/da574a8e-1377-4c41-b105-7b5a29c71837)
![desktop embedding usage](https://github.com/Mintplex-Labs/anything-llm/assets/122247996/fd459f85-afbd-404d-a19a-e78b714b585e)

desktop windows  manager goes wild trying to rending the graphics of the embedding loading screen.   using 10 to 20% of the gpu to render the little moving circles seems excessive? 

### Are there known steps to reproduce?

embedded 10  pdfs files at a time..

**Comment by timothycarambat** [comment]
Are we sure that is the process for the frontend? If you are using the built-in embedder then what is occurring is the `Xenova` transformers.js running the local embedder - which would make perfect since to consume resources since we are running a local embedder model on the computer.

**Comment by timothycarambat** [comment]
Looking at this now the task manager is showing this use on CPU with only 0.7% GPU. This checks out. The embedder runs on CPU, so yeah - the local default embedder is running so of course it will use the CPU - that is how it works and runs locally.

**Comment by LindsayRex** [comment]
> Are we sure that is the process for the frontend? If you are using the built-in embedder then what is occurring is the `Xenova` transformers.js running the local embedder - which would make perfect since to consume resources since we are running a local embedder model on the computer."


To add some more context.. when i minimize the anytignllm window, while it it busy doing embedding's..  the desktop manager process immediately drops to under 1% gpu.. or none at all.. as soon I as show the anythingllm app window again.. the desktop manager fires up to 10 to 20% gpu to render the spinning circles., whilst i wait for the embeddings job to  finish.
