### ISSUE TITLE
Can AnythingLLM support langchain API calls?

### ISSUE THREAD

**Issue by heiheiheibj** [Mintplex-Labs/anything-llm#1621]
### What would you like to see?

I have configured it as a knowledge base in AnythingLLM at http://localhost:3001/api/v1/workspace/hehe/chat and the model is LLAMA3 8B. via postman, it can be called fine. Now I want to call it in langchain, how should I do it.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6910198/a46dabf0-857c-412e-9d16-66ce58bd4699)

llm = OpenAI(model_name="llama3:8b", temperature=0,openai_api_key='sk-xxxxxxxxxxxxxxxxx',base_url='http://localhost:3001/api/v1/workspace/hehe/chat')`

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6910198/0cfd492f-0fde-4a3d-890c-5834ab7d9442)

thx ...

**Comment by timothycarambat** [comment]
The API is _not OpenAI compatible_! So that is why it does not work.

**Comment by Twisig** [comment]
Does langchain have a public api available so that I can ask it questions with postman?

**Comment by timothycarambat** [comment]
Langchain is a library - there is no "API" in the sense that it is a service that you can call like a REST service. AnythingLLM API is REST and can be called with postman
