### ISSUE TITLE
[BUG]: MaxLength Configuration in Docker Installation of AnythingLLM

### ISSUE THREAD

**Issue by NEWbie0709** [Mintplex-Labs/anything-llm#1628]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I faced an issue when asking the agent to elaborate more, and this is the error I encountered. I searched on GitHub and found that they suggest editing the maxLength to 500 in the folder 'frontend/src/components/WorkspaceChat/ChatContainer/PromptInput/index.jsx', but I can't find it, inside the fronted folder is empty . I used Docker to install AnythingLLM.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/81673708/c5ced433-aa43-4d18-93ba-91f336d53e5e)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/81673708/927cb5cb-de63-40b5-b710-55ced9ad00c6)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/81673708/2ec67809-1fec-4604-9aeb-aa908b00a89d)

**Comment by timothycarambat** [comment]
The error you are getting has no relation to the `MaxLength` property and it is not even something you would edit in the code, we have a form input for it.

The reason for this is that the agent session has run too long with text and whatever provider you are using is overflowing. What provider/model combination are you currently using?

In the interim, you can `/reset` the chat session or hop to a new thread and the context window will open again. We dont have context window management on the agent session (apparently)
