### ISSUE TITLE
[BUG]: Non- Searchable/ scanned document not supported 

### ISSUE THREAD

**Issue by rpaGuyai** [Mintplex-Labs/anything-llm#1629]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/154881376/db5e0743-a6b4-40ed-b7d1-ab85ebbf6ad1)
I tried uploading scanned PDF but, says no text found.
Is there a way to upload scanned PDFs as well?

### Are there known steps to reproduce?

Select any workspace ->Upload document

**Comment by timothycarambat** [comment]
Moved to https://github.com/Mintplex-Labs/anything-llm/issues/510
