### ISSUE TITLE
im getting error when deploying docker on remote host

### ISSUE THREAD

**Issue by madruga8** [Mintplex-Labs/anything-llm#163]
I have double checked the .env and the constants.js and changed to the target host ip. but still getting this error.

<img width="369" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30551844/ddfbd9a1-7122-4217-b206-d023e197f991">

**Comment by jignnsd** [comment]
Hey there. What scrips did you run?
I'm having kind of the same issue?

**Comment by jignnsd** [comment]
Got it, many thanks @madruga8
