### ISSUE TITLE
Bump Ollama Built-in to latest

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1633]
Built-in Ollama is on v0.1.27

Fixed in v.0.1.33 https://github.com/ollama/ollama/issues/2615

Will reference in new issues

_Originally posted by @timothycarambat in https://github.com/Mintplex-Labs/anything-llm/issues/1632#issuecomment-2155173504_

**Comment by timothycarambat** [comment]
resolved by v.1.5.8 release

**Comment by njss** [comment]
the error persists on windows 11
Ollama call failed with status code 500: llama runner process has terminated: exit status 0xc0000135

**Comment by timothycarambat** [comment]
Not the same error and is again within the scope of ollama and not anythingllm
