### ISSUE TITLE
[BUG]: TTS voice on macOS sounds too whispy when using a Siri based voice.

### ISSUE THREAD

**Issue by andrewkincaid** [Mintplex-Labs/anything-llm#1638]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I'm running AnythingLLM on an intel-based MacBook Pro (2019) running Sonoma 14.5.  If I select any Siri based voice, like English (US) Voice 3, it sounds very airy and it's very difficult to understand.

**Comment by andrewkincaid** [comment]
Also, it doesn't seem to honor the speed setting under: Settings > Accessibility > Spoken Content.

**Comment by timothycarambat** [comment]
We use the Electron/Chromium-based TTS provider engine. The voice is rendered via that process and is not something we directly control. We simply pass the text to the TTS provider and it is read. It is essentially an accesibility tool
