### ISSUE TITLE
Ollama Connection issues FAQ help

### ISSUE THREAD

**Issue by BAK-HOME** [Mintplex-Labs/anything-llm#1640]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

 I deployed AnythingLLM on docker on another server in the local area network, and it was all set up, and ollama was also deployed on the server. I could also open AnythingLLM on the web side on another computer. I couldn't connect to 127.0.1: 11434 according to the tutorial, but I had to use 171.0.1: 11434. I could also select the model in ollama, but a dialog would say,"Could not respond to message.An error occurred while streaming response." Error network: Type Error: fetch failed 
    at Object.fetch (node:internal/deps/undici/undici:11731:11) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
    at async ollamaAIModels (/app/server/utils/helpers/customModels.js:245:18) 
    at async getCustomModels (/app/server/utils/helpers/customModels.js:33:14) 
    at async /app/server/endpoints/system.js:929:35 { 
  cause: Error: connect ECONNREFUSED 127.0.0.1:11434 
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) { 
    errno: -111, 
    code: 'ECONNREFUSED', 
    syscall: 'connect', 
    address: '127.0.0.1', 
    port: 11434” 
 I also added "Environment="OLLAMA_HOST=0.0.0.0"in ollama.service, but it still doesn't work. Is there any way to solve it?

**Comment by BAK-HOME** [comment]
I am using ubuntu22.04 server.

**Comment by timothycarambat** [comment]
Looks like the Endpoint never was saved or set?

> cause: Error: connect ECONNREFUSED 127.0.0.1:11434

You are indeed correct that on Ubuntu Docker you will need to use `171.0.1:11434` to map to localhost on the host. IIRC that IP though maps to 127.0.0.1 and not `localhost` or `0.0.0.0`

Did you look at [this faq page](https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/ollama/README.md) yet? Or is that what you followed and still got connection issues?

**Comment by timothycarambat** [comment]
https://docs.useanything.com/ollama-connection-troubleshooting
