### ISSUE TITLE
[BUG]: Preloaded model gets reloaded

### ISSUE THREAD

**Issue by PaoloC68** [Mintplex-Labs/anything-llm#1643]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I preload codestral, then I start or continue a chat and even if a model is loaded it gets reloaded with 5 min keepalive

### Are there known steps to reproduce?

I try to run anythingLLM with codestral preloaded permanently on ollama:
`ollama run codestral "" --keep-alive -1s`

```
:~$ ollama ps
NAME                ID              SIZE     PROCESSOR    UNTIL
codestral:latest    fcc0019dcee9    13 GB    100% GPU     Forever
```
But when I start a chat with anythingLLM the model gets reloaded:

```
:~$ ollama ps
NAME                       ID              SIZE     PROCESSOR    UNTIL
codestral:22b-v0.1-q4_0    fcc0019dcee9    13 GB    100% GPU     4 minutes from now
```

**Comment by PaoloC68** [comment]
I know that there was a similar bug before but the bug is still present:

https://github.com/Mintplex-Labs/anything-llm/issues/1011

**Comment by timothycarambat** [comment]
Ah yes, being tracked in https://github.com/Mintplex-Labs/anything-llm/issues/1585

That issue was for `mlock`, but not for prevention of unloading. We need to close that chore issue and will set it to something higher since 5 min is quite low.
