### ISSUE TITLE
[BUG]: 500 error while executing /api/v1/system/remove-documents

### ISSUE THREAD

**Issue by ashok-log** [Mintplex-Labs/anything-llm#1650]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When I tried to execute DELETE /api/v1/system/remove-documents I received a 500 Internal server error. On Docker logs, the error reported is:

purgeDocument is not defined ReferenceError: purgeDocument is not defined
    at /app/server/endpoints/api/system/index.js:264:41

### Are there known steps to reproduce?

Use the DELETE API under /api/v1/system/remove-documents

It gives this error.

**Comment by ashok-log** [comment]
Found the bug. Following line missing in:

const { purgeDocument } = require("../../../utils/files/purgeDocument");

/app/server/endpoints/api/system/index.js

const { purgeDocument } = require("../../../utils/files/purgeDocument"); 

must be following 

const { validApiKey } = require("../../../utils/middleware/validApiKey");

**Comment by ashok-log** [comment]
The bug still continues. Now I receive a new error:

Invalid path. Error: Invalid path.
    at normalizePath (/app/server/utils/files/index.js:191:48)
    at purgeDocument (/app/server/utils/files/purgeDocument.js:14:21)
    at /app/server/endpoints/api/system/index.js:265:47

when I execute the same DELETE API for remove-documents. Please look into it.

Thanks.

**Comment by timothycarambat** [comment]
resolved by 29263dab524ed3812b8ae9bfaa052619e416013f

your path issue is likely because STORAGE_DIR is not defined and is a configuration issue
