### ISSUE TITLE
cannot upload files or fetch web in production [BUG]: 

### ISSUE THREAD

**Issue by yongshengma** [Mintplex-Labs/anything-llm#1652]
### How are you running AnythingLLM?

Not listed

### What happened?

I know you have mentioned prod issues wont be supported  but I really need a help as I'm doing modifications on translating some labels.

I am running in production without docker.

Everything looks as good as in devlopment  except uploading files. I cannot click to upload. This doesn't happen in development. Everything goes well in development. 

I noticed that `prod:collector` is missing in package.json. Then I follow the `BARE_METAL.md` to manually start collector but it reports the same error as https://github.com/Mintplex-Labs/anything-llm/issues/1589

### Are there known steps to reproduce?

export STORAGE_DIR=$HOME/anythingllm
touch $HOME/anythingllm/.env
yarn prod:frontend
cp -R frontend/dist server/public
yarn prod:server

Because I couldn't click to upload, I added a step:
cd collector && NODE_ENV=production node index.js &

AnythingLLM was running on http://localhost:3001 but I got the same issue as https://github.com/Mintplex-Labs/anything-llm/issues/1589

The collector didn't output any info on shell prompt.

Any workaround please?

**Comment by timothycarambat** [comment]
Here is a simple helper script:

```
echo "Rebuilding Frontend"
cd /home/ubuntu/anything-llm/frontend && yarn && yarn build && cd /home/ubuntu/anything-llm

echo "Copying to Sever Public"
rm -rf server/public
cp -r frontend/dist server/public

echo "Killing node processes"
pkill node

echo "Installing collector dependencies"
cd /home/ubuntu/anything-llm/collector && yarn

echo "Installing server dependencies & running migrations"
cd /home/ubuntu/anything-llm/server && yarn
cd /home/ubuntu/anything-llm/server && npx prisma migrate deploy --schema=./prisma/schema.prisma
cd /home/ubuntu/anything-llm/server && npx prisma generate

echo "Booting up services."
truncate -s 0 /logs/server.log
truncate -s 0 /logs/collector.log

cd /home/ubuntu/anything-llm/server
(NODE_ENV=production node index.js) &> /logs/server.log &

cd /home/ubuntu/anything-llm/collector
(NODE_ENV=production node index.js) &> /logs/collector.log &
```

notice that we have to copy the frontend to server public _then_ run the equivalent of `prod:server`. This is because in production the frontend is served from the server `public` folder. The we start the collector and server is two processes.
