### ISSUE TITLE
I have an article of tens of thousands of words and need to find the information I need. Can I ask questions directly after uploading the knowledge base to the workspace? Or do you add the article to the question and let the model answer it? My model supports 100k context

### ISSUE THREAD

**Issue by mingLvft** [Mintplex-Labs/anything-llm#1659]
### What would you like to see?

I have an article of tens of thousands of words and need to find the information I need. Can I ask questions directly after uploading the knowledge base to the workspace? Or do you add the article to the question and let the model answer it? My model supports 100k context

**Comment by timothycarambat** [comment]
You can just ask a question. If you are not getting the answers you expect you can refer to this article:
https://docs.useanything.com/llm-not-using-my-docs
