### ISSUE TITLE
How can I upgrade "anythingllm" built with docker?

### ISSUE THREAD

**Issue by mingLvft** [Mintplex-Labs/anything-llm#1660]
How can I upgrade "anythingllm" built with docker?

**Comment by timothycarambat** [comment]
https://docs.useanything.com/update#updating-on-docker

**Comment by gcleaves** [comment]
@timothycarambat the link is no longer available. Upgrade instructions would be great. Last time I tried it I nuked the installation and had to build everything again from scratch.

Usually I just update the image version in the compose file and do `docker compose up -d` to upgrade other systems. But it failed for me.

**Comment by timothycarambat** [comment]
You would just run the same command to start after a `docker pull`
https://docs.anythingllm.com/installation-docker/local-docker

Since the volume for the storage is on the host, it will persist between container destroys and image pulls

**Comment by gcleaves** [comment]
Unfortunately when I do that, the new instance starts giving all sorts of front end javascript errors. It's now happened to me twice. It makes no sense. I wonder if it has something to do with being behind an NGINX reverse proxy for TLS termination that somehow confuses the front end after an upgrade (even if the front end and back end get updated simultaneously.)

I'll need to make a video to prove I'm not crazy ;)

**Comment by timothycarambat** [comment]
> the new instance starts giving all sorts of front end javascript errors

Can you post some? Should be an easy solve. Reverse proxy on NGINX is pretty normal practice and we do it internally for some instances so I know for sure it works. Sharing your site NGINX config could also show where things are going awry

**Comment by gcleaves** [comment]
I disabled an asset caching setting on the reverse proxy and the problem seems to have gone away.
