### ISSUE TITLE
[BUG]: Cannot rename thread -- Rename thread dialog disappears while attempting to change thread name.   C

### ISSUE THREAD

**Issue by reh-ino** [Mintplex-Labs/anything-llm#1662]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

My original install version was v1.5.5
Yesterday I upgraded to v1.5.6

I can't rename threads.

### Are there known steps to reproduce?

Win 10,  AnythingLLM v1.5.6

- When I click on a thread and then the "..." three dots, I get a dialog to change the name.
- As soon as I place the cursor with my mouse in the edit box for changing the name, the dialog closes without changing the name.

**Comment by AIbottesting** [comment]
I confirm your issue (Win 10, AnythingLLM v1.5.6)
Cool feature though! (to auto-name the thread)

**Comment by timothycarambat** [comment]
resolved with f19e50bbc70b4397a0b1352373e041693af037b0

(will be in next patch)
