### ISSUE TITLE
[IDEA] Can select more than 1 workspace to chat with (multi select workspaces)

### ISSUE THREAD

**Issue by jignnsd** [Mintplex-Labs/anything-llm#167]
Hello, I think will be good idea to have the option to **multi select workspaces**, to have a chat with the documents of all the selected workspaces.

Let's say that you are a law firm and you have a client with many cases with you and you have a workspace for each case you have. Then let's say that you have "workspace 1" for the "case A", "workspace 2" for "case B". You are chasing with the documents in workspace 1 (case A) and working with that. In the other hand you do the same with workspace 2 (case B). In some point, the law firm will need to interact with case A and case B. Instead of adding all the documents to one workspace, will be great to just for that chat conversation select workspace 1 and workspace 2 and do the interaction.

how does that sound?

many thanks!
Javier

**Comment by iokinpardo** [comment]
I agree, this seems to be super useful. 👌

**Comment by jignnsd** [comment]
Hey @timothycarambat , do you think feature is worth to add? 
Many thanks for the great project.

**Comment by timothycarambat** [comment]
While i like the notion, the complexity of supporting this specific interface as opposed to just adding the two sets of documents into a new workspace - it would not be worth managing the complexity for a feature that would likely have very limited us as if you had enough questions crossing over Workspace A and Workspace B, you would just make a new workspace so it would persist.
