### ISSUE TITLE
【If this is what you want, you are thinking of agents, which are coming to AnythingLLM soon.】 What does this sentence mean? Does that mean rag can retrieve all the contents of the document?

### ISSUE THREAD

**Issue by mingLvft** [Mintplex-Labs/anything-llm#1670]
### Description

【If this is what you want, you are thinking of agents, which are coming to AnythingLLM soon.】 What does this sentence mean? Does that mean rag can retrieve all the contents of the document?

**Comment by timothycarambat** [comment]
I have no idea where this sentence is coming from. The agent is able to summarize any specific doc in your embedded files and can do general rag. If you want to get all the content of a document that is **not** RAG. 

You should look at document pinning.

Also can you please use discord for general questions? Github is for technical discussion, features, and bugs - not a general fourm
