### ISSUE TITLE
[BUG]: OpenAI does not have access to text-moderation-007

### ISSUE THREAD

**Issue by IMTanuki** [Mintplex-Labs/anything-llm#1671]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

**Installed a default OpenAI setup:**
LLM Provider - OpenAI
workspace chat model - gpt-4o
-- also tried gpt-4, gpt-0613
chat mode - chat
history - 20
prompt - default
refusal response - default
temp - .7

**Prompt:**
- can be anything
- I tried a complex request, as well as 'Hello'

**Error:**
OpenAI::CreateModeration failed with: 403 Project `proj_xxx` does not have access to model `text-moderation-007`

**Notes**
- text-moderation-007 is not a listed model in OpenAi's project models
- I understand this is a dedicated moderation endpoint to detect inappropriate requests
- this error is listed in OpenAI community (as of 1 week ago), but no answer is listed

Is there any way to suppress this call?

### Are there known steps to reproduce?

See notes above.
Error occurs regardless of the prompt.

**Comment by timothycarambat** [comment]
Referring to this discussion, correct?
https://community.openai.com/t/no-access-to-text-moderation-models/760242/12

**Comment by IMTanuki** [comment]
yup
tbh - my goal w/ anything is to migrate away from openai and it's progressively limited functionality, including text moderation. I've got a new MSI w/ 64GB and and RTX 4090 w 16GB and I'm hoping that will drive an LLM from Mistral.  I guess my question would be - does anything use a variant of text-moderation w/ other open source LLM's?

**Comment by timothycarambat** [comment]
> does anything use a variant of text-moderation w/ other open-source LLM's?

Only OpenAi has moderation on chats and its high time we just remove it/make it opt-in. It originally existed simply because we didn't want people accidentally getting themselves banned but to force it enabled, but **only** OpenAI makes little sense now since all others are unmoderated and at the end of the day...its your key!

**Comment by timothycarambat** [comment]
I am with the core-team for Mintplex Labs which builds this tool. 

> Just to confirm - with all other LLM's, no issues, right?

Correct! If you get any refusals it's either from the model directly or if using some cloud-based LLM they may do some censoring, but nothing we control.

**Comment by IMTanuki** [comment]
Cool! Thx for the clarification. Just downloaded anything (Win app) last night - UI and options look great! Hope to get it running w/ a Mistral LLM later today.

**Comment by IMTanuki** [comment]
Sorry for re-opening this issue but I was wondering - I have my own (very basic) openAI client and I never get the text-moderation-007 error. Is there sth unique about how anything interfaces with openAI?

**Comment by timothycarambat** [comment]
If you are not using the moderation endpoint, then you would never see this error

**Comment by IMTanuki** [comment]
Not to beat this to death, but if my client doesn't encounter the text-moderation-007 error, presumably bc I'm not using the moderation endpoint, then can't Mintplex likewise remove its use of the same endpoint? Unless I'm missing something, it seems like that should be a relatively easy solution to this issue.

**Comment by timothycarambat** [comment]
That is what I was saying in https://github.com/Mintplex-Labs/anything-llm/issues/1671#issuecomment-2166116264

**Comment by IMTanuki** [comment]
Not having this problem with any other open source or proprietary OpenAI client. Can't move forward until it's resolved.
