### ISSUE TITLE
[BUG]: The rename window keeps quitting

### ISSUE THREAD

**Issue by argoyal** [Mintplex-Labs/anything-llm#1672]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When I am trying to rename a thread in a workspace a popup window opens to punch in the name for the thread and as soon as I click on the input box to edit the name the popup window goes away.

I am using the Anything LLM Mac App (Apple Silicon) - v1.5.6

### Are there known steps to reproduce?

Following are the steps to reproduce

1. Create a workspace
2. Start a new thread
3. Click on three dots in the workspace explorer window against your thread and click on rename
4. Click on input box to rename
5. The popup window closes

**Comment by ethyoo** [comment]
A fix was published with [v1.5.7](https://docs.useanything.com/changelog/v1.5.7): "Fix issues where you could not rename threads manually"

**Comment by argoyal** [comment]
@ethyoo thanks for this. this issue seems to be resolved now.
