### ISSUE TITLE
[BUG]: document processor unavailable 

### ISSUE THREAD

**Issue by jackfood** [Mintplex-Labs/anything-llm#1674]
### How are you running AnythingLLM?

AnythingLLM desktop app 1.5.5 to 1.5.7.

### What happened?

I am using a corporate desktop running windows 10, with restricted admin right controlled via domain. When I starts, I am unable to upload any files, showing 'Document Processor unavailable, we can't upload your files right now because the document processor offline. Please try again later'

The app is installed in C:\user\<username>\AppData\Local\Programs\Anythingllm-Desktop.

![Uploading 17182690483027225754161957228031.jpg…]()

**Comment by timothycarambat** [comment]
The image failed to upload, but in general the collector app should attempt to bind to port 8888 and if unavailable the process will bind to another port. I presume the app has been fully quite and rebooted post-update and was not updated while open.

Are you able to retrieve logs from the appropriate debug method? https://docs.useanything.com/debug

**Comment by jackfood** [comment]
Here is the log using cmd windows. Thanks for looking into the issue.

`[Preferences] preference config stored at C:\Users\WindowsUser\AppData\Roaming\anythingllm-desktop\config.json
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:C:/Users/WindowsUser/AppData/Roaming/anythingllm-desktop/storage/anythingllm.db"

Already in sync, no schema change or pending migration was found.

Running generate... (Use --skip-generate to skip the generators)
Error: request to https://binaries.prisma.sh/all_commits/61e140623197a131c2a6189271ffee05a7aa9a59/windows/query_engine.dll.node.gz.sha256 failed, reason: connect ETIMEDOUT 104.22.22.109:443
Prisma schema loaded from prisma\schema.prisma
Error: request to https://binaries.prisma.sh/all_commits/61e140623197a131c2a6189271ffee05a7aa9a59/windows/query_engine.dll.node.gz.sha256 failed, reason: connect ETIMEDOUT 172.67.4.173:443
[OllamaProcessManager] Ollama will bind on port 11434 when booted.
[Preferences] Will load window with last know bounds.
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'uc.micro'
Require stack:
- C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\linkify-it\build\index.cjs.js
- C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mailparser\lib\mail-parser.js
- C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mailparser\index.js
- C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mbox-parser\dist\Parser.js
- C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\mbox-parser\dist\index.js
- C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\collector.js
-
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/utility_init:2:3040)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\WindowsUser\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\linkify-it\build\index.cjs.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\WindowsUser\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\linkify-it\\build\\index.cjs.js',
    'C:\\Users\\WindowsUser\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mailparser\\lib\\mail-parser.js',
    'C:\\Users\\WindowsUser\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mailparser\\index.js',
    'C:\\Users\\WindowsUser\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mbox-parser\\dist\\Parser.js',
    'C:\\Users\\WindowsUser\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\node_modules\\mbox-parser\\dist\\index.js',
    'C:\\Users\\WindowsUser\\AppData\\Local\\Programs\\anythingllm-desktop\\resources\\backend\\collector.js',
    undefined
  ]
}

Node.js v18.16.1
[TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
prisma:info Starting a sqlite pool with 13 connections.
[TELEMETRY SENT] {
  event: 'server_boot',
  distinctId: '2a0d551c-df4a-410f-a197-fe78c56bd74f',
  properties: { runtime: 'desktop' }
}
Hot loading of AnythingLLMOllama - LLM_PROVIDER is anythingllm_ollama.
[NativeEmbedder] Initialized
[CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.
[production] AnythingLLM Standalone Backend listening on port 3001
[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.
[OllamaProcessManager] [windows] Ollama subprocess running. Port 11434. PID 5496.
OllamaAPI offline - retrying. 1/3`

**Comment by timothycarambat** [comment]
@jackfood Is the system running the app offline? I only ask as the main issue is
> Error: Cannot find module 'uc.micro'

Which appears to only be a dependency for parsing `mbox` types files. This should obviously not block boot up and others do not seem to suffer from it. So want to see what is going on client side that could prevent that.

I _strongly suspect_ this is some local AV software stripping the `uc.micro` library from the system because it does not like that "extension" even though it is a folder. [Reference](https://github.com/microsoft/vscode/issues/13559)
 
If you allowlist AnythingLLM in your AV - does the problem go away?
_closing for now, since it appears to be client side, but discussion can still continue_

**Comment by jackfood** [comment]
Thanks for your reply. I do not have control of AV whitelist as it is corporate laptop controlled by domain (encrypted by bitlocker). However, the same type of laptop (unencrypted) using same AV using mklink to bring anythingllm to D:\  solves this issue of uploading.
