### ISSUE TITLE
[FEAT]: Bulk prompting

### ISSUE THREAD

**Issue by ericthomas1** [Mintplex-Labs/anything-llm#1680]
### What would you like to see?

If one could upload a folder of documents (or if [this feature was enabled](https://github.com/Mintplex-Labs/anything-llm/issues/1679), an entire Container of docs) then a single prompt issued to be executed on each individual document...that would be a HUGE win.

**Example**:
1. Connect to an Azure Blob Storage Container
2. Then back in the prompting area, select the Container and issue a single prompt to execute on all
    - `Summarize this document into 4 sentences or less`, etc.
3. BONUS: Save the results into yet another Container!...wow

**Comment by timothycarambat** [comment]
You could do this via the `@agent` skill for document summarization, a competent model, and uploading all the documents into the workspace 👍
