### ISSUE TITLE
[BUG]: Fetch failed error for a PDF document loaded on workspace

### ISSUE THREAD

**Issue by velteyn** [Mintplex-Labs/anything-llm#1682]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hello, I obtain a Fetch failed error after I loaded a PDF document to a workspace.
![immagine](https://github.com/Mintplex-Labs/anything-llm/assets/1019294/8682fb1b-24aa-42ac-9906-0bcd7ecb0caf)
The error log is showing nothing  related , Is this the correct place to read the logs ?
![immagine](https://github.com/Mintplex-Labs/anything-llm/assets/1019294/72d7eb9b-b16f-4805-be31-1a77225f4939)

### Are there known steps to reproduce?

I'm using Linux mint Cinnamom and the desktop app. Im using ollama on the same machine (slow but it works for normal chat) and the model is llama3:8b-instruct-q8_0
To reproduce I simply created a workspace, loaded a pdf file to workpace and started the agent... 
After I asked something related to the pdf I obtain the error above.

**Comment by timothycarambat** [comment]
Can you send a basic non-agent chat on a workspace? or does that not work as well?

**Comment by befama** [comment]
Hi, 
I am experiencing a similar issue. I'm using Ubuntu Server 22.04, and while the chat function works well with various LLMs (like Mistral, Llama, etc.), I encounter an error when uploading documents to the workspace—specifically, I receive a "fetch failed" error. Although I can upload and organize documents in the "My Documents" section without any issues, the problem arises when I try to upload them to the workspace. I would greatly appreciate your assistance in resolving this issue.

**Comment by befama** [comment]
Hi,
The default embedding template for anythingLLM didn't seem to work for me. I installed a different embedding template from Ollama, updated the configuration in anythingLLM, and this resolved the issue. I hope this information helps anyone facing similar problems.
