### ISSUE TITLE
[BUG]: Cannot chat with Gemini API key. 

### ISSUE THREAD

**Issue by harwinpopat** [Mintplex-Labs/anything-llm#1689]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/84907767/9a7c6104-516d-4f72-8f51-e81b20bb87b6)

When using the API key from Gemini and adding that to the Workspace LLM Provider, I get this error - [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: Cannot convert argument to a ByteString because the character at index 486 has a value of 8211 which is greater than 255.

### Are there known steps to reproduce?

Add Gemini API key in Workspace LLM Provider and chat with it.

**Comment by timothycarambat** [comment]
Does this occur on a workspace with no documents embedded in it?

**Comment by harwinpopat** [comment]
Happens either way.

**Comment by timothycarambat** [comment]
I am unable to reproduce this with our key(s). You do have access to 1.5 Pro, correct? We have some contacts who exclusively use Gemini so if this was a pervasive bug i'd be getting emails from all of them. 🤔
