### ISSUE TITLE
[FEAT]:  searXNG as an additional way to web-browse, no API key

### ISSUE THREAD

**Issue by FemBoxbrawl** [Mintplex-Labs/anything-llm#1690]
### What would you like to see?

I just think it can be personally annoying having to use an API key sometimes, and was thinking that  it would be a addition, to sort of be able to do instant web browsing without worrying about API keys.

**Comment by timothycarambat** [comment]
Tracking in https://github.com/Mintplex-Labs/anything-llm/issues/1367!
