### ISSUE TITLE
[FEAT]: Persist query mode refusal responses as chat history

### ISSUE THREAD

**Issue by santini-cyber** [Mintplex-Labs/anything-llm#1696]
### What would you like to see?

In our dev environment we typically will roll out a new ALLM build every four to six weeks.  We have a set of standard tests that we run to validate the build process.  In our use case, we are using ALLM for document analysis via the API. In our document analysis workflow, the refusal response is an important data point.  In our Feb, March, and April builds we were receiving a refusal response (from the LLM) which was returned via the ALLM API.  Starting in our June build we noticed that the API was no longer returning the refusal response and the refusal response was not being written to the local database.  When interacting through the UI, the refusal response is presented to the user but does not persist in the Workspace Chats.  We set up a test to validate this observation. We ran the exact same queries and workspace configuration side by side comparing the April vs. June builds.  With the same query, model, and workspace configuration the April build returns a refusal response via the API and persists to the local db, while the June version does not.  Can we bring back this feature?  I believe it is a very valuable analytical capability of the ALLM platform.

**Comment by timothycarambat** [comment]
The refusal from the LLM itself, from the perspective of AnythingLLM, is a chat response.
We did add "Custom Chat refusal response" as a property of the workspace. Are you saying that when you get these refusals the chat is not stored and you would like to keep these prompt/responses as well? They are currently omitted from chat history and are not saved.

**Comment by santini-cyber** [comment]
I built and tested a new version of ALLM yesterday.  The refusal responses are persisted in local db storage and accessible via "Workspace Chats". When I attempt to export via /api/v1/workspace/{workspace}/chats endpoint, the refusal responses are not returned. Would it be possible to allow refusal responses to be returned from this api endpoint?

**Comment by timothycarambat** [comment]
We exclude the refusals from being included in the `/chats` because then they would be part of the history and would use tokens/impact chat results since they would persist in the history during a prompt session

**Comment by santini-cyber** [comment]
Thank you for your response @timothycarambat . I get it from an economic perspective.  I feel like as the language models mature and continue to expand their intelligence, the refusal responses will be valuable context for the AI. For example they would provide a holistic perspective on human patterns of inquiry which could then be used to provide more helpful responses.
