### ISSUE TITLE
[BUG]: Problem unexpected token 'i'. "Internal S"... is not valid Json..

### ISSUE THREAD

**Issue by Carioca72** [Mintplex-Labs/anything-llm#1698]
### How are you running AnythingLLM?

anythingLLM cloud version Professional

### What happened?

I had the error mentioned above. Everything happened after trying a link from a website called "investSite.com.br". The wizard that we are trying to feed data from the site did not work, and then I fed another site and it gave this error. Please note: I did one thing at a time and still got the 502 error. Now I don't have access to the bill I paid, much less I can feed the AI. Need help

### Are there known steps to reproduce?

The error is: I put the link to a website called B3.com.br (finance and assets website).  And I added it to workspace and put it to feed

**Comment by timothycarambat** [comment]
You should email team@mintplexlabs.com for any hosted cloud issues. This GitHub is not the place to submit tickets for any issues you run into on the hosted service.

https://docs.useanything.com/cloud/error-502
