### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net')

### ISSUE THREAD

**Issue by sasi143** [Mintplex-Labs/anything-llm#170]
Unable to communicate with openAI service

anything-llm    | Traceback (most recent call last):
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
anything-llm    |     worker.init_process()
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
anything-llm    |     self.load_wsgi()
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
anything-llm    |     self.wsgi = self.app.wsgi()
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
anything-llm    |     self.callable = self.load()
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
anything-llm    |     return self.load_wsgiapp()
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
anything-llm    |     return util.import_app(self.app_uri)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
anything-llm    |     mod = importlib.import_module(module)
anything-llm    |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
anything-llm    |     return _bootstrap._gcd_import(name[level:], package, level)
anything-llm    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
anything-llm    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
anything-llm    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
anything-llm    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
anything-llm    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
anything-llm    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
anything-llm    |   File "/app/collector/wsgi.py", line 1, in <module>
anything-llm    |     from api import api
anything-llm    |   File "/app/collector/api.py", line 2, in <module>
anything-llm    |     from scripts.watch.process_single import process_single
anything-llm    |   File "/app/collector/scripts/watch/process_single.py", line 2, in <module>
anything-llm    |     from .filetypes import FILETYPES
anything-llm    |   File "/app/collector/scripts/watch/filetypes.py", line 1, in <module>
anything-llm    |     from .convert.as_text import as_text
anything-llm    |   File "/app/collector/scripts/watch/convert/as_text.py", line 4, in <module>
anything-llm    |     from ...utils import tokenize
anything-llm    |   File "/app/collector/scripts/utils.py", line 2, in <module>
anything-llm    |     encoder = tiktoken.encoding_for_model("text-embedding-ada-002")
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/tiktoken/model.py", line 75, in encoding_for_model
anything-llm    |     return get_encoding(encoding_name)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
anything-llm    |     enc = Encoding(**constructor())
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
anything-llm    |     mergeable_ranks = load_tiktoken_bpe(
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/tiktoken/load.py", line 116, in load_tiktoken_bpe
anything-llm    |     contents = read_file_cached(tiktoken_bpe_file)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/tiktoken/load.py", line 48, in read_file_cached
anything-llm    |     contents = read_file(blobpath)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file
anything-llm    |     resp = requests.get(blobpath)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/requests/api.py", line 73, in get
anything-llm    |     return request("get", url, params=params, **kwargs)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/requests/api.py", line 59, in request
anything-llm    |     return session.request(method=method, url=url, **kwargs)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
anything-llm    |     resp = self.send(prep, **send_kwargs)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
anything-llm    |     r = adapter.send(request, **kwargs)
anything-llm    |   File "/app/collector/v-env/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
anything-llm    |     raise ConnectionError(e, request=request)
anything-llm    | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd164d929b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
anything-llm    | [2023-08-02 08:19:59 +0000] [19] [INFO] Worker exiting (pid: 19)
anything-llm exited with code 1

**Comment by timothycarambat** [comment]
Unrelated to anythingllm - is a DNS issue with the tiktoken model download. There was a service interruption but the name appears to resolve now

`curl -I https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken` => 200
