### ISSUE TITLE
[FEAT]: Delete all chat history at once.

### ISSUE THREAD

**Issue by chalitbkb** [Mintplex-Labs/anything-llm#1701]
### What would you like to see?

Sometimes, I just want to delete all the old chat messages in one go. Imagine how tedious it would be to delete them one by one if there were a lot.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/c2ec0a90-27b1-4722-98fe-f464eef57d3f)

**Comment by timothycarambat** [comment]
Hold Control and you can quickly click and remove all the threads you want to prune.

**Comment by chalitbkb** [comment]
> Hold Control and you can quickly click and remove all the threads you want to prune.

I know it can be done, but sometimes when there are a lot of items, like 100, it becomes quite cumbersome to click each one individually. I think it's too many steps. At the very least, there should be an additional button to delete all items without selecting them one by one. This would make the process more flexible because users often have different needs. In my opinion, to cover all bases, you might want to consider adding this feature.
