### ISSUE TITLE
Possible to ignore NPM Packages?

### ISSUE THREAD

**Issue by ericthomas1** [Mintplex-Labs/anything-llm#1703]
Hello,

There are some features of Anything LLM that we do not want to enable. Things like `anthropic*`, `google*`, `weaviate*`, `qdrant*` etc. 

Can we remove these packages from the `server/package.json` and still have a successful installation of Anything LLM?

Thank you

**Comment by timothycarambat** [comment]
You could, as if the resulting code that references those imports is not explicitly called the service should not crash. Obviously, we don't recommend doing this, but it is possible if this is some kind of requirement you have

**Comment by ericthomas1** [comment]
Thank you for the quick response. 

**Just so I'm clear**: 
    1. If I remove these packages from `server/package.json`, Anything LLM would *install* without issue. AND
    2. If I either...
        - ...remove the ability for a user to call the missing reference OR
        - ...if I don't call the missing references myself in, say, the admin area...
...Anything LLM should work?

**Comment by timothycarambat** [comment]
yes, but again - if it doesnt work we cannot help or will support running AnythingLLM in that manner. We include the packages because they are part of the app. So you can do that at your own risk
