### ISSUE TITLE
What is `posthog-node` used for in Anything LLM

### ISSUE THREAD

**Issue by ericthomas1** [Mintplex-Labs/anything-llm#1705]
Hello,

One of the dependencies in `server/package.json` is `posthog-node`. The [npm docs](https://www.npmjs.com/package/posthog-node) are scant. Followed the links to the [product docs](https://posthog.com/product-analytics). 

**Questions**:
1. Which product does Anything LLM use?
2. Does `posthog` power the anonymous telemetry in Anything LLM or does it power user analytics that are surfaced in the admin panel?

Thank you

**Comment by timothycarambat** [comment]
This is outlined in our README.
https://github.com/Mintplex-Labs/anything-llm?tab=readme-ov-file#telemetry--privacy

You can disable it from the UI under the "Privacy and Data Handling" setting in sidebar. These metrics are not used for any admin panel that is used in the application and is purely for the core team and no instance specifics or IP addresses are collected.

**Comment by ericthomas1** [comment]
Thank you @timothycarambat. Will Anything LLM install and run if `posthog` is removed from `server/package.json`?

**Comment by timothycarambat** [comment]
yes, but you need to also remove all `Telemetry` calls
