### ISSUE TITLE
[BUG]: Doesn't work under proxy environment?

### ISSUE THREAD

**Issue by freesiafreesia** [Mintplex-Labs/anything-llm#1710]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Windows 10
WSL2
Ubuntu 22.04
Proxy environment

The installation seems to have been successful, but everytime I use gemini-api I get the following error:
```
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:streamGenerateContent?alt=sse: fetch failed
```
![image](https://github.com/Mintplex-Labs/anything-llm/assets/82436722/fd2d6b02-81f2-4793-b99e-c85fec8ef425)

But on the same environment, if I use same api-model and key with curl, I can get a respons.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/82436722/f10a025c-8dd1-4eac-8327-803d21ebf1a9)

And it's not only the gemini problem.
I cannot get a response from Anthropic neither.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/82436722/7d25fa8c-9937-43c8-9f37-eb207c65b0e7)

I have installed AnythingLLM using the same procedure on a PC that is not under proxy, none of the errors above will not occur.
It seems something to do with a proxy...

**Comment by timothycarambat** [comment]
Correct, Proxy will break SSL connections
Tracking at https://github.com/Mintplex-Labs/anything-llm/issues/1228

**Comment by paulgear** [comment]
> Correct, Proxy will break SSL connections

For the record, a normal (non-intercepting) HTTP proxy will not break SSL connections.  Most HTTP libraries support connecting via proxies using the CONNECT HTTP method, which simply tunnels the TLS session through the proxy.
