### ISSUE TITLE
can not load models[BUG]: 

### ISSUE THREAD

**Issue by Hotlat6077** [Mintplex-Labs/anything-llm#1713]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![微信图片_20240618171526](https://github.com/Mintplex-Labs/anything-llm/assets/52187584/24376cdf-db3d-418b-9999-8f078c182a0d)

**Comment by timothycarambat** [comment]
Please refer to https://docs.useanything.com/ollama-models-not-loading and https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/ollama/README.md

And lastly, `ollama serve` should be running on the host machine outside of docker so that it can be reached.
