### ISSUE TITLE
AnythingLLM with RAG and Vector Database Provider (Croma) Reloads LLM in VRAM

### ISSUE THREAD

**Issue by Smocvin** [Mintplex-Labs/anything-llm#1717]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I want to report an issue with AnythingLLM when using Retrieval-Augmented Generation (RAG) and the vector database provider, Croma. When I have some vectors for RAG, the chat process involves uploading and downloading the LLM model into the VRAM every time I input a question. This results in a noticeable delay due to the repeated model loading process.

However, when I use Ollama directly, there are no such delays related to uploading and downloading the LLM into the VRAM. Additionally, I do not experience any delays when using AnythingLLM without the vector database (Vector Database set to 0).

This indicates that the issue is specifically related to the interaction between AnythingLLM, RAG, and the Croma vector database.

--------------------------------------------------------
2X Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
RAM 256Gb DDR3
2X RTX-2080TI
Centos7
AnythingLLM - Docker (Local)

**Comment by Smocvin** [comment]
An update: The LLM reloads in VRAM every time only when using a third-party embedding provider (I use Ollama snow-flake-arctic-22m). There are no issues with the original AnythingLLM embedder.

**Comment by timothycarambat** [comment]
@Smocvin Are you using Ollama for your embedder or LLM or both? The issue only mentions you using Ollama as your LLM

**Comment by Smocvin** [comment]
When I use LLM -> Ollama and embedder  "snow-flake-arctic-22m" -> Ollama = LLM in VRAM is uploading and dowloading
When I use LLM -> Ollama and embedder Original AnythingLLM = no issues with LLM uploading and dowloading in VRAM

**Comment by timothycarambat** [comment]
It is related to this issue and would be solved by this PR:
- Ollama model unloads after 5 minutes  #1585

The loading into vRAM is because we `mlock` it for future call performance. The timeout will resolve that matter _however_ if you use Ollama for embedding and LLM **and** the system cannot hold both models in VRAM it will kick one out to make room for the one it needs it both cannot fit.

That is what is going on here - linked PR will fix that so moving discussion there

**Comment by Smocvin** [comment]
I see the problem. The issue is not with AnythingLLM; it's with Ollama. Ollama cannot hold two models simultaneously, even though I am using small models that should fit in the VRAM.

**Comment by Smocvin** [comment]
**Solution to Ollama VRAM Issue**
I found the solution to the issue:

Open the file /etc/systemd/system/ollama.service.
In the [Service] section, add the following line:

`Environment="OLLAMA_MAX_LOADED_MODELS=3"`
Save the file and close it.
Next, execute the following commands in the terminal:

```
systemctl daemon-reload
systemctl restart ollama
```
This configuration change allows Ollama to hold up to three models simultaneously, resolving the VRAM reloading issue.

**Comment by timothycarambat** [comment]
@Smocvin TIL! I did not know that was even a ENV key for ollama 😆
