### ISSUE TITLE
why llm offline? help  ToT

### ISSUE THREAD

**Issue by lilinrestart** [Mintplex-Labs/anything-llm#172]
help:(
![image](https://github.com/Mintplex-Labs/anything-llm/assets/140720825/6043a623-7e4e-466a-aa09-32bf2217eecb)
this is my .env
![image](https://github.com/Mintplex-Labs/anything-llm/assets/140720825/5727aedd-5f84-4010-8cf2-5fd970d84ccd)

**Comment by timothycarambat** [comment]
server port is 7027 but the `frontend/utils/constants` expects the internal API address to be on `localhost:3001/api` you need to set another variable for `VITE_API_BASE="/api"` this will infer the API URL from the current host on docker.

**Comment by lilinrestart** [comment]
> 

I started the program using docker-compose, so how can I modify the parameters：）

**Comment by lilinrestart** [comment]
> > 
> 
> 我使用docker-compose启动程序，那么如何修改参数：）

I made changes docker-compose.yml-->ports:7027:3001,and change .env SERVER_PORT=3001

>

**Comment by lilinrestart** [comment]
> > > 
> > 
> > 
> > 我使用docker-compose启动程序，那么如何修改参数：）
> 
> I made changes docker-compose.yml-->ports:7027:3001,and change .env SERVER_PORT=3001
> 
> >

not work for this ,llm offline:(  . @timothycarambat
