### ISSUE TITLE
[BUG]: Failed to add document, document extraction failed.

### ISSUE THREAD

**Issue by sonlige** [Mintplex-Labs/anything-llm#1720]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hello, I am from China, and I am running AnythingLLM on a server using Docker and accessing its interface in a browser. Then I upload files, and after the files are uploaded, I submit them to the workspace. However, I get an extraction failure. My ollama already has the qwen2 model downloaded, and AnythingLLM is able to connect to the qwen2 model during initialization.

**Comment by dalekirkwood** [comment]
I'm getting this error every time I try to upload a file - I'm running on Railway but we are considering the cloud version. We just wanted to test. Is the cloud version more reliable?

Error: Unexpected token '<', "<!doctype "... is not valid JSON

Could this be the same bug or should I open a new ticket?

**Comment by timothycarambat** [comment]
@sonlige - Qwen is an LLM, what are you using for your embedding model. I have seen people try to use an LLM as their embedder and that usually is the issue for some. If you are using the default embedder this shouldn't be an issue. What is your setup?

@dalekirkwood the error you got indicates that the upload failed from trying to embed a large file. Its worth noting that the built-in embedder runs on CPU and even a moderate document on Railways _default_ container size is one 1vCPU and like 512MB of RAM and will crash unless you allocate more resources. 

Check the logs and/or resources and you'll probably see it maxed out and that is why it crashed. Railway will auto-reboot on crash, but the logs will persist from the crash. If it crashes with no exit code, that is the reason.

**Comment by sonlige** [comment]
@timothycarambat  Thank you for your reply. I successfully uploaded the file by modifying the embedder and changing it to the Ollama connection.
