### ISSUE TITLE
[BUG]:  When I attempt to use the Vector Database provided by Qdrant, the chatbot responds with the error message: ‘Could not respond to message. Fetch failed.’

### ISSUE THREAD

**Issue by pengge** [Mintplex-Labs/anything-llm#1721]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

 When I change the default vector database to Qdrant and use the input URL ‘http://localhost:6333,’ 
 ![localhost_url](https://github.com/Mintplex-Labs/anything-llm/assets/3012297/cef44099-2889-4c42-af5d-b5a03b31d5af)
 the chatbot replies with an error message: ‘Could not respond to message. Fetch failed.’ 
 ![error Info](https://github.com/Mintplex-Labs/anything-llm/assets/3012297/8623c0a6-0629-40dd-b9fa-027efd522f86)
 
 However, if I use the input URL ‘http://127.0.0.1:6333,’
![127_url](https://github.com/Mintplex-Labs/anything-llm/assets/3012297/464e3af0-7b1b-4bc7-9f7b-1b1414564b67)
 it works fine.

**Comment by timothycarambat** [comment]
This is because the qdrant application is not binding to the `localhost` loopback and is instead binding to the address of `127.0.0.1` - this is common for some applications or docker setups

**Comment by mcandiav** [comment]
I have simila issue. I am using easypanel to deploy all my services. AnythingLLM also Qdrant. The only way  that works for me was. Installing both AnythingLLM and Qdrant on the same Easypanel's project and give the name http://projectname_qdrant:6333/ in that way I make it works perfectly. 
Anothe issue is to use qdrant selfhosted inside easypanel. It has been almost impossible to use qdrant with anythingllm. I can use qdran in N8N without any problem. Only Anythingllm localy on my pc cant use qdrant at all. Any solutions?
