### ISSUE TITLE
[BUG]: 504 Gateway Time-out

### ISSUE THREAD

**Issue by cyberlink1** [Mintplex-Labs/anything-llm#1722]
### How are you running AnythingLLM?

Docker (local)

### What happened?

AnythingLLM is running in my docker swarm, Im using Ollama on a seperate server that has 8 cores/16 threads, 32g of ram and 2x GTX1660's.

When I do a chat api call through api/docs, the system responds with 

`<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>`

about 60% of the time. 

Through the anythingllm interface I always get a response though it can take up to 45 seconds to respond.

**Comment by timothycarambat** [comment]
We dont run a webserver/proxy in AnythingLLM by default so this is a configuration with whatever webserver is running your swarm - which looks like nginx and would be outside of scope for this repo.

I would check that layer of your stack as that is where the error is coming from. All request should be proxy-passed to the <Ipaddress>:3001 URL of the docker container.

**Comment by cyberlink1** [comment]
@timothycarambat Thank you for the reply. I had completely forgotten that I have haproxy offloading SSL. You were correct, that was the problem.
