### ISSUE TITLE
[BUG]: Unexpected Model Switch Issue

### ISSUE THREAD

**Issue by chalitbkb** [Mintplex-Labs/anything-llm#1726]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I'm confident that I'm using the Gemini1.5 Pro model and that I'm in the same workspace as this model, which can handle large prompts. So why is it like in the picture? It's strange that the model is automatically selected as OpenAI.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/953bff85-1b81-4f44-aaf2-f150c4b562dd)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/86bfb5aa-be12-4dbf-9447-c4c035f24853)

**Comment by timothycarambat** [comment]
> OpenAI failed to embed

Is OpenAI you embedder? In order to do vector search the prompt is embedded and then searched in the vector DB. it appears your prompt is too long for that embedders context window.

This is also known as well

**Comment by chalitbkb** [comment]
> > OpenAI failed to embed
> 
> Is OpenAI you embedder? In order to do vector search the prompt is embedded and then searched in the vector DB. it appears your prompt is too long for that embedders context window.
> 
> This is also known as well

How can we solve this problem, or are there any alternatives that can handle a large prompt? I want to use Gemini.

@timothycarambat

**Comment by timothycarambat** [comment]
@chalitbkb Currently, you can actually just chat with a workspace with no documents. A very large prompt would likely introduce very bad vector search results
