### ISSUE TITLE
[FEAT]: Custom SERP entry

### ISSUE THREAD

**Issue by non-npc** [Mintplex-Labs/anything-llm#1732]
### What would you like to see?

Can we get the option to add our own custom SERP to the list of providers?
We do not want existing SERP's to have/use/sell/track our search data and so have built our own SERP internally.
Our custom SERP can use a VPN to search any site, grab results and format it in the appropriate manner.

**Comment by timothycarambat** [comment]
IMO this is better under a fit as a custom tool/integration

**Comment by timothycarambat** [comment]
Also, moving/linking the conversation to #1327
