### ISSUE TITLE
[BUG]: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Marcus1Pierce** [Mintplex-Labs/anything-llm#1736]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When i select Embedding Preference to ollama, i have this error when try to generate text.

[OllamaEmbedder] Embedding 1 chunks of text with nomic-embed-text:latest.
TypeError: Cannot read properties of undefined (reading '0')
    at Object.similarityResponse (/app/server/utils/vectorDbProviders/chroma/index.js:132:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.performSimilaritySearch (/app/server/utils/vectorDbProviders/chroma/index.js:359:47)
    at async streamChatWithWorkspace (/app/server/utils/chats/stream.js:145:9)
    at async /app/server/endpoints/chat.js:86:9

This is on webui 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/72237814/5fa19edb-44e3-4056-81f0-b1e0ec4e7d2a)

### Are there known steps to reproduce?

- Go to settings > Embedding Preference > Select Ollama provider
- Ask anything on the webui
- Error show
![image](https://github.com/Mintplex-Labs/anything-llm/assets/72237814/88473c43-2c0f-433f-96d8-ce35c57144f1)

**Comment by timothycarambat** [comment]
Did you use the workspace and another embedder first prior to swapping to ollama? Additionally, that error may be result of Ollama embeddings not working

**Comment by timothycarambat** [comment]
What version of Chroma are you using?

**Comment by Marcus1Pierce** [comment]
> What version of Chroma are you using?

I'm using latest tags on chromadb docker so for now it should be 0.5.3

**Comment by timothycarambat** [comment]
This workspace has documents embedded in it, correct?

**Comment by timothycarambat** [comment]
Currently unable to replicate:
- Using OpenAI for LLM
- Default embedder
- Chroma @latest

I create a fresh workspace, embed a document, and send a chat and similarity search returns citations for cited answers as well as answers with no citations

**Comment by timothycarambat** [comment]
The error is coming from Chroma, but it appears the ollama embedder is failing to return a queryVector in this instance.

Are you sending a very large prompt into the workspace or is ollama offline? Because if a null value is passed into chromas search field it will indeed fail

**Comment by Marcus1Pierce** [comment]
> This workspace has documents embedded in it, correct?

Yes of course.



> Currently unable to replicate:
> 
> * Using OpenAI for LLM
> * Default embedder
> * Chroma @latest
> 
> I create a fresh workspace, embed a document, and send a chat and similarity search returns citations for cited answers as well as answers with no citations

For LLM i use Ollama too.

For me when i got error, i'm using combined 
LLM = Ollama
Embedding = Ollama
Vector Database = Chroma

But if i change Embedding to AnythingLLM Embedder or like this
LLM = Ollama
Embedding = AnythingLLM
Vector Database = Chroma

It works perfectly.



> The error is coming from Chroma, but it appears the ollama embedder is failing to return a queryVector in this instance.

At first it looks like that but when i change embedding to AnythingLLM, even when using chroma it works.



> Are you sending a very large prompt into the workspace or is ollama offline? Because if a null value is passed into chromas search field it will indeed fail

Nope, just "test" like in the picture.

**Comment by Marcus1Pierce** [comment]
I don't know what is wrong with my setup or config and i don't even now how i fix the issue, but looks like the error is gone now.

I think it just error in my config not bug.

**Comment by coreyt** [comment]
In case anyone else runs across this in the future: 
I an into this error too. On my side it ended up that ollama was throwing an error because it could not find a device.  In this case, there were new GPU drivers that had been installed, but I had not rebooted yet.  After a reboot, ollama was fine, and the query through anythingllm worked fine as well.

**Comment by timothycarambat** [comment]
@coreyt can i ask what version of ollama you were on?

**Comment by ibetho** [comment]
same issue

**Comment by timothycarambat** [comment]
@ibetho use the correct [docker command](https://docs.anythingllm.com/installation-docker/local-docker) as you are probably missing your ENV file in your storage
