### ISSUE TITLE
Initial test done on Chatbot - Feedbacks

### ISSUE THREAD

**Issue by iokinpardo** [Mintplex-Labs/anything-llm#174]
Hi Timothy, we have been testing the full “**Anything LLM Chatbot**” application as it matches perfectly with our idea, but we have found many adjustments to be solved. Some **issues, UX changes, UI suggestions and feedbacks**. We have collected all of them and instead of creating a single issue per each topic, we have listed all of them below. Please let me know if you have any doubt or questions about any of those topics. Btw, not sure if you prefer having all those issues on Discord channel rather that Github. Just let me know. Many thanks in advance. Amazing work done.

**_Some issues faced:_**

•	I had this issue about not being able to login with created credentials for 3 times. Same for created users. It required me to re-built the system completely. So there seems to be a type of issue with saved credentials.

(![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/2c94642f-9653-465d-9ac0-283427eb5dee)))

**_Important feedback:_**

•	Add MS Azure OpenAI model – Critical for companies
•	Important to be able setting users email addresses too. This should allow Password recovery system for users without being logged in, for multi-user mode
•	SQLite – Possibility to use other SQL databases like MySQL/MariaDB or PostgreSQL 
•	 **System Settings** imh opinion should **should be hidded for None-Admin users**. And the Logout button should be placed on the Top-Left or Bottom-Left section-column rather than inside of that section. It should be more accessible for any user.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/c90743b9-b526-4091-9cd1-7e70800d81da)

**_Suggestions & Feedbacks:_**

-	Possibility to **Import users** of specific Type **massively trough CSV files**.
-	Possibility setting **new User types,** this could allow create **specific Clients groups**, like current ones Admin & Member and new ones l**ike Client1, Client2, Client3**….
-	BTW, in the user list it says “**Default**” instead of “**Member**”.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/92fc0ea4-ca88-4ccb-90ce-c550f8868d24)

•	Once the embedding process is completed, there should be a “f**ile successfully uploaded!**” or similar. Now it just closes the window and we have to “**believe**” that everything has gone fine. 
•	Flexibility for **hiding several UI** elements if desired like:
          o	Below 2 buttons & Social networks icons
          o	Change main branding colors
          o	Possibility for adding client-user Logos to the top bar
![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/8c63f565-8322-4018-bfee-6c947d372f59)

•	**Conversations Report** section **filtering** even possibility to **Download them in CSV** format
•	Add a more intuitive and helpful **“Clear” button** for clearing conversations, with **“/reset” command is not very user-friendly**
•	**Increase the Prompt**, as it is very short and not valid for many use cases. 
•	Embedding process: Maybe there could be a select method (Default & Custom)
o	Default: Current way (btw, can you please explain what method is currently being used?)
o	Custom: Allowing the user to set those params for the embedding to use

	Chunk size

	Overlap

•	The selecting file to be embedded into the Vector DB is **not very user friendly**. It is **hard to understand** that the file is selected when it is displayed as “**red**”. I think that this process requires to be improved for a better User Experience, otherwise there will be many user issues or ticketing with doubts.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/c590d4c7-cdb0-4dee-ac18-c2bf3c87155a)

**_Nice to have:_** 
-	**Conversation history record**, allowing to continue old conversations as  ChatGPT does.
-	Add **Claude 2 model for chatbots conversations**, while keeping OpenAI/Azure OpenAI models for embeddings
-	In case hundreds of users are created, we will need **possibility to filter Users by specific User type** (Member, Client1, Client2,…..)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/64370c50-0081-43a0-824a-898a27618e40)

-	Possibility to **edit or hide this message**. Consider that on **client user hands we should avoid** this type of messages.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/7a76975b-181d-4d13-ac75-bcabedba685d)

**Comment by iokinpardo** [comment]
A couple additional topics identified:

- If the label below showing “**332 indices**” means the current Vector DB total vector count, maybe better label it “**332 vectors**”.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/2c743104-7d0f-4cb8-bd97-77308c64df90)


- While editing workspaces, editing Users, the **popup-window** below does **not close clicking outside**, as the rest.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/c5103530-9927-4a6a-8cde-0197169d22de)


- After setting “**Users can delete workspaces**” as **unchecked**, I still can see the button “Delete workspace” with a “**Member**” user.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/0034b431-c897-4863-92ed-d272c80de88f)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/73a84def-a4be-4645-aa44-314e8b6b10ab)


- Could be possible to set a “**logo**” replacing “**AnythingLLM**” label? Maybe it could be a **default one** and being available setting a **custom one** for **new “User Types”** by the admin? This could allow setting **custom client logos** for each **Type of user**, right?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/6673107/be51262c-ba50-4629-bb27-4d826667a411)

**Comment by jignnsd** [comment]
Hey @iokinpardo did you have a chance to solve the "not being able to login"
I'm experiencing the same issue. Thanks

**Comment by buanzo** [comment]
+1 to supporting Postgresql PGVector (there are other vectorial extensions for pgsql).

**Comment by timothycarambat** [comment]
Marking as stale but also we have addressed pretty much all of these requests that you outlined. Thank you!
