### ISSUE TITLE
Discord LLM bot [FEAT]: 

### ISSUE THREAD

**Issue by Appolonius001** [Mintplex-Labs/anything-llm#1744]
### What would you like to see?

a way for my Discord bot to access the currently running LLM.
i have a private family discord room and would like for them to be able to use the currently running LLM

**Comment by timothycarambat** [comment]
You can accomplish this with the API that is served on all versions of AnythingLLM. In settings you can provision an API Key to interact with your AnythingLLM instance.
https://docs.useanything.com/features/api

**Comment by timothycarambat** [comment]
Closed because its out of scope, especially for this repo, to build all the piecemeal integrations with third party apps currently since most implementations are extremely use-case specific and will not share many requirements
