### ISSUE TITLE
[BUG]:when i try to save and embed file in the workspace, i get error 1 that could not find the specified file

### ISSUE THREAD

**Issue by lodion** [Mintplex-Labs/anything-llm#1747]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![Snipaste_2024-06-23_10-51-16](https://github.com/Mintplex-Labs/anything-llm/assets/76713050/e3ba2948-e05e-4a00-9ff9-2bf839547262)
![Snipaste_2024-06-23_10-51-57](https://github.com/Mintplex-Labs/anything-llm/assets/76713050/f26667a4-f493-4a82-b67d-ce08249f594b)
but in fact i can find the file in my local file system(windows 10)

**Comment by lodion** [comment]
![Snipaste_2024-06-23_10-54-59](https://github.com/Mintplex-Labs/anything-llm/assets/76713050/a92cecf6-391f-4ad3-b9d4-874ff4265c9c)
![Snipaste_2024-06-23_10-55-05](https://github.com/Mintplex-Labs/anything-llm/assets/76713050/3389f34b-a411-449d-b9df-d1bbc871b30a)
This may make it easier to understand my situation

**Comment by timothycarambat** [comment]
To me, this reads as a permissions issues with the application being able to located _and_ execute on your system. This is dependent on how you have your default permissions on your machine, but considering the file appears to clearly exist and is not empty - I would be willing to bet this is execute permissions related.

**Comment by lodion** [comment]
> To me, this reads as a permissions issues with the application being able to located _and_ execute on your system. This is dependent on how you have your default permissions on your machine, but considering the file appears to clearly exist and is not empty - I would be willing to bet this is execute permissions related.

Thank you very much. It was solved when I used administrator rights. I had no idea before.
