### ISSUE TITLE
[FEAT]: Claude 3.5?

### ISSUE THREAD

**Issue by SerenityNrrd** [Mintplex-Labs/anything-llm#1751]
### What would you like to see?

I am able to use Claude 3.5 on other AI chat bots. but for the life of me I can't get it to show up in the list on here? is it an update thing or am I doing something wrong?

**Comment by timothycarambat** [comment]
Anthropic does not have a `/models` endpoint - so we have to add every model manually to the list. That being said, it was already added and that update has just not been released to desktop currently.

https://github.com/Mintplex-Labs/anything-llm/pull/1731
