### ISSUE TITLE
[BUG]: When trying to stop the model the CPU job doesn't go down

### ISSUE THREAD

**Issue by doggi87** [Mintplex-Labs/anything-llm#1760]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When I write something to a model and then trying to stop, it works sometimes and sometimes the CPU is still 100% even after stopping, seems that the process hangs and I need to kill the process.

Can inform that I use docker container.
I use Ryzen 7 5800h 16GB ram

### Are there known steps to reproduce?

Type anything to any model like llama3 or mistral.
Let the model write and then stop in the middle and write again and stop. Sometimes the process doesn't go idle and pushing the CPU 100% even after everything is stopped.

**Comment by timothycarambat** [comment]
There is no detail on what LLM provider you are using here, so hard to help debug. Most LLM providers dont even support a `halt` method so once they start inferencing they cannot stop - all we can do client side is disconnect from the listener and hope the provider can see `CONN_CLOSED` and stop.

Again, most dont support this.

**Comment by doggi87** [comment]
Oh okay, im using ollama api. But if ollama is the problem then they should
fix i hope.

Regards

Den tis 25 juni 2024 22:33Timothy Carambat ***@***.***> skrev:

**Comment by timothycarambat** [comment]
Yeah :/ I agree, believe me I have had this same issue myself and I have found just killing the process and rebooting worked when it was on a runaway inference

**Comment by doggi87** [comment]
But strange part is I tried open webui and there it works when stopping but
the performance of answer from the model is slower than anythingllm.

Den tis 25 juni 2024 22:43Timothy Carambat ***@***.***> skrev:
