### ISSUE TITLE
[FEAT]: Allow default users to upload documents

### ISSUE THREAD

**Issue by Justincjr** [Mintplex-Labs/anything-llm#1763]
### What would you like to see?

is there a way i can allow default users to upload documents?

**Comment by timothycarambat** [comment]
Currently, that is not permitted under the `default` role but will be handled via:
https://github.com/Mintplex-Labs/anything-llm/issues/840
https://github.com/Mintplex-Labs/anything-llm/issues/797
https://github.com/Mintplex-Labs/anything-llm/issues/727
https://github.com/Mintplex-Labs/anything-llm/issues/587

**Comment by sabmaz** [comment]
Dear Tim, 

Allowing default users to upload documents is a very important future in our production environment!

Any time plan when this feature will be impleted and ready to use?

Kind regards
Bysystem
