### ISSUE TITLE
[FEAT]: Embedding Download

### ISSUE THREAD

**Issue by Bai1026** [Mintplex-Labs/anything-llm#1768]
### What would you like to see?

Dear anything-llm team,

Is there any chance we could download the embedded vector DB to our own device?
Since I do not find any download button from the workspace. Appreciate!

Best regards,
Vincent Pai

**Comment by timothycarambat** [comment]
The built-in vector db is just [LanceDB!](https://github.com/lancedb/lancedb). If you need the data you can open the storage folder on your device and it is all stored there. Nothing is stored on a cloud service unless you opt-in to use a cloud based vector db!

The storage folder locations vary based on operating system but in general:
Windows: `C:\Users\user\AppData\Roaming\anythingllm-desktop\storage\lancedb`
Mac: `/Library/Application Support/anythingllm-desktop/storage/lancedb`

**Comment by Bai1026** [comment]
Thx for the reply!!! U guys definitely build a useful tool!
