### ISSUE TITLE
[BUG]: Confluence crawler incorrectly does not accept subdomains

### ISSUE THREAD

**Issue by Matti-Koopa** [Mintplex-Labs/anything-llm#1772]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Subdomains seem to be only supported for normal TLDs.
Something like `https://confluence.myorg.at/display/SPACE/*` works.
Something like `https://confluence.myorg.gv.at/display/SPACE/*` doesn't work.
Apparently it uses regular expression to check if an URL is valid, but it's hardcoded to only check for a single or no subdomain at all.

### Are there known steps to reproduce?

Click Data Connectors, click Confluence, enter the URL, click Submit, get error

**Comment by JayCroghan** [comment]
I'm assuming this is also why it doesn't work when there is a port in the URL??

Mine is http://DOMAIN.net:8090/display/PRJ and it tells me it's not in the correct format.

**Comment by derkoe** [comment]
And you can also run confluence under a context path - which also does not work. For example:

```
https://my.domain.com/confluence/display/myspace/*
```
