### ISSUE TITLE
[UI/UX]: Slow loading times after adding large documents

### ISSUE THREAD

**Issue by JamesClarke7283** [Mintplex-Labs/anything-llm#1776]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I find that after adding some large documents, through the github scraper or website downloader, i can't add new documents easily, it slows down to a hault, making the interface unusable unless you get rid of the documents.

### Are there known steps to reproduce?

1. Download 2 or more large documents through Github scraper and/or website scraper.
2. Try and load the document importer interface.

**Comment by timothycarambat** [comment]
related https://github.com/Mintplex-Labs/anything-llm/issues/928

**Comment by gowreesh369** [comment]
@timothycarambat Is this issue open? Can i take it?

**Comment by timothycarambat** [comment]
Moved to #2317
