### ISSUE TITLE
[BUG]: Bing API web search not working

### ISSUE THREAD

**Issue by Justincjr** [Mintplex-Labs/anything-llm#1780]
### How are you running AnythingLLM?

Docker (local)

### What happened?

provided bing api key for the web search, but "I’m sorry, but as a text-based AI, I don’t have the capability to search the internet or browse specific websites."

**Comment by timothycarambat** [comment]
https://docs.useanything.com/agent-not-using-tools

**Comment by scyto** [comment]
What is not planned?  The bing search won't be fixed?

The reason it seems to not work is it is not possible to save the bing API key in the agent configuration, every time i come back to this page it has reset.  

I verified my key works with `curl -H "Ocp-Apim-Subscription-Key: <yourkeygoeshere>" https://api.bing.microsoft.com/v7.0/search?q=microsoft+devices` on another machine

<img width="1565" alt="image" src="https://github.com/user-attachments/assets/63802d6b-07c0-4f3d-b761-49004b5e942c">
