### ISSUE TITLE
[BUG]: Copy buttons have no effect

### ISSUE THREAD

**Issue by 2hy6v** [Mintplex-Labs/anything-llm#1781]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

In a normal chat setting there are two copy buttons one for the chat message itself and extra buttons for the code areas.
In both cases clicking the copy button leads to no effect.
Clicking the copy button for the chat message next to edit and refresh has no effect whatsoever also no console output.
Clicking the copy button for the code area leads to an error in the browsers console:
Firefox v127.0.2
"Uncaught TypeError: window.navigator.clipboard is undefined"
Chrome v126.0.6478.127
"Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')

**Comment by timothycarambat** [comment]
HTTP & browser permissions for non-SSL/TLS connections
See: https://github.com/Mintplex-Labs/anything-llm/issues/1631#issuecomment-2155170550
