### ISSUE TITLE
[FEAT]: Modify default user role to allow doc upload 

### ISSUE THREAD

**Issue by arbi-dev** [Mintplex-Labs/anything-llm#1782]
### What would you like to see?

The different user permission levels are great, but since the key functionality is to be able to upload documents, default users should have the ability to upload documents, at least to a single personal workspace.  Most users will not need  manager-level permissions to change LLMs, add other users etc.

**Comment by timothycarambat** [comment]
Moving to https://github.com/Mintplex-Labs/anything-llm/issues/1787

**Comment by spyroskotsakis** [comment]
@timothycarambat It would be beneficial if the default user could upload documents to the workspace that they cannot change or modify, but can use with their own data.
Thanks a lot!

**Comment by felix-laarmann-hyve** [comment]
@timothycarambat this would be a huge value to organisations! Currently we need to manually adjust the role permissions to enable users to upload documents to workspaces, but this way all files are visible to everyone. It would be a lot smoother, if users could upload files to individual threads.
