### ISSUE TITLE
[FEAT]: allow users to have different levels of permissions for different workspaces

### ISSUE THREAD

**Issue by arbi-dev** [Mintplex-Labs/anything-llm#1783]
### What would you like to see?

In practice, users may need manager rights to some workspaces, but only view access to others.  Ideally it would be possible for the user to have different levels of permissions to different workspaces.  In other words, RBAC should be more fine-grained at workspace level, not just at instance level.

**Comment by timothycarambat** [comment]
> RBAC should be more fine-grained at workspace level, not just at instance level.

Agreed, we will be tracking that in https://github.com/Mintplex-Labs/anything-llm/issues/1787 !

Moving conversation there
