### ISSUE TITLE
[BUG]: Ollama call failed with status code 500: llama runner process has terminated: exit status 0xc0000135 | Windows

### ISSUE THREAD

**Issue by njss** [Mintplex-Labs/anything-llm#1795]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When trying to ask a question, I get the following error message (using any models): 
Ollama call failed with status code 500: llama runner process has terminated: exit status 0xc0000135

### Are there known steps to reproduce?

Configure the sw
upload a pdf document
ask a question

**Comment by RockinRoddieAi** [comment]
I am facing the exact same issue.

I have tried to uninstall the model(s) and reinstall them and no go.  This error renders Anything LLM useless and unusable. :(

**Comment by droza888** [comment]
Same problem here with 1.5.8. Totally fresh install.

**Comment by timothycarambat** [comment]
This error is obviously tied back to ollama, I have a feeling it is device related. Please run the app in debug mode and on boot and when sending a chat there should be logs that describe the whole ollama runtime

https://docs.useanything.com/debug#anythingllm-debug-mode-on-windows

I will need those to help. I would prefer to not go back to the previous Ollama version as it is slower and the newer version has improved greatly.

Other details:
- Do you have GPU?
- CUDA installed? If so, which version
- CPU specs (does it support AVX?)

**Comment by timothycarambat** [comment]
> This error renders Anything LLM useless and unusable.

You can just use literally any other provider to get around this. Does downloading Ollama directly from them and just connecting with AnythingLLM still yield the same issue?

**Comment by RockinRoddieAi** [comment]
Yah downloading directly did not seem to resolve the issue with 1.5.8.  And yes I understand i can use other providers, i was trying to keep my deployment straight forward.

**Comment by RockinRoddieAi** [comment]
Hi

 

I followed the debugging mode instructions.  Log file details are below.

 

I have this issue on two issues:

 

Workstation specs:

GPU = Yes

NVIDIA GeForce RTX 3090

CPU = 12th Gen Intel Core i9-1290 3.19 GHz and yes it supports AVX

 

Laptop specs:

GPU = Yes

NVIDIA GeForce RTX 3050

CPU = 12th Gen Intel Core i-12700H 2.30 GHz and yes it supports AVX

 

---

C:\Users\r0ss\AppData\Local\Programs\anythingllm-desktop>

[Preferences] preference config stored at C:\Users\r0ss\AppData\Roaming\anythingllm-desktop\config.json

Prisma schema loaded from prisma\schema.prisma

Datasource "db": SQLite database "anythingllm.db" at "file:C:/Users/r0ss/AppData/Roaming/anythingllm-desktop/storage/anythingllm.db"

 

Already in sync, no schema change or pending migration was found.

 

Γ£ö Generated Prisma Client (v5.3.1) to .***@***.***\client in 342ms

 

 

Prisma schema loaded from prisma\schema.prisma

 

Γ£ö Generated Prisma Client (v5.3.1) to .***@***.***\client in 309ms

 

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)

```

import { PrismaClient } from ***@***.***/client'

const prisma = new PrismaClient()

```

or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)

```

import { PrismaClient } from ***@***.***/client/edge'

const prisma = new PrismaClient()

```

 

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

 

[OllamaProcessManager] Ollama will bind on port 11434 when booted.

[Preferences] Will load window with last know bounds.

Collector hot directory and tmp storage wiped!

[production] AnythingLLM Standalone Document processor listening on port 8888

[TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.

prisma:info Starting a sqlite pool with 33 connections.

[TELEMETRY SENT] {

  event: 'server_boot',

  distinctId: 'd0bfea5d-0865-477d-bd01-2fd3a4f18feb',

  properties: { runtime: 'desktop' }

}

Hot loading of AnythingLLMOllama - LLM_PROVIDER is anythingllm_ollama.

[NativeEmbedder] Initialized

[CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.

[EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.

[production] AnythingLLM Standalone Backend listening on port 3001

[BackgroundWorkerService] Feature is not enabled and will not be started.

[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.

[OllamaProcessManager] [windows] Ollama subprocess running. Port 11434. PID 39160.

OllamaAPI offline - retrying. 1/3

[NativeEmbedder] Initialized

Error: Ollama call failed with status code 500: llama runner process has terminated: exit status 0xc0000135

    at createOllamaStream ***@***.***\community\dist\utils\ollama.cjs:26:21)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async createOllamaChatStream ***@***.***\community\dist\utils\ollama.cjs:61:5)

    at async ChatOllama._streamResponseChunks ***@***.***\community\dist\chat_models\ollama.cjs:399:30)

    at async ChatOllama._streamIterator ***@***.******@***.***\core\dist\language_models\chat_models.cjs:82:34)

    at async ChatOllama.transform ***@***.******@***.***\core\dist\runnables\base.cjs:384:9)

    at async wrapInputForTracing ***@***.***\core\dist\runnables\base.cjs:258:30)

    at async pipeGeneratorWithSetup ***@***.***\core\dist\utils\stream.cjs:230:19)

    at async StringOutputParser._transformStreamWithConfig ***@***.***\core\dist\runnables\base.cjs:279:26)

    at async StringOutputParser.transform ***@***.***\core\dist\output_parsers\transform.cjs:36:9) {

  response: Response {

    [Symbol(realm)]: null,

    [Symbol(state)]: {

      aborted: false,

      rangeRequested: false,

      timingAllowPassed: true,

      requestIncludesCredentials: true,

      type: 'default',

      status: 500,

      timingInfo: [Object],

      cacheState: '',

      statusText: 'Internal Server Error',

      headersList: [HeadersList],

      urlList: [Array],

      body: [Object]

    },

    [Symbol(headers)]: HeadersList {

      cookies: null,

      [Symbol(headers map)]: [Map],

      [Symbol(headers map sorted)]: null

    }

  }

}

**Comment by timothycarambat** [comment]
We identified the root cause of this issue:
- On windows systems which have a discoverable CUDA capable device GPU
- Do _not_ have Ollama already installed on the client system
- Attempt to run the built in Ollama client
-> Client fails as ollama does not failover on CUDA library missing to CPU and aborts the process.

The fix was to include missing binaries for CUDA support. Currently, these will be pre-bundled with AnythingLLM windows, future updates may move them to a post-install process.

As such, downloading the latest version of[ AnythingLLM 1.5.8 ](https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop.exe)as of July 1, 2024 ~11:20AM PST will download this patched version.

Installation may take longer than expected since we are going to unpack the supporting libraries now, but it will result in a working and GPU-enabled built-in Ollama experience.

**Comment by RockinRoddieAi** [comment]
Thanks, that did the trick.

 

Super impressed with this support thread.

 

Keep up all the great work. I am thoroughly enjoying this app.

**Comment by drgamedev** [comment]
I am having the same issue. I've set up AnythingLLM. Then restarted. The same error is occurring again. Could someone please provide the precise steps to resolve it? Thanks.
