### ISSUE TITLE
[FEAT]: Chat with Github Repo

### ISSUE THREAD

**Issue by Jiayou-Chao** [Mintplex-Labs/anything-llm#1797]
### What would you like to see?

Integrate the chatbot with a git repository that allows users to interact with the repo via natural language. This could be useful for fetching documentation, or getting help with certain commands.

**Comment by timothycarambat** [comment]
<img width="1485" alt="Screenshot 2024-07-01 at 11 54 43 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/5faa1b69-49e3-4d0d-822f-bb97e050efd5">

this is already in the app

**Comment by Jiayou-Chao** [comment]
I'm so sorry. I didn't notice this yesterday.
