### ISSUE TITLE
unable to run collector; not able to install whaaaat (mac os 12.2.1)

### ISSUE THREAD

**Issue by altafr** [Mintplex-Labs/anything-llm#18]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f2/k2pm6hv14vdb975wm5msdk540000gn/T/pip-install-8mictb59/whaaaaat_da2d91bcef8244be854586bbc3776280/setup.py", line 10, in <module>
          long_description = pypandoc.convert('README.md', format='md', to='rst')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by Tuminha** [comment]
I have the same issue, and I could not solve it even trying to change the venv several times. The package causing it is pypandoc and I also have it installed.

**Comment by timothycarambat** [comment]
Just going to remove whaaaat - seems to just give everyone issues and has a bunch of random deps. Will just make it a number input command instead of interactive.

**Comment by allthecodeDev** [comment]
same on windows 11

**Comment by abelmoricz-evo** [comment]
I had the same issue and after running `cp .env.example .env` as it says in the README.md after installing pip requirements it was fixed.

**Comment by hipnologo** [comment]
I fixed it by changing the version of the pypandoc package. Pushed a branch. `gh pr checkout 23`. Alternatively, the whaaaat could try `long_description = pypandoc.convert_file('README.md', 'rst')` instead. Hope it helps!

**Comment by timothycarambat** [comment]
resolved by #23
