### ISSUE TITLE
[BUG]: Linux Desktop App - Ollama local - Could not respond to message error regardless of LLM Preferences successful setup

### ISSUE THREAD

**Issue by liberateyourtech** [Mintplex-Labs/anything-llm#1802]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Loving this app, thank you for the great work! But so far not been able to get the Linux client to work

Installed via latest script without errors and lunched from the command line, configured Ollama local with URL, model and token successfully, created workspace ok, send "hello" immediately get error:

_Could not respond to message.
An error occurred while streaming response. network error_

Unable to access settings again after above error, app hangs

My setup:
Running Ollama locally on Ubuntu 22 with ./ollama serve, flags for LAN access enabled, browser confirms **ollama is running** on

http://127.0.0.1:11434/
and
http://192.168.100.144:11434/ (IP of same machine on network)

I am able to connect and chat via windows Anything LLM desktop app over LAN

**Console output from Anything LLM:**

libre@AI-ASR:/$ ./home/libre/AnythingLLMDesktop/start
[Preferences] preference config stored at /home/libre/.config/anythingllm-desktop/config.json
[44716:0702/163258.555428:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/libre/.config/anythingllm-desktop/storage/anythingllm.db"

Already in sync, no schema change or pending migration was found.

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 347ms

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 334ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

[OllamaProcessManager] Ollama will bind on port 38677 when booted.
[Preferences] Will load window with last know bounds.
[44750:0702/163306.278799:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[44750:0702/163319.458568:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[44750:0702/163327.965429:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

**Console output from running Ollama:**

llama_new_context_with_model: graph splits = 1
INFO [main] model loaded | tid="130192473569152" timestamp=1719925470
time=2024-07-02T14:04:31.064+01:00 level=INFO source=server.go:572 msg="llama runner started in 1.26 seconds"
[GIN] 2024/07/02 - 14:04:31 | 200 |  4.286584256s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/07/02 - 14:08:21 | 200 |         2m25s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/07/02 - 14:09:54 | 200 |    1.148565ms | 192.168.100.165 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:12:25 | 200 |    1.168343ms | 192.168.100.165 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:13:15 | 200 |    1.195207ms | 192.168.100.165 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:18:01 | 200 |    1.441114ms | 192.168.100.165 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:18:30 | 200 |    1.703561ms | 192.168.100.165 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:21:43 | 200 |    1.503829ms | 192.168.100.165 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:34:29 | 200 |    1.199092ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/07/02 - 14:34:29 | 200 |    1.121646ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/07/02 - 15:32:21 | 200 |    1.112652ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/07/02 - 15:33:37 | 200 |      99.496µs | 192.168.100.144 | GET      "/"
[GIN] 2024/07/02 - 15:33:48 | 200 |     500.678µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/07/02 - 15:33:59 | 200 |     1.45739ms | 192.168.100.144 | GET      "/api/tags"
[GIN] 2024/07/02 - 16:17:02 | 200 |     1.41016ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/07/02 - 16:18:08 | 200 |     1.10151ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/07/02 - 16:33:09 | 200 |    1.062379ms |       127.0.0.1 | GET      "/api/tags"

It looks like Ollama is getting GET api/tags

Is the Desktop app correct? [OllamaProcessManager] Ollama will bind on port 38677 when booted.

I have tried

Quit and relaunch the app
Quit and relaunch, reset LLM Preferences succesfully
Deleting the folder in .config and setup again

I tried installing the same Linux Desktop app on another machine on the network, same errors

Thank you!

**Comment by timothycarambat** [comment]
So the built-in Ollama (AnythingLLM LLM) should not run on linux and that may be the root cause. Are you using the AnythingLLM LLM or Ollama as the LLM Provider?

Ollama is supposed to connect to a localhost ollama that you are running elsewhere, which sounds to be the case. The log 
> [OllamaProcessManager] Ollama will bind on port 38677 when booted.

though indicates that it did try to boot the _internal_ Ollama running - which would fail

**Comment by liberateyourtech** [comment]
I am using the Ollama LLM, not AnythingLLM LLM (screenshot below)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/68810015/c9ca49c9-d4d1-4f39-89e6-c2fb343eb759)

Normally I would see POST messages in the Ollama console when succesfully chatting with Ollama, as below

![image](https://github.com/Mintplex-Labs/anything-llm/assets/68810015/6ad12d51-bb5d-4a08-a1e4-aacb0d02f165)

Thank you!

**Comment by timothycarambat** [comment]
And after sending a chat, what does the logs show in AnythingLLM and does a POST /api/chat in Ollama as well

**Comment by Falcon-16** [comment]
This is still an Issue @timothycarambat 
I am experiencing the same issue; exactly the same.
On the AnythingLLM log corner, it does try to spin up something:

<img width="884" height="318" alt="Image" src="https://github.com/user-attachments/assets/346db5bb-001b-4ac0-9c62-60fd4b08b846" />

I also note that it does not start up the selected model in Ollama, when running Ollama ps.
One thing that shows up and is interesting is this brain icon; it is not present on your docs. It brings up this different model selector. 

<img width="1445" height="875" alt="Image" src="https://github.com/user-attachments/assets/98d62f8d-81d9-4b78-879d-3fce5623d08c" />
When I click Ollama, a button called "Use this model" turns up, and clicking on it causes an error called "Invalid model selection" to come up, and then *crash*.

<img width="1453" height="875" alt="Image" src="https://github.com/user-attachments/assets/6ee00f43-ecb6-4d61-9e0e-c570993078e4" />

**Comment by Falcon-16** [comment]
Even running a locally pre-downloaded model causes the "streaming response network" error to come up.
Even if all network-related functions are turned off.
