### ISSUE TITLE
[BUG]: I have got this error when I ask for an answer to AnythingLLM v.1.5.8 "An error occurred while streaming response. network error"

### ISSUE THREAD

**Issue by Marco20-ux** [Mintplex-Labs/anything-llm#1810]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I have got this error when I ask for an answer to AnythingLLM v.1.5.8 "An error occurred while streaming response. network error"

### Are there known steps to reproduce?

I have got this error when I ask for an answer to AnythingLLM v.1.5.8 "An error occurred while streaming response. network error"

**Comment by timothycarambat** [comment]
There is not enough information in this to help you.
- What OS/runtime (tag shows Docker, but 1.5.8 is desktop?)
- What LLM provider
- What embedder
- Can you send chats on an empty workspace at all?

Get appropriate logging from:
https://docs.useanything.com/debug

Closing until more information and/or bug is reproduced
