### ISSUE TITLE
Change Local LLM Download Location [FEAT]: 

### ISSUE THREAD

**Issue by Waldin-Botha** [Mintplex-Labs/anything-llm#1813]
### Change Download Location when?

Currently whenever I want to download a LLM using AnythingLLM to run a model locally it downloads the model to my C drive and then fails because my C drive is full and there is no option to make its download location somewhere else. I thought it would download into its own install directory but this is not the case it seems.

**Comment by timothycarambat** [comment]
It downloads to `C:\Users\usr\AppData\Roaming\anythingllm-desktop` since that is really the only persistent and writable location for the app. You can however use `mklink` in powershell to write all data for AnythingLLM to a different directory. 

Copy `C:\Users\usr\AppData\Roaming\anythingllm-desktop` to the new destination and 
```
cd C:\Users\usr\AppData\Roaming\anythingllm-desktop
mklink /d anythingllm-desktop d:\folder\anythingllm-desktop
```

Not something we explicitly support, but from my understanding it can be done like that. We dont plan to allow people to overwrite where appdata is stored

**Comment by ChefAndy** [comment]
> We dont plan to allow people to overwrite where appdata is stored

Oh well. Separating potentially hundreds of gigabytes of resource storage from your *operating system disk* is a pretty standard requirement for people that do anything with a large amount of data. Considering that it's a pretty smooth experience overall as a product, I find that stance confusing. I'd totally pay for a pro version of the local desktop app-- I have a 4090 so I don't have to use cloud services for things like that.

**Comment by justin-vanwinkle** [comment]
+1 - I would like the ability to set where my LLM should be saved or even just the ability to select an existing LLM that i keep on a data drive.

**Comment by ZeroCool22** [comment]
> It downloads to `C:\Users\usr\AppData\Roaming\anythingllm-desktop` since that is really the only persistent and writable location for the app. You can however use `mklink` in powershell to write all data for AnythingLLM to a different directory.
> 
> Copy `C:\Users\usr\AppData\Roaming\anythingllm-desktop` to the new destination and
> 
> ```
> cd C:\Users\usr\AppData\Roaming\anythingllm-desktop
> mklink /d anythingllm-desktop d:\folder\anythingllm-desktop
> ```
> 
> Not something we explicitly support, but from my understanding it can be done like that. We dont plan to allow people to overwrite where appdata is stored

Why all the "anythingllm-desktop" folder, wouldn't be enough just the **models** folder?

![Image](https://github.com/user-attachments/assets/4deca6e7-da6f-4ccb-8148-3edc52a93c3b)

**Comment by iopenet** [comment]
This is the main reason people moved Anything-llm to the trash-bin !
Many other apps allow you to place models in another driver/location.

**Comment by timothycarambat** [comment]
This issue was moved to https://github.com/Mintplex-Labs/anything-llm/issues/2435 (which is open)
and almost certainly this stand-alone reason is _not why_ people delete the app - it is just yours.
