### ISSUE TITLE
Moving an uploaded file to workspace, save and embedd

### ISSUE THREAD

**Issue by basementmedia2** [Mintplex-Labs/anything-llm#1814]
Hi,

first of all: Thank you for your great work! Really great API!
I had success in uploading a file to the custom-documents folder via API.

But how can i move it to workspace....

![grafik](https://github.com/Mintplex-Labs/anything-llm/assets/23479553/f2926cb1-8f20-40a4-b00d-2739dc48895b)

and then save and embedd...

![grafik](https://github.com/Mintplex-Labs/anything-llm/assets/23479553/e4a1d2fc-ac52-47ff-90f2-ef32f14e3c53)

I tried the following (console says "success" but the file is not in the workspace):

```
async function moveToWorkspace() {
        try {
            const documentUrl = "custom-documents/Test.txt"; 
            const scrapeResponse = await fetch('http://localhost:3001/api/v1/workspace/slki/update-embeddings', {
                method: 'POST',
                headers: {
                    'accept': 'application/json',
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer [mytoken]'
                },
                body: JSON.stringify({ adds: [documentUrl] })
            });

            if (!scrapeResponse.ok) {
                console.error('Error:', scrapeResponse.statusText);
                const scrapeError = await scrapeResponse.json();
                console.error('Details:', scrapeError);
                return;
            }

            const scrapeResult = await scrapeResponse.json();
            console.log('Success:', scrapeResult);

        } catch (error) {
            console.error('Error:', error);
        }
    }
```

Would be nice if you can help me out :-)

Best wishes
Daniel

**Comment by pyphp** [comment]
<img width="934" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/26706686/45a22946-8429-4eff-8d5b-98c03ec730ef">
I encountered an error while embedding

**Comment by basementmedia2** [comment]
@pyphp  What is the correct way to move documents to workspace and save/embed via API? Is my example code correct? I don't know what is the meaning of your answer.

**Comment by LareinaSayHello** [comment]
Why the answer is not based on document?
![image](https://github.com/Mintplex-Labs/anything-llm/assets/68209500/20262297-2b76-4dd3-9fd5-043d031e40c9)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/68209500/d530c719-f486-4ab0-a6b5-a31a0e22729b)

**Comment by timothycarambat** [comment]
The correct value for the add is not the "name" of the document - but AnythingLLM's name for the document, which is always a JSON file in the folder it is present in with a UUID attached to it.
`custom-documents/my-pdf-<uuid>.json`

you can get this value from `/v1/workspace/{slug}` endpoint

**Comment by ezequias** [comment]
I think you should use the response[location'] from uploadText resource. The location is used in moveFiles. It brings the title + the id to be used.

I think that way you could succeed.

Good look.

**Comment by ezequias** [comment]
> The correct value for the add is not the "name" of the document - but AnythingLLM's name for the document, which is always a JSON file in the folder it is present in with a UUID attached to it. `custom-documents/my-pdf-<uuid>.json`
> 
> you can get this value from `/v1/workspace/{slug}` endpoint where you can see all available documents you can move

It works properly. Thank you for the information.

**Comment by basementmedia2** [comment]
Hi,

althought i have a file in my custom-documents folder  (please see screenshot) the documents array returned by the function is empty:

![grafik](https://github.com/user-attachments/assets/c8d4a263-897a-4e05-9b3e-0bdd114f9eaf)

My current function:

async function moveToWorkspace() {
        try {
            const docResponse = await fetch('http://localhost:3001/api/v1/workspace/slki/', {
                method: 'GET',
                headers: {
                    'accept': 'application/json',
                    'Authorization': 'Bearer MY_API__KEY'
                }
            });

            if (!docResponse.ok) {
                console.error('Upload failed:', docResponse.statusText);
                return;
            }


            const doctoMove = await docResponse.json();
            console.log('Files that can be moved:', doctoMove);

            const documents = doctoMove.workspace.documents;

            for (const doc of documents) {
                // Move uploaded document to workspace
                const documentUrl = doc.docpath;
                console.log("File that can be moved:" + documentUrl);
            }
        } catch (error) {
            console.error('Error:', error);
        }
    }
