### ISSUE TITLE
[BUG]: In Windows 11, the Desktop branch cannot be run，need help

### ISSUE THREAD

**Issue by RobinGitHub** [Mintplex-Labs/anything-llm#1815]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

when run **yarn start** in frontend,then show error
![image](https://github.com/Mintplex-Labs/anything-llm/assets/3375920/15b359e8-1ebd-4b73-9384-85b68a07ab38)

then i run ** yarn add --dev electron ** && **yarn start**，then show error
![image](https://github.com/Mintplex-Labs/anything-llm/assets/3375920/96a529ac-bbca-4de5-bc2c-0316b0ce6943)

then i change 
~~~
import strDistance from "js-levenshtein"; => import * as strDistance from "js-levenshtein";

~~~

then refresh page, show error

![image](https://github.com/Mintplex-Labs/anything-llm/assets/3375920/d9650fe6-0640-4876-8a9d-1c4d810ce1c8)

please tell me why, appreciate it;

**Comment by LareinaSayHello** [comment]
check here [https://github.com/Mintplex-Labs/anything-llm/blob/master/BARE_METAL.md](url)

**Comment by RobinGitHub** [comment]
ok, thanks
