### ISSUE TITLE
[BUG]: addDocumentToNamespace LanceDBError : Operation not supported (os error 95)

### ISSUE THREAD

**Issue by aprt06** [Mintplex-Labs/anything-llm#1825]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I use k8s on this app .mount the path /app/server/storage/ to azure file share. the lancedb is selected as DB . the chat is ok and the upload is work fine but this error  happens when I move file to work space 
`[backend] info: Chunks created from document:
[backend] info: Inserting vectorized chunks into LanceDB collection.
[backend] error: addDocumentToNamespace
[backend] error: Failed to vectorize`
addDocumentToNamespace LanceDBError: LanceError(IO): Generic LocalFileSystem error: Unable to copy file from /app/server/storage/lancedb/hello-world2.lance/_versions/.tmp_1.manifest_6fd3dc1e-e164-4235-ba8d-0045de339d5f to /app/server/storage/lancedb/hello-world2.lance/_versions/1.manifest: Operation not supported (os error 95), /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/convert/mod.rs:757:9

### Are there known steps to reproduce?

Hi everyone , for my case . I use k8s on this app and my path mount is /app/server/storage   the lancedb was selected and the upload was work fine but This happens when I move file to work space

`addDocumentToNamespace LanceDBError: LanceError(IO): Generic LocalFileSystem error: Unable to copy file from /app/server/storage/lancedb/hello-world2.lance/_versions/.tmp_1.manifest_6fd3dc1e-e164-4235-ba8d-0045de339d5f to /app/server/storage/lancedb/hello-world2.lance/_versions/1.manifest: Operation not supported (os error 95), /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/convert/mod.rs:757:9`

![Screenshot 2024-07-05 163511](https://github.com/Mintplex-Labs/anything-llm/assets/10378077/de42a774-8145-4b48-9582-3b4cd0dadc40)

**Comment by timothycarambat** [comment]
This is because for whatever reason the application and/or docker user does not have write permissions on the `/app` folder - or more likely where the `/app` folder for the docker container is bound to. In most cases it should be some `$HOME` directory for the host - something easily writable

**Comment by ericthomas1** [comment]
@aprt06 , @timothycarambat , @ccr-fan-3000,

**Is this a factor?**: https://lancedb.github.io/lancedb/guides/storage/#azure-blob-storage
- How can we configure the default LanceDB instance to write to Azure Blob Storage?

**Comment by ericthomas1** [comment]
I think we are going to try this unless @timothycarambat doesn't think it will work: 

1. Create Blob Container. Within the Blob Container, create a LanceDB database.
2. Set theses Azure Web App Environment Variables:
    - AZURE_STORAGE_ACCOUNT_NAME
    - AZURE_STORAGE_ACCOUNT_KEY
    - AZURE_CONTAINER_NAME (set to container name from above)
    - AZURE_DATABASE_NAME (set to db name from above)
    - VECTOR_DB (set this to lancedb)
3. Make changes to `server/utils/vectorDbProviders/lance/index.js`
```
const lancedb = require("@lancedb/lancedb");  
  
/** * LancedDB Client connection object * @typedef {import('@lancedb/lancedb').Connection} LanceClient */  
const LanceDb = {  
  // Update URI to point to Azure Blob Storage  
  uri: `az://${process.env.AZURE_CONTAINER_NAME || 'my-container'}/${process.env.AZURE_DATABASE_NAME || 'my-database'}`,  
  name: "LanceDb",  
  
  /** @returns {Promise<{client: LanceClient}>} */  
  connect: async function () {  
    if (process.env.VECTOR_DB !== "lancedb") throw new Error("LanceDB::Invalid ENV settings");  
  
    // Add Azure Blob Storage credentials to storage options  
    const storageOptions = {  
      accountName: process.env.AZURE_STORAGE_ACCOUNT_NAME,  
      accountKey: process.env.AZURE_STORAGE_ACCOUNT_KEY  
    };  
  
    const client = await lancedb.connect(this.uri, { storageOptions });  
    return { client };  
  },  
  
  // ... rest of your methods  
};  
  
module.exports.LanceDb = LanceDb;  
```

Thoughts on this one?

**Comment by ericthomas1** [comment]
Bingo! This works.
