### ISSUE TITLE
[BUG]: embedding error，but i dont know why

### ISSUE THREAD

**Issue by o85757o** [Mintplex-Labs/anything-llm#1834]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Error: 1 documents failed to add.
Could not embed document chunks! This document will not be recorded.

Failed to add batches to table list: lance error: LanceError(Arrow): Invalid argument error: Values length 768 is less than the length (3584) multiplied by the value size (3584) for FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 3584), C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lance-datafusion-0.12.1\src\utils.rs:41:28

Failed to add batches to table zhai: lance error: LanceError(Arrow): Invalid argument error: Values length 2570496 is less than the length (3584) multiplied by the value size (3584) for FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 3584)

**Comment by o85757o** [comment]
i just reinstall

**Comment by saulwang83** [comment]
![v](https://github.com/user-attachments/assets/3c33859b-db1b-4cdf-b54d-849ff748a542)
the same bug

**Comment by guhao17** [comment]
the same bug，how to do

**Comment by timothycarambat** [comment]
This error occurs when you have changed your embedders and are attempting to use a previously embed file that was using a different embedder. At least this is the only way i have ever been able to replicate the bug, you should not change your embedders when you have content already embed because the dimensionality mismatch causes this.

If this is not the case let me know how you got to this stage and also what embedder you are using

**Comment by guhao17** [comment]
![image](https://github.com/user-attachments/assets/ca3282bd-4b27-4ff2-9d4e-be58016c457f)
![image](https://github.com/user-attachments/assets/4dd6e759-6d9f-42e2-bd93-5ddcf380fdd3)
![image](https://github.com/user-attachments/assets/d1171320-2f1e-4c3b-b468-be1d6e67384a)
When updating my embedders, I created a new workspace and deleted the original workspace along with its data. Initially, I was using the 'anythingllm' embedder, but later I switched to the 'ollama' embedder. What should I do now?

**Comment by timothycarambat** [comment]
To be double sure all dimensionality aligns you can do the following:
1. Delete workspaces _or_ just reset the vector database in each workspace
2. Ensure any `cached` documents are fully deleted from the system
3. Reupload and embed into fresh/reset workspace - should have no issues

**Comment by guhao17** [comment]
Where can I find the address of the cached document

**Comment by timothycarambat** [comment]
You would just select the document in the UI and then click the "trash" icon - the cached filenames are hashed so you would not know which belongs to which file
