### ISSUE TITLE
[BUG]: A timeout occurred on api.together.xyz

### ISSUE THREAD

**Issue by Gopichandar** [Mintplex-Labs/anything-llm#1839]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

On running the image and try to use the workspace thread, it was timed out.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/13073344/b4618352-e8d0-4a95-be0e-ae35f6e91ef8)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/13073344/189e2705-0f32-4567-895e-c071459aea7f)

**Comment by timothycarambat** [comment]
This is not a bug with AnythingLLM. TogetherAI's API was/is down so chats were failing. If you continue to get the Cloudflare downtime page then it is your specific connection to TogetherAI (probably VPN related?)

**Comment by Gopichandar** [comment]
Hi @timothycarambat , thanks for the clarification, I have verified that together api seems to wokring fine,  Is there anyway to verify that via anything llm?

**Comment by timothycarambat** [comment]
We dont pre-verify a connection to any specific providers - so sending a chat would be the only way at this time to ensure the same API call reaches TogetherAI

**Comment by timothycarambat** [comment]
I did just use my own key with Together AI and was able to successfully send a chat and get a streamed response back

**Comment by Gopichandar** [comment]
Okay.  Looks like issue on together ai api on some specific models.  Im having issue running the `zero-one-ai/Yi-34B-Chat` where as 'Lllama-3' seeems to be working fine.  Anyway thanks for the help.
