### ISSUE TITLE
[BUG]: Contact Support link (mailto: supportemail) does not bring up email client

### ISSUE THREAD

**Issue by daleferrario** [Mintplex-Labs/anything-llm#1845]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

From the Customization screen running as a Manager, I have entered a support mail address. When I click on the Contact Support link in the INSTANCE SETTINGS panel, it does not bring up an email client.

**Comment by shatfield4** [comment]
Unable to reproduce this bug. What email did you enter into the support email input?

**Comment by daleferrario** [comment]
I tried multiple, including my own ***@***.***).

I am running chrome. I checked and mail.google.com is set as the protocol
handler. I also tried edge with the same behavior.

**Comment by shatfield4** [comment]
![Screenshot 2024-07-10 at 3 50 52 PM](https://github.com/Mintplex-Labs/anything-llm/assets/2336488/fb41ef3c-4ee3-4a77-86a0-49a0b0cc4429)

If you click on the user menu at the top right and the `Support` option here, does that work for you to open the email client?

**Comment by daleferrario** [comment]
No, it does nothing as well. I can see when I mouse over that it has
"mailto: ***@***.***". But when I click nothing happens.

**Comment by timothycarambat** [comment]
Then this is certainly a configuration issue since even anchor tags are not working. Is your instance being accessed on an _ip address over HTTP_ and not on `localhost` or `HTTPS`? Browser security or handlers can sometimes block things like this from occurring when on HTTP connections since its insecure

**Comment by daleferrario** [comment]
Ok thanks I will look into it.Sent from my iPhoneOn Jul 10, 2024, at 4:08 PM, Timothy Carambat ***@***.***> wrote:﻿
Then this is certainly a configuration issue since even anchor tags are not working. Is your instance being accessed on an ip address over HTTP and not on localhost or HTTPS? Browser security or handlers can sometimes block things like this from occurring when on HTTP connections since its insecure
