### ISSUE TITLE
[FEAT]: Light theme option

### ISSUE THREAD

**Issue by mguilherme** [Mintplex-Labs/anything-llm#1864]
### What would you like to see?

Would it be possible to have a clear theme?
I know almost everyone prefer dark themes but unfortunately my eyes can't stand dark backgrounds white clear text!

**Comment by byzheng** [comment]
+1 I also support light theme as I use invert color in windows

**Comment by timothycarambat** [comment]
@grantcarthew PR is already out here https://github.com/Mintplex-Labs/anything-llm/pull/2629
