### ISSUE TITLE
[BUG]: generating a docker image locally,it always reports that the port cannot be used

### ISSUE THREAD

**Issue by Yongliao666** [Mintplex-Labs/anything-llm#1865]
### How are you running AnythingLLM?

Docker (local)

### What happened?

[BUG]: After compiling and generating a docker image locally, when generating a container, it always reports that the port cannot be used, but the port is clearly not occupied
![image](https://github.com/user-attachments/assets/f91ad995-c34b-456d-b9e7-90e4a1cda574)

### Are there known steps to reproduce?

![image](https://github.com/user-attachments/assets/f91ad995-c34b-456d-b9e7-90e4a1cda574)

**Comment by timothycarambat** [comment]
You have a process already running on port 3001, you need to kill that process or just change your command to use another port `3002:3001`. Also the command you are using will lead to you not being able to use the web scraper and you will lose all your data on container rebuild. Use the official command so you dont run into issues!
```powershell
# Run this in powershell terminal
$env:STORAGE_LOCATION="$HOME\Documents\anythingllm"; `
If(!(Test-Path $env:STORAGE_LOCATION)) {New-Item $env:STORAGE_LOCATION -ItemType Directory}; `
If(!(Test-Path "$env:STORAGE_LOCATION\.env")) {New-Item "$env:STORAGE_LOCATION\.env" -ItemType File}; `
docker run -d -p 3001:3001 `
--cap-add SYS_ADMIN `
-v "$env:STORAGE_LOCATION`:/app/server/storage" `
-v "$env:STORAGE_LOCATION\.env:/app/server/.env" `
-e STORAGE_DIR="/app/server/storage" `
mintplexlabs/anythingllm;
```

**Comment by FallenComet7** [comment]
How to change the port from 3001?
My machine has something else running in that port. How to change it? Tried changing in docker file, but still haven't changed
