### ISSUE TITLE
[BUG]: Agent session closes immediately after invoking and requires OpenAI API key.

### ISSUE THREAD

**Issue by goodglitch** [Mintplex-Labs/anything-llm#1872]
### How are you running AnythingLLM?

Directly from Windows 10

### What happened?

When I write any request to agent the following occurs. May be it is my bad, but I haven't seen anywhere requirment of OpenAI API for agents in the documentation.
![image](https://github.com/user-attachments/assets/1c57e957-3597-432a-afe1-ecee939493c2)

### Are there known steps to reproduce?

Any request to agent ends up like that.

**Comment by timothycarambat** [comment]
There is no requirement, we just fallback to OpenAI is all that is occurring here. If you open the workspace settings -> Agent Configuration you can select your preferred LLM provider + model (can be any provider)

**Comment by goodglitch** [comment]
> There is no requirement, we just fallback to OpenAI is all that is occurring here. If you open the workspace settings -> Agent Configuration you can select your preferred LLM provider + model (can be any provider)

Why just not write a human readable message? Something like "Preferred LLM provider for the agent is not specified. Please go to workspace settings -> Agent Configuration to choose one."

**Comment by timothycarambat** [comment]
PR?
