### ISSUE TITLE
[BUG]:  llama 3 cannot be found for local installed ollama

### ISSUE THREAD

**Issue by byzheng** [Mintplex-Labs/anything-llm#1875]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I freshly installed anything-llm in my Windows 11 laptop. 

It is working for LLM  Providers, Anything-LLM with llama3, but very slow (no GPU usage)

Following the suggestions (https://github.com/Mintplex-Labs/anything-llm/issues/1398), I separately installed ollama and pull model with `ollama pull llama3` which is working on command line.

Then I configure LLM Providers in Anything LLM to select model llama3-latest. However, I get an error message.

```
Ollama call failed with status code 404: model "llama2" not found, try pulling it first 
```

**Comment by timothycarambat** [comment]
Open your LLM prefs, select another model (if one is not selected) and reselect what you intended to use - seems that it did not save your config during onboarding

**Comment by fsiler** [comment]
I am having this same issue and reselecting the model did not help.  Win 11 Pro x86, Ollama, hoping to use llama3.2 and get same error.
