### ISSUE TITLE
[FEAT]: multi-modal, lang translators integration, agent plugin system

### ISSUE THREAD

**Issue by attyru** [Mintplex-Labs/anything-llm#1876]
### What would you like to see?

please add:
1) images embedding & search (mutimodal)
2) integration language translate queryes and answers with google translate/yandex/deepl.
3) plugin system, to add custom agent plug-ins.
Sorry for my bad english.
Thanks.

**Comment by ericthomas1** [comment]
Really looking forward to multi-modal using Azure OpenAI `gpt-4o`. Want to paste images directly into chat with text.
