### ISSUE TITLE
[BUG]: AnythingLLM1.5.9.0 and 1.5.10.0 workspace can not upload files

### ISSUE THREAD

**Issue by hejp001** [Mintplex-Labs/anything-llm#1880]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

AnythingLLM1.5.9.0 and 1.5.10.0 workspace can not upload files.

**Comment by timothycarambat** [comment]
This is not a helpful issue - I am on 1.5.10 as of right now and I am able to successfully upload all manners of files.
- What files are you uploading?
- How many are you uploading?
- Do you have any logs from [debug mode](https://docs.useanything.com/debug) that could possibly help
