### ISSUE TITLE
[FEAT]: POST document with meta

### ISSUE THREAD

**Issue by byzheng** [Mintplex-Labs/anything-llm#1886]
### What would you like to see?

If my reading is correct, there are several meta related with a document. For example, from API document .

```json
{
  "success": true,
  "error": null,
  "documents": [
    {
      "location": "custom-documents/anythingllm.txt-6e8be64c-c162-4b43-9997-b068c0071e8b.json",
      "name": "anythingllm.txt-6e8be64c-c162-4b43-9997-b068c0071e8b.json",
      "url": "file://Users/tim/Documents/anything-llm/collector/hotdir/anythingllm.txt",
      "title": "anythingllm.txt",
      "docAuthor": "Unknown",
      "description": "Unknown",
      "docSource": "a text file uploaded by the user.",
      "chunkSource": "anythingllm.txt",
      "published": "1/16/2024, 3:07:00 PM",
      "wordCount": 93,
      "token_count_estimate": 115
    }
  ]
}
```

I would be interesting

**Comment by timothycarambat** [comment]
You can do so with this endpoint (however please dont use metadata keys that are not present in the code block you posted because it _will cause issues_ with the vector database! However you can put whatever you want for the values!

<img width="1469" alt="Screenshot 2024-07-18 at 9 20 26 AM" src="https://github.com/user-attachments/assets/6f80cc87-f5ed-41cf-9a69-21fc09251b9f">

**Comment by Renaldy002** [comment]
Hello, i read this posted and have some question. im trying to uuse pinecone as my vector database and i need to add metadata for each chunk. from your response before it cannot. but it can add meratadata presented in the code block. is it "KeyOne" and "KeyTwo". or is there any list of key i can use for metadata? Thank you

**Comment by jstawski** [comment]
Can we have the same functionality for:

- /v1/document/upload-link
- /v1/document/upload
- /v1/document/upload/{folderName}

I'm building a Sharepoint Synch using the API and I can't create the document with any metadata nor update it.

**Comment by ktalach** [comment]
What about setting url? I'm also trying to implement Sharepoint sync and need clickable reference to uploaded document.. just like in Confluence integration. I want to send document body and url via upload API.
