### ISSUE TITLE
[DOCS]: curl: (6) Could not resolve host: s3.us-west-1.amazonaws.com 

### ISSUE THREAD

**Issue by jkemp814** [Mintplex-Labs/anything-llm#1891]
### Description

Could not resolve host. Address needs updating or wrong server address from Linux installer script.

**Comment by timothycarambat** [comment]
You are probably on a VPN and it is being blocked

**Comment by jkemp814** [comment]
Yes I am. I will try with VPN turned off. I'm in Phoenix, AZ, exiting a server in Phoenix.
