### ISSUE TITLE
[BUG]: uploading documents fail

### ISSUE THREAD

**Issue by chenxjc970140** [Mintplex-Labs/anything-llm#1897]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

My documents interface,  has been unsuccessful and the interface is stuck in circles..
![bug](https://github.com/user-attachments/assets/3a0a43cf-2312-4150-9c71-31a021c0c5a1)

**Comment by timothycarambat** [comment]
Please install the latest desktop version 1.5.11 - this has already been patched
https://docs.useanything.com/changelog/v1.5.11#fixes--improvements
https://github.com/Mintplex-Labs/anything-llm/issues/1881
