### ISSUE TITLE
[Suggestion] Rename DISABLE_TELEMETRY to something app-specific

### ISSUE THREAD

**Issue by levicki** [Mintplex-Labs/anything-llm#1912]
While naming an environment variable `DISABLE_TELEMETRY` is just fine for a docker container it's not really the best choice for a desktop app which shares global environment namespace with other apps.

Imagine the fallout if all apps started using such generic ennvironment variable names &mdash; users would not be able to control anything per app.

It's of course possible to set the telemetry opt-out variable in a command prompt and launch the app from there, but that's far from a convenient icon double-click.

Therefore, I suggest renaming it to `ALLM_DISABLE_TELEMETRY` or something similar.

**Comment by timothycarambat** [comment]
The variable name in the app is not loaded from a global namespace (like system envs) - it comes from a `.env` file that is used to start the backend processes with the correct settings. While I presume someone _could_ run a CLI command to start these same processes with written-in ENV commands.

Additionally, this is toggleable from the UI as well so disabling of telemetry is not restricted to an ENV variable and its value will persist between restarts

**Comment by levicki** [comment]
> The variable name in the app is not loaded from a global namespace (like system envs) - it comes from a .env file that is used to start the backend processes with the correct settings. 

Are we talking about Windows native app or a docker app?

Because as I said, for Docker it doesn't really matter.
