### ISSUE TITLE
[BUG]:  i can not input chinese

### ISSUE THREAD

**Issue by fangyifei222** [Mintplex-Labs/anything-llm#1924]
### How are you running AnythingLLM?

Local development

### What happened?

When I switch to anythingllm, my Chinese input method stops working, resulting in the ability to only type in English. What's going on?

**Comment by timothycarambat** [comment]
The input in the app should have no impact on your keyboard output - without more information there is no way to assist in if this is a bug or not.

- Can you type Chinese while in any other language display?
- Are you simply just using the app and the input does not work?
- How are you typing Chinese? native keyboard, virtual, etc
- You set the environment as `Local development` so this would mean you are in a browser - do you normally have issues with input of Chinese in browser?
