### ISSUE TITLE
[BUG]: AnythingLLM Win10 Desktop App and LM Studio issue with Llama 3

### ISSUE THREAD

**Issue by wrtz008** [Mintplex-Labs/anything-llm#1927]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I am using AnythingLLM on Win10 22H2 and also LM Studio v0.2.27 (latest version). I've loaded my Llama 3 LM in LM Studio:

![anything lm 2](https://github.com/user-attachments/assets/7838ead4-cce5-465d-b992-11240ad78bb1)

and in AnythingLLM I have the setting as LLM Provider as such:

![anything lm 1](https://github.com/user-attachments/assets/d6902384-b7fa-4b77-918f-474cc5ff3520)

and in the Workspace Settings > Agent Configuration  > I am using LM Studio:

![anything lm 3](https://github.com/user-attachments/assets/69b373b7-21f2-413b-b55b-d26bbee1d4bb)

**Any idea if this is the correct setup to use Llama 3? Because I tried the chat feature, it seems it can't reply back and confirm what LLM it's using:**

![anything lm 4](https://github.com/user-attachments/assets/d5e4b052-509e-40c7-90e6-a08e9c70163d)

Thank you!

**Comment by timothycarambat** [comment]
This is not a bug, this is how LLM's work. In general most LLMs have no idea what they are - this is even a problem with GPT https://community.openai.com/t/gpt-4-through-api-says-its-gpt-3/286881

In general, you should not expect a model to really _know_ anything!
