### ISSUE TITLE
[BUG]: No GPU used for Native Bare Metal AnythingLLM Instance

### ISSUE THREAD

**Issue by omaralagouz** [Mintplex-Labs/anything-llm#1928]
### How are you running AnythingLLM?

Local development

### What happened?

I am using the Native option of a downloaded custom LLM (Mistral-7b-instruct-v0.2.Q5_K_M.gguf & Llama-2-7b-chat.Q5_K_M.gguf) but when i ask any question it takes about 1.5 minutes to get a response with RAG. I am running this in development on:
- MS Windows 10 Pro
- Processor: 12th Gen Intel(R) Core(TM) i9-12900T, 1400 MHz, 16 Core(s), 24 Logical Processor(s)
- 64 GB RAM
- GPU: NVIDIA T1000 8GB

Is there a way to use the GPU for inference, offloading a specific number of layers? I tried looking through the code but couldn't find where i can adjust this knowing that Llama.cpp is used in the background.

**Comment by timothycarambat** [comment]
Yeah, this is one of the pain points with the "native" llama.cpp module. Its becomes a lot more trouble to use directly vs just relying on the work of other local runners like Ollama or LMStudio so we will be deprecating the native runner in upcoming changes - unfortunately because of how the llama.cpp is built in-image it makes rebuilding so hard to do in-container to even _hope_ to bind to the machines GPUs, plus it has no CUDA in the image so I imagine that wont even help :/

I highly recommend to swap out to another local LLM runner as we are going to remove that LLM provider soon because of issues like this

**Comment by omaralagouz** [comment]
> Yeah, this is one of the pain points with the "native" llama.cpp module. Its becomes a lot more trouble to use directly vs just relying on the work of other local runners like Ollama or LMStudio so we will be deprecating the native runner in upcoming changes - unfortunately because of how the llama.cpp is built in-image it makes rebuilding so hard to do in-container to even _hope_ to bind to the machines GPUs, plus it has no CUDA in the image so I imagine that wont even help :/
> 
> I highly recommend to swap out to another local LLM runner as we are going to remove that LLM provider soon because of issues like this

The issue with switching to ollama or lmstudio is that the their server doesn’t allow for parallel API calls, which makes it so that it can’t be used as an application deployed somewhere for many users to log into and use simultaneously. If I’m wrong please correct me

**Comment by timothycarambat** [comment]
Ollama does now support parallelization/concurrency [now as of 0.2.0](https://github.com/ollama/ollama/releases/tag/v0.2.0)

It previously did not, and LMStudio still does not

**Comment by omaralagouz** [comment]
awesome! I downloaded ollama for windows and it's working great! It is in fact though using minimal GPU (4%), may you guide me as to how to increase the GPU usage? If im not mistaken it's to do with offloading more layers to the GPU? It was easier to do on LMStudio.

**Comment by timothycarambat** [comment]
Ollama should auto-bind to your GPU should the GPU support CUDA. What GPU are you on? Closing this for now but we can keep the convo going.

https://github.com/ollama/ollama/blob/main/docs/gpu.md

**Comment by omaralagouz** [comment]
I'm on Windows 10, Lenovo Thinkstation with an Nvidia T1000 8GB GPU, The entire model is loaded onto the GPU memory (taking up 5-6 GB), and when I ask a question to the LLM the GPU usage % spikes to 100% then back to around 0%. I've tried setting the num_gpu parameter to -1, 10, 20, and 32 for Mistral, and all seem to be about the same.
