### ISSUE TITLE
[BUG]: Docker finetune white page.

### ISSUE THREAD

**Issue by SamuelEnzi** [Mintplex-Labs/anything-llm#1930]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I hosted anything llm on docker (remote server) behind a proxy (forwarded wss for agents) and ssl. When i navigate to /fine-tuning only a white page is shown. There are no http error responses but console errors:
![image](https://github.com/user-attachments/assets/6a39e61a-5f29-4e2c-b475-2f004d400ba4)

### Are there known steps to reproduce?

1. install anythingllm on a remote machine using docker 
2. setup a proxy like apache add a ssl certificate and dns entry. forward wss for agents.
2. use it and generate some data until the popup for finetune shows.
3. click on the button in the settings or the popup to see the white page and the errors in console

**Comment by timothycarambat** [comment]
Just patched, that should have gotten caught by a local linter rule I have, it was due to a bad import as we dumb `ssr` icons from phosphor icons to reduce the frontend bundle size.
