### ISSUE TITLE
[BUG]: Windows protected your PC

### ISSUE THREAD

**Issue by 37OMKAR** [Mintplex-Labs/anything-llm#1941]
### How are you running AnythingLLM?

Docker (local)

### What happened?

cant install 
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

### Are there known steps to reproduce?

<html><body>
App: | AnythingLLMDesktop.exe
-- | --
Publisher: | Unknown publisher

</body></html>

**Comment by 37OMKAR** [comment]
cant proceed 
![image](https://github.com/user-attachments/assets/b9c26265-7c0e-4104-b737-db69f97dd1eb)

**Comment by CedricGoby** [comment]
Click "More info" and proceed.

**Comment by 37OMKAR** [comment]
> Click "More info" and proceed.

nope its not thre when we click  there is only App: | AnythingLLMDesktop.exe -- | -- Publisher: | Unknown publisher notring else

**Comment by timothycarambat** [comment]
@37OMKAR this sounds like you arent an admin on your computer then - you may have to get permissions from whoever is to run the application then. This only occurs because the windows app is still currently unsigned

**Comment by sanchez1337** [comment]
@timothycarambat is there a plan of doing it? Trying to run it on my work laptop but encountered the same issue.

**Comment by dantewang** [comment]
Is there any plan to sign the Windows app and get it recognized by Windows Smart Screen?

**Comment by timothycarambat** [comment]
@dantewang I would love to TBH, but it seems that interacting with these providers has been nothing short of totally painful (DigiCert mostly) and admittedly its a bit out of my wheelhouse which is why it is taking so long since there are about 20 ways to sign things and they are not exactly flexible.

That's candidly the main blocker.

**Comment by notorious-dle** [comment]
Please spend the money to get a Code Signing Certificate:

[Certum EV code signing certificate](https://shop.certum.eu/data-safety/code-signing-certificates/certum-ev-code-sigining.html)
[DigiCert EV code signing certificate](https://www.digicert.com/signing/code-signing-certificates)
[Entrust EV code signing certificate](https://www.entrust.com/products/digital-signing/code-signing-certificates)
[GlobalSign EV code signing certificate](https://go.microsoft.com/fwlink/p/?LinkId=620888)
[IdenTrust EV code signing certificate](https://www.identrust.com/digital-certificates/trustid-ev-code-signing)
[Sectigo (formerly Comodo) EV code signing certificate](https://www.sectigo.com/ssl-certificates-tls/code-signing)
[SSL.com EV code signing certificate](https://www.ssl.com/certificates/ev-code-signing/)

**Comment by rogerfar** [comment]
@timothycarambat you can use [Azure Trusted Signing](https://azure.microsoft.com/en-us/products/trusted-signing), it's pretty cheap and easy to integrate in a build pipeline.

A workaround is to unblock the file first:

<img width="484" height="647" alt="Image" src="https://github.com/user-attachments/assets/9cc9b81f-4eb5-440a-b6d5-ad89070d5e54" />
