### ISSUE TITLE
[FEAT]: Add Helm Chart for Kubernetes Deployment

### ISSUE THREAD

**Issue by justmenyou** [Mintplex-Labs/anything-llm#1947]
### What would you like to see?

This issue proposes the creation of a Helm chart to streamline the deployment of our application on Kubernetes clusters.

**Comment by juhoinkinen** [comment]
Could you add a reference to the Helm chart, which I suppose is somewhere as this was marked completed? I could not find any reference to it from this repo; Google shows multiple hits "anythingllm helm chart", but I would like to use an official one, if such exists.

**Comment by roylkng** [comment]
+1
