### ISSUE TITLE
[FEAT]: introduce the conversation with a message

### ISSUE THREAD

**Issue by nicho2** [Mintplex-Labs/anything-llm#1950]
### What would you like to see?

Is it possible to begin the conversation, with a text to explain why the embed chat is do ?

**Comment by timothycarambat** [comment]
There is currently a `greeting` which should fulfill this:
> data-greeting — Default text message to be shown when chat is opened and no previous message history is found.

https://github.com/Mintplex-Labs/anything-llm/tree/master/embed#script-customization-options
