### ISSUE TITLE
[DOCS]: Continues software development 

### ISSUE THREAD

**Issue by hemangjoshi37a** [Mintplex-Labs/anything-llm#1951]
### Description

If anyone has achieved or can suggest for this . In this we want to continuously index the updated code base in the HippoRAG index and query on the updated index and then make code changes and continuously do so. Here consider that we want to do this offline with ollama type models only and dont want to use OpenAI or Claude .

If anyone can suggest how can i do this ?

**Comment by timothycarambat** [comment]
Have you considered this beta feature? https://docs.useanything.com/beta-preview/active-features/live-document-sync

**Comment by hemangjoshi37a** [comment]
@timothycarambat i cant find experimental features in my docker running image that is given in the web-page you provided.
