### ISSUE TITLE
[FEAT]: Groq LLama3.1 support

### ISSUE THREAD

**Issue by jasonmhead** [Mintplex-Labs/anything-llm#1953]
### What would you like to see?

When will LLama3.1 Groq models be supported?

Is that something that is in the development pipeline?

Is there a way that whatever models are available from a source could be added without explicitly listing them in the code/settings file?

**Comment by timothycarambat** [comment]
There was when we first integrated Groq, but wow my mind is blown they finally have a models endpoint!!
https://console.groq.com/docs/api-reference#models-list

Will work on this now.
