### ISSUE TITLE
[BUG]: cannot connect to LM Studio server 

### ISSUE THREAD

**Issue by FBTCAD** [Mintplex-Labs/anything-llm#1955]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

using version 1.5.11 when trying to connect to LM studio server, cannot see the model - window stuck - can see the embbeder with right model, but when chat get a connection error. 
![connection](https://github.com/user-attachments/assets/c2f8da64-313c-41a9-a567-242618fcd523)
![embedder](https://github.com/user-attachments/assets/c4397604-06e2-42e4-8b74-6352223602ed)
![model](https://github.com/user-attachments/assets/c95a17f9-ddce-427c-81c6-c0009ab16de2)

**Comment by timothycarambat** [comment]
You forgot `http` for the LLM connection - which is why models do not work. If the model dropdown does not populate then the connection URL is not correct
