### ISSUE TITLE
Copy Invite Link button does not copy link to clipboard

### ISSUE THREAD

**Issue by TychoML** [Mintplex-Labs/anything-llm#196]
As per the title. Experienced this in Windows 11, using Firefox. Just a minor issue of course, as just copy pasting the key directly can be used as a workaround.

![afbeelding](https://github.com/Mintplex-Labs/anything-llm/assets/130043595/a53cdd0b-2483-4c14-84bd-1ba8d0a57b3e)

**Comment by timothycarambat** [comment]
Marked as wontfix for the reasons above
