### ISSUE TITLE
[FEAT]: API `Workspaces` should return thread slugs.

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1961]
### What would you like to see?

As an API user, when i request a workspace or `workspaces` I should be able to see all thread slugs available for use with their slug and respective owner (if applicable)

**Comment by byzheng** [comment]
Is it released? How should I use it? I download V 1.5.12 and still don't have threads information from workspace.

**Comment by timothycarambat** [comment]
When something is closed on here that means it live in docker, but does not mean it is live in Desktop since the desktop client is pre-compiled. It will be live in 1.6.0, which is live now.
