### ISSUE TITLE
[BUG]: LanceDB::Invalid ENV settings 

### ISSUE THREAD

**Issue by win32fk** [Mintplex-Labs/anything-llm#1974]
### How are you running AnythingLLM?

Docker (local)

### What happened?

when i  move a document to workspace and save embed ,then it toast a " LanceDB::Invalid ENV settings " message.

after minutes:
try again ,it. works .

what is the problem?

**Comment by timothycarambat** [comment]
This is almost certainly an issue with your setup - did you run the docker container using the command in [This documentation](https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md)?

What vector database are you using? If the ENV is wrong it should not be temporary - it would be broken until it is fixed.

**Comment by win32fk** [comment]
I'm not  use that documentation ,and  not set env . i think it works by default .

**Comment by timothycarambat** [comment]
Ah, then that for sure would lead to issues - if you just boot the container with no .env you can get a lot of very weird issues like the one listed here.

**Comment by dbcalo** [comment]
I encountered this issue. I installed AnythingLLM on TrueNAS scale 25.04.2.1, and the error started after I rebooted. The only apparent solution is to uninstall AnythingLLM and start over.

**Comment by timothycarambat** [comment]
This was a bug briefly for 1.8.5 - it was patched in 1.8.5-r2 shortly after

**Comment by drdreamm** [comment]
@timothycarambat - how do I install 1.8.5-r2 ? Cannot see branch ?

**Comment by drdreamm** [comment]
I just need to save LANCEDB as vector DB

**Comment by austingsmith** [comment]
> I encountered this issue. I installed AnythingLLM on TrueNAS scale 25.04.2.1, and the error started after I rebooted. The only apparent solution is to uninstall AnythingLLM and start over.

I think this is an issue w/ the docker container on that platform.  I too suffer the same - it appears the location where these settings are stored is not properly mapped to a host file directory which will erase configuration settings upon redeployment of the container.

**Comment by timothycarambat** [comment]
There is a big warning message if you dont have STORAGE_DIR set
https://github.com/Mintplex-Labs/anything-llm/blob/6270a0a189d34153d5e9e6b255a6d797bf8d3096/docker/docker-entrypoint.sh#L4-L17

This is explicitly outlined in the HOW TO USE DOCKER file in the docker folder
https://github.com/Mintplex-Labs/anything-llm/blob/6270a0a189d34153d5e9e6b255a6d797bf8d3096/docker/HOW_TO_USE_DOCKER.md?plain=1#L34-L36

This is additionally said on our actual docs page
https://docs.anythingllm.com/installation-docker/quickstart#start-anythingllm-via-docker
https://docs.anythingllm.com/installation-docker/local-docker#run-the-image

If it is not set, storage is in the container, it will be deleted with the container on removal
