### ISSUE TITLE
[FEAT]: list documents with pagination

### ISSUE THREAD

**Issue by johnnychen94** [Mintplex-Labs/anything-llm#1975]
### What would you like to see?

I've successfully uploaded the entire knowledge base (> 7000 files) using the API endpoint programmatically.
This immediately introduces a performance issue that `/v1/documents` fails to return the result in a reasonable time.

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
```

Another similar situation is the document workspace fails to show the result and keeps the loading ring almost forever:

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/4f521f12-a51c-47b3-bf96-3ff621177b44">

The chat and RAG part still works.

This is a request for pagination support so that workspaces with too many documents still work well.

For what it worths, our current workaround is to merge eagerly the 8000 files into a few big files (e.g., concatenate them until reaches 50M limit) so that we don't reach this too-many-files problem.

**Comment by timothycarambat** [comment]
Moved to #2317
