### ISSUE TITLE
UI issue: System Setting - Tabs are not showing properly

### ISSUE THREAD

**Issue by crippledfaith** [Mintplex-Labs/anything-llm#198]
![Screenshot 2023-08-17 220904](https://github.com/Mintplex-Labs/anything-llm/assets/7411687/79865866-02e9-4164-9d50-8b0fa0d94000)
![Screenshot 2023-08-17 2221149](https://github.com/Mintplex-Labs/anything-llm/assets/7411687/1aba04c5-5d31-4de9-907c-c948adf1cd10)

**Comment by timothycarambat** [comment]
It scrolls to the side, this UI will be changed soon because of how much it has grown
