### ISSUE TITLE
[BUG]: Fault add Document to workspace

### ISSUE THREAD

**Issue by kuyinya** [Mintplex-Labs/anything-llm#1980]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

In the Anything LLM Desktop application on macOS version 15, when attempting to import documents into the workspace and encountering a failure during the "Save and Embed" operation, the error message you're seeing translates to:

"Error: 1 document failed to add, fetch failed."
<img width="1315" alt="Screenshot 2024-07-27 at 09 35 08" src="https://github.com/user-attachments/assets/a0e42448-db90-4393-943c-1ba440e91916">
<img width="1355" alt="Screenshot 2024-07-27 at 09 34 57" src="https://github.com/user-attachments/assets/f71a533c-af74-4788-97a9-102b417e8850">

**Comment by TianT1209** [comment]
@kuyinya Hello, how did you solve this problem?

**Comment by avi-cenna** [comment]
@TianT1209 I had this same issue on MacOS, and I think the `fetch failed` message means that it failed to download the embedder model. This could be due to company firewall, for example.

What I did to fix the problem was to change my embedder model to Ollama Llama 3.1 in the AnythingLLM settings.
