### ISSUE TITLE
[FEAT]: Add Function Calling Functionality to anything-llm

### ISSUE THREAD

**Issue by vdamov** [Mintplex-Labs/anything-llm#1986]
### What would you like to see?

**Description:**
I am requesting the addition of function calling functionality within the anything-llm project. This feature will enable users to dynamically execute predefined functions or custom scripts based on specific triggers or commands processed by the language model.

**Rationale:**
Integrating function calling capabilities will significantly enhance the versatility and practical utility of the anything-llm project by allowing it to:

- **Automate Tasks**: Execute automated workflows and repetitive tasks based on natural language commands.
- Extend Capabilities: Interface with external systems, databases, or APIs to retrieve and manipulate data in real-time.
- **Interactive Applications**: Develop more interactive applications where the language model can directly interact with the underlying system to perform complex operations.
- **Customization**: Allow users to define custom functions that can be triggered by specific phrases or commands, enabling a highly personalized and powerful user experience.

Thank you for considering this feature request. I am eager to see how this functionality can further elevate the capabilities of the anything-llm project and am willing to contribute to the development and testing process.

**Comment by timothycarambat** [comment]
Handled by custom agent skills
https://docs.anythingllm.com/agent/custom/introduction
