### ISSUE TITLE
[DOCS]: OpenApi Spec not valid

### ISSUE THREAD

**Issue by acrive82** [Mintplex-Labs/anything-llm#1988]
### Description

I am using `openapi-generator` to automatically create interfaces to invoke the AnythingLLM API. The specification provided does not meet the validation rules (which I omit here).  In addition, the provided swagger-ui itself, does not allow valid visualization. The main errors, concern the payload definitions of POST requests. 

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/dc6661b4-591f-4ef9-a116-185d93aa2c16">

**Comment by timothycarambat** [comment]
Visualization bug patched in 1.6.0!
