### ISSUE TITLE
[BUG]: does not work with local ollama

### ISSUE THREAD

**Issue by josersleal** [Mintplex-Labs/anything-llm#1989]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

1- there are no clear end to end  instructions on how to use ollama local setup. The reason is that it does not work.

Just that.  try to use local ollama anyway you want and it fails.

### Are there known steps to reproduce?

just choose local ollama as llm provider and try to chat

**Comment by timothycarambat** [comment]
There are certainly clear instructions - search the repo and our docs before posting issues like this.
https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/ollama/README.md#common-issues-with-ollama
https://docs.useanything.com/ollama-connection-troubleshooting

You can also search past issues in Github
