### ISSUE TITLE
[BUG]: The 'chat selection model' in Groq always reverts back to the first one (gemma2).

### ISSUE THREAD

**Issue by GitOnTop** [Mintplex-Labs/anything-llm#1992]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When Groq is set as the LLM, if I select any llama model as the 'chat model', then 'save changes', it automatically reverts back to the first chat model (gemma2) every single time.

The problem appeared when I upgraded to AnythingLLM version 1.5.12 today. The last version that I was running (1.5.5) did not appear to have that particular issue. I'm using the Windows desktop version.

**Comment by timothycarambat** [comment]
This turned out to be a simple UI bug. WHile it may show that the model is `gemma` is will actually send calls as whatever you did select and save on. So this is a UI issue only and will be in next desktop update and is patched now

**Comment by GitOnTop** [comment]
Great, thank you!
