### ISSUE TITLE
Configured env keys but getting PinecoreError: failed getting project name

### ISSUE THREAD

**Issue by bachagabriel** [Mintplex-Labs/anything-llm#2]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[PineconeError: Failed getting project name. TypeError: fetch failed]

I installed everything. After I run the server, when I run the front end, the server crashed with the above error

**Comment by jlevy-io** [comment]
I had the same issue, I had pasted my entire pinecone index URL value in.   Fixed by only using the index name.

Example:  myindex-xxxxxxx.svc.xxxxxx-gcp.pinecone.io
replaced with just "myindex" and it worked

**Comment by timothycarambat** [comment]
This was recently patched. It was hot-loading the Pinecone helper and if you were using something else it would crash the entire server.

Pull in latest changes and try again and re-open this if needed!

Thanks @jlevy-io as well!
