### ISSUE TITLE
error running on windows 10

### ISSUE THREAD

**Issue by kaza** [Mintplex-Labs/anything-llm#20]
I tried running it on windows 10, got following error:

'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS E:\source\repos\anything-llm>

**Comment by timothycarambat** [comment]
Are you running this in powershell? You would need to use a WSL terminal or a BASH wrapper when doing this on windows since commands like `cat` `ls` and other *inux commands are not available

**Comment by timothycarambat** [comment]
Refer to PR #34, once merged can run rocker
