### ISSUE TITLE
[FEAT]: Where is the vector database in my PC?

### ISSUE THREAD

**Issue by iamalex33329** [Mintplex-Labs/anything-llm#2006]
### What would you like to see?

How can I access the vector database after I've uploaded the files to my disk?

**Comment by timothycarambat** [comment]
On Mac:
`/Users/<usr>/Library/Application Support/anythingllm-desktop/storage/lancedd`

On Linux:
`/Users/<usr>/.config/anythingllm-desktop/storage/lancedd`

On Windows:
`C:\\User\<usr>\AppData\Roaming\anythingllm-desktop\storage\lancedd`

**Comment by iamalex33329** [comment]
Thank you very much :))
