### ISSUE TITLE
[BUG]: Knowledge/Dataset not going to gemini?!

### ISSUE THREAD

**Issue by akwin1234** [Mintplex-Labs/anything-llm#2008]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

how do i solve this?

gemini doesnt see any knowledge or datasets. works fine with openAI or claude APis

main thing is its not even working if i check "Pin Knowledge" its still not working either

### Are there known steps to reproduce?

append vector DB to gemini.

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/llm-not-using-my-docs

How to you _know_ that no information is going to Gemini and it's not just bad queries resulting in no similarity search results?
