### ISSUE TITLE
[BUG]: Special characters in workspace name break vector database table name

### ISSUE THREAD

**Issue by jmalmellones** [Mintplex-Labs/anything-llm#2009]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

If you name your workspace with special characters, that is breaking vector database table access.

### Are there known steps to reproduce?

Name a workspace like "No Man's Sky". Add any document to the workspace and try to embed it.

**Comment by jmalmellones** [comment]
The problem seems to persist after a workspace name change in workspace settings. Only solution for now is remove the workspace and create another one with a better name.

Best regards

**Comment by timothycarambat** [comment]
Yeah, the name change only changes the display name, not its table-slug. Extended the mapping to cover all symbols
