### ISSUE TITLE
[BUG]: TypeError: Failed to resolve module specifier "@phosphor-icons/react/dist/ssr".

### ISSUE THREAD

**Issue by ccr-fan-3000** [Mintplex-Labs/anything-llm#2012]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Hello, 

I am running into issues deploying AnythingLLM remotely with Docker. I do have a bit of an unorthodox setup, as my docker file is pulling the image and overwriting a very specific part of it (as I needed to use a PostgreSQL db iunstead of SQLite). Anyways, everything seems to be working until I create and click into a new workspace. Upon clicking on a Workspace, the UI goes blank and throws `TypeError: Failed to resolve module specifier "@phosphor-icons/react/dist/ssr". Relative references must start with either "/", "./", or "../".`
![image](https://github.com/user-attachments/assets/59d5b77f-6777-4857-a13b-fa062131d5d9)

Below is my DockerFile configuration for reference. 
```
FROM mintplexlabs/anythingllm  
  
COPY ./schema.prisma ./server/prisma/  
# Delete existing sqlite migrations  
RUN rm -rf ./server/prisma/migrations/  
# Copy Postgres migrations  
COPY ./migrations/ ./server/prisma/migrations/  
```

**Comment by timothycarambat** [comment]
This has already been patched + deployed to docker
https://github.com/Mintplex-Labs/anything-llm/commit/2ee5d2095504d96bde7bb028f191e5f3a89007b0

Please repull the newest image - sorry :)
