### ISSUE TITLE
[FEAT]: Adjustable TTS speed. And please add STT.

### ISSUE THREAD

**Issue by AIbottesting** [Mintplex-Labs/anything-llm#2013]
### What would you like to see?

The open source program "espeak" has a slider to increase or lower the speed at which the TTS can be run. Please add this feature.

Please add STT. It sounds like there are several projects that have figured out small and fast models (I could be wrong).
https://github.com/ILikeAI/AlwaysReddy?tab=readme-ov-file#setup
I would prefer the STT to be local and run off the CPU or something, but I don't know if that is possible. Just a teeny tiny model that isn't that accurate would be better than nothing at all.

If you do any of this, thank you in advance.

**Comment by timothycarambat** [comment]
We have STT to the docker version since Chrome has a mic and STT library built in, however Electron does not - which is why this native ability is missing in desktop

**Comment by AIbottesting** [comment]
Oh okay, thanks

**Comment by timothycarambat** [comment]
STT now exists in the desktop app with a local whisper model running on device as of v.1.6.3

**Comment by AIbottesting** [comment]
You are the best! Thank Youuuuu!!!

**Comment by Kurasa632** [comment]
When I use Speech-to-text as input，the following error message is displayed:“Could not locate file:
"http://localhost:3001/static/stt/models/Xenova/whisper-tiny/tokenizer config.json”Do you have any experience with this situation?
