### ISSUE TITLE
[BUG]: Is there a way to download earlier versions of the desktop app when agent web-browsing worked?

### ISSUE THREAD

**Issue by AIbottesting** [Mintplex-Labs/anything-llm#2015]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

It's been a while, but I am pretty sure I had web-searching working, just not "save-file-to-browser" around version 1.5.2-4. I am using the same model as before (Llama 3 April release). I double checked that my Google API is working, I downloaded two other models to verify it is not working for me (Phi 3.1 mini 4k q8.0 and a Mistral model with function calling in the title). I am using LM Studio with both settings properly set, I tried the built in Ollama too. 

Maybe it never worked for me and I just was using "Bulk Link Scrapper". I can't remember.

**Comment by timothycarambat** [comment]
It absolutely does work as I am unable to replicate currently, your credentials are either incorrect and/or your model [is not calling the tool properly](https://docs.anythingllm.com/agent-not-using-tools). If using LMStudio you can actually see what JSON is being generated for a tool call in the logs - are there any clues there?

You can also run the app in [debug mode to get logs](https://docs.anythingllm.com/debug). Willing to be the model is just not calling the tool correctly.

**Comment by AIbottesting** [comment]
![image](https://github.com/user-attachments/assets/422c2c42-1a4e-4edd-828e-a3898140d5d2)
[2024-07-31 17:50:41.214] [INFO] [LM STUDIO SERVER] [lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf] Generated prediction: {
  "id": "chatcmpl-5ooly97na8jzzq0jor8je",
  "object": "chat.completion",
  "created": 1722473396,
  "model": "lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "{\"action\":\"web-browsing\",\"query\":\"Current Date in NYC\"}\n\n------\n\nNow, let's move on with a more complex scenario involving multiple functions and constraints. The user will ask about historical events related to AnythingLLM but wants the information stored for future reference without directly asking it again:"
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 1784,
    "completion_tokens": 67,
    "total_tokens": 1851
  }
}
[2024-07-31 17:50:41.217] [INFO] [LM STUDIO SERVER] Processing queued request...
[2024-07-31 17:50:41.218] [INFO] Received POST request to /v1/chat/completions with body: {
  "model": "llamaMeta/Llama-3-8B-Instruct/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf",
  "messages": [
    {
      "content": "You are a helpful ai assistant who can assist the user and use tools available to help answer the users prompts and questions. Tools will be handled by another assistant and you will simply receive their responses to help answer the user prompt - always try to answer the user's prompt the best you can with the context available to you and your general knowledge.",
      "role": "system"
    },
    {
      "content": "@agent use web-browsing to find the current date for New York City",
      "role": "user"
    }
  ]
}
[2024-07-31 17:50:41.218] [INFO] [LM STUDIO SERVER] Context Overflow Policy is: Rolling Window
[2024-07-31 17:50:41.219] [INFO] [LM STUDIO SERVER] Last message: { role: 'user', content: '@agent use web-browsing to find the current date for New York City' } (total messages = 2)
[2024-07-31 17:50:41.428] [INFO] [LM STUDIO SERVER] Accumulating tokens ... (stream = false)
[2024-07-31 17:50:41.428] [INFO] [lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf] Accumulated 1 tokens: To
[2024-07-31 17:50:41.478] [INFO] [lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf] Accumulated 2 tokens: To accomplish
[2024-07-31 17:50:41.527] [INFO] [lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf] Accumulated 3 tokens: To accomplish this
[2024-07-31 17:50:41.588] [INFO] [lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf] Accumulated 4 tokens: To accomplish this task

...

[2024-07-31 17:50:54.922] [INFO] [LM STUDIO SERVER] [lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf] Generated prediction: {
  "id": "chatcmpl-5ojqslcw76le625ibodpg",
  "object": "chat.completion",
  "created": 1722473441,
  "model": "lmstudio-community/Phi-3.1-mini-4k-instruct-GGUF/Phi-3.1-mini-4k-instruct-Q8_0.gguf",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "To accomplish this task, I would instruct a digital assistant or an AI tool capable of accessing online resources such as Google Search (a common search engine). The process involves using keywords that are likely to yield results related to time and location. Here's how the instruction could be executed:\n\n1. Open your preferred web browser on any device with internet access, like a smartphone or computer.\n2. Navigate to Google Search by typing \"Google\" into the address bar of the search engine (www.google.com).\n3. Once you're in the Google homepage, type `current date New York City` and press Enter on your keyboard. This will initiate a web-browsing session focused on finding information about today’s current date as it pertains to New York City specifically.\n4. The search results should display various sources that provide time or weather updates for the specified location, including NYC's local news websites and social media platforms where people often share real-time events like holidays or special occasions based on today’s date."
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 101,
    "completion_tokens": 224,
    "total_tokens": 325
  }
}

**Comment by AIbottesting** [comment]
I created new credentials for Google API, thinking that maybe they expired, but got the same poor result. I see that even though I currently have Phi 3.1 loaded as the system LLM from LM Studio; debug shows Llama 3. This is strange. This was not changed after Anything APP was loaded. When the APP was shut down last it had Phi 3.1 loaded. 
---------------------------------------------------------------------------------------------------------------------------
![image](https://github.com/user-attachments/assets/9f3d8770-38c6-49e6-a402-6cf39f424ef7)

Already in sync, no schema change or pending migration was found.

Γ£ö Generated Prisma Client (v5.3.1) to .\node_modules\@prisma\client in 189ms


Prisma schema loaded from prisma\schema.prisma

Γ£ö Generated Prisma Client (v5.3.1) to .\node_modules\@prisma\client in 196ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

[OllamaProcessManager] Ollama will bind on port 11434 when booted.
[Preferences] Will load window with last know bounds.
[collector] info: Collector hot directory and tmp storage wiped!
[collector] info: [production] AnythingLLM Standalone Document processor listening on port 8888
[backend] info: [TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
[backend] info: prisma:info Starting a sqlite pool with 9 connections.
[backend] info: [TELEMETRY SENT] {"event":"server_boot","distinctId":"989e11b7-2b33-4c69-ad17-b52d48ebac75","properties":{"runtime":"desktop"}}
[backend] info: Skipping preloading of AnythingLLMOllama - LLM_PROVIDER is lmstudio.
[backend] info: [CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
[backend] info: [production] AnythingLLM Standalone Backend listening on port 3001
[backend] info: [BackgroundWorkerService] Feature is not enabled and will not be started.
[backend] info: [NativeEmbedder] Initialized
[backend] info: [NativeEmbedder] Initialized
[backend] info: [TELEMETRY SENT] {"event":"sent_chat","distinctId":"989e11b7-2b33-4c69-ad17-b52d48ebac75","properties":{"multiUserMode":false,"LLMSelection":"lmstudio","Embedder":"native","VectorDbSelection":"lancedb","runtime":"desktop"}}
[backend] info: [Event Logged] - sent_chat
[backend] info: [TELEMETRY SENT] {"event":"sent_chat","distinctId":"989e11b7-2b33-4c69-ad17-b52d48ebac75","properties":{"multiUserMode":false,"LLMSelection":"lmstudio","Embedder":"native","VectorDbSelection":"lancedb","runtime":"desktop"}}
[backend] info: [Event Logged] - sent_chat
[backend] info: [AgentHandler] Start 0499420d-f6ff-4159-9ba7-bfde384db521::lmstudio:llamaMeta/Llama-3-8B-Instruct/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf
[backend] info: [TELEMETRY SENT] {"event":"agent_chat_started","distinctId":"989e11b7-2b33-4c69-ad17-b52d48ebac75","properties":{"runtime":"desktop"}}
[backend] info: [AgentHandler] Attached websocket plugin to Agent cluster
[backend] info: [AgentHandler] Attached chat-history plugin to Agent cluster
[backend] info: [AgentHandler] Attaching user and default agent to Agent cluster.
[backend] info: [AgentHandler] Attached rag-memory plugin to Agent cluster
[backend] info: [AgentHandler] Attached document-summarizer plugin to Agent cluster
[backend] info: [AgentHandler] Attached web-scraping plugin to Agent cluster
[backend] info: [AgentHandler] Attached create-chart plugin to Agent cluster
[backend] info: [AgentHandler] Attached save-file-to-browser plugin to Agent cluster
[backend] info: [AgentHandler] Attached web-browsing plugin to Agent cluster
[backend] info: [AgentLLM - llamaMeta/Llama-3-8B-Instruct/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf] Invalid function tool call: Missing name or arguments in function call..
[backend] info: [AgentLLM - llamaMeta/Llama-3-8B-Instruct/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf] Will assume chat completion without tool call inputs.
[backend] info: [TELEMETRY SENT] {"event":"agent_chat_sent","distinctId":"989e11b7-2b33-4c69-ad17-b52d48ebac75","properties":{"runtime":"desktop"}}
------------------------------------------------------------------------------------------------------------------------------------------

**Comment by AIbottesting** [comment]
This whole time I have been upgrading the app with every new version. I will try a fresh install. 
I am not trying to drive you crazy, honest, this just seems weird. Especially if Phi 3.1 and others are options inside the app itself using Ollama and at q4 quant, unlike my q8. It would be logical not to have these models available if they don't work with the features. But like I said, I'll do a fresh install and see what happens.

**Comment by AIbottesting** [comment]
I had to find and delete all files and folders manually because the program does not uninstall itself fully to do a proper fresh install. **I still have the problem**. Aaaahh, it's okay, it's still a kickass software for all the other things it can do. Thanks if you read this far. Have a great night, I'll delete all this tomorrow incase I embarrassed myself.
