### ISSUE TITLE
[BUG]: together.ai integration won't show Llama 3.1 and Gemma 2 series

### ISSUE THREAD

**Issue by huydhoang** [Mintplex-Labs/anything-llm#2017]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I'm on the AnythingLLM desktop app on Windows. Had my together.ai API key in place.
But somehow Llama 3.1 and Gemma 2 models won't show up in the list as stated in AnythingLLM docs.

Is there a quick fix in some local config files?

![Screenshot 2024-08-01 191606](https://github.com/user-attachments/assets/2b522b7d-9c6d-4476-8c6b-ccd44871724c)

### Are there known steps to reproduce?

1. Install AnythingLLM
2. Turn on together.ai integration
3. Click on dropdown menu of available models

**Comment by timothycarambat** [comment]
Already patched in `master` https://github.com/Mintplex-Labs/anything-llm/commit/466bf7dc9c3ffc0502cf3f63a53655d024cb2a9c

Will be in the next desktop app. They do not support a `/models` endpoint so we have to statically grab the list and refresh is manually
