### ISSUE TITLE
Unable to Delete File or Vectors.

### ISSUE THREAD

**Issue by crippledfaith** [Mintplex-Labs/anything-llm#202]
There is no way to delete a file once uploaded. There should be a way to delete files that are uploaded. If you have an endpoint to do this please let me know.

Thanks

**Comment by timothycarambat** [comment]
Expand the file - it is purge document.

UI will be changing soon for file manager to be more intuitive.

<img width="579" alt="Screen Shot 2023-08-21 at 2 36 30 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/65cd274c-05ea-49dd-8d4e-ff42b270eea4">
