### ISSUE TITLE
[FEAT]: Multiple Ollama instance support

### ISSUE THREAD

**Issue by grantterra** [Mintplex-Labs/anything-llm#2024]
### What would you like to see?

Supporting multiple Ollama instances would be great.

I have multiple Ollama instances running on different servers.

If I can use one instance for workspace chat and another for agent skills, that would be nice.

or maybe different workspace use different ollama server.

Similar to:
#https://github.com/Mintplex-Labs/anything-llm/issues/1409

**Comment by timothycarambat** [comment]
Correct, lets keep this constrained to #1409 as well as #1567

They are basically the same concept - but yes understood as hot-loading the required model i supposed is not ideal for everyone and apparently people have many ollama's running all over at once!
