### ISSUE TITLE
[FEAT]: Pin Docker Image Tags to Specific Versions to Avoid Breaking Changes

### ISSUE THREAD

**Issue by la-cc** [Mintplex-Labs/anything-llm#2026]
### What would you like to see?

Currently, the application is being built and tagged as :latest for the Docker image. This approach can lead to breaking changes when the image is updated. To prevent such issues, it would be beneficial to bind the image to specific tags and pin these tags in the build and push image GitHub workflow. It would be great if a version of the application itself could be introduced so that you can see, for example, below in the ui the Info anything-llm-0.3.5 or so, which one matches the image tag. 

We have currently [created a fork and are building a fixed version](https://github.com/la-cc/anything-llm), but would like to have a fixed version in the core repository from you.

We have also provided a [helm chart](https://github.com/la-cc/anything-llm-helm-chart), which allows several configuration options and we also receive requests why we have our own image with a fixed tag.

**Comment by reefland** [comment]
Probably others dups of this.  #1857

**Comment by timothycarambat** [comment]
They are, moving to #1857 for docker version pins
