### ISSUE TITLE
[BUG]: Citations do not correspond to the true chunk locations.

### ISSUE THREAD

**Issue by sonnt-dna** [Mintplex-Labs/anything-llm#2027]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I am using a Docker file and embedding texts in the AnythingLLM Database. When I use it, the citation section shows the wrong positions of the chunks used to provide the answer. Please help me fix this issue, and if there is a way to do it, please provide guidance!

**Set up the Environment:**

Ensure Docker is installed and running on your machine.
Use the provided Docker file to set up the AnythingLLM environment.
Start the Docker container.

**Embed Texts in AnythingLLM Database:**

Use the embedding function to add texts to the AnythingLLM Database.
Ensure that the texts are divided into chunks correctly during the embedding process.

**Query the Database:**

Perform a query that triggers the citation functionality.
Observe the results and note the positions of the cited chunks.

**Identify the Issue:**

Compare the cited positions with the actual positions in the original text.
Note any discrepancies where the citation positions do not match the correct locations of the chunks

**Comment by timothycarambat** [comment]
This is not a bug if I am reading this correctly, this is just how RAG works. They are ranked by "similarity" not their inherent order in the original document. In fact, embeddings do not preserve their order in the source document at all and are purely linked via metadata alone.
