### ISSUE TITLE
[DOCS]: GitHub Codespace hangs for Local Container on Windows 10

### ISSUE THREAD

**Issue by MrSimonC** [Mintplex-Labs/anything-llm#2029]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hello. I'm trying to start Anything LLM in a GitHub Codespace (so that I might contribute, even in a tiny way) and also trying locally using a container on Windows 10 with Visual Studio Code dev containers. However, I'm experiencing issues with the startup process.

**Steps to Reproduce:**

1. Followed the instructions in the `.devcontainer/README.md` file to set up the dev container in Visual Studio Code.
2. Also tried created a new GitHub Codespace and installed the dev container using the same instructions.
3. The container starts up then `yarn setup` starts up.

**Expected Behavior:**

Yarn should set up / install what it needs, then finishes setting up / installing dependencies.

**Actual Behavior:**

The startup process hangs indefinitely _(I've waited for hours on windows, and GitHub Codespaces waits so long that GitHub actually deletes the Codespaces itself as it never gets past the Container-Creating setup - I've experienced this twice now)_, displaying the following output:
```
##########################################################################################
[5/5] Building fresh packages...
[-/4] ⠠ waiting...
[2/4] ⠐ sharp
[-/4] ⠐ waiting...
[4/4] ⠐ puppeteer
```
This output remains the same for hours, with no progress or errors displayed.

**Environment:**

* GitHub Codespace: latest version, asking GitHub Codespace (in cloud) to show in VSCode locally
* Local environment: Windows 10, Visual Studio Code with dev containers, using WSL to run locally in windows
* Container: Docker container based on the `.devcontainer/README.md` instructions

**Troubleshooting:**

I've tried the following:

* Restarted the container and GitHub Codespace multiple times

**Request:**

I would appreciate any guidance on how to resolve this issue. Is there a known problem with the startup process, or are there additional steps I need to take to get Anything LLM running in my environment? Could one of the team just try running the existing devcontainer from scratch locally / in GitHub Codespaces? Surely it can't be just me?

**Additional Information:**

* I've checked the GitHub Codespace and local container configurations, and they appear to be identical.
* I've tried searching for similar issues in the GitHub repository, but couldn't find any relevant information.

**Comment by timothycarambat** [comment]
d4eecdef030fc53d2b3c98ff8adbe212f631b473
