### ISSUE TITLE
Pinecone: Chunk deletes

### ISSUE THREAD

**Issue by crippledfaith** [Mintplex-Labs/anything-llm#203]
Unable to remove the file from Workspace Setting
https://github.com/Mintplex-Labs/anything-llm/assets/7411687/1a6755ec-40e8-4031-92b0-aa81bef50fcc

**Comment by crippledfaith** [comment]
After Inspecting the docker logs. 

PineconeClient: Error calling delete1: PineconeError: Number of provided ids: 1022 exceeds the maximum amount per request: 1000 [PineconeError: PineconeClient: Error calling delete1: PineconeError: Number of provided ids: 1022 exceeds the maximum amount per request: 1000]

This seems to be a very efficient what to delete, is there no way to bulk delete?

DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg0-58e5b047-aaff-4517-82b2-ac93d7c2f737.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg1-2ecca708-8b90-41b2-a345-b3b614450897.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg10-c45acb06-81ad-4ab7-bf95-0470fa133b1a.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg100-cfa2db74-c317-4f82-b5e4-056a20bfedd8.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg101-78801aef-62c2-4ea6-a222-e6fab228fad5.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg102-00380668-d07c-4562-ab9c-54d23a7d4678.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg103-03907801-0562-4981-b36b-be81799fd5bc.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg104-bc1e0b13-9045-4475-9308-0865f9c030ae.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg105-75be3b6f-ade7-4ea4-8028-39657f7d693f.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg106-98ad7722-2e63-4aaa-b024-0329e917eab7.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg107-2ff36203-234d-4a84-be02-e10ccda57893.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg108-bef641a8-f66f-4940-be9e-f9ad2714d141.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg109-f7272887-e207-4d5f-9985-3a98a177e6db.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg11-079441aa-2705-4af7-9f3f-3ead5fe49936.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg110-3009b978-3937-4c9c-8df9-17f20112f566.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg111-59fec7cc-3318-423b-9822-4312f562fe7b.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg112-af2a7744-8feb-42e9-ba5d-9e28af69619e.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg113-fae6559f-7c2f-4c58-a87a-857f5df27b7b.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg114-7468e464-4642-4c56-b300-6275d836a3af.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg115-46048d8e-24ef-4b9a-80e7-a7213977ded0.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg116-06392982-10a0-4cb5-825e-548f188b95e1.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg117-813d64e4-ce39-4be8-bb76-4d97cf507937.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg118-45cb1889-6af8-4100-a434-a24192b6244a.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg119-5a93f05f-985d-4f64-b61d-553197285117.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg12-77853c13-ac4a-4bbe-991b-0fbe5c6643ab.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg120-c48a08cc-7d69-4530-89a0-a9d76bd5cfa2.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg121-079fbd92-8702-42a4-98ef-ed8dc9c286ec.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg122-3072db93-b632-42ec-99d8-10efd8d5a3ba.json' AND workspaceId = 3
DELETE FROM workspace_documents WHERE docpath = '64-1692225068/64-pg123-aef38186-dba3-4562-a5c1-7dd4024fb0bf.json' AND workspaceId = 3

**Comment by timothycarambat** [comment]
When deleting vectors from Pinecone the data needs to be chunked in blocks of 1,000 ids per call. This is due to a limitation of Pinecone delete calls.
