### ISSUE TITLE
[FEAT]: Return thread name in the workspace API

### ISSUE THREAD

**Issue by byzheng** [Mintplex-Labs/anything-llm#2030]
### What would you like to see?

In the latest version 1.6.0

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/blob/0b64aa51016db6286438f954a51a5472c01686e9/server/endpoints/api/workspace/index.js#L122

**Comment by timothycarambat** [comment]
That is from the desktop branch
