### ISSUE TITLE
[FEAT]: Allowing users to set and manage multiple keys themselves.

### ISSUE THREAD

**Issue by chalitbkb** [Mintplex-Labs/anything-llm#2040]
### What would you like to see?

Is it possible to set up multiple API keys from providers like OpenAI or Gemini? Sometimes my API key hits its limit, and I'd like to automatically switch to another key from a backup list instead of manually setting each one. I feel like I'm wasting time having to set a new API key every time it exceeds the usage limit.

Additionally, it would be great if users could set multiple keys themselves as mentioned above. Even better, if possible, it would be fantastic to allow users to specify a personal API endpoint to fetch external API lists for use.
![image](https://github.com/user-attachments/assets/0f23c39f-71bd-471b-a386-aa9e0739b49a)

**Comment by timothycarambat** [comment]
This is indeed a common ask - covered by #2022 and more specifically #1567.

Those PR's would address this exact issue you are referencing to have multiple stored _connections_ so you can have many at once without interference 👍
