### ISSUE TITLE
[FEAT]:  Add gemini-1.5-pro-exp-0801 model to Gemini API

### ISSUE THREAD

**Issue by KrisFortnite** [Mintplex-Labs/anything-llm#2043]
### What would you like to see?

Could you please add the experimental Gemini 1.5 Pro version to the list of Gemini API models? I would be very grateful. 

Thank you very much for your time :)

**Comment by timothycarambat** [comment]
Already done https://github.com/Mintplex-Labs/anything-llm/pull/2031

If it is not in the Desktop app it is because it missed the weekly desktop app update. latest version is 1.6.0 and therefore will be present in any subsequent version since it is already live in master
