### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by leonnn1** [Mintplex-Labs/anything-llm#2046]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I am trying to use the LLM as a chat bot for my website, I fed it with some of my web pages and my documentation page, the problem is that when I try ask something it begins generating a response and crashes just after.

![image](https://github.com/user-attachments/assets/2a6cb55f-867f-40fe-b73b-7f5140d9ae6c)

### Are there known steps to reproduce?

I set the workspace with a deepseek-coder-v2.16b lite q8 and everything was on default.
I only added the web pages to the workspace as embeds and I asked a question related to that website

**Comment by timothycarambat** [comment]
This would indicate your ollama client crashed and did not return a valid text response as it should have, presuming it is a chat model - which is appears to be.

**Comment by leonnn1** [comment]
> This would indicate your ollama client crashed and did not return a valid text response as it should have, presuming it is a chat model - which is appears to be.

Yes it is a chat model, I am using deepseek, but why is it happening I dont understand, I used a couple of models and all ended up with the same error
