### ISSUE TITLE
[FEAT]: Upload new documents directly in a specified folder

### ISSUE THREAD

**Issue by MihailCosmin** [Mintplex-Labs/anything-llm#2055]
### What would you like to see?

The current way of organizing files and folders is extremely un-user-friendly.
All new files are uploaded to the default folder as noted in this issue: [#1824](https://github.com/Mintplex-Labs/anything-llm/issues/1824)

When you upload hundreds of files to the default folder that already has hundreds of files, going through all of them and clicking on each checkbox to select and then move them to another folder is bad user experience and unnecessary.

A better solution would be to actually go in the windows/linux folder where the files are stored and move them to the correct folder manually thus making the interface useless.

Another solution could be to have the workspaces separated by folders, and have the option to navigate to the parent directory and thus access all workspace folders. But in most cases the files should be separated by workspace.

**Comment by timothycarambat** [comment]
You can do this now via draggin and dropping files directly into chat while focused on a workspace
