### ISSUE TITLE
[BUG]: Context not correct after embedding file

### ISSUE THREAD

**Issue by florian-hansen-mw** [Mintplex-Labs/anything-llm#2056]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hi,

I am on the AnythingLLM desktop app for MacOS with Apple Silicon chips, v1.6.0
I am integrating it with a local Ollama installation running the mistral-nemo:latest model with a max-tokens config of 120.000.
I use the default Vector DB and Embedder and Text Splitter.

I have configured a workspace with a Prompt "You are alf". I have changed nothing else. Regarding the question "Who are you", the model correctly replies with "I am Alf..."
![image](https://github.com/user-attachments/assets/1f99bda4-33a3-4400-b08b-40787c8189a1)

Now I create a new Thread in the same Workspace.
I added a file (content should not matter, it's a 6 line shell script).
When I now ask "Who are you?" it still knows it's Alf.
Now I appended a 6ki file (second message), and the model forgets, who it is:

![image](https://github.com/user-attachments/assets/019066af-b36b-4920-9aad-0c9d53742d18)

**Comment by timothycarambat** [comment]
This is an LLM behavior - this is not related to AnythingLLM or how it functions. Depending on the quantization of your model it may not even "listen" to your system prompt at all.
