### ISSUE TITLE
[FEAT]: AnythingLLM RAG + OCR with Preprocessing + WebSearch  Workflow

### ISSUE THREAD

**Issue by vishaldwdi** [Mintplex-Labs/anything-llm#2059]
### What would you like to see?

Requesting Easily Implementable Feature Enhancement to achieve this Workflow, so that life of Researchers, Investigators, Officials, and PhD Students could improve

(I'm adding this through the eyes of researcher, I'm aware that certain capabilities may already have been implemented in some way or form, I'm also aware that some part of this was requested earlier, my the goal is to make end product much more cohesive considering upcoming University Season)

_**_# High Level Workflow_**_

**Step 1: Add Document for RAG** -
User uploads a document (e.g., PDF, image, or text file) to the system. AnythingLLM performs RAG to store document in a respective database.

**Step 2: Anything LLM Checks if Document Requires OCR**
Anything LLM analyzes the document to determine if it requires OCR (Optical Character Recognition). -
If the document is an image or scanned PDF, it likely requires OCR.

**Step 3: OpenCV + Pillow Preprocessing prior OCR** -
If OCR is required, Anything LLM utilizes Tesseract OCR with OpenCV and Pillow preprocessing to extract text from the document. The extracted data is then stored to improve respective database.

( I have personally tested that OpenCV+Pillow Preprocessing prior Tesseract improves complex text recognition by 52% ). 

**Step 4: Database Improvement**  -
If OCR was required, the extracted text is used to improve the database.
If OCR was not required, Anything LLM uses its inbuilt capabilities to improve the database with the uploaded document.

**Step 5: User Enters Query** -
The user enters a query or question.

**Step 6: Database Search and Web Search (if database insufficient)**
Anything LLM searches the database to satisfy the user's query. -
If the database search yields insufficient results, Anything LLM utilizes a web search API (e.g., Google Custom Search) to fetch relevant results. The web search results are then stored in the database.

**Step 7: Anything LLM Processing -**
Anything LLM processes the query using its multiple LLM models accessed through APIs. The LLM models generate a response based on the database search and web search results.

**Step 8: Response Generation** -
Anything LLM generates a response to the user's query, utilizing the processed information. This workflow integrates OCR, web search, and LLM capabilities to provide accurate and up-to-date responses to user queries.

Reference:
https://github.com/ItzCrazyKns/Perplexica
https://github.com/tesseract-ocr/tesseract
https://pypi.org/project/opencv-python/
https://pillow.readthedocs.io/en/stable/

**Comment by timothycarambat** [comment]
We do **all** of the above steps already and even the websearch part (using `@agent`)  and agents can _also_ access RAG'd documents. The only part of this not done is the OCR component which is covered by https://github.com/Mintplex-Labs/anything-llm/issues/510 👍 

Also, we are a nodeJS project so references to a Python library is not going help us much in solving these issues. However, tesseract has node bindings and we are aware of this already internally so that would likely be the way we go about doing that

**Comment by vishaldwdi** [comment]
@timothycarambat Hi, I appreciate your response.
 
I want to bring your attention to the latest update of Gemini. Coincidently, on the same day, Gemini released its full support with "PDF Vision and Text understanding".

Let me quote from the reference, "The Gemini API and AI Studio now support PDF understanding through both text and vision. If your PDF includes graphs, images, or other non-text visual content, the model uses native multi-modal capabilities to process the PDF. You can try this out via Google AI Studio or in the Gemini API."

I am interpreting that OCR can be done through Gemini API or am I mistaken? Does it mean that AnythingLLM just got OCR through Google Vision by itself?

Please confirm whether if a user connects AnythingLLM with GeminiAPI and when the user prompts RAG of AnythingLLM then the API will perform OCR? If yes, then it indeed is great news.

If not, then can something be done easily to utilize this newly released capability of GeminiAPI? 


Reference: https://developers.googleblog.com/en/gemini-15-flash-updates-google-ai-studio-gemini-api/

**Comment by kundeng** [comment]
rag and ocr are 2 different use cases.
