### ISSUE TITLE
[BUG]: Document Upload Not Functioning for Default Users in Docker Installation on a multiuser setup

### ISSUE THREAD

**Issue by spyroskotsakis** [Mintplex-Labs/anything-llm#2060]
### How are you running AnythingLLM?

Docker (local)

### What happened?

In a Docker installation with multiple users enabled, the document upload functionality does not work for regular users. When the file selection popup opens and a document is chosen, no response or indication appears to show that the document has been attached to the chat. However, for Managers and Administrators, this functionality works without any issues. Additionally, no errors are found in the logs.

Is this a known issue?

Thanks!

### Are there known steps to reproduce?

To reproduce the issue, set up a Docker installation with multiple users enabled. Log in to the application using a regular user account (default user type). Navigate to the chat section and attempt to upload a document by opening the file selection popup and choosing a document. Observe that there is no response or indication that the document has been attached to the chat.

**Comment by timothycarambat** [comment]
Default users cannot upload documents, which is why nothing happens as it is gated on the backend to prevent that. The UI element allowing this is the bug.

**Comment by spyroskotsakis** [comment]
@timothycarambat  Thank you for clarifying. Are there any ongoing developments to make this feature available to default users? A workspace that offers more flexibility and allows interaction with each user's own data would be extremely helpful.
Thanks a lot!

**Comment by timothycarambat** [comment]
Indeed we do (would just be a custom role)
https://github.com/Mintplex-Labs/anything-llm/issues/1787

Considering the scope of this issue, we may add an intermediate role soon that basically allows "private workspace" so everyone can do their own thing without impacting anyone else.
