### ISSUE TITLE
[FEAT]: Does anything-llm have API to allow calling from external code?

### ISSUE THREAD

**Issue by jingweibhuang** [Mintplex-Labs/anything-llm#2063]
### What would you like to see?

Thank you for the awesome tool! 

I’m wondering whether anything-llm has API ( like OpenAI API) to allow call anything-llm from python or an external system such as langchain? Such type of APIs will be very useful to allow machines (rather than just human users) to interact with anything-llm. For example, I have a large set of text, each of them needs to call an LLM engine for query.

Thank you:-)

**Comment by timothycarambat** [comment]
We do, every instance (even desktop) of AnythingLLM has a full developer APi you can use to send chats. https://docs.anythingllm.com/features/api

If you have anythingllm running, opening settings > Tools > Developer API and you can get your own key + view all the docs/endpoints available.

**Comment by jingweibhuang** [comment]
Thank you for quick response!! 
It would be more helpful if a bit more information such as function interface is provided in the documentation page https://docs.anythingllm.com/features/api.
Thanks again:-)

**Comment by Nero10578** [comment]
> Thank you for quick response!! It would be more helpful if a bit more information such as function interface is provided in the documentation page https://docs.anythingllm.com/features/api. Thanks again:-)

Did you get this to work? I just keep getting 401 Unauthorized on the API when trying to chat using openai api endpoint.

**Comment by timothycarambat** [comment]
@Nero10578 did you possibly get an API key first so that you can use the API. On the sidebar > Tools > Developer API > Generate API Key button right at the top.

It is an API - so you need a key, even if you are doing everything locally. 401 means you dont have a key and/or are sending the request incorrectly. Header should be `Authorization Bearer API-KEY-GOES-HERE`
