### ISSUE TITLE
[FEAT]: Improve versioning latest release in public S3 bucket

### ISSUE THREAD

**Issue by ddaws** [Mintplex-Labs/anything-llm#2068]
### What would you like to see?

It would be really helpful for packaging if the latest version of the app was also published to the `legacy` directory of the public S3 bucket used for distributing binaries and bundles. 

Pacman packages built with makepkg verify checksums, but this is harder to do if the URL used to retrieve assets aren't versioned. This means the package can break if the files in `latest` are updated but the checksums in the package configuration aren't updated. 

Here is an AUR package that could benefit from improved versioning
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=anythingllm-desktop-bin#n29

**Comment by timothycarambat** [comment]
Okay, will do this when we publish. When we make a new version we will dupe the files to its legacy folder version as well. Right now we have just been using the legacy folder before a new version release, but we can make it part of the release process now.
