### ISSUE TITLE
[BUG]: Embedding Provider URL not recognized

### ISSUE THREAD

**Issue by luc-w** [Mintplex-Labs/anything-llm#2069]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I run the AnythingLLM desktop app and LocalAI in Docker. When chosing Local AI as embedding provider and providing the Local AI base URL, the embedding model name remains --waiting for URL--. When I change the embedding provider to LM Studio (which is not installed) and provide the same URL, AnythingLLM recognizes all models installed in Local AI.

### Are there known steps to reproduce?

Freshly installed AnythingLLM Desktop with
`curl -fsSL https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/installer.sh | sh`
and Local AI with
`docker run -p 8080:8080 --name local-ai -ti localai/localai:latest-aio-cpu`
Llama3:8b-instruct-q8_0 is running via Ollama in the background

**Comment by timothycarambat** [comment]
Are you using `http://127.0.0.1/v1` or just `http://127.0.0.1`? The right URL is `/v1`

**Comment by luc-w** [comment]
Thanks! Not sure where I missed this detail.

**Comment by timothycarambat** [comment]
@luc-w That is not on you - its in the placeholder for the input and we should handle it for you tbh @shatfield4
