### ISSUE TITLE
[BUG]: Error: connect ECONNREFUSED 127.0.0.1:5433

### ISSUE THREAD

**Issue by sonnt-dna** [Mintplex-Labs/anything-llm#2070]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hi Admin,

I am currently encountering an issue with connecting to the Local-Postgres database while using AnythingLLM. Below are the details of the error and the steps I have taken so far:

Error Details:

less
Copy code
@agent: Checking what are the available databases.
@agent: Checking what are the available tables in the Local-Postgres database.
Running SQL: SELECT * FROM pg_catalog.pg_tables WHERE schemaname = 'public'
Error: connect ECONNREFUSED 127.0.0.1:5433
Steps Taken:

Verified that PostgreSQL is running on port 5433.
Checked that the PostgreSQL service is active and listening on the correct port using sudo lsof -i -P -n | grep LISTEN.
Updated the pg_hba.conf and postgresql.conf files to ensure proper configurations.
Restarted the PostgreSQL service using brew services restart postgresql@14.
Successfully connected to the PostgreSQL server via the command line:
css
Copy code
psql -h localhost -p 5433 -U postgres -d postgres
Despite these steps, the application still throws the "connect ECONNREFUSED 127.0.0.1:5433" error. Could you please guide me on how to properly configure the connection for AnythingLLM?

I appreciate any assistance or guidance you can provide.
![image](https://github.com/user-attachments/assets/f2311ee7-5ce2-4bb1-bacf-47a99a92ecce)

![image](https://github.com/user-attachments/assets/16c807a8-d0de-469c-a11f-d2e40f819389)

**Comment by timothycarambat** [comment]
Unless you are running PG _inside_ of the AnythingLLM container (unlikely) when you use 127.0.0.1 or localhost you are referring to the _containers network layer_ not your host.

Use `host.docker.internal:5433` or if on Ubuntu `172.17.0.1` to reach back out to the host network layer.

**Comment by sonnt-dna** [comment]
> Unless you are running PG _inside_ of the AnythingLLM container (unlikely) when you use 127.0.0.1 or localhost you are referring to the _containers network layer_ not your host.
> 
> Use `host.docker.internal:5433` or if on Ubuntu `172.17.0.1` to reach back out to the host network layer.

Thanks for your reply
I am using PG inside of my AnythingLLM. 
How can I do it
Thanks you for supporting!
