### ISSUE TITLE
[FEAT]: Custom base urls for OpenAI Voice & Speech

### ISSUE THREAD

**Issue by lee-b** [Mintplex-Labs/anything-llm#2071]
### What would you like to see?

The new voice and speech support is great, but the OpenAI provider only supports the official OpenAI servers.  OpenedAI-Speech and LocalAI both support these speech APIs locally, so not allowing custom API URLs is an unnecessary limitation here.

**Comment by timothycarambat** [comment]
This is what is covered by #1453
