### ISSUE TITLE
[BUG]: Can't download Llama3.1 8B 

### ISSUE THREAD

**Issue by greanleaf** [Mintplex-Labs/anything-llm#2076]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

In the latest versions that have Llama 3.1 8B as an option for the AnythinLLM  LLM provider, it gets stuck downloading and never progresses. I've tried this on two different Macbooks on two different networks and get the same result.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e739ea2f-24f6-40b7-bc3b-17caacf7521a">

### Are there known steps to reproduce?

1. Go to settings
2. Go to AI providers
3. Go to LLM
4. Select AnythingLLM as the LLM provider
5. Select Llama3.1 8B
6. Click Save Changes

After this, you get a popup that it has started downloading, and the top right of the window reflects this, however it never actually starts downloading (I check via a network monitor) and never progresses. Other models download and load just fine.  

In also tried completely removing and installing AnythingLLM (including all of the stuff stored in ~/Library) so that it is a completely fresh install. It made no difference.

**Comment by codemonkey2k5** [comment]
Having the same issue.  A progress bar would be extremely helpful and save folks a lot of time waiting for nothing to happen.

**Comment by BHMSI** [comment]
I am having this issue on M1 Mac and can't cancel the download of the model, so ALLM is completely stuck. I can't  cancel the download, change models, etc. I tried restarting the app, reinstalling, etc. No joy.

**Comment by shatfield4** [comment]
We've just pushed a bug fix for this, please update to the latest version and this is patched.

**Comment by softwaresinc** [comment]
Appears to still be effectively broken. I stopped the download but it doesn't know it. Error message:

AnythingLLM:404: llama3.2:3b has not completed downloading. Please wait for it to complete to send a chat.

**Comment by max38tech** [comment]
> Having the same issue. A progress bar would be extremely helpful and save folks a lot of time waiting for nothing to happen.

AMEN!! It's a no-brainer.
