### ISSUE TITLE
[FEAT]: Support for Custom Root Path

### ISSUE THREAD

**Issue by danikong** [Mintplex-Labs/anything-llm#2078]
### What would you like to see?

I would like to request the ability to deploy AnythingLLM on a custom root path, such as `example.com/chat`, rather than being limited to subdomain deployments like `chat.example.com`. This feature would allow for greater flexibility in integrating AnythingLLM into existing websites and applications that are structured with specific path requirements.

Benefits:
- Increased flexibility for deployment options.
- Better integration with existing web applications.
- Simplified DNS management for users who prefer not to use subdomains.

Thank you for considering this feature request!

**Comment by timothycarambat** [comment]
This is an arch NGINX setup issue and is out of scope for the project. It is a docker container and you can get it to run however you like, as you could with any other web-service.

Is it more difficult to do? Yes, but it is certainly possible if you know your way around the depths of webserver setup
