### ISSUE TITLE
[BUG]: Homebrew installation broken

### ISSUE THREAD

**Issue by hcguersoy-cg** [Mintplex-Labs/anything-llm#2079]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I wanted to install AnythinLLM on my MBP using Homebrew, resulting in an error due to SHA mismatch:

```shell
 brew install --cask anythingllm
==> Downloading https://s3-us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop-Silicon.dmg
################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: c596e2e121ab10c12b4b0ab2156e00300cbf5e7954c62b7009a70f049deb18c8
  Actual: 096bff3430f0dc9d3fe585205d36d08a0e6b20758fd7c5acdc37641b9b90b3b5
    File: /Users/xyz/Library/Caches/Homebrew/downloads/7cc866ab69c401d5283a88bf9e255969d8a4126bbcac211d9c035d40f3b22632--AnythingLLMDesktop-Silicon.dmg
To retry an incomplete download, remove the file above.
```

This may be caused by referring the `latest` version instead of a specific version in the brew formulae. 

My system: macOS 14.5 on Apple Silicon M1, Homebrew 4.3.14 

### Are there known steps to reproduce?

Simply run a `brew install --cask anythingllm` in you macOS shell.

**Comment by timothycarambat** [comment]
We dont maintain that cask, someone else in the community does and I do not know how to contact them or update the file for it so we can control its content. :(

**Comment by timothycarambat** [comment]
All we do it upload to our bucket - somehow that cask will auto-update, not sure how that whole process works

**Comment by hcguersoy-cg** [comment]
In this case I don't understand why the installation using _Homebrew_ is mentioned in the documentation:

<https://docs.anythingllm.com/installation/desktop/macos#install-using-homebrew>

**Comment by timothycarambat** [comment]
Because someone in the community built it and had PR'd it to the old docs and we ported it to the new docs - the top of that page has downloading the DMG as the first method, the other are alternatives.

Maybe we can add a warning on that option since that is not the preferred method, but in the interim you could just use any other method, you are not confined to homebrew
