### ISSUE TITLE
[BUG]: Cannot be deployed on a linux server docker

### ISSUE THREAD

**Issue by icewizardry** [Mintplex-Labs/anything-llm#2086]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The following is the log in the docker container:

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db

### Are there known steps to reproduce?

Run the docker-run.sh file. The following is the content of the file.
- I am using the root account, so there is no sudo command to execute.
- I use the command "chmod 755 /data/sites/AnythingLLM"
But there is no effect, still no permission to access. I have been using this method to start various mirrored containers, but this one is the only one that has this problem. Since the disk is mounted in the /data directory, you can't restrict users to publishing using userspace.
- I mounted into the path "/ home/XXX/data/sites/AnythingLLM" still doesn't work.
I have always used the root account and should not have this kind of problem.

#!/bin/bash
export STORAGE_LOCATION=/data/sites/AnythingLLM &&
touch "$STORAGE_LOCATION/.env" &&
docker run -d --name=anythingllm -p 2235:3001
--cap-add SYS_ADMIN
-v ${STORAGE_LOCATION}:/app/server/storage
-v ${STORAGE_LOCATION}/.env:/app/server/.env
-e STORAGE_DIR="/app/server/storage"
--log-opt max-size=10m --log-opt max-file=3
mintplexlabs/anythingllm:1.1.1

**Comment by jiojiojackson** [comment]
I have the same issue. How did you solve it ?

**Comment by thistleknot** [comment]
unable to open database file: ../storage/anythingllm.db
okay, I figured out this error
https://github.com/Mintplex-Labs/anything-llm/issues/1996
chmod -R 777 /mnt/intRaid_/anythingllm
