### ISSUE TITLE
Getting Inaccurate and Incomplete answer

### ISSUE THREAD

**Issue by crippledfaith** [Mintplex-Labs/anything-llm#209]
Getting Inaccurate and Incomplete results from Anything-LLM results it seem like it not reading the whole document, before giving the results.

Anything LLM result
![Screenshot 2023-08-22 075822](https://github.com/Mintplex-Labs/anything-llm/assets/7411687/c6f168a0-b7d0-47af-85cf-34d57b62c889)
ChatGTP result
![Screenshot 2023-08-22 075749](https://github.com/Mintplex-Labs/anything-llm/assets/7411687/cfd934e6-37e8-4f1b-adb8-50366f285f2d)

Text File In Question,
[INCOME TAX MANUAL.txt](https://github.com/Mintplex-Labs/anything-llm/files/12409952/INCOME.TAX.MANUAL.txt)

**Comment by timothycarambat** [comment]
Resolved by chat window improvements that have been live for a while now! Give it another try
