### ISSUE TITLE
[FEAT]: convert toasts to something prettier

### ISSUE THREAD

**Issue by jose-donato** [Mintplex-Labs/anything-llm#2093]
### What would you like to see?

have you considered other toast solutions prettier than the current solution?

i've used https://sonner.emilkowal.ski/ a lot in the past and it's great. the API is great and the styles out of the box are awesome as well

<img width="462" alt="image" src="https://github.com/user-attachments/assets/e6b84087-4a57-4cb7-a9aa-f85d30683ec8">

can help create a PR if you like the idea

**Comment by timothycarambat** [comment]
This is just an opinion on design, we are perfectly happy with `react-toastify`, that being said since it all goes to a single place in the code it would be an easy swap to make for your own fork 👍
