### ISSUE TITLE
Lengthy response and codeblock appearance

### ISSUE THREAD

**Issue by mkammes** [Mintplex-Labs/anything-llm#21]
Lengthy ChatGPT responses appear on top of previous responses.
Example: 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/8660699/cc74799e-d28d-430a-ae9c-1fb94f2bfc18)

ChatGPT response with markdown code block gives three backticks (```) , but no codeblock.

Example response for code:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/8660699/76a718d3-9f41-4335-94a6-895cc072dfc1)

**Comment by timothycarambat** [comment]
Marked as an issue - great suggestion.

Objective: Implement codeblock output similar to the output style of ChatGPT for prompt responses only.
