### ISSUE TITLE
[FEAT]: Some sort of text search in the current chat or all chats in workspace is needed for the desktop version.

### ISSUE THREAD

**Issue by Taluen79** [Mintplex-Labs/anything-llm#2101]
### What would you like to see?

Do you sometimes remember talking about something with the AI but don't know which chat it was in? Or where in a very long conversation, something important was mentioned but you don't quite remember where?

FTLOG Please implement a text search for the desktop version. WebUI interface can often get away with this with the built-in text search function of the browsers. Desktop users are left scrolling endlessly looking for that important message somewhere in the haystack of messages.

**Comment by timothycarambat** [comment]
solid point!

**Comment by Taluen79** [comment]
I'm not sure it anything-llm uses Nativefier or Electron. If it is using Elelectron it might be possible to inject some JavaScript to enable text search? Just a guess.

**Comment by DangerousBerries** [comment]
Very much needed.

**Comment by socketbox** [comment]
@timothycarambat You've indicated that OP makes a "solid point" but you closed a similar feature request as "not planned": #2740

**Comment by timothycarambat** [comment]
Ctrl+f in the chat view and you can search. [Been live since 1.6.9](https://docs.anythingllm.com/changelog/v1.6.9#find-in-page-support-for-workspace-chat)
