### ISSUE TITLE
[BUG]: Resulting text content was empty for xxx

### ISSUE THREAD

**Issue by qiuchen001** [Mintplex-Labs/anything-llm#2102]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I am uploading two documents, one of them succeeds but the other one fails with a failure log message of:
[collector] info: -- Working 软件设计师教程第5版.pdf --
[backend] info: [Event Logged] - document_uploaded
[collector] error: Resulting text content was empty for 软件设计师教程第5版.pdf.

From the logs, I can't directly deduce what's causing the problem

Initially I wondered if the document was too big, and when I compressed the failed one to the same size as the successful one (16M), it still failed the same way.

Does anyone know what is causing this? How can I circumvent this error?

**Comment by timothycarambat** [comment]
Is it possible this document is a _scanned_ PDF and not a generated PDF? the pdf parser does not use OCR https://github.com/Mintplex-Labs/anything-llm/issues/510
