### ISSUE TITLE
[BUG]: Could not respond to message.

### ISSUE THREAD

**Issue by hy-yq** [Mintplex-Labs/anything-llm#2105]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

With the docker version installed in a foreign Linux environment, I can access anythingllm pages in China, and I can also configure LLM. After installing local ollama on a foreign server, errors will be reported when uploading documents and conversations after remote access. Dialog Times error: Could not respond to message.An error occurred while streaming response. network error. Are these problems related to the domestic export firewall or VPN? With the same configuration and environment, I used anythingllm deployed in China and everything worked fine.

### Are there known steps to reproduce?

:Could not respond to message.An error occurred while streaming response. network error.

**Comment by lijiajun325** [comment]
I have the same problem

**Comment by timothycarambat** [comment]
I presume you are using Ollama for both the LLM and Embedder provider? Do these errors occur on _embedding_ of the files after being uploaded?

**Comment by timothycarambat** [comment]
Closing as this is 100% a VPN or firewall issue, but I can help you debug where exactly that is for you in this thread.
