### ISSUE TITLE
[FEAT]: Make links (url's) in embedded chat clickable

### ISSUE THREAD

**Issue by troymroberts** [Mintplex-Labs/anything-llm#2107]
### What would you like to see?

Currently trying to use Anythingllm as a chatbot for an ecommerce store via the embed script. The bot reacts as appropriate and can supply a user with the store URL for a product that meets their criteria. However, the URL's in the embed chat aren't clickable.

I tried the same query in the normal non-embed workspace and the links are clickable as expected

**Comment by timothycarambat** [comment]
This is how links are formatted - you can specify in your system prompt to format them as markdown and they will be clickable. It is up to the LLM to format them correct or as plaintext
