### ISSUE TITLE
[BUG]: Anthropic Error:invalid_request_error messages: text content blocks must contain non-whitespace text

### ISSUE THREAD

**Issue by assortednuggets** [Mintplex-Labs/anything-llm#2108]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Latest desktop on Mac 1.62

previous version works perfectly

Anthropic default LLM and Chat LLM
GPT4o for agents
Below is the error now from Claude in main chat

Anthropic Error:invalid_request_error messages: text content blocks must contain non-whitespace text

**Comment by timothycarambat** [comment]
Look through your chat history log and find the offending response which is just whitespace and delete it and this error will go away in the interim for the chat thread it is blocking
