### ISSUE TITLE
[BUG]: Cannot find Bangla document uploaded to the Workspace

### ISSUE THREAD

**Issue by mayeenulislam** [Mintplex-Labs/anything-llm#2116]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I uploaded a markdown file to the Workspace:

<img width="1511" alt="File Screenshot at Aug 14 22-41-57" src="https://github.com/user-attachments/assets/6674819b-a2ac-482c-95f6-cb672dec3359">

Using Ollama and `gemma2:latest` (max tokens: 4096) I asked:

> @agent can you scrape the animals.md and summarize in bangla?

✅ Based on my CPU and RAM it took time, but responded with some text after summarization

I then thought to speed up the processing using Groq API. So I changed the settings of the Workspace to:

> LLM Provider: Groq
> Chat model: gemma2-9b-it
> Chat mode: Chat

Whereas the vector database shows a vector count 57

> Document similarity threshold: High
> Agent LLM Provider: Groq
> Agent Model: gemma2-9b-it

But with every query after setting Groq, it ❌ failed:

> @agent can you scrape the animals.md and summarize in bangla?
> @agent Summarize the “animals.md” file in Bangla

With a significant improvement in speed, it says that **it doesn't have any access to the file**.

<img width="1486" alt="Screenshot at Aug 14 22-51-55" src="https://github.com/user-attachments/assets/6050cfd6-a39c-4c66-9f81-9468622808ea">

I tried changing the Agent Model to Ollama:gemma2:2b, but it stays the same.

### Are there known steps to reproduce?

1. Make a Workspace
2. Upload a markdown file to the workspace
3. Use Ollama and gemma2:2b model
4. Ask to summarize the file
5. It will do it successfully
6. Add Groq API for both chat provider and agent provider
7. Ask to summarize the file again
8. It will fail finding the file

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/agent-not-using-tools

Not a bug, just the LLM being bad at creating valid tool calls. In fact, in that screenshot I dont even see the "thoughts" of the agent calling tools - did they never show up?

**Comment by mayeenulislam** [comment]
The thoughts were there. But couldn't find them later.
