### ISSUE TITLE
[BUG]: A JavaScript error occurred in the main process after update to 1.6.3 v

### ISSUE THREAD

**Issue by Milor123** [Mintplex-Labs/anything-llm#2128]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I am getting this bug after update to 1.6.3 desktop version, when try open a workspace:
![image](https://github.com/user-attachments/assets/461e7c2f-23f3-4948-9722-2d73142eca60)

Now my client keep freezing!! it need be fixed with urgency guys! 
Thank u very much!

**Comment by timothycarambat** [comment]
What OS are you on? Linux?

**Comment by timothycarambat** [comment]
Patched, download again from the bucket/installer script now

**Comment by Milor123** [comment]
> Patched, download again from the bucket/installer script now

thank u very much bro, love you !!!
