### ISSUE TITLE
[QUESTION]: Unable to upload files to a specific folder?

### ISSUE THREAD

**Issue by eric-shchiu** [Mintplex-Labs/anything-llm#2132]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I was able to create a folder and upload documents to the specific folder directly. However, recently, after a couple pull request, I am not able to do so anymore. Now, every time when I try to upload a document, it goes only to the "custom-documents" folder. I'm just wondering if there's anyway to fix this? Thanks!

**Comment by timothycarambat** [comment]
We have never had the ability to upload files directly into a subfolder in the file picker. You have always needed to create said folder, upload, and then move those into the desired folder.

This was with the exception of data connectors which do create their own folders

**Comment by computersrmyfriends** [comment]
On a user usability perspective, it would be easier to use only if we could upload files directly into specific folders I'm not sure why it was planned to be a 2 step process.

**Comment by MihailCosmin** [comment]
I had the same issue: [#2055](https://github.com/Mintplex-Labs/anything-llm/issues/2055#issuecomment-2271709393)

This keeps getting dismissed as irrelevant for some reason. But many consider this an important usability issue...
Maybe you guys should re-consider

**Comment by timothycarambat** [comment]
Its already marked as a feature request, not sure what else there is to do beyond that?

**Comment by timothycarambat** [comment]
Moved to #2235
