### ISSUE TITLE
[BUG]: Ubuntu 24.04 - docker 27.1.2  Cannot embed document, get network error trying to fetch resource

### ISSUE THREAD

**Issue by roninhockley** [Mintplex-Labs/anything-llm#2135]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Ubuntu 24.04 LTS desktop,  docker version 27.1.2

After uploading a document and adding it to my workspace, I click to Save and Embed, and I get this:

Error: NetworkError when attempting to fetch resource.

### Are there known steps to reproduce?

Start ollama and run llama3.1
use this docker run command:

export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d \
--cap-add SYS_ADMIN \
--network host \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm

Go to the anythingllm gui, select ollama for the llm. Keep everything else default.
Create a workspace
Upload a txt file, add to workspace. 
Click on Save and Embed.

**Comment by roninhockley** [comment]
Pretty sure there is more needed on the docker run command, as the app is unstable when I try to configure workspaces.

**Comment by timothycarambat** [comment]
>  the app is unstable when I try to configure workspaces.

What does this mean?

> Error: NetworkError when attempting to fetch resource.

Ollama serve is not running and/or your connection to Ollama is not correct:
- Are you using localhost in docker? 
https://docs.useanything.com/ollama-connection-troubleshooting
- Are you using an embedding model for embedding - sometimes people set `llama3` as their embedder model and obviously that cannot work
