### ISSUE TITLE
[BUG]: Based on the knowledge base inquiry about product materials, the robot replies that it cannot find the product.

### ISSUE THREAD

**Issue by noiceman** [Mintplex-Labs/anything-llm#2138]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I uploaded a 10K document: it contains Product 1, Product 2, and Product 3. After vectorizing several times, each time the robot randomly told me that one of the products does not exist.

### Are there known steps to reproduce?

uploaded a 10K document: it contains Product 1, Product 2, and Product 3，then quest about product

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/llm-not-using-my-docs

That is not surprising since that is not how RAG works! The doc above explains how the system works, how to tune it to your use case, and why blinding uploading 10K documents about something is not going to magically work with perfect recall!
