### ISSUE TITLE
[BUG]: update-pin API call returns "401 Error: Invalid auth token" even with valid API key

### ISSUE THREAD

**Issue by aka-collab** [Mintplex-Labs/anything-llm#2140]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

In both my code implementation and the Swagger UI for using the API, the POST method update-pin always returns an invalid auth token error even when the token is valid, not updating the document pin status. I've made sure I was using the right workspace slug and document Json filename. The Swagger UI also shows the error code 401 as undocumented, if that means anything to the dev team:
![image](https://github.com/user-attachments/assets/acbadbf6-0458-4016-ab65-fac9264bdf98)

**Comment by timothycarambat** [comment]
You need to use `Authorization: Bearer <KEY>` for your Post request and the endpoint works so we are unable to replicate on `latest`

Possible issues are:
- API key is wrong (or has spaces at the end?)
- Wrong header when using Postman/code/POST
- Did not put the key in the `Authorization` box at the top of the Swagger UI & save so you **can use** the swagger UI.

**Comment by aka-collab** [comment]
Figured it out, it was a documentation issue. The swagger docs are missing the 'v1' in the url only for the update-pin method:
![image](https://github.com/user-attachments/assets/126bf10c-f80a-4f51-bf87-cdcc88ecfb65)
