### ISSUE TITLE
[BUG]: gemini-1.5-pro-exp-0801 API error

### ISSUE THREAD

**Issue by lukemauldinks** [Mintplex-Labs/anything-llm#2142]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Reference https://github.com/Mintplex-Labs/anything-llm/issues/2081
On Anything LLM 1.6.3 on OSX still receiving the same error message while accessing `gemini-1.5-pro-exp-0801`.

Error:
`[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro-exp-0801:streamGenerateContent?alt=sse: [404 Not Found] models/gemini-1.5-pro-exp-0801 is not found for API version v1, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.`

### Are there known steps to reproduce?

1. Install Anything LLM 1.6.3.
2. Setup Gemini API workspace targeting `gemini-1.5-pro-exp-0801`
3. Send a chat message

**Comment by timothycarambat** [comment]
Already done via https://github.com/Mintplex-Labs/anything-llm/pull/2031
https://github.com/Mintplex-Labs/anything-llm/issues/2043#issuecomment-2269438798

**Comment by lukemauldinks** [comment]
I don't understand because the bug is still present in Anything LLM 1.6.3 which was released after the fix.

**Comment by timothycarambat** [comment]
Sorry, Yes,  it would be in the next update, that is what I was trying to show. The changelog for 1.6.3 only shows we added support for STT, it included no bug fixes or other updates

https://docs.anythingllm.com/changelog/v1.6.3
