### ISSUE TITLE
[BUG]: Cannot find a valid ref in desktop/linux_installer.sh

### ISSUE THREAD

**Issue by ali0une** [Mintplex-Labs/anything-llm#2147]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hi there!

Trying to get the latest 1.6.4 the download link for Linux AppImage is broken.
Page sends 404 error.

### Are there known steps to reproduce?

Go to https://docs.useanything.com/installation/desktop/linux#install-using-the-installer-script

Click on the link :

> You can view the raw script contents [here](https://github.com/Mintplex-Labs/anything-llm/blob/desktop/linux_installer.sh).

**Comment by timothycarambat** [comment]
Oh that is because we renamed `desktop` to `desktop-legacy`. Just swapped it back - works now!
