### ISSUE TITLE
[FEAT]: Integrate Perplexity into Search Services

### ISSUE THREAD

**Issue by spyroskotsakis** [Mintplex-Labs/anything-llm#2152]
### What would you like to see?

Hello

Including Perplexity as an option in web search services would greatly improve the quality of the responses.

Thank you!

**Comment by timothycarambat** [comment]
We already support perplexity. Just use their models that have `-online` in the name. There is not Perplexity search API
https://docs.perplexity.ai/reference/post_chat_completions
