### ISSUE TITLE
[BUG]: AnythingLLM Desktop 1.6.4 on Windows: Kill ollama-llama-server.exe process after closing application.

### ISSUE THREAD

**Issue by mtomas7** [Mintplex-Labs/anything-llm#2154]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I noticed that after closing app, Ollama (together with loaded model) remains in the memory, in my case using 16 GB of RAM.

Thank you!

**Comment by timothycarambat** [comment]
This will be resolved in the 1.6.5 release - it is currently patched in the development build 👍
