### ISSUE TITLE
[FEAT]: AWS Bedrock temperature adjustment

### ISSUE THREAD

**Issue by ytjhai** [Mintplex-Labs/anything-llm#2155]
### What would you like to see?

I'm currently using the AWS Bedrock feature and it looks like bedrock supports adjusting the temperature through their API. It'd be helpful to have this in the settings since some models operate at different optimum temperatures than others (ex: Mistral large has a different "optimum" temperature than Llama 3.1)

**Comment by timothycarambat** [comment]
We do support temperature!
https://github.com/Mintplex-Labs/anything-llm/blob/f7756d475812989ff3b78cd36b40250ed4539b3c/server/utils/AiProviders/bedrock/index.js#L179

You can set it per-workspace in the workspaces `Chat Settings` (scroll to bottom)
<img width="842" alt="Screenshot 2024-08-20 at 2 08 33 PM" src="https://github.com/user-attachments/assets/bb39289e-cac4-4f13-b261-973c02e93a14">

**Comment by ytjhai** [comment]
Ah I see it! Thanks for the quick response!
