### ISSUE TITLE
[BUG]: API: Example password for creating new users is too short

### ISSUE THREAD

**Issue by FaRunge** [Mintplex-Labs/anything-llm#2170]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![grafik](https://github.com/user-attachments/assets/f9bb9a14-2afa-467c-92d7-b3cd3cb5c1af)
the example password "hunter2" is too short. All passwords are required to have 8 signs. Use "hunter21" instead. ;)

**Comment by timothycarambat** [comment]
While true...
- You should never use the example for a password in the documentation
- This setting is actually configurable by the admin via the ENV settings
https://github.com/Mintplex-Labs/anything-llm/blob/master/server/models/user.js#L237
