### ISSUE TITLE
[Question]: Installed Llava with Ollama but no way to select it.

### ISSUE THREAD

**Issue by venturaEffect** [Mintplex-Labs/anything-llm#2174]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I installed the multimodal Llava LLM as it shows on settings. Saved after installing but can't select it. Just shows the three default llms but nothing about Llava.

### Are there known steps to reproduce?

Just went to settings and installed from the llms that you can choose from Ollama section in AnythingLLM, waited until installation was finnished and clicked saved. Went to the workspace settings and selected Ollama but when trying to choose the multimodal Llava model it wasn't there. Just the three it shows by default.

How to solve it?

**Comment by timothycarambat** [comment]
The built-in ollama is not the same as your system ollama (for good reason - we don't want to mess with your local Ollama install).

What screen are you looking at, the only "three default LLMs" are on onboarding so as to not overwhelm people with selections. You can also show all to see all the available models.

**Comment by venturaEffect** [comment]
It is on the workspace settings where I select the Agent the LLM. There, I select the Ollama option as the Llava model I installed from the options available in the general settings is available from AnythinLLM (not installed by a local .gguf LLM).

So basically after waiting to install it and save the changes it should be available to choose on the Workspace settings. But there is just llama, mistral and one more. But definitely not the Llava installed. And there are no more options to select other LLMs on the workspace settings.

Appreciate your help.

**Comment by timothycarambat** [comment]
No, that is where the confusion is. When you installed llava llama from the layout that looks like this
<img width="1625" alt="Screenshot 2024-08-25 at 1 33 03 PM" src="https://github.com/user-attachments/assets/1e5d8005-611f-4899-95e8-746fdc9a1d13">
 or
 <img width="1484" alt="Screenshot 2024-08-25 at 1 33 45 PM" src="https://github.com/user-attachments/assets/d384e3d5-b025-4541-8b12-79201845f0de">

This is not the same as Ollama install separately on your computer, which it sounds like it is. Models installed or downloaded there will not just appear in your dropdown, they arent the same provider.

The default AnythingLLM provider does not support per-workspace models like the external Ollama connection does at this time. You are basically using a totally different provider. If you want to use `Ollama + llava llama` but only in a specific workspace you need to do `ollama pull llava-llama3` and it will appear in the dropdown for that specific workspace.

**Comment by venturaEffect** [comment]
Yes, I didn't installed separately on my Ollama on the computer. I try to use from directly choosing it from AnythingLLM but, after being active and save the changes I can not select it. It just shows the three options by default.

I repeat, it is selected and being active IN ANYTHINGLLM not trying to add it from Ollama outside of AnythingLLM. But even like this, there is no way to select it.

Appreciate your time and hope it is clear what I mean.
