### ISSUE TITLE
[FEAT]: User account items, editing, and management functions are enhanced

### ISSUE THREAD

**Issue by hejp001** [Mintplex-Labs/anything-llm#2177]
### What would you like to see?

Can I add a nickname to a user account? When a user or administrator edits a user account, the user name cannot be edited (once it is determined). The user nickname can be modified. Because within an organization we need to identify users by their nicknames and real names. In addition, can I add the function of importing users in batches?

**Comment by timothycarambat** [comment]
Users only have usernames, passwords, and roles. There are no other identifiers aside from their database db.

The admin & user can both edit a username after it is set. The admin from the users dashboard and the user from their account settings.

You can bulk create users via the API. There is a user creation endpoint.
