### ISSUE TITLE
[BUG]Docker(windows desktop)  container stopped unexpectedly

### ISSUE THREAD

**Issue by hejp001** [Mintplex-Labs/anything-llm#2178]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When the workspace uses a visual model, the system functions normally if the system default visual model is used, but if the system default model is not a visual model and the workspace sets the visual model separately, the Docker container stops unexpectedly.

**Comment by hejp001** [comment]
The visual model used by my system and workspace is MiniCPM-v-2 _ 6-q5-k_m.

**Comment by timothycarambat** [comment]
There is not enough information here to help debug this issue:
- What provider are you using to run this model. Both for workspace and system level.
- How did you load this model in?
- The logs from the docker container on crash are required here to help further debug
