### ISSUE TITLE
[DOCS]: How to remove orange "You have enough data to finetune" banner?

### ISSUE THREAD

**Issue by ericthomas1** [Mintplex-Labs/anything-llm#2185]
### Description

Users are getting confused by this banner. Is there a way to turn if off?

**Comment by timothycarambat** [comment]
Click dismiss, it should only appear for admins
https://github.com/Mintplex-Labs/anything-llm/blob/fc6d7359b683a9e3d4f671547ec4ecaff1839453/frontend/src/models/experimental/fineTuning.js#L88
