### ISSUE TITLE
[BUG]: Milvus not returning text in chunks

### ISSUE THREAD

**Issue by shatfield4** [Mintplex-Labs/anything-llm#2186]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Embed any document into the latest version of Milvus standalone docker image and when asking questions to the LLM, we receive chunks from the vector db but with no text content.

**Comment by wolfganghuse** [comment]
Hello, seems i am hitting similar in #2862 
@timothycarambat was this closed because of no feedback ?
