### ISSUE TITLE
[BUG]: Unable to Upload Folders

### ISSUE THREAD

**Issue by JKDevz** [Mintplex-Labs/anything-llm#2188]
### How are you running AnythingLLM?

AnythingLLM desktop app

##### Technical Stuff:
- Windows 11
- Desktop
- AnythingLLM v1.6.4

### What Happened?
Uploading Folders from my NAS on my local Network (in File Explorer), or from my local Drive does not work.

**What I Expected:**
I understand that when uploading documents for use in Chat-With-Docs you should be able to simply drag-and-drop a file or folder with files, and even subfolders, into the document upload space, and then all files would then be processed. 

**What Happened:**
Nothing, to be quite frank. Not even a Folder that only has files in it works. It doesn't even seem to recognise that I have attempted to upload files, even with a single file in the Folder. This occurs when attempting to drag-and-drop any folder from either my NAS or local Drives.

Drag-and-drop does work for files without the inclusion of a Folder.

Would appreciate any help or assistance. I've been struggling with this issue for a very long time now.

### Are there known steps to reproduce?

1. Open up AnythingLLM and LM Studio
2. Setup AnythingLLM to use LM Studio LLM Model
3. Drag and drop a folder with SubFolders from a device on your Local Network (from File Explorer)

**Comment by timothycarambat** [comment]
This is intentional behavior, but is related to #1177 feature request 👍

**Comment by JKDevz** [comment]
Ah, wonderful! Glad to know it's on your radar. Looking forward to the fix!
