### ISSUE TITLE
[UI/UX]: White bar under messages (User/AI)

### ISSUE THREAD

**Issue by ghost** [Mintplex-Labs/anything-llm#2190]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Everything works fine but this weird white bar shows up under all my messages not sure if this is a bug on my end or I didn't configure it properly but just checking if anyone else had this issue.
<img width="541" alt="Screenshot 2024-08-28 at 12 11 38 PM" src="https://github.com/user-attachments/assets/ca955282-0ea4-468d-8c80-4c7ba9e766d2">

AnythingLLM - Docker (Unraid)

**Comment by shatfield4** [comment]
What browser are you using here where this is happening? I cannot replicate this on Chrome. Are you running the latest docker image?

**Comment by mybr4inhurts** [comment]
I have this issue as well with the **latest anythingllm docker image** (pulled a couple of minutes ago). Happens only in Chrome browsers (Chrome, Chromium, Edge) but not in Firefox.

**Comment by timothycarambat** [comment]
What OS? @mybr4inhurts

**Comment by mybr4inhurts** [comment]
We tested this with Windows 10, Windows 11 and Ubuntu 24.04 (x86-64)

**Comment by oatmealm** [comment]
Same here. Chromium on Linux with a docker image running on remote macos, latest build available today.
![image](https://github.com/user-attachments/assets/896660ac-f89f-4690-8521-151cc26926aa)
