### ISSUE TITLE
[BUG]: 'Restrict Requests from Domains' Feature Not Working

### ISSUE THREAD

**Issue by bentwnghk** [Mintplex-Labs/anything-llm#2194]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

The 'Restrict Requests from Domains' feature does not seem to work. When I click the save button, the domain is reset to blank.

![329763427-916a15bf-58cb-4131-9721-e8b8aa5dc7a6](https://github.com/user-attachments/assets/fa8591a4-ef62-42fb-80d6-e2f31124eec1)

After clicking the save button:
![329763384-341172fb-8877-4843-9991-d9c60ef65dbe](https://github.com/user-attachments/assets/7f549d79-3f86-4b29-a565-8dd2942cfd37)

Have I missed anything or configured anything incorrectly?

**Comment by timothycarambat** [comment]
An annoying ui quirk, but after typing press `Enter` focusing off the input does not submit the input.

_not submitted_
<img width="719" alt="Screenshot 2024-08-29 at 1 59 19 PM" src="https://github.com/user-attachments/assets/3a00d98e-3440-4a29-887e-526feca9c36e">

_parse and validated - will submit_
<img width="699" alt="Screenshot 2024-08-29 at 1 59 23 PM" src="https://github.com/user-attachments/assets/1d61d7cc-984a-4606-bded-a0114de52b6c">
