### ISSUE TITLE
[FEAT]: Why refuse to have a button to delete all threads?

### ISSUE THREAD

**Issue by rezmeplxrf** [Mintplex-Labs/anything-llm#2196]
### What would you like to see?

We already have a button to delete all chat history but this won't remove the empty threads after deletion.
I have searched issues here and found quite some people already requested this feature but they were all closed without any meaningful replies. Is there a reason not to do this?

I can easily build a script to delete all threads but it seems stupid not to have this feature.

**Comment by timothycarambat** [comment]
Hold control and you can quickly select threads and click X + delete all threads.

The issue is closed because it exists. The associated PRs on those issues link to that as well
