### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by straydog-1212** [Mintplex-Labs/anything-llm#2198]
### What would you like to see?

Add a way to allow default/manager users (in multi-user mode)  to upload files without making them a manager. makes it easier for a user who has access to only one or two workspaces to upload files relevant to their work in their workspace without giving them access to every workspace or making them admin.

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/1787
