### ISSUE TITLE
MacOS: yarn dev:frontend issues with vite.config.js, failed to load config

### ISSUE THREAD

**Issue by ssbob** [Mintplex-Labs/anything-llm#22]
Have NPM, Yarn installed. Yarn dev:server runs without issue, but yarn dev:frontend results in:

❯ yarn dev:frontend
yarn run v1.22.19
$ cd frontend && yarn start
warning package.json: No license field
$ vite --open
failed to load config from /Users/<username>/Developer/anything-llm/frontend/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /Users/<username>/Developer/anything-llm/frontend/vite.config.js.timestamp-1686430326577-c946bfcc5297d.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:781:9)
    at moduleResolve (node:internal/modules/esm/resolve:830:20)
    at defaultResolve (node:internal/modules/esm/resolve:1035:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:269:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:153:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Have tried removing dir and re-cloning, as well as what I could find "googling" around. Any ideas?

**Comment by mkammes** [comment]
I ran into this as well (macOS, M1, 12.6.3).  I had to manually install the dependencies one at a time.

**Comment by jdingus** [comment]
> I ran into this as well (macOS, M1, 12.6.3). I had to manually install the dependencies one at a time.

@mkammes how exactly do you load the dependencies one at a time?  Do you still use yarn?

**Comment by timothycarambat** [comment]
@ssbob did you go to `cd frontend` and then `yarn install`? That will install all the dependencies.

Dont forget to do the same for `server`
