### ISSUE TITLE
[FEAT]: Add Bitbucket / Git repo connector

### ISSUE THREAD

**Issue by yncki** [Mintplex-Labs/anything-llm#2203]
### What would you like to see?

Why limit only to github ?

**Comment by timothycarambat** [comment]
We support GitHub and GitLab, we will have loadable data connectors and you can build the ones you explicitly use. The GitHub and GitLab connectors were highly requested, that is why.

**Comment by lbklb** [comment]
Many users might benefit from having a self-hosted option that's privacy-focused. Thank you for considering this feature!
