### ISSUE TITLE
[FEAT]: integrate `autogen-studio` with this for agents otchestration

### ISSUE THREAD

**Issue by hemangjoshi37a** [Mintplex-Labs/anything-llm#2205]
### What would you like to see?

please integrate `autogen-studio` with this for agents otchestration :    https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-studio

**Comment by timothycarambat** [comment]
This is written in python, it cannot be added into the app as it is not compatible in desktop environment even if it could be bundled into the docker image

**Comment by timothycarambat** [comment]
You can port an agent skill with this PR when merged: 
https://github.com/Mintplex-Labs/anything-llm/pull/2202
