### ISSUE TITLE
[BUG]: `GitHub` data connector giving error even if the repo download is successful

### ISSUE THREAD

**Issue by hemangjoshi37a** [Mintplex-Labs/anything-llm#2206]
### How are you running AnythingLLM?

Docker (local)

### What happened?

in the documents section  `GitHub` data connector giving error even if the repo download is successful

**Comment by timothycarambat** [comment]
Without any logs, screenshots or  more information there is no action we can take on a report like this. Please update this issue to include screenshots, container logs, or other pieces of information that can help us locate the issue.

When that information exists and there is something we can action on, ill reopen the issue.

**Comment by hemangjoshi37a** [comment]
Well there are no logs as it is happening in the gui portion.

**Comment by timothycarambat** [comment]
You issues indicated 
> Docker (local)

So there are logs in the docker container, that is what I am requesting
