### ISSUE TITLE
[FEAT]: edit the chat message and retry button on output message 

### ISSUE THREAD

**Issue by hemangjoshi37a** [Mintplex-Labs/anything-llm#2207]
### What would you like to see?

i want you to add two buttons . on the user message button there should be edit button to edit the already sent message and resubmit it . 
also in the output there should be a retry button to retry the output so that the output will be again generated .

**Comment by timothycarambat** [comment]
Both of these buttons already exist in the UI. Hover over the user/AI message as you would on other UI's

<img width="329" alt="Screenshot 2024-09-03 at 2 00 45 PM" src="https://github.com/user-attachments/assets/2587fd74-0dd7-44e9-bd2a-153888ac9d47">
<img width="1114" alt="Screenshot 2024-09-03 at 2 00 49 PM" src="https://github.com/user-attachments/assets/e47f3fac-76ed-4282-9271-c3a2027249a3">
