### ISSUE TITLE
[FEAT]: What is the process for setting up a proxy server/proxy client for anythingllm?

### ISSUE THREAD

**Issue by JerryXu2023** [Mintplex-Labs/anything-llm#2209]
### What would you like to see?

What is the process for setting up a proxy server/proxy client for anythingllm?

**Comment by JerryXu2023** [comment]
I’m using the Windows desktop version of Anythingllm. How do I set up proxy settings?

**Comment by timothycarambat** [comment]
We do not currently support proxying every request in the app for desktop (https://github.com/Mintplex-Labs/anything-llm/issues/1228). You could proxy the docker image though since you can put Nginx or something else in front of the docker container.
