### ISSUE TITLE
please help with "Error: Could not validate login"

### ISSUE THREAD

**Issue by jignnsd** [Mintplex-Labs/anything-llm#223]
I was using multi-user of anything-llm.
I made some changes to the .env file
then run the: docker-compose up -d --build
When docker network and container are created and started, and I get in the "Error: Could not validate login"
I'm running the docker in my server at port 3001, and using a public ip from outside.

Please help on this, many thanks
![Screenshot 2023-08-23 at 11 17 43 PM](https://github.com/Mintplex-Labs/anything-llm/assets/90939257/cedc11d7-1988-4133-86c1-5f1486e05078)

**Comment by timothycarambat** [comment]
Changes made in docker to not write to the host system database, but changes in the host DB will appear in docker. There is not enough information to answer the question here.

If the `JWT_TOKEN` was changed in the env then the stored passwords wont work as they are hashed and salted with that key - so if you change it all logins would become invalid.

**Comment by jignnsd** [comment]
Many thanks @timothycarambat ill check it and get back with more info.

**Comment by jignnsd** [comment]
I didn't have the jwt_token with any password. I did a new installation with that information. It is working now, will see what happened in the event of a rebuilt, many thanks @timothycarambat
