### ISSUE TITLE
[FEAT]: Separated url / address for ollama workspaces

### ISSUE THREAD

**Issue by mallory303** [Mintplex-Labs/anything-llm#2238]
### What would you like to see?

I think separated url / address settings per workspace for ollama workspaces will be a nice feature. I have multiple PCs with ollama servers, but I can access only one with anything-llm.

**Comment by timothycarambat** [comment]
Agreed, something we have conceptualized how to accomplish but need to do.

See comment https://github.com/Mintplex-Labs/anything-llm/issues/2024#issuecomment-2265861249
