### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by obeiip** [Mintplex-Labs/anything-llm#2241]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

按照https://docs.anythingllm.com/installation/desktop/linux中的Install using Docker安装

### Are there known steps to reproduce?

[36m[collector][0m [32minfo[39m: Collector hot directory and tmp storage wiped!
[36m[collector][0m [32minfo[39m: Document processor app listening on port 8888
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 493ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

SQLite database anythingllm.db created at file:../storage/anythingllm.db

23 migrations found in prisma/migrations

Applying migration `20230921191814_init`
Applying migration `20231101001441_init`
Applying migration `20231101195421_init`
Applying migration `20231129012019_add`
Applying migration `20240113013409_init`
Applying migration `20240118201333_init`
Applying migration `20240202002020_init`
Applying migration `20240206181106_init`
Applying migration `20240206211916_init`
Applying migration `20240208224848_init`
Applying migration `20240210004405_init`
Applying migration `20240216214639_init`
Applying migration `20240219211018_init`
Applying migration `20240301002308_init`
Applying migration `20240326231053_init`
Applying migration `20240405015034_init`
Applying migration `20240412183346_init`
Applying migration `20240425004220_init`
Applying migration `20240430230707_init`
Applying migration `20240510032311_init`
Applying migration `20240618224346_init`
Applying migration `20240821215625_init`
Applying migration `20240824005054_init`

The following migrations have been applied:

migrations/
└─ 20230921191814_init/
└─ migration.sql
└─ 20231101001441_init/
└─ migration.sql
└─ 20231101195421_init/
└─ migration.sql
└─ 20231129012019_add/
└─ migration.sql
└─ 20240113013409_init/
└─ migration.sql
└─ 20240118201333_init/
└─ migration.sql
└─ 20240202002020_init/
└─ migration.sql
└─ 20240206181106_init/
└─ migration.sql
└─ 20240206211916_init/
└─ migration.sql
└─ 20240208224848_init/
└─ migration.sql
└─ 20240210004405_init/
└─ migration.sql
└─ 20240216214639_init/
└─ migration.sql
└─ 20240219211018_init/
└─ migration.sql
└─ 20240301002308_init/
└─ migration.sql
└─ 20240326231053_init/
└─ migration.sql
└─ 20240405015034_init/
└─ migration.sql
└─ 20240412183346_init/
└─ migration.sql
└─ 20240425004220_init/
└─ migration.sql
└─ 20240430230707_init/
└─ migration.sql
└─ 20240510032311_init/
└─ migration.sql
└─ 20240618224346_init/
└─ migration.sql
└─ 20240821215625_init/
└─ migration.sql
└─ 20240824005054_init/
└─ migration.sql

All migrations have been successfully applied.
┌─────────────────────────────────────────────────────────┐
│ Update available 5.3.1 -> 5.19.1 │
│ Run the following to update │
│ npm i --save-dev prisma@latest │
│ npm i @prisma/client@latest │
└─────────────────────────────────────────────────────────┘
[36m[backend][0m [32minfo[39m: [36m[EncryptionManager][0m Self-assigning key & salt for encrypting arbitrary data.
[36m[backend][0m [32minfo[39m: [32m[TELEMETRY ENABLED][0m Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
[36m[backend][0m [32minfo[39m: prisma:info Starting a sqlite pool with 5 connections.
[36m[backend][0m [32minfo[39m: [32m[TELEMETRY SENT][0m {"event":"server_boot","distinctId":"c70e1268-675f-42ea-a0df-ea6981fb54e6","properties":{"commit":"--","runtime":"docker"}}
[36m[backend][0m [32minfo[39m: [36m[CommunicationKey][0m RSA key pair generated for signed payloads within AnythingLLM services.
[36m[backend][0m [32minfo[39m: [36m[EncryptionManager][0m Loaded existing key & salt for encrypting arbitrary data.
[36m[backend][0m [32minfo[39m: Primary server in HTTP mode listening on port 3001
[36m[backend][0m [32minfo[39m: [36m[BackgroundWorkerService][0m Feature is not enabled and will not be started.

[36m[collector][0m [32minfo[39m: Collector hot directory and tmp storage wiped!
[36m[collector][0m [32minfo[39m: Document processor app listening on port 8888
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 487ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db

**Comment by timothycarambat** [comment]
> unable to open database file: ../storage/anythingllm.db

Sounds like you are running the docker container without using the official command which proactively sets the ENV to the correct place to prevent this issue.

```shell
 export STORAGE_LOCATION="/var/lib/anythingllm" && \
 mkdir -p $STORAGE_LOCATION && \
 touch "$STORAGE_LOCATION/.env" && \
 docker run -d -p 3001:3001 \ # expose on port 3001 (can be any host port)
 --cap-add SYS_ADMIN \
 -v ${STORAGE_LOCATION}:/app/server/storage \
 -v ${STORAGE_LOCATION}/.env:/app/server/.env \
 -e STORAGE_DIR="/app/server/storage" \
 mintplexlabs/anythingllm:master
 ```

also for `export STORAGE_LOCATION="/var/lib/anythingllm"` Make sure you have read+write permissions to this directory for the docker user!
`chmod -R 777 /var/lib/anythingllm` to quickly be sure
