### ISSUE TITLE
[BUG]: Agent auto closed

### ISSUE THREAD

**Issue by albertmx** [Mintplex-Labs/anything-llm#2248]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image](https://github.com/user-attachments/assets/d507460a-1f6b-4875-942a-ccdb5e6c30f7)
![image](https://github.com/user-attachments/assets/3b7eccc3-1329-4f5d-b1fa-b5bf0f3f88e5)
![image](https://github.com/user-attachments/assets/a63f4270-8e9d-413e-b941-51f75f9125c1)
I pull AnythingLLM via docker for the latest version. Setup Ollama locally and connected to AnythingLLM. The normal conversation has no issue. However, @agent always show completed whenever and whatever I try to call it. Is there an issue for AnythingLLM running via Docker?

### Are there known steps to reproduce?

Create new workspace, new thread and try to call @agent with any instructions, it will complete without allowing me to integrate anything.

**Comment by timothycarambat** [comment]
You need to pull your `docker logs <container_id>` - most of the time it has to do with how you are running/accessing the container and the websocket connection hanging up.

Pull the logs when the error occurs and it should tell us more - closing until a reproducible bug is found

**Comment by albertmx** [comment]
> You need to pull your `docker logs <container_id>` - most of the time it has to do with how you are running/accessing the container and the websocket connection hanging up.
> 
> Pull the logs when the error occurs and it should tell us more - closing until a reproducible bug is found

![Uploading 1.jpg…]()
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()
![Uploading 4.jpg…]()

The Logs seems not helpful as it only mention sent chat.

Below is my installation command:
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d --restart=always --network=host --name AnythingLLM --cap-add SYS_ADMIN -v ${STORAGE_LOCATION}:/app/server/storage -v ${STORAGE_LOCATION}/.env:/app/server/.env -e STORAGE_DIR="/app/server/storage" -p 3001:3001 mintplexlabs/anythingllm

Then I use nginx to redirect the port:
#Edit the Nginx conf file
server {
    listen 80;
    location / {
        proxy_pass http://my internal ip address:3001;
    }
}

I try a few times freshly install my ubuntu server, docker and then AnythingLLM, @agent had this same issue.
Thank you very much.

**Comment by albertmx** [comment]
Let me attach the image again here:
![1](https://github.com/user-attachments/assets/32d2dbfd-8233-4fc2-99b9-e201081b5a4a)
![2](https://github.com/user-attachments/assets/7341da48-42aa-4057-b67a-a0b711402193)
![3](https://github.com/user-attachments/assets/e040440b-cc72-4938-91c8-0a8d18ae474d)
![4](https://github.com/user-attachments/assets/e1115a49-357a-4850-92d1-bd694e61f1f0)

**Comment by timothycarambat** [comment]
Ah! the same `websocket` proxy config for Nginx catching people again!
https://github.com/Mintplex-Labs/anything-llm/issues/1379#issuecomment-2338983228

example block to add
```
 # Enable websocket connections for agent protocol.
   location ~* ^/api/agent-invocation/(.*) {
      proxy_pass http://0.0.0.0:3001;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
   }
```

**Comment by albertmx** [comment]
Hi @timothycarambat,
Yes it works. Thank you very much : )
