### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by soturiBerg** [Mintplex-Labs/anything-llm#2249]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Good afternoon! Just started with a fresh install of AnythingLLM, downloaded and activated the Llama3.1 8B model and tried to prompt it but keep receiving the following error: "llama runner process has terminated: CUDA error".

I have not been able to find any posts on the web regarding the exact same error. Is there anything I can do to fix this? Note: I have been able to get this model to work in a different tool called GPT4all, so it should work.

extra device info:

Windows 10, using latest installation version of AnythingLLM
GPU = AMD 6650XT

![Screenshot (556)](https://github.com/user-attachments/assets/cadf4375-640e-4438-80ab-1d80e711e1bd)

**Comment by timothycarambat** [comment]
> GPU = AMD 6650XT

We dont currently ship the ROCM bindings for AMD cards (>1GB) so instead of trying to patch this in the app, which will be frustrating you can install [Ollama](https://ollama.com) and connect to _that_ as an external LLM.

Not ideal, we know about this bug though and it is tracked elsewhere and will be patched soon

**Comment by ojsl1** [comment]
>
> We dont currently ship the ROCM bindings for AMD cards (>1GB) so instead of trying to patch this in the app, which will be frustrating you can install [Ollama](https://ollama.com) and connect to _that_ as an external LLM.
> 
> Not ideal, we know about this bug though and it is tracked elsewhere and will be patched soon

Where exactly is it tracked currently, and is it implemented yet (after a year)?

**Comment by timothycarambat** [comment]
It has been live for almost a year now. Since like 1.2.x IIRC
