### ISSUE TITLE
[BUG]: does not work : error cannot select a model

### ISSUE THREAD

**Issue by gilluc** [Mintplex-Labs/anything-llm#2252]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

drop down list of models is empty
cannot select a model
![dropdown list is empty](https://github.com/user-attachments/assets/49a29b18-0fd3-4d0f-aa3e-0f79f253f528)
![chat error](https://github.com/user-attachments/assets/e8ae39dd-e000-4360-8e11-7e165b2ad8c2)

### Are there known steps to reproduce?

first install  of desktop app on windows
i went to space settings trying to complete settings
because first chat gave an error

**Comment by timothycarambat** [comment]
Error message shows the issue - Please go to the LLM settings for the _system_:
https://docs.anythingllm.com/setup/llm-configuration/overview#system-llm
https://docs.anythingllm.com/setup/llm-configuration/local/built-in

Pick the model you wish to use and ensure that the default is running. 

For system what do you have as the LLM - this might explain why the dropdown is not populating.
