### ISSUE TITLE
[FEAT]: Ability to scroll up and read while the response is streaming

### ISSUE THREAD

**Issue by MorganMarshall** [Mintplex-Labs/anything-llm#2253]
### What would you like to see?

I think users would really like to be able to scroll up and read while the response is streaming.

**Comment by MorganMarshall** [comment]
Oh I see. My apologies I didn't catch it. Thanks for the response

**Comment by 2hy6v** [comment]
This is (at least for us in the selfhosted browser version) 
not working as intended.
You can disable the auto scroll, if you send the prompt while not being scrolled to the very bottom of the page. 
But if you are scrolled to the bottom, which is probably the default when you write a prompt, then you can not (most of the times) "escape" the autoscroll and scolling up just pushed you down again.
Also if you are not "trapped" in the auto scroll and read a part of the answer that has already been streamed, then you sometimes scroll too far down and end up in the "scroll trap" which you can not escape.
AND the whole thing is not deterministic meaning sometimes you can scroll and escape but most of the times you can not.

**Comment by MorganMarshall** [comment]
2hy6v, I think this is why I've noticed it on and off, thanks

**Comment by timothycarambat** [comment]
@shatfield4

**Comment by justme409** [comment]
yeh this needs to be fixed
