### ISSUE TITLE
[FEAT]: Azure OpenAI 4o on Chat Model Token Limit

### ISSUE THREAD

**Issue by kirkjaa** [Mintplex-Labs/anything-llm#2264]
### What would you like to see?

Would like to be able to select Azure OpenAI 4o on Chat Model Token Limit drop box, please. Since the latest one we can select is still GPT4 turbo 128,000

**Comment by timothycarambat** [comment]
That is simply a label, but the value is correct. Will update the label for ease of use rn
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4o-and-gpt-4-turbo
