### ISSUE TITLE
[BUG]: [Desk 1.6.5] Agent skills  won't save after set search provider and save.

### ISSUE THREAD

**Issue by Richter03** [Mintplex-Labs/anything-llm#2271]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I set agent model then set up agent skill.
![image](https://github.com/user-attachments/assets/eff85b87-d0a4-4253-9198-2dd128aa8dde)

However when I try to do web search I got this error.
![image](https://github.com/user-attachments/assets/9c772f33-64e5-4952-9598-fc110b5d07c9)

When I go back and check I found out it not save.
![image](https://github.com/user-attachments/assets/ae412fc5-103f-4a07-b765-e4b4d885c0e5)

### Are there known steps to reproduce?

Just go to Agent Skills, Web Search topic and set search provider then save and click on other agent skills topic than move back to web search topic again and you will find it back to non select option.

**Comment by maciejdzierzek** [comment]
Manually add: /plugins/agent-skills to in the "storage" directory. It works.

**Comment by Richter03** [comment]
Sadly, it not work for me.
![image](https://github.com/user-attachments/assets/18cbedab-ff9d-4cba-844d-bfc3b015120a)

**Comment by timothycarambat** [comment]
will be in 1.6.6 - if on prior version yes, creating the folder manually will work

**Comment by ernexto** [comment]
bug still present on 1.6.6

**Comment by timothycarambat** [comment]
@ernexto I am unable to replicate this on 1.6.6, are you saying toggling skills is not saving? not custom skills, just the others

**Comment by ernexto** [comment]
@timothycarambat 

1 - I go here and activate the web search agent skill
![01](https://github.com/user-attachments/assets/5c19b513-eadf-4de2-8387-199de7c9c28b)

2 - I choose the provider, insert data and click save
![02](https://github.com/user-attachments/assets/9cb21fb0-15c7-448e-aa8f-47202605c785)

3 - I exit this screen and go in another menu, then if I come back to agent skills-web search it appears like this. nothing is saved
![3](https://github.com/user-attachments/assets/eac84e14-6bc8-40c7-b44a-488bd7a74ecd)

**Comment by ernexto** [comment]
the same for voice & speech, i choose elevenlabs, insert api, choose a chat model different form "sarah", click save, come back here and it defaults to "sarah"

**Comment by ernexto** [comment]
ah, directories plugins and agent-skill are not created on my installation on windows 11, and if i create them manually it still doesn't work

**Comment by timothycarambat** [comment]
@ernexto This issue got sidetracked and was ultimately unclear to me, which is why it got lost. Was able to replicate. Just patched in https://github.com/Mintplex-Labs/anything-llm/issues/2281

**Comment by timothycarambat** [comment]
The settings _are saved_ so the agent will call them, they just dont appear in the UI

**Comment by timothycarambat** [comment]
@ernexto 11Labs bug patched as well
https://github.com/Mintplex-Labs/anything-llm/issues/2283

Will release next week. Never want to push the desktop app on a Friday for UI updates because it has given us major headaches doing so on a Friday and ruining an entire weekend for everyone.

In general, both of these bugs _display_ nothing in the UI, but your changes _do indeed_ save to the system and should persist when they are actually used or called.
