### ISSUE TITLE
[BUG]: Perplexity model name does not match models available via the API

### ISSUE THREAD

**Issue by rahul-tar** [Mintplex-Labs/anything-llm#2274]
### How are you running VectorAdmin?

Docker (local)

### What happened?

The model name under perplexity is wrong and does not match any model on perplexity model card.

### Are there known steps to reproduce?

Follow these steps:
Chat Settings > Workspace LLM Provider > Perplexity AI > Workspace Chat Model > llama-3.1-sonar-huge-128k-chat

Now try chatting and it will say invalid model. That's because `llama-3.1-sonar-huge-128k-chat` is not the right name for the 405B model. It is `llama-3.1-sonar-huge-128k-online` as seen in docs here - https://docs.perplexity.ai/guides/model-cards

**Comment by timothycarambat** [comment]
Would be way more effort than its worth because they _also_ keep changing the docs page too! 😆 

~$3B company and can't make a /models endpoint like everyone else, crazy!

**Comment by rahul-tar** [comment]
> Would be way more effort than its worth because they _also_ keep changing the docs page too! 😆
> 
> ~$3B company and can't make a /models endpoint like everyone else, crazy!


brainstorming here: Maybe a feature where user can type in model name in addition to the preset drop down?

**Comment by timothycarambat** [comment]
Ideally, yeah - basically a combobox for those who dont allow us to pull models dynamically!
