### ISSUE TITLE
[BUG]:  /usr/local/bin/docker-entrypoint.sh: line 7:   111 Illegal instruction     (core dumped) node /app/server/index.js 

### ISSUE THREAD

**Issue by youzhengjie9** [Mintplex-Labs/anything-llm#2286]
### How are you running AnythingLLM?

Docker (local)

### What happened?

How can I solve this problem? I am using docker for deployment and this error occurs (/usr/local/bin/docker-entrypoint.sh: line 7: 111 Illegal instruction (core dumped) node /app/server/index.js)

**Comment by timothycarambat** [comment]
See the pinned issue. Your CPU is too old and does not support AVX2 instructions. Either use a supporting CPU or dont use LanceDB as the vector Db
https://github.com/Mintplex-Labs/anything-llm/issues/1331#issuecomment-2153414982

**Comment by youzhengjie9** [comment]
> See the pinned issue. Your CPU is too old and does not support AVX2 instructions. Either use a supporting CPU or dont use LanceDB as the vector Db [#1331 (comment)](https://github.com/Mintplex-Labs/anything-llm/issues/1331#issuecomment-2153414982)

Thank you very much. I'll try again.

**Comment by mmonjezi817-hue** [comment]
> ### How are you running AnythingLLM?
> 
> Docker (local)
> 
> ### What happened?
> 
> How can I solve this problem? I am using docker for deployment and this error occurs (/usr/local/bin/docker-entrypoint.sh: line 7: 111 Illegal instruction (core dumped) node /app/server/index.js)
> 
> ### Are there known steps to reproduce?
> 
> _No response_

**Comment by mmonjezi817-hue** [comment]
> > ### How are you running AnythingLLM?
> > 
> > Docker (local)
> > 
> > ### What happened?
> > 
> > How can I solve this problem? I am using docker for deployment and this error occurs (/usr/local/bin/docker-entrypoint.sh: line 7: 111 Illegal instruction (core dumped) node /app/server/index.js)
> > 
> > ### Are there known steps to reproduce?
> > 
> > _No response_
> 
>

**Comment by mmonjezi817-hue** [comment]
> > ### How are you running AnythingLLM?
> > 
> > Docker (local)
> > 
> > ### What happened?
> > 
> > How can I solve this problem? I am using docker for deployment and this error occurs (/usr/local/bin/docker-entrypoint.sh: line 7: 111 Illegal instruction (core dumped) node /app/server/index.js)
> > 
> > ### Are there known steps to reproduce?
> > 
> > _No response_
> 
>
