### ISSUE TITLE
On Ubuntu 22.04, the program gets stuck at the "Running generate..." stage, with no further output or error messages.

### ISSUE THREAD

**Issue by waterno1** [Mintplex-Labs/anything-llm#2290]
### How are you running AnythingLLM?

Local development

### What happened?

My operating system is Ubuntu 22.04. After running the program with ./start, the following message appears, and then the interface stops at "Running generate... (Use --skip-generate to skip the generators)". And no graphical interface is displayed.
How can I resolve this issue?

log：
[Preferences] preference config stored at /home/my/.config/anythingllm-desktop/config.json
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/my/.config/anythingllm-desktop/storage/anythingllm.db"

Applying migration `20230921191814_init`
Applying migration `20231101001441_init`
Applying migration `20231101195421_init`
Applying migration `20240113013409_init`
Applying migration `20240118201333_init`
Applying migration `20240202002020_init`
Applying migration `20240206181106_init`
Applying migration `20240206211916_init`
Applying migration `20240208224848_init`
Applying migration `20240210001903_init`
Applying migration `20240210004405_init`
Applying migration `20240216214639_init`
Applying migration `20240219211018_init`
Applying migration `20240301002308_init`
Applying migration `20240326231053_init`
Applying migration `20240405015034_init`
Applying migration `20240412183346_init`
Applying migration `20240425004220_init`
Applying migration `20240430230707_init`
Applying migration `20240510032311_init`
Applying migration `20240618224346_init`
Applying migration `20240702174155_init`
Applying migration `20240821215625_init`
Applying migration `20240824005054_init`

The following migration(s) have been applied:

migrations/
  └─ 20230921191814_init/
    └─ migration.sql
  └─ 20231101001441_init/
    └─ migration.sql
  └─ 20231101195421_init/
    └─ migration.sql
  └─ 20240113013409_init/
    └─ migration.sql
  └─ 20240118201333_init/
    └─ migration.sql
  └─ 20240202002020_init/
    └─ migration.sql
  └─ 20240206181106_init/
    └─ migration.sql
  └─ 20240206211916_init/
    └─ migration.sql
  └─ 20240208224848_init/
    └─ migration.sql
  └─ 20240210001903_init/
    └─ migration.sql
  └─ 20240210004405_init/
    └─ migration.sql
  └─ 20240216214639_init/
    └─ migration.sql
  └─ 20240219211018_init/
    └─ migration.sql
  └─ 20240301002308_init/
    └─ migration.sql
  └─ 20240326231053_init/
    └─ migration.sql
  └─ 20240405015034_init/
    └─ migration.sql
  └─ 20240412183346_init/
    └─ migration.sql
  └─ 20240425004220_init/
    └─ migration.sql
  └─ 20240430230707_init/
    └─ migration.sql
  └─ 20240510032311_init/
    └─ migration.sql
  └─ 20240618224346_init/
    └─ migration.sql
  └─ 20240702174155_init/
    └─ migration.sql
  └─ 20240821215625_init/
    └─ migration.sql
  └─ 20240824005054_init/
    └─ migration.sql

Your database is now in sync with your schema.

Running generate... (Use --skip-generate to skip the generators)

**Comment by timothycarambat** [comment]
This has to do with `@prisma` and generating of the prisma client used by the ORM. Unable to replicate on a fresh Ubuntu 22 instance. Not sure what CPU arch you are on, that would be the only detail worth noting.

Otherwise, unable to replicate at all

**Comment by timothycarambat** [comment]
If this is local dev, you can try to cd into the root and run `yarn prisma:generate` and you _may_ get more verbose logging

**Comment by netbuddy** [comment]
@waterno1 I also encountered the same error, and finally found that it was caused by the following error:
`Error: request to https://binaries.prisma.sh/all_commits/61e140623197a131c2a6189271ffee05a7aa9a59/debian-openssl-3.0.x/libquery_engine.so.node.gz.sha256 failed, reason: connect ECONNREFUSED`
To run `prisma generate`, you need to download some additional tools. Therefore you need to configure the proxy to access this URL.
