### ISSUE TITLE
[FEAT]: docling integration

### ISSUE THREAD

**Issue by thistleknot** [Mintplex-Labs/anything-llm#2295]
### What would you like to see?

docling supports automatic markdown format for pdf's including properly parsed tables

i've integrated it into my own workflow.  If you would like to see how, I'll send the code, but it's fairly straightforward.

https://github.com/DS4SD/docling/issues

**Comment by timothycarambat** [comment]
This is a python library/tool - we cannot use it

**Comment by thistleknot** [comment]
Cant? What about unstructured or pymupdf. Are they not python libraries.
Doesn't make sense as it's mit license but okay

**Comment by timothycarambat** [comment]
How are we going to import a python library into a NodeJS project, MIT license or not has no bearing on the ability to run and execute the associated code that does whatever the related library or tool will do

**Comment by thistleknot** [comment]
Sorry misassumed backend stack
