### ISSUE TITLE
[FEAT]: Add support for temporary session credentials when connecting with Bedrock

### ISSUE THREAD

**Issue by SHASHANKB** [Mintplex-Labs/anything-llm#2299]
### What would you like to see?

Currently Bedrock connector only supports long term IAM User credentials. These can be insecure because they don't rotate automatically.

If you can add support for temporary session credentials (access-key, secret-key and session-token) when connecting with Bedrock, it'll remove the dependency to maintain an IAM User with long term static credentials

**Comment by dannysteenman** [comment]
+1 for this feature.
