### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [Mintplex-Labs/anything-llm#230]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@vvxhid) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by timothycarambat** [comment]
Create a security document in root. The proper email is team@mintplexlabs.com and I believe we did get an email from them, but it did not go into detail on the issue - only on the proper channel for reporting which is that email. 👍
