### ISSUE TITLE
[BUG]: LLM preference is selected, but Docker reboot needs to be reselected, what is the reason?

### ISSUE THREAD

**Issue by wewaa** [Mintplex-Labs/anything-llm#2307]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Use this template to file a bug report for AnythingLLM. Please be as descriptive as possible to allow everyone to replicate and solve your issue. Want help contributing a PR? Use our repo chatbot by OnboardAI! https://learnthisrepo.com/anythingllm"

### Are there known steps to reproduce?

LLM Preference and Embedding Preference are selected, but after Docker restarts, I find that I have to choose again, what is the reason?

**Comment by lukas-thirdmind** [comment]
We are currently hosting AnythingLLM on Google Cloud and encountering the same issue. After restarting the Docker container, all the AI configurations (LLM, VectorDB, etc.) seem to be lost, while the rest of the data remains intact.

**Comment by timothycarambat** [comment]
@lukas-thirdmind You are not mounting external storage, use the [official command](https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md) and it will persist post restarts or new image pulls.
