### ISSUE TITLE
[BUG]: Does not recover gracefully from errors

### ISSUE THREAD

**Issue by pwrreset** [Mintplex-Labs/anything-llm#2312]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When there's an inference error or a network error, the whole workspace becomes useless and corrupted with a red message. It is not possible to delete this message or retry.
see image:
![image](https://github.com/user-attachments/assets/02051d5b-6cc5-4795-bcc8-3ad948e94e29)

### Are there known steps to reproduce?

Just put a wrong URL or wrong passphrase in the model configuration, create a workspace and send a prompt. It'll give the red network error.

Fixing the configuration and/or retrying should be possible.

**Comment by timothycarambat** [comment]
> When there's an inference error or a network error, the whole workspace becomes useless and corrupted with a red message.

You can just send another chat right after - the workspace is still functional and the system has not crashed. Closing for now as unable to replicate
