### ISSUE TITLE
[FEAT]: Automatic Re-indexing of webpages in a workspace?

### ISSUE THREAD

**Issue by scooter7** [Mintplex-Labs/anything-llm#2323]
### What would you like to see?

Hi,

If I am querying Google Docs that are published as webpages in a workspace, is there any way that the URL can be re-indexed at timed intervals to account for changes that will be made to the content in these URLs over time?

Thanks!

**Comment by timothycarambat** [comment]
Yes, via the live document sync. Only manually uploaded documents are not able to be live synced when on Docker, otherwise every file is able to be synced.
https://docs.anythingllm.com/beta-preview/active-features/live-document-sync
https://docs.anythingllm.com/beta-preview/enable-feature

**Comment by scooter7** [comment]
Awesome, thank you!
