### ISSUE TITLE
[BUG]: Stucked at [BackgroundWorkerService] Feature is not enabled and will not be started.

### ISSUE THREAD

**Issue by daweiwang216** [Mintplex-Labs/anything-llm#2331]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

System: Ubuntu 22.04 arm64
Running other services like mongodb (port 27017), ollma (port 11434), nginx(port 80, 443) etc.

**Issue:**
When I start with `sudo docker run mintplexlabs/anythingllm:latest` or with the following options `--add-host=host.docker.internal:host-gateway`, it seems running correctly like the following message showed. But the message stucked at  `[BackgroundWorkerService] Feature is not enabled and will not be started.` 

Checking with docker status by `docker ps -a`, it shows **STATUS  Up 2 hours (healthy)** but **PORTS** are empty. 

---------------------------------------------------------------------------------------------

[collector] info: Collector hot directory and tmp storage wiped!
[collector] info: Document processor app listening on port 8888
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 395ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
'''
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
'''
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
'''
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
'''

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

SQLite database anythingllm.db created at file:../storage/anythingllm.db

23 migrations found in prisma/migrations

......

  └─ 20240618224346_init/
    └─ migration.sql
  └─ 20240821215625_init/
    └─ migration.sql
  └─ 20240824005054_init/
    └─ migration.sql
      
All migrations have been successfully applied.
┌─────────────────────────────────────────────────────────┐
│  Update available 5.3.1 -> 5.19.1                       │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
[backend] info: [EncryptionManager] Self-assigning key & salt for encrypting arbitrary data.
[backend] info: [TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
[backend] info: prisma:info Starting a sqlite pool with 17 connections.
[backend] info: [TELEMETRY SENT] {"event":"server_boot","distinctId":"89988ae1-940a-4088-892a-07df1b673dc4","properties":{"commit":"--","runtime":"docker"}}
[backend] info: [CommunicationKey] RSA key pair generated for signed payloads within AnythingLLM services.
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
[backend] info: Primary server in HTTP mode listening on port 3001
**[backend] info: [BackgroundWorkerService] Feature is not enabled and will not be started.**

**Comment by timothycarambat** [comment]
> [BackgroundWorkerService] Feature is not enabled and will not be started.

This is a normal message. Its just a log for a [beta preview feature](https://docs.anythingllm.com/beta-preview/overview). The server appears to boot fine
> [backend] info: Primary server in HTTP mode listening on port 3001

You should probably use the official command with your edit in it for the host gateway
```bash
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
--add-host=host.docker.internal:host-gateway \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

**Comment by daweiwang216** [comment]
> > [BackgroundWorkerService] Feature is not enabled and will not be started.
> 
> This is a normal message. Its just a log for a [beta preview feature](https://docs.anythingllm.com/beta-preview/overview). The server appears to boot fine
> 
> > [backend] info: Primary server in HTTP mode listening on port 3001
> 
> You should probably use the official command with your edit in it for the host gateway
> 
> ```shell
> export STORAGE_LOCATION=$HOME/anythingllm && \
> mkdir -p $STORAGE_LOCATION && \
> touch "$STORAGE_LOCATION/.env" && \
> docker run -d -p 3001:3001 \
> --cap-add SYS_ADMIN \
> --add-host=host.docker.internal:host-gateway \
> -v ${STORAGE_LOCATION}:/app/server/storage \
> -v ${STORAGE_LOCATION}/.env:/app/server/.env \
> -e STORAGE_DIR="/app/server/storage" \
> mintplexlabs/anythingllm
> ```

Could you help me with this 'HTTP mode listening on port 3001' situation? 
`netstat -tuln | grep :3001` `lsof -i :3001` show nothing and I think my port 3001 is available. Even if I change the port number, like `-d -p 8000:3001` this message keeps showing up.

**Comment by timothycarambat** [comment]
If you run that command without the `--add-host` does it boot up fine? It should bind to whatever parent port you like assuming that the port is available, otherwise the container will just shut down

**Comment by daweiwang216** [comment]
> If you run that command without the `--add-host` does it boot up fine? It should bind to whatever parent port you like assuming that the port is available, otherwise the container will just shut down

Thank you so much for your help. 
Unfortunately, it suffers from the same problem that says, "Primary server in HTTP mode listening on port 3001" **with or without adding `--add-host` AND/OR assign a host port by using `-p` option.**

**Comment by wangdaowei** [comment]
> > If you run that command without the `--add-host` does it boot up fine? It should bind to whatever parent port you like assuming that the port is available, otherwise the container will just shut down
> 
> Thank you so much for your help. ~Unfortunately, it suffers from the same problem that says, "Primary server in HTTP mode listening on port 3001" **with or without adding `--add-host` AND/OR assign a host port by using `-p` option.**~
> 
> **Issue Fixed** It was my environmental setting issue. Thank you so much for helping

i have the same problem, how can i fix it ?
