### ISSUE TITLE
[Question]: Could not respond to message.

### ISSUE THREAD

**Issue by laoheige** [Mintplex-Labs/anything-llm#2350]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![Snipaste_2024-09-23_14-46-24](https://github.com/user-attachments/assets/fafd57f1-6d12-4959-aeec-d0cf21c5ddfb)

### Are there known steps to reproduce?

我如果不在工作区上传文档 ，只聊天就正常。如果上传本地文档，再聊天 就这样了   重启电脑 重新安装 都试过 ，就是不行

**Comment by timothycarambat** [comment]
Since failure only occurs when chatting with embedded documents are you able to get the logs for the error?
https://docs.anythingllm.com/installation-desktop/debug

**Comment by Sure0520** [comment]
> ### How are you running AnythingLLM?
> Docker (local)
> 
> ### What happened?
> ![Snipaste_2024-09-23_14-46-24](https://private-user-images.githubusercontent.com/181073670/369772991-fafd57f1-6d12-4959-aeec-d0cf21c5ddfb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNzE1MDgsIm5iZiI6MTczMDE3MTIwOCwicGF0aCI6Ii8xODEwNzM2NzAvMzY5NzcyOTkxLWZhZmQ1N2YxLTZkMTItNDk1OS1hZWVjLWQwY2YyMWM1ZGRmYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwMzA2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGNhOTZjNWQ5YTkxODZlZDRiZDMwMWZlNWJhODY1NjgxOGYxNjA3ZmJmZjk1ZjBmYjZkM2I0YWYzYjk4Y2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.brMdSdh2d-YtHKlkuixezVYCXzMfsMxSuoOdFEcJ8no)
> 
> ### Are there known steps to reproduce?
> 我如果不在工作区上传文档 ，只聊天就正常。如果上传本地文档，再聊天 就这样了 重启电脑 重新安装 都试过 ，就是不行

你好，我也遇到了相同的问题，请问是如何解决的？

**Comment by yongshengma** [comment]
It could be a bug. I always get this issue after creating a workspace and/or upload documents and embedding. I find that the LLM selection in settings is gone and I have to reselect it and save it, and then this issue is gone.
