### ISSUE TITLE
Pinecone free tier does not support namespaces

### ISSUE THREAD

**Issue by filippoSelvatici** [Mintplex-Labs/anything-llm#236]
When you create an index in Pinecone using a free tier, it defaults to the environment `gcp-starter` and it cannot be changed. According to [pinecone docs](https://docs.pinecone.io/docs/namespaces), the environment `gcp-starter` does not support namespaces yet, which is necessary for anything-llm to properly use the context from the custom vectorized content. 

An easy alternative that runs on docker locally is ChromaDB. Instructions on how to install it are already described at `server/utils/vectorDbProviders/chroma/CHROMA_SETUP.md`.

**Comment by timothycarambat** [comment]
resolved by 79e3faa82ddc8f2bc0ed3db254016a90c235d00c
