### ISSUE TITLE
[DOCS]: Unclear how to access the app on local network

### ISSUE THREAD

**Issue by tcsenpai** [Mintplex-Labs/anything-llm#2360]
### Description

Hello!
I am using the Windows app on a PC on my network.
As I am using a laptop in the same network for daily usage, I'd like to access my anythingllm instance through LAN.

As far as I understood, by enabling discovery in Admin settings I should be able to do that.

I have indeed access to [lan ip]:3001 but it returns a "Not found" string without any other explanation.

In the past, using Docker, I was able to reach 3001 and the app just fine.

I could not find any instructions in the docs either.

**Comment by olariuromeo** [comment]
Add this in your docker compose:
        extra_hosts:
        - "host.docker.internal:host-gateway"
        - "127.0.0.1:host-gateway" `

**Comment by timothycarambat** [comment]
@tcsenpai 

> As far as I understood, by enabling discovery in Admin settings I should be able to do that.

Correct, then you need to _close and reopen the app_ when you edit that setting. Then the app should attach to 0.0.0.0 and other devices can see it.

> In the past, using Docker, I was able to reach 3001 and the app just fine.

Ah, there is some confusion on the UI part. The _desktop_ app serves the GUI only within the client, but that discoverability is if you want to use the API for the desktop client. Only the _docker_ version serves the GUI from the server - so that it can be accessed in a browser.

The desktop app has never served the UI from the server, intentionally.

**Comment by timothycarambat** [comment]
@olariuromeo I highly doubt you wrote that comment out and pretty sure its AI. Please dont post comments generated by AI for helping people. The comment you posted would not have helped the OP at all and was mostly irrelevant to their question.


Or just use a better model if you're going to do that and maybe limit `max_tokens`.

**Comment by olariuromeo** [comment]
> @olariuromeo I highly doubt you wrote that comment out and pretty sure its AI. Please dont post comments generated by AI for helping people. The comment you posted would not have helped the OP at all and was mostly irrelevant to their question.
> 
> Or just use a better model if you're going to do that and maybe limit `max_tokens`.

the comment was created by me, AI only did the formatting of the text and the grammar correction, if you think that the configuration of nginx and the one for anything, nginx and qadrand docker compose diles is wrong, which I already use successfully in every application and it works perfectly, any suggestion is welcome. There are 3 iterations for each suggested application, my model uses 8k

**Comment by timothycarambat** [comment]
@olariuromeo Apologies then, it was just so verbose and was not related to the question from OP so I assumed that as we have been recently spammed with AI issues/comments recently and thought it was more of the same.

**Comment by olariuromeo** [comment]
> @olariuromeo Apologies then, it was just so verbose and was not related to the question from OP so I assumed that as we have been recently spammed with AI issues/comments recently and thought it was more of the same.
It's only my fault that I gave a more extensive explanation of how I use the anything-llm application in docker to connect containers to each other, I thought it could be useful. In the future I will be more concise. The anything llm application is wonderful, it helped me a lot.

**Comment by tcsenpai** [comment]
Hi @olariuromeo , thanks for the reply.

Let me clarify: I have no issues using Docker both locally and publicly, I'd like to do the same while running the app itself.

Is that possible?

**Comment by timothycarambat** [comment]
<img width="1779" alt="Image" src="https://github.com/user-attachments/assets/4515ab02-2ad4-461f-9c5e-1a3b6875969d" />

If you want a _user interface_ across your LAN, you need to run the docker-based version of AnythingLLM
