### ISSUE TITLE
[FEAT]: Upload Repo from a local folder.

### ISSUE THREAD

**Issue by olariuromeo** [Mintplex-Labs/anything-llm#2362]
### What would you like to see?

GitHub has a limit for downloading repositories directly via the API. It would be useful if we could upload a folder directly from the computer containing our data. This way, a new folder with our documents would be automatically created within the data directory. Additionally, I often encounter the following error:

[collector] error: Error: Unable to fetch repository files: 403 {"message":"API rate limit exceeded for user ID . If you reach out to GitHub Support for help, please include the request ID and timestamp","documentation_url":"https://docs.github.com/rest/overview/rate-limits-for-the-rest-api","status":"403"} at /app/collector/node_modules/langchain/dist/document_loaders/web/github.cjs:

This is a feature request for the application, upload from local repo wil be very fast and no limit.

**Comment by timothycarambat** [comment]
Moving to #923
