### ISSUE TITLE
[BUG]: Data Connector Confluence cannot valid custom domain with two parts

### ISSUE THREAD

**Issue by dinhthanhtung** [Mintplex-Labs/anything-llm#2368]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Data Connector Confluence cannot valid right custom domain with two parts :
Example https://confluence.company.com.vn/display/PROJECT_DEMO
![image](https://github.com/user-attachments/assets/d06acafd-c6b3-4752-aedd-4af9c2bef041)

### Are there known steps to reproduce?

Step 1: click button upload at workspace (role admin)
Step 2: click tab Data connectors
Step 3: choose Confluence (connector)
Step 4: fill information (example confluence page url https://confluence.company.com.vn/display/PROJECT_DEMO)
Step 5: click button submit
-> AnythingLLM will return error message

**Comment by timothycarambat** [comment]
PR'd already: https://github.com/Mintplex-Labs/anything-llm/pull/2118
Issue: https://github.com/Mintplex-Labs/anything-llm/issues/1772
