### ISSUE TITLE
[BUG]: Docker container illegal construction

### ISSUE THREAD

**Issue by troymroberts** [Mintplex-Labs/anything-llm#2370]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Installed anything LLM on my local docker server via portainer, go through the setup process, connect to Ollama, create the initial workspace and attempt a query.

Get the following error: 
![image](https://github.com/user-attachments/assets/49829f31-2bff-4276-acdd-e8dcbb11b993)

When i check the container logs i have the following error: /usr/local/bin/docker-entrypoint.sh: line 7:   175 Illegal instruction     (core dumped) node /app/server/index.js

**Comment by timothycarambat** [comment]
See pinned issue - same error: https://github.com/Mintplex-Labs/anything-llm/issues/1331#issuecomment-2153414982

CPU is too old, requires AVX2 support for lancedb
