### ISSUE TITLE
[BUG]: Agent is not working

### ISSUE THREAD

**Issue by petrusali** [Mintplex-Labs/anything-llm#2387]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Agent never able to answer
![image](https://github.com/user-attachments/assets/d316b865-2ba7-4e26-aab0-131302280b22)

**Comment by timothycarambat** [comment]
Says you are using docker, there are handful of issues you can search that are closed that resolve this. 

First, logs would be most useful
https://docs.anythingllm.com/installation-docker/debug

And if you are using a reverse proxy to communicate with the instance, you need to make sure websocket is enabled
https://github.com/Mintplex-Labs/anything-llm/issues/2248#issuecomment-2339405618

https://github.com/Mintplex-Labs/anything-llm/issues?q=is%3Aissue+is%3Aclosed+agent+closed
