### ISSUE TITLE
[BUG]: RAG stream chat return nothing, but with citation

### ISSUE THREAD

**Issue by yufeng97** [Mintplex-Labs/anything-llm#2399]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Don't know how it happends.

I have check it's chat mode not query mode.
![image](https://github.com/user-attachments/assets/d576a75d-9a2c-4642-b2fb-9bab3bfce11a)

The workspace has selected documents.
![image](https://github.com/user-attachments/assets/ab546837-25fa-4c64-a084-3e342f607e04)

The request screenshots are showing below.
![image](https://github.com/user-attachments/assets/0c165ec1-9e2e-41d8-bae0-32d43cfc3245)
![image](https://github.com/user-attachments/assets/6f747402-6d37-4bb8-8a0a-5230710263d5)

**Comment by timothycarambat** [comment]
- What are you using for your LLM (Provider and model)
- Does the workspace chats log (in settings) show a response or is that empty too?

**Comment by yufeng97** [comment]
The LLM is Qwen2.5-14B-Instruct-AWQ in Xinference, but the provider is LocalAI.
