### ISSUE TITLE
[BUG]: Switching workspaces/threads results in the progress being made by embedding/chatting to not be shown

### ISSUE THREAD

**Issue by EDLLT** [Mintplex-Labs/anything-llm#2402]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

If I was chatting with an LLM and it began generating a response then I changed threads/workspaces and came back to the window, it won't show me the LLM's response(whilst still being generated)
This could confuse a user and make them think that the LLM stopped responding when in reality, it is still generating a response

A similar thing happens to documents that are being embedded whereby going to the "Data connectors" tab or dismissing the embedding window after you had begun to embed a document makes it not show you what it's doing in the background.
It confuses the end user

**Comment by timothycarambat** [comment]
Yes, because these screens and processes are not async/bg tasks - they dont not run when the user closes the connection to them. The embed will still go on and complete, but the LLM response will terminate. This is currently intentional

**Comment by EDLLT** [comment]
> Yes, because these screens and processes are not async/bg tasks - they dont not run when the user closes the connection to them. The embed will still go on and complete, but the LLM response will terminate. This is currently intentional

Okay so, I wasn't clear about the LLM response not terminating.

In my case, the LLM response does not terminate once I hit the "stop generating" button when the LLM being used is connected to LM Studio.
![image](https://github.com/user-attachments/assets/7258e9ca-d1c0-408d-b9ab-45f3ba613c3b)

It still continues generating the response(up until I either close AnythingLLM or stop the LM Studio server/eject the model)
