### ISSUE TITLE
[FEAT] Dark Theme/Appearance settings

### ISSUE THREAD

**Issue by rstil2** [Mintplex-Labs/anything-llm#2404]
### What would you like to see?

It would be nice to have the ability to have a dark theme and appearance settings. I like the application, but it sure could use some polish as the UI could be little easier to navigate (the layout does not seem idea for ease of use). Adding themes/appearance settings and cleaning up the UI to make it easier to navigate would make this application really shine. :)

**Comment by shatfield4** [comment]
Could you give me some specific examples of where the UI can be polished or easier to navigate? Also if you could please expand on "the layout does not seem idea for ease of use" as well too that would be very helpful.

 We want to improve our UI and improve the UX so any details you can provide would be greatly appreciated so we can implement it.

**Comment by timothycarambat** [comment]
Closing until something more actionable is defined

**Comment by rstil2** [comment]
Yes. For example, LM studio has options to change and customize the appearance of their interface. There are no options to change that in my version (macOS). That should be an obvious thing to put in as I find the interface unattractive to the point that I'm not inclined to use it. It looks to me as if someone did not put much time into the interface layout itself. For example, if you click on customization->appearance, the only thing you can change is the language and custom message. That is not what I expect when I click on that. I expect to be able to change the appearance of the interface, like a dark theme, etc.. Must users will likely expect the same thing and be disappointed. That is just one example, but there are many things like that just don't make sense in the menus. It needs some polish and QC. I think if you spent some time reorganizing the interface, polishing it, making the layout make more sense, then people would be much more likely to jump on board. I spent a couple of days just figuring it out, whereas with LM studio I was just up and running. Just trying to help.
