### ISSUE TITLE
[FEAT]: Attach file in chat

### ISSUE THREAD

**Issue by petrusali** [Mintplex-Labs/anything-llm#2405]
### What would you like to see?

I'd like docker version to have user be able to attach file in the conversation. Thank you.

**Comment by timothycarambat** [comment]
They can drag and drop files into the prompt and it works the same as it does on desktop

**Comment by petrusali** [comment]
That doesn't work on me, when drag & drop the file. The browser automatically download / open the file and the file is not attached to the conversation.
