### ISSUE TITLE
[FEAT]: Add Jenkinsfile file upload support.

### ISSUE THREAD

**Issue by rcruz63** [Mintplex-Labs/anything-llm#2407]
### What would you like to see?

If you try to add a Jenkinsfile, you'll get an error message saying, "No file extension found. This file cannot be processed."

When I'm trying to improve my software with AI, I'd like to think about the pipelines, so I'd like to be able to add my Jenkinsfile to the workspace.

**Comment by timothycarambat** [comment]
What is the file extension for a Jenkins file? Is it without an extension?

**Comment by Aryann15** [comment]
Yes, I do think Jenkins and Dockerfiles come without extensions. Can I proceed with this ? @timothycarambat, I think I see the root cause of this issue (collector/processSingleFile/index.js)

**Comment by timothycarambat** [comment]
@rcruz63 If you come across more for your use case you can PR them to this specialCases array:
https://github.com/Mintplex-Labs/anything-llm/blob/1a0ddfcd20c56ad531c601b1f433ed82a6d9748d/collector/utils/files/mime.js#L50

Not case sensitive!
