### ISSUE TITLE
[BUG]: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by VincentJGeisler** [Mintplex-Labs/anything-llm#2419]
### How are you running AnythingLLM?

Local development

### What happened?

installed using the script on ubuntu 22.04
curl -fsSL https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/installer.sh | sh
then ran start

died with the above error

### Are there known steps to reproduce?

follow the linux install guide. fails at the start command

**Comment by timothycarambat** [comment]
Related to electron/chromium: https://github.com/puppeteer/puppeteer/issues/12003#issuecomment-1965974235

System dep appears to be missing, not something we bundle in the app.
`sudo apt-get install libatk1.0-0`
