### ISSUE TITLE
[FEAT]: Support for OpenAI O1 series of models

### ISSUE THREAD

**Issue by onetake-ai** [Mintplex-Labs/anything-llm#2424]
### What would you like to see?

I can access a number of OpenAI models once I enter my API key, but not the o1 series (o1-mini and o1-preview).

However, my organization has API access to those, and with high limits, so I'd like to use them inside AnythingLLM rather than having to use the OpenAI playground or other clients.

I've updated to 1.6.7 today, just to make sure, but still no luck.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/514187b2-cfd2-46a6-9ef0-47473392b97e">

Since they seem to be chat completion models, is there any limitation that prevents AnythingLLM from showing the models?

**Comment by Claus1** [comment]
[v1.6.9 Linux] o1 models are not in the model list of openai, 
![anyllm](https://github.com/user-attachments/assets/bbc2de4a-f875-4f3b-8bd6-d21cf84cefa6)

**Comment by timothycarambat** [comment]
@Claus1 
<img width="746" alt="Screenshot 2024-11-10 at 12 07 56 PM" src="https://github.com/user-attachments/assets/37a32a77-f20f-4128-9aee-e073125c20bc">
 Yes they are, you probably don't have a tier 4 or higher API account on OpenAI. 
 https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-five#usage-tiers
 
 Only recently did they allow tier 4 API users to use it,
