### ISSUE TITLE
[DOCS]: SERP Configuration (Live Web Search and Browsing)

### ISSUE THREAD

**Issue by WizenThorne** [Mintplex-Labs/anything-llm#2426]
### Description

Could we get a little more clarification in getting the SERP configured, including the way to invoke a Web Search? As far as I've been able to glean from looking through other Issue conversations, the search is initiated using the @agent command followed by some sort of prompt like "Do a web search for XYZ". Is there a way to inform the LLM or Workspace to prioritize a current web search over information stored in the LLM, and can this be invoked without using the @agent command? An update to the DOCs could help clarify some of this.

**Comment by timothycarambat** [comment]
Since SERP is an agent skill, it must be done in an agent session since we currently differentiate the traditional RAG chat vs agent sessions.

You can prioritize tool calls over looking in memory via the workspaces system prompt though so you dont have to type it every session

**Comment by WizenThorne** [comment]
> Since SERP is an agent skill, it must be done in an agent session since we currently differentiate the traditional RAG chat vs agent sessions.
> 
> You can prioritize tool calls over looking in memory via the workspaces system prompt though so you dont have to type it every session

Do you know what I could put in that prompt to make that happen? I've tried a number of different prompts and it always results in the LLM stating it doesn't have access to real-time information unless I force it to access the web search agent skill using the @agent command.

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/agent-not-using-tools

What model are you using?

**Comment by WizenThorne** [comment]
Llama3.1 but I also tried with llama2.

**Comment by Julian-Dumitrascu** [comment]
I'm setting up your program.
I've toggled on the live web search and browsing.
I'd use SearXNG when someone shares their [API Base URL](https://docs.searxng.org/search.html?q=API+Base+URL).
