### ISSUE TITLE
[BUG]: AnythingLLM consistently recognised ollama/qwen2.5:1.5b as Claude by Anthropic

### ISSUE THREAD

**Issue by evian999** [Mintplex-Labs/anything-llm#2428]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

As the title and followed picture indicated. I had tried the same question in ollama, qwen worked well (fig. 1). This issue still exists even though I changed both the LLM preference and the workspace LLM provider to ollama/qwen2.5 (fig. 2-3). Interestingly, this issue does not raise when I switched the LLM to ollama/llama (fig. 4). 

So, I am curious if the AnythingLLM might have trouble with dealing the point in "2.5" so that the qwen cannot be recognised properly, and hence the system just switch Claude to me? But why Claude, because I do not have any Claude API or account at all.

![image](https://github.com/user-attachments/assets/d0f0a420-e61f-416c-b030-b867b0da4ff0) (fig. 1 same question in  anythingLLM and ollama with same LLM)

![image](https://github.com/user-attachments/assets/3b96a05e-66cb-4c18-be4b-79bfe7dec5a9) (fig. 2 workspace LLM provider)

![image](https://github.com/user-attachments/assets/497d3e50-a731-4b8f-b806-2cd9e4e97774) (fig. 3 LLM preference)

![image](https://github.com/user-attachments/assets/69f9f3aa-37f8-4ac5-aa5e-40a403a3dc1d) (fig. 4 llama3 do not have the same issue)

**Comment by timothycarambat** [comment]
This is not a bug with AnythingLLM. What you are seeing is a model hallucination, the difference between the CLI example and our UI was the use of a system prompt, but you can see that whole chain.

In general, you should never rely a model to tell you what it is. this is doubly true for OSS models. This is just a model quirk and is the LLM just hallucinating an answer. Go through everywhere in the code and you'll see we make no mention of trying to give an LLM an identity. The default system prompt just says it is "a useful assistant"
