### ISSUE TITLE
[BUG]: proxmox LXC docker exit

### ISSUE THREAD

**Issue by takenpro** [Mintplex-Labs/anything-llm#2438]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I'm in a Proxmox Ubuntu LXC trying to install Anythin LLM and access it from another client. When I complete the installation, docker ps -a shows that it doesn't start and remains in status 'exit'. I've tried several times with different LXC containers, and they all give me the same status. How could I solve this?

Thank you.

**Comment by timothycarambat** [comment]
Without container logs, its impossible to know what the error you are seeing actually is.
Did you review the pinned issue? https://github.com/Mintplex-Labs/anything-llm/issues

CPU may not support AVX2 instruction set, which is now nearly 10 years old tech!
