### ISSUE TITLE
[LanceDB] Could not respond to message. 

### ISSUE THREAD

**Issue by anchormath** [Mintplex-Labs/anything-llm#244]
I'm using the Docker version on a Mac. 
I disabled all vector db options except 
`VECTOR_DB="lancedb"`
My documents seem to have been processed successfully.
When I try to chat I get the 429 error and don't see any errors in the logs, just `SELECT * FROM workspace_documents WHERE workspaceId = 1`

Also server/storage/lancedb is empty

**Comment by timothycarambat** [comment]
They are embedded? Because if they were embedded the lancedb folder would not be empty. The Moderation endpoint is something totally unrelated to if your documents are embedded or not.

**Comment by anchormath** [comment]
ah, so am I missing a step? I do see the documents, how do I get the embeddings for them? 
<img width="607" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/213284/21dfd686-2ef2-4775-9050-a3f79ebdca64">

**Comment by timothycarambat** [comment]
Uploading puts them in one massive folder currently. If you click on the line that says `custom documents` it will expand to show a ton of files (112!) 

And file with a ⚡ means it has been embedded before. Red means it is currently embedded and you need to click on the **icon** to select a whole folder or a specific file.

Very annoying, the whole thing is getting a refresh right now with the V2 UI. But from what I can see it looks like only stuff was uploaded - nothing was embedded yet. That explains the issue!
