### ISSUE TITLE
[BUG]: proxmox LXC ubuntu docker exit

### ISSUE THREAD

**Issue by elcerilla** [Mintplex-Labs/anything-llm#2441]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hello, I have been installing Anything LLM multiple times on my Ubuntu-based LXC, and every time I install it, the Docker container shows an exited status. It doesn't start.

LOGS container docker:
CONTAINER ID   IMAGE                             COMMAND                  CREATED        STATUS                    PORTS                    NAMES
26c0843672d2   mintplexlabs/anythingllm          "/bin/bash /usr/loca…"   20 hours ago   Exited (1) 20 hours ago                            youthful_mccarthy
2f60f8559683   mintplexlabs/anythingllm          "/bin/bash /usr/loca…"   20 hours ago   Exited (1) 20 hours ago                            recursing_blackburn
[collector] info: Collector hot directory and tmp storage wiped!
[collector] info: Document processor app listening on port 8888
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 4.43s

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"
Error: Schema engine error:
SQLite database error

unable to open database file: ../storage/anythingllm.db

root@asistentev3:~# docker logs 2f60f8559683
[collector] info: Collector hot directory and tmp storage wiped!
[collector] info: Document processor app listening on port 8888
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

**Comment by timothycarambat** [comment]
> unable to open database file: ../storage/anythingllm.db

Please use the supported docker command which will 
- Create host storage for persistence
- Avoid this issue since the file for the local DB will exist.

https://docs.anythingllm.com/installation-docker/local-docker

```bash
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

**If you ran that command an have an issue, you need to chmod the storage folder you are using**
