### ISSUE TITLE
[DOCS]: Multi-user Mode

### ISSUE THREAD

**Issue by Akki-401** [Mintplex-Labs/anything-llm#2448]
### Description

In Multi-user Mode, What is max number of users are supported or verified? Is there any benchmarking result presents?

**Comment by timothycarambat** [comment]
As many as your system can handle. The bottle neck will _always_ be the LLM, not the application. The application can easily handle whatever you throw at it and if you have issues it will be from too many concurrent requests to a local LLM.

If you use a cloud based LLM provider, then your limitation becomes rate-limiting.

**Comment by Akki-401** [comment]
Thanks for clarification @timothycarambat
