### ISSUE TITLE
[BUG]:corrupt PDFs from agent

### ISSUE THREAD

**Issue by DrABolton** [Mintplex-Labs/anything-llm#2451]
### How are you running AnythingLLM?

All versions

### What happened?

 If I request that the agent create a PDF (locally or hosted) the PDF when downloaded will not open ...  Adobe reader reports it as damaged or corrupt.   Tried on multiple systems.   I don't get any errors.

### Are there known steps to reproduce?

Happens with every creation and export

**Comment by DrABolton** [comment]
Further info...What appears to be happening is that the chat text is exported as a PDF file but it is just a plain text file.   Export as txt instruction works as it sends the same data but gives it a .txt filename vs. pdf.   I used the syntax from the DOCs to ensure I was instructing it correctly    @agent can save this information as a PDF on my desktop folder?

**Comment by timothycarambat** [comment]
> If I request that the agent create a PDF (locally or hosted) the PDF when downloaded will not open ... Adobe reader reports it as damaged or corrupt. Tried on multiple systems. I don't get any errors.

This is not a skill that we even offer. The only agent skill built-in we offer is `text` files. You cannot just change the extensions of a text file into `.pdf` and have that work - they are two totally different file types.

If you specifically require PDF generation you will need to make a skill for that with custom agent skills. The LLM will simply hallucinate the PDF generation using the text doc skill and tell you it works - which is what is occurring here.
https://docs.anythingllm.com/agent/custom/introduction
