### ISSUE TITLE
[BUG]: Agent do not use its web browsing feature (only one over ten)

### ISSUE THREAD

**Issue by flefevre** [Mintplex-Labs/anything-llm#2463]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The agent make web browsing research only one time over ten, even if I ask directly "make a web browsing / research" in the prompt.

### Are there known steps to reproduce?

when 

- i activate the web browsing feature, with google parameter for the agent
- i call the agent with @agent in a discussion
- i ask for instance "who is the prime minister in France to day, make a reasearch on internet"

The agent answered me 
"I am sorry, I cannot perform an internet search because I am a language model and not a search engine. However, using the information I have up to now, the current Prime Minister of France is Jean Castex."

Nevertheless, i try several in time in the same discussion channel or open a new one, some time, the agent make the call to its web browsing feature and answered me fine.

**Comment by timothycarambat** [comment]
This is related to your model - https://docs.anythingllm.com/agent-not-using-tools

Basically, you need a more reliable model. This is accomplished via moving to increasing one of two parameters:
- the model's parameter (3B - > 8B) if possible
- The quantization used. The default is typically 4-bit and its usually bad for tool calling. Q8 is best usually. This is of course a factor of the parameter size. A 70B Q4 usually is better than a Q8 3B model.

**Comment by Securiteru** [comment]
@timothycarambat, is it normal for tool calls to not work with 4o? 

I'm currently running the AppImage version of AnythingLLM (the latest) and tools doesn't seem to trigger at all.

![Image](https://github.com/user-attachments/assets/d94d260b-4d8b-4d06-baa0-49955eacc9ac)

![Image](https://github.com/user-attachments/assets/255d4c37-3834-42d4-b2e6-74ce15549d07)

![Image](https://github.com/user-attachments/assets/88887102-0a8a-4f2a-8ab0-0af5b20f2a80)


Sorry for hijacking this thread, I just down know if it's something that I'm doing or not.

**Comment by timothycarambat** [comment]
@Securiteru 
> I'm currently running the AppImage version of AnythingLLM (the latest) and tools doesn't seem to trigger at all.

The agent flow actually never and ran at all. It exited instantly before it could even run. Can you check the logs or run the AppImage in [debug](https://docs.anythingllm.com/installation-desktop/debug)? Basically, something is crashing the agent before it can even execute so nothing happens.

Using gpt-4o for agent. Ignore the workspace name, this is not deepseek. This is what agent calls look like when they work.


<img width="1904" alt="Image" src="https://github.com/user-attachments/assets/12534827-2c42-4f58-8b4c-6504731b6ea2" />

**Comment by boomboom77365** [comment]
My agent refuses to use web-browsing skill to look for anything at all. I'm running DeepSeek-R1-Distill-Llama-8B-Q6_K. My answers are always very strange and ignorant.

**Comment by o0LINNY0o** [comment]
This is driving me insane ! , every YT video makes it look so easy and im getting zero help . ive created tickets in Discord channel and in Reddit on /LocalLLaMA . 

Ive ran as Admin , uninstalled and re-installed , ensured firewalls are not on , 

its not pulling any of the tools either , ive used Qwen314 4_k_M a& Agentic 7B Q8 ... nothing changes

**Comment by one-dumb-dude** [comment]
@o0LINNY0o Did you ever figure this out?
