### ISSUE TITLE
[BUG]: Voices support mp3's but it only lists wav files

### ISSUE THREAD

**Issue by phazei** [Mintplex-Labs/anything-llm#2467]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The xtts voices list will only show files in the directory that end in wav.

If I rename a mp3 to wav, then it works just fine.

I presume that's probably due to the ffmpeg dealing with it.  It seems like it should just list the mp3s as well.

### Are there known steps to reproduce?

Add a mp3 to the voices dir.

rename it to wav without even converted, watch it work.

**Comment by timothycarambat** [comment]
> The xtts voices list will only show files in the directory that end in wav.

Where is this that you are seeing the list of voices as `wav` files?

**Comment by phazei** [comment]
🤦🏻 wrong repo, sorry
