### ISSUE TITLE
How do I change the API's localhost to access it via the local machine's IP?

### ISSUE THREAD

**Issue by zhijianren** [Mintplex-Labs/anything-llm#2472]
Based on AnythingLLM + Ollama, I deployed a model, and it works fine when accessing it with curl -X POST http://localhost:3001/api/v1/workspace/llm/chat.... However, when I replace localhost with the IP address (e.g., curl -X POST http://172.13.x.xxx:3001/api/v1/workspace/llm/chat...), it shows curl: (7) Failed to connect to 172.13.x.xxx port 3001 after 2055 ms: Could not connect to server. In summary, I can access it using localhost and 127.0.0.1 with the port number, but using the local machine's IP address with the port number does not work. How can AnythingLLM listen on all IPs so that other devices can access it via the IP address?

**Comment by timothycarambat** [comment]
Are you on the desktop app?
If so, then you should go to the settings > security and enable "Disoverable on network".
Close and reopen app again and now the backend server for the app will listen on `0.0.0.0:3001` making is discoverable by other machines on the LAN.

If on Docker, this is a configuration issue that can be solved by attaching a network bridge or more commonly is blocked by computer firewalls and is outside of the AnythingLLM software directly.

**Comment by zhijianren** [comment]
Thank you very much for your reply. The problem has been solved.
