### ISSUE TITLE
[BUG]: Use Postman to POST API /v1/document/upload with chinese file name, API will response garbled title name

### ISSUE THREAD

**Issue by appdevhm88mt** [Mintplex-Labs/anything-llm#2474]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Expect to get correct chinese or multiple-language title name

### Are there known steps to reproduce?

See the Postman testing screenshots.
1. Chinese File Name -> Get garbled title name (X)
![Chinese-File-Name](https://github.com/user-attachments/assets/14b6ac0b-6ebe-44d7-a04d-79f0cb41a753)
2. English File Name -> Get correct English title name (V)
![English-File-Name](https://github.com/user-attachments/assets/ec2531c9-ae88-4cd9-b1a2-30a03c54dcfb)

**Comment by appdevhm88mt** [comment]
Hi,
1. Can this solution also solve other languages? Such as Japanese, Korean, Vietnamese, etc. See the attached screenshot for Japanese issue)
2. When will this solution be released?

![image_Japanese](https://github.com/user-attachments/assets/1c45740a-afad-41a2-9a68-47dc6518a938)

**Comment by timothycarambat** [comment]
This would apply to all languages that are not `latin` UTF

**Comment by appdevhm88mt** [comment]
OK, Thx

**Comment by Pinocchioi** [comment]
你好，调用上传文件接口出现中文乱码这个该如何解决
