### ISSUE TITLE
[FEAT]: bulk link scraper realtime log

### ISSUE THREAD

**Issue by jasonmhead** [Mintplex-Labs/anything-llm#2478]
### What would you like to see?

I would be useful to have a bulk link scraper realtime log so you can see that the scraping is working, and progress, 
and especially the error when the fetch fails.

The first process can take a while, then you see fetch failed with no other details.

**Comment by timothycarambat** [comment]
Agreed, all the scrapers need reporting back to UI, as well as embedding.
This particular feature is tracked in https://github.com/Mintplex-Labs/anything-llm/issues/1570

**Comment by timothycarambat** [comment]
There is a comment at the end of the above link that shows how to tail said log from backend directly
