### ISSUE TITLE
[BUG]: AWS Bedrock - This model doesn't support system messages

### ISSUE THREAD

**Issue by dabump** [Mintplex-Labs/anything-llm#2486]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hi all. Need some help please.

Enabled the 'Titan Text G1 - Express' foundation model in AWS Bedrock. Getting this message when trying to interact in workspace. 

'This model doesn't support system messages. Try again without a system message or use a model that supports system messages.'

Can anybody shed some light on what I'm doing wrong or have any suggestions?

![image](https://github.com/user-attachments/assets/979c53b0-d341-466c-9627-f8585cea815b)

`[backend] error: ValidationException: This model doesn't support system messages. Try again without a system message or use a model that supports system messages.
    at de_ValidationExceptionRes (/app/server/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:1159:21)
    at de_CommandError (/app/server/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:1008:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/server/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /app/server/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /app/server/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /app/server/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async ChatBedrockConverse._streamResponseChunks (/app/server/node_modules/@langchain/aws/dist/chat_models.cjs:250:26)
    at async ChatBedrockConverse._streamIterator (/app/server/node_modules/@langchain/aws/node_modules/@langchain/core/dist/language_models/chat_models.cjs:93:34)
    at async ChatBedrockConverse.transform (/app/server/node_modules/@langchain/aws/node_modules/@langchain/core/dist/runnables/base.cjs:394:9)
`

**Comment by timothycarambat** [comment]
Hm, this is odd. I thought the Titan model did support system messages? That is all that is going on here. Using any other foundational model and this would not be an issue (llama, mistral, Claude).

Will investigate this tonight/tomorrow AM

**Comment by timothycarambat** [comment]
Ah, so yes. While not obviously documented by AWS - the Titan models indeed work with a system message. Unfortunately this also breaks RAG for chats so we will need to patch this behavior for bedrock models that do not use `system` messages. Easily done, will have PR tomorrow (it is late by me currently)

**Comment by dabump** [comment]
You are a legend @timothycarambat ...will wait for new release, thanks :)

**Comment by timothycarambat** [comment]
Will be live in docker image `latest` when this build or a future build completes:
https://github.com/Mintplex-Labs/anything-llm/actions/runs/11372556281

**Comment by timothycarambat** [comment]
Then you should open a new GH issue if a bug has regressed. That being said - it is legitimately hard coded to handle that model explicitly - since there is no API or way to determine this preflight

https://github.com/Mintplex-Labs/anything-llm/blob/0d1a2f06aa9a71ed8adf7191ca0c0eb0a3e8d7c6/server/utils/AiProviders/bedrock/index.js#L22
