### ISSUE TITLE
[BUG]: Fetch URL with chinese will cause "Error uploading link: A processing error occurred."

### ISSUE THREAD

**Issue by subirdkimo** [Mintplex-Labs/anything-llm#2493]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Using upload Document with Fetch website, example: fetch URL with Chinese words like below
https://zh.wikipedia.org/wiki/2024年中華民國總統就職典禮
Will cause "Error uploading link: A processing error occurred."

### Are there known steps to reproduce?

upload Document with Fetch website
https://zh.wikipedia.org/wiki/2024年中華民國總統就職典禮

**Comment by sdshin** [comment]
i'm still having this error while using fetching below link -
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere-supervisor/8-0/vsphere-supervisor-concepts-and-planning/vsphere-with-tanzu-deployment-options/zoned-supervisor-vs-vsan-stretched-cluster-supervisor-deployments.html
