### ISSUE TITLE
[BUG]: Unable to upload file to the docker version

### ISSUE THREAD

**Issue by petrusali** [Mintplex-Labs/anything-llm#2497]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

<img width="328" alt="image" src="https://github.com/user-attachments/assets/ff06e4cc-bdfe-4a39-8559-1c21c0d8c6ce">
I tried to upload any .csv & .pdf files but always got error. And on some files, has never ending upload process. I've waited for up to 30 mins for files around 10MB size.

The problem happen after upgrading to the latest version.

**Comment by petrusali** [comment]
I resolved the issue by repulling the latest image

But the long upload time with seems still there
<img width="359" alt="image" src="https://github.com/user-attachments/assets/fde38b8a-46a3-40e7-bcfa-26040cba254b">
<img width="337" alt="image" src="https://github.com/user-attachments/assets/9e89f5ef-d23c-4d2b-9d9f-53e5e2715711">

**Comment by timothycarambat** [comment]
You need to run the docker container with the appropriate command:
https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md#recommend-way-to-run-dockerized-anythingllm

```
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

^ handles storage and web-scraping perms

**Comment by timothycarambat** [comment]
Also i see you said pulling the latest image changes something. I dont think that is exactly the case, but also parsing document at any speed is heavily dependent on the machine/resources Docker can use on the image. 

What are the specs for the machine? Using a t3.mico for instance is going to be very very slow parsing any reasonably sized document and is a resource issue, not a software one!

**Comment by petrusali** [comment]
Hi Timothy, thanks for your feedback. Actually I did exactly the same as instructed and everything is working perfectly without any issues.

After having some test, I find out that when the PDF doc has images in it. The upload process will stuck. Different from the desktop version where when the PDF has images, the embedding process will ignore the images and only embed the text to the DB.

And for the machine spec, I use Standard_B2ps_v2 from Azure. I monitor the usage is very healthy without any indication of overloading the resources (while the upload process stuck, the CPU and memory usage is nearly 0).

Any further help is very welcome. Thank you.

**Comment by timothycarambat** [comment]
@CRYPTO-GENIK Its answered here https://docs.anythingllm.com/installation-docker/local-docker#recommend-way-to-run-dockerized-anythingllm
