### ISSUE TITLE
Unable to load the "Upload Docs" from the UI

### ISSUE THREAD

**Issue by Nhan-Vo** [Mintplex-Labs/anything-llm#250]
I am having this issue that is saying my document processor is offline.
Please help me fixing it.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/88568930/4e10c6fb-a248-400e-9523-ca68e4173278)

**Comment by timothycarambat** [comment]
Please [consult the Readme](https://github.com/Mintplex-Labs/anything-llm/tree/master/collector#running-the-document-processing-api-locally)on how to run the document processor in development
