### ISSUE TITLE
[BUG]: Uncaught TypeError: destroy is not a function

### ISSUE THREAD

**Issue by andrewyuau** [Mintplex-Labs/anything-llm#2503]
### How are you running AnythingLLM?

Docker (local)

### What happened?

As a user, getting blank page after going back to main page from workspace. Getting same error from Docker (local) and dev mode. Error message in dev mode is "Uncaught TypeError: destroy is not a function"

### Are there known steps to reproduce?

1. Modify Anything-LLM security to use password
2. Create user with role default
3. Create workspace as administrator and add user to it
4. Log in as user, click on workspace and then click on logo to go back to main page

https://github.com/user-attachments/assets/c6ce067f-2f50-4263-9a5b-a14eab2126f3

**Comment by timothycarambat** [comment]
> Modify Anything-LLM security to use password
Single user mode or multi-user mode? If all you need is a password = single-user mode.

> Create user with role default
This should not even be possible to do since the instance is not in _multi-user mode_

**Comment by timothycarambat** [comment]
Ah, was able to repro - patched

**Comment by andrewyuau** [comment]
Amazing, thanks very much!
