### ISSUE TITLE
[FEAT]: [Docker] 

### ISSUE THREAD

**Issue by nekopep** [Mintplex-Labs/anything-llm#2504]
### What would you like to see?

Currently anythingLLM allow to develop agent plugin as NodeJS plugin. A lot of agent related thing are coded in python that used a lot in AI domain.
For example: https://openwebui.com/functions is a great source of such function that an LLM could call.
Would it be possible to create an NodeJs agent that would do underyhin pythaon function call?

**Comment by nekopep** [comment]
Sorry hot enter before finishing feature request...

**Comment by timothycarambat** [comment]
Yes, if Python is available on the host system, NodeJS could execute the client python installation and run arbitrary code to perform tasks. Obviously only run scripts you trust.
