### ISSUE TITLE
[FEAT]: Support Groq multi-modal

### ISSUE THREAD

**Issue by japen0617** [Mintplex-Labs/anything-llm#2505]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

groq released the image recognition language for llama 3.2, and you can also choose related 90B and 11B models, but when I upload an image and ask the language model to recognize it, it always fails, I don't know if it's stuck on the base64 issue

### Are there known steps to reproduce?

選取groq的llama-3.2-90b-vision-preview  或是 llama-3.2-11b-vision-preview 模型 , 然後上傳一張圖片

**Comment by timothycarambat** [comment]
Not a bug, needs to be done as a feature. We dont currently pass in images for the Groq provider
https://github.com/Mintplex-Labs/anything-llm/blob/7342839e779e6dee0c2e1a670857dfe3e9ce6edf/server/utils/AiProviders/groq/index.js#L62-L67

**Comment by japen0617** [comment]
okay , thanks for help .
