### ISSUE TITLE
[BUG]: Show citations functionality does not render visualizations

### ISSUE THREAD

**Issue by MounirHader** [Mintplex-Labs/anything-llm#2508]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When asking questions about a specific knowledge base, the agent replies with context-specific text. When expanding the **Show citations** link at the bottom of the answer, I keep finding greyed out blocks. I suspect these are supposed to be matched keywords 
![Screenshot 2024-10-21 at 12 16 40](https://github.com/user-attachments/assets/268ce909-c460-4692-8b3f-6b3541d75da0)
or something. Is this a known issue?
![Screenshot 2024-10-21 at 12 16 49](https://github.com/user-attachments/assets/5af88dec-de34-4e49-85fb-afbe01fb9629)

### Are there known steps to reproduce?

- Run anythingllm locally with docker
- Set up a workspace
- Upload documents
- Start a chat (either in the default or in a new thread)
- Ask a context-specific question and click the "Show citations" link at the bottom

**Comment by timothycarambat** [comment]
This is simply a UI element that is emulating the "space between text blocks". There is nothing supposed to be there or is loading. This is the 3rd time this confusion has been highlighted so we are going to remove this.
