### ISSUE TITLE
Error : 429 OpenAI::CreateModeration failed with: Request failed with status code 429

### ISSUE THREAD

**Issue by MirzaAreebBaig** [Mintplex-Labs/anything-llm#251]
Hello,
I have win 10 & setup the instance as OpenAI api & pinecone as vector database with multi user enabled & getting this error when trying to chat.

**Comment by timothycarambat** [comment]
You 429 is a rate limit request - you either are using a key that is used elsewhere and it subject to rate limit or many users are on the same instance at the same time sending many chats per min.

You can disable moderation via code only currently. Will look into making this a feature you can fully turn off. Moderation calls do not count towards the limit if I recall.

**Comment by MirzaAreebBaig** [comment]
Hello,
Thank you for your reply on this.
Yes i have generated another key & it worked but as of now its working but once i give access to multiple users on that same instance will this issue again arise? 
Or as you have pointed i can disable moderation via code how can i achieve this?

**Comment by timothycarambat** [comment]
I would find it quite unlikely that even in a multi user instance you would hit the rate limit with normal human traffic unless your instance has hundreds of concurrent users chatting at the same time.

Comment out this section of code:
https://github.com/Mintplex-Labs/anything-llm/blob/e4a5fe5971b45d2415ec74f457d8be1c3a06510f/server/utils/chats/index.js#L78-L90

And it will not go through moderation - however if inappropriate questions are asked the LLM will start to return refusals

**Comment by MirzaAreebBaig** [comment]
Alright that's great i got it. Thank you.
