### ISSUE TITLE
[FEAT]:  need to disable login to anythingllm

### ISSUE THREAD

**Issue by shreyshreya** [Mintplex-Labs/anything-llm#2518]
### What would you like to see?

Want to disable login screen for anythingllm to be able to integrate with our in-house tool

**Comment by timothycarambat** [comment]
Login is not enabled by default on all instances. If it is already enabled for _multi-user_ authentication the instance needs to be reset to return to unauthenticated. This is intentional

**Comment by shreyshreya** [comment]
How do we reset the instance to return to unauthenticated? In multi user
mode.

**Comment by timothycarambat** [comment]
Delete the folder you associated the docker container storage with and rerun the same start command you have been running. This will fully reset everything on the instance.
