### ISSUE TITLE
[BUG]: bulk link

### ISSUE THREAD

**Issue by socir9** [Mintplex-Labs/anything-llm#2519]
### How are you running AnythingLLM?

Docker (local)

### What happened?

is there a way to increse max deepth level in bulk link scrapper

**Comment by timothycarambat** [comment]
Is this not that configuration setting?

<img width="1612" alt="Screenshot 2024-10-22 at 10 21 20 AM" src="https://github.com/user-attachments/assets/82505b06-5c17-4caf-809c-55b7891f421d">
