### ISSUE TITLE
[BUG]: cannot load models from ollama

### ISSUE THREAD

**Issue by xjqsusu** [Mintplex-Labs/anything-llm#2523]
### How are you running AnythingLLM?

Docker (local)

### What happened?

cannot select Ollama Model.

AnythingLLM is install per https://docs.anythingllm.com/installation-docker/local-docker

AnythingLLM is running in the docker on a Linux machine,
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04

Tried to change the Ollama base url 
http://host.docker.internal:11434
http://localhost:11434
http://172.17.0.1:11434

Ollama is running
curl localhost:11434
Ollama is running

<img width="871" alt="image" src="https://github.com/user-attachments/assets/3ae890d7-a42e-4d45-8dad-71661e8f4f09">

**Comment by szur1** [comment]
This is still happening for me - even using http://host.docker.internal:11434/

Windows 11
AnythingLLM (Latest) is running in Docker - Verified http://localhost:3001/
Ollama (Latest) is running in windows  - Verified http://localhost:11434
Ollama has Llama3.1 model installed - verified with the command C:\Windows\System32>ollama list
Ollama return chat using C:\Windows\System32>ollama run llama3.1

Have tried all these - No models able to be selected - pulldown is disabled

http://host.docker.internal:11434/
http://localhost:11434/
http://172.17.0.1:11434/

**Comment by timothycarambat** [comment]
@szur1 you need to be running `ollama serve` - only this command starts the server in the backend. However, I presume that is working since the localhost:11434 is up.

How are you running the docker container (command) since this is a network layer thing with the docker container being able to reach the host network

**Comment by szur1** [comment]
I am running C:\Windows\System32>ollama serve

**Comment by xjqsusu** [comment]
still not working with http://172.17.0.1:11434

anythingllm docker log
[backend] error: TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ollamaAIModels (/app/server/utils/helpers/customModels.js:283:18)
    at async getCustomModels (/app/server/utils/helpers/customModels.js:36:14)
    at async /app/server/endpoints/system.js:910:35

<img width="886" alt="image" src="https://github.com/user-attachments/assets/c8f00426-3017-4706-8a4a-8df2b4caf48f">

**Comment by xjqsusu** [comment]
if I do
curl 172.17.0.1:11434
curl: (7) Failed to connect to 172.17.0.1 port 11434: Connection refused

but
curl localhost:11434
Ollama is running

**Comment by timothycarambat** [comment]
> if I do
curl 172.17.0.1:11434
curl: (7) Failed to connect to 172.17.0.1 port 11434: Connection refused

Are you doing this inside of the anythingllm docker container or on your host? That IP only resolves inside of the container. Also how are you running the docker container?

**Comment by szur1** [comment]
curl 172.17.0.1:11434
curl: (7) Failed to connect to 172.17.0.1 port 11434 after 0 ms: Connection refused

From within the docker image.  Running using Docker Desktop

**Comment by xjqsusu** [comment]
follow this fixed the issue for me - https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/ollama/README.md

now it is returning running 
curl 172.17.0.1:11434
Ollama is running
