### ISSUE TITLE
[FEAT]: "Get all threads" API

### ISSUE THREAD

**Issue by lewismacnow** [Mintplex-Labs/anything-llm#2538]
### What would you like to see?

This feature request is to enhance the API for AnythingLLM by adding functionality to get all Threads from prisma

We have get all chats in a thead, but we have no get all threads:

<img width="1450" alt="image" src="https://github.com/user-attachments/assets/bb46a25a-6388-46db-8181-2d88544d28f1">

**Comment by timothycarambat** [comment]
Temporarily closing wrt PR https://github.com/Mintplex-Labs/anything-llm/pull/2539
