### ISSUE TITLE
[BUG]:  Skipping document - Token limit of 128000 has already been exceeded by pinned documents

### ISSUE THREAD

**Issue by kabaluyot** [Mintplex-Labs/anything-llm#2543]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

What does this "info log" means?

For context, it is a gpt4o-mini model wit 950 pdfs uploaded as knowledge source.

<img width="1070" alt="Screen Shot 2024-10-28 at 12 34 17 PM" src="https://github.com/user-attachments/assets/ce17f523-fff2-437f-bf7f-920fc9294430">

**Comment by timothycarambat** [comment]
`gpt4o-mini` has a max context window of 128K tokens. You pinned more than 128K tokens so our system prunes them out of the context because your request would fail. This is likely because you attaching 980 PDFs, the model's context window is not infinite
