### ISSUE TITLE
[UI/UX]: Incorrect focus border style on input field in embedded setup

### ISSUE THREAD

**Issue by danvincent11** [Mintplex-Labs/anything-llm#2544]
### How are you running AnythingLLM?

Local development

### What happened?

When the input field is focused in the embedded setup, a blue border appears around it. However, this border styling does not align with the expected design of the input field. It seems out of place and may appear inconsistent with other UI elements.
![image](https://github.com/user-attachments/assets/ab7b0823-c4d7-4329-8a2e-76b2df2c4893)

**Comment by shatfield4** [comment]
@danvincent11 What browser/device are you viewing this on where it has the blue border around it? I cannot replicate this on my machine. 

Also are you running the most up to date version of AnythingLLM?

**Comment by timothycarambat** [comment]
FWIW: We already `outline-none` on `active` and `focus` for the embed, this very well may be browser behavior
https://github.com/Mintplex-Labs/anythingllm-embed/blame/6bd51d251ff1b204d7d88cdda0061df00676386e/src/components/ChatWindow/ChatContainer/PromptInput/index.jsx#L73
