### ISSUE TITLE
[unable loading ollama with dokcer anythingllm ]: can't loading the local Ollama with docker anything

### ISSUE THREAD

**Issue by ddimit2020** [Mintplex-Labs/anything-llm#2548]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I'm also follow the step to install docker anything

1. **docker pull mintplexlabs/anythingllm**
2. export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env"

docker run -d -p 3001:3001 \
--add-host=host.docker.internal:host-gateway \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm

3.also vim /etc/systemd/system/ollama.service
[Service] add 2 Env.
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_MODELS=/www/algorithm/LLM_model/models"

4. after restart 
systemctl daemon-reload
systemctl restart ollama

5.than setup the anythingllm,can;t load the localhost:ollama
![anythingllm](https://github.com/user-attachments/assets/353c9ce3-ae3c-44e1-8c14-ffbdce31728b)

also i already try URL:http://host.docker.internal:11434,still can't loading the ollama model

shoud i miss something step?

os:Ubuntu 20.04.6
ollama install the ubuntu localhost:11434
Docker version 24.0.7
anythingllm install the docker

have anything idea???

**Comment by timothycarambat** [comment]
Are you able to even reach the ollama API via the `http://192.168.58.164:11434` URL in a browser?
http://192.168.58.164:11434/api/tags should return a JSON response with all installed models.

If the browser cannot resolve the that location, then the container certainly cannot.

**Comment by ddimit2020** [comment]
it's mean on ubuntu open browser to get http://192.168.58.164:11434 and http://192.168.58.164:11434/api/tags
i'm try it,but still can't get anything(unable to connect),
but http://localhost:11434 cam show the ollama is running
so any tips miss???
i don't have any idea

**Comment by timothycarambat** [comment]
I overlooked this prior, but host.docker.internal **does not work on Ubuntu**
https://docs.anythingllm.com/ollama-connection-troubleshooting#url-detection-failed-when-manual-endpoint-input-is-expanded-the-url-was-not
On "Docker" tab 

```
Docker Version
Windows/macOS: http://host.docker.internal:11434
Linux: http://172.17.0.1:11434
On Linux, use http://172.17.0.1:11434 as host.docker.internal doesn't work.
```

Have you tried http://172.17.0.1:11434 in the URL? This maps localhost in the container to the host, which now since localhost works - this should too.
