### ISSUE TITLE
[BUG]: Other machines on the local area network are unable to access this machine except for the local machine itself

### ISSUE THREAD

**Issue by holylong** [Mintplex-Labs/anything-llm#2549]
### How are you running AnythingLLM?

Local development

### What happened?

![1730173509941](https://github.com/user-attachments/assets/86b160b9-5730-4cba-9879-1373e312fd80)
![1730173714044](https://github.com/user-attachments/assets/1d94d44d-eb2d-49e1-a709-b2103cf7c302)

### Are there known steps to reproduce?

start command
```
yarn run dev:server
yarn run dev:frontend
```

**Comment by timothycarambat** [comment]
The is a config/setup issues. Not a bug that requires fixing.
1. Make sure frontend/.env has this ENV set
https://github.com/Mintplex-Labs/anything-llm/blob/3fe59a7cf5cea9c3c845c362b07a9cf218af0bd7/frontend/.env.example#L1

2. Check the log/terminal of `dev:server` clearly it is throwing an error prevent it from booting. Fix that and it will work fine!
Common issues:
No `server/.env` file
No `server/storage/anythingllm.db` file

Both of which are created by running `yarn setup` from root of repo.
