### ISSUE TITLE
[FEATURE]: Workspace chat history Dev API improvements

### ISSUE THREAD

**Issue by kabaluyot** [Mintplex-Labs/anything-llm#2556]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Even if chat history limit is set to 20, the workspace chat history endpoint still returns all data making the API call longer when having lots of chat history.

<img width="759" alt="Screen Shot 2024-10-30 at 9 13 05 AM" src="https://github.com/user-attachments/assets/38cbbba8-adc9-4304-a6bc-fe7cf7dafecf">

![image](https://github.com/user-attachments/assets/ff803873-52af-4a42-a672-5ffe090312ae)

**Comment by timothycarambat** [comment]
That property is under **Chat settings**, so it only applies during chats (via UI or API).

The workspace/chats endpoint is exactly for retrieving all chats within the system. What should be done is we should add an optional limit and orderBy to this endpoint so it works like a RESTful endpoint
