### ISSUE TITLE
Agent cannot find my SQL

### ISSUE THREAD

**Issue by kkellyk** [Mintplex-Labs/anything-llm#2557]
I turned on the Agent SQL settings and connected.
![image](https://github.com/user-attachments/assets/eb6b4f2c-bacb-489c-b3c3-66b89e13576c)

But I ask  @agent Checking what are the available databases?
The agent cannot connect to my SQL.
![image](https://github.com/user-attachments/assets/cac8b527-d954-4a9d-b4bd-556f0e43b7f6)

I have used python to connect to my MySQL and can read the data normally.
**How can I use the agent to read the MySQL data?**
Is there a step I'm missing?
Thanks

**Comment by timothycarambat** [comment]
we have a whole doc about this exact issue
https://docs.anythingllm.com/agent-not-using-tools

**Comment by vin958** [comment]
> I turned on the Agent SQL settings and connected. ![image](https://github.com/user-attachments/assets/eb6b4f2c-bacb-489c-b3c3-66b89e13576c)
> 
> But I ask [@agent](https://github.com/agent) Checking what are the available databases? The agent cannot connect to my SQL. ![image](https://github.com/user-attachments/assets/cac8b527-d954-4a9d-b4bd-556f0e43b7f6)
> 
> I have used python to connect to my MySQL and can read the data normally. **How can I use the agent to read the MySQL data?** Is there a step I'm missing? Thanks

Hello，Have you sloved this issue？ If so，can you tell me how to do it？

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/agent/usage#what-is-sql-agent-and-how-to-use-it

Your agent never ever _tried_ to call the SQL agent skill - see the image on this page. You should have seen several tool call outputs here that would show the agent doing actions on the DB.

https://docs.anythingllm.com/agent-not-using-tools#llm-is-refusing-to-even-detect-or-call-a-tool-at-all
