### ISSUE TITLE
[BUG]: mistral-nemo-minitron-8b-instruct results in endless loop (LMStudio LLM Provider) / How to disable system prompt?

### ISSUE THREAD

**Issue by joomgallerytestit** [Mintplex-Labs/anything-llm#2562]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hi,

when I use LMStudio as an LLM provider and load ”
**lmstudio-community/mistral-nemo-minitron-8b-instruct**” in LMStudio,
 I end up in an endless loop in the chat in AnythingLLM. 

Because every few sentences there is then ‘**<extra_id_1>User**’ and a question and then **<extra_id_1>Answer**...

What is this “extra_id_1” all about? How can I control or disable it in AnythingLLM?

Apparently, at least one problem has nothing to do with AnythingLLM, but with the prompt format of XY:
“ Prompt format <extra_id_0>System
{system_prompt}

<extra_id_1>User
{prompt}
<extra_id_1>Assistant
”
Unfortunately, I am not yet sufficiently familiar with the subject matter to know how to solve the problem I have described.

A similar problem seems to be that some LLMs simply do not support a system prompt and throw an error in the AnythingLLM chat if a system prompt is stored in the AnythingLLM workspace. Even if the field for the system prompt is empty. How can I disable system prompt passing in AnythingLLM?

Thanks in advance and best regards
Joomgallerytestit

**Comment by timothycarambat** [comment]
This should be fixable by the chat template specification in LMStudio, no? Since this is a model-specific issue. Also, what quantization are you running in LMStudio because behaviors like outputting its own stop/chat tokens are a huge problem when a small model (8B) is over-quantized.

With even removal of a system prompt it would likely still be broken and spitting out pure nonsense

**Comment by joomgallerytestit** [comment]
I want to build a ggod local system for RAG! 

Since “Chat Mode” is set to Query, quantization **Q4** should not play a major role.

In my tests I had several LLMs that threw an error because they did **not support system prompts**. So it would be important to be able to deactivate this in AnythingLLM.
