### ISSUE TITLE
[BUG]: Error: SQLite database error

### ISSUE THREAD

**Issue by tifDev** [Mintplex-Labs/anything-llm#2564]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Container crashes while starting

### Are there known steps to reproduce?

1. Launch the container:
```

export STORAGE_LOCATION=$HOME/anythingllm && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v "${STORAGE_LOCATION}:/app/server/storage" \
-v "${STORAGE_LOCATION}/.env:/app/server/.env" \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm

```

2. Crashes
3. Docker logs
```

[collector] info: Collector hot directory and tmp storage wiped!
[collector] info: Document processor app listening on port 8888
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 417ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)

import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()


See other ways of importing Prisma Client: http://pris.ly/d/importing-client

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

26 migrations found in prisma/migrations

Error: SQLite database error
attempt to write a readonly database
   0: sql_schema_connector::sql_migration_persistence::initialize
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/sql_migration_persistence.rs:14
   1: schema_core::state::ApplyMigrations
             at schema-engine/core/src/state.rs:201

```

**Comment by shatfield4** [comment]
It looks like you are on Linux/macOS.

Do you have multiple containers running AnythingLLM at the same time? This can lock the db and make it read only if 2 containers are trying to access the db at the same time. Another thing that can cause issues like this is if you have the db open in something like DB Browser for SQLite. This can also lock the db and prevent AnythingLLM from writing to it.

**Comment by lrbmike** [comment]
the same issue
```shell
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db
```

**Comment by bogorad** [comment]
same error. very sloppily made docker-compose

**Comment by Reis-A** [comment]
this is a permission error. I ran into this when I ran the installation file on ubunut24 as root.
the folder $HOME/anythingllm on the docker host has to have write permission... 
now the question is which user is needed. for me it was the admin user and not root (even though I run docker as root.)
Maybe this can be clarified. but giving the permission 0777 to the anythingllm folder aswell as to the .env file solves the problem

**Comment by lrbmike** [comment]
> this is a permission error. I ran into this when I ran the installation file on ubunut24 as root. the folder $HOME/anythingllm on the docker host has to have write permission... now the question for which user .. for me it was the admin user and not root (even though I run docker as root.) Maybe this can be clarified. but giving the permission 0777 to the anythingllm folder aswell as to the .env file solves the problem or once u know the user that needs write permission go for a chgrp and a 0770

yes, this is a permission error. I solved this problem by giving the directory 777 permissions.

**Comment by gitwittidbit** [comment]
Agree, 777 solves the problem. But I would rather keep the permissions more strict. So does anyone know which user needs to have write permissions on that folder (other than root)?

**Comment by timothycarambat** [comment]
The same one as the docker user, which if you installed it according to dockers instructions is should be the current user

**Comment by nickolasdeluca** [comment]
I'll leave this here in case anyone runs into issues with permission for the SQLite database.

In my scenario, I'm running the container on an Oracle Cloud Instance, so, since Docker containers often run as the first non root user, which is opc in this scenario, you have to chown the created dir to opc or 1000.

```bash
sudo chown -R 1000:1000 anythingllm
```

or 

```bash
sudo chown -R opc:opc anythingllm
```

That did the trick for me.

**Comment by bilogic** [comment]
The bug is that `docker compose up` creates the storage folder as `root:root`, when it should have been `1000:1000`
