### ISSUE TITLE
[BUG]: "Show chat window scrollbar" doesn't do anything.

### ISSUE THREAD

**Issue by DangerousBerries** [Mintplex-Labs/anything-llm#2569]
### How are you running AnythingLLM?

Docker (local)

### What happened?

There is no scrollbar in the thread chat no matter if the setting is on or off.

**Comment by z1588919** [comment]
I found that the latest content cannot be automatically refreshed under the chat window, and I need to use the mouse wheel to scroll.

**Comment by vikasbodke** [comment]
facing the same issue on Docker hosted on cloud provider as well
