### ISSUE TITLE
[BUG]: Failed to analyze images using OpenAI api

### ISSUE THREAD

**Issue by Jason202268** [Mintplex-Labs/anything-llm#2579]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When I uploaded images, the response is just like, "I'm sorry, but I can't process images directly. However, you can use OCR (Optical Character Recognition) software or apps to extract text from photos. Would you like recommendations for some OCR tools?"

**Comment by timothycarambat** [comment]
This is an LLM refusal, not an AnythingLLM error. The LLM probably does not support vision.
Currently for OpenAI only a few models support vision and if it is supported, we pass through the image.
https://github.com/Mintplex-Labs/anything-llm/blob/0bb47619dcdbbfc6af8a1c0e9a8b4e3d1b6f99bb/server/utils/AiProviders/openAi/index.js#L80-L95
