### ISSUE TITLE
[FEAT]: What is the Retrival Rule of AnythingLLM

### ISSUE THREAD

**Issue by zu0feng** [Mintplex-Labs/anything-llm#2580]
### What is the Retrival Rule of AnythingLLM and where I can see it?

What is the Retrival Rule of AnythingLLM and where I can see it?
I want to use another way to realize retriving in the process of RAG. Can I change the retrival rule of Anythingllm into my rule.
How can I change it if I can.

**Comment by timothycarambat** [comment]
It is [similaritySearch ](https://github.com/Mintplex-Labs/anything-llm/blob/0bb47619dcdbbfc6af8a1c0e9a8b4e3d1b6f99bb/server/utils/vectorDbProviders/lance/index.js#L70) and as long as the provider has options for others you can change that function and its params as needed
