### ISSUE TITLE
[FEAT]: The ability to route saved conversations to a scalable storage database

### ISSUE THREAD

**Issue by danielrosehill** [Mintplex-Labs/anything-llm#2583]
### What would you like to see?

I'd love to be able to store conversations in a custom endpoint. 

This might allow the conversation history to be mined and explored in parallel systems like wikis / knowledge management tools.

For this to work effectively, individual outputs would need to be batched into their constituent conversations. 

Logical databases for storage might be Postgres or MongoDB.

**Comment by timothycarambat** [comment]
> I'd love to be able to store conversations in a custom endpoint.

Could you not export the information from the API endpoint `/v1/system/export-chats` and upload to your db of choice?

As far as other databases go, this is capture in https://github.com/Mintplex-Labs/anything-llm/issues/2574

The reason for SQLite is it is zero config or set up and the docker setup flows down into the desktop app via the `desktop` branch it is critical we don't ask people installing a desktop app "Okay, now first set up a PostgreSQL db" - which is a nonstarter for that userbase.

There are some subtle differences between SQLite/PG, but they prisma schemas should be able to port for the most part
