### ISSUE TITLE
[BUG]: If there is a file name that is too long, I cannot click the pin.

### ISSUE THREAD

**Issue by xianghappy** [Mintplex-Labs/anything-llm#2587]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/user-attachments/assets/2171076d-6848-4c5b-a88d-3a10c5918fe9)
If there is a file name that is too long, I cannot click the pin.

**Comment by shatfield4** [comment]
I cannot repro this and from the screenshot I can tell that this is most likely an older version of AnythingLLM Desktop. In the latest version we have select checkboxes on each row for moving around multiple files and we truncate more of the text so it does not overlap anymore. 

Please update to the latest version and this will be resolved.
