### ISSUE TITLE
[BUG]: Problem using VoyageAI embedders  

### ISSUE THREAD

**Issue by PetrAPConsulting** [Mintplex-Labs/anything-llm#2593]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When using embedders **voyage-3** or **voyage-3 lite** picked up from the VoyageAI embedder choices (Intel based Mac AnythingLLM-desktop app), I received information from VoyageAI API usage statistics that was used model voyage-01 model instead. 
<img width="1849" alt="API usage statistics" src="https://github.com/user-attachments/assets/18228668-966d-475b-a1c2-52696254d8ee">
<img width="983" alt="App embedder settings" src="https://github.com/user-attachments/assets/ed8efcf9-ec8e-4c11-bbe9-3ce223196c17">

**Comment by timothycarambat** [comment]
I have responded to this over email, but those models keys are directly from their docs and all we do is passthrough the model used. Can you open the [desktop apps storage folder](https://docs.anythingllm.com/installation-desktop/storage)

Then open the file named `.env` and paste exactly what value is for the `EMBEDDING_MODEL_PREF` line item in the env. Unless VoyageAI does some kind of fallback for voyage-3 to voyage-01 we are passing exactly what is provided to us.

If the `EMBEDDING_MODEL_PREF` ENV is indeed as you see in the AnythingLLM UI you need to contact VoyageAI - as their dashboard clearly does not reflect the proper model used.

When attempting to repro I can confirm that the model key passed is indeed relayed to the Voyage API. So I am unable to repro this and its possible the dashboard on Voyage is incorrect

**Comment by timothycarambat** [comment]
Fixed, will be in next desktop version. Upstream dep changed interface and that was the result and somehow did not throw errors in the provider.
