### ISSUE TITLE
Transform application into Dockerized application

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#26]
Instead of 3 separate folders - we can package the entire application into a known environment to prevent conflicting library installs so those who run Docker on their machine can participate in the fun!

credit: @ronivaldo

connect #25

**Comment by frasergr** [comment]
You mentioned here looking at getting an Ubuntu environment setup, have you gone through that process yet? I think reworking the packages to work on all systems will need to come before Dockerizing.

**Comment by timothycarambat** [comment]
Resolves by #34
