### ISSUE TITLE
[BUG]: JavaScript error occured in the main process - Launching AnythingLLM on Windows

### ISSUE THREAD

**Issue by OctavoPE** [Mintplex-Labs/anything-llm#2600]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Having finished the setup wizard, I went to launch AnythingLLM but I get this JavaScript error. 

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOTDIR, not a directory
     at createError (node: f?)
     at Object.mkdirSync (node:electron/js2c/asar_bundle2:12581)
     at Object.<anonymous>
[C drive location omitted]\AnythingLLM\resources\app.asar\di....:34348
at Module._compile (nodeinternal/modules/cjs/loader:1271:14)
at Object.js (node:internal/modules/cjs/loader: 1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at node:internal/modules/cjs/loader:967:12
at Function._load (node:electron/js2c/asar_bundle:2:13327)
at node:electron/js2c/browser_init:2:122709
at node:electron/js2c/browser_init:2122912
`

This was version v1.6.9 for Windows from AnythingLLM.com

### Are there known steps to reproduce?

I downloaded the version above, waited for the setup wizard to finish, and I receive this when trying to launch it.

**Comment by timothycarambat** [comment]
Here is the previous version, can you confirm if this occurs on 1.6.8?
https://s3.us-west-1.amazonaws.com/public.useanything.com/legacy/1.6.8/AnythingLLMDesktop.exe

**Comment by timothycarambat** [comment]
Some more information is required since this seems its not consistent across every install. When you install are you using the suggested default install location or are you changing that? 

Just trying to consider all possible set ups that could be blocking boot

**Comment by timothycarambat** [comment]
Im am unable to replicate on a totally fresh install of windows.

When you open the `AppData/Roaming/AnythingLLM` folder do you see something like this?
![Screenshot 2024-11-08 104303](https://github.com/user-attachments/assets/aa43480b-dc3c-4acd-8dfa-f73cfc6c07b9)

Example location is `C:\Users\USR\AppData\Roaming\anythingllm-desktop\storage`

**Comment by OctavoPE** [comment]
`appdata/roaming/anythingllm-desktop` is empty for me except for a single `1kb` file named `Local State`.

I installed it once more and didn't pick any custom location, I let ALLM install where it wanted to be - same as the first time I installed it. Same error. Running it in admin mode also didn't do anything, obviously, we can see that half its guts are missing for some reason. 

I'm trying the previous version `1.6.8` of the desktop version now and will report back.

In the meantime, I can confirm I got the docker version of ALLM to work.

**Comment by OctavoPE** [comment]
Just as a small note, if I can get `1.6.8` to work, I'll try more things on the new version. I forgot to mention that for `1.6.9`, both times I installed it as single user instead of for everyone, (I'm the only user on my machine, so either choice is fine), and I didn't run the installer as an administrator.

**Comment by OctavoPE** [comment]
Reporting back: I'm sad to say I couldn't get `1.6.8` to work either. Same error, the folder continues to be empty with just a single `Local State` file inside. 

Back to version `1.6.9` installed in Administrator mode and choosing the All Users version (again, all without changing the installation location) it did not work either. 
![image](https://github.com/user-attachments/assets/61e4f7f3-49a7-44e6-a011-fb267f0a4f7d)
(I receive no errors during installation - only this when trying to run it)

For some reason, it is not happy with my machine. Thankfully the docker version of ALLM works! 

Since I'm okay with the docker version, I won't really pursue this any longer. However, I'd be more than happy to continue to help if this is something you'd want resolved and want to chase. I understand completely if this is a minor non issue with no priority or what you perceive to be a PEBCAK error. So no worries. Thanks for your help!

**Comment by timothycarambat** [comment]
@OctavoPE Im glad you were able to get the docker version running, I'm sure you cannot be the only person on earth that comes across this issue so i want to see how we can solve it. If i have any more questions Ill post them here but the above helps a massive amount!

**Comment by timothycarambat** [comment]
@OctavoPE  - Okay, one final favor. I made a build that should resolve this issue for you.

https://s3.us-west-1.amazonaws.com/public.useanything.com/staging/AnythingLLMDesktop.exe

This is not an official release since its `1.6.10-beta` and works on my Windows machine, but it already did prior so if it works on yours we can call it solved.

**Comment by OctavoPE** [comment]
Hi, @timothycarambat,
Happy to report that `1.6.10-beta` worked. Installed it once in administrator mode to _all users_ and ALLM opened. 
![image](https://github.com/user-attachments/assets/eb18be0d-0cfc-483a-b26b-cbffd12f227d)

Thanks for your amazing work!

**Comment by timothycarambat** [comment]
Thank you for confirming that for me! Case closed. Will push next release

**Comment by timothycarambat** [comment]
Just updated the live 1.6.9 to reflect that singular change - you can stay on your beta or swap back, but all set
