### ISSUE TITLE
[DOCS]: Windows Desktop installer has undocumented / missing command-line switches

### ISSUE THREAD

**Issue by geeklimit** [Mintplex-Labs/anything-llm#2607]
### Description

The "AnythingLLMDesktop.exe" installer seems to take /currentuser, but doesn't have a /?, /h or /help file (I was looking for silent install. 'AnythingLLMDesktop.exe /currentuser /S' acts like it's silent-installing but doesn't actually install)

"%LOCALAPPDATA%\Programs\AnythingLLM\Uninstall AnythingLLM.exe" can take /currentuser and /S for silent uninstall.

**Comment by timothycarambat** [comment]
Undocumented! I didnt even know that existed 😆!

Either way, we use Electron-builder so the NSIS installer has the typical args (except apparently the ones you expect?)

A silent install would require `/D` for the path or else it cannot continue
`\AnythingLLMDesktop.exe /currentuser /S /D="C:\Users\USER\AppData\Local\Programs\AnythingLLM"`

**Comment by desk7** [comment]
@timothycarambat is there a flag to skip the popup about Meeting Assistant during installation?
