### ISSUE TITLE
[FEAT]: Support Claude 3.5 Sonnet 2024-10-22

### ISSUE THREAD

**Issue by nicodv** [Mintplex-Labs/anything-llm#2613]
### What would you like to see?

The Claude LLM dropdown does not yet support the latest and greatest October model: https://www.anthropic.com/news/3-5-models-and-computer-use

**Comment by timothycarambat** [comment]
Already completed via 5aa79128f7d935bf42fdd133c523337f041d81b0

**Comment by PierrunoYT** [comment]
> Already completed via [5aa7912](https://github.com/Mintplex-Labs/anything-llm/commit/5aa79128f7d935bf42fdd133c523337f041d81b0)

It's not showing up via Anthropic
