### ISSUE TITLE
[BUG]: Missing library on startup

### ISSUE THREAD

**Issue by factor3** [Mintplex-Labs/anything-llm#2619]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I installed AnythingLLM following the instructions provided at:

    https://docs.anythingllm.com/installation-desktop/linux#install-using-the-installer-script

this is installed on a system running Ubuntu V22.04.

When I start the start script, I get the following failure message:

 `/home/mainuserAnythingLLMDesktop/anythingllm-desktop/anythingllm-desktop: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory`

What is this library and how can I get AnythingLLM to start up?

### Are there known steps to reproduce?

1. Download the LLMAnything App as instructed.
2. Enter "~/AnythingLLMDesktop/start" and press ENTER.
3. See the error.

**Comment by timothycarambat** [comment]
This enables Electron to launch a browser process, most distros have this installed since it is a common dep
`sudo apt-get install libatk1.0-0` is how you install this dependency

**Comment by FY21TH** [comment]
> This enables Electron to launch a browser process, most distros have this installed since it is a common dep `sudo apt-get install libatk1.0-0` is how you install this dependency

It not works in centos 7

**Comment by timothycarambat** [comment]
CentOS uses `yum` - it was just an example.
