### ISSUE TITLE
[BUG]: http://localhost:3001/settings/embedding-preference , white page

### ISSUE THREAD

**Issue by zhenda-hub** [Mintplex-Labs/anything-llm#2620]
### How are you running AnythingLLM?

Docker (local)

### What happened?

click embedder, then will become a white page

### Are there known steps to reproduce?
I use docker compose  started anything-llm.

click  open setttings -> AI Providers -> embedder, then will become a white page

**Comment by timothycarambat** [comment]
You probably have an invalid setting from whatever your docker-compose has set for the ENV. What embedder do you have set? This is a config issue as unable to replicate on current production build.

**Comment by zhenda-hub** [comment]
I have no .env file. just use compose.yaml to run it. 

I want to know which is the default embedder. 

I could not set embedder.

**Comment by timothycarambat** [comment]
`native` is. In your compose YAML, you have to specify some ENVIRONMENT VARS and `EMBEDDING_ENGINE: "native"` needs to be one.
