### ISSUE TITLE
[BUG]: Cannot move window on Mac if already focused

### ISSUE THREAD

**Issue by zareami10** [Mintplex-Labs/anything-llm#2630]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

If AnythingLLM's window is already focus, you can't move/drag it at all. However if it's already unfocused, it can be dragged normally.

- App Version: 1.6.9
- OS Version: 14.7.1

**Comment by zareami10** [comment]
Ah, this seems to happen only within the initial screen...

**Comment by timothycarambat** [comment]
Patched this in the upcoming 1.6.10 release - on onboarding you cannot move the window as well!
