### ISSUE TITLE
[FEAT]: Any port for API access on Desktop? (for integration with Word Add-in)

### ISSUE THREAD

**Issue by GPTLocalhost** [Mintplex-Labs/anything-llm#2636]
### What would you like to see?

Thank you for this great repo. Is there any port for API access on Desktop version? I have integrated the following with the Docker version with port 3001 ([demo here](https://gptlocalhost.com/demo/)), but I couldn't find the port for Desktop. Is it feasible?  Thank you for any advice. 

- [GPTLocalhost](https://gptlocalhost.com/demo/) - A local Word Add-in for you to use local LLM servers in Microsoft Word. Alternative to "Copilot in Word" and completely local.

**Comment by timothycarambat** [comment]
Saw you got it figured out. Port on docker is whatever you set as the entrypoint port [`-p 3001:3001`](https://docs.anythingllm.com/installation-docker/local-docker#recommend-way-to-run-dockerized-anythingllm).

Typically 3001

**Comment by GPTLocalhost** [comment]
Thank you for your reply, but I mean the following "Desktop" version instead of "Docker" version. 

> https://anythingllm.com/desktop

Port 3001 works well for Docker but not Desktop. I wonder whether it is feasible.
