### ISSUE TITLE
[BUG]: When I leave a chat that's still getting a response, then go back, it has disconnected.

### ISSUE THREAD

**Issue by phazei** [Mintplex-Labs/anything-llm#2640]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I asked for a response, then went to another chat, then went back.

I'd expect it to keep the socket open unless I hit stop.  That way I'm not stuck on the chat screen waiting for a response when I could have other conversations going.  It really slows down it's utility.

### Are there known steps to reproduce?

Just chat and ask for something that would return a long response.  While it's responding, leave the chat, then go back.

**Comment by tmas** [comment]
@timothycarambat Sorry to necro an old issue, but I'm experiencing the issue and I can confirm that the behavior @phazei reported (the conversation is lost in AnythingLLM but inference continues and the response from the LLM goes nowhere) is still happening, at least with LM Studio.

This is a bit of a pain when waiting for models to load, as I sometimes click away to read through another chat and then go back to find that my prompt has been lost along with the generated response from the LLM.

Even if the inference result is still discarded (I wouldn't be surprised if some inference providers genuinely support cancelling the request), maybe the prompt could be saved? That could potentially involve saving a "pending" state on the thread, or showing the user message as sent and handling a state where the most recent message is from the user and displaying a "Generate response" button to re-send the inference request.
