### ISSUE TITLE
[FEAT]: hpp (header for a C++ code file) MIME addition

### ISSUE THREAD

**Issue by grantcarthew** [Mintplex-Labs/anything-llm#2647]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

In the "My Documents" management window, I'm trying to upload a `.hpp` file and I get the following error:

"File extension .hpp not supported for parsing and cannot be assumed a text file"

Code reference: https://github.com/Mintplex-Labs/anything-llm/blob/727d8027796785555f1c8308a37272a6ec0de34e/collector/processSingleFile/index.js#L60

I've raised a PR for the upstream project **mime**:

https://github.com/broofa/mime/pull/318

If this doesn't get merged, then we could add `hpp` to the **setOverrides** list:

https://github.com/Mintplex-Labs/anything-llm/blob/727d8027796785555f1c8308a37272a6ec0de34e/collector/utils/files/mime.js#L19

**Comment by timothycarambat** [comment]
Related to #2638
