### ISSUE TITLE
[FEAT]: Any port for API access for "Desktop" version (not "Docker" version)? (for integration with Microsoft Word)

### ISSUE THREAD

**Issue by GPTLocalhost** [Mintplex-Labs/anything-llm#2650]
### What would you like to see?

Thank you for the following reply:

> https://github.com/Mintplex-Labs/anything-llm/issues/2636#issuecomment-2483731909

But I mean the following "Desktop" version instead of "Docker" version.

> https://anythingllm.com/desktop

Port 3001 works well for Docker but not Desktop. I wonder whether it is feasible.

**Comment by GPTLocalhost** [comment]
I had tried AnythingLLM 1.6.7 Desktop version but port 3001 didn't work. It's workable to create an API key, but it seems nowhere to use it. Is there any document I can dig into? Thank you for your advice.

**Comment by timothycarambat** [comment]
If you are on the API key page, there should be a link to "View documentation" - this will open the local documentation/swagger docs - this will or _should_ show the endpoint as well. 

its worth noting that if 3001 is occupied the desktop app will port hunt until a free port is found, which is likely the case here.

**Comment by GPTLocalhost** [comment]
Indeed, port 3001 works on Desktop version. The following helps. Thanks a lot.

> "View documentation" - this will open the local documentation/swagger docs - this will or should show the endpoint as well.
