### ISSUE TITLE
[FEAT]: Please add support for gemini-exp-1114

### ISSUE THREAD

**Issue by DangerousBerries** [Mintplex-Labs/anything-llm#2657]
### What would you like to see?

https://ai.google.dev/gemini-api/docs/models/experimental-models

It's the best free model that's available through API right now.

**Comment by DangerousBerries** [comment]
lol gemini-exp-1121 just came out, the merged commit doesn't look too complicated, maybe in the future we could just type in the model name?

**Comment by DangerousBerries** [comment]
> What we need is a combo box so it can be dropdown + input override

That would be great, so will an update in the meantime lol.

**Comment by DangerousBerries** [comment]
> What we need is a combo box so it can be dropdown + input override

Thank you for the quick update, although I'm getting this error message:

[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-exp-1121:streamGenerateContent?alt=sse: [404 Not Found] models/gemini-exp-1121 is not found for API version v1, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.

It's strange because here he says it's available through API here: https://x.com/OfficialLoganK/status/1859667244688736419

**Comment by timothycarambat** [comment]
62be0cd0c5b28ad781c562685bce640782fccf74

**Comment by DangerousBerries** [comment]
gemini-exp-1206 just released with 2 million tokens. 😅
