### ISSUE TITLE
[FEAT]: How do I compile the desktop client? Does it support this?

### ISSUE THREAD

**Issue by wangwei15-cd** [Mintplex-Labs/anything-llm#2668]
### What would you like to see?

How do I compile the desktop client? Does it support this?

**Comment by timothycarambat** [comment]
You need to make your own wrapper (its just a simple electron wrapper) - but the branch you are looking for is the `desktop` branch

**Comment by wangwei15-cd** [comment]
> You need to make your own wrapper (its just a simple electron wrapper) - but the branch you are looking for is the `desktop` branch
"After the compilation is complete, there is a dist_server folder and a dist folder under frontend. How do I package it using Electron? The entry point is _index.html, but how do I associate the backend files. 
Thank you
