### ISSUE TITLE
[BUG]: install was renamed to pip-install

### ISSUE THREAD

**Issue by Trisogene** [Mintplex-Labs/anything-llm#2669]
### How are you running AnythingLLM?

Docker (local)

### What happened?

In the docker local version when you do
$ docker-compose up -d --build
You are gonna get the error
No matching distribution found for install==1.3.5

This is because the install package was renamed to pip-install
It should be changed in the requirements.tsx

**Comment by timothycarambat** [comment]
Wrong repo? We dont have `pip` or `python` anywhere in our Dockerfile or even a requirements.txt?
