### ISSUE TITLE
[FEAT]: Can the font size of the chat input box be increased?

### ISSUE THREAD

**Issue by AezwxLOkCzw** [Mintplex-Labs/anything-llm#2670]
The current font is too small.

<img width="659" alt="image" src="https://github.com/user-attachments/assets/7484390e-6284-4df2-a72a-c122707a0928">

**Comment by AezwxLOkCzw** [comment]
Could you please package an application for me on macOS?
I do need it.

**Comment by timothycarambat** [comment]
@AezwxLOkCzw It will come out in the next release (next week). We do not do intermediate builds for single merges unless they are fixing critical bugs

**Comment by AezwxLOkCzw** [comment]
> @AezwxLOkCzw It will come out in the next release (next week). We do not do intermediate builds for single merges unless they are fixing critical bugs

okay, thank you very much.
