### ISSUE TITLE
can not create first workspace

### ISSUE THREAD

**Issue by jamsnrihk** [Mintplex-Labs/anything-llm#268]
I git lastest version of anything-llm, and success build and running a docker.
but get following error message when try to create the first new workspace.
![cap4](https://github.com/Mintplex-Labs/anything-llm/assets/134043330/bb514e13-f328-4bae-80e0-6b3646bb9590)

**Comment by timothycarambat** [comment]
Visit your container URL with `/api/migrate` appended to the end
