### ISSUE TITLE
[BUG]: Failed to fetch logo: TypeError: URL constructor: /api/system/logo is not a valid URL.

### ISSUE THREAD

**Issue by lewismacnow** [Mintplex-Labs/anything-llm#2693]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Navigating to the Logo change section, and trying to change the logo, produces an error:

Failed to fetch logo: TypeError: URL constructor: /api/system/logo is not a valid URL.

### Are there known steps to reproduce?

https://github.com/user-attachments/assets/5e09307e-a451-426d-8fbd-43e5f0c69c79

**Comment by timothycarambat** [comment]
resolved by f6ab3313c7bf10da18a60669dfa3df7e22ef53ba
