### ISSUE TITLE
[BUG]: i can not log in my account

### ISSUE THREAD

**Issue by caiot744** [Mintplex-Labs/anything-llm#2694]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

for some reason, when i insert the credentias it says: Error: Could not validate login.

i already refresh the stack on docker, somebody can help´me?

![Screenshot_18](https://github.com/user-attachments/assets/dd956e9f-0af9-4254-a4d0-835d2dacbed0)

**Comment by timothycarambat** [comment]
This is not the place to post this issue. If you are in password mode your password is the ENV for `AUTH_TOKEN` in the storage folder `.env` file.
