### ISSUE TITLE
The issue encountered when using FastAPI to call the /document/upload endpoint.

### ISSUE THREAD

**Issue by qiqi0308** [Mintplex-Labs/anything-llm#2696]
I am unable to test the /document/upload endpoint directly on http://127.0.0.1:3001/api/docs/ due to network issues. However, when sending an upload request directly in Postman, there is no Chinese character garbling. The following is the case.
![fa4a173e41a63eb06c5035c6881ebba](https://github.com/user-attachments/assets/1ff9c5aa-7dfb-4bbb-a094-f4093d3b01da)
But when I write FastAPI code to call the original interface, it never succeeds, and the test results are always garbled.
![ddf71d665f232fbdfc7fd7d9df2d50a](https://github.com/user-attachments/assets/2c38ec76-8cfd-4d15-a8ab-ecadd2da2fec)
 the test results are always garbled.
![2cb19b4ed5591787f0b0b00de4fca6c](https://github.com/user-attachments/assets/aa1621a7-2456-4035-b6f8-9f0a56a7de1d)

**Comment by qiqi0308** [comment]
what should i do？

**Comment by timothycarambat** [comment]
The headers in Postman are the key. After sending a successful request check the request headers that were generated and use those in your Python code. The key is the content type and charset that is sent. Since `requests` does not apply auto-generated headers like Postman that is what you need to add.

**Comment by qiqi0308** [comment]
I test your the /document/upload endpoint again,i find response is error,i dont know how to solove it .
![1732425474701](https://github.com/user-attachments/assets/17665cc5-361d-4817-9339-daf6570c5c0b)

**Comment by qiqi0308** [comment]
> The headers in Postman are the key. After sending a successful request check the request headers that were generated and use those in your Python code. The key is the content type and charset that is sent. Since `requests` does not apply auto-generated headers like Postman that is what you need to add.
I still have trouble in this.when i post my url ,both requests and https would automatically generate the correct Content-Type and boundary parameters. I find yours header Content-Type is application/json; charset=utf-8. Sadly to say I could not understand why I post with header  Content-Type application form-data . hope to your reply
![1732431235458](https://github.com/user-attachments/assets/40654fc0-a705-4bae-a42f-82da094ae8f6)
