### ISSUE TITLE
Litellm integration request

### ISSUE THREAD

**Issue by ranjancse26** [Mintplex-Labs/anything-llm#271]
I think it's a good idea to integrate with the Litellm as it provides an easy to integrate with 100+ LLMs.

https://github.com/BerriAI/litellm

LLM as a drop-in replacement for GPT. Use Azure, OpenAI, Cohere, Anthropic, Ollama, VLLM, Sagemaker, HuggingFace, Replicate (100+ LLMs)

cc @ishaan-jaff

**Comment by timothycarambat** [comment]
Does not support NodeJS env for all inferencing models - would love to but the support isn't there at this time. Closing for now.
