### ISSUE TITLE
still can not create first workspace

### ISSUE THREAD

**Issue by jamsnrihk** [Mintplex-Labs/anything-llm#272]
I tried access http://localhost:3001/api/migrate, and try to create the first workspace, but still get following error log:

The table `main.system_settings` does not exist in the current database.
2023-10-08 23:01:29 anything-llm  | prisma:query INSERT INTO `main`.`system_settings` (`label`, `value`, `createdAt`, `lastUpdatedAt`) VALUES (?,?,?,?) ON CONFLICT  (`label`) DO UPDATE SET `value` = ? WHERE (`main`.`system_settings`.`label` = ? AND 1=1) RETURNING `id` AS `id`, `label` AS `label`, `value` AS `value`, `createdAt` AS `createdAt`, `lastUpdatedAt` AS `lastUpdatedAt`
2023-10-08 23:01:29 anything-llm  | FAILED TO UPDATE SYSTEM SETTINGS 
2023-10-08 23:01:29 anything-llm  | Invalid `prisma.system_settings.upsert()` invocation:
2023-10-08 23:01:29 anything-llm  | 
2023-10-08 23:01:29 anything-llm  | 
2023-10-08 23:01:29 anything-llm  | The table `main.system_settings` does not exist in the current database.

anyway to manual create the `main.system_settings‘ table?

**Comment by timothycarambat** [comment]
Before you run the docker container are you running the setup script? It will create your database and even run the migration. When docker builds it will reference the host-system DB and load on top of that. If you dont run that script prior (or haven't run it since the prisma migration) you will have a broken docker instance.

**Comment by timothycarambat** [comment]
You may need to run from the host machine `yarn prisma:generate` and then `yarn prisma:migrate`. Then rebuilding of the docker container will not exit from the system being unable to communicate with the DB.

https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/prisma/PRISMA.md

**Comment by jamsnrihk** [comment]
@timothycarambat thanks timothy, it works after I run yarn prisma:generate and yarn prisma:migrate.
after i upload some documents and try to chat with it, it can generate the answer, but the reference showing in some strange encoding character, not show original one (Chinese).
please kindly advise.
![cap5](https://github.com/Mintplex-Labs/anything-llm/assets/134043330/65823320-c008-451a-997a-d2a12d1e4b1e)

**Comment by timothycarambat** [comment]
Related to this PR which has nt been merged:
https://github.com/Mintplex-Labs/anything-llm/pull/169

**Comment by timothycarambat** [comment]
That will resolve the weird encoding on filenames. Will work to get that change merged. I think it has side effects which is why it has sat out so long

**Comment by nyavana** [comment]
HI, I'm running docker on unraid which yarn is not available. Is there any workaround which I can do manual initiation for prisma?

**Comment by jamsnrihk** [comment]
> That will resolve the weird encoding on filenames. Will work to get that change merged. I think it has side effects which is why it has sat out so long

I am not mean the file name not encoding, i mean the source contents not encoding, it should be chinese. but currently, showing some strange things.
