### ISSUE TITLE
[BUG]: There is no window to enter the interface of downloading the model, and the download of the model cannot be cancelled. It is an endless loop.

### ISSUE THREAD

**Issue by w-h-w** [Mintplex-Labs/anything-llm#2723]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![Snipaste_2024-11-26_21-06-19](https://github.com/user-attachments/assets/e47565a4-a9c2-4d37-8fb1-c6f44bd6c195)
Is this a bug? This model can't be downloaded, and there is no cancel interface. I can't select any other model I want to download. According to the prompts, unless the model is downloaded, it may be my network problem. This model can't be downloaded at all, and there is no download interface to cancel. It's just an endless loop, downloading this model forever and I can't cancel it.

**Comment by timothycarambat** [comment]
I am not sure what OS you are on, but you clipped the top bar out of the screenshot and the cancel button and progress shows in the top right
<img width="1612" alt="Screenshot 2024-11-26 at 8 22 33 AM" src="https://github.com/user-attachments/assets/e55cf9db-190b-4e4b-8e2e-60ea5b0f60b3">
