### ISSUE TITLE
[FEAT]: Is this because I didn't use it correctly, or is it a problem with the software?

### ISSUE THREAD

**Issue by w-h-w** [Mintplex-Labs/anything-llm#2724]
![图片](https://github.com/user-attachments/assets/bc85cc27-0443-40cf-8572-df4bf63fac2d)
I laughed. The query function of this software is a joke. The answer is wrong,
I uploaded a 400-page document, and the output directory cannot be completed. Is there a problem with my settings?
![图片](https://github.com/user-attachments/assets/801ba239-78e8-49c1-9654-96e131c9db4d)

**Comment by timothycarambat** [comment]
You are using it wrong. Its not magic https://docs.anythingllm.com/llm-not-using-my-docs
