### ISSUE TITLE
[FEAT]: Could you please add a spelling checker to AnythingLLM during input?

### ISSUE THREAD

**Issue by AezwxLOkCzw** [Mintplex-Labs/anything-llm#2725]
ditto

**Comment by timothycarambat** [comment]
<img width="362" alt="Screenshot 2024-11-26 at 9 58 35 AM" src="https://github.com/user-attachments/assets/e2a2435d-2866-4cea-a380-a5eab8dcf46c">
<img width="384" alt="Screenshot 2024-11-26 at 9 58 40 AM" src="https://github.com/user-attachments/assets/fbe17b4f-3f3a-4fc0-b124-bc83bbd40300">
