### ISSUE TITLE
[BUG]: AnythingLLM quit unexpectedly

### ISSUE THREAD

**Issue by shiyanalex** [Mintplex-Labs/anything-llm#2728]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hi,
I’m running macOS Catalina 10.15.7 on an Intel Macbook, and I get an unexpected error when trying to open the app. Is this version of macOS supported? Any advice would be appreciated.

<img width="1007" alt="Screenshot 2024-11-28 at 00 43 00" src="https://github.com/user-attachments/assets/7517cb83-964f-42cc-9eff-501d8e13858b">

**Comment by timothycarambat** [comment]
Catalina is quite old and im fairly certain our build does not support it. Upgrade the OS (if possible). We are usually targeting the latest major. We work on intel and silicon and I'm on an Intel Mac on Sonoma and the DMG works as is.
