### ISSUE TITLE
OpenAI::createChatCompletion failed with: Request failed with status code 401

### ISSUE THREAD

**Issue by ilkkaruso** [Mintplex-Labs/anything-llm#273]
Trying to utilize GPT-4 to chat with a local pdf getting this error:  **Request failed with status code 401**

was previously hitting error 429 and commented out the code as suggested #251 then rebuild with container with `docker-compose up -d --build`

Weirdly when I set LLM to gpt-3.5 turbo I get error 404, (switching between LLMs using the GUI)

**Comment by LPedro20020** [comment]
Weirdly enough, gpt3.5 works for me. I get the 404 error when switching to any gpt4 option both through the gui and rebuilding the docker container.

**Comment by fdchiu** [comment]
You will also need to enter the openai key in the frontend LLM preference.
Also the frontend seems to have a bug where it does not save the key. And once you get out of the frontend and rerun, you need to enter it again. 

The config for Pinecorne needs to be enter again next when you restart the frontend.

Should fire a bug for these.

**Comment by timothycarambat** [comment]
> You will also need to enter the openai key in the frontend LLM preference. Also the frontend seems to have a bug where it does not save the key. And once you get out of the frontend and rerun, you need to enter it again.
> 
> The config for Pinecorne needs to be enter again next when you restart the frontend.
> 
> Should fire a bug for these.

This is not a bug. This is `nodemon` restarting the server (thus reloading in the .env in the server folder if it exists and unsettling any `process.env`). When in production any changes to the env are automatically dumped so server restarts dont suffer from this issue.
https://github.com/Mintplex-Labs/anything-llm/blob/d1fbe94a3385866a45dd64d5cc86d497c7673b52/server/endpoints/system.js#L253

If the main issue is related to this, then running the node server in production would remedy that.

**Comment by timothycarambat** [comment]
@ilkkaruso this is most certainly your issue if you are doing this in docker as the docker instance will not overwrite your host machines `.env` so when the container restarts the file is gone. You can remedy this by modifying the DockerFile.

We will also be moving away from this model and storing the data in the SQLite DB. Its in the env for legacy reasons, but it should be migrated away from this now.
https://github.com/Mintplex-Labs/anything-llm/issues/281
