### ISSUE TITLE
[BUG]: how to get thread name

### ISSUE THREAD

**Issue by qiqi0308** [Mintplex-Labs/anything-llm#2731]
### How are you running AnythingLLM?

Docker (local)

### What happened?

How can I obtain the name of the current workspace's thread? I tried the interface http://127.0.0.1:3001/api/v1/workspace/test, but the thread details returned only include the thread's slug, not the thread's name

**Comment by qiqi0308** [comment]
Looking forward to your helpful reply

**Comment by mayzyo** [comment]
+1 here. The APIs from `/api/docs` doesn't have a way to obtain the display name of threads.
Both `baseUrl/api/v1/workspaces` and `baseUrl/api/v1/workspace/{slug}` only returns an array with `user_id` and `slug` which is a uuid for the field `threads`.

The endpoint called by the actual frontend `baseUrl/api/workspace/{slug}/threads` seem to include the name of the thread, but calling it with the bearer token would result in `No auth token found.`

**Comment by qiqi0308** [comment]
> +1 这里。的 API 无法获取线程的显示名称。 Both and only 返回一个数组，其中 和 是字段的 uuid 。`/api/docs``baseUrl/api/v1/workspaces``baseUrl/api/v1/workspace/{slug}``user_id``slug``threads`
> 
> 实际前端调用的端点似乎包含线程的名称，但使用 bearer token 调用它会导致`baseUrl/api/workspace/{slug}/threads``No auth token found.`

i did not try multipart users mode,i am sorry to say i dont know

**Comment by qiqi0308** [comment]
> +1 这里。的 API 无法获取线程的显示名称。 Both and only 返回一个数组，其中 和 是字段的 uuid 。`/api/docs``baseUrl/api/v1/workspaces``baseUrl/api/v1/workspace/{slug}``user_id``slug``threads`
> 
> 实际前端调用的端点似乎包含线程的名称，但使用 bearer token 调用它会导致`baseUrl/api/workspace/{slug}/threads``No auth token found.`

i did not try multipart users mode,i am sorry to say i dont know

**Comment by qiqi0308** [comment]
i can't find /api/workspace/{slug}/threads this api.How do you run anythingLLM?
i try the issue #2538,but call back all threads name not single workspace
