### ISSUE TITLE
Anything Llm won't reset to start page even after deleting . 

### ISSUE THREAD

**Issue by beinginevitable** [Mintplex-Labs/anything-llm#2732]
### How are you running AnythingLLM?

Local development

### What happened?

so I am using a MacBook Pro and I installed anything llm after that I removed for some reason and tried to reinstall since I wanted to show it to someone while doing no matter what I did I was unable remove it I tried everything . I am a beginner if anyone could just guide me to how to completely reset anything llm to right from the logo and where we pick the llms (or lm studio options ) . 

thanks a Lot

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/installation-desktop/uninstall#uninstalling-on-macos

> To remove all AnythingLLM desktop data from your system, please also delete the /Library/Application Support/anythingllm-desktop folder. This folder is where your database, documents, and vector cache are located.

If you remove the storage folder this will "totally cleanup" the storage

**Comment by lauramariel** [comment]
I found it in my home directory under `~/Library/Application Support/anythingllm-desktop`

**Comment by timothycarambat** [comment]
Correct, that is documented here: https://docs.anythingllm.com/installation-desktop/storage

**Comment by lauramariel** [comment]
thanks, I was looking at this doc https://docs.anythingllm.com/installation-desktop/uninstall

![Image](https://github.com/user-attachments/assets/db9b4d27-03a1-4a05-a21b-17837cc81b36)
