### ISSUE TITLE
[BUG]: Chat embed widget timestamp

### ISSUE THREAD

**Issue by NemanjaML** [Mintplex-Labs/anything-llm#2733]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hello, I am using anythingLLM chat embed widget for chating with my workspace. Somehow, the timestamp for messages within the chat changes overtime dynamically (whenever I ask another question, the previous messages got the same timestamp as the current one).

First message (3.15PM):
![Screenshot 2024-11-28 151147](https://github.com/user-attachments/assets/45f61a9a-e980-4118-ba0c-fa2b06b2c27e)

Second message (3.17PM):
![Screenshot 2024-11-28 151331](https://github.com/user-attachments/assets/283d1d18-694f-494a-a58a-8bda21244106)

**Comment by shatfield4** [comment]
Users also reported that some responses would use the class `text-center`. Could be a class collision.
