### ISSUE TITLE
[FEAT]: API for "/reset"? 

### ISSUE THREAD

**Issue by GPTLocalhost** [Mintplex-Labs/anything-llm#2735]
### What would you like to see?

> http://localhost:3001/api/docs

Is there any API for sending "/reset" to clear the chat memory in workspace? I tried sending it through "/api/v1/openai/chat/completions" but it won't work.  I'm currently integrating AnythingLLM with Microsoft Word like the following. It would be helpful if users can reset workspace memory in AnythingLLM from Word Add-in. 

* [Using Microsoft Word in multiple minds? An experiment with two workspaces in AnythingLLM.](https://medium.com/@gptlocalhost/using-microsoft-word-in-multiple-minds-an-experiment-with-two-workspaces-in-anythingllm-fb5044174b21)

**Comment by timothycarambat** [comment]
The openai endpoints are openai compatible.
https://github.com/Mintplex-Labs/anything-llm/blob/69b672b625cc9fc8e4eba3793610b8c8c5cad46f/server/endpoints/api/openai/index.js#L143-L149

A request looks like
```
 messages: [
                {"role":"system", content: "You are a helpful assistant"},
                {"role":"user", content: "What is AnythingLLM?"},
                {"role":"assistant", content: "AnythingLLM is...."},
                {"role":"user", content: "Follow up question..."}
                ],
                model: "sample-workspace",
                stream: true,
                temperature: 0.7
```

So to remove the "history" you send less messages, just like OpenAI normally.
