### ISSUE TITLE
[BUG]: Can't start desktop app on ubuntu, sandboxing issue

### ISSUE THREAD

**Issue by dacou-rca** [Mintplex-Labs/anything-llm#2738]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

After installation on ubuntu using the provided script,i get this error when launching with `./AnythingLLMDesktop/start` : 
```
[306733:1129/152127.691509:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/xxx/AnythingLLMDesktop/anythingllm-desktop/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

```

**Comment by mgrecar** [comment]
I encountered the same issue.  From my experience with running Obsidian as an AppImage file, I made the following change to the start script at line 43:
```
exec "$BIN" "--no-sandbox"
```
And it fired up.  I'm not sure that's the right long term solution, but it let me at least get started.

**Comment by timothycarambat** [comment]
Are you running the AppImage as root? Other than that the file permissions in the error message would resolve this

Related doc I've used before
https://authmane512.medium.com/solve-the-suid-sandbox-helper-binary-was-found-but-is-not-configured-correctly-3-solutions-4f1425a9a76c

**Comment by mgrecar** [comment]
I just used the recommended Linux installer script and directions here: https://docs.anythingllm.com/installation-desktop/linux#install-using-the-installer-script.  There was no mention of running it as root.  Perhaps the start script out to make changes to avoid needing to run as root?  This seems like a problem literally everyone using that script will have.

**Comment by rocko-mx** [comment]
> ### How are you running AnythingLLM?
> AnythingLLM desktop app
> 
> ### What happened?
> After installation on ubuntu using the provided script,i get this error when launching with `./AnythingLLMDesktop/start` :
> 
> ```
> [306733:1129/152127.691509:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/xxx/AnythingLLMDesktop/anythingllm-desktop/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap (core dumped)
> ```
> 
> ### Are there known steps to reproduce?
> _No response_

Hello there,

I just installed AnythingLLM on my brand new Ubuntu 24.04 setup, and found that after the install script finishes we need to run this commands:

`cd AnythingLLMDesktop/anythingllm-desktop/`
`sudo chown root:root chrome-sandbox`
`sudo chmod 4755 chrome-sandbox`

and then return to your $HOME_DIR and you can start the desktop with:

`./AnythingLLMDesktop/start`

But I still not able to make it work properly:

![Image](https://github.com/user-attachments/assets/c9206527-85d8-4ce1-8ccd-a9eb4e2c1843)

Any idea on this will be very much appreciated.

**Comment by timothycarambat** [comment]
@rocko-mx - the built in AnythingLLM LLM runner does not run on Linux (it shouldn't even be selectable or usable). If you want to run ollama you need to run that outside of AnythingLLM and let AnythingLLM connect to it. That is why.
