### ISSUE TITLE
Question: Supporting multiple websites with a single installation of Anything LLM

### ISSUE THREAD

**Issue by jeffjoslin** [Mintplex-Labs/anything-llm#2739]
I just found your solution today, amazing!

Does the current version support creating mulitple embedded chatbots for different websites, and if so, can each bot be branded differently for each website?

Lastly, does your api support adding urls to the chatbots workspaces programmatically?

🙏

**Comment by timothycarambat** [comment]
Each chat widget can be branded independently and each widget is tied to a workspace - so yes. The API does support modification of the embeddings on the workspace via the API, which would then show in the embedding as well

**Comment by jeffjoslin** [comment]
Thank you for your response. I successfully got it up and running on our
system two days ago and am absolutely an thrilled with the results. I will
be joining the discord community and will be sure to report any issues and
share my feedback to support ongoing development.

Again, thank you for responding!!
