### ISSUE TITLE
@agent usage in embedded chat

### ISSUE THREAD

**Issue by drik** [Mintplex-Labs/anything-llm#2746]
I realized during my tests that it was not possible to use the agent syntax from the embedded chat.
Is it possible to invoke the agent from the embedded chat?
If yes, how, because I did not find any information about it in the docs.
If no, when will it be available?

Thanks

**Comment by timothycarambat** [comment]
This is not supported at this time - mostly to prevent abuse since agents can burn lots of tokens and we need to first scope skills to workspaces
