### ISSUE TITLE
[FEAT]: Mono Repo With Turbo Repo

### ISSUE THREAD

**Issue by lerno-academy** [Mintplex-Labs/anything-llm#2747]
### What would you like to see?

Hi everyone!
This feature is really simple: one command to run everything in development for a better developer experience (DX)!
I appreciate the opportunity to contribute this to the repo.

**Comment by timothycarambat** [comment]
We have codespaces already running and the current setup for development is like ~4 commands?
`yarn setup`
Then to run each service:
`yarn dev:{server,frontend,collector}` each in a diff tab!
