### ISSUE TITLE
[BUG]: when logging in to anythingllm using SSO as default user I see the create workspace button available. 

### ISSUE THREAD

**Issue by shreyshreya** [Mintplex-Labs/anything-llm#2753]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I login to anythingllm instance using SSO auth token as default user of a workspace and can see create workspace, settings edit buttons enabled . The same are disabled when you login through login screen but visible only when logging in using SSO. The actual functionality is that these options should not be visible to default user.

<img width="1509" alt="Screenshot 2024-12-02 at 10 39 46 AM" src="https://github.com/user-attachments/assets/884fe24c-38e0-49bb-be83-4ed2d64fed87">

### Are there known steps to reproduce?

Go to <your-anythingllm-instance/api/docs>
try the api <v1/users/<userid>/issue-auth-token> (give userid of user with default role)
use the token generated as response to the api call with your anythingllm instance url like : <anythingllm-url>/<sso-token>
you will be logged in to anythingllm instance as userid but can see the create workspace and other things which usually should be disabled for default role.

**Comment by timothycarambat** [comment]
Reproduction steps:
- Enable multi user mode
- Enable Simple SSO via ENV
- Create admin account
- Create `default` user role (id: 2)
- Create API Key
- Issue temp auth token for user id `2` - get endpoint
- Open incognito window and visit SSO URL

Results:
- I am logged in as the proper account, but I can see the create workspace button
-> If i try to create a workspace i am `Unauthorized` as expected
-> Page reload also removes button

This seems to be a UI issue, not a security one as the security features work as expected. Its just the initial page load.
