### ISSUE TITLE
[BUG]:  the document hit rate is not high

### ISSUE THREAD

**Issue by qiqi0308** [Mintplex-Labs/anything-llm#2755]
### How are you running AnythingLLM?

Docker (local)

### What happened?

"I've noticed that the document hit rate is not high, and I'm looking for good methods to improve the understanding of documents. I tested a 60k Excel file, and almost none of the questions could be answered. The model I'm using is qwen2.5:7b.

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/llm-not-using-my-docs
