### ISSUE TITLE
[FEAT]: Could you please add a button that can hide the sidebar?

### ISSUE THREAD

**Issue by AezwxLOkCzw** [Mintplex-Labs/anything-llm#2756]
<img width="304" alt="image" src="https://github.com/user-attachments/assets/9be6fa70-fdc6-47c2-bef6-79dd09824ac4">

**Comment by programmerraja** [comment]
@timothycarambat can i work on this?

**Comment by timothycarambat** [comment]
@programmerraja I would advise against this as we have a designer and we would like to respect their work to have this be easily integrated into the UI in a way that makes sense for the app in all distributions.

**Comment by morbificagent** [comment]
@timothycarambat great, thanks :-) If it would be possible to make the workspaces reorder-able that would be so great
