### ISSUE TITLE
[FEAT]: Suggest integrate to GitHub's repo FIRST.

### ISSUE THREAD

**Issue by naive231** [Mintplex-Labs/anything-llm#2759]
### What would you like to see?

Like #761 , I think there should be a more compelling and important data source is the GitHub's repo itself.

The knowledge in a repo would have its own revision history and digestible far more easily than Google Workspaces(Doc/Slide/Sheet) or Microsoft 365(Word/Excel/PowerPoint). Of course, most content reside in there, but we could start from basics.

Even more, integrate with GitHub can build a more **automatically updated knowledge content**. If the author had updated a document, no matter how large or small scale it was, it could trigger a webhook to update the cached document in AnythingLLM, to the reader of AnythingLLM would automatically get the latest knowledge in real-time.

**Comment by timothycarambat** [comment]
Do you mean the `.git` file? https://github.com/Mintplex-Labs/anything-llm/issues/923

or local folder as a data source (related https://github.com/Mintplex-Labs/anything-llm/issues/1570)
