### ISSUE TITLE
[FEAT]: Is there a way to disable streaming mode for GenericOpenAI

### ISSUE THREAD

**Issue by CharlesPeng1998** [Mintplex-Labs/anything-llm#2760]
### What would you like to see?

I am using a LLM that is served in OpenAI API spec but not supporting stream mode. I can see the response is just keep loading. I wonder if I can disable stream mode, or how can I modify the code to disable it?
![image](https://github.com/user-attachments/assets/f25efdb8-2328-4f68-a16a-7ce1327b38c7)

**Comment by timothycarambat** [comment]
Change 
https://github.com/Mintplex-Labs/anything-llm/blob/6c9e234227aa32a02ba6a05ee978534760e3fd74/server/utils/AiProviders/genericOpenAi/index.js#L54C3-L56C4

to 
```
 streamingEnabled() {
    return false;
  }
  ```

**Comment by SecretiveShell** [comment]
is there any way to disable this without having to vendor the repo?
