### ISSUE TITLE
[BUG]: Rag Memory isn't working

### ISSUE THREAD

**Issue by morbificagent** [Mintplex-Labs/anything-llm#2764]
### How are you running AnythingLLM?

Docker (local)

### What happened?

If I try to save something in rag memory I get this error message:

[backend] info: [AgentHandler] [debug]: @agent is attempting to call `rag-memory` tool
[backend] info: Adding new vectorized document into namespace asc
[backend] info: [RecursiveSplitter] Will split with {"chunkSize":8191,"chunkOverlap":20}
[backend] info: Chunks created from document: 1
[backend] error: addDocumentToNamespace The "path" argument must be of type string. Received null

It's the actual Docker version under Ubuntu and Weaviate as VectorDbProvider.

**Comment by timothycarambat** [comment]
Sounds like you are not running the container via the official command - which will lead to the path argument issue since the STORAGE_DIR env will be unset
https://docs.anythingllm.com/installation-docker/local-docker

**Comment by morbificagent** [comment]
@timothycarambat

Sounds like it but I have used the command and everything else is working fine... File uploads to. And from inside the docker I can see and use the variable:

![Screenshot_20241205_064746_JuiceSSH](https://github.com/user-attachments/assets/ea20fe0a-8126-431f-847b-e5aad4d99373)
