### ISSUE TITLE
[BUG]: Latex blocks wrapped with `\[\]` are not rendered

### ISSUE THREAD

**Issue by i0ntempest** [Mintplex-Labs/anything-llm#2769]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

As stated here: https://github.com/Mintplex-Labs/anything-llm/issues/2018#issuecomment-2289005011, AnythingLLM only supports latex blocks wrapped with $ but not braces. A lot of models use braces for latex blocks by default, so I must tell it to switch symbols instead to get it to render correctly.

### Are there known steps to reproduce?

Ask a llama model a math question that requires latex. I asked "Why is e^(B_t-2/t) a martingale".

**Comment by i0ntempest** [comment]
I have tried and at least some models insisted on using square braces instead of $, even after I explicitly told them to use $.

**Comment by i0ntempest** [comment]
Also see https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/228#issuecomment-2536615337. qwen models are an example of the problem above, not following the instruction.

**Comment by quank123wip** [comment]
> Closing as this is behavior oriented. The main reason is we dont want to load 10 different *TeX parsers into the renderer to support the dozens of whats TeX content can come from - ultimately whatever the model is trained on or predicts to be the best is what it will output, telling it to use the format we support via system prompt is currently the way forward

Forgive me, but this could simply be done by updating upstream extension. The 'markdown-it-katex' version you use is unmaintained and @vscode/markdown-it-katex actively maintained. I will submit a pull request to upstream package to support this simple feature. Would you like to switch to @vscode/markdown-it-katex afterwards?
