### ISSUE TITLE
[BUG]: Connect A Database for Desktop App

### ISSUE THREAD

**Issue by gorkemgul** [Mintplex-Labs/anything-llm#2790]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

_After connecting a database. I wanted to run the llm model to make analysis, however, although I had the connection, I couldn't get any proper or correct answer from it._

**Short info** 

- I used the _Llama3_ as the model. 
- I have chosen _mysql_ as the database. 

**Note**: I'm not sure if there's a bug or sth. But, as far as I know after connection it should give answers according to the connected database.

### Are there known steps to reproduce?

**Steps in short**

- Model selection 
- DB connection 
- Asking questions

**Comment by timothycarambat** [comment]
Is any agent skill execution even occurring? It looks like this in the UI:
<img src="https://docs.anythingllm.com/_next/image?url=%2Fimages%2Fguides%2Fai-agents%2Fsql-agent.png&w=3840&q=100"/>

Otherwise, this doc is relevant https://docs.anythingllm.com/agent-not-using-tools

**Comment by gorkemgul** [comment]
Hi @timothycarambat, thanks for the reply. However this did not fix my problem. I connected the database from agent configuration. But it still gives meaningless answers or tries to write meaningless queries with unexist table names.

**Comment by timothycarambat** [comment]
> I used the Llama3 as the model.

Then this is your model. What version, param size, and quant of LLama are you running? Its related to the models ability to follow the prompt to make valid queries
https://docs.anythingllm.com/agent-not-using-tools
