### ISSUE TITLE
[FEAT]: Feature Request for github import programmatically

### ISSUE THREAD

**Issue by olariuromeo** [Mintplex-Labs/anything-llm#2792]
### What would you like to see?

It would be useful if, when importing from GitHub, the user could select the maximum number of requests per hour. This way, if a repository is very large, it could be imported programmatically in multiple steps, as GitHub has a limit. The initial part of the repository could be imported, and then in subsequent hours or days, the task could be completed by updating the import in several stages. This would be particularly helpful for large repositories to manage the import process more efficiently. Additionally, this task could run in the background, and once it is completed, a notification could be displayed to the user. Furthermore, it would be beneficial to have an update option that could also be programmed, allowing for automatic updates when a new version becomes available, for example. Thus, having the ability to maintain multiple versions of a repository would be very useful, enabling users to have different versions of the documents within the repository.

. Additionally, I often encounter the following error:

`[collector] error: Error: Unable to fetch repository files: 403 {"message":"API rate limit exceeded for user ID . If you reach out to GitHub Support for help, please include the request ID and timestamp","documentation_url":"[https://docs.github.com/rest/overview/rate-limits-for-the-rest-api","status":"403"}](https://docs.github.com/rest/overview/rate-limits-for-the-rest-api%22,%22status%22:%22403%22%7D) at /app/collector/node_modules/langchain/dist/document_loaders/web/github.cjs:`

**Comment by timothycarambat** [comment]
See my previous comment about cron-related tasks or long running message in your other issue.
