### ISSUE TITLE
[FEAT]: Feature Request for scraping websites programmatically

### ISSUE THREAD

**Issue by olariuromeo** [Mintplex-Labs/anything-llm#2793]
### What would you like to see?

For scraping websites, it would be beneficial to allow users to select a maximum number of web pages to scrape per hour. This way, for larger sites, the job could be completed in multiple steps. For example, if you want to index 1,000 pages or an entire large website, this could be done over several days, making the process more manageable and efficient. Additionally, it would be useful to set a cron job programmatically, allowing users to select how often it should run—whether by minute, day, week, etc. This way, the scraping process can be kept updated as desired. It would also be useful to provide two options for the initial indexing as well as for updates.

**Comment by timothycarambat** [comment]
This would be better suited as a cron task that you would write a script for and then use the API to do all of the document management and upserting. Adding this into the core app is a niche request and would add complexity whereas it can easily be accomplished as part of a users deployment in addition to the app and simply using the api!
