### ISSUE TITLE
[BUG]: LM studio listed ads an embedding providers but it does not show up

### ISSUE THREAD

**Issue by yichunx1** [Mintplex-Labs/anything-llm#2798]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

LM Studio is listed as am embedding provider here in the doc (https://docs.useanything.com/features/embedding-models#supported-embedding-model-providers) but there is no such option in the AnythingLLM desktop app. In the app, only the other 4 providers are supported.  
![image](https://github.com/user-attachments/assets/edb876b7-3b57-416b-b4fb-8b2683ca977a)

**Comment by timothycarambat** [comment]
scroll down
https://github.com/user-attachments/assets/65eeae58-6b30-4a41-82ce-84bad6972ade
