### ISSUE TITLE
[BUG]: server field not populating in SQLConnects.js

### ISSUE THREAD

**Issue by szur1** [Mintplex-Labs/anything-llm#2799]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When trying to connect to MS SQL Server, AnythingLLM is failing with the error:

MSSQLConnector TypeError: The "config.server" property is required and must be of type string

Looking into the code I believe the issue lies here:

  #parseDatabase() {
    const connectionPattern = new UrlPattern(
      "mssql\\://:username\\::password@*\\::port/:database*"
    );
    const match = connectionPattern.match(this.connectionString);
    this.database_id = match?.database;
    this.connectionConfig = {
      ...this.connectionConfig,
      user: match?.username,
      password: match?.password,
      database: match?.database,
      server: match?._[0],
      port: match?.port ? Number(match.port) : null,
    };
  }

// Note how there is no server definition in the URLPattern

mssql://<user>:<password>@<server>:<port>/<database>

the match?._[0] is not picking up the sever name

**Comment by timothycarambat** [comment]
Since the server can be any number of valid formats it is wild-carded

```js
#parseDatabase() {
    const connectionPattern = new UrlPattern(
      "mssql\\://:username\\::password@*\\::port/:database*"
      // * => catch all and use this for server endpoint
    );
    const match = connectionPattern.match(this.connectionString);
    this.database_id = match?.database;
    this.connectionConfig = {
      ...this.connectionConfig,
      user: match?.username,
      password: match?.password,
      database: match?.database,
      server: match?._[0],
      port: match?.port ? Number(match.port) : null,
    };
  }
  ```
