### ISSUE TITLE
Cannot use gpt-4

### ISSUE THREAD

**Issue by fdchiu** [Mintplex-Labs/anything-llm#280]
Try to set use of gpt4 model in both places, and still getting pgt3:
1) in server .env set use "gpt-4"
2) in frontend setting for LLM preference, also set gpt-4
3) in chat: "which gpt model are you"? answer is always gpt-3

**Comment by timothycarambat** [comment]
[Do not rely on the model to answer that question :)](https://community.openai.com/t/gpt-4-through-api-says-its-gpt-3/286881)

If you double-check what model you are using - you can check your Billing on OpenAI and see the call was labeled as gpt-4.
