### ISSUE TITLE
[BUG]: ollama not supported using Runpod and Docker

### ISSUE THREAD

**Issue by jebali-safouene** [Mintplex-Labs/anything-llm#2802]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Hello 
I am trying to use anythingLLM on Runpod Platform 
After Creating a template with these informations and i wanted to use ollama it say that 
anythingllm@6228216e0d7b:~$ ollama run llama3:8b
bash: ollama: command not found
How can i resolve this porblem ? 
![Capture d'écran 2024-12-11 121748](https://github.com/user-attachments/assets/cd19db81-7550-491e-bf66-4c99805aa5a9)

**Comment by timothycarambat** [comment]
The docker app does not come installed in our image, you need to set it up in _addition_ to our container. Then it will accessible.
