### ISSUE TITLE
Return Relevancy Score with `similarityResponse`

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#282]
We should include a normalized `score` value in every vectordb's `similarityResponse` method. We will not display this at this time but it should be a normalized score of 0-100% in decimal value.

In the future we can show the score next to each snippet and add a default 'relevancy filter' per workspace to determine if a snippet/citation should be included in a response.

Each vectorDB returns a vary idea of similarity scoring. Ref VectorAdmin to see how that is done.

**Comment by franzbischoff** [comment]
And this can also be used further on with a re-rank step before sending things to the LLM.
