### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by arjunrockzz07** [Mintplex-Labs/anything-llm#2828]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When creating Work space at Agent configuration tab -> Workspace Agent LLM Provider -> GeminiAI is not listing why is this a bug,.?

![image](https://github.com/user-attachments/assets/f0889dab-dc82-454e-9a11-abde1390d574)

**Comment by timothycarambat** [comment]
Gemini agents are not supported becuase the Gemini API is too rate limited to be able to run agent calls. Or at least it was the last time we checked it out.

#1297
