### ISSUE TITLE
[BUG]: Documents with Chinese filenames will appear as garbled text when uploaded.

### ISSUE THREAD

**Issue by udyk-dev** [Mintplex-Labs/anything-llm#2832]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Documents with Chinese filenames will appear as garbled text when uploaded.
<img width="1535" alt="iShot_2024-12-14_20 38 14" src="https://github.com/user-attachments/assets/448538f4-de93-4762-931c-5f9a432ef334" />

**Comment by HugoWang232608** [comment]
Same problem
