### ISSUE TITLE
[BUG]: AnythingLLM on railway Hobby Plan (7 vCPU)

### ISSUE THREAD

**Issue by KI-canvas-de** [Mintplex-Labs/anything-llm#2833]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I have a large PDF Document I want to analyse. It didn't work work with the default setting, so I changed it:
LLM: Openai
Vector DB: LanceDB
Embedding: Openai
I opened a new workspace and embed my pdf.
If I ask anything in the chat. Answer is: Failed to execute query stream: Invalid input, No vector column found to match with the query vector dimension: 1536

**Comment by timothycarambat** [comment]
> If I ask anything in the chat. Answer is: Failed to execute query stream: Invalid input, No vector column found to match with the query vector dimension: 1536

Reset the workspaces vector database.
Click on gear on workspace > Vector database > Reset.

You swapped embedding models and the table schema is set on the first embed. In fact, we will auto-reset your entire instance now once https://github.com/Mintplex-Labs/anything-llm/pull/2819 is merged
