### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by udyk-dev** [Mintplex-Labs/anything-llm#2836]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The API endpoint `/api/v1/document/raw-text` cannot save titles containing Chinese characters.

<img width="1141" alt="iShot_2024-12-15_18 49 43" src="https://github.com/user-attachments/assets/de42a3d9-9120-4b4a-9c6a-a42cc18738db" />

------

docker image: mintplexlabs/anythingllm:latest (cb62a3c82ff0c66739e71c7eddb8be4abad6d4e76146c7c778dc2c2d8194582e)

### Are there known steps to reproduce?

1, create a API  KEY 

2,  send post  request to endpoint `/api/v1/document/raw-text` with curl  

```
curl --location 'localhost:3001/api/v1/document/raw-text' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer PZT2TS9-AF2MPFR-JZ637WK-40HV8WP' \
--data '{
  "textContent": "测试中文内容.",
  "metadata": {
    "title": "测试中文内容.txt",
    "etc": "测试中文内容",
    "docAuthor":"测试中文内容",
    "docSource":"测试中文内容",
    "description":"测试中文内容"
  }
}'
```

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/2474
