### ISSUE TITLE
[FEAT]: Need new api endppoint to append users to workspace

### ISSUE THREAD

**Issue by shreyshreya** [Mintplex-Labs/anything-llm#2838]
### What would you like to see?

New api endpoint to add users to existing workspace. It would help all admin users to add new users to the workspace through api.

**Comment by timothycarambat** [comment]
There should exist an endpoint under `User Management` that takes the format of
`POST /v1/users/:id/workspaces` that takes a body with two keys
```json
{
 workspaces: [slug, slug slug],
 reset: false,
}
 ```
 
 `reset` will determine if the workspace slug associations are being appended or if the workspaces will be the only associations going forward for the user.
 
 There should be an associated `GET /v1/users/:id/workspaces` to list associations for a give user and their workspaces.
