### ISSUE TITLE
[BUG]: App won't start

### ISSUE THREAD

**Issue by sebelk** [Mintplex-Labs/anything-llm#2839]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Stuck on:
Stuck on downloading Prisma engines and it never starts:

```
Preferences] preference config stored at /home/sergio/.config/anythingllm-desktop/config.json
> Downloading Prisma engines for Node-API for rhel-openssl-3.0.x [                    ] 0%
```

### Are there known steps to reproduce?

Just run:
`/home/sergio/AnythingLLMDesktop/start`

The OS is Fedora 41.

**Comment by timothycarambat** [comment]
> Stuck on downloading Prisma engines and it never starts:

[Primsa](https://github.com/prisma/prisma) is required and each OS has its own binary, if it cannot download you are either on a VPN and that is somehow blocking downloading of the binary from their CDN or otherwise. Not within the scope of AnythingLLM to address
