### ISSUE TITLE
Not getting response from chatbot

### ISSUE THREAD

**Issue by mouritech-kalyani** [Mintplex-Labs/anything-llm#285]
Hello All, 
After doing configuration with pinecone and adding AI key. I am getting this error from chatbot, can someone please help me here?

(Note: Added Pincone configuration, Added Open AI Key, uploaded text document) 
Error: 
TypeError: Cannot read properties of undefined (reading 'replace')

**Comment by timothycarambat** [comment]
Going to need some direct output from the logs on this issue. Can you inspect the logs for the backend server or the docker container if available?

**Comment by mouritech-kalyani** [comment]
I am running it locally not using docker, i used npx flowise start to run the application, but after asking something to chatbot of flowise getting this error in inspect

![Uploading Screenshot 2023-10-25 at 10.48.34 AM.png…]()

**Comment by timothycarambat** [comment]
I wasn't aware of a flowise integration of AnythingLLM or how to connect the two. Regardless the screenshot failed to attach, can you reupload it?

**Comment by mouritech-kalyani** [comment]
> I wasn't aware of a flowise integration of AnythingLLM or how to connect the two. Regardless the screenshot failed to attach, can you reupload it?

Uploaded, Please check once

**Comment by timothycarambat** [comment]
This is a source code screenshot from the generic `xhr.js` file in the JS bundle. I would need the logs for your docker container running your anythingllm instance. No information from your browser is required for now.
