### ISSUE TITLE
[BUG]: Bad RAG performance when using Milvus

### ISSUE THREAD

**Issue by wolfganghuse** [Mintplex-Labs/anything-llm#2862]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I use build-in embedding engine. When i store vectors in local LanceDB i can easily ask questions about my documents and i get good answers, with working citations.
When changing VectorDB to locally hosted Milvus DB (2.5.0-beta) there is no usage of the vectors. Answers are only generic.
When checking Milvus Datasets i see the right number of datasets but there is no metadata attached to it.

Happy to work with somebody to provide more details.

**Comment by timothycarambat** [comment]
https://docs.anythingllm.com/llm-not-using-my-docs

Its not Milvus, its:
- your documents
- the prompts you are sending
- Your LLM's context/ability 

Document links above how to address and fix this
