### ISSUE TITLE
[BUG]: No vector column found to match with the query vector dimension: 1536

### ISSUE THREAD

**Issue by jwr** [Mintplex-Labs/anything-llm#2863]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I configured OpenAI API keys, created a new workspace, uploaded several documents and moved them to the workspace.

Asking any query results in:

`Failed to execute query stream: Invalid input, No vector column found to match with the query vector dimension: 1536`

If I change the embedder to a different one and reset the vector database for the workspace, the number is different, but I can never get anything to work.

**Comment by timothycarambat** [comment]
Reset the vector database on the workspace. You changed your vector db or embedding model/prefernce and now you have a dimensionality mismatch.

We fixed this in https://github.com/Mintplex-Labs/anything-llm/pull/2819 to prevent it from happening in the future, it is not in desktop app until next patch

**Comment by jwr** [comment]
I did reset the vector database in the workspace. Multiple times. I even created a new workspace, but no matter what I do I can't seem to get past this.

**Comment by jwr** [comment]
After banging my head against this wall some more, I now think the problem is that resetting the vector database does not help. What does help is completely deleting all uploaded documents (not just ones moved to the workspace, all uploaded ones).

**Comment by timothycarambat** [comment]
Your old docments were _cached_ and so they _also_ had the old embedding dimensions, so when you re-added them it just set the table back to the old dimensions over and over. You had to remove the documents and re-embed them as well.

Again, we fixed this in the PR linked. It will basically wipe all namespace and unembed and wipe the cache of documents away too so you dont encounter this again
