### ISSUE TITLE
[FEAT]:  Finally, a Gemini models endpoint

### ISSUE THREAD

**Issue by Peterson047** [Mintplex-Labs/anything-llm#2866]
### What would you like to see?

I would like to know if it would be possible to implement the functionality to list the Gemini 2.0 model in the project. My API already supports the experimental version, but I noticed that AnythingLLM currently does not list all available models, including Gemini 2.0.

It would be very helpful to have support for this version integrated. This would make it easier to use new features and experiments with Gemini 2.0.

![{500B3800-EB79-44C1-A679-7BC4294FA2A9}](https://github.com/user-attachments/assets/7f9e4d5e-dcb2-4f1f-b378-ba16a82bd844)

**Comment by timothycarambat** [comment]
If they have a publically accessible API that we can hit, we would - but for the longest time it has never existed.

Looks like recently this was supported via:
https://ai.google.dev/api/models#method:-models.list

So we should be able to add it now.

**Comment by Peterson047** [comment]
I created a new container with yesterday's build and the model appeared.
![image](https://github.com/user-attachments/assets/9351516f-e35f-4684-82af-84c44235b75c)

**Comment by timothycarambat** [comment]
@Peterson047 that is probably from f8e91e1ffacc501085849b8f5b6cfb0784dcfa13 - it was not hitting the /models endpoint.

**Comment by spencerthayer** [comment]
@timothycarambat when will this new incredible functionality be seen in the Docker [mintplexlabs/anythingllm:latest](https://hub.docker.com/r/mintplexlabs/anythingllm/tags)? Thank you so much!
