### ISSUE TITLE
How does the default thread work?

### ISSUE THREAD

**Issue by a0926019412** [Mintplex-Labs/anything-llm#2878]
Hi, I'm running anythingllm in a docker environment and encountered an issue during testing. I'd like to ask you for help.
I created a new workspace and set a prompt, but when I tested it in the default thread, the prompt didn't seem to take effect. After creating a new thread, the prompt worked as expected in that thread. Could you please explain why this happened?

**Comment by shatfield4** [comment]
I am unable to replicate this. After you set a prompt in the chat settings and save it the default thread follows what the prompt is set at. Are you able to replicate this behavior consistently?

**Comment by a0926019412** [comment]
Hi, thank you for your reply. I found that after deleting the previous conversation history, the chat responses are now as expected. Thank you.
