### ISSUE TITLE
[FEAT]: SAML Integration

### ISSUE THREAD

**Issue by dpcahill** [Mintplex-Labs/anything-llm#2880]
### What would you like to see?

This is something we absolutely need. Most companies and organizations cannot use username and password and it makes it so this codebase (which is the best in my opinion), isn't an option for us.

**Comment by timothycarambat** [comment]
Does building your own auth portal and using the Simple_SSO setting not work? it is often a ton of work to build-to-suite the thousands of auth providers and their niche implementations and gotchas. Usually if you have oAuth, you have resources to make a simple SSO portal (or have one already) and can add in our simple SSO hook to do automatic auth for subusers.

Its a single POST request to get a token. Most people have it as a link in their intranet
https://docs.anythingllm.com/configuration#simple-sso-passthrough
