### ISSUE TITLE
[BUG]: Where can I find the version number?

### ISSUE THREAD

**Issue by mihongyu** [Mintplex-Labs/anything-llm#2889]
### How are you running AnythingLLM?

Not listed

### What happened?

I am using a browser to remotely access my AnythingLLM server. But I cannot find the version number displayed on the page, which makes it difficult for me to determine whether the code has been successfully upgraded from GitHub.  
If it is the desktop version, the version number is displayed in the upper right corner. But it seems that the browser version cannot find the location of the version number.

**Comment by spencerthayer** [comment]
This is not currently possible via the UI.

**Comment by timothycarambat** [comment]
version number is only in the desktop app. Check the image SHA if deployed on docker.
