### ISSUE TITLE
[BUG]: Windows v1.7.1 - Using Azure Open AI LLM to chat but failed due to "self signed certificate in certification chain"

### ISSUE THREAD

**Issue by robinszeto** [Mintplex-Labs/anything-llm#2896]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![Screenshot 2024-12-24 154312](https://github.com/user-attachments/assets/d9cf5e64-fd49-4a7b-b79a-33be66902392)

Using Azure OpenAI LLM (gpt-4o-mini) to start chat but failed in Windows Desktop v1.7.1.
However, the same setting works in MacOS Desktop v1.7.1.

**Comment by timothycarambat** [comment]
your VPN (or possibly ISP?) is causing this issue and it is very common to occur. Basically your client requests cannot be verified by the azure endpoint and so this arises during the HTTPS request.

Are you using a VPN or otherwise?
