### ISSUE TITLE
[BUG]: error when docker run

### ISSUE THREAD

**Issue by shawnli89** [Mintplex-Labs/anything-llm#2897]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The Docker Container Logs are as follows:
![image](https://github.com/user-attachments/assets/beed4cde-68eb-41bf-83ee-6af6636ca30d)
docker version 20.10.7
node version v18.20.5
anythingllm docker image is the latest

**Comment by timothycarambat** [comment]
You are missing `--cap-add SYS_ADMIN` which enables the puppeteer web scraper to work, however on start that is a v8 chrome error and whatever it is, is unrelated to any code we wrote. Paste a full log instead of screenshot for more help + system OS and any other relevant specs
