### ISSUE TITLE
[BUG]: Wrong Gemini model names and 500 Internal Server Error

### ISSUE THREAD

**Issue by DangerousBerries** [Mintplex-Labs/anything-llm#2898]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When selecting the first "Gemini Experimental 1206" from the Chat Model Selection list (there are six overall on the list), It's apparently using gemini-1.5-pro-exp-0801, not 1206, since I'm getting this error: 

 Could not respond to message.
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-exp-0801:streamGenerateContent?alt=sse: [500 Internal Server Error] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

When I select the correct "Gemini Experimental 1206" (the forth one top to bottom on the list) and try to send a prompt message, I get the same error just with the correct model.

 Could not respond to message.
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-exp-1206:streamGenerateContent?alt=sse: [500 Internal Server Error] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

Sucks that I've apparently been using 0801all this time before this error started, at least now I know.

Edit: The 500 Internal Server Error is gone now, the model names bug is still there though. I also have a few more comments:

- The metrics say the LLM's reply takes a few seconds but it actually takes a few minutes to stop loading and show up sometimes, why is that?

- Gemini 2.0 Flash Thinking Experimental is showing the thinking process in the reply and gets broken easily, using wrong context for its replies.

**Comment by timothycarambat** [comment]
The names returned directly from google are wrong for their own ids
```
{
  name: 'models/gemini-1.5-pro-exp-0801',
  version: 'exp-0801',
  displayName: 'Gemini Experimental 1206',
  description: 'Experimental release (December 6th, 2024) of Gemini.',
  inputTokenLimit: 2097152,
  outputTokenLimit: 8192,
  supportedGenerationMethods: [ 'generateContent', 'countTokens' ],
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxTemperature: 2
}
{
  name: 'models/gemini-1.5-pro-exp-0827',
  version: 'exp-1206',
  displayName: 'Gemini Experimental 1206',
  description: 'Experimental release (December 6th, 2024) of Gemini.',
  inputTokenLimit: 2097152,
  outputTokenLimit: 8192,
  supportedGenerationMethods: [ 'generateContent', 'countTokens' ],
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxTemperature: 2
}
```

We just show the name and as a result, there are 3 "duplicate" entries for the same name - will change this to the ID since this is confusing not knowing exactly which key you chose since we can only fit so much into the input selector.

Also your error 
> [exp-0801:streamGenerateContent?alt=sse](https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-exp-0801:streamGenerateContent?alt=sse): [500 Internal Server Error] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

Is from Google, not us - they must have had downtime on their servers and you hit their API during this time. There is nothing we can do to patch that.

**Comment by DangerousBerries** [comment]
> The names returned directly from google are wrong for their own ids
> 
> ```
> {
>   name: 'models/gemini-1.5-pro-exp-0801',
>   version: 'exp-0801',
>   displayName: 'Gemini Experimental 1206',
>   description: 'Experimental release (December 6th, 2024) of Gemini.',
>   inputTokenLimit: 2097152,
>   outputTokenLimit: 8192,
>   supportedGenerationMethods: [ 'generateContent', 'countTokens' ],
>   temperature: 1,
>   topP: 0.95,
>   topK: 64,
>   maxTemperature: 2
> }
> {
>   name: 'models/gemini-1.5-pro-exp-0827',
>   version: 'exp-1206',
>   displayName: 'Gemini Experimental 1206',
>   description: 'Experimental release (December 6th, 2024) of Gemini.',
>   inputTokenLimit: 2097152,
>   outputTokenLimit: 8192,
>   supportedGenerationMethods: [ 'generateContent', 'countTokens' ],
>   temperature: 1,
>   topP: 0.95,
>   topK: 64,
>   maxTemperature: 2
> }
> ```
> 
> We just show the name and as a result, there are 3 "duplicate" entries for the same name - will change this to the ID since this is confusing not knowing exactly which key you chose since we can only fit so much into the input selector.
> 
> Also your error
> 
> > [exp-0801:streamGenerateContent?alt=sse](https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-exp-0801:streamGenerateContent?alt=sse): [500 Internal Server Error] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting
> 
> Is from Google, not us - they must have had downtime on their servers and you hit their API during this time. There is nothing we can do to patch that.

Any idea regarding the sometimes slow loading times of messages? even though the metrics show a few seconds?
