### ISSUE TITLE
Error with adding documents on newly initialized project

### ISSUE THREAD

**Issue by didrio** [Mintplex-Labs/anything-llm#29]
The server and frontend are set up and working, but when trying to add documents to a workspace (clicking the + folder icon), I get this error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'items') at toggleSelection`

Which is from this line:

`const folderItems = directories.items.find((item) => item.name === parent).items;`

And I'm not sure how to solve it

**Comment by timothycarambat** [comment]
Have to run the `collector` and have any documents in the `server/documents` folder?

**Comment by timothyasp** [comment]
This error is fixed in #40 - unrelated to adding documents, but I did the same thing first go around.  Thought that the "+" icon would bring up a file window.
