### ISSUE TITLE
[BUG]: sh: 31: ./AnythingLLMDesktop.AppImage: Exec format error

### ISSUE THREAD

**Issue by kalustian** [Mintplex-Labs/anything-llm#2915]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I want to install AnythingLLM Desktop on my **Nvidia AGX Orin 32Gb** . When running the below curl, it gave me " sh: 31: ./AnythingLLMDesktop.AppImage: Exec format error" message.

curl -fsSL https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/installer.sh | sh 

Any suggestion to fix it ?

**NOTE:** I have the docker version running without issue, but seems the "Custom Skill" option is not enabled in docker.

Thanks

**Comment by timothycarambat** [comment]
> but seems the "Custom Skill" option is not enabled in docker.

Are you on the most recent image or an image that supports custom skills?
There is also this: https://docs.anythingllm.com/configuration#anythingllm-hub-agent-skills

We have people run AnythingLLM on Orins with no issue (via docker), however for desktop you might be on the wrong arch. Isnt the Orin ARM based? If so, we dont have Linux ARM support, only windows ARM. We do support ARM linux for docker though.

As for the skill stuff, do you have somewhere on the UI where you see skills being unavailable + what is your image SHA
