### ISSUE TITLE
Error: spawn xdg-open ENOENT

### ISSUE THREAD

**Issue by rafalohaki** [Mintplex-Labs/anything-llm#3]
using: 

1st screen
yarn setup
yarn prod:backend

1nd screen
cd frontend 
yarn install
cd ..
yarn prod:frontend

the error is from 'yarn prod:frontend'
  VITE v4.3.9  ready in 1111 ms

  ➜  Local:   http://localhost:3000/
  ➜  press h to show help
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:3000/' ]
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

commit:
https://github.com/Mintplex-Labs/anything-llm/tree/8199fcc077e4a70caf9a8c529dcb81467e2a2574

**Comment by timothycarambat** [comment]
What does `yarn dev:frontend` give you?

**Comment by timothycarambat** [comment]
Nevermind, are you on Ubunut?
Full Solution: https://stackoverflow.com/a/73942711

Temp solution
`frontend/package.json`
` "start": "vite --open",` => ` "start": "vite",`
