### ISSUE TITLE
[Windows Problem]:Error running on installing packages for collector 

### ISSUE THREAD

**Issue by Cenrax** [Mintplex-Labs/anything-llm#30]
1. pip install - requirements.txt in /collector folder gives this error
2. From the initial inspection it seems this is an windows error
<img width="214" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/43017632/e9661670-64fa-42f4-8c0d-2ae941e776d9">

Steps to reproduce:

1. cd collector
2. pip install -r requirements.txt

**Comment by jwaltz** [comment]
similar/duplicate to #5

@Cenrax, the project maintainer is looking into dockerizing the various components of the app to avoid OS-specific package install issues. See #26

**Comment by timothycarambat** [comment]
Closing this as duplicate + is in the works

as @jwaltz said refer to PR #34
