### ISSUE TITLE
Custom User Roles - Permissions

### ISSUE THREAD

**Issue by iokinpardo** [Mintplex-Labs/anything-llm#302]
@timothycarambat I have been thinking a bit about User permissions and how this could be set in a more flexible way for the Admin side.
Imagine that the Admin could create “Custom User Roles” enabling/disabling permissions, as there could be many different possibilities to cover on each sub-projects.

Admin (Existing Role) – Full permissions and the only one to create custom User Roles.
Developer 1 (Custom User Role)  – Permissions to Appearance, API Keys, LLM Preferences, Vector DB, Export Import and Security
Developer 2 (Custom User Role)  – Permissions to Appearance and LLM Preferences
Final User or Chat Only (Existing Role)  – Permissions just to chatbots

Do you think this could be useful to apply? Thanks.

**Comment by husanto** [comment]
Very good idea

**Comment by timothycarambat** [comment]
connect #296
