### ISSUE TITLE
Cloud deployment to AWS using doc guide does not work

### ISSUE THREAD

**Issue by mrloofer** [Mintplex-Labs/anything-llm#307]
Deploying to AWS cloud using the documentation provided results in a site that is unreachable. I've terminated and created a new stack multiple times following the guide but each time the site becomes unreachable. Is the documentation out of date?

**Comment by timothycarambat** [comment]
It is certainly out of date, it is community-maintained. I'll self-assign to see if I can get it back up to par. We had some large changes recently that for sure those templates do not compensate for.

**Comment by timothycarambat** [comment]
@mrloofer You can now use Cloudformation to deploy [the updated template](https://github.com/Mintplex-Labs/anything-llm/blob/master/cloud-deployments/aws/cloudformation/cloudformation_create_anythingllm.json) and you will have a running instance.
