### ISSUE TITLE
Summarization actions

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#310]
Given the default nature of AnythingLLM is a Q/A against a document set, we should also enable an "action" via the prompt that can then do rote summarization of all text data attached to a specific workspace - if possible we should also enable filtering of summarization on specific documents in case their workspace contains many large documents.

`/summary <?doc> <prompt/>`

**Comment by bplunkert** [comment]
This would be extremely useful.

**Comment by timothycarambat** [comment]
This will be done with https://github.com/Mintplex-Labs/anything-llm/pull/758
You can pin a document and ask to summarize and it will

**Comment by raidduelist** [comment]
Anything LLM, I move many files into the workspace. I want it to summarize all of the documents one by one but the results are not really good. There are actually so many important things to note but the result does not meet my expectation. I am using the LLama3 7B ai model. This is good but not really good. I feel like this can't generate multiple documents to summarize one by one with good result
