### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by jamsnrihk** [Mintplex-Labs/anything-llm#312]
It is very strange, once enable multi-user mode, first time is ok to login, once quite and try to login again, will show : Error: Could not validate login.
Even 100% sure user name and password is correct, still can't login.
![cap8](https://github.com/Mintplex-Labs/anything-llm/assets/134043330/97cd570d-c445-4a41-91be-0b26762e0a3c)

**Comment by timothycarambat** [comment]
Are you in development mode on localhost? If so this is a known issue when the server hot-reloads. Based on previous conversations I am assuming that you are running this in development mode?

**Comment by jamsnrihk** [comment]
I am running on a docker, i think it is localhost, not development mode.
yes, it happened when i restart the docker. any solution for it?

**Comment by timothycarambat** [comment]
Pull in changes and rebuild - you should ideally start fresh again. Now the settings will persist between restarts.

resolved by 7d3d0e03c6970ec84d8aa5425d620817f487ea7a
