### ISSUE TITLE
LM Studio Integration?

### ISSUE THREAD

**Issue by abcnow** [Mintplex-Labs/anything-llm#313]
I wonder if you can install anything llm with LM Studio and use your LLM instead of ChatGPT? Thanks in advance!

**Comment by timothycarambat** [comment]
Related #118 

Thanks for the suggestion! Will be doing a bunch of localLLM support soon!

**Comment by franzbischoff** [comment]
PR #335

**Comment by timothycarambat** [comment]
Resolved by f499f1ba59f2e9f8be5e44c89a951e859382e005
