### ISSUE TITLE
API keys wont go green.

### ISSUE THREAD

**Issue by luizbueno3d** [Mintplex-Labs/anything-llm#33]
My .env.development looks like this:
```
SERVER_PORT=3001
OPEN_AI_KEY=sk-.....
OPEN_MODEL_PREF='gpt-3.5-turbo'
CACHE_VECTORS="true"

# Enable all below if you are using vector database: Chroma.
# VECTOR_DB="chroma"
# CHROMA_ENDPOINT='http://localhost:8000'

# Enable all below if you are using vector database: Pinecone.
VECTOR_DB="pinecone"
PINECONE_ENVIRONMENT=us-wes...
PINECONE_API_KEY=b5......
PINECONE_INDEX=default

# Enable all below if you are using vector database: LanceDB.
# VECTOR_DB="lancedb"

# CLOUD DEPLOYMENT VARIRABLES ONLY
# AUTH_TOKEN="hunter2" # This is the password to your application if remote hosting.
# JWT_SECRET="my-random-string-for-seeding" # Only needed if AUTH_TOKEN is set. Please generate random string at least 12 chars long.
# STORAGE_DIR= # absolute filesystem path with no trailing slash

```
with all correct and cross checked keys. Am I doing something obviously wrong?

When I send a chat message, I get a return: Could not send chat.
I check the API keys and they are RED. "Ensure all fields are green before attempting to use AnythingLLM or it may not function as expected!" in red.
I've tried everything I could think of. Could anyone help?

**Comment by prakks1992** [comment]
same issue with me

**Comment by timothycarambat** [comment]
Is this file in the `server` folder and also did you restart the server after making the changes?

Also be sure you are running `yarn dev:server` and **not** `yarn prod:server`

**Comment by luizbueno3d** [comment]
Yes, all Exactly how you’ve said it.
All went smoothly in the installation. Followed every read me and your
YouTube video.
I’m wondering why I don’t get a Green from the keys. Did something change?
The structure of the key screen looks a little bit different. Yours has no
field “pinecone“ like ours.
Luiz

**Comment by timothycarambat** [comment]
That video was made on a way earlier version of the repo, so other vector dbs, were not supported. the current `.env.example` is the correct format.

**Comment by preeteshjain** [comment]
Same issue. Did a fresh clone just a few minutes ago and installed everything as per the instructions.

Here's what I am seeing:

<img width="1416" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/6207830/9f6d2eb5-b62e-4f11-a86d-e9deabc94ebf">

**Comment by luizbueno3d** [comment]
Here is what I am seeing:
![9C7ED95F-3DD4-4142-9646-0DD321A1BE0F](https://github.com/Mintplex-Labs/anything-llm/assets/35733902/f066f6c0-94fa-4e6b-aae6-a2ac7bba775b)

**Comment by preeteshjain** [comment]
@luizbueno3d Thanks that worked.

**Comment by luizbueno3d** [comment]
It works on your end now?
Can you chat with it and wont get errors when you send a chat?

**Comment by preeteshjain** [comment]
Hey @luizbueno3d 

It says "Could not send chat" when I send any message.

<img width="441" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/6207830/be07ee67-1db0-4209-8309-5354b2f52d82">

Though my configuration looks normal now

<img width="1422" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/6207830/655e18a6-d49e-4cfa-80b0-8beacda42e08">

**Comment by timothycarambat** [comment]
Please pull in the latest changes and just run the application inside of [Docker](https://docker.com) locally. It should have no issues!

**Comment by rewphus** [comment]
+1

**Comment by ShadowXZT** [comment]
Finally, I got it running by moving this line to the end of the .env.development:

> CACHE_VECTORS="true"

In my case, I guess there may be something wrong here: 

> "dev": "NODE_ENV=development nodemon --ignore documents --ignore vector-cache --trace-warnings index.js",

**Comment by luizbueno3d** [comment]
I have to admit I gave up on this project. It feels like Mintplex Labs has
bigger fish to fry. I spent some days trying to make it work with no
success. There are times we got to know when it is enough.

Shame cause it seems promising and useful

Luiz

**Comment by bibi-b** [comment]
Same here. I try to run it with docker but it seems that the .env isnt recognized. Any hints?

**Comment by bibi-b** [comment]
Found a related post on discord. If you run the project on a server and open the URL remotely, it opens the side, but it seems the .env is not loaded. All you have to do is to hardcode the server's address here and rebuild the docker:
frontend/src/utils/constants.js
 (change localhost here to your IP)

**Comment by abibell** [comment]
Same issue here. I created a fresh setup from scratch 20 mins ago.
![Screenshot 2023-06-20 155606](https://github.com/Mintplex-Labs/anything-llm/assets/544653/5b677f07-a57d-4ddc-8062-e89142ff124b)
