### ISSUE TITLE
Code File Types upload query

### ISSUE THREAD

**Issue by a7t0fwa7** [Mintplex-Labs/anything-llm#346]
Hey There, does anything-llm support uploading code files? I tried to upload one C file to test it out but is seems like the file format is not accepted, do we need to convert these file types into a text format first?
Cheers

**Comment by timothycarambat** [comment]
If you simply renamed the file from .cpp or .c to `.txt` you could upload and its format would not matter.

We have an issue for alternative file-type chunking so it works better with specific types of files are regular chunking on code could split in the middle of a function.


Alternatively, you could just not embed the file at all and past the code directly into chat and that would probably work too (depending on size)
