### ISSUE TITLE
Unable to use AnythingLLM on EC2

### ISSUE THREAD

**Issue by ittech17** [Mintplex-Labs/anything-llm#347]
I have setup it over EC2 (with docker), and trying to use it from UI

However I get an error : " Could not respond to message.Reason: OpenAI chat: undefined is not valid for chat completion!" 

Could you please help to troubleshoot and resolve this isue ?
![Screenshot 2023-11-08 104748](https://github.com/Mintplex-Labs/anything-llm/assets/43367504/dc5ba36a-9efa-4aca-add2-e17b24579810)

**Comment by timothycarambat** [comment]
Responded to email. You need to set an ENV or it was not set during onboarding
https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/AiProviders/openAi/index.js#L145
