### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by franzbischoff** [Mintplex-Labs/anything-llm#350]
https://github.com/Mintplex-Labs/anything-llm/blob/f499f1ba59f2e9f8be5e44c89a951e859382e005/frontend/src/pages/GeneralSettings/LLMPreference/index.jsx#L11

needs to be lowercased

**Comment by timothycarambat** [comment]
resolved by 195d3cfcc33fc5c03cc2c8451e302c38383558d7
