### ISSUE TITLE
LM Studio Embeddings Integration

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#358]
@netandreus Responded with 

> Hello, @franzbischoff ! Thank you for quick reply. I try to use master branch at actual top commit (https://github.com/Mintplex-Labs/anything-llm/commit/6e72519cafbb603b7559e6c47e36836454e69576) but still don't see ability to use LocalAI for Embeddings. Only OpenAI and Azuer OpenAI are available. Can you please add it?
> 
> <img width="666" alt="Screenshot 2023-11-10 at 10 35 49" src="https://github.com/Mintplex-Labs/anything-llm/assets/313477/7e5ae80a-7a5b-4abc-b817-b600078251a2">

**Comment by Amejonah1200** [comment]
Afaik LM Studio *doesn't* have an embeddings feature, it would be nice to just provide a different URL for the embeddings API, so you could just host your own.

**Comment by Amejonah1200** [comment]
However, other providers have APIs for it:
https://localai.io/howtos/easy-setup-embeddings/
https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-embeddings

**Comment by timothycarambat** [comment]
Yeah, so this issue is not relevent anymore than because it wont be as easy as just supporting that. We would indeed have to support Ollama or LocalAI. 

Ollama was on the list anyway!

**Comment by Amejonah1200** [comment]
You are already planning on making provision of different base URL for OpenAI, you could make the same thing for embeddings.

**Comment by netandreus** [comment]
> Yeah, so this issue is not relevent anymore than because it wont be as easy as just supporting that. We would indeed have to support Ollama or LocalAI.
> 
> Ollama was on the list anyway!

LocalAI please 🙏

**Comment by timothycarambat** [comment]
Resolved by #361
