### ISSUE TITLE
增加支持局域网运行，增加中文支持

### ISSUE THREAD

**Issue by liuyang77886** [Mintplex-Labs/anything-llm#36]
希望能增加支持局域网运行，增加中文支持

**Comment by kaboomskizzle** [comment]
> 希望能增加支持局域网运行，增加中文支持
OpenAI Notes:
`In English, it says: "Hope to increase support for local area network operation, and increase Chinese language support."`

当这个项目的社区不断壮大时，我们期待着为其贡献我们的资源，并尽力相互支持。

另外，请注意，就个人而言，我在局域网上使用没有遇到问题。请问您是否在局域网上遇到了特定的问题？

Thanks again to OpenAI...
`Sure, I can convey your message and inquire about the specific issue on LAN. Here's the message:

"As the community grows for this project, we are excited to contribute our resources and support each other to the best of our abilities. Additionally, I wanted to mention that personally, I have had no issues with running it over LAN. Could you please specify if you are experiencing any particular issue on LAN?"`

**Comment by timothycarambat** [comment]
Closing only because its not an issue but thank you for the comment and translation. Any requests (like this) can go in the discord https://discord.gg/6UyHPeGZAC
