### ISSUE TITLE
collected URL article files cannot be moved into a workspace

### ISSUE THREAD

**Issue by santini-cyber** [Mintplex-Labs/anything-llm#374]
Observed Behavior:
After running the collector and successfully capturing the content from a single URL website, the resulting article-*.json file cannot be moved into the workspace via the File Manager UI in order to be embedded.
Error/Log Data:
I am not seeing any errors in the docker logs.  The json structure in the article file has been verified via json lint.  I also reviewed the network trace in the developer tools for the Firefox and Chrome browsers and am not seeing any errors or warnings that might explain the observed behavior.   
Repeatable:
Recreated the issue with Chrome, Firefox and Edge.  Also recreated using several different URLs.  And three successive daily builds.

**Comment by timothycarambat** [comment]
Pull in latest and re-run the collector and the schema will work. This is only an issue if you are connected to a LanceDB vectordb, any other provider would not have this issue. Thanks!

c5dc68633b5b63ecdbe7a7ab5ba004e1eb9c0c29

**Comment by santini-cyber** [comment]
Tested collector this morning with new code. URLs captured as json files and can be moved in to the workspace + embedded. Getting the following error when executing the collector:  
print(f"Your estimated cost to embed this data using OpenAI's text-embedding-ada-002 model at $0.0004 / 1K tokens will cost {ada_v2_cost(tokenCount)} using {tokenCount} tokens.")
NameError: name 'tokenCount' is not defined

**Comment by timothycarambat** [comment]
Fixed `1e3d82e18485b60173362dd5c7c248abe0581f36`
