### ISSUE TITLE
Not being able to set chunk size for local.ai embeddings

### ISSUE THREAD

**Issue by Amejonah1200** [Mintplex-Labs/anything-llm#388]
https://github.com/Mintplex-Labs/anything-llm/blob/5ad8a5f2d0c545a913319a641877d70aa7b82b09/server/utils/EmbeddingEngines/localAi/index.js#L16

Why is this not configurable using `EMBEDDING_MODEL_CHUNK_SIZE` or something? Because some embedding models need lower chunk sizes. 
For example, [sentence-transformers/all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2#intended-uses) has a default of 256 "word pieces".

**Comment by Amejonah1200** [comment]
```diff
- this.embeddingChunkLimit = 1_000;
+ if(!process.env.EMBEDDING_MODEL_CHUNK_SIZE)
+   this.embeddingChunkLimit = 1_000;
+ else {
  let size = parseInt(process.env.EMBEDDING_MODEL_CHUNK_SIZE)
  if(size === NaN || size <=0) throw new Error("Invalid int for EMBEDDING_MODEL_CHUNK_SIZE."); 
  this.embeddingChunkLimit = size;
}
```Should do the trick.

**Comment by timothycarambat** [comment]
This is not the size of a chunk, its how many chunks can be sent at once via the API. Most embedding apis allow you to send many `n` long chunks at the same time so you dont have to send a request `n` times.

That is what the 1,000 is actually referring to. I imagine that with LocalAI, it cannot handle more than one request at a time though and that is likely the issue

**Comment by Amejonah1200** [comment]
Apart from this, I kinda doubt you can append 2 embeddings, as they would represent 2 different meanings.

**Comment by Amejonah1200** [comment]
https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/vectorDbProviders/qdrant/index.js#L172-L180

I found this code, as said: not every embedder can process such amount of tokens at once.
