### ISSUE TITLE
where to switch "dark" and "light" model

### ISSUE THREAD

**Issue by jamsnrihk** [Mintplex-Labs/anything-llm#391]
after i download the lastest version, i can't find where to switch the “dark" and "light" theme, please kindly advise.
originally, it should located in "Appearance Settings", but now only have logo and system messages setup.

**Comment by manzke** [comment]
it is not implemented as far as I have seen it in the code (only for the modals)

**Comment by timothycarambat** [comment]
We do not support a light mode anymore since the UI redesign. Simplifies the design of new screens and components. It will return in the future

**Comment by williamstein** [comment]
I just came here to comment that I would greatly appreciate a light mode.  I searched through all github issues, and there are several that mention lightmode, but no open issues involving light mode.

It's an accessibility issue -- for me personally I have vision issues that make it so I find dark mode very difficult to see.

(Obviously, this is open source and an amazing product, and I'm just putting in a humble tiny vote for light mode and that's all.)
