### ISSUE TITLE
Coding Support

### ISSUE THREAD

**Issue by mkammes** [Mintplex-Labs/anything-llm#4]
First off, this project looks extraordinarily useful!

If a user wanted help debugging code - or prototyping apps - what would be the best way to handle this?  Push to a github repo for the LLM to index, or perhaps flatten code into a PDF?

Keep up the good work!

**Comment by timothycarambat** [comment]
Oh you mean being able to consume code as a file? I would think it could be recursively possible using the langchain `git` loader or some other tool.

I would think right now it would be best to export these as .txt files with their line numbers for each file.

**Comment by martinsantos** [comment]
Error: Failed to fetch

in WORKSPACE creation?

**Comment by kichen1984** [comment]
Same as above. Getting a failed to fetch error on localhost:5000/workspaces. The settings tab gives an error "ENV settings are missing - this software will not function fully.". I'm using Chroma, commented out Pinecone and uncommented the Chroma section for clarity. When starting the server I'm also getting...

"[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --trace-warnings index.js`
[nodemon] clean exit - waiting for changes before restart" 

When you attempt to yarn dev:frontend after that it opens the frontend on port 3000 and restricts any update to settings in the vite dev environment. 

So close, any help is appreciated.

**Comment by timothycarambat** [comment]
@kichen1984 @martinsantos  Open a new issue when you issue is unrelated to the current topic.

@kichen1984 this is what your `server/.env.development` should look like
```
SERVER_PORT=5000
OPEN_AI_KEY=your-open-ai-api-key
OPEN_MODEL_PREF='gpt-3.5-turbo'
CACHE_VECTORS="true"

# Enable all below if you are using vector database: Chroma.
VECTOR_DB="chroma"
CHROMA_ENDPOINT='http://localhost:8000'
```

it is also possible there is another instance of the server running so run `sh clean.sh` after exiting the server to ensure the port is released when updating the .env because nodemon sometimes will not release it.
