### ISSUE TITLE
Password Complexity Check Capability

### ISSUE THREAD

**Issue by pritchey** [Mintplex-Labs/anything-llm#401]
This pull request add more sophisticated password checking capability.  Many organizations have requirements/audits/etc. that require specific password complexities to be used (length, upper/lower case, numbers and special characters).  This pull request does the following to the 'server' portion of the code:

1.  Requires the "joi" and "joi-password-complexity" npm packages.  The joi-password-complexity package provides the complexity check via a simple API and user configurable specification.
2. Adds a user configuration section to the .env.example configuration file at the bottom where the user can adjust the settings to meet their requirements.  These are commented out by default, and the current default mimics the current 8 character length requirement.
3. Adds calls to a password complexity check function in the server/models/user.js file to the 'create' and 'update' model calls.  The added function includes default complexity settings mimicking the current default, however it will automatically override those defaults with those specified by the user in their .env/.env.developer file.
4. In the event the password entered does not meet the requirements, the current error display capability included in the user dialog is used to display the requirements that were not met.

Pull request is #402

**Comment by timothycarambat** [comment]
resolved by #402
