### ISSUE TITLE
LocalAI API Key needed

### ISSUE THREAD

**Issue by lunamidori5** [Mintplex-Labs/anything-llm#405]
For my copy of localai we need a place to put in api keys, is there a way to do that?

**Comment by timothycarambat** [comment]
Well sure, we do that for Chroma, I'm more just curious on if that is supported by LocalAI or not since I dont ever recall seeing it :)

**Comment by lunamidori5** [comment]
> Can you point me to where in the documentation LocalAI supports API keys - or is this a custom wrapper around the LocalAI API that you run in front of the service?
> 
> If this is a custom wrapper what API schema do you support? `Authorization: Bearer` or `X-API-Key: xxxxx` type?

its the same as openai... if you add "API_KEY=" to your env file on docker setup, it will check for those keys on every request!

**Comment by timothycarambat** [comment]
TIL! I very much missed that. Thank you for that. Will work on this
