### ISSUE TITLE
issue: Error: 1 documents could not be embedded

### ISSUE THREAD

**Issue by Justin-KM** [Mintplex-Labs/anything-llm#406]
I deployed the docker image from the link:
docker pull mintplexlabs/anythingllm:master 

and run it with the following cmd in my MacBook Pro intelCPU
docker run -d -p 3001:3001 mintplexlabs/anythingllm:master

and I got this error when trying to vectorize a document, I try to use embedding models from both openai and azure, it doesn't make any difference:

Error: 1 documents could not be embedded.

**Comment by timothycarambat** [comment]
Can you tail the docker logs to report why the embedding failed? It should be in the logs and from there can trace what was the root cause.

**Comment by roedlmax** [comment]
Same Problem: here the Liog from Docker:

[TELEMETRY SENT] {

  event: 'document_uploaded',

  distinctId: '966042aa-53b7-4e18-a597-282a1515217f',

  properties: {}

}

Adding new vectorized document into namespace happy-18324266

Chunks created from document: 19

Error: Could not embed document chunks! This document will not be recorded.

    at Object.addDocumentToNamespace (/app/server/utils/vectorDbProviders/lance/index.js:211:15)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Object.addDocuments (/app/server/models/documents.js:56:26)

    at async /app/server/endpoints/workspaces.js:161:33

addDocumentToNamespace Could not embed document chunks! This document will not be recorded.

Failed to vectorize custom-documents/a-113626-XXXXXXXXXXXXXX-20230912t1050-ap-75487-13f389ba-1b17-418c-91df-e9dec3e42b75.json

[TELEMETRY SENT] {

  event: 'documents_embedded_in_workspace',

  distinctId: '966042aa-53b7-4e18-a597-282a1515217f',

  properties: { LLMSelection: 'localai', VectorDbSelection: 'lancedb' }

}

**Comment by Justin-KM** [comment]
here you go:
Chunks created from document: 7


Error: Could not embed document chunks! This document will not be recorded.

at Object.addDocumentToNamespace (/app/server/utils/vectorDbProviders/lance/index.js:211:15)

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

at async Object.addDocuments (/app/server/models/documents.js:56:26)

at async /app/server/endpoints/workspaces.js:161:33

addDocumentToNamespace Could not embed document chunks! This document will not be recorded.

Failed to vectorize custom-documents/8807-20231115-77f486ad-c2dc-4697-8421-101055077607.json

**Comment by Justin-KM** [comment]
thanks for your reply.
I spent some time today to trace down into source code and found the followingh http retturn of openai embedding api.
My guest is it is using async http calling openai embedding api, and the api doesn't like multiple calls.



------------------------
 Error: Request failed with status code 429
    at createError (/Users/justin/anythingllm/anything-llm/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/justin/anythingllm/anything-llm/server/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/justin/anythingllm/anything-llm/server/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {

**Comment by timothycarambat** [comment]
@Justin-KM Indeed, looks like a 429 error. Are you using the "free" version of the OpenAI API. A long time ago we had a question like this on Discord and that was the issue.

We have a couple known instances using OpenAi with ~20-30 concurrent users chatting during regular hours and never getting a 429. So wondering if this is an OpenAI account-level thing. Also if you are using the `gpt-4-turbo` model preview I believe the rate limits are lower on that model than others!

**Comment by roedlmax** [comment]
I am not shure if this is a rate limit issue. I run localai in docker with Mistral7B. I dont know where to set a rate-limit and there is no documentation where to set it. Localai gets the input, as follows:

The File i try to vectorize is named test.txt, the Content is: "Dies ist ein Text."

Output of localai Debug Log:

`[127.0.0.1]:44650 200 - GET /readyz

9:40AM DBG Request received: 

9:40AM DBG Parameter Config: &{PredictionOptions:{Model:mistral-7b-openorca.Q6_K.gguf Language: N:0 TopP:0.95 TopK:40 Temperature:0.2 Maxtokens:0 Echo:false Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 TypicalP:0 Seed:0 NegativePrompt: RopeFreqBase:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:mistral F16:true Threads:4 Debug:true Roles:map[] Embeddings:false Backend: TemplateConfig:{Chat:chatml-block ChatMessage:chatml Completion:completion Edit: Functions:} PromptStrings:[] InputStrings:[Dies ist ein Text.] InputToken:[] functionCallString: functionCallNameString: FunctionsConfig:{DisableNoAction:false NoActionFunctionName: NoActionDescriptionName:} FeatureFlag:map[] LLMConfig:{SystemPrompt: TensorSplit: MainGPU: RMSNormEps:0 NGQA:0 PromptCachePath: PromptCacheAll:false PromptCacheRO:false MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 MMap:true MMlock:false LowVRAM:false Grammar: StopWords:[<|im_end|>] Cutstrings:[] TrimSpace:[] ContextSize:4096 NUMA:false LoraAdapter: LoraBase: LoraScale:0 NoMulMatQ:false DraftModel: NDraft:0 Quantization: MMProj: RopeScaling: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0} AutoGPTQ:{ModelBaseName: Device: Triton:false UseFastTokenizer:false} Diffusers:{PipelineType: SchedulerType: CUDA:false EnableParameters: CFGScale:0 IMG2IMG:false ClipSkip:0 ClipModel: ClipSubFolder:} Step:0 GRPC:{Attempts:0 AttemptsSleepTime:0} VallE:{AudioPath:}}

[172.23.0.1]:57178 500 - POST /v1/embeddings

[127.0.0.1]:44682 200 - GET /readyz`

**Comment by timothycarambat** [comment]
You should put this as a bug in LocalAI, this is not a bug from AnythingLLM and appears to be related to how the model is loaded or run on the LocalAI side. AnythingLLM is just reporting back there was an error.
