### ISSUE TITLE
BUG #2 LocalAI with API KEY set can not pull model

### ISSUE THREAD

**Issue by lunamidori5** [Mintplex-Labs/anything-llm#417]
API KEY is not getting passed when AnythingLLM requests models from LocalAI when a API KEY is set. Returns a 401.

**Comment by timothycarambat** [comment]
Given that the API using the OpenAi `basePath` overwrite, I dont see anything wrong with the implementation here. Obviously getting a 401 means that the API key is expected by LocalAI, but AnythingLLM should be appending it here.

https://github.com/Mintplex-Labs/anything-llm/blob/8cc1455b721dfcea7e4f3b7d83787623f1054c91/server/utils/AiProviders/localAi/index.js#L9C4-L16

**Comment by lunamidori5** [comment]
@timothycarambat its not sending the API KEY with both model and embedding requests
```
2:48AM DBG [WatchDog] Watchdog checks for idle connections
[172.23.0.1]:46020 401 - GET /v1/models
2:49AM DBG [WatchDog] Watchdog checks for idle connections
2:49AM DBG [WatchDog] Watchdog checks for idle connections
2:50AM DBG [WatchDog] Watchdog checks for idle connections
[172.23.0.1]:46020 401 - POST /v1/embeddings
[172.23.0.1]:46020 401 - POST /v1/embeddings
2:50AM DBG [WatchDog] Watchdog checks for idle connections
[172.23.0.1]:46020 401 - POST /v1/embeddings
2:51AM DBG [WatchDog] Watchdog checks for idle connections
```

**Comment by lunamidori5** [comment]
Fixed the error with the embeds by copy and paste the code from the localai index file to the embeding index file
[index.txt](https://github.com/Mintplex-Labs/anything-llm/files/13622505/index.txt)

**Comment by timothycarambat** [comment]
Oh so just the API key is missing on the embedding and is not being inherited in the embedding file. Will update this right now then.

**Comment by timothycarambat** [comment]
Task: Update API key auth and UI for LocalAI embedding as the LLM model only use the API key currently.

**Comment by lunamidori5** [comment]
@timothycarambat dont forget models <3 deeply sorry for having to make yall do this
