### ISSUE TITLE
Cant use togetherAI api?

### ISSUE THREAD

**Issue by dillfrescott** [Mintplex-Labs/anything-llm#425]
I tried setting it up but it refuses to inference with the model

https://docs.together.ai/reference/completions

**Comment by timothycarambat** [comment]
We dont have a TogetherAI integration. How are you doing this in AnythingLLM?

**Comment by dillfrescott** [comment]
Oh, just via a localai endpoint. I got it working with fireworks.ai and I think its an issue with togetherai. I joined their discord server and a team member is looking into it. He set up anythingLLM himself and is running some tests

**Comment by timothycarambat** [comment]
Oh okay, well please let me know if you would like us to just integrate Together directly (the team member can also just contact us at team@mintplexlabs.com).

Could be done by EOD

**Comment by dillfrescott** [comment]
Oh thank you. You can add it if you think it would be beneficial but Its not exactly in high demand for me at the moment. I appreciate it though!

**Comment by timothycarambat** [comment]
@dillfrescott checking in, did their team help you out or do we need to get this live for you? Happy to do it if it means you can use AnythingLLM with your Together AI models

**Comment by dillfrescott** [comment]
They actually added a model list that should help. I havent checked to see if it actually works though

**Comment by timothycarambat** [comment]
Moved to #531
