### ISSUE TITLE
[UI-BUG] Navbar button bug while hovering over it

### ISSUE THREAD

**Issue by pranay911** [Mintplex-Labs/anything-llm#428]
The navbar buttons seemed to have incorrect CSS styling associated with them resulting in choppy hovering animation all of the buttons are getting shifted downwards by 1px while trying to hover over the navbar 

**Video attachment:** 

![llm](https://github.com/Mintplex-Labs/anything-llm/assets/65008142/03f9e9a1-f47a-40a3-bc66-4ebd4b3bfefa)

**Comment by timothycarambat** [comment]
Thank you for pointing this out. Should be fixed now ❤️
