### ISSUE TITLE
Ability to set max tokens for localai api?

### ISSUE THREAD

**Issue by dillfrescott** [Mintplex-Labs/anything-llm#430]
I need this feature!

**Comment by timothycarambat** [comment]
Would this limit apply to every workspace and chat sent? If so that can be configured for LocalAI LLM inferencing.

Is the chat running away and not terminating output?

**Comment by dillfrescott** [comment]
I added it globally right around here actually:

https://github.com/Mintplex-Labs/anything-llm/blob/ce9233c258a6769ddf4e640dd49623c5c7b0f37d/server/utils/AiProviders/localAi/index.js#L119

So I guess that works for me!

**Comment by timothycarambat** [comment]
Are we talking about configuring the `max_tokens` parameter?
