### ISSUE TITLE
Allow the SpaCy splitter choice in the settings

### ISSUE THREAD

**Issue by cesco69** [Mintplex-Labs/anything-llm#437]
It would be helpful to have the option to choose the type of splitter in the settings.

Currently RecursiveCharacterTextSplitter is the default option but in some cases other splitters may be more suitable.

For example, spacy divides text by language and provides a more semantic subdivision of the text.

Anyway this is a great project, many thanks

**Comment by timothycarambat** [comment]
Closing as wonfix for now, the reason being it relies on us running a python script to get spacy running or relies on the user doing so since no node-native bindings exist for that library. Other methods of splitting will be coming, but they will be native and not rely on external services.

**Comment by arty-hlr** [comment]
@timothycarambat Has there been an update on further (native) splitting methods?
