### ISSUE TITLE
BUG (LocalAI): API KEY not getting passed with Model Endpoint Request

### ISSUE THREAD

**Issue by lunamidori5** [Mintplex-Labs/anything-llm#438]
The API key is not getting pasted with the model endpoint request.

AnythingLLM WebUI - https://tea-cup.midori-ai.xyz/download/194f5aac-52de-402c-b41b-7d8aab4c1e9a-chrome_iA1fkmVQjf.png
AnythingLLM Docker - https://tea-cup.midori-ai.xyz/download/a3e43ba8-88d5-4262-9308-19fc10a711c8-chrome_OjTBcLreiT.png
Localai Docker - https://tea-cup.midori-ai.xyz/download/2dd29c56-b2a7-4b58-86b0-c2996ce8d5c3-Docker_Desktop_wwvzVr9xv6.png

**Comment by timothycarambat** [comment]
Closing as unable to replicate.
- I have a LocalAI instance running on LAN and i connect to it via NGROK. I start the container using the `API_KEY=sk-secret123` env parameter.
- I think try to visit `https://localaiURL/v1/models` in browser and receive a 401 status code as expected
- In AnythingLLM i put in `https://localaiURL/v1` as my endpoint URL and click off the input and AnythingLLM backend reports a 401 status code as well as the LocalAI logs for /models endpoint
- In AnythingLLM i then put `sk-secret123` into the LocalAI API key field and click off the input and all my models now appear in my dropdown.
- I then send a chat and get a streamed response from my model successfully.

Possible configuration issue with API_KEY environment variable in LocalAI docker container?

**Comment by lunamidori5** [comment]
@timothycarambat it must be that I am updating the .env and reinstalling, ill try using the GUI, bug is still there tho. and you did show it...

**Comment by lunamidori5** [comment]
> Closing as unable to replicate.
> 
> * I have a LocalAI instance running on LAN and i connect to it via NGROK. I start the container using the `-e "API_KEY=sk-secret123"` env parameter in docker startup command.
> * I then try to visit `https://localaiURL/v1/models` in browser and receive a 401 status code as expected
> * In AnythingLLM i put in `https://localaiURL/v1` as my endpoint URL and click off the input and AnythingLLM backend reports a 401 status code as well as the LocalAI logs for /models endpoint

Bug found and replicated... So I do not understand...

**Comment by timothycarambat** [comment]
> > Closing as unable to replicate.
> > 
> > * I have a LocalAI instance running on LAN and i connect to it via NGROK. I start the container using the `-e "API_KEY=sk-secret123"` env parameter in docker startup command.
> > * I then try to visit `https://localaiURL/v1/models` in browser and receive a 401 status code as expected
> > * In AnythingLLM i put in `https://localaiURL/v1` as my endpoint URL and click off the input and AnythingLLM backend reports a 401 status code as well as the LocalAI logs for /models endpoint
> 
> Bug found and replicated... So I do not understand...

you forgot the new two steps that proved the key **does** work!
> - In AnythingLLM i then put sk-secret123 into the LocalAI API key field and click off the input and all my models now appear in my dropdown.
> - I then save config & send a chat and get a streamed response from my model successfully.

You need to put in the key + API endpoint in their respective inputs and the dropdown will populate. Only one or the other and it wont. I dont understand the confusion?
