### ISSUE TITLE
[Docs] Update documentation for host.docker.internal resolutions on Docker Readme.md

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#439]
Often users of AnythingLLM will encounter a "bug" where AnythingLLM does not resolve a localhost instance URL of a vector database or Local LLM/Embedder inference.

This is due to Docker container `localhost` not resolving on the host system network and therefore a localhost URL will not work.

Let's update the documentation on the Docker page with a !TIP or !Important explaining you will need to use host.docker.internal for reaching localhost on the host machine from a docker container.

**Comment by Amejonah1200** [comment]
It would be also good to see some information on how LMStudio might be reachable.

**Comment by timothycarambat** [comment]
> It would be also good to see some information on how LMStudio might be reachable.

Reviewing the thread in LMStudio discord would it work to use `ngrok` to forward the request to a public facing IP? I know that is not sustainable (or safe) solution but that is what I do to connect to my GPU computer on LAN instead of getting its LAN IP each time for LocalAI - wonder if the same could be done in WSL environments?

`ngrok http 1234` on the host machine and use that URL in AnythingLLM?

**Comment by Amejonah1200** [comment]
@timothycarambat the idea is cursed. I love it.
