### ISSUE TITLE
Custom LLM

### ISSUE THREAD

**Issue by KPCOFGS** [Mintplex-Labs/anything-llm#440]
When I tried to use my own custom Llama model that I downloaded from internet, I see it says "Using a locally hosted LLM is experimental. Use with caution." When I tried to load a model by clicking "waiting for models," there is no response of it. If I want to add the custom LLM manually, I need to go the storage/models/downloaded ?

**Comment by timothycarambat** [comment]
Since running on the custom model selection will use CPU (or GPU if available or using Apple M-series chips) the next best option would be using a purpose built tool like [LocalAI](https://localai.io) where you can run the service with GPU acceleration and custom models (GGUF format).

You will likely get better performance this way by offloading the inferencing somewhere with a GPU.

It is also worth noting that running AnythingLLM in docker will force CPU base inferencing and not use your underlying host system. Only in development will the local model model use the underlying host system - hence why this is still in experimental :)

**Comment by songkq** [comment]
@timothycarambat  Hi, I'm also confusing why the gguf model cannot be loaded into anythingllm. When running anythingllm, Model Selection is always empty.  Could you please give some kind advice?
<img width="1406" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/4e409435-f5b4-4bfe-aa2a-d5f039d6d086">


![image](https://github.com/Mintplex-Labs/anything-llm/assets/30183023/d08b8a53-d99e-4250-831d-0157295d539d)

My env was built locally from source following the tutorial.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/30183023/919474bb-9a19-4d6d-a044-9bd08bd91dff)

My env: `Mac M1`
model path: `/app/server/storage/models/ggml-model-q4_0.gguf`

**Comment by KPCOFGS** [comment]
Hi! I think you will need to put the model under /server/storage/models/downloaded folder
![Screenshot from 2023-12-15 07-44-08](https://github.com/Mintplex-Labs/anything-llm/assets/100217654/7d25b0a5-af91-415c-a865-36bd5fdac48d)

**Comment by songkq** [comment]
@KPCOFGS  Thanks. It works after changing the `model_path` to `/app/server/storage/models/downloaded/ggml-model-q4_0.gguf`.

**Comment by songkq** [comment]
@KPCOFGS @timothycarambat Hi, could you please help me with this issue?
When I send a chat message to the local llm(https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v0.6), it could not respond to message. After resetting the llm preference, docker container crashed after sending  a chat message. 
<img width="431" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/391d8f1d-46fe-4d73-bf3d-92bc54c6129f">

<img width="479" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/dc4981eb-b7dd-4ee0-baaa-2e98cbab4884">

<img width="1349" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/2a666d02-5492-4a9e-b13b-b13297ba3a88">

**Comment by timothycarambat** [comment]
What do the docker logs say?

**Comment by songkq** [comment]
@timothycarambat Where can I find some log information for debug?

Even setting a LocalAI LLM server, anythingllm cannot build connections to the server. It seems that anythingllm also could not respond to message from the LocalAI server.  It works well only I set the OpenAI API as a LLM server.

LocalAI LLM server:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/30183023/1254a759-dd11-4729-9d36-f3d697a68bf2)


Local connection test:
```
curl http://localhost:8080/v1/models
{"object":"list","data":[{"id":"ggml-gpt4all-j","object":"model"}]}%
```

anything-llm with LocalAI server:
<img width="1181" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/707da62b-de21-45aa-a836-e636e7c3910c">

<img width="1172" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/d10d16ad-4385-479b-bd55-ce5d95526860">

anything-llm with OpenAI API Key:

<img width="1347" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/d4aaa6b6-adc9-4cce-bee8-2e3f01ae99d7">

<img width="1165" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/30183023/87bf0bb8-5897-463e-9096-4fe6c7f07cfd">

**Comment by timothycarambat** [comment]
The docker logs are available with however you run AnythingLLM, so `docker logs <CONTAINER_ID>` or if in docker desktop you can see it by clicking on the running container

**Comment by nihs269** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/82037705/d5fad1f5-89f2-4458-a12e-f1082098cc72)
where can I find this model?
