### ISSUE TITLE
I think there should be a /downloaded folder

### ISSUE THREAD

**Issue by KPCOFGS** [Mintplex-Labs/anything-llm#443]
Hi!
When I was reading the README.md file under /server/storage/models, I saw there is no /downloaded folder when the article mentioned "should be placed in the storage/models/downloaded folder." I at first thought it was a typo and did not create the folder but put my custom model directly in  "storage/models" folder. And then I built it...... It was then I realized I should have created the /downloaded folder

And I think it would be nice to modify the part "storage/models/downloaded " to "/server/storage/models/downloaded" because I was redirected to this readme.md file from the home page and I did not realize it was under server folder until some times after.

**Comment by timothycarambat** [comment]
Ah, i understand the confusion here. Its mostly because the STORAGE_DIR env is not the same for everyone so we initially didn't assume that the start of the path would be the default of `server/storage...`

Will update the documentation to clear that up!
