### ISSUE TITLE
is running with CPU cause higher memory consumption

### ISSUE THREAD

**Issue by KPCOFGS** [Mintplex-Labs/anything-llm#444]
Hi!
When I was using the project with a custom chat model, I realized that it uses some seconds to just spit out one word, and I realized that the program uses more than 10GB of memory at its peak, I use CPU because I don't have a GPU, could this be the reason why it's so slow?

**Comment by timothycarambat** [comment]
Yes, while the custom chat model feature is experimental it currently only uses CPU when in docker. When run in development mode on the host machine it will use your CPU w/GPU acceleration if available.

If you want to use the same functionality of a local model still but leverage your underlying system you can use a tool like [LocalAi](https://localai.io) for now :)
