### ISSUE TITLE
can not run by docker 

### ISSUE THREAD

**Issue by IxaKylin** [Mintplex-Labs/anything-llm#447]
this is my docker logs ， it can not start 

[2023-12-14 06:32:18 +0000] [10] [INFO] Starting gunicorn 20.1.0
[2023-12-14 06:32:18 +0000] [10] [INFO] Listening at: http://0.0.0.0:8888 (10)
[2023-12-14 06:32:18 +0000] [10] [INFO] Using worker: sync
[2023-12-14 06:32:18 +0000] [17] [INFO] Booting worker with pid: 17
[2023-12-14 06:32:18 +0000] [18] [INFO] Booting worker with pid: 18
[2023-12-14 06:32:18 +0000] [23] [INFO] Booting worker with pid: 23
[2023-12-14 06:32:18 +0000] [24] [INFO] Booting worker with pid: 24
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.0) to ./node_modules/@prisma/client in 225ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

warn Versions of prisma@5.3.1 and @prisma/client@5.3.0 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db

**Comment by AldrinL** [comment]
same here

**Comment by smartvis** [comment]
me too

# docker logs 3f3a
[2023-12-14 07:23:46 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2023-12-14 07:23:46 +0000] [9] [INFO] Listening at: http://0.0.0.0:8888 (9)
[2023-12-14 07:23:46 +0000] [9] [INFO] Using worker: sync
[2023-12-14 07:23:46 +0000] [21] [INFO] Booting worker with pid: 21
[2023-12-14 07:23:46 +0000] [22] [INFO] Booting worker with pid: 22
[2023-12-14 07:23:46 +0000] [23] [INFO] Booting worker with pid: 23
[2023-12-14 07:23:46 +0000] [24] [INFO] Booting worker with pid: 24
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.3.0) to ./node_modules/@prisma/client in 157ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client


warn Versions of prisma@5.3.1 and @prisma/client@5.3.0 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"

Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db

**Comment by tiagogcunha** [comment]
Same:
OS: Ubuntu 22.04.3 LTS 
Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db

**Comment by xkz0777** [comment]
Same, OS: macOS Sonoma 14.1.2

**Comment by timothycarambat** [comment]
Are you building from source or pulling from docker?

**Comment by tiagogcunha** [comment]
Building from source works but pulling from docker doesn’t

**Comment by timothycarambat** [comment]
All I run to boot up docker (without even using the default setup!) is
`docker pull mintplexlabs/anythingllm:master` (Digest: `sha256:b86d7d449f1fef0406fb5b128e88081627cbe464f43196f989f576c1c5197036`)

`docker run -d -p 3001:3001 mintplexlabs/anythingllm:master`

Then I can use localhost:3001 to use the container

**Comment by xkz0777** [comment]
> All I run to boot up docker (without even using the default setup!) is `docker pull mintplexlabs/anythingllm:master` (Digest: `sha256:b86d7d449f1fef0406fb5b128e88081627cbe464f43196f989f576c1c5197036`)
> 
> `docker run -d -p 3001:3001 mintplexlabs/anythingllm:master`
> 
> Then I can use localhost:3001 to use the container

Using this command works for me too

**Comment by AldrinL** [comment]
@timothycarambat then I assume the issue is with the external storage, right?
using external storage is recommanded when running with docker, can you find the RC and fix it?

**Comment by timothycarambat** [comment]
@AldrinL I couldn't possibly find the root cause since it works for me and others across various environments. Being I cannot replicate it you would need to debug on your system as the current documentation is correct.

If I had to guess, this is permission related and the docker container does not have permission to write to the directory you are using for storage outside of docker.

**Comment by AldrinL** [comment]
@timothycarambat just FYI, it might be because I am using root directory, but this works for me 
the only change seems to be `-u 0:0 \`
`export STORAGE_LOCATION=~/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
-u 0:0 \
--name anythingllm \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm:master`

**Comment by Allenxuxu** [comment]
Add `-u {user name}`

for example
```
docker -u root ...
```

**Comment by hoishing** [comment]
the problem is caused by not having write permission on anythingllm folder while creating the database file, setting user to root could do the trick, or change anythingllm folder mod to 777 can work around too.
