### ISSUE TITLE
Refer Directly to Docs

### ISSUE THREAD

**Issue by MilesP46** [Mintplex-Labs/anything-llm#45]
This is a SOLID project.

Would it be possible to leverage a specific prompt that would refer to a document(s) directly?

Say I need to pull A from Page X and pull B from Page Y, being able to directly point to where the information can be found would be helpful.

**Comment by timothycarambat** [comment]
Currently when you add documents to a workspace you get relevant document citations at the bottom of the message - so you know where that information comes from.

That being said, I _really_ want to add in-app document citations so you can go exactly the to doc + text it used in context. Langchain does not help here so we would have to roll our own.

Not a big ask at all, but half of what you are asking for is already live 🎉

**Comment by MilesP46** [comment]
> Currently when you add documents to a workspace you get relevant document citations at the bottom of the message - so you know where that information comes from.
> 
> That being said, I _really_ want to add in-app document citations so you can go exactly the to doc + text it used in context. Langchain does not help here so we would have to roll our own.
> 
> Not a big ask at all, but half of what you are asking for is already live 🎉

I appreciate the response - however, I don't think I was clear in what I meant.

What I am talking about is the ability to provide a specific prompt and direct OpenAI to look at the contents prior to returning a response.

Example: "I need you to determine whether or not Document X that is inside of my Vector database can be used for..."

Essentially, it is directing OpenAI to target those documents specifically as it relates to the conversation at large.

Apologies for the confusion.

**Comment by MilesP46** [comment]
Do you have any idea as to whether you will incorporate a direct reference?

**Comment by MilesP46** [comment]
Do you have any idea as to whether you will incorporate a direct reference?

**Comment by timothycarambat** [comment]
Going to mark this as closed since we will be implementing a slash command functionality to be able to refer to a document directly in a chat.
