### ISSUE TITLE
Add mistralai/Mixtral-8x7B-Instruct-v0.1

### ISSUE THREAD

**Issue by andsty** [Mintplex-Labs/anything-llm#450]
Trying with mistralai/Mixtral-8x7B-Instruct-v0.1 it seems that the chat works fine. when i add a document in my workspace the responses are not related to the document i have added at all

**Comment by timothycarambat** [comment]
Are you sure that the context from a relevant document is being passed to the model? Additionally, not all models behave the same. Are you running this via LocalAI or LMStudio or otherwise?

**Comment by lunamidori5** [comment]
> Are you sure that the context from a relevant document is being passed to the model? Additionally, not all models behave the same. Are you running this via LocalAI or LMStudio or otherwise?

Localai as of right now does not support Mixtral, they are working on adding support for it.

**Comment by lunamidori5** [comment]
@andsty Localai now supports Mixtral

**Comment by timothycarambat** [comment]
Closing this as wontfix since support for this would need to come from the provider itself (LocalAI, LMStudio or another provider) and not from AnythingLLM directly.

Since LocalAI supports this model now you can use that!
