### ISSUE TITLE
[Help Needed] How to deploy to Vercel?

### ISSUE THREAD

**Issue by Lerty** [Mintplex-Labs/anything-llm#452]
is it possible to deploy to Vercel and leveraging Azure OpenAI ?

**Comment by timothycarambat** [comment]
I am not familiar with Vercel deployments but being that the app is not Next.js and is not built for serverless applications I do not think we can support Vercel deployment environments unless they support a persistence runtime + storage.

**Comment by timothycarambat** [comment]
After investigating this I am going to close this as `wontfix` we cannot rebuild AnythingLLM to support a serverless arch as it would be too much lift. We designed AnythingLLM to be run on a persistent machine with a persistent disk and to port our code to support serverless would be far too much a lift and break compatibility with existing installations on servers.
