### ISSUE TITLE
If the filename is too long,I can't click the remove button

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#456]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/4c41fd37-2e36-49ef-bf8f-49679aa1bb1e)

Discovered a bug on this interface: When retrieving information from a website with an exceptionally long file name, it renders the delete button on the interface unclickable.

**Comment by srinivaspavan9** [comment]
Hi @timothycarambat,
I want to work on this issue but i am having trouble setting up the project.
Do i need to run the dockerized application for development as well ?

I ran the yarn setup command after cloning the forked repo on my pc and ended up getting an error :
'cp' is not recognized as an internal or external command,
operable program or batch file.

Thats when i realised that the application needs to be run in a docker container. 
Am i right ? Is there any documentation for project setup for development ? 
I need help setting up the project

**Comment by ayushgupta-1** [comment]
hi @srinivaspavan9, checkout the docs at : https://docs.useanything.com/private-deployment/run-anythingllm-locally
