### ISSUE TITLE
 adding additional  plugins/agents?

### ISSUE THREAD

**Issue by freedomtrain** [Mintplex-Labs/anything-llm#462]
Great Project !!!
Is it possible to extend anything-llm by adding additional  plugins/agents?
If it is possible can you point me to the documentation for this or to where in the code to start ? 

Thanks

**Comment by timothycarambat** [comment]
If you have an instance running you can visit the `api/docs` page and you'll be able to see all available endpoints where the world is your oyster!

We are scoping internally how to add a more "simple" plugin extension system, but for right now, that is what we have :)
