### ISSUE TITLE
docker-compose up -d --build failed with invalid docker-compose.yml

### ISSUE THREAD

**Issue by l0rdbarcsacs** [Mintplex-Labs/anything-llm#467]
Docker Compose version v2.23.3
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/blob/2d700b13f6f704bacb0fc09e18cb90f31d26feba/docker/docker-compose.yml#L1

> docker-compose version 1.29.2

need latest docker-compose
