### ISSUE TITLE
How to deploy the application on Google Cloud?

### ISSUE THREAD

**Issue by tipromon** [Mintplex-Labs/anything-llm#473]
I'm not being able to deploy the application on GCP, could someone maybe help me with a step-by-step or tutorial on how can i deploy on Google Cloud?

**Comment by timothycarambat** [comment]
This is in the docs - are these not sufficient? This documentation is community written so I have no explicitly tested it as working but its modeled off the AWS deployment pipeline, which for sure does.

https://github.com/Mintplex-Labs/anything-llm/blob/master/cloud-deployments/gcp/deployment/DEPLOY.md

**Comment by tipromon** [comment]
We actually have deployed the VM Instance inside GCP, but we are not being able to run the application on Cloud Run, it seems to be missing some instructions and steps on how actually run and use the application after we create the VM Instance, could you or someone else help with this?
