### ISSUE TITLE
Gemini Support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#489]
Adding support for the [Google Gemini API](https://ai.google.dev/)

**Comment by dmatora** [comment]
What about Gemini 1.5 Pro support?
It's so much better than 1.0

**Comment by timothycarambat** [comment]
@dmatora are you using that in AI Studio? Gemini 1.5 Pro is not available via the API and still is not for /models with a special invite. I can use it in the online chat UI, but still blocked via API.

**Comment by dmatora** [comment]
Hmm, good point, explains why I don't see billing for usage
Didn't check if it's available over API, just assumed it is

**Comment by dmatora** [comment]
@timothycarambat actually, I finally did check, and I can confirm that yes, it's available over api
<img width="2033" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/647062/ac8d19d3-ee5b-48ae-9850-f502a82f1419">

**Comment by timothycarambat** [comment]
`gemini-pro-preview-0409` was the model??

**Comment by dmatora** [comment]
<img width="220" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/647062/80ba4fa7-b063-4b26-a24d-313a98012a6a">

**Comment by dmatora** [comment]
it's 1.5 pro
