### ISSUE TITLE
Chunking and Text Splitter customization

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#490]
We should build out the text-splitting and chunking strategy to be more configurable per workspace. This should be delineated as an advanced setting since in general most should not need to change it. For those who understand the implications should be allowed to modify it.

[More on splitters](https://js.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/character_text_splitter)

It would make sense for the UI to have a way to set file extensions => splitter settings with a way to select a document to "preview" how a document would be split in real-time.

**Comment by j-loquat** [comment]
Consider using intelligent chunking approach like Unstructured:
https://medium.com/@unstructured-io

**Comment by timothycarambat** [comment]
It is likely not wise for us to spin up an embedded container running Unstructured inside of AnythingLLM to rebuild the document parser and/or rely on a third-party API for this. Their tool appears robust and powerful but I am not sure the dependency is worth overhead at this time currently. Will investigate further though

**Comment by j-loquat** [comment]
Agree it would be a challenge. No question that more intelligent "chunking" of content during ingestion will really help the quality of the future search results, however.
I wonder if there would be a way to offer a choice to send the documents to a second optional container that could run a different parser and then return the chunks (JSON format?) back to your main container for embedding? Sort of like an effects loop for a guitar amp.

**Comment by j-loquat** [comment]
Txtai looks very good as a one stop shop way of doing embeddings and different types of search:

https://neuml.github.io/txtai

**Comment by junxu-ai** [comment]
> We should build out the text-splitting and chunking strategy to be more configurable per workspace. This should be delineated as an advanced setting since in general most should not need to change it. For those who understand the implications should be allowed to modify it.
> 
> [More on splitters](https://js.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/character_text_splitter)
> 
> It would make sense for the UI to have a way to set file extensions => splitter settings with a way to select a document to "preview" how a document would be split in real-time.

strongly agreed with this point, as i noticed that the default embedding is a nightmare to get the right input for LLM generation.

**Comment by timothycarambat** [comment]
@junxu-ai do you mean the splitting or the embedding?

**Comment by mstfldmr** [comment]
are there any updates about this?

I need to be able to select different chunking strategies (per page, semantic, hierarchical...) per workspace

**Comment by arty-hlr** [comment]
I tried anythingLLM last week and I also agree, being able to customize how a document is split would go a long way towards better RAG.

**Comment by Zeddddd** [comment]
The current issue is that when the chunk size is too small, the returned answer only includes content from the chunk, and subsequent content (even within the same paragraph) is discarded. To address this, I increased the chunk size to 1024 and re-embedded the data by deleting the cache files and re-uploading & re-embedding the content. However, the recall performance worsened. It seems that contextual coherence measures are needed to ensure more complete information presentation.
