### ISSUE TITLE
[FEAT] Azure OpenAI answer streaming

### ISSUE THREAD

**Issue by jeffrey-devhkg** [Mintplex-Labs/anything-llm#491]
I tried using the Azure OpenAI LLM, the answer will not stream out, the processing icon just spins and after a while, the answer appears. When I changed the LLM preference to OpenAI, the answer streaming is working.

**Comment by timothycarambat** [comment]
Are you sure that your Azure OpenAI settings are input correctly? You need to be using the proper Endpoint and a valid streamable model from Azure. You should be able to use the same inputs and credentials in a regular POST request

**Comment by timothycarambat** [comment]
I just re-read this issue. So you _do_ get the answer, you just want it streamed. When we implemented Azure streaming was not available and we have not revisited it since initial integration.

Updating issue now.
