### ISSUE TITLE
Ollma stuck on `-- loading available models --`

### ISSUE THREAD

**Issue by ThatOneCalculator** [Mintplex-Labs/anything-llm#495]
When setting up with Ollama, it seems to not be able to find any of the models that I have installed. 

![image](https://cdn.discordapp.com/attachments/1114740395159597068/1189770183171125269/image.png)

**Comment by Abdoulaye-Sayouti** [comment]
If you are running it using Docker, you to access first the docker image shell with:
docker exec -u 0 -it docker_image_id /bin/bash

Then you need to install ollama :
curl https://ollama.ai/install.sh | sh

Then pull the model you want. From what I understood, anythingllm docker image can't have access to the ollama server insatlled on the host machine

**Comment by ThatOneCalculator** [comment]
Oh, well then that kind of makes anything-llm a bit useless for ollama users. Why would I want to reinstall ollama and have a duplicate of all my models? Other docker based frontends can access ollama from the host just fine.

**Comment by timothycarambat** [comment]
You need to use `http://host.docker.internal:11434` to be able to connect to localhost from outside the AnythingLLM docker container. Using 127.0.0.x or localhost will only resolve inside of the docker container running AnythingLLM while your Ollama instance is running on your host machine.

**Comment by drmetro09** [comment]
I have an issue where my ollama models are loading, but when i type anything in chat box of anything LLM the container of anything LLM crashes automatically any fix for this?

**Comment by ThatOneCalculator** [comment]
@timothycarambat why is this the case? Other Docker-based Ollama UIs can connect to 0.0.0.0:11434 normally

**Comment by timothycarambat** [comment]
@ThatOneCalculator AnythingLLM uses a network bridge and not the host network itself because we run other services within the container that resolve via localhost/loopback. In order to prevent port conflicts we only bridge to the host.

**Comment by ThatOneCalculator** [comment]
Tested and works. Please consider adding a warning like this when selecting Ollama:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/44733677/7dbaef99-d576-410c-8796-89b0ce4402fd)

**Comment by ThatOneCalculator** [comment]
Welp, doesn't work. Tried a single message and it crashed.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/44733677/eccce662-2f69-4e35-9505-eb06a7bf60e5)

From the podman container:

```
[TELEMETRY SENT] {
  event: 'server_boot',
  distinctId: 'ad98c37a-8a86-4625-bc10-a76a89ba3024',
  properties: { commit: '--' }
}
Primary server listening on port 3001
/app/server/utils/chats/stream.js:240
        fullText += chunk.message.content;
                                  ^

TypeError: Cannot read properties of undefined (reading 'content')
    at /app/server/utils/chats/stream.js:240:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by moritz-t-w** [comment]
I have the same issue with LocalAI
![image](https://github.com/Mintplex-Labs/anything-llm/assets/90388353/ded20bbf-4727-44b0-a104-49dee45c94aa)
LocalAI is running:
```
 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.50.0                   │ 
 │               http://127.0.0.1:8080               │ 
 │       (bound on host 0.0.0.0 and port 8080)       │ 
 │                                                   │ 
 │ Handlers ............ 73  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................ 13 │ 
 └───────────────────────────────────────────────────┘ 
 ```

**Comment by timothycarambat** [comment]
@moritz-t-w 
Do you see any relevant logs in the AnythingLLM docker container or the LocalAI container? If the request is going through and failing you would see logs on each container. Something from AnythingLLM and LocalAI reporting the request was denied and its status code.

**Comment by moritz-t-w** [comment]
@timothycarambat 
The LocalAI container did not recieve any requests, that's all I know. I don't know how to see the logs from the AnythingLLM container.

**Comment by bokey007** [comment]
its the same issue with me

**Comment by mdkberry** [comment]
this is closed, but if this info helps anyone else it had me confused for a bit. In the browser you put http://localhost:11434/ and it shows Ollama running but AnythingLLM doesnt find it like that and needs http://127.0.0.1:11434 

I ran into this issue on Windows 10 with the download install of Ollama and AnythingLLM (not the docker version). 

Instructions elsewhere had said to run powershell and type "ollama serve" it gives 127.0.0.1:11434 but without the http bit, so when you try to add that in the field it refuses it as it wants a URL (hence why I assumed localhost would solve it but it doesnt). I had to manually change it to http://127.0.0.1:11434 and then it found the models. 

A bit confusing that it wont work with "localhost" since that is what works in a browser, but this fixed the issue if anyone else hits it.

**Comment by timothycarambat** [comment]
Yeah, you have to specify `OLLAMA_HOST` as an env var to bind it to localhost, otherwise it defaults to 127.0.0.1

**Comment by kalilfagundes** [comment]
Try 0.0.0.0 instead of localhost or 127.0.0.1. Worked here.

**Comment by MilitantHitchhiker** [comment]
None of these solutions worked for me. My LLM models in Ollama are local .gguf models that I've imported.

**Comment by ParshvLimbad** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/103508696/d83a28bb-841a-437c-a54e-ce71dd0694ae)
what is the issue here please help

**Comment by MilitantHitchhiker** [comment]
I have fixed the issue.

**Comment by AIlvxiaobu** [comment]
```shell
export STORAGE_LOCATION=/disk/anythingllm && \
rm -rf /disk/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
chmod 777 $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
sudo docker run -d \
 --name anythingllm \
 --network=host \
 --env STORAGE_DIR=/app/server/storage \
 --health-cmd "/bin/bash /usr/local/bin/docker-healthcheck.sh || exit 1" \
 --health-interval 60s \
 --health-start-period 60s \
 --health-timeout 10s \
 --cap-add SYS_ADMIN \
 -p 3001:3001/tcp \
 --restart=always \
 --user anythingllm \
 -v ${STORAGE_LOCATION}:/app/server/storage \
 -v ${STORAGE_LOCATION}/.env:/app/server/storage/.env \
 -w /app \
 mintplexlabs/anythingllm 
 ```

**Comment by blackpyramid88** [comment]
<img width="525" alt="Image" src="https://github.com/user-attachments/assets/3dcf1faf-3c2a-4e64-bbbe-616b91002763" />

I can't get the models to load either. I had it working fine for weeks, I upgraded Ollama to a newer version and it wont load the models. So i uninstalled Anything LLM and reinstalled hoping it would reconnect and this didn't work. Also it wont allow me to change the port. Ollama shows it's serving in my browser like normal

**Comment by blackpyramid88** [comment]
<img width="466" alt="Image" src="https://github.com/user-attachments/assets/1cd5fff4-7a9e-4fa9-bbae-97cb5e98f5e8" />
This is on a WIndows 10 system. Not sure why it quit working

**Comment by jacfalcon0** [comment]
I'm also having the problem, nothing above solves it.

**Comment by RoLex** [comment]
Same. Has this been fixed yet?
