### ISSUE TITLE
Forgot login password

### ISSUE THREAD

**Issue by Rosejacka** [Mintplex-Labs/anything-llm#496]
What should I do if I forget my login password

**Comment by timothycarambat** [comment]
You can start a shell inside of the container and `cat server/.env` and you should be able to see it in there. If this is multi user there is nothing you can do.

**Comment by Rosejacka** [comment]
I am a single user, but I cannot see it in the. env file either

**Comment by Rosejacka** [comment]
@timothycarambat

**Comment by timothycarambat** [comment]
It is certainly there, if in docker you can `cat /app/server/.env` and its the value for `AUTH_TOKEN`
