### ISSUE TITLE
requirements.txt issue on Ubuntu

### ISSUE THREAD

**Issue by jlevy-io** [Mintplex-Labs/anything-llm#5]
Hey @timothycarambat , heard about this project yesterday and love the concept!   

I am running Ubuntu on WSL2 and I am able to get the frontend and server up but when I try to run the install in the /collector folder, I get the following: 

"error: PyObjC requires macOS to build"

I'm wondering if everything in that requirements.txt is needed for this to run on Linux?   If so then I'm out of luck

**Comment by timothycarambat** [comment]
Those requirements are exported from Unix (Mac) but I'm willing to bet that the offending library is `whaaaaat` for the CLI interface options.

Let me see if I can get an Ubuntu system going to see if that is what is breaking everything!

**Comment by jlevy-io** [comment]
> Those requirements are exported from Unix (Mac) but I'm willing to bet that the offending library is `whaaaaat` for the CLI interface options.
> 
> 
> 
> Let me see if I can get an Ubuntu system going to see if that is what is breaking everything!

Awesome, thank you!  I would greatly appreciate it.  I'm hoping my team can use this for chatting with up to date docs on npm packages we use in our projects

**Comment by jwaltz** [comment]
I wanted to second support for Ubuntu. I deleted all of the pyobjc packages from requirements.txt as well as whaaaaat, and removed the references to whaaaaat in collector/main.py. I never really intended to use that functionality, just upload some internal docs.

Also got some errors when referencing Lance:
```Cannot find module './x86_64-unknown-linux-gnu.node'
Require stack:
- /home/jwaltz/projects/anything-llm/server/node_modules/vectordb/native.js
- /home/jwaltz/projects/anything-llm/server/node_modules/vectordb/dist/index.js
- /home/jwaltz/projects/anything-llm/server/utils/vectorDbProviders/lance/index.js
- /home/jwaltz/projects/anything-llm/server/utils/helpers/index.js
- /home/jwaltz/projects/anything-llm/server/endpoints/system.js
- /home/jwaltz/projects/anything-llm/server/index.js Error: Cannot find module './x86_64-unknown-linux-gnu.node'
```
I commented out the lance import in [server/utils/helpers/index.js](https://github.com/Mintplex-Labs/anything-llm/blob/master/server/utils/helpers/index.js) and this stopped the errors.

Great project! Hope I can help contribute.

**Comment by skidvis** [comment]
I've spent so many hours trying to get this to work. If only someone would make a docker image.

**Comment by timothycarambat** [comment]
@skidvis it is an issue - feel free to contribute! #26

**Comment by kaboomskizzle** [comment]
Thank you so very much @timothycarambat for this magnificent contribution to humanity!

**Here is the exact error I get on Linux Mint:**
`Collecting pyobjc-core==9.1.1 (from -r requirements.txt (line 63))
  Downloading pyobjc-core-9.1.1.tar.gz (896 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 896.1/896.1 kB 14.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

**ChatGPT Notes:**
One popular alternative is pyobjus, a Python library that provides a bridge to the Objective-C runtime. It allows you to call Objective-C code from Python on Linux systems. Here's how you can install pyobjus:

I'm not exactly sure how this works, but I figured perhaps sharing the exact error might be useful. 
Without further ado, I'll try @jwaltz suggestion for starters.

Thanks again!
Kaboom.ski

**Comment by timothycarambat** [comment]
This can be resolved by just running anything LLM in the new Dockerized version that was merged in this PR #34 !

**Comment by jlevy-io** [comment]
@timothycarambat thank you so very much for the resolution!

**Comment by skidvis** [comment]
This is great news! Thank you!
