### ISSUE TITLE
 How can I use the microphone feature? I see that this section of code is disabled. How can I enable this functionality? 

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#504]
How can I use the microphone feature? I see that this section of code is disabled. How can I enable this functionality? Thank you.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/01a31c67-575c-4324-8c85-20653e118b2f)

**Comment by timothycarambat** [comment]
It is commented out because the functionality does not exist. At one point it was slated to be done but now is not on the roadmap. All this comment does is hide the icon but the entire backend to support this does not exist at this time
