### ISSUE TITLE
 Easily misleading knowledge base document references for users.

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#505]
I've identified an issue where if a question I pose does not exist in the vector knowledge base, it still displays the reference document information, and the content of the referenced document is incorrect. This can lead to user confusion, as they might think the answer comes from the vector knowledge base when it actually doesn't.

Could it be modified so that if the content to be queried does not exist in the vector knowledge base, the reference link is not displayed? This way, users would understand that the answer comes from the large model, not the vector knowledge base, making it clearer. Thank you!
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/3d447649-4127-4072-9ff4-93f8e6316e55)

**Comment by timothycarambat** [comment]
If you do not want to see "irrelevant" citations open the workspaces settings and increase the "Document Similarity Threshold"

It is low on purpose so that it err's on the side of providing sources vs not. This is not a bug and is just a principle of RAG.
