### ISSUE TITLE
Using Local LLMs

### ISSUE THREAD

**Issue by vanlaure** [Mintplex-Labs/anything-llm#506]
I am using a local instance and the LM Studio icon to use a local open source LLMs is not avaialbel.  I tried reloading and it is still not available. I also do not know how to update the app.  Can you help me run the local instance on my computer using LM Studios?

**Comment by timothycarambat** [comment]
This is more appropriate for the Discord, not a GitHub issue. You can find help in there. You can find a current link to the Discord in the README.

Thanks
