### ISSUE TITLE
'Number of Vectors' in Workspace Settings Not Updating Instantly After Uploading

### ISSUE THREAD

**Issue by pritchey** [Mintplex-Labs/anything-llm#516]
I was loading documents into a new workspace and noticed when I shifted from the "Documents" tab to the "Settings" tab the value for "Number of Vectors" was zero.  Exiting the settings dialog and going back in and going into the "Settings" tab triggered the value to be updated.  What I suspect is happening is the value for the number of vectors is retrieved when the workspace settings dialog is opened but not refreshed when moving from the "Documents" tab to the "Settings" tab.

To recreate:
1.  Create a new workspace.
2. Go into the workspace settings dialog for the newly created workspace.
3. Upload some documents and embed them into the new workspace.
4. As soon as the embedding is completed, go into the "Settings" tab and look at the "Number of Vectors", it will be zero.
5. Click the "x" to exit the workspace settings dialog.
6. Go back into the workspace settings dialog.
7. Click on the "Settings" tab and the "Number of Vectors" will now reflect the number of vectors in the database.

**Comment by brendankntb** [comment]
I don't know if it is just for me but the number of vectors in the Settings tab for all of my workspaces are showing zero even after leaving and reloading the Setting dialog.

**Comment by timothycarambat** [comment]
@brendankntb Which vector database are you using?

**Comment by timothycarambat** [comment]
Adding onto this issue, it is misleading because the number is also the total number of vectors in the database, not even for _just_ that specific workspace

**Comment by brendankntb** [comment]
> @brendankntb Which vector database are you using?

I am using the built-in lancedb database (via the docker image). I have had an initial look to see whether there is something I have setup incorrectly but so far I can't see anything I have changed to cause this.
