### ISSUE TITLE
"Could not respond to message" for Azure openAI

### ISSUE THREAD

**Issue by zhh210** [Mintplex-Labs/anything-llm#517]
I was following the [documentation](https://docs.useanything.com/feature-overview/llm-selection/microsoft-azure) for Azure openAI. The chat UI always gives an error "Could not respond to message". Is there a way to see where the error is from? The web UI doesn't show anything other than the generic error msg.

**Comment by timothycarambat** [comment]
- Open the docker container -> logs. You should see some type of error in the log once the chat had failed to send. This will help trace the error more easily.

- Which model are you using?
- What image tag are you using for the docker image?

**Comment by timothycarambat** [comment]
Ah! That is a very subtle difference. I wonder if there is a way we can do some URL pattern matching to prevent that easy to make mistake.
