### ISSUE TITLE
Use video in README

### ISSUE THREAD

**Issue by moritz-t-w** [Mintplex-Labs/anything-llm#521]
The gif in the README has some uggly compression artifacts and a limited color pallet.
Also:
> GIFs are an average of 5-10 times larger than an efficiently encoded MP4 video.

~ https://trellis.co/blog/gifs-vs-animated-videos-which-should-you-use

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/assets/16845892/16701245-697f-41ec-b443-a6ab747cb2dc

**Comment by timothycarambat** [comment]
![New Chat UI](https://github.com/Mintplex-Labs/anything-llm/assets/16845892/cfc5f47c-bd91-4067-986c-f3f49621a859)

**Comment by timothycarambat** [comment]
resolved with a2a903741de1dc36adfce21659f729ab131e0c2b

Prefer the autoplay of GIFs, but moved to uncompressed GIF hosted on Github CDN
