### ISSUE TITLE
Sitemap collector tries downloading/parsing image files.

### ISSUE THREAD

**Issue by Mike-Benoit** [Mintplex-Labs/anything-llm#53]
Sitemap collector tries downloading/parsing image files (ie: PNG)

It appears it only exclude PDF files, but perhaps it should only be including htm/html files instead?

**Comment by timothycarambat** [comment]
@skidvis Any idea on the best angle to attack this?

**Comment by Mike-Benoit** [comment]
Curiously, not sure why it avoids PDF documents, as those can be parsed. Perhaps a SiteMap w/PDF and SiteMap w/o PDF could be handy.

**Comment by timothycarambat** [comment]
@Mike-Benoit  What sitemap are you using? So I can test this

**Comment by skidvis** [comment]
@timothycarambat There's a PR to block images. 

@Mike-Benoit PDFs are only parsed in the hotdir folder. Using the sitemap feature to parse them would require downloading them to a temp folder somewhere, parsing them, and then deleting them. That feature currently does not exist, and it would also be problematic storage-wise if there were many large pdfs. 

If enough people ask for this, it may be worth implementing, but currently the hotdir should be where pdfs are handled.

**Comment by timothycarambat** [comment]
resolved by #56
