### ISSUE TITLE
other languages error

### ISSUE THREAD

**Issue by jansverre** [Mintplex-Labs/anything-llm#54]
When trying to add links with foreign letters (like the lovely ø or æ for intance) the log gives error 
addDocumentToNamespace PineconeClient: Error calling upsert: PineconeError: not supported value type Failed to vectorize website

and english articles go through as they should

**Comment by Adelao4** [comment]
noted

**Comment by timothycarambat** [comment]
This has been fixed since the merge of the new and improved document collector! 
`719521c307d81c430d7d90872768d6de556c38d7`
