### ISSUE TITLE
[FEAT] Milvus Vector Database Support

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#543]
[Milvus](https://milvus.io/) is an OSS database that should be able to support AnythingLLM vectors. Additionally, if it is not additional lift to support [Hosted Milvus](https://zilliz.com/) that would be great to support as well.

[Documentation on NodeJS SDK](https://github.com/milvus-io/milvus-sdk-node)

**Comment by zhanshuyou** [comment]
We have planned to support, you can assign to me
