### ISSUE TITLE
[FEAT] New User Level - Power User

### ISSUE THREAD

**Issue by dmerriman11** [Mintplex-Labs/anything-llm#547]
Reviewing the users, Default, Manager and Admin, it seems to be lacking one more level.

Power User: Admin or Manager adds them to a workspace, they have the ability to add docs and modify settings in that workspace only.

**Comment by calz1** [comment]
This is a great idea! The fact that you have to be a full administrator to use the document upload feature limits how widely it can be rolled out. I like the idea of someone who has broad rights to workspace but it isn't an overall admin.

**Comment by timothycarambat** [comment]
Moving to https://github.com/Mintplex-Labs/anything-llm/issues/1787
