### ISSUE TITLE
Pull Request Template for better Development

### ISSUE THREAD

**Issue by imjaglan** [Mintplex-Labs/anything-llm#557]
We should implement a PR template for getting a good understanding of the issue solved along with the extra description so that, whoever is going to review the pr can easily review it , Every time someone will make a pr he will see this PR description automatically.

If you Agree @timothycarambat , I volunteer to make a PR for this??

### 💻  Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Description of Change

- Here we can write the description of the change, or a Loom video explaining the code.

### Additional Information

-  Add any other context about the Pull Request here.

**Comment by timothycarambat** [comment]
Absolutely do need to do this. It's actually on our internal Asana board. Let the core-team handle this because there are some specific things that need to be added to this flow for Bugs/Features etc etc and other QoL items!

Thank you for making the issue because it's reminded me to do it!
