### ISSUE TITLE
Add multi-modal support for image generation (Ollama LLava, GPT4V, DALLE, SD)

### ISSUE THREAD

**Issue by jameschen83** [Mintplex-Labs/anything-llm#558]
Ollama support LLaVA model (Image to Text). I am wondering whether AnthingLLM can support to upload an image in chat window and then ask any question on the upload image?

**Comment by lunamidori5** [comment]
And Localai supports llava too

**Comment by Anto79-ops** [comment]
This would be great!

**Comment by rquast** [comment]
For reference, ollama webui has this feature if it helps. https://github.com/ollama-webui/ollama-webui/issues/220

**Comment by Chammar37** [comment]
Would be a great feature!
