### ISSUE TITLE
Can't input username from Web UI https://hostname/login

### ISSUE THREAD

**Issue by zhh210** [Mintplex-Labs/anything-llm#568]
The webUI works ok after I finished up onboarding and logging out. However, when I was revisiting the UI from `https://hostname/login` there's no way to input the username:

<img width="686" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/3037080/c883bc8a-a913-4ff3-8345-b8ebda163281">

Also the password doesn't work either as no username is provided to anythingllm. It was deployed to GKE with docker.

**Comment by shatfield4** [comment]
When it is showing just the password screen this means that you enabled password protection only without multi-user mode enabled. You can try to delete the docker container and reinstall it to set it up again and during the onboarding the 'Just Me' and 'No' for password protection. This will make your instance not protected at all and then later if you wish to enable either of the protection settings you can do so in the security settings of AnythingLLM.
