### ISSUE TITLE
Microsoft Azure OpenAI error

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#569]
Hi,

When I try to use Azure OpenAI I get this error.
What could it be?
I get this error from console:
_TypeError: this.openai.streamChatCompletions is not a function_

<img width="781" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/22151717/85476ce3-68a7-40de-be6f-732d8868acba">

<img width="417" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/22151717/a502bc99-775e-4cd1-8dc9-6b7edca74190">

![image](https://github.com/Mintplex-Labs/anything-llm/assets/22151717/cc7f154d-3b47-48f0-89dc-79a759b166bc)

**Comment by timothycarambat** [comment]
Can you verify the following?
- How are you running AnythingLLM (local dev, docker, docker on remote machine, etc)

- What `tag` & `digest` hash (if on Docker) or `commit` is your running instance of AnythingLLM is on?

**Comment by timothycarambat** [comment]
connect #518

**Comment by Mirgiacomo** [comment]
I confirm what you said, I had the updated sources but had not updated the libraries.
Thank you
