### ISSUE TITLE
anythingllm container not able to communicate with local ollama/lacalai models running on local host on Ubuntu 

### ISSUE THREAD

**Issue by bokey007** [Mintplex-Labs/anything-llm#585]
its the same issue with me

Primary server in HTTP mode listening on port 3001
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ollamaAIModels (/app/server/utils/helpers/customModels.js:84:18)
    at async getCustomModels (/app/server/utils/helpers/customModels.js:20:14)
    at async /app/server/endpoints/system.js:769:35 {
  cause: Error: getaddrinfo ENOTFOUND host.docker.internal
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'host.docker.internal'
  }
}

@timothycarambat I am facing this issue with both ollama and localAi

I think, this problem is specifically for linux machines.

_Originally posted by @bokey007 in https://github.com/Mintplex-Labs/anything-llm/issues/495#issuecomment-1890304226_

**Comment by bokey007** [comment]
Hi @sumitsodhi88 appreciate the response, yes I did. It did not work.

**Comment by timothycarambat** [comment]
This issue is certainly on your side and has to do with networking. So `host.docker.internal` is a special name when used within a docker container that allows it to access the host system `localhost`. However, both applications need to be running on the same machine. Alternatively, you can put the host machine's local IP as the address and it should still resolve. I do not think `host.docker.internal` works on ubuntu machines, as its part of docker engine.

**Comment by Botoni** [comment]
If it helps with anything, the host.docker.internal addres works for me in my linux machine, in my case Fedora 39 and Lm studio.

**Comment by befama** [comment]
I'm having similar problems. On Ubuntu 24.04. the error is the following: error: TypeError: fetch failed
 at node:internal/deps/undici/undici:12618:11
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 at async bocamaAIModels (/app/server/utils/helpers/customModels.js:310:18)
 at async getCustomModels (/app/server/utils/helpers/customModels.js:45:14)
 at async /app/server/endpoints/system.js:953:35

**Comment by timothycarambat** [comment]
> Ubuntu 24.04.

We need to add this to the docs page, but on ubuntu that docker workaround does not work. Instead it is this IP `172.17.0.1` _unless_ you run the container with `--add-host=host.docker.internal:host-gateway`.

Just a Docker linux quirk

**Comment by befama** [comment]
> > Ubuntu 24.04.
> 
> We need to add this to the docs page, but on ubuntu that docker workaround does not work. Instead it is this IP `172.17.0.1` _unless_ you run the container with `--add-host=host.docker.internal:host-gateway`.
> 
> Just a Docker linux quirk

Thanks for your reply.
The address you provided works just like the IP address assignment of the computer running Ollama. Thanks for that. However, the problem persists.

Despite configuring AnythingLLM with 172.17.0.1:11434 or the computer's IP address followed by :11434, and correctly selecting the installed models in Ollama, the problem occurs when I try to send a request in the chat. AnythingLLM doesn't seem to receive any response from Ollama and continues to display the following error, leaving the chat screen blank every time a message is sent. This never happened to me on ubuntu 22.04 the problem appears on ubuntu 24.04.01 version.

**Comment by timothycarambat** [comment]
Pull the `latest` image. There was a single build with an issue like that from commit 9584a7e1400a2ac581631f1901281c29c15224ba

Was fixed via https://github.com/Mintplex-Labs/anything-llm/issues/3018#issuecomment-2611369658 last week.

**Comment by timothycarambat** [comment]
`getCustomModels` is only ever called on the model selection page, so is not possible for that error to come from the chat page.

If the model dropdown populates, the connection works and so will chats. There is no way for us to only reach the `models` endpoint but on that same URL not be able to reach the `chat` completions

**Comment by ingvardm** [comment]
Same issue over here. Everything can connect to my local ollama except Anything-llm that runs on same machene.

**Comment by timothycarambat** [comment]
@ingvardm Like others, are you trying to use `localhost` in a docker container?

On non-linux: localhost => `host.docker.internal`
On linux/Ubunut: localhost => `172.17.0.1`
