### ISSUE TITLE
[BUG]: Not able to delete empty custom messages in the Apperance pane.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#586]
### What would you like to see?

A very small bug. 
![Screenshot 2024-01-13 232111](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/bf2276a0-ae72-4ca6-bd25-e00f7324b2cc)
I deleted the custom message completely including the "Double click to edit..." message. The area to enter the message got hidden. Now it is coming as an empty message at the homepage.

**Comment by chinmaym07** [comment]
Hey @timothycarambat 
can I work on this ?

**Comment by timothycarambat** [comment]
@chinmaym07 sure!
