### ISSUE TITLE
[FEAT]: Privacy Scoping: Documents, Workspaces and Chats

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#587]
### What would you like to see?

So we have several managers with several teams working under them. The data for each team is sensitive in nature and should not be shared outside of the circle. But as the other teams have the access to all the documents uploaded, this brings a risk to our work and may cause leakage. Please make a provision to hide uploaded documents to the other managers.

And why are the all workspaces be available to all maangers. Let the admin decide whom to give access to the workspace except the ones created by the managers themselves.

Another issue is that the managers should not be allowed to see chat history and only administrator should have that right. This feature is required to implement in large organisations where we require several managers with separate workspaces.

Eesentially three features are required:
1. Document privacy.
2. Workspace privacy.
3. Chat privacy.

![Screenshot 2024-01-13 233023](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/9fbd086a-48f7-468c-b872-a162ffa40761)

**Comment by rpaGuyai** [comment]
@timothycarambat  This is very important feature, we are unable to roll out at enterprise level due to this, there should be super user / workspace level manager/admin access, current manager role doesn't really make sense as the manager can see all the work spaces.

**Comment by timothycarambat** [comment]
Moving to https://github.com/Mintplex-Labs/anything-llm/issues/1787

**Comment by rpaGuyai** [comment]
Hi @Timothy ***@***.***>

Just want to understand the exact change that has been implemented in this patch to modify the access control.

I re-installed but didn’t see any workspace level change, as a manager I can still view all the workspaces, Idea was to have workspace level manager/super-user access.

Please could you help in elaborating on the changes implemented, also I saw some other features have stopped working:


  1.  As a manager we can still see other workspaces along with the documents uploaded for each workspace.
  2.  The answers to the query have become extremely slow which was lightning fast in the previous version using the same LLM.

Could you guide me how to roll back to previous version, I have installed using docker.

Linux Installation ~ AnythingLLM (useanything.com)<https://docs.useanything.com/installation/desktop/linux>

Thanks

Faraz
