### ISSUE TITLE
[FEAT]: Some very small changes in the UI.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#588]
### What would you like to see?

1. The login image has very high resolution and some of the text has also been added at the bottom of the image in our case. when logged in the image looks odd on the top of the screen (in case of the mobile). Please add this small change to add another image that can be showed after logging in.

2. Additionally, if the image of the LLM bot in the chat can also be changed, it would be nice. although the current one also not so bad.
3. The Favicon.ico should also be allowed to change with the Text for the docker implementation. 
4. The support email should be allowed to be changed as I don't want people from my organisation to fill up your in-boxes if they have forgotten their id-passwords 😆 
5. each workspace can have one custom message so that people using that workspace for the first time can be told what to expect and how to chat.
6. more independence to make small changes in application .env for the people using docker desktop.

![Screenshot 2024-01-13 233847](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/a40ccf61-7073-4df9-b0c6-878ae529cea0)

**Comment by timothycarambat** [comment]
> I would like to add the following small change in the interface. Please give the option in the system preferences to remove the "github", "docs" and "discord" icon. Or at least be able to change the links of those icons, in order to point the people of the organization to local information.

This has been live since https://github.com/Mintplex-Labs/anything-llm/pull/694 was merged

**Comment by timothycarambat** [comment]
> The login image has very high resolution and some of the text has also been added at the bottom of the image in our case. when logged in the image looks odd on the top of the screen (in case of the mobile). Please add this small change to add another image that can be showed after logging in.

This is something that can be revisited in the future. Right now it is a low priority but I can understand your concern there. 


> Additionally, if the image of the LLM bot in the chat can also be changed, it would be nice. although the current one also not so bad.

#706 

> The Favicon.ico should also be allowed to change with the Text for the docker implementation.
Since we compile the entire public folder into the server folder inside the docker container, this can be tricky for us to support since the favicon is not linked outside the container. Again, this falls to a lower priority then some of the other items outlined

> The support email should be allowed to be changed as I don't want people from my organisation to fill up your in-boxes if they have forgotten their id-passwords 😆
#707 

> each workspace can have one custom message so that people using that workspace for the first time can be told what to expect and how to chat.
Merged with https://github.com/Mintplex-Labs/anything-llm/pull/664

> more independence to make small changes in application .env for the people using docker desktop.
You can edit the .env in the bound docker storage already! Any changes made will take effect on container restart!
