### ISSUE TITLE
[DOCS]: Method of updating the docker image is not clearly given.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#589]
### Description

It is good that the application is being updated with the latest features. I am using Ollma and Anything LLM both in the docker, and it is running on my old Acer Nitro 5 like a charm. But I would like to update the application as soon as a new version is available. I would love to have a single command to update the application. If it is already there, please provide one in the documentation. I am a vey newbie to all these things, so I am sorry if I am raising an issue like this.

**Comment by timothycarambat** [comment]
All you need to do is stop the running container of AnythingLLM
run `docker pull mintplexlabs/anythingllm` (will pull latest image)
then restart container pointing it at the same place the previous container was storing information at

```
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```
