### ISSUE TITLE
Default prompting kills off creativity/hypothetical scenarios

### ISSUE THREAD

**Issue by simonSlamka** [Mintplex-Labs/anything-llm#59]
Hey there,

Based on my several experiments using both `gpt-3.5-turbo-16k` and `gpt-4`, I have observed that the responses returned by the API are incredibly rigid. Both models continuously refuse to be creative. I do writing as a side hustle and wanted to use semantic search as a tool for finding connections in a vast universe that I had already written, but here, it appears that the models either respond if they "find a match" or simply say that they don't know. Therefore, if you want to ask about hypothetical scenarios or developmental queries (e.g. "*expand character XYZ based on the available details*") based on some context given by your documents. I am pretty sure prompting is the issue here, so it would likely help if there was a user-friendly way to manipulate the prompt. I might take a look at it later, though I don't have much experience with web dev.

Thanks!

**Comment by timothycarambat** [comment]
Great comment. Langchain does not give much clarity into how the query-mode prompt is arranged, but it could for sure be a setting on workspaces along with temperatue

**Comment by timothycarambat** [comment]
This has been done and is available in workspace settings! `System prompt`
