### ISSUE TITLE
[FEAT]: Sorting and Folder Mangement

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#591]
### What would you like to see?

![Screenshot 2024-01-13 233023](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/fc6530fe-0312-4322-9a60-6acb6dd746ba)

Please provide good folder management so that the documents uploaded can be managed. I have to upload 1000s of documents.

Also provide ability to rename the files, in some cases it is taking some other name than the file name. (issue with pdf only) but that is a pain

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/554
