### ISSUE TITLE
[BUG]: Embeddings not removed.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#594]
### What would you like to see?

Even though I may have added and saved one embedding in a workspace and later realised it was not giving me correct results, I removed it. But in the workspace it was still given as citation - and yes it was giving answers from that only.

The embeddings are not getting removed when I choose to remove from a workspace, my only solution was to remove the work space completely and make a new one.

**Comment by wepschmiede** [comment]
I have the same problem as sumitsodhi88, the embeddings are not being removed cleanly for me either. Is there already a solution?

**Comment by timothycarambat** [comment]
This is for lanceDB correct? The current workaround, if suitable, if just deleting the workspace and re-embedding the cached files. Obviously not ideal but we are working on the solution.
