### ISSUE TITLE
[FEAT]: Limit Response to only the Custom Data provided

### ISSUE THREAD

**Issue by bibutikoley** [Mintplex-Labs/anything-llm#597]
### What would you like to see?

I'm new to the world of AI and still exploring the features that this repo offers.
Not sure if it works in the current version or not (If it does work, please let me know how can I do it)

Is it possible that LLM/Bot provides response only from the documents that is provided to it while embedding i.e. vector database. The bot should **NOT** use its own knowledge or data from internet. 
Please let me know how can this be achieved.

Thanks!

**Comment by timothycarambat** [comment]
@sumitsodhi88 This is a problem with your model or the settings of AnythingLLM workspace (such as threshold) and not something that this application explicitly controls.
