### ISSUE TITLE
[FEAT]:  Does the API interface support streaming output when used for chat?

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#599]
### What would you like to see?

 Does the API interface support streaming output when used for chat?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/395502bd-a44c-43f3-8b8e-3a921bc71ad8)

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/562
