### ISSUE TITLE
[FEAT]: Document Upload Api should return details

### ISSUE THREAD

**Issue by netclectic** [Mintplex-Labs/anything-llm#600]
### What would you like to see?

When uploading documents through the API, the response should return the details of the uploaded document. I would expect to see the same details that are returned from a Get request to /documents (expect for a single document).

It would also be useful if the document item in the response included the full path to the document, as it would be used in a call to update-embeddings.

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/570
