### ISSUE TITLE
Conversation mode

### ISSUE THREAD

**Issue by shipb** [Mintplex-Labs/anything-llm#61]
Readme says there are 2 conversation modes: "Two chat modes conversation and query. Conversation retains previous questions and amendments. Query is simple QA against your documents"

How do i use Conversation mode? I seem to be stuck in QA. (or is that not implemented yet?)

**Comment by frknue** [comment]
Yeah I'm interested in that too.

**Comment by timothycarambat** [comment]
For those of you who see this and are wondering where it is - it is in the roadmap. There are some vector dbs which wont support this so easily but it is being worked on soon 👍 

_stay tuned_

**Comment by AntonioCiolino** [comment]
please update the readme? I understand rationale, but it's confusing.

**Comment by alexnklein** [comment]
Tim would you be open to putting it live just for certain VectorDbs so we can get started on it or are you committed to launching it with multi Db support from day one? I'm certainly keen to try it with ChatGPT/Pinecone. I feel like if you get just this implementation in you're going to pull a lot of users out of a lot of unreliable plugins on the official site.

**Comment by timothycarambat** [comment]
@alexnklein @frknue 

Conversation mode is now the default and live for all vector databases
PR: https://github.com/Mintplex-Labs/anything-llm/pull/112

**Comment by alexnklein** [comment]
Awesome updating now
