### ISSUE TITLE
[FEAT]: llama index

### ISSUE THREAD

**Issue by drewskidang** [Mintplex-Labs/anything-llm#623]
### What would you like to see?

if we change back to use llama-index, do we have to change the front end??

**Comment by timothycarambat** [comment]
How would you even use Llama index in the frontend? We hardly even have and Langchain dependencies. Can you clarify what you mean?

**Comment by drewskidang** [comment]
apologies for some reason i thought langchain was used on the back end

**Comment by timothycarambat** [comment]
It is, but only in some specific areas. Namely for text splitting and for ease of implementation of some document loaders - that's all.
