### ISSUE TITLE
Can't build docker image on Mac M1 Max, keep getting following error

### ISSUE THREAD

**Issue by ICreativeKid** [Mintplex-Labs/anything-llm#63]
ARCH=arm64 docker-compose up -d --build
WARN[0000] The "CLOUD_BUILD" variable is not set. Defaulting to a blank string. 
[+] Building 0.2s (3/3) FINISHED                                                
 => [anything-llm internal] load build definition from Dockerfile          0.0s
 => => transferring dockerfile: 3.99kB                                     0.0s
 => [anything-llm internal] load .dockerignore                             0.0s
 => => transferring context: 299B                                          0.0s
 => ERROR [anything-llm internal] load metadata for docker.io/library/ubu  0.1s
------
 > [anything-llm internal] load metadata for docker.io/library/ubuntu:jammy-20230522:
------
failed to solve: ubuntu:jammy-20230522: error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``

**Comment by frasergr** [comment]
This looks like an issue with your computer being able to get the base Ubuntu image from Docker

**Comment by timothycarambat** [comment]
This should be resolved by #60
