### ISSUE TITLE
Ollama setup Not working

### ISSUE THREAD

**Issue by rdhillbb** [Mintplex-Labs/anything-llm#633]
I am unable to get ollama to work. I have included in this submission the following
System Configuration
AnythingLLM Olama Entry
Docker File Change for local host.
End User Error Message
Internal Error Message
If you can provide some guidance on document I need to look at  or configuration setting. Much appreciated. 

**_Thank You_**

**System Configuration:**
Macbook Pro running Sonoma
I9 Intel Processor
32 G memory

**Configuration anythingLLM Olama LLM Selection**
Ollama Base URL
http://127.0.0.1:11434
Chat Model Selection
-- loading available models --
**<NOTHING LOADADS>**
Token context window
4096

**Container Setup  Docker Yamal File**
extra_hosts:
      - "host.docker.internal:127.0.0.1"

**Displayed Error Message**
Failed to save LLM settings:

localhost, 127.0.0.1, or 0.0.0.0 origins cannot be reached from inside the Anything LLM container. Please use host.docker.internal, a real machine IP, or domain to connect to your service.

**Internal Error Message**
nything-llm  | TypeError: fetch failed
anything-llm  |     at Object.fetch (node:internal/deps/undici/undici:11730:11)
anything-llm  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
anything-llm  |     at async ollamaAIModels (/app/server/utils/helpers/customModels.js:88:18)
anything-llm  |     at async getCustomModels (/app/server/utils/helpers/customModels.js:21:14)
anything-llm  |     at async /app/server/endpoints/system.js:718:35 {
anything-llm  |   cause: Error: connect ECONNREFUSED 127.0.0.1:11434
anything-llm  |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
anything-llm  |     errno: -111,
anything-llm  |     code: 'ECONNREFUSED',
anything-llm  |     syscall: 'connect',
anything-llm  |     address: '127.0.0.1',
anything-llm  |     port: 11434
anything-llm  |   }
anything-llm  | }

**Comment by timothycarambat** [comment]
Yes, because in docker `127.0.0.1` resolves internally in the container, not on the host. 
```
"host.docker.internal:127.0.0.1"
``` is probably not required.

In AnythingLLM, just use `http://host.docker.internal:11434` instead of `127.0.0.1`. That is what that error message is trying to tell you. Localhost doesn't work in docker because it resolves inside the container.

**Comment by rdhillbb** [comment]
Thank you.
I will test it out.

**Comment by rdhillbb** [comment]
All good. Oly issue is Ollam is very slow.

**Comment by timothycarambat** [comment]
@rdhillbb The issue mainly here is the Ollama is using you're running on an Intel CPU. It's slow on my computer as well, but on an M-series chip it's lightning fast. That's just how it works for the amd86-based arch and no GPU support :/
