### ISSUE TITLE
 The accuracy of data retrieval is not high

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#645]
### What would you like to see?

During the testing process, it was found that the accuracy of data retrieval is not high, and there are often illusions when dealing with large amounts of data. Additionally, the answers provided are too brief. I suggest referring to this open-source platform: https://github.com/danswer-ai/danswer. The project utilizes intent recognition with a large model and re-ranking techniques, which significantly improve accuracy. Can you make some optimizations in this regard? The accuracy of data retrieval is the most critical part of the system. Thank you.

**Comment by GANJAC** [comment]
Hi huicewang, do you use native embedder ?

**Comment by huicewang** [comment]
Yes，bge-large





------------------ Original ------------------
From: GANJAC ***@***.***&gt;
Date: Fri,Jan 26,2024 1:08 AM
To: Mintplex-Labs/anything-llm ***@***.***&gt;
Cc: huicewang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Mintplex-Labs/anything-llm]  The accuracy of data retrieval isnot high (Issue #645)





 
Hi huicewang, do you use native embedder ?

**Comment by huicewang** [comment]
But the openai embedding is the same result





------------------ Original ------------------
From: GANJAC ***@***.***&gt;
Date: Fri,Jan 26,2024 1:08 AM
To: Mintplex-Labs/anything-llm ***@***.***&gt;
Cc: huicewang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Mintplex-Labs/anything-llm]  The accuracy of data retrieval isnot high (Issue #645)





 
Hi huicewang, do you use native embedder ?

**Comment by GANJAC** [comment]
Hi guys, excuse me for the delayed response, i have 95% mitigated this issue with this model:

https://huggingface.co/Xenova/multilingual-e5-large

as native embedder an qdrant vector db.

Also i use openorca mistral 7b served by llama-cpp-python as generative ai.

I hope this can help.

**Comment by timothycarambat** [comment]
@GANJAC This is an interesting model. I wonder if we could have this as an option for the native embedder as we currently use the [all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) model, but that model does not perform well with other languages (esp Mandarin).

What language are your documents? If they are English and the models are the same, I would be interested to see how that model performs unless it is too large to download on the fly

**Comment by GANJAC** [comment]
> @GANJAC This is an interesting model. I wonder if we could have this as an option for the native embedder as we currently use the [all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) model, but that model does not perform well with other languages (esp Mandarin).
> 
> What language are your documents? If they are English and the models are the same dimension, I would be interested to see how that model performs unless it is too large to download on the fly

Hi @timothycarambat, first of all thank you so much for your awesome work!!! My documents is Italian and English (50/50), from what i see the model **multilingual-e5-large** is more and more accurate than **all-MiniLM-L6-v2** in any languages, and despite it's size (2.7 GB) it's very fast in embeddings.

Hope this help.

**Comment by huicewang** [comment]
If a PDF file contains images, is there a good solution? Can OCR recognition be used to achieve this?



------------------ Original ------------------
From: GANJAC ***@***.***&gt;
Date: Tue,Jan 30,2024 4:11 PM
To: Mintplex-Labs/anything-llm ***@***.***&gt;
Cc: huicewang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Mintplex-Labs/anything-llm]  The accuracy of data retrieval isnot high (Issue #645)





  
@GANJAC This is an interesting model. I wonder if we could have this as an option for the native embedder as we currently use the all-MiniLM-L6-v2 model, but that model does not perform well with other languages (esp Mandarin).
 
What language are your documents? If they are English and the models are the same dimension, I would be interested to see how that model performs unless it is too large to download on the fly
  
Hi @timothycarambat, first of all thank you so much for your awesome work!!! My documents is Italian and English (50/50), from what i see the model multilingual-e5-large is more and more accurate than all-MiniLM-L6-v2 in any languages, and despite it's size (2.7 GB) it's very fast in embeddings.
 
Hope this help.

**Comment by Tiberius1313** [comment]
> Hi guys, excuse me for the delayed response, i have 95% mitigated this issue with this model:
> 
> https://huggingface.co/Xenova/multilingual-e5-large
> 
> as native embedder an qdrant vector db.
> 
> Also i use openorca mistral 7b served by llama-cpp-python as generative ai.
> 
> I hope this can help.


How can I switch the embedding model?

**Comment by timothycarambat** [comment]
@Tiberius1313 
Its in the settings on the sidebar under "Embedding preference"

**Comment by Tiberius1313** [comment]
@timothycarambat thank you for your fast reply.

I'm on Windows10 and AnythingLLM v.1.2.0. Left sidebar -> Settings -> Embedding preference. Do you change AnythingLMM Embedder to a different embedding model or did you use "LocalAI" / "Ollama"? I was able to run in LM Studio a local model (Mixtral 8x7b) but not an embedding model. In my UI there's no option to change the default embedder.

![Screenshot (6108)](https://github.com/Mintplex-Labs/anything-llm/assets/97293733/12b20ec2-1ad2-4114-ae00-71d2d6534b94)

**Comment by timothycarambat** [comment]
@Tiberius1313 in that above UI you just can click on any other provider and there will be options to load an embedder via OpenAi,Azure,LocalAI, and Ollama (requires additional setup on your end). The default app only ships with one embedding model due and is meant to be quite general and it notable does **not** perform well in multi-lingual documents. Basically only english. It is a small model (all-miniLM)

**Comment by timothycarambat** [comment]
see https://github.com/Mintplex-Labs/anything-llm/issues/780
@Tiberius1313 the multi-lingual model is not yet supported. That must be custom code?

Moving conversation to the above issue!
