### ISSUE TITLE
[BUG]:  Answers are not saved when using Azure OpenAI

### ISSUE THREAD

**Issue by cloutier** [Mintplex-Labs/anything-llm#646]
### What would you like to see?

After reloading, the answers are blank:
![MicrosoftTeams-image](https://github.com/Mintplex-Labs/anything-llm/assets/1014864/d1e84f1a-0daf-4f27-bf03-321dff176286)

I have tested switching to OpenAI, and it doesn't have this problem, only when using the azure version this happens.

**Comment by timothycarambat** [comment]
Just patched, if running locally or from repo you can re-pull. Otherwise when the [docker build completes ](https://github.com/Mintplex-Labs/anything-llm/actions/runs/7646264382)the new image will have the fix.

**Comment by cloutier** [comment]
Thank you! works now on my end
