### ISSUE TITLE
[FEAT]: [IMPORTANT] embedding chat into iframe for web page

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#663]
It would be very important and allow for expanded use in an expenential way, the possibility of add the ability to add a chat into a site via iframe

**Comment by timothycarambat** [comment]
Being done here: https://github.com/Mintplex-Labs/anything-llm/pull/656

(also don't say "important" please! It makes it seem urgent like security issue)
