### ISSUE TITLE
[FEAT]: Each Workspace should have it's own LLM preference

### ISSUE THREAD

**Issue by ithax-wb** [Mintplex-Labs/anything-llm#673]
### What would you like to see?

**Reason:**
I use LocalAI with AnythingLLM. I would like to use for each workspace a different LLM. Currently I use a Mistral 7B for each workspace defined in the system preferences. But I want to use in my "Coding Workspace" a finetuned coding model. And I would like to use in my "German Workspace" with a finetuned German LLM model that understands German even better. And I would like to use a specific Translation LLM in my "Translation Workspace". And so on.

**Implementation**
Please add a LLM Preference in the Workspace Settings that overrule the default LLM Preferences in the System Preferences. This way each workspace can be configured with their own LLM.

**Comment by timothycarambat** [comment]
This feature already exists. You can select any model connected to the current provider. The only limitation is you cannot swap between entire LLM providers.

This was merged Dec 28, 2023
https://github.com/Mintplex-Labs/anything-llm/issues/503

<img width="1761" alt="Screenshot 2024-02-05 at 9 47 21 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/cf71c001-4107-47a8-a9f4-276eae3a0508">
