### ISSUE TITLE
[FEAT]:  The display styles of the two interfaces are different.

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#686]
### What would you like to see?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/b8f38113-fc0f-49d1-8673-25c502b4aab5)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/a8a36732-729a-4dc8-b3b7-794a65bd93ab) 

The format of the content output by the large language model in the chat interface is different from the format of the information output when viewing chat logs. The content output in the chat interface does not display numerical numbering, but when viewing logs, there is numerical numbering, and the format is more orderly. Does this mean that the content output by the large language model does indeed have numerical numbering, but it is formatted away in the chat interface, making it appear less aesthetically pleasing, as shown in the figure?

**Comment by huicewang** [comment]
The default output of the large language model includes numbering and formatting, but these are removed in the output interface.

**Comment by timothycarambat** [comment]
resolved by 500e53dc8a03c17e4dcdc3eab68bd8a529afb03f
