### ISSUE TITLE
[FEAT]:  If I want to modify the format of the LLM output, which file's code should I edit? Thank you very much.

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#687]
### What would you like to see?

 If I want to modify the format of the LLM output, which file's code should I edit? Thank you very much.

**Comment by timothycarambat** [comment]
For the UI https://github.com/Mintplex-Labs/anything-llm/blob/master/frontend/src/utils/chat/markdown.js
Otherwise, it would be the system prompt dictating how the output should be listed
