### ISSUE TITLE
[API]: Support raw text + metadata uploads

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#688]
### What would you like to see?

Currently, we support the uploading of documents and links via the collector endpoints in the API. There is a use case though for an API user to directly send raw text and preferred metadata directly to the collector for it to then format and save.

*note* the metadata cannot allow arbitrary key values or else database schemas for many vector dbs will prevent the upsert as sometimes the metadata is spread into columns and the columns must be homogenous across that collection.

**Comment by timothycarambat** [comment]
@icsy7867 - merged

**Comment by icsy7867** [comment]
This looks great! Looking at th swagger right now:

```
{
  "textContent": "This is the raw text that will be saved as a document in AnythingLLM.",
  "metadata": {
    "keyOne": "valueOne",
    "keyTwo": "valueTwo",
    "etc": "etc"
  }
}
```


For the metadata bits - Can I set any field from the return response?  I.E url, docAuthor, title, published etc...?
```
{
  "success": true,
  "error": null,
  "documents": [
    {
      "id": "c530dbe6-bff1-4b9e-b87f-710d539d20bc",
      "url": "file://my-document.txt",
      "title": "hello-world.txt",
      "docAuthor": "no author found",
      "description": "No description found.",
      "docSource": "My custom description set during upload",
      "chunkSource": "no chunk source specified",
      "published": "1/16/2024, 3:46:33 PM",
      "wordCount": 252,
      "pageContent": "AnythingLLM is the best....",
      "token_count_estimate": 447,
      "location": "custom-documents/raw-my-doc-text-c530dbe6-bff1-4b9e-b87f-710d539d20bc.json"
    }
  ]
}
```

**Comment by timothycarambat** [comment]
@icsy7867 In that case, you can specify any of the fields from the `/api/v1/document/metadata-schema` endpoint. You can override the `url` metadata and the link will be present, but that won't be live until #689 is merged - so id wait for that first!
