### ISSUE TITLE
[FEAT]: Support ingestion of ebook formats such as epub, azw, mobi

### ISSUE THREAD

**Issue by gumbolastima** [Mintplex-Labs/anything-llm#709]
### What would you like to see?

I would like to suggest Anything LLM support the ingestion of ebook formats such as ebub, azw, and mobi. This will permit long-gathered local books to be included without having to convert them to a different ingestable format first.

**Comment by timothycarambat** [comment]
Very interesting. I imagine this should be easily extendable as a supported filetype. 
Relevant loader possibly - will have to see how it works: https://js.langchain.com/docs/integrations/document_loaders/file_loaders/epub

**Comment by sati-bodhi** [comment]
I second this proposal.

**Comment by sati-bodhi** [comment]
[privateGPT](https://github.com/imartinez/privateGPT) has this in-built feature.
