### ISSUE TITLE
[BUG]: GCP Cloud Deployment YAML

### ISSUE THREAD

**Issue by cloud-ray** [Mintplex-Labs/anything-llm#710]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Hello. I've come across an issue running the 'gcp_deploy_anything_llm.yaml' as is (on the Ubuntu instance).

The Docker container will start, but exit due to the issue "unable to open database file: ../storage/anythingllm.db".

The workaround I have found is running the command: sudo chown -R ubuntu:ubuntu /home/anythingllm

With this, the database creates properly. I've uploaded the workaround line to the yaml [in this repo.](https://github.com/cloud-ray/anything-llm-deployment)

I also wrote about my experience with AnythingLLM in this article: [Craft Your Own AI-Powered Knowledge Base: Wordpress + Ollama + AnythingLLM](https://cloudray.medium.com/craft-your-own-ai-powered-knowledge-base-wordpress-ollama-anythingllm-04dc4260dd37)

I'm not 100% sure this is the recommended way to fix it, which is why I did not submit a pull request. I'd be happy if you'd prefer.

Hope this helps!

<img width="874" alt="1-docker-exit" src="https://github.com/Mintplex-Labs/anything-llm/assets/120739995/c382b690-8218-4082-936c-89214bb7a262">
<img width="641" alt="2-chown-folder" src="https://github.com/Mintplex-Labs/anything-llm/assets/120739995/bf0b9b94-2464-44a0-ad8b-90205b2ca035">
<img width="897" alt="3-rerun" src="https://github.com/Mintplex-Labs/anything-llm/assets/120739995/2de58a82-8bb9-41b6-8f03-a332dcbada51">
<img width="688" alt="4-db-created" src="https://github.com/Mintplex-Labs/anything-llm/assets/120739995/cbac396c-0e20-44a0-a18a-4806e8093d8c">

**Comment by timothycarambat** [comment]
Hey @cloud-ray, this is a great write up. In my opinion I would be happy to merge a PR with that `chmod` fix. My primary reasoning is that the risk level of that folder running is quite low.

Alternatively, the alternative is changing the docker runner from using a user and running as root, which I'm less comfortable with.

We saw a similar issue with https://github.com/Mintplex-Labs/anything-llm/issues/702 and if you make that PR it would close two issues at the same time.

These templates are community-maintained anyway. That being said let me know if you would like to do the PR or if you would like us to handle it. Either way, I appreciate the write up and report on this.

**Comment by cloud-ray** [comment]
Hello @timothycarambat, thank you for your response. I'll submit the PR. #702 suggested _chmod_ and I used _chown_. Do you have a preference?

**Comment by timothycarambat** [comment]
`chown` makes more sense since we need to change the user ownership, not really the permissions since the entire system does not need access, only the user

**Comment by cloud-ray** [comment]
Thanks again for your help @timothycarambat!
