### ISSUE TITLE
[Doc]: DISABLE_TELEMETRY=true/false should be available in the docker .env template.

### ISSUE THREAD

**Issue by xpufx** [Mintplex-Labs/anything-llm#711]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I noticed in the logs that telemetry is enabled by default. I had to search github for the correct parameter to disable it. It should be in the .env template so people can search for it easily.

### Are there known steps to reproduce?

Run a modified .env file template from github without adding parameters to it.

**Comment by timothycarambat** [comment]
resolved by 347c95872dedddf785b393194fce6571895b80ca
