### ISSUE TITLE
How can I get started (development environment) 

### ISSUE THREAD

**Issue by brinrbc** [Mintplex-Labs/anything-llm#72]
I'm sorry for the question, but how can I start the server if I'm not deploying through docker? it is written how to upload documents and what to do next, I did not understand

upd: it was not obvious to me that the continuation of the installation was on the links [below](https://github.com/Mintplex-Labs/anything-llm/blob/master/collector/README.md) 

upd: upd: But there is also no way to start the server in development mode.

**Comment by tabgab** [comment]
I have to agree, I also could not find any description of this. It would be a great help if we had a concise and easy-to-follow way to get this running - in one readme, and not scattered all across the project.

**Comment by adieyal** [comment]
`yarn setup`
`yarn dev:server`
`yarn dev:frontend` (in another terminal)

have a look in `package.json` to better understand how it all hangs together.
