### ISSUE TITLE
[FEAT]: A New Role called User-Manager

### ISSUE THREAD

**Issue by ithax-wb** [Mintplex-Labs/anything-llm#727]
### What would you like to see?

I woulld like to have a new role that is allowed to only create default users and connect users to existing workspaces. This role is unable to create, modify or delete workspaces. This role is not allowed to change any other setting.

If AnythingLLM is placed in a organisation, this role would apply to certain managers.

**Comment by timothycarambat** [comment]
Moving to https://github.com/Mintplex-Labs/anything-llm/issues/1787
