### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by aixintiankong** [Mintplex-Labs/anything-llm#728]
### How are you running AnythingLLM?

Local development

### What happened?

i run AnythingLLM in production without Docker on macos. when i upload a pdf files, the error is "Error: ENOENT: no such file or directory, open '/Users/hua/collector/hotdir/FREE FEP+.pdf'. and i can't upload a pdf file. As the error reminds, the file “'/Users/hua/collector/hotdir/” does not exist, but the file "/Users/hua/anything-llm/collector/hotdir" exist. why the pdf is not upload to the exist file dircument. please help me to sovle the problem.
<img width="578" alt="Screenshot 2024-02-16 at 02 02 24" src="https://github.com/Mintplex-Labs/anything-llm/assets/12507774/305eb34c-46bb-46ad-8270-f865755d4017">

**Comment by timothycarambat** [comment]
If this is on local development you should not be setting the `STORAGE_DIR` environment var in `.env.development` - if unset it uses storage relative to the file in the entire repo - which would be the intended way to use it during local development.

All other deployment modes require a STORAGE_DIR to be set.
