### ISSUE TITLE
[FEAT]: Document Pinning

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#729]
### What would you like to see?

Users should be able to "pin" a document in a workspace where the entire context of the document (context permitting) is placed into the system message.

Doing this will override almost all other documents and settings for a workspace since we will need to maximize context window space and provide ample room for responses.

**Comment by stanribilir** [comment]
thanks Tim. sometimes when i don't pin the document, it retrieves no answer (with the query mode). when i pin it, i get some pretty good answers with my pdf. another detail is i use built-in embedding and vector db settings with 1000 chunks and 40 overlaps.

**Comment by timothycarambat** [comment]
Ah, so in query it does not seem to allow you to just use pinned docs, which i suppose can make sense but ideally when in query mode, pins should count and be allowed.

**Comment by wimkhan** [comment]
i don't even know what is the point of pinning a document in a anythingllm workspace? if you create it then it should has a meaning.

**Comment by wimkhan** [comment]
> What about "select all" and "pin it all"? Is it a good idea?

i do agree!
