### ISSUE TITLE
[BUG]:  In Query mode, will there still be an output of answers if the content of the query cannot be found in the knowledge base?

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#740]
### How are you running AnythingLLM?

Local development

### What happened?

 When the chat mode is set to Query mode, responses are generated even if the content of the question is completely unrelated to the knowledge base. However, the chat mode settings mention: "Query will provide answers only if document context is found." This implies that answers should only be given when the document context is identified. Is there a contradiction here?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/ac6d4aec-4fc7-4f3d-9841-6bc5e3a3be89)

**Comment by huicewang** [comment]
When displaying the cited documents, can the similarity of the documents be shown, or is there a sorting by similarity, otherwise the displayed content has a very low similarity and essentially no reference value?

**Comment by timothycarambat** [comment]
That context means that the RAG process determined that is was semantically similar (not that it was useful! It does not do an evaluation, only similarity). So it is possible to get context that is fundamentally useless for your question but did somehow get something from the vector db.

We can add the score to each chunk though - which I think would be useful for debugging - which again is only the score of its semantic similarity from the vector db, not that it will answer your question fully.
