### ISSUE TITLE
[BUG]: Getting started - LLM Preference - Ollama Base URL appears filled out but isn't

### ISSUE THREAD

**Issue by jcobol** [Mintplex-Labs/anything-llm#741]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

While going through the Getting Started flow, on the LLM Preference page with Ollama selected, the "Ollama Base URL" text field shows http://127.0.0.1:11434 which to me appeared to be already filled in as a default. I was confused as to why "Chat Model Selection" said "-- waiting for URL --" even though I had Ollama running locally.

Suggest either entering the default value explicitly or changing the appearance of the "ghost" value http://127.0.0.1:11434 so it is more obviously not actually entered.

**Comment by timothycarambat** [comment]
Will address this, closing as this is actually being tracked here: https://github.com/Mintplex-Labs/anything-llm/issues/556

You have been heard though! We will address this soon to prevent confusion.
