### ISSUE TITLE
[FEAT]: Live web-browsing for context

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#746]
### What would you like to see?

As a user, if my prompt results in no contextual documents from my vector database I should be able to have the LLM then search the internet for possible results to my query using a traditional search engine.

This is an opt-in feature that can be configured at the system level and enabled _per workspace_. This feature can only be enabled by admins/managers.

Providers:
- Default (web-scraper) - Subject to random failure, captchas, and other issues
- Google SERP API (free for ~1K calls) - Requires API key setup but is totally free [Reference](https://developers.google.com/custom-search/v1/overview)
- `?????` (please leave comment if you see this issue to suggest provider)

**Comment by dumengnan** [comment]
This is a very useful feature, maybe it would be better to use the google search api, web scrapers might get out of control.
If live web-browsing is added, is it necessary to classify the user's questions and identify whether the user wants to call the knowledge base, perform a web search, or directly talk to llm?

**Comment by DanSt** [comment]
How about the DuckDuckGo SerpAPI? https://serpapi.com/duckduckgo-search-api

**Comment by theEricDevelops** [comment]
The Hugging Face Chat UI allows web content with these methods: SERP API, SERPER API, SERPSTACK API, LOCAL WEBSEARCH, SEARXNG (this is the one I'm trying via [https://search.ericdevelops.com](https://search.ericdevelops.com)), and YOU API.
