### ISSUE TITLE
[FEAT]: Allow code file types

### ISSUE THREAD

**Issue by InTEGr8or** [Mintplex-Labs/anything-llm#747]
### What would you like to see?

I think the LLMs are capable of doing a lot of code analysis, right? Several of them are advertised as "code interpreters".

I must be missing something significant because I am wondering why code files are not allowed in the file upload.

Why aren't code file types allowed?

**Comment by InTEGr8or** [comment]
For additional background, I can easily convert a code file to a `.txt` file and then ask Ollama in AnywhereLLM questions about the code file and it answers as if it understands the code file and what I'm trying to do from the command line.

NOTE: I added this line to the top of the `.txt` file:

```txt
// this is the text version of a `build.gradle` file.
```


![image](https://github.com/Mintplex-Labs/anything-llm/assets/1802850/088a48e0-5bf6-4a9e-a510-99c4079c4cc1)

**Comment by nicho2** [comment]
is it possible to accept yaml and json files ?

**Comment by grantneufeld** [comment]
I would like an setting where we can add arbitrary file extensions to be treated as text. (e.g., `.c`, `.py`, `.swift`, `.cpp`, etc.)

Maybe even a setting where we can tell the app to try to open _any_ unrecognized file as text.
