### ISSUE TITLE
[FEAT]: Ugly Scrollbar

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#748]
### What would you like to see?

A simple scroll bar maybe a small black | line instead of full scroll bar.

**Comment by timothycarambat** [comment]
Where? Also which client? I find windows does the worst job in making a clean scrollbar which is why you will see `.no-scroll` as a class on may components because it just ruins the look and its _very_ tricky to override native scrollbars with custom CSS types.
