### ISSUE TITLE
[BUG]: .jpg load

### ISSUE THREAD

**Issue by MokkaBoss1** [Mintplex-Labs/anything-llm#749]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I have loaded the Llava model and would like to analyse a .jpg

However when I upload a file of this type to the chat, I receive an error message saying this is an invalid file type.

How should I use Llava's image analysis capabilitiy?

**Comment by timothycarambat** [comment]
Being tracked on https://github.com/Mintplex-Labs/anything-llm/issues/558
