### ISSUE TITLE
[BUG]: AnythingLLMDesktop.exe installer will not run

### ISSUE THREAD

**Issue by manjaroblack** [Mintplex-Labs/anything-llm#752]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I downloaded AnythingLLMDesktop for Windows. When I try to run the installer, nothing happens. I tried rebooting and redownloading, but the installer will not open. I am running Windows 11 Pro in a VM within Proxmox with my GPU passed through. Ollama is up and running without issues.

**Comment by manjaroblack** [comment]
I was able to install AnythingLLMDesktop.exe by running a Terminal, cd to my downloads folder then run ./AnythingLLMDesktop.exe 

This was the only way I could get the installer to run. I tried right clicking and running as administrator. I tried compatibility modes. I don't know what is different about running the installer via the Terminal, but there is a work around for anyone else experiencing this issue.

**Comment by FreezyExp** [comment]
Just sharing my two cents:

Perhaps your downloads folder is in a path that has some unexpected characters that might trip up the installer.
Could you place it in something like `c:\temp` if that works, then please check your downloads folder path and report anything that might be out of the ordinary.

Either that or windows forgot how to run exe applications, but that is unlikely.
Easily checked, harder to fix.

**Comment by timothycarambat** [comment]
I feel it is related to your specific runtime `Windows 11 Pro in a VM within Proxmox`. We built the desktop client for Windows Home, but regardless it should work no matter what so we should try to solve this for sure.

I am unsure why the installer wont even start (or why it requires terminal execution?). In your env is there still a `C:\Users\<usr>\AppData folder? Again, the installer _should_ account for this.

**Comment by Redcatsixtyfour** [comment]
After downloading the .zip installer and extracting AnythingLLM, I found that there was no .exe [installer] file in the folder.  Is there another method to install?  [Win 10 Pro 64bit]

**Comment by timothycarambat** [comment]
The .zip? We don't publish a .zip file of AnythingLLM. The only location we publish an exe is from the https://useanything.com/download website. The current exe location is https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop.exe

**Comment by Redcatsixtyfour** [comment]
Thanks for getting back.  I downloaded the .exe and all is good here.

The .zip I referred to is the ZIP download from github.  The link on your download page on the website took me to github.

Dan

------ Original Message ------
From "Timothy Carambat" ***@***.******@***.***>>
To "Mintplex-Labs/anything-llm" ***@***.******@***.***>>
Cc "Daniel Smith" ***@***.******@***.***>>; "Comment" ***@***.******@***.***>>
Date 2/24/2024 6:38:09 PM
Subject Re: [Mintplex-Labs/anything-llm] [BUG]: AnythingLLMDesktop.exe installer will not run (Issue #752)


The .zip? We don't publish a .zip file of AnythingLLM. The only location we publish an exe is from the https://useanything.com/download website. The current exe location is https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop.exe
