### ISSUE TITLE
[BUG]: Windows desktop app Get Started flow: Providing an email address isn't optional despite claim that it is

### ISSUE THREAD

**Issue by ackalker** [Mintplex-Labs/anything-llm#753]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

At the end of the Get Started flow, I'm presented with this screen:

![Screenshot 2024-02-18 163832](https://github.com/Mintplex-Labs/anything-llm/assets/429567/ac698901-e9ac-4280-9f59-26371a22ea41)

Despite the fact that the heading says "Optional", I cannot proceed with setup leaving the email field blank. Unless I fill in the email field, the arrow button to the right keeps popping up the admonition shown in the screenshot.

### Are there known steps to reproduce?

1. Download and run the desktop app installer for Windows.
2. Complete the setup process, choosing LLM, embeddings and vector store providers.
3. End up at the abovementioned screen.

**Comment by FreezyExp** [comment]
I can confirm, it is optional, the opt out could be a bit more obvious, but this is 2024, dark patterns in UI are everywhere now even in open source applications.
