### ISSUE TITLE
[BUG]: Response different between embed chat and workspace chat

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#755]
### How are you running AnythingLLM?

Local development

### What happened?

I noticed this anomaly:

I created a workspace where I uploaded some material. As a model I use GPT-3.5-turbo.
If from the platform where I create the workspaces I chat with the chatbot, and ask it questions that have nothing to do with it such as "How much does the sun weigh?", it responds correctly saying "_**I do not know the answer to that question. If you have any other questions related to Test test, feel free to ask! And remember, for any medical concerns, you can contact Test Hospital support at 000000 or e-mail test@test.it. To book a medical visit, you can visit: https://prenota.test.it/**_"
Which is the right answer I expect because I don't want to answer questions out of context.

<img width="886" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/22151717/6e0cfe17-232f-48c1-bc31-9904deb01559">

Going to embed this workspace in an iframe in a site, however, I found that when writing the same question, the answer it provides is different:

<img width="410" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/22151717/7d85421b-90bf-44f1-b87d-d06c5cc305a7">
Which is not the answer I expect.

The workspace is the same, the prompt is therefore the same.
I don't understand why it gives different answers.

It almost seems that in the embed part it does not take the prompt into consideration.

**Comment by timothycarambat** [comment]
Did you define a `data-prompt` property in the config and/or allow override of the system prompt in the config?

**Comment by Mirgiacomo** [comment]
Yes, it was not flashed.

After I cleared the cache it was working properly.... idk
