### ISSUE TITLE
Misguiding error message when creating a workspace

### ISSUE THREAD

**Issue by S-Maciejewski** [Mintplex-Labs/anything-llm#76]
### Problem: 
Creating a workspace gave me this error:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/20989002/35d84fef-3136-4dfb-8e06-1d224e3fa98a)

This is misguiding, the logs point to a problem with SQLite.
```
anything-llm    | SQLITE_CANTOPEN: unable to open database file [Error: SQLITE_CANTOPEN: unable to open database file] {
anything-llm    |   errno: 14,
anything-llm    |   code: 'SQLITE_CANTOPEN'
anything-llm    | }
anything-llm    | fetch failed TypeError: fetch failed
anything-llm    |     at Object.fetch (node:internal/deps/undici/undici:11457:11)
anything-llm    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
anything-llm    |     at async ChromaClient.heartbeat (/app/server/node_modules/chromadb/dist/main/ChromaClient.js:66:26)
anything-llm    |     at async Object.connect (/app/server/utils/vectorDbProviders/chroma/index.js:22:21)
anything-llm    |     at async Object.totalIndicies (/app/server/utils/vectorDbProviders/chroma/index.js:34:24)
anything-llm    |     at async /app/server/endpoints/system.js:84:27 {
anything-llm    |   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
anything-llm    |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
anything-llm    |     errno: -111,
anything-llm    |     code: 'ECONNREFUSED',
anything-llm    |     syscall: 'connect',
anything-llm    |     address: '127.0.0.1',
anything-llm    |     port: 8000
anything-llm    |   }
anything-llm    | }
```
The `TypeError` went away after switching to Pinecone but the `SQLITE_CANTOPEN` persists.

### Solution:
Improve error handling in the UI so that users don't get misguiding errors anymore and make the error message with `SQLITE_CANTOPEN` more descriptive (which file is the problem?)

**Comment by frasergr** [comment]
@S-Maciejewski This could be a permission issue if your host user UID and GID do not match the UID and GID values set in the ./docker/.env file.

**Comment by timothycarambat** [comment]
What commit are you on? This _should_ be resolved by the more recent commits. Additionally, if you did change the UID:GUID params it would fail to create the anythingllm db file on boot and would crash - only applies to docker.

If this was local development on your host machine then just create an empty `anythingllm.db` files in `/server/storage` and restart the server.

**Comment by S-Maciejewski** [comment]
Thanks for your help! It was indeed a problem with the UID and GID. 
They were both set to `'1000'` by default in `.env.example` but it didn't work for me. I changed it to `1000` (no quotes) and it worked fine.
Not sure why that's the case, I deployed it on Ubuntu 20.04 running on WSL (under Windows 11)
