### ISSUE TITLE
[FEAT]: Google Gemma Model

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#770]
### What would you like to see?

New Open Model by Google.

https://blog.google/technology/developers/gemma-open-models/

**Comment by timothycarambat** [comment]
This can be done by using the HuggingFace connector - however we should support VertexAI, which is the more native way to run these models on GCP infra.

Going to close this and open VertexAI issue

**Comment by timothycarambat** [comment]
Also this can be done in Ollama as of today
https://twitter.com/ollama/status/1760373589201600593
