### ISSUE TITLE
Private deployment. Non-Docker Windows 11. Unclear how to gain API access[DOCS]: 

### ISSUE THREAD

**Issue by thebaldgeek** [Mintplex-Labs/anything-llm#777]
### Description

Testing the suggested endpoint of /api/docs on port 3001 times out for both 'localhost' and '127.0.0.1'.
There are no docs that mention how to use / access the API for non-docker, private deployment of anything-llm.

Use case is to only use the desktop app for training. Once the LLM is ready to go, all access will be via home spun web page interface to the API.

Can the docs be updated for the Windows install API access.

**Comment by timothycarambat** [comment]
Non-docker? You are using the desktop app? The desktop app is more for a "single-player" experience and we likely won't expose the API that comes with the docker image because it doesn't really make sense for something that is basically all local.

However, I'm open to discussing this. Why do you need the desktop client API access and what is the use case? Happy to explore that.

**Comment by thebaldgeek** [comment]
Honest... I did watch your YouTubes and read all the docs here, but there was no mention that the different versions had different features.
Also it was not clear to me that the Docker version was an option?
There is no download link for Docker, hence thinking since Im running Windows, the windows download link here is the correct and only choice?
![image](https://github.com/Mintplex-Labs/anything-llm/assets/7385116/ddeff3d3-ffc3-4697-a850-aa294bbd9735)

Please point me to the WSL docker running on Windows download / install docs and I will go that way (Happy to nuke the 10+ hours I have in the embedding process).

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md#recommend-way-to-run-dockerized-anythingllm

Can get latest image from `docker pull mintplexlabs/anythingllm`. You can also keep the embeddings and progress you already have & you don't have to use WSL if you have a docker desktop client running on the host. WSL is known to give networking issues if trying to communicate with programs running on the same machine outside of WSL

Walkthrough on how to do this:
- Open the desktop storage folder at `C:\Users\<user>\AppData\Roaming\anythingllm-desktop\storage`. You should see several folders in this. This is the local storage of the desktop app.

- Create a folder where your docker information will persist. Typically this is `$HOME\Documents\anythingllm`. It should be somewhere your user has access to.

- Copy all of the contents of `C:\Users\<user>\AppData\Roaming\anythingllm-desktop\storage` into the `$HOME\Documents\anythingllm` directory (or wherever you decided to create the folder from the previous step.)

- Run the docker run command to start the container and use the existing storage folder.
```powershell
$env:STORAGE_LOCATION="$HOME\Documents\anythingllm"; `
If(!(Test-Path $env:STORAGE_LOCATION)) {New-Item $env:STORAGE_LOCATION -ItemType Directory}; `
If(!(Test-Path "$env:STORAGE_LOCATION\.env")) {New-Item "$env:STORAGE_LOCATION\.env"}; `
docker run -d -p 3001:3001 `
--cap-add SYS_ADMIN `
-v "$env:STORAGE_LOCATION`:/app/server/storage" `
-v "$env:STORAGE_LOCATION\.env:/app/server/.env" `
-e STORAGE_DIR="/app/server/storage" `
mintplexlabs/anythingllm;
```

The docker container should boot and you should have all of your data, embeddings, and settings ready to go, but now in the dockerized app.
