### ISSUE TITLE
[BUG]: LanceDBError Append with different schema when embedding

### ISSUE THREAD

**Issue by calmtortoise** [Mintplex-Labs/anything-llm#779]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When saving/embedding a document to the workspace I get the following error

LanceDBError: Append with different schema.

This only seems to occur with certain documents. I have successfully uploaded and embedded multiple documents and it will embed those into any Workspace but not specific ones. I have tried a variety of different file types.

### Are there known steps to reproduce?

1. Drag and drop a file and wait until uploaded.
2. Select and add to list of documents to embed.
3. Click on Save/Embed.

**Comment by calmtortoise** [comment]
Update: I was able to fix the problem by deleting the old workspace and creating a new one. No idea why that worked.

**Comment by calmtortoise** [comment]
Prior to getting the error there were two PDF files embedded.

**Comment by timothycarambat** [comment]
Hm, currently unable to replicate. The deleting/re-creating is a suitable workaround until we can have a know replication of this elusive bug.

**Comment by novadiem** [comment]
Failed to add. LanceDBError: Append with different schema

I had embedded a collection of webpages, and 4 pdf files. On trying to embed another 2 pdf files, I got the above error. Removed all html embeds and tried to embed a single new pdf and still get the following:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/124882695/50745caf-6e58-468c-866f-948a05638228)

**Comment by timothycarambat** [comment]
@novadiem Are you on Docker or Desktop?

**Comment by novadiem** [comment]
Desktop - W11 Pro

**Comment by timothycarambat** [comment]
We have found the issue causing this on the desktop app. It will be patched in the next update which is to be release tomorrow. The error is from the lanceDB provider library and it just needed to be patched to most recent version.

**Comment by timothycarambat** [comment]
@calmtortoise The issue here says Docker, but this issue should not be on Docker - was your original issue on a Docker instance and not the desktop app?
