### ISSUE TITLE
Clarify instructions in Docker readme

### ISSUE THREAD

**Issue by frasergr** [Mintplex-Labs/anything-llm#78]
Update Docker instructions to remove references to yarn as well as add note about UID and GID.

**Comment by digitalw00t** [comment]
There are mutliple mentions of an .env file which I don't see documented, and the command for yarn to build it does not work. I also can't seem to find anything-llm in hub.docker.com.

**Comment by frasergr** [comment]
You don't need yarn for the docker setup. From the docker directory, make a copy of .env.example and name it .env then fill in the variables.

After that is done, you can build the image. The instructions in the docker directory are mostly correct other than the yarn stuff.

**Comment by digitalw00t** [comment]
PINECONE_ENVIRONMENT
Not sure what is suppose to go there.

**Comment by digitalw00t** [comment]
Found it... thanks.

**Comment by timothycarambat** [comment]
resolved by #79

**Comment by jhalbrecht** [comment]
> Found it... thanks.

I'm here for the same question. How did you resolved this?

**Comment by frasergr** [comment]
@jhalbrecht Pinecone environment is found in the Pinecone Console in the Indexes section.

**Comment by jhalbrecht** [comment]
> Pinecone environment is found in the Pinecone Console in the Indexes section.

Thanks @frasergr 
Regarding creating index on pinecone I don't know the answers to `Dimensions` and `Metric`?

And I heard there is a discord server/channel can I get an invite? Should readme.md contain that info?
