### ISSUE TITLE
Windows Docker desktop not responding on port 3001[BUG]: 

### ISSUE THREAD

**Issue by thebaldgeek** [Mintplex-Labs/anything-llm#782]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Pull mintplexlabs/anythingllm:latest from the search bar on docker desktop
Start container.
Unable to connect to either http://localhost:3001 or http://127.0.0.1:3001 on the same PC that docker desktop is running.
Issue exists on Firefox, Chrome and Edge.
Both URLs also timeout when checking /api/docs

Windows firewall is off for all interfaces.
Docker desktop logs suggest that the server is listening.
Unsure what to check or try next.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/7385116/ee81830d-44eb-492b-bf31-fd98372c0b11)

### Are there known steps to reproduce?

Brand new docker desktop install.
No other docker containers running.
Docker desktop install suggested WSL, so that suggestion was accepted during the install.

**Comment by timothycarambat** [comment]
When you started the container did you bind host port 3001 to container port 3001?

Via CLI `docker run -d -p 3001:3001 ....`

In UI when you click on the image and click `start` it should show a modal for `PORT`
<img width="657" alt="Screenshot 2024-02-22 at 2 54 27 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/1de64e46-7a23-4b9b-8a24-12841fff5aaa">

**Comment by thebaldgeek** [comment]
I am not using the CLI, all actions performed via docker desktop app.
Can confirm that the option is set.
Have set the browser to use http links vs always using https.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/7385116/4dcf93a5-c801-48f3-a19f-79dc787b2453)

**Comment by timothycarambat** [comment]
> I am not using the CLI, all actions performed via docker desktop app. Can confirm that the option is set. Have set the browser to use http links vs always using https.
> 
> ![image](https://private-user-images.githubusercontent.com/7385116/307179447-4dcf93a5-c801-48f3-a19f-79dc787b2453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDUxMjMsIm5iZiI6MTcwODY0NDgyMywicGF0aCI6Ii83Mzg1MTE2LzMwNzE3OTQ0Ny00ZGNmOTNhNS1jODAxLTQ4ZjMtYTE5Zi03OWRjNzg3YjI0NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMjMzMzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdiZGNlZGJmZTIyMTFjOTcwMWJiNjM0MDNkMTRjOWQwYjMzNGJmZTcyY2UyNzRiOWNmMDc3NzA4NTVhYWQ5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rVTpd-Z_KLvzwypLdM2j3xG0EHqAa2cQvVj2oMWuVzs)

This screen shot shows that you left that field empty. Put "3001" into that field. The placeholder text is telling you that it will be binding to `:3001` on the container - leaving it empty will make the container unreachable

**Comment by thebaldgeek** [comment]
Thanks for the help on this. Docker is very hard to work with.
I think I need to put an issue in with ollama in order to progress as now that I have Docker desktop going, I can not proceed as ollama only listens to 127.0.0.1 and docker wont / cant connect to that.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/7385116/6e91f86c-551f-4cf5-b04e-d2e49622e7cb)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/7385116/f92d0e29-a9e6-4e00-b982-c201bfda7bc0)

Your project looks to be exactly what I am after, the multi workspace, teams aspect and smooth training (document UI handling aside) is spot on. Just getting it running in Docker is a bit tricky vs the Windows Desktop.
