### ISSUE TITLE
[DOCS]: AnythingLLM bare metal

### ISSUE THREAD

**Issue by moferreira** [Mintplex-Labs/anything-llm#783]
### Description

I am trying to follow the instructions and install AnythingLLM on a bare metal server. I have followed the instructions on the "Run AnythingLLM in production without Docker". However, when I git the project the directory does not have any setup file that I can run yarn to set the system up. Am I missing something or the bare metal installation is broken?

**Comment by timothycarambat** [comment]
in the root you should just need to run `yarn setup` - that will install everything and create the example ENV files

**Comment by moferreira** [comment]
Ok, I have tried your direction. I did:
mo@mo-KVM:~/anything-llm/server$ ls
endpoints  jsconfig.json  nodemon.json  prisma   swagger  yarn.lock index.js   models         package.json  storage  utils
mo@mo-KVM:~/anything-llm/server$ yarn 
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

I got Yarn installed by doing:
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt install yarn -y

What am I missing? My guess is that my Yarn is not the one the project is expecting to have.
m

**Comment by moferreira** [comment]
When we git the project, the anything-llm directory does not have a file so called "setup".

**Comment by timothycarambat** [comment]
`yarn` by itself installs all packages in the relative `package.json` for the folder you are in. If `yarn` by itself is not working then the command `yarn install` does the same thing.

`setup` is not a file it a script in the root `package.json` - as I linked above. So you would run that by being in the root and running `yarn setup` or `yarn run setup`.

**Comment by erik-sv** [comment]
@moferreira Here is what I did after installing Yarn on Ubuntu [(seen here, similar to what you did)](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365):

`sudo npm install -g n` to install NPM (node package manager)
`sudo n 18.12.1` (Installs node version 18.12.1, works here as of this post)

Make sure you are in the anything-llm folder then run 
`yarn setup`

Hopefully should work for you as well.
