### ISSUE TITLE
RAG With images

### ISSUE THREAD

**Issue by shanvinod4u** [Mintplex-Labs/anything-llm#785]
### What would you like to see?

Would be good to have RAG with images, workspace chat right now has only text, its good to have images and texts from documents

**Comment by timothycarambat** [comment]
Tracking on https://github.com/Mintplex-Labs/anything-llm/issues/558

**Comment by timwu-ipevo** [comment]
I suppose individuals may interpret "RAG with images" in various ways. One interpretation is that LLM can reference the image from the document in its response. Another interpretation is that LLM can consider both the image and text as prompts and attempt to comprehend the image.

**Comment by dberardo-com** [comment]
Why has this issue been closed?

AFAIK it is not possible yet to ask questions related to images when using RAG.

In my use case I would like to upload a bunch of pdf texts explaining common consumer electrical energy pattern in households and then some pdf with plots that give some statistical information on these consumption patterns.

During inference I would like to upload a pdf report with mainly plots and ask the ai if there is any anomaly
