### ISSUE TITLE
[FEAT]: Ollama Embedding Support

### ISSUE THREAD

**Issue by mortenfj** [Mintplex-Labs/anything-llm#788]
### What would you like to see?

Embeddings using the new version of ollama, they should be lightning fast and would save a lot of time when processing very large files. It's very new to Ollama version 0.1.26. Just wanna put it your guys radar. thank you for all you do.

**Comment by CharlesBdg** [comment]
+1 
nomic-embed-text seems really good with ollama
https://ollama.com/library/nomic-embed-text

**Comment by timothycarambat** [comment]
This is a good tip just to know in general. We don't have the capacity (or want) to force Ollama to be installed for the user, but happy to now add them as an embedding provider as well alongside the others we have

**Comment by timothycarambat** [comment]
TASK:

Ollama now supports embeddings for several embed models. Many Ollama users would like to have Ollama be both their LLM and embedder. We should add Ollama Embeddings as a provider for the user to run embeddings against.
