### ISSUE TITLE
[FEAT]: Appearance Setting UI Updates

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#790]
### What would you like to see?

<img width="1512" alt="Admin Settings - Multi User" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/c45e3070-b73b-4c14-a483-bccd2a71bae6">

**Comment by PLK2** [comment]
- dark/light mode
- change fonts

**Comment by Superkikim** [comment]
[FEAT] Text zooming or font size selection

Right now, I couldn't figure out how to increase font size on my 4k screen on Manjaro (with XFCE). Incresing QT ratio did not do the trick.

**Comment by timothycarambat** [comment]
@Superkikim please request that on another feature request, it will not be triaged if you leave it as a comment
