### ISSUE TITLE
[FEAT]: iWork documents support (Pages / Keynote / Numbers)

### ISSUE THREAD

**Issue by originalmagneto** [Mintplex-Labs/anything-llm#794]
### What would you like to see?

I (and a lot of people) don’t use Microsoft products for productivity and it would be great if the system could scrape and process .pages .keynote and Numbers files.

**Comment by timothycarambat** [comment]
With the exception of .keynote (which would need to be exported as PPT), AnythingLLM can accept both .pages and numbers files, both of which will be converted to text
