### ISSUE TITLE
Dockerfile cleanup and enforce Unix line endings

### ISSUE THREAD

**Issue by frasergr** [Mintplex-Labs/anything-llm#80]
The docker entrypoint and cmd scripts are a bit redundant. The CMD dual_boot.sh script should just move to the entrypoint script and we remove the CMD altogether.

We should also enforce Unix line endings via .gitattributes as some Windows users have had problems when building the image related to line endings mismatch.

**Comment by timothycarambat** [comment]
resolved by #81
