### ISSUE TITLE
[FEAT]: Self-Hosted Gitlab Data Connector

### ISSUE THREAD

**Issue by mark3apps** [Mintplex-Labs/anything-llm#812]
### What would you like to see?

Since the GitHub connector is already set up, it'd be super helpful to have a connector that could connect to a self-hosted Gitlab Server.  Then we could really keep all of our media and code offline automatically.

**Comment by mark3apps** [comment]
Hey, I was wondering if any progress was made on this or if this is something you guys are looking into.  It would be amazingly helpful to have this functionality.

**Comment by martindellavecchia** [comment]
Hey data connector aren-t working for me on my self hosted ubuntu install, any tip or any log to look at?. I am clueless

**Comment by timothycarambat** [comment]
Closed by https://github.com/Mintplex-Labs/anything-llm/pull/1932
