### ISSUE TITLE
[FEAT]: Renaming source documents

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#816]
### What would you like to see?

At times, the source document name being shown can be incorrect, ambiguous, or otherwise not great. You should be able to click on such a document and select "rename". This only changes the property in the `documents/` folder, but will help greatly in organization.

**Comment by atljoseph** [comment]
First off… Awesome product with lots of potential. 

It is crucial for the people curating documents to be able to accurately identify and correlate between documents they are curating locally vs documents that have been already uploaded to the system. Random file names === context switch. Context switch === human performance loss. Human performance loss === lower quality source documents. Lower quantity source docs === not as good of a product. Please make it easier for document curators to do their magic. In a system containing hundreds of documents, this really becomes a no-brainer. 

Also, if it is not possible yet to replace document embedding in the vector store (other issue), then this feature request becomes even more important. 
- How can someone recognize a doc they uploaded if you change the name?
- If you let them change the name, at least they’d be able to version it. 

Lastly, am curious. Does your locally running API have an endpoint to post document(s) with a customized name?

**Comment by atljoseph** [comment]
Also, I’ve noticed that the docs on the right side (which are indexed) do not seem retain any link to the origin folder. So, it might be difficult to tell one file from another if they have the same or similar name. I know it’s one of those things where whatever decision you make won’t end with everyone being happy, but maybe just the original filter they came from? 

One last tweak here, maybe? If entering a GitHub url, maybe the folder name should start with github-, then repo name and branch name.
