### ISSUE TITLE
[FEAT]: scroll should not be locked to bottom while inference

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#823]
### What would you like to see?

The UI does not allow scrolling up while the output is being streamed.
Yes, the UI should keep you to the bottom but it should allow scrolling up and checking the chat instead of waiting for the output to complete. Maybe at the starting only of the output it should do that or when the user is already at the bottom it may do for just a start.
P.S.: Also please remove the scroll bar it is not useful anyways and looks bad in windows.

**Comment by ajmurmann** [comment]
What release includes this change? For me it still autoscrolls back to the bottom when the LLM is streaming on 1.6.2 on macOS.
