### ISSUE TITLE
[BUG]: Output hidden if switched to another workspace/ screen.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#824]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When a question is asked and you switch to any other workspace or setting and come back to the same workspace, the steaming gets hidden and is not continuing or not shown if completed. The user has to refresh the screen to view the results.

**Comment by timothycarambat** [comment]
Do not leave the workspace while the response is streaming? We cannot keep that connection open when their is no listener
