### ISSUE TITLE
[BUG]: Citations are wrong.

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#826]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The results given are correct but the citations given are completely wrong and unrealated.

**Comment by timothycarambat** [comment]
Not a bug, this is just how vector databases work. They do semantic similarity which is not logic based, but instead math based (cosine similarity)

Some ways to improve citation results:
- Use a larger dimension embedder model (OpenAI)
- Increase the threshold for workspace (Settings > Vector Database)
- Manually partition documents (aka make smaller documents for uploads) for more logical splitting as ANythingLLM will just take chunks of ~1000 chars
- Use document pinning for critical documents so they are always in context

We are working on better retrieval methods beyond naive RAG
