### ISSUE TITLE
[BUG]: Error while uploading multiple documents

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#827]
### How are you running AnythingLLM?

Docker (local)

### What happened?

If you choose many documents to be uploaded. Some of the documents are not uploaded and show error. The files are being uploaded simultaneously and not one by one.
![Screenshot 2024-02-27 220537](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/e16ea0df-1c34-46d2-8cd8-9d35d03a127c)

**Comment by timothycarambat** [comment]
Are you able to upload the error'd document independently after it fails?
