### ISSUE TITLE
[BUG]: Workspace deletion

### ISSUE THREAD

**Issue by delbertaud** [Mintplex-Labs/anything-llm#829]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When you delete a workspace and then recreate a new one with the same name previous data is brought back. I would suspect the desired effect of a deletion would be the loss of said information.

**Comment by timothycarambat** [comment]
Closing as stale, additionally unable to replicate but will keep a tab on internal issue board so we can link to this issue should it come through again.
