### ISSUE TITLE
[BUG]: ERROR message recived white move file to workspace.

### ISSUE THREAD

**Issue by MinagiCN** [Mintplex-Labs/anything-llm#836]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/152168137/eb9e50ff-7f9a-439a-bdc3-335b656d87e1)
when i move file to workspace ,it pop up failture everytime,it says "Error:1 documents failed to add fetch failed"
, no matter i upload a txt file or a docx file. it happens everytime, how to sovle this? or there are specifications for file format?
(windows11 desktop app) 
i tried create new workspace but no use.same error.
my LLM preference is LMStudio,Embedding Preference is AnythingLLM Embedder

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1968217337

Your IP is likely blocked by hugging face due to sanctions, VPN, or something else and you cannot download the native embedder model. The above comment shows how to fix that.

**Comment by MinagiCN** [comment]
> [#821 (comment)](https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1968217337)
> 
> Your IP is likely blocked by hugging face due to sanctions, VPN, or something else and you cannot download the native embedder model. The above comment shows how to fix that.

thank you problem solved!

**Comment by zasl** [comment]
> > [#821 (comment)](https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1968217337)
> > Your IP is likely blocked by hugging face due to sanctions, VPN, or something else and you cannot download the native embedder model. The above comment shows how to fix that.
> 
> thank you problem solved!

Could you please tell me how you solved the problem, as I am also using a Windows 11 system and downloaded all the files from that website link into AppData\Roaming\anythingllm-desktop\storage\models\Xenova\all-MiniLM-L6--v2 directory but failed to make it work even after restarting.

**Comment by timothycarambat** [comment]
Make sure all of the files are readable by the system. Sometimes they can be downloaded but unable to be read/executed and that makes them broken as well
