### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: './outputs/website-logs'

### ISSUE THREAD

**Issue by aHardReset** [Mintplex-Labs/anything-llm#84]
Running the project with Docker on Windows

Running docker commands in WSL2 Ubuntu:
```
docker-compose up -d --build
sudo docker exec -it --workdir=/app/collector anything-llm python main.py
```

When using collector main.py with 
`Article or Blog Link(s) > URL Crawler`

I got:

`PermissionError: [Errno 13] Permission denied: './outputs/website-logs'`

I tried to do 

`echo "$(id -u):$(id -g)"`

in the Ubuntu terminal, and it reports 1000:1000

From the Readme:

## About UID and GID in the ENV
- The UID and GID are set to 1000 by default. This is the default user in the Docker container and on most host operating systems. If there is a mismatch between your host user UID and GID and what is set in the `.env` file, you may experience permission issues.

But they are matching.

**Comment by jlevy-io** [comment]
Same issue for me.  Fixed by running `chmod -R 777 outputs` in the /collector folder.   Not sure if this is best practice but it worked 🤷
