### ISSUE TITLE
[BUG]: Bad Mime-type mapping for TS files

### ISSUE THREAD

**Issue by PiotrSkon** [Mintplex-Labs/anything-llm#841]
### What would you like to see?

Was hoping to do a bit of research on LLM's and RAG and all that against my code (Angular, TypeScript, HTML, CSS).
Dragged in my source files and it failed to parse .ts files :/ A real bummer. HTML went through but, that's useless without the component code.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/592773/5d397cf2-9613-42de-9e39-08d0feede5a3)

**Comment by timothycarambat** [comment]
The reason for this is really a bug. The Mime library maps this extension to `video/mp2t` because `.ts` has been a file extension long before typescript. Nobody is using that file for this so we should override this and others

https://en.wikipedia.org/wiki/MPEG_transport_stream
