### ISSUE TITLE
[BUG]: 1 document failed to added: fetch failed

### ISSUE THREAD

**Issue by ivy-lv11** [Mintplex-Labs/anything-llm#848]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

When I run the anythingllm docker on Linux, I run into "1 document failed to added: fetch failed" error after clicking "save and embed". Could you please help me check the cause of the problem? Thanks!

**Comment by timothycarambat** [comment]
Your IP, VPN, or something else is being blocked by Hugging face and cannot download the native embedding model
see this issue for resolution!
https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1968217337

**Comment by wangwangzuge** [comment]
> Your IP, VPN, or something else is being blocked by Hugging face and cannot download the native embedding model see this issue for resolution! [#821 (comment)](https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1968217337)

I'm using VPN. I can access Hugging Face through the browser normally, and I can download model files as well. However, when using AnythingLLM, it reports this exception.

**Comment by timothycarambat** [comment]
Yes, this is expected because the client used but the Xenova/transformers library is different and under this combination it is being blocked. There are specific headers set to download the model to be compliant with their CDN to be able to download the file via fetch/curl
