### ISSUE TITLE
[BUG]: Modal workspace window needs a scrollbar to show all users.

### ISSUE THREAD

**Issue by sheneman** [Mintplex-Labs/anything-llm#851]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When trying to add users to a workspace, if there are too many users  you cannot see them all on the screen and there is no scrollbar in the modal user select window.    I cannot navigate to all of the users within the modal dialog or click "okay".  The list of users extends beyond the bottom of the screen.

<img width="1445" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/3028345/a64331a9-5555-4895-91aa-0213b57796ea">

### Are there known steps to reproduce?

Once you have 20 or more users, this starts to become a problem.  It is reproducible every time.

Relatedly, I am not sure how to tell from the web interface which version/release of AnythingLLM I am running

**Comment by timothycarambat** [comment]
😓 Well, this is clearly an issue. Wil have design take a crack at this soon as when you have this many users the UI is basically unuseable for its purpose.

**Comment by timothycarambat** [comment]
@shatfield4 Lets at least get the page scrollable and we can get the page useable and then get designs to re-work this totally
