### ISSUE TITLE
Notebook Tab/ mode and RAG on / off switch

### ISSUE THREAD

**Issue by LJtrix** [Mintplex-Labs/anything-llm#852]
### What would you like to see?

(Doesn’t have to be, Again, just an idea that could be super cool)
Notebook mode: a tab where you can write notes, or Stories, etc, and then use either text completion, or simple command that enables instruct mode(to make the LLM write something specific in the notebook), and then the option to send it to the documents or save as text file (which can then be added to the RAG)

inspired by an oobabooga text gen extension:
Specifically the notebook and ‘quick instruct’ feature:
https://github.com/FartyPants/Playground?tab=readme-ov-file

And then on top of that: to add an option to turn RAG on or Off, so that you can ask an LLM normally without relying on added context optionally.

Just a rough example I can imagine in “notebook mode”:
‘[RAG mode: off]
(Written by user:)
Character A: 32, male, brown hair, blue eyes, powers:  teleportation, has a great friendship with character B, (etc.

character B: (more notes)

They are a (….)[(generate text completion; LLM)]
….
(Written by user ⬇️)
(instruct) (example command): $$write me a summary of character A and B

Summary: …(created by LLM)
…

[RAG mode: ON](e.g: a pinned a document|
 about some summary of a story/ concept)

(Written by user ⬇️)
$$how can I add the concept of (from pinned document) and connect it with Character A’s powers and Character B’s… etc.

…
‘
———————

just ideas, but it would most definitely be a super Overpowered, useful and awesome feature. 
(If you decide to add this, you can obviously customize anything you’d like doesn’t have to be $$ for instruct, etc.)

I feel like this feature would be great as without it, I’d have to have 3 applications running and it would get messy and use up more power, etc.
Anyway, AnythingLLM is great project and love it a lot, and is my favorite overall application.

**Comment by timothycarambat** [comment]
Dang, i really like the idea behind what you are getting at there. I see the overall point but im having trouble seeing how we can fit it into the app. I wonder if there is some opt-in mode or control we can surface to the frontend if desired to fullfill that kind of concept. Cool idea!
