### ISSUE TITLE
[FEAT]: running under wine

### ISSUE THREAD

**Issue by a00110110011** [Mintplex-Labs/anything-llm#855]
### What would you like to see?

is it possible to run the windows version with wine on linux? if not whats the timeline for deployment? months? years?

**Comment by shatfield4** [comment]
This is not on our radar to support this but feel free to try running it with wine. We don't have a timeline to support wine but we would like to support Linux natively.

**Comment by timothycarambat** [comment]
We will for sure not support WINE as that is only likely to lead to infinite compatibility errors that are not worth debugging. We will be providing a native Linux AppImage that can be run. AppImage should be done within the month. In the meantime, the Docker image is Linux compatible and can be spun up easily in lieu of the AppImage currently.
