### ISSUE TITLE
[BUG]: too slow of the collector to transfrom the docx file to data

### ISSUE THREAD

**Issue by sddzcuigc** [Mintplex-Labs/anything-llm#858]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I use the local anythingLLM and ollama , I use very small chinese docx into the database,but it takes too long
and when it is done.  I don't know how to ask due to the data I upload. When I ask any question It shows ollama failed to embed undefined: undefined.

**Comment by wallartup** [comment]
@timothycarambat are you working in moving the local embeddings to GPU? That would make things much much faster.

**Comment by sddzcuigc** [comment]
yes，using gpu is faster,and makes less error. I use the ollama as the local engine,
when I ask questions, if the questions I force to stop the AI answer streaming,cpu/gpu will not be free for a very long time, that means when I stop the question, the backgroud thread will not force to stop, and the question will not record.
________________________________
发件人: wallartup ***@***.***>
发送时间: 2024年3月7日 3:14
收件人: Mintplex-Labs/anything-llm ***@***.***>
抄送: Yang xiaoyu ***@***.***>; Author ***@***.***>
主题: Re: [Mintplex-Labs/anything-llm] [BUG]: too slow of the collector to transfrom the docx file to data (Issue #858)


@timothycarambat<https://github.com/timothycarambat> are you working in moving the local embeddings to GPU? That would make things much much faster.

―

**Comment by airylinus** [comment]
I got the same problem,   and solve it by reducing chunk size setting to 2048 ( from 8196) in anythingLLM's admin pannel.
 Maybe you can have I try.  BTW, I think it may helps also to splitting large text/ pdf file to smaller pieces.

**Comment by timothycarambat** [comment]
This seems more like a setup/config issue on the Ollama side where putting the placeholder value (which is arbitrary) too high for the model provided, which is also memory dependent in addition to model-constrained.

Glad there was a path around. AnythingLLM will only work with the settings given since there is no way to "ask" a model how big its context window is
