### ISSUE TITLE
[BUG]: User role default can't view any of workspace which was created by admin.

### ISSUE THREAD

**Issue by cebernic** [Mintplex-Labs/anything-llm#860]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Role Manager works fine.

### Are there known steps to reproduce?

Reproduced and directly.

**Comment by timothycarambat** [comment]
Not a bug. The default role can only view workspaces it is explicitly added to.

**Comment by Lurtroxx** [comment]
Okay so how do you add the default user to a workspace...

**Comment by timothycarambat** [comment]
They were invited to the system, to add them to a workspace in the admin settings to to workspaces, then click on the 3 dots on the workspace you want to add them to.

This is actually being worked on right now as the UI/UX is not intuitive.

**Comment by Lurtroxx** [comment]
Ahh I realize now that these invites are for a designated person to make an account, there is no feature for a link that can be given to people to register an account and use the system. My apologies.

**Comment by timothycarambat** [comment]
I see no reason why invite links should not auto-add to defined or pre-set workspaces. I like that idea, ill add as feature request!

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/972
