### ISSUE TITLE
[FEAT]: Linux Support

### ISSUE THREAD

**Issue by ennob** [Mintplex-Labs/anything-llm#862]
### What would you like to see?

The useanything.com website says that Linux support is coming soon. Is there any release schedule available or maybe just a preliminary launch date? If there is a specific list of problems that has to be solved for this to happen, I would be happy to contribute if someone can point those problems out.

**Comment by timothycarambat** [comment]
Live https://useanything.com/download

Download: https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop.AppImage

Tested on Ubuntu 22 LTS.

Docs: https://docs.useanything.com/anythingllm-desktop/linux-instructions
