### ISSUE TITLE
[BUG]: Desktop "Document Processor Unavailable" on launch

### ISSUE THREAD

**Issue by ub1979** [Mintplex-Labs/anything-llm#866]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

<img width="600" alt="Screenshot 2024-03-06 at 02 43 01" src="https://github.com/Mintplex-Labs/anything-llm/assets/34165536/06168630-ab21-4f46-aa28-a20aacfd21a4">

**Comment by luoluoter** [comment]
got the same problem with you;
i reinstalled the latest dmg from official website and still not working.

**Comment by StephenHnilica** [comment]
If you uploaded an audio / video file, what's happening is that it's transcribing the file & that takes a while. On my PC it takes ~1m for every 1m of audio.

For some reason it pauses the queuing function while it's working. When the transcription is finished, the document processor will come back online.

You can read my documentation of the issue here: https://github.com/Mintplex-Labs/anything-llm/issues/849

**Comment by ub1979** [comment]
no its not letting to upload any file from start, like I made the workflow and when I press upload file I got this msg.

**Comment by timothycarambat** [comment]
@ub1979 
What OS are you on for mac?
What chip are you running (intel/M-series)
Can you open the `Terminal` application and run this - make sure the currently running app is fully quit:
`/Applications/AnythingLLM.app/Contents/MacOS/AnythingLLM ` (then press enter)

It will start the app like usual but all logs will be dumped to terminal. Can you paste that output into here? We have seen this issue on Windows but never on Mac and it will be easier to debug this way.

If you can do this we can fully squash this issue as others have not been able to provide us these logs and we _cannot_ replicate it on any machine we get our hands on.

**Comment by PieroPicc** [comment]
Hi @timothycarambat I'm having the same issue on M1 Mac, here are the logs:

Seems like a permission issue and a missing Prisma module. Are there any additional steps after installation I might've missed?

`Already in sync, no schema change or pending migration was found.

EPERM: operation not permitted, open '/Applications/AnythingLLM.app/Contents/Res
ources/backend/node_modules/.prisma/client/index.js'


Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
EPERM: operation not permitted, open '/Applications/AnythingLLM.app/Contents/Resources/backend/node_modules/.prisma/client/index.js'


node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module '.prisma/client/index'
Require stack:
- /Applications/AnythingLLM.app/Contents/Resources/backend/node_modules/@prisma/client/index.js
- /Applications/AnythingLLM.app/Contents/Resources/backend/server.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/utility_init:2:3040)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Applications/AnythingLLM.app/Contents/Resources/backend/node_modules/@prisma/client/index.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/AnythingLLM.app/Contents/Resources/backend/node_modules/@prisma/client/index.js',
    '/Applications/AnythingLLM.app/Contents/Resources/backend/server.js',
    undefined
  ]
}

Node.js v18.16.1
Collector hot directory and tmp storage wiped!
[production] AnythingLLM Standalone Document processor listening on port 59647
`

**Comment by PieroPicc** [comment]
Solved it, the problem is due to System Integrity Protection (SIP) on macOS. To solve you just need to install it inside the Applications folder of the current user and not in the root application folder.

Hope it helps!

**Comment by timothycarambat** [comment]
@PieroPicc **THANK YOU**. This is almost certainly the case as well for multi-user Windows systems that are encountering this issue. The app should only be installed as the current user as the global `/Applications` will fail due to perms.

Ping me in Discord if you want a contributor badge, this headache is worthy of one. In the meantime I will see if there is a way to prevent that kind of install error from occuring.

**Comment by luoluoter** [comment]
`Terminal` run `/Applications/AnythingLLM.app/Contents/MacOS/AnythingLLM` is working, for me;

don't know how to 'install it inside the Applications folder of the current user and not in **_the root application folder_**.',

i only can see ONE application folder, and open in folder or Dock is not working.

**Comment by timothycarambat** [comment]
@luoluoter In Finder click in Go -> "Go to Folder" -> `~/Applications` and drag the app from the root application folder and into that one. The dock shows both I believe.

**Comment by timothycarambat** [comment]
Also related #875 if this does not solve your issue

**Comment by dmatora** [comment]
Same issue on MacOS.
Working fine on Intel MacBook, but getting Document Processor Unavailable on M1

Here is M1 log

Applications/AnythingLLM.app/Contents/MacOS/AnythingLLM 
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/Users/Melanj/Library/Application Support/anythingllm-desktop/storage/anythingllm.db"

Already in sync, no schema change or pending migration was found.

✔️ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 86ms


Prisma schema loaded from prisma/schema.prisma

✔️ Generated Prisma Client (v5.3.1) to ./node_modules/@prisma/client in 89ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

[OllamaProcessManager] Ollama will bind on port 11434 when booted.
[TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
Collector hot directory and tmp storage wiped!
[production] AnythingLLM Standalone Document processor listening on port 8888
prisma:info Starting a sqlite pool with 17 connections.
[TELEMETRY SENT] {
  event: 'server_boot',
  distinctId: '...',
  properties: { runtime: 'desktop' }
}
Skipping preloading of AnythingLLMOllama - LLM_PROVIDER is lmstudio.
[production] AnythingLLM Standalone Backend listening on port 3001

**Comment by timothycarambat** [comment]
Its been pointed out before that moving the App from /Applications to /User/Applications will solve this. This may be the issue

**Comment by dmatora** [comment]
@timothycarambat just tried that, but it did not not help

**Comment by moltar** [comment]
same prob on the hosted trial

**Comment by dirtstudio** [comment]
I'm having the same issue and have found that turning my VPN off fixes the issue. Turning it back on causes the issue again with immediate effect

**Comment by timothycarambat** [comment]
@dirtstudio That is bizzare. The collector is fully local, why would the VPN stop that processing from booting? Are you able to view the collector logs? https://docs.anythingllm.com/installation-desktop/storage

**Comment by dirtstudio** [comment]
Hey @timothycarambat 
Here's what's there. It's a fairly fresh install as I've been trying to fix this issue by wiping the deck clean.
Thanks in advance for taking a look

OS: MacOS 26.1 
Processor: M1 Max
Mem: 64GB RAM
AnythingLLM Desktop: Version 1.9.1 (1.9.1)


> {"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"-- Working AAA AAA CV 2022.pdf --","service":"collector"}
{"level":"info","message":"Warning: Could not find a preferred cmap table.","service":"collector"}
{"level":"info","message":"Warning: Could not find a preferred cmap table.","service":"collector"}
{"level":"info","message":"Warning: Could not find a preferred cmap table.","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 1 --","service":"collector"}
{"level":"info","message":"[SUCCESS]: AAA AAA CV 2022.pdf converted & ready for embedding.\n","service":"collector"}
{"level":"info","message":"-- Working AAA_AAA_CV_2024.pdf --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 1 --","service":"collector"}
{"level":"info","message":"[SUCCESS]: AAA_AAA_CV_2024.pdf converted & ready for embedding.\n","service":"collector"}
{"level":"info","message":"-- Working 2024_AAA_AAA_Portfolio_CV.pdf --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 1 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 2 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 3 --","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Input will take too long to encode - estimating","service":"collector"}
{"level":"info","message":"[SUCCESS]: 2024_AAA_AAA_Portfolio_CV.pdf converted & ready for embedding.\n","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Initialized new TikTokenTokenizer instance.","service":"collector"}
{"level":"info","message":"Collector hot directory and tmp storage wiped!","service":"collector"}
{"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}
{"level":"info","message":"-- Working AAAtie-AAAAAA-Draft-7-v22.pdf --","service":"collector"}
{"level":"info","message":"Warning: TT: undefined function: 32","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 1 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 2 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 3 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 4 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 5 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 6 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 7 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 8 --","service":"collector"}
{"level":"info","message":"-- Parsing content from pg 9 --","service":"collector"}
{"level":"info","message":"\u001b[35m[TikTokenTokenizer]\u001b[0m Input will take too long to encode - estimating","service":"collector"}
{"level":"info","message":"[SUCCESS]: AAAtie-AAAAAA-Draft-7-v22.pdf converted & ready for embedding.\n","service":"collector"}

**Comment by timothycarambat** [comment]
@dirtstudio 
> {"level":"info","message":"[production] AnythingLLM Standalone Document processor listening on port 8888.","service":"collector"}

We run the collector on port 8888, which _can_ sometimes be used for web-proxies and especially VPN activities. With the VPN running and AnythingLLM _closed_ can you see what the result of `sudo lsof -i :8888`

We do port-hunt to ensure we dont try to use an occupied port but that may not be being detected or something

```
# With AnythingLLM running - as an example
tim@mac.lan /Users/tim  sudo lsof -i :8888
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
AnythingL 94165  tim   29u  IPv4 0x3c558701fe189387      0t0  TCP localhost:ddi-tcp-1 (LISTEN)
```

**Comment by dirtstudio** [comment]
@timothycarambat 
With VPN on and AnythingLLM closed, looks like nada
> user@user ~ % sudo lsof -i :8888
Password:
user@user ~ % sudo lsof -i :8888
user@user ~ %

**Comment by timothycarambat** [comment]
Hm, then I am really out of ideas on why this would be the case TBH. I guess just going to file that under "things that might come up randomly" haha

**Comment by dirtstudio** [comment]
@timothycarambat I'm just glad I got it working! Thanks for your help and for the app, I love it

**Comment by ColoursofOSINT** [comment]
Can confirm that on MacOS VPN breaks it, turning it off it starts working again. Firewall (Little Snitch) seems to have no impact. 

I was wondering why it was working then failed but I was turning on VPN and didn't think this could be the issue, until I saw the solution.  Seems like it is a fetch failed error. I will see if I can get more details.

Could you guys add timestamps to your logs? Would make troubleshooting much easier.

**Comment by ColoursofOSINT** [comment]
[backend] info: [LMStudio] No context windows cached - Context window may be inaccurately reported.
[backend] info: [LMStudio] No context windows cached - Context window may be inaccurately reported.
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
[collector] info: Found 21 files from Obsidian Vault obsidian to process
[backend] info: [TELEMETRY SENT] {"event":"extension_invoked","distinctId":"016460fd-0ab5-412f-aa8b-5e1fe5c836bf","properties":{"type":"obsidian_vault"}}
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
[backend] info: [CollectorApi] fetch failed
[backend] info: [TELEMETRY SENT] {"event":"extension_invoked","distinctId":"016460fd-0ab5-412f-aa8b-5e1fe5c836bf","properties":{"type":"obsidian_vault"}}
prisma:info Starting a sqlite pool with 17 connections.
[backend] warn: Child process exited with code 0 and signal null
[backend] info: Worker for job "cleanup-orphan-documents" exited with code 0


You can see the first works without VPN, then I turned it on and instant failure.

**Comment by ColoursofOSINT** [comment]
I used wireshark but couldnt see any network failures, and I don't know why this might be happening. Going to debug with node.

**Comment by ColoursofOSINT** [comment]
Found the issue, looks like 0.0.0.0 gets killed by the VPN, whereas 127.0.0.1 loopback is fine which explains why the lmstudio still works. 
```

HTTP 74538: SERVER socketOnParserExecute 660
STREAM 74538: endReadableNT
STREAM 74538: readableAddChunk {
  message: '\x1B[36m[EncryptionManager]\x1B[0m Loaded existing key & salt for encrypting arbitrary data.',
  level: 'info',
  service: 'backend',
  [Symbol(level)]: 'info',
  [Symbol(message)]: '{"level":"info","message":"\\u001b[36m[EncryptionManager]\\u001b[0m Loaded existing key & salt for encrypting arbitrary data.","service":"backend"}'
}
STREAM 74538: ondata
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
STREAM 74538: maybeReadMore read 0
STREAM 74538: read 0
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: do read
NET 74538: createConnection [
  {
    highWaterMark: 65536,
    path: undefined,
    localAddress: null,
    port: '8888',
    host: '0.0.0.0'
  },
  null,
  [Symbol(normalizedArgs)]: true
]
NET 74538: pipe false undefined
NET 74538: connect: attempting to connect to 0.0.0.0:8888 (addressType: 4)
NET 74538: afterConnect
STREAM 74538: read 0
STREAM 74538: need readable false
STREAM 74538: length less than watermark true
STREAM 74538: do read
NET 74538: _read - n 65536 isConnecting? false hasHandle? true
NET 74538: Socket._handle.readStart
NET 74539: onconnection
STREAM 74539: read 0
STREAM 74539: need readable false
STREAM 74539: length less than watermark true
STREAM 74539: do read
NET 74539: _read - n 16384 isConnecting? false hasHandle? true
NET 74539: Socket._handle.readStart
HTTP 74539: SERVER new http connection
STREAM 74539: resume
STREAM 74539: resume true
STREAM 74539: flow
STREAM 74539: read undefined
STREAM 74539: need readable true
STREAM 74539: length less than watermark true
STREAM 74539: reading, ended or constructing false
STREAM 74538: on readable
STREAM 74539: resume
STREAM 74539: push < [censored] ... 9 more bytes>
STREAM 74539: resume false
STREAM 74539: read 0
STREAM 74539: need readable false
STREAM 74539: length less than watermark true
STREAM 74539: do read
STREAM 74539: flow
STREAM 74539: read undefined
STREAM 74539: need readable true
STREAM 74539: length less than watermark true
STREAM 74539: reading, ended or constructing false
STREAM 74539: read undefined
STREAM 74539: need readable true
STREAM 74539: length less than watermark true
STREAM 74539: reading, ended or constructing false
STREAM 74539: push null
STREAM 74539: onEofChunk
STREAM 74539: emitReadable_
STREAM 74539: flow
STREAM 74539: read undefined
STREAM 74539: endReadable
HTTP 74539: SERVER socketOnParserExecute 1188
STREAM 74539: endReadableNT
STREAM 74539: readableAddChunk {
  message: 'Found 21 files from Obsidian Vault obsidian to process',
  level: 'info',
  service: 'collector',
  [Symbol(level)]: 'info',
  [Symbol(message)]: '{"level":"info","message":"Found 21 files from Obsidian Vault obsidian to process","service":"collector"}'
}
STREAM 74539: ondata
[collector] info: Found 21 files from Obsidian Vault obsidian to process
STREAM 74539: dest.write true
STREAM 74539: ondata
STREAM 74539: dest.write true
HTTP 74539: write ret = true
HTTP 74539: outgoing message end.
STREAM 74539: maybeReadMore read 0
STREAM 74539: read 0
STREAM 74539: need readable true
STREAM 74539: length less than watermark true
STREAM 74539: do read
STREAM 74538: push <[censored]2584 more bytes>
STREAM 74538: emitReadable
STREAM 74538: emitReadable false
STREAM 74538: emitReadable_
STREAM 74538: read undefined
STREAM 74538: need readable false
STREAM 74538: length less than watermark true
STREAM 74538: do read
NET 74538: _read - n 65536 isConnecting? false hasHandle? true
STREAM 74538: push <[censored]2332 more bytes>
STREAM 74538: push null
STREAM 74538: onEofChunk
STREAM 74538: emitReadable
STREAM 74538: emitReadable false
STREAM 74538: read undefined
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: reading, ended or constructing false
STREAM 74538: flow
STREAM 74538: emitReadable_
STREAM 74538: flow
STREAM 74538: on readable
STREAM 74538: emitReadable
STREAM 74538: emitReadable false
STREAM 74538: read undefined
STREAM 74538: need readable false
STREAM 74538: length less than watermark true
STREAM 74538: reading, ended or constructing false
STREAM 74538: endReadable
STREAM 74538: read undefined
STREAM 74538: endReadable
STREAM 74538: emitReadable_
STREAM 74538: flow
STREAM 74538: endReadableNT
STREAM 74538: endReadableNT
HTTP 74538: write ret = true
HTTP 74538: outgoing message end.
NET 74538: destroy
NET 74538: close
NET 74538: close handle
NET 74538: emit close
STREAM 74539: push null
STREAM 74539: onEofChunk
STREAM 74539: emitReadable_
STREAM 74539: flow
STREAM 74539: read undefined
STREAM 74539: endReadable
STREAM 74539: read 0
STREAM 74539: endReadable
STREAM 74539: endReadableNT
NET 74539: _final: not ended, call shutdown()
STREAM 74539: endReadableNT
NET 74539: afterShutdown destroyed=false
NET 74539: destroy
NET 74539: close
NET 74539: close handle
NET 74539: has server
NET 74539: SERVER _emitCloseIfDrained
NET 74539: SERVER handle? true   connections? 0
NET 74539: emit close
HTTP 74539: server socket close
NET 74538: _onTimeout
NET 74538: destroy
NET 74538: close
NET 74538: close handle
NET 74538: has server
NET 74538: SERVER _emitCloseIfDrained
NET 74538: SERVER handle? true   connections? 0
NET 74538: emit close
HTTP 74538: server socket close
NET 74538: onconnection
STREAM 74538: read 0
STREAM 74538: need readable false
STREAM 74538: length less than watermark true
STREAM 74538: do read
NET 74538: _read - n 16384 isConnecting? false hasHandle? true
NET 74538: Socket._handle.readStart
HTTP 74538: SERVER new http connection
STREAM 74538: resume
STREAM 74538: resume true
STREAM 74538: flow
STREAM 74538: read undefined
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: reading, ended or constructing false
STREAM 74538: resume
STREAM 74538: push < 7[censored] ... 9 more bytes>
STREAM 74538: resume false
STREAM 74538: read 0
STREAM 74538: need readable false
STREAM 74538: length less than watermark true
STREAM 74538: do read
STREAM 74538: flow
STREAM 74538: read undefined
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: reading, ended or constructing false
STREAM 74538: read undefined
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: reading, ended or constructing false
STREAM 74538: push null
STREAM 74538: onEofChunk
STREAM 74538: emitReadable_
STREAM 74538: flow
STREAM 74538: read undefined
STREAM 74538: endReadable
HTTP 74538: SERVER socketOnParserExecute 660
STREAM 74538: endReadableNT
STREAM 74538: readableAddChunk {
  message: '\x1B[36m[EncryptionManager]\x1B[0m Loaded existing key & salt for encrypting arbitrary data.',
  level: 'info',
  service: 'backend',
  [Symbol(level)]: 'info',
  [Symbol(message)]: '{"level":"info","message":"\\u001b[36m[EncryptionManager]\\u001b[0m Loaded existing key & salt for encrypting arbitrary data.","service":"backend"}'
}
STREAM 74538: ondata
[backend] info: [EncryptionManager] Loaded existing key & salt for encrypting arbitrary data.
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
STREAM 74538: maybeReadMore read 0
STREAM 74538: read 0
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: do read
NET 74538: createConnection [
  {
    highWaterMark: 65536,
    path: undefined,
    localAddress: null,
    port: '8888',
    host: '0.0.0.0'
  },
  null,
  [Symbol(normalizedArgs)]: true
]
NET 74538: pipe false undefined
NET 74538: connect: attempting to connect to 0.0.0.0:8888 (addressType: 4)
NET 74538: destroy
NET 74538: close
NET 74538: close handle
STREAM 74538: readableAddChunk {
  message: '\x1B[36m[CollectorApi]\x1B[0m fetch failed',
  level: 'info',
  service: 'backend',
  [Symbol(level)]: 'info',
  [Symbol(message)]: '{"level":"info","message":"\\u001b[36m[CollectorApi]\\u001b[0m fetch failed","service":"backend"}'
}
STREAM 74538: ondata
[backend] info: [CollectorApi] fetch failed
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
STREAM 74538: maybeReadMore read 0
STREAM 74538: read 0
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: do read
NET 74538: emit close
HTTP 74538: write ret = true
HTTP 74538: outgoing message end.
STREAM 74538: push null
STREAM 74538: onEofChunk
STREAM 74538: emitReadable_
STREAM 74538: flow
STREAM 74538: read undefined
STREAM 74538: endReadable
STREAM 74538: read 0
STREAM 74538: endReadable
STREAM 74538: endReadableNT
NET 74538: _final: not ended, call shutdown()
STREAM 74538: endReadableNT
NET 74538: afterShutdown destroyed=false
NET 74538: destroy
NET 74538: close
NET 74538: close handle
NET 74538: has server
NET 74538: SERVER _emitCloseIfDrained
NET 74538: SERVER handle? true   connections? 0
NET 74538: emit close
HTTP 74538: server socket close
prisma:info Starting a sqlite pool with 17 connections.
STREAM 74538: readableAddChunk {
  message: 'Child process exited with code 0 and signal null',
  level: 'warn',
  service: 'backend',
  [Symbol(level)]: 'warn',
  [Symbol(message)]: '{"level":"warn","message":"Child process exited with code 0 and signal null","service":"backend"}'
}
STREAM 74538: ondata
[backend] warn: Child process exited with code 0 and signal null
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
STREAM 74538: readableAddChunk {
  service: 'backend',
  level: 'info',
  message: 'Worker for job "cleanup-orphan-documents" exited with code 0',
  [Symbol(level)]: 'info',
  [Symbol(splat)]: [ undefined ],
  [Symbol(message)]: '{"level":"info","message":"Worker for job \\"cleanup-orphan-documents\\" exited with code 0","service":"backend"}'
}
STREAM 74538: ondata
[backend] info: Worker for job "cleanup-orphan-documents" exited with code 0
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
STREAM 74538: maybeReadMore read 0
STREAM 74538: read 0
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: do read
^CSTREAM 74538: readableAddChunk {
  service: 'backend',
  code: 'SIGINT',
  ignore_hook: true,
  hide_meta: true,
  level: 'info',
  message: 'Gracefully exiting',
  [Symbol(level)]: 'info',
  [Symbol(splat)]: [ { code: 'SIGINT', ignore_hook: true, hide_meta: true } ],
  [Symbol(message)]: '{"code":"SIGINT","hide_meta":true,"ignore_hook":true,"level":"info","message":"Gracefully exiting","service":"backend"}'
}
STREAM 74538: ondata
[backend] info: Gracefully exiting
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
STREAM 74538: maybeReadMore read 0
STREAM 74538: read 0
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: do read
STREAM 74538: readableAddChunk {
  service: 'backend',
  code: 'SIGINT',
  ignore_hook: true,
  hide_meta: true,
  level: 'info',
  message: 'Gracefully exited',
  [Symbol(level)]: 'info',
  [Symbol(splat)]: [ { code: 'SIGINT', ignore_hook: true, hide_meta: true } ],
  [Symbol(message)]: '{"code":"SIGINT","hide_meta":true,"ignore_hook":true,"level":"info","message":"Gracefully exited","service":"backend"}'
}
STREAM 74538: ondata
[backend] info: Gracefully exited
STREAM 74538: dest.write true
STREAM 74538: ondata
STREAM 74538: dest.write true
[Preferences] Saving last_bounds preference.
STREAM 74538: maybeReadMore read 0
STREAM 74538: read 0
STREAM 74538: need readable true
STREAM 74538: length less than watermark true
STREAM 74538: do read
----


```
Heres some other information relating to ProtonVPN blocking 0.0.0.0 

NO VPN
```
@~ % curl -I --connect-timeout 2 http://0.0.0.0:9999
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.14.0
Date: Sat, 27 Dec 2025 23:28:11 GMT
Content-type: text/html; charset=utf-8
Content-Length: 303
@127 MacOS % python3 -m http.server 9999 --bind 0.0.0.0 
Serving HTTP on 0.0.0.0 port 9999 (http://0.0.0.0:9999/) ...
127.0.0.1 - - [27/Dec/2025 15:28:11] "HEAD / HTTP/1.1" 200 -
```







and with VPN 
```
@~ % curl -I --connect-timeout 2 http://0.0.0.0:9999
curl: (7) Failed to connect to 0.0.0.0 port 9999 after 0 ms: Couldn't connect to server
@~ % 
```

**Comment by ghost** [comment]
Encountered this recently and, as mentioned above, you need to specifically allow access to 0.0.0.0 
If you're using Lulu, then you need to add a rule for that. 
Without it, the document uploader was offline. After adding, it was enabled/available.
