### ISSUE TITLE
[BUG]: Cannot send any successful query on macOS desktop app

### ISSUE THREAD

**Issue by deeplook** [Mintplex-Labs/anything-llm#867]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I've installed AnythingLLM 1.2.0 desktop on macOS arm, added my OpenAI API key, created a workspace, but cannot run a single request. Instead I'm getting these errors. Ideas welcome.

<img width="340" alt="anythingllm2" src="https://github.com/Mintplex-Labs/anything-llm/assets/1001778/2a74fe77-6614-4b0f-bfb0-b9e763a3bf84">
<img width="287" alt="anythingllm" src="https://github.com/Mintplex-Labs/anything-llm/assets/1001778/99af24a0-1e6b-4077-ad8a-7d8d6b7823f3">

**Comment by deeplook** [comment]
If I run this on a model in my local LM Studio, I do get a response from the model, and right after that this very response is overwritten by the same error message:

<img width="445" alt="anyllm2" src="https://github.com/Mintplex-Labs/anything-llm/assets/1001778/9e3310e2-e602-4896-b507-fe59ee54ae2b">

**Comment by timothycarambat** [comment]
This looks like the local SQLite db was not migrated as it should have been on boot - the `chatMode` property does not exist. Can you full-quit the application and restart it? That should migrate the db as it does a schema check on boot.

**Comment by deeplook** [comment]
Amazing, but that does the trick. I can't believe I haven't done this before. Thanks!

**Comment by timothycarambat** [comment]
@deeplook Glad it was a simple fix :)

The adage of "did you turn it off and turn it back on again" sometimes can actually work 😆
