### ISSUE TITLE
[FEAT]: how to specify running the llama cpp model on GPU

### ISSUE THREAD

**Issue by ivy-lv11** [Mintplex-Labs/anything-llm#870]
### What would you like to see?

I use Docker to run the AnythingLLM. 
After putting llama-2-7b.gguf under the model/ folder, it runs correct and outputs normally. However, where could I specify the model device is GPU or CPU? 
Thanks a lot!

**Comment by timothycarambat** [comment]
The llama.cpp functionality is quite bare-bones right now. If you wanted to offload layers to GPU for better performance and such that isn't available currently for that form. You can move your model over to Ollama or something else more comprehensive and get that ability. 👍
