### ISSUE TITLE
[BUG]: Cannot save and embed PDFs or scraped web pages.

### ISSUE THREAD

**Issue by iandol** [Mintplex-Labs/anything-llm#872]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

V1.1.1 of the desktop, also running LM Studio V0.2.16. Plain chat is working fine, but when I try to add documents, nothing I try works.

1. Click to upload and select some PDFs.
2. Select 1 PDF and "move to workspace"
3. Click Save and Embed.

I always get the below:

<img width="423" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/153905/351261c4-9575-4c4d-9248-b681d45b7195">

No errors in the settings > event logs. I've tried with about 10 different PDFs (none of them need OCR, they are text). I also tried "Fetch website" using: 

https://elv.sh/learn/fundamentals.html

This gives the same error when clicking save and embed.

### Are there known steps to reproduce?

See above, this is 100% reproducible on my Macbook Air M2 16GB running macOS 14.3.1

**Comment by taozhiyuai** [comment]
same problem.

**Comment by timothycarambat** [comment]
Your IP/VPN is blocked by HuggingFace. Solution: https://github.com/Mintplex-Labs/anything-llm/issues/821

**Comment by iandol** [comment]
Thanks for the help. Manual download didn't work for me: https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1984856061
