### ISSUE TITLE
[FEAT]: Persist LLM Providers parameters when toggling between providers

### ISSUE THREAD

**Issue by tiangao88** [Mintplex-Labs/anything-llm#874]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Running AnythingLLM on hosted version in Railway thanks to the deployment template (thanks!)

Parameters are not saved consistently which is quite an annoyance if you switch frequently LLM models to compare them
For example:
- OpenAI : the API key is saved but the other parameters are not
- LocalAI : the API key is saved but the other parameters are not
- Perplexity: the API key is not saved but the other parameters are 
- Openrouter: none of the parameters are saved
- Groq: perfect, all parameters are saved!

I haven't tried the other LLM providers.

**Comment by timothycarambat** [comment]
The parameters are not saved at all? Or are not saved between restarts?

**Comment by tiangao88** [comment]
> The parameters are not saved at all? Or are not saved between restarts?

For example, I set up parameters for Openrouter and go test the LLM in a workspace. 
I go back to the settings to switch to set up Openai parameters and go try the LMM in a workspace.
I go back to the settings to switch back to Openrouter and all parameters are gone.

I just tried Azure OpenAI and all parameters are also not saved when switching back and forth different settings.

My Railway instance is set up to never go to sleep, and I never restart the instance.

**Comment by timothycarambat** [comment]
Oh, this is actually normal. It ties back to a legacy reason as to why it happens but I agree that it is not an "ideal" behavior. I think we can make this change now given the current state of the codebase. So not a bug, but really a feature that would make toggling between providers not so much of a headache 👍
