### ISSUE TITLE
[FEAT]: Can I add more document folders and rename the folders for better structure ?

### ISSUE THREAD

**Issue by wallartup** [Mintplex-Labs/anything-llm#877]
### What would you like to see?

When uploading a lot of documents it gets messy quite quickly because of the share amount of documents.

Can I rename the custom-documents folder and add more folders to the documents folder to make the experience easier to work with. For example like this:

Folder: Food
Folder: Recipes
Folder: Research
Folder: Appliances

You get it, this way it's easy to get organized.

Managing larger amounts of documents with many users is quite difficult at the moment.

**Comment by timothycarambat** [comment]
Agreed, we actually have designs to implement this and it will be done pretty soon. It is indeed hard to manage many documents as they all sit in a single folder.

Moving conversation to https://github.com/Mintplex-Labs/anything-llm/issues/554

**Comment by BeeVee23** [comment]
Excellent! That's exactly the question I came to ask. I have md documentation arranged by year and I'd like to import it for AnythingLLM into folders called 2024, 20205, 2026 and so on. Any news on progress?
