### ISSUE TITLE
[BUG]: Race Condition Vulnerability

### ISSUE THREAD

**Issue by rook1337** [Mintplex-Labs/anything-llm#878]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hello team,
Please check full report here: https://huntr.com/bounties/a3c69faf-cca0-4c10-8739-57e5bef7a95f/

There is no response on this report from past 1 month, kindly check and review it

**Comment by timothycarambat** [comment]
Closing as wonfix as it would require the instance owner publishing an invitation link publically - which is obviously ill advised since all instances get users by invitation only and should be sent peer to peer
