### ISSUE TITLE
[FEAT]: Support to query local project api interface

### ISSUE THREAD

**Issue by xingwozhonghua126** [Mintplex-Labs/anything-llm#880]
### What would you like to see?

I hope this project can read the code, like the internal projects of local companies. If you want to know the api interface, you can only ask the old employees. If ai can directly read all the projects and analyze the interfaces, it will be much more convenient.

**Comment by lem0na** [comment]
I second this. The last few days I have been trying to achieve this with no success - to index git repositories from the file system.

**Comment by timothycarambat** [comment]
Can now be done with custom agents https://docs.anythingllm.com/agent/custom/introduction
