### ISSUE TITLE
[FEAT]: Push event logging to asynchronous tasks

### ISSUE THREAD

**Issue by khareyash05** [Mintplex-Labs/anything-llm#883]
### What would you like to see?

I had been going through the server side code and I found out that event logging functionalities in api can cause critical tasks like new admin creation to fail if they take a lot of time. Pushing those events to a message queue system can enable critical tasks to complete without any hinderance thus also enabling easy scaling .

I can help implement the system using BullMQ/ RabbitMQ/ Any other message brokers

**Comment by timothycarambat** [comment]
The restriction here is that we cannot run any extra services that arent nodejs as we cannot port that to the desktop app.

Agreed that these tasks should not be blocking and be delegated to another service so that they are non-blocking.

**Comment by khareyash05** [comment]
We have to find alternatives as it might cause major issues while scaling. I will look for alternative solutions if any.

**Comment by timothycarambat** [comment]
I would suspect the bottleneck at any nominal scale would not be a DB call to a local DB file. It would likely be the LLM running inferencing. We have instances that have 100+ concurrent users with no hiccups and their slowest (or most costly) bottleneck is having an LLM provider that can manage that much throughput from users.

I still agree is should be moved to another process, but I really dont think this would be the bottleneck to optimize on
