### ISSUE TITLE
[BUG]: Use remote embedder fails

### ISSUE THREAD

**Issue by egSat** [Mintplex-Labs/anything-llm#884]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hi all
I'm trying to use a remote embedder, loaded from text-generation-webui.  I set thte ip address and port, and Max embedding chunk length to 384. I use LanceDB.
I removed the file and loaded again (as recommended when switching embedder), but it shows the following error from logs:
Adding new vectorized document into namespace emfpruebas
Chunks created from document: 13
Inserting vectorized chunks into LanceDB collection.
addDocumentToNamespace LanceDBError: Append with different schema: original=Field(id=0, name=vector, type=fixed_size_list:float:384)
Field(id=1, name=id, type=string)
Field(id=2, name=url, type=string)
Field(id=3, name=title, type=string)
Field(id=4, name=docAuthor, type=string)
Field(id=5, name=description, type=string)
Field(id=6, name=docSource, type=string)
Field(id=7, name=chunkSource, type=string)
Field(id=8, name=published, type=string)
Field(id=9, name=wordCount, type=double)
Field(id=10, name=token_count_estimate, type=double)
Field(id=11, name=text, type=string)
 new=Field(id=0, name=vector, type=fixed_size_list:float:768)
Field(id=1, name=id, type=string)
Field(id=2, name=url, type=string)
Field(id=3, name=title, type=string)
Field(id=4, name=docAuthor, type=string)
Field(id=5, name=description, type=string)
Field(id=6, name=docSource, type=string)
Field(id=7, name=chunkSource, type=string)
Field(id=8, name=published, type=string)
Field(id=9, name=wordCount, type=double)
Field(id=10, name=token_count_estimate, type=double)
Field(id=11, name=text, type=string)

Failed to vectorize file with stuff.docx

### Are there known steps to reproduce?

Use a remote embedder with Max embedding chunk length different than 768

**Comment by egSat** [comment]
Hi,

removing the data from folder (lancedb/workspace-lance/data) fixes it.
I don't know just removing the document from web should be sufficient, so I leave this issue open.

thank you very much for this amazing project

**Comment by timothycarambat** [comment]
Do you know which tag of docker you are/were on? This was an old bug we had a long time ago that was due to lanceDB package that we bumped and fixed.

If you dont know tag the value for `vectordb` in the `/app/server/package.json` file in the container would be nice to have. It should be `0.1.19`

**Comment by egSat** [comment]
Yes, it shows 0.1.19 for vectorDB. I pulled the image two days ago so I assume it's the latest one
