### ISSUE TITLE
OpenAI:listModels unable to get local issuer certificate

### ISSUE THREAD

**Issue by venki-lfc** [Mintplex-Labs/anything-llm#886]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hi, I get the error 
`OpenAI:listModels unable to get local issuer certificate` when I try to enter my OpenAI API key and try to choose the models. I am using the pulled docker image and I have followed the instructions mentioned in the docker README. When when I send a text, I get the same response.

I ran the docker using 
`docker run -it -p 3001:3001 --cap-add SYS_ADMIN -v ${STORAGE_LOCATION}:/app/server/storage -v ${STORAGE_LOCATION}/.env:/app/server/.env -e STORAGE_DIR="/app/server/storage" mintplexlabs/anythingllm`

I created the storage folder and .env file before executing the above line. 

![image](https://github.com/Mintplex-Labs/anything-llm/assets/60582874/37ca96c3-e756-40b6-9b7d-6fdbd74a8f59)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/60582874/26e64553-7300-499f-933f-551e0a40fc96)

Any help would be appreciated, thanks!

### Are there known steps to reproduce?

Trying to enter the OpenAI API key and this error pops up.

**Comment by shatfield4** [comment]
Did you enter the OpenAI API key in the LLM settings? Make sure your .env is in the correct place and make sure your OpenAI API key is valid.

**Comment by timothycarambat** [comment]
Additionally, what operating system are you on? Seems to be related to an OS SSL/TLS issue not trusting certificates or getting an invalid cert due to a number of reasons. https://medium.com/@akhilkanugolu/dealing-with-certificate-issues-in-the-openai-package-on-your-local-machine-a7f563394c6c

**Comment by timothycarambat** [comment]
Marking as wontfix, this related to the network layer of the client and outside of scope of AnythingLLM
