### ISSUE TITLE
Can you add Windows compatibility?

### ISSUE THREAD

**Issue by IMCARLOSEHR** [Mintplex-Labs/anything-llm#89]
I can't download "pyobjc-framework-AddressBook" as well as a few other files because it is for MasOS, is there a windows version?

According to ChatGPT, only the developer can fix this issue.

**Comment by timothycarambat** [comment]
Refer to running this application [Inside of Docker](https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md)
