### ISSUE TITLE
[FEAT]:  Multiple simulataneous Chats with Ollama

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#903]
### What would you like to see?

I can deploy infra for multiple users to chat at the same time. There should be provision in the admin account to choose number of people who can chat through their accounts at the same time instead of queing the responses.
I am using ollama as it is free to use.

**Comment by timothycarambat** [comment]
This rate limiting can be applied via the system preferences in multi-user mode via the "chats per day". While this may not be ideal this is a specific infra problem with your implementation of Ollama and therefore it would be your responsibility to apply more granular rate limiting on top of this solution as it is specific to your use case using some kind of middleware between AnythingLLM and Ollama
