### ISSUE TITLE
[FEAT]: Default support to search from some sites

### ISSUE THREAD

**Issue by razakpm** [Mintplex-Labs/anything-llm#904]
### What would you like to see?

I have a requirement to support multi-website information retrieval, implement role-based access restrictions for retrieving searches from those sites, and enable the ability to search through PDF documents available on designated websites. I noticed that [anything-llm] offers PDF features. Could you confirm if it's possible to provide site URLs?

**Comment by timothycarambat** [comment]
The PDF is a direct file upload only. It would be recommended that you download the file and upload and or automate this via the API (Docker version only - no API on desktop).

If you put a URL to a PDF in the "website fetch" part of the uploader I'm pretty certain it will fail. That is a great feature to add though. Being able to fetch even documents via a URL and read them in.
