### ISSUE TITLE
[FEAT]: Support for Multimodal - LlaVa, MiniGPT-v2 and MiniGPT4

### ISSUE THREAD

**Issue by karthikRavichandran** [Mintplex-Labs/anything-llm#905]
### What would you like to see?

It would be really great for research community to have Multimodal support in anythingLLM. Currently I'm using LlaVa through CLI Ollama so I can see the impact.

**Comment by timothycarambat** [comment]
Agreed, it will be connected soon. Issue is being tracked on this issue https://github.com/Mintplex-Labs/anything-llm/issues/558
