### ISSUE TITLE
[FEAT]: Search from sites , display answer along with the sources(webpage links)

### ISSUE THREAD

**Issue by sinjup** [Mintplex-Labs/anything-llm#906]
### What would you like to see?

I need to develop a custom Search Engine tailored for my websites. I tested with anythingllm by inputting the website URL in the 'website fetch' feature, but along with the answer, I also require the link to the webpage to be displayed. Additionally, if there are any other matching contents available on the websites, I need to display their sources (links) as well. Is this something that can be achieved through Anythingllm?

**Comment by timothycarambat** [comment]
We currently do this with Websites that are collected via the scraper!

<img width="1516" alt="Screenshot 2024-03-14 at 9 47 57 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/82abbdff-e06a-402c-848c-38bf7083dbe1">
<img width="794" alt="Screenshot 2024-03-14 at 9 48 03 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/cb3de2a1-9f67-48c6-b163-ef1201a9ded7">
