### ISSUE TITLE
[FEAT]: markdown support in UI

### ISSUE THREAD

**Issue by karthikRavichandran** [Mintplex-Labs/anything-llm#908]
### What would you like to see?

It would be great if we have certain markdown support for code snippet and latex for formula : Check this response: Sure! Here’s an explanation of how MINILLM works, along with some mathematical formulas to help illustrate the process:

```
$$S = f_{KD}(T)$$

$$S’ = \text{Prune}(S, \alpha)$$

$$S’’ = \text{Fine-tune}(S’, (x_1, y_1), \ldots, (x_n, y_n))$$
```

**Comment by timothycarambat** [comment]
This is more of an LLM thing not highlight the `\```\` codeblock with the appropriate language. For whatever reason LaTex does not come back with its normal alias of `tex`

If you were to ask it to highlight the codeblock with "tex" it would highlight the syntax properly. You can add this instruction to the system prompt of the workspace if working with lots of LaTex questions so you dont need to clarify this each prompt.
