### ISSUE TITLE
[FEAT]: Integeration with Cohere LLMs and embedders

### ISSUE THREAD

**Issue by 3koozy** [Mintplex-Labs/anything-llm#912]
### What would you like to see?

Command r and other Cohere LLM models using their API and embeder v3 model for embeddings..

**Comment by AnsonLai** [comment]
I'm going to add my voice to this one as well.  Should Cohere's models are pretty impressive and would really work well with Anything LLM's general approach.

**Comment by timothycarambat** [comment]
Will add this week support for both LLMs and embedders. Rerankers might be a bit more troublesome, but at least those
