### ISSUE TITLE
Differentiation of Anything LLM and Open-UI/EmbedChain

### ISSUE THREAD

**Issue by stevenbaert** [Mintplex-Labs/anything-llm#916]
### What would you like to see?

Anything-LLM seems quite behind when compared to any other tool in the market, f.e. Open-UI or EmbedChain. Open-UI has lots of tools and makes things easy to browse, while EmbedChain lets you bring in stuff from YouTube and other places. Your platform does have its own hosted version, which is good because it saves people from having to set it up themselves, but that's about it for now. It's great that you're excited about your project, but to really stand out, you might need to add more features like the ones in Open-UI, EmbedChain, MacGPT, MindMac, and Talk-To-GPT3.

**Comment by timothycarambat** [comment]
Okay, i see what you are suggesting, but to that point I'm not sure what version of AnythingLLM you are looking at but we have all of those tools listed + more and we have a desktop app, which is far simpler then even the hosted offering.
