### ISSUE TITLE
[BUG]: Failed to Save LLMs 

### ISSUE THREAD

**Issue by hittle2015** [Mintplex-Labs/anything-llm#918]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When model selected, click save changes only to get the failed to save LLMs error. 

### Are there known steps to reproduce?

1.  pull a  docker
2.  run with the suggested command, adding  two more 
    --add-host=host.docker.internal:host-gateway --net=host
3. docker container error logs  (see below)
[TELEMETRY ENABLED] Anonymous Telemetry enabled. Telemetry helps Mintplex Labs Inc improve AnythingLLM.
prisma:info Starting a sqlite pool with 21 connections.
fatal: not a git repository (or any of the parent directories): .git
getGitVersion Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

[TELEMETRY SENT] {
  event: 'server_boot',
  distinctId: 'bad38249-92b4-4bc4-9ef3-65431751adda',
  properties: { commit: '--', runtime: 'docker' }
}
Primary server in HTTP mode listening on port 3001
[Event Logged] - update_llm_provider
[Event Logged] - update_llm_provider
[Event Logged] - update_llm_provider
[Event Logged] - update_llm_provider

**Comment by timothycarambat** [comment]
I do not see an error log in those logs, only that the event for update was stored in the DB. There should be an error message in addition to Failed to Save LLM Settings. What LLM are you attempting to connect to?

**Comment by hittle2015** [comment]
llama2

**Comment by timothycarambat** [comment]
@hittle2015 Using which provider? LMStudio, LocalAi, Ollama, etc etc

**Comment by timothycarambat** [comment]
closed as stale
