### ISSUE TITLE
[BUG]: chatbot widget overriding html css

### ISSUE THREAD

**Issue by Kofangun** [Mintplex-Labs/anything-llm#919]
### How are you running AnythingLLM?

Docker (local)

### What happened?

First thank you for thzt great code.
Everything works fine to me exept the chatbot widget overriding my html css. For exemple h2 become normal font ... 
Not really a bug but i would like to change the widget icon and the open chat size. Is there a way ? 

### Are there known steps to reproduce?

I just use the provided js code and past it in my html.

**Comment by timothycarambat** [comment]
🤔 I would imagine this has to do with how tailwind is being loaded - it may be overriding the styles defaults presently. That being said, we are going to address the chat styling soon and that symptom will go away once that is merged. Is definitely a bug at this time though.

**Comment by jopdorp** [comment]
This makes the embed unusable for us at the moment

**Comment by timothycarambat** [comment]
@jopdorp does that prefix work by just including that script or does it not work unless you modify all the classes and then add that script? 

Also, is that script being applied before or after the embed?

**Comment by mice6** [comment]
> Even when adding the tag below to configure a prefix and adding the tailwind-anythingllm- in all the used tailwind classes, then it still interferes with the surrounding css. The prefix does seem to work:
> 
> ```
> <script>
>     tailwind.config = {
>       prefix: "tailwind-anythingllm-"
>     }
> </script>
> ```

Could I write how you used it?
