### ISSUE TITLE
Could not send chat

### ISSUE THREAD

**Issue by IMCARLOSEHR** [Mintplex-Labs/anything-llm#92]
I am using with docker, with the help of GPT I was able to get to the browser UI but when I insert a query it says:

localhost:3001 says
Could not send chat

GPT has no clue why

**Comment by argondigitalmoen** [comment]
I'm having the same issue. When I go to System Settings, all of the fields are green as well. Any idea what else it might be? 
<img width="335" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/137108011/06acff0f-a5a4-4c5d-8474-8bb96e332abc">

**Comment by frasergr** [comment]
Have a look at the container logs `docker logs anything-llm` and see if there's any hints there.

**Comment by jkrobin** [comment]
Same error and conditions here. I do see the following in the Docker log, however:

PineconeClient: Error calling describeIndex: 404: Not Found [PineconeError: PineconeClient: Error calling describeIndex: 404: Not Found]

**Comment by argondigitalmoen** [comment]
thank you for the tip, @frasergr . That helped me troubleshoot the problem and eventually solve it. I think I had multiple things going on.

For future people that might come here, my error could've been resolved by several changes.

1. The cp command doesn't work for me, and I need to use "copy" instead. So, in the package.json file, I updated one line to: "setup:envs": "copy /Y .\\server\\.env.example .\\server\\.env.development && copy /Y .\\collector\\.env.example .\\collector\\.env && copy /Y .\\docker\\.env.example .\\docker\\.env && echo \"All ENV files copied!\"",
2. Anywhere else it mentions cp in instructions, I just typed copy instead
3. I uninstalled Python from the Windows apps and went to https://www.python.org/downloads/ to reinstall it. When reinstalling, I checked the PATH option. Also, I selected custom install to make sure it got installed for all users. I also updated the save location to just C:/
4. Also, in the server location, my env files didn't copy properly, so I just filled those in manually (Pinecone info, etc)
5. And, I just reinstalled everything according to the various instructions. (Did a pip install pinecone-client, cd to anything-llm and did yarn install, then cd frontend && yarn install && cd ../server && yarn install, cd back to docker/, then docker-compose up -d --build, -m pip install virtualenv, then -mvirtualenv v-env, then source v-env/bin/activate, then pip install -r requirements.txt, then copy .env.example .env)

For anyone with this issue, if you're open to hosting it remotely, I found the AWS setup and instructions (with a bit of help from ChatGPT on GPT4) to be much easier to implement. Plus, I like the idea of being able to share online access with others and not having to walk them through the local install themselves.

**Comment by IMCARLOSEHR** [comment]
@argondigitalmoen I followed all the steps except #5.

I will do that later and update if it worked but for now I am still getting the "Could not send" error.

However, if you could link to the AWS setup, if it is easier I am all for it.

**Comment by IMCARLOSEHR** [comment]
@jkrobin 

While copying and pasteing errors into GPT, it seems to suggest it's something to do with Pinecone

**Comment by argondigitalmoen** [comment]
@IMCARLOSEHR check the AWS folder in anything-llm, it lays out the steps there.

If you followed any part of steps 1 through 4, you would definitely still need to do at least part of #5, because otherwise it wouldn't be updated. If you did all of them, follow the Read Me instructions from the beginning essentially.

I would avoid step #1 though unless you ran the "docker logs anything-llm" command prompt mentioned in the previous response by @frasergr got you an error related to cp.
