### ISSUE TITLE
[BUG]: Foreign language handled incorrectly

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#926]
### How are you running AnythingLLM?

Not listed

### What happened?

On hosted server (useanything), the prompt response sometimes displays odd characters instead of the Swedish characters.

<img width="596" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/5c752ae6-33a1-4af1-8ba6-1c65ffdc493f">

**Comment by shatfield4** [comment]
What model are you using here for your LLM? This may be an issue with language incompatibility in your model.

**Comment by RahSwe** [comment]
Hi!I use Claude-3, have used many times before without any problems. Hard to day if it’s a LLM or ALLM problem I guessMed vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.19 mars 2024 kl. 21:25 skrev Sean Hatfield ***@***.***>:﻿
What model are you using here for your LLM? This may be an issue with language incompatibility in your model.

**Comment by timothycarambat** [comment]
What is the target language, Swedish?

**Comment by RahSwe** [comment]
Yes, we have the special characters å ä öMed vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.20 mars 2024 kl. 01:11 skrev Timothy Carambat ***@***.***>:﻿
What is the target language, Swedish?

**Comment by shatfield4** [comment]
Is there any specific message that you send where you can consistently get these weird characters? I have tested all the claude models asking it to print out paragraphs in Swedish but cannot get the broken encoding like you are getting here. Also are you using this with your own documents? There is a possibility that your documents may include some characters with broken encoding and the LLM is just copying what it gets as context.


![Screen Shot 2024-03-20 at 11 34 03 AM](https://github.com/Mintplex-Labs/anything-llm/assets/2336488/a819e8f4-b6a3-418d-95b2-f2bd971559cd)

**Comment by RahSwe** [comment]
Hi!I did a lot of prompting today with no problems with the special characters. I will onboard a team on Friday, will return if there are any new language errors. May have been a temporary model lapse?Med vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.20 mars 2024 kl. 19:40 skrev Sean Hatfield ***@***.***>:﻿
Is there any specific message that you send where you can consistently get these weird characters? I have tested all the claude models asking it to print out paragraphs in Swedish but cannot get the broken encoding like you are getting here. Also are you using this with your own documents? There is a possibility that your documents may include some characters with broken encoding and the LLM is just copying what it gets as context.
Screen.Shot.2024-03-20.at.11.34.03.AM.png (view on web)

**Comment by shatfield4** [comment]
Closing since we haven't heard back.
