### ISSUE TITLE
[BUG]: Help！Upload file fail！Use Ollama and default config！

### ISSUE THREAD

**Issue by KKD4Soei** [Mintplex-Labs/anything-llm#932]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/58964439/53a1198b-a450-47ac-a225-ac0afd1260e9)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/58964439/130dbab5-eb33-44f5-87c9-84d69a4bf6fc)
Help！

![image](https://github.com/Mintplex-Labs/anything-llm/assets/58964439/462af596-2476-4827-b6b7-7a73de27ffa6)

**Comment by timothycarambat** [comment]
#821 

IP blocked by HuggingFace. See that issue for resolution

**Comment by KKD4Soei** [comment]
I Choolse Ollama as embedding model,and solve the problem!
