### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by crystal-yxj** [Mintplex-Labs/anything-llm#933]
### How are you running AnythingLLM?

Docker (local)

### What happened?

see my picture, i need your 
![all](https://github.com/Mintplex-Labs/anything-llm/assets/82490606/20d0291a-f117-438c-88b2-a99f2910bb9f)
![error](https://github.com/Mintplex-Labs/anything-llm/assets/82490606/ab230212-b7fc-4d07-a68a-163e5f2675b8)
![ing](https://github.com/Mintplex-Labs/anything-llm/assets/82490606/92a4637f-b461-488d-aa50-3a4ec39aa801)
help please.

**Comment by timothycarambat** [comment]
#821 IP blocked by hugging face, cannot download the embed model to run locally. Fix is in that thread!
