### ISSUE TITLE
[FEAT]: Keep focus on message box and clear terminal when using /reset to clear chat memory.

### ISSUE THREAD

**Issue by tsweet77** [Mintplex-Labs/anything-llm#937]
### What would you like to see?

There are a couple of recommendations:

1) When I have sent a message, the message box loses focus and I have to click on it again between each message instead of just continuing to type.

2) When I clear my chat memory and start a new chat, it doesn't clear the terminal.

**Comment by timothycarambat** [comment]
> When I have sent a message, the message box loses focus and I have to click on it again between each message instead of just continuing to type.

Will do this.

> When I clear my chat memory and start a new chat, it doesn't clear the terminal.

This is intended. The chats, despite visible in the UI still do not appear in the history sent to the LLM. They are purely only visible in the UI after reset.
