### ISSUE TITLE
[FEAT]: LLM Provider: AWS Bedrock Integration

### ISSUE THREAD

**Issue by gelbzucht** [Mintplex-Labs/anything-llm#938]
### What would you like to see?

how about integrating AWS Bedrock, too? (set API Key + API Secret Key + Region). 
So i.e. the Claude V3 can be used via AWS Bedrock API.

**Comment by teemuniiranen** [comment]
Named profile support would be nice in addition to manual API key / secret / region combination.

**Comment by fmg-tomdifulvio** [comment]
Is anyone currently working on this?
