### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by tsweet77** [Mintplex-Labs/anything-llm#948]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![Anything_LLM_Chat_Issue](https://github.com/Mintplex-Labs/anything-llm/assets/59816302/11f5ece6-e66f-48e3-b68c-dd054216fad1)

I have attached a screenshot of how AnythingLLM has just started going crazy on a chat with Mistral Medium on OpenRouter. I just ask how it is, and it goes into a discussion that I didn't talk about. I reinstalled the AnythingLLM and it seemed to have remembered my workspaces and API keys and such from before, so I was unable to do a clean reinstall.

### Are there known steps to reproduce?

Chose OpenRouter, Mistral Medium LLM.

Chose Mistral Medium chat model from the chat settings.

Started typing "How are you?"

It went into a deep discussion about irrelevant things.

I am not sure if AnythingLLM is sending extra conversation things.

It also happened when I tried Mixtral Base model.

**Comment by tsweet77** [comment]
When I go to the OpenRouter playground and try Mistral Medium, it answers fine without detracting:

Hi! I'm just a computer program, so I don't have feelings, but I'm here to help you. How can I assist you today? Is there something you would like to learn about or discuss? I can provide information on a wide range of topics.

**Comment by timothycarambat** [comment]
This is not a bug per-se, this is a model behavior and is not something within AnythingLLM's control (we dont run the model, we just send requests to it!). 

Anecdotally, I have found OpenRouter in particular to sometimes have this behavior but only on the _first_ message in a given session history. It is intermittent, but its unrelated to AnythingLLM's code or execution
