### ISSUE TITLE
[BUG]:  AppImage is missing app icon.

### ISSUE THREAD

**Issue by AndKe** [Mintplex-Labs/anything-llm#950]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The AppImage does not have an application icon.

### Are there known steps to reproduce?

Start .AppImage on (for example) Ubuntu 23.10

**Comment by timothycarambat** [comment]
This is a bug with `electron-builder` that currently goes unsolved for reasons unknown. I have tried to implement every solution that is said to patch it and none reflect in the AppImage besides running the appicon daemon. So for now, no icon for AppImages :(
