### ISSUE TITLE
[FEAT]: Chaning Token size with different model from LM Studio

### ISSUE THREAD

**Issue by mictadlo** [Mintplex-Labs/anything-llm#951]
### What would you like to see?

Hi,
I installed AnythingLLMDesktop-AppleSilicon.  I was able to connect both AnythingLLM with LM Studio. However, I could not figure out how to change in AnythingLLM for a new Model size the Token size.

**Comment by timothycarambat** [comment]
This can be configured from the UI to suit your model needs. It can also be controlled on the LMStudio side as well

<img width="882" alt="Screenshot 2024-03-22 at 2 44 46 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/4328708b-6f46-4ed3-a7ef-2ad5cba1fa4f">
