### ISSUE TITLE
[BUG]: Embed chat into website overide css from Website

### ISSUE THREAD

**Issue by wepschmiede** [Mintplex-Labs/anything-llm#954]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When embedding the chat, Tailwind overrides the styles of the page, for instance when Bootstrap 5 is used in the template. Additionally, the embed yarn build does not generate executable code that work.

### Are there known steps to reproduce?

Use anythingllm-chat-widget.min.js:

Include Script in Demo Page that use Bootstrap 5:

- Heading reformat with tailwind and other css style overide by tailwind.

Build Steps anythingllm-chat-widget.min.js:

- cd embed 
- yarn 
- yarn dev 

boot up an example HTML page to use the chat embed widget with own data-embed-id not working.

**Comment by timothycarambat** [comment]
Tracking in #919

As for dev, its not that simple to run.
- be running `yarn dev:server` and `yarn dev:frontend`
- Create workspace and then create a real Embed Config
- Copy its embed-id

then in the embed folder:
`yarn dev`
Open HTML demo index.html page and in that HTML edit the <script> to have the src of `src="/dist/anythingllm-chat-widget.js"` to load in changes and edits and make sure the `data-embed-id` attribute is the same value from the previous step.

This will dev embed connected to a local embed config and will hot load changes on refresh of the page.

It needs to reference the correct

**Comment by hanwayTech** [comment]
May it be better to use just pure css for this widget as it is not complex?

**Comment by timothycarambat** [comment]
That would make it more complex
