### ISSUE TITLE
[BUG]: Information about chat model isn't stored

### ISSUE THREAD

**Issue by ErykCh** [Mintplex-Labs/anything-llm#955]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hi, version 1.4.1 on windows

after setting chat model 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/40fcfa41-94f7-4956-bbbe-aa8098b5b9ef)
and saving (update workspace on the bottom)
when I back again to this tab there is:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/95491982/3785bdb7-4183-4ddc-a4b6-99c49d8232f1)

**Comment by shatfield4** [comment]
Does this only happen on OpenRouter or all LLMs? Are you changing the LLM provider in the LLM preference menu after setting the chat model under workspace settings? Every time you switch the LLM provider under LLM preferences, it is supposed to switch back to system default.

**Comment by ErykCh** [comment]
No I don't touch LLM Provider. Its OpenRouter all the time.

**Comment by timothycarambat** [comment]
Currently unable to replicate in AnythingLLM Desktop 1.4.0
Using other providers, but also including OpenRouter.
- Set OpenRouter as LLM Preference with some model
- Set multiple workspace to use different model from same provider & Save.

On revisit the model is still selected and chats honor this.

Recommendation: Ensure on the latest version and to full quit AnythingLLM and restart to ensure all migrations are present.
