### ISSUE TITLE
[FEAT]: Provide options to choose between different LLM providers for each workspace

### ISSUE THREAD

**Issue by dctmfoo** [Mintplex-Labs/anything-llm#960]
### What would you like to see?

At the time of setup of anythingLLM i had chosen openAI for LLM and now whenever i create a new workspace, i am forced to use OpenAI. Please provide options to choose between different LLM providers in the workspace.

**Comment by timothycarambat** [comment]
Tracking this feature on https://github.com/Mintplex-Labs/anything-llm/issues/698

Agree with you, and it will be done 👍
