### ISSUE TITLE
Could not respond to message. An error occurred while streaming response. Failed to fetch [BUG]: 

### ISSUE THREAD

**Issue by dague0477** [Mintplex-Labs/anything-llm#962]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I was able to install AnythingLLM. I created the workspace. It's when I type in a question, I get the following message: 
....Could not respond to message. An error occurred while streaming response. Failed to fetch...

I am running Lubuntu 23.10 Mantic. 
![screenshot-d33cad50](https://github.com/Mintplex-Labs/anything-llm/assets/79458262/e821e14e-aaaa-4778-876b-95cee928fbed)

**Comment by dague0477** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

Python 3.8.11
[GCC 7.5.0] :: Anaconda, Inc. on linux

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/821

Do you have documents already embedded?

**Comment by dague0477** [comment]
This is the message I am getting in the terminal. Also,
/tmp/.mount_Anythi7IKsIf/resources/ollama/llm        ----> The folder "Ollama/llm" is missing in the resources folder

thanks,
David G.


OUTPUT MSG:

Updating location Prisma binaries for linux builds.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/{user}/.config/anythingllm-desktop/storage/anythingllm.db"

Applying migration `20230921191814_init`
Applying migration `20231101001441_init`
Applying migration `20231101195421_init`
Applying migration `20240113013409_init`
Applying migration `20240118201333_init`
Applying migration `20240202002020_init`
Applying migration `20240206181106_init`
Applying migration `20240206211916_init`
Applying migration `20240208224848_init`
Applying migration `20240210001903_init`
Applying migration `20240210004405_init`
Applying migration `20240216214639_init`
Applying migration `20240219211018_init`
Applying migration `20240301002308_init`

The following migration(s) have been applied:

migrations/
  └─ 20230921191814_init/
    └─ migration.sql
  └─ 20231101001441_init/
    └─ migration.sql
  └─ 20231101195421_init/
    └─ migration.sql
  └─ 20240113013409_init/
    └─ migration.sql
  └─ 20240118201333_init/
    └─ migration.sql
  └─ 20240202002020_init/
    └─ migration.sql
  └─ 20240206181106_init/
    └─ migration.sql
  └─ 20240206211916_init/
    └─ migration.sql
  └─ 20240208224848_init/
    └─ migration.sql
  └─ 20240210001903_init/
    └─ migration.sql
  └─ 20240210004405_init/
    └─ migration.sql
  └─ 20240216214639_init/
    └─ migration.sql
  └─ 20240219211018_init/
    └─ migration.sql
  └─ 20240301002308_init/
    └─ migration.sql

Your database is now in sync with your schema.

EROFS: read-only file system, unlink '/tmp/.mount_Anythi7IKsIf/resources/backend/node_modules/.prisma/client/index.js'


Prisma schema loaded from prisma/schema.prisma
Error:
EROFS: read-only file system, unlink '/tmp/.mount_Anythi7IKsIf/resources/backend/node_modules/.prisma/client/index.js'


[OllamaProcessManager] Ollama will bind on port 34477 when booted.
[OllamaProcessManager] Creating Ollama models folder in application storage. {
  destination: '/home/{user}/.config/anythingllm-desktop/storage/models/ollama'
}
[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.
[OllamaProcessManager] Cannot boot Ollama - no executable found in /tmp/.mount_Anythi7IKsIf/resources/ollama/llm


________________________________

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/821

**Comment by timothycarambat** [comment]
That Ollama error is not blocking the boot of the system. Its because Linux does not have support for embedded Ollama

**Comment by dague0477** [comment]
Ok but how do I solve that problem?



On Mar 25, 2024, at 1:11 PM, Timothy Carambat ***@***.***> wrote:

﻿

That Ollama error is not blocking the boot of the system. Its because Linux does not have support for embedded Ollama

**Comment by timothycarambat** [comment]
We do not support embedded built in Ollama for Linux desktop in v1.4.x. It may appear in the next update. The bug you are encountering is likely the bug in https://github.com/Mintplex-Labs/anything-llm/issues/821

**Comment by IvanMoon** [comment]
I also have it popping up sometimes. Only restarting the software helps.

**Comment by Capitalmind** [comment]
I have the same error and wonder if it is to do with ollama or gollama already being installed and a server clash?

**Comment by lhx150926** [comment]
I have the same error :[OllamaProcessManager] Ollama will bind on port 46257 when booted.
[Preferences] Will load window with last know bounds.
[OllamaProcessManager] SINGLETON LOCK: Using existing OllamaProcessManager.
[OllamaProcessManager] Cannot boot Ollama - no executable found in /AnythingLLMDesktop/anythingllm-desktop/resources/ollama/llm
