### ISSUE TITLE
[BUG]: Error: 1 documents failed to add. fetch fail  

### ISSUE THREAD

**Issue by peoplelikethesun** [Mintplex-Labs/anything-llm#964]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/52613270/8c6b30c9-90e5-496c-9e1e-7b6041ead6b3)

**Comment by walkerandmay** [comment]
I am experiencing the same issue.

**Comment by walkerandmay** [comment]
Could it be because we used Chinese literature?

**Comment by Zowlex** [comment]
+1

**Comment by Tiberius1313** [comment]
> Could it be because we used Chinese literature?

AnythingLLM Embedder uses Xenova all-MiniLM-L6-v2
https://huggingface.co/Xenova/all-MiniLM-L6-v2

To my understanding this model is English only
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

For Chinese embedding you have to use a model that understands the Language
https://huggingface.co/models?library=sentence-transformers&language=zh&sort=trending

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/issues/966

This is because the embedder cannot download from HuggingFace due to VPN, IP-blocked, or something along those lines by HF servers. You can however manually download these models from their UI or individually.

**Comment by zykj** [comment]
i7 3700/16g ram ,win10 simplified Chinese Version ,  Anythingllm v1.4.1 + ollama + qwen:4b ,  same problem ,

**Comment by wxzcldw** [comment]
I faced the same issue
![image](https://github.com/Mintplex-Labs/anything-llm/assets/163713584/97eab5a0-e4ca-40a5-bded-d8f716c50987)
I tried Chinese Or English Files, the result is same.

**Comment by wxzcldw** [comment]
I find a way  to fix this problem. set as fellows:
![image](https://github.com/Mintplex-Labs/anything-llm/assets/163713584/2f37b7d3-8a09-40c2-beee-05aa21037841)
then, add files are good.

**Comment by shanghaiyangming** [comment]
> I find a way to fix this problem. set as fellows: ![image](https://private-user-images.githubusercontent.com/163713584/319658341-2f37b7d3-8a09-40c2-beee-05aa21037841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjIzNjEsIm5iZiI6MTcxNjI2MjA2MSwicGF0aCI6Ii8xNjM3MTM1ODQvMzE5NjU4MzQxLTJmMzdiN2QzLThhMDktNDBjMi1iZWVlLTA1YWEyMTAzNzg0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwMzI3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDU2ZmIzN2M3OGNiNGNmN2U2ZTcwN2MxYzdkOWM5MDVjMTAzMzJlOGYzODIxMGJmYmI1ODVhZTZlZGE4MzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.quO7HvplUDBpVVmeiFM1lH6y0d4rhijzKIcWW-oJYDQ) then, add files are good.

it is indeed sloved the problem with your method

**Comment by nfhspongying** [comment]
same case as zykj while use [wxzcldw]'s solution，“failed to add.

Ollama Failed to embed: [undefined]: undefined”

**Comment by timothycarambat** [comment]
> same case as zykj while use [wxzcldw]'s solution，“failed to add.
> 
> Ollama Failed to embed: [undefined]: undefined”

This means the ollama process ran out of memory processing the embeddings and failed to return a vector

**Comment by Sunrisies** [comment]
![Image](https://github.com/user-attachments/assets/9ae5dfb1-51dd-4df4-9a15-8637ab50127e)可以使用ollama来解决这个问题

**Comment by timothycarambat** [comment]
If you are based in China and looking at this thread please see: https://github.com/Mintplex-Labs/anything-llm/issues/3113#issuecomment-2637804724

This suspension will be resolved in the future, but for now that is this will be the case.
