### ISSUE TITLE
[BUG]: embed document failed | windows | LanceDB

### ISSUE THREAD

**Issue by Zowlex** [Mintplex-Labs/anything-llm#966]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Failed to embed documents in windows
Related to: [issue](https://github.com/Mintplex-Labs/anything-llm/issues/964#issuecomment-2016804763)
Solution for mac found in : [solution](https://github.com/Mintplex-Labs/anything-llm/issues/821#issuecomment-1968382359)

Alternative solution for windows users:

Steps to fix

1. Go [HF](https://huggingface.co/Xenova/all-MiniLM-L6-v2/tree/main)
2. Clone repo (if familiar with git) or Download everything manually and copy to following folder (supposing your OS in C drive)
`C:\Users\[your-username]\AppData\Roaming\anythingllm-desktop\storage\models\Xenova`
**!!make sure to show hidden files**
3. embeding afterwards should work

![image](https://github.com/Mintplex-Labs/anything-llm/assets/23696982/35eebed1-4e5c-40dd-92fc-4d0e6d97e30c)

**Comment by wxzcldw** [comment]
please careful with the CapsLock，it must be "xenova" not "Xenova"
![image](https://github.com/Mintplex-Labs/anything-llm/assets/163713584/231d58ca-4112-4f7d-8e7b-44eb89bc38eb)
