### ISSUE TITLE
[DOCS]: Suggest add steps about how to get  data-embed-id 

### ISSUE THREAD

**Issue by NickWong77** [Mintplex-Labs/anything-llm#967]
### Description

<script 
  data-embed-id="5fc05aaf-2f2c-4c84-87a3-367a4692c1ee"
  data-base-api-url="http://localhost:3001/api/embed"
  src="http://localhost:3000/embed/anythingllm-chat-widget.min.js">
</script> , steps of how to find data-embed-id is not mentioned in the document

**Comment by timothycarambat** [comment]
You need to create an embed in the actual local AnythingLLM app running so that the script has a real server and embed ID to speak to.
