### ISSUE TITLE
How to fix language output

### ISSUE THREAD

**Issue by Olivia7777** [Mintplex-Labs/anything-llm#97]
When I ask questions in Chinese, it sometimes answers in Chinese and sometimes in English. What is the reason? How should we solve this problem?

**Comment by sweetcard** [comment]
This is because the model used can not support your language completely.
Change another more powerful model and try it again.

**Comment by timothycarambat** [comment]
Unfortunately most models are not fully multilingual. If you know your model is capable of multi-language response the best place to force this instruction is in the system prompt. If you dont change the workspaces system prompt it will be given in english (as it is default written in english) and that is probably messing with your output.
