### ISSUE TITLE
[BUG]: Could not respond to message. LanceDBError: LanceError(IO): Query vector must have non-zero length

### ISSUE THREAD

**Issue by lbls888** [Mintplex-Labs/anything-llm#971]
### How are you running AnythingLLM?

Desktop

### What happened?

The knowledge base has an error.  Is it a problem with the settings or something else? Does anyone know?

**Comment by timothycarambat** [comment]
This happens when sending a chat?

**Comment by lbls888** [comment]
> This happens when sending a chat?
Yes, after uploading the knowledge base file, selecting it, and returning to the chat page, this situation occurs. The introductory video works very smoothly, so why is this problem occurring? I'm deeply doubting myself.

**Comment by timothycarambat** [comment]
You reported this issue as using docker. Can you open the docker container logs and send a chat to see the full crash error and report.

**Comment by mulderyu** [comment]
i have the same issue, when setting "Embedding Preference" to opanai or others, ther error will occure, i can only use anythingllm embedder

**Comment by lbls888** [comment]
> You reported this issue as using docker. Can you open the docker container logs and send a chat to see the full crash error and report.

I only used the desktop version of AnythingLLM for desktop.  I don't understand Docker and I can't use it. The log in the software is: "workspaceName": "lbls88",  "numberOfDocumentsAdded": 1
![QQ截图20240327163405](https://github.com/Mintplex-Labs/anything-llm/assets/131499083/8d9353e2-fbe3-4d64-b1a9-135771f8a08e)

**Comment by timothycarambat** [comment]
Then why did you report the issue as Docker (local)?? @mulderyu are you on docker or desktop?

**Comment by lbls888** [comment]
I'm a desktop software developer, and the report is also for the desktop.  Maybe I'm not good at it. The desktop version seems to be very leisurely, with only the information I provided.

**Comment by mulderyu** [comment]
> Then why did you report the issue as Docker (local)?? @mulderyu are you on docker or desktop?

sorry forgot to mention that i'm using docker verison

**Comment by mulderyu** [comment]
i just find out the solution(maybe) on docker version
just delete /app/server/storage/lancedb/{workspace name}.lance directory, re-add document to workspace, then it works!
maybe it can use on desktop version too

**Comment by mulderyu** [comment]
> i just find out the solution(maybe) on docker version just delete /app/server/storage/lancedb/{workspace name}.lance directory, re-add document to workspace, then it works! maybe it can use on desktop version too

remember to remove and delete files on workspace, then delete /app/server/storage/lancedb/{workspace name}.lance directory

**Comment by timothycarambat** [comment]
Creating a new workspace would solve this and is going to be the recommended go-forward solutions for this. Root cause is the dimensionality response from using the non-default embedder and getting a 0 length response.

If you delete a workspace it will delete the attached files (not the source files!) and the lance folder for that workspace if you wanted to clean that up!

**Comment by snoworld888** [comment]
> > i just find out the solution(maybe) on docker version just delete /app/server/storage/lancedb/{workspace name}.lance directory, re-add document to workspace, then it works! maybe it can use on desktop version too
> 
> remember to remove and delete files on workspace, then delete /app/server/storage/lancedb/{workspace name}.lance directory

it doesn't work
Could not respond to message.
LanceDBError: LanceError(IO): Query vector must have non-zero length, C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lance-0.9.18\src\dataset\scanner.rs:378:27

**Comment by snoworld888** [comment]
> Creating a new workspace would solve this and is going to be the recommended go-forward solutions for this. Root cause is the dimensionality response from using the non-default embedder and getting a 0 length response.
> 
> If you delete a workspace it will delete the attached files (not the source files!) and the lance folder for that workspace if you wanted to clean that up!

it doesn't work too

**Comment by timothycarambat** [comment]
What are you using for embedding? This error occurs to those who use Ollama and forgot to run `ollama serve` or are using an LLM for embedding like `llama2` instead of an actual embedding model since ollama does not differentiate and people just pick a random one

**Comment by snoworld888** [comment]
> What are you using for embedding? This error occurs to those who use Ollama and forgot to run `ollama serve` or are using an LLM for embedding like `llama2` instead of an actual embedding model since ollama does not differentiate and people just pick a random one

ye，I use ollama, but it was started 
![Uploading 1715220827250.png…]()

**Comment by snoworld888** [comment]
> What are you using for embedding? This error occurs to those who use Ollama and forgot to run `ollama serve` or are using an LLM for embedding like `llama2` instead of an actual embedding model since ollama does not differentiate and people just pick a random one

ye，I use ollama, but it was started 
![Uploading 1715220827250.png…]()

**Comment by laowalter** [comment]
I got the same problem with the latest docker every time upload local documents.
here is the outputs of the docker log:

[Event Logged] - sent_chat
Adding new vectorized document into namespace asdf
Cached vectorized results of custom-documents/AttentionLSTM.pdf-3c95c5d7-e805-4bd6-8c96-aebdc3809ff7.json found! Using cached data to save on embed costs.
Adding new vectorized document into namespace asdf
Cached vectorized results of custom-documents/CNN_for_stock_price_prediction.pdf-232e22cf-27e7-4d4a-b6c2-9bc499e13c45.json found! Using cached data to save on embed costs.
[TELEMETRY SENT] {
  event: 'documents_embedded_in_workspace',
  distinctId: 'cb46b0f4-fe3a-4e49-8d97-35ce385574d9',
  properties: {
    LLMSelection: 'ollama',
    Embedder: 'ollama',
    VectorDbSelection: 'lancedb',
    runtime: 'docker'
  }
}
[Event Logged] - workspace_documents_added
[OllamaEmbedder] Embedding 1 chunks of text with nomic-embed-text:latest.
[Error: Failed to execute query stream: lance error: LanceError(IO): Query vector must have non-zero length, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.12.1/src/dataset/scanner.rs:434:17] {
  code: 'GenericFailure'
}
