### ISSUE TITLE
[BUG]: Custom Messages - User input not saved

### ISSUE THREAD

**Issue by CharlesBdg** [Mintplex-Labs/anything-llm#974]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The user inputs from the Custom Messages in Appearance tab are not saved.
![custom_messages](https://github.com/Mintplex-Labs/anything-llm/assets/73182771/2266a770-b023-48cf-830c-89bcd15d3d86)
![welcome_page_without_user_inputs](https://github.com/Mintplex-Labs/anything-llm/assets/73182771/82ad5e93-4177-48f8-b73d-67da5fa8c7ef)
![Appearance_tab_after](https://github.com/Mintplex-Labs/anything-llm/assets/73182771/153167eb-7552-485d-a87d-ca998bc54ed0)

**Comment by timothycarambat** [comment]
Did you click save changes? The button should appear in the UI after editing those fields below the input.

<img width="846" alt="Screenshot 2024-03-26 at 3 41 10 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/a3d0ce2f-1ddc-4355-bfd2-58b64e26f68e">

Unable to replicate

**Comment by CharlesBdg** [comment]
Yes, each time I click on the save button and only the user input is not saved

**Comment by timothycarambat** [comment]
Replicated:
Add System message
Add user Message
Add System Messae
Add User message

ensure you are not focused on any inputs
click save

Reload the page, notice the use inputs are not retained but the system are.
