### ISSUE TITLE
[BUG]: Custom document folder crashing

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#980]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I created a custom folder and started migrating the files from the standard directory.
When I had moved all files to the custom folder and started re-embedding, an error message appeared about "exceeding vector cache" or similar. A lot and large files were being embedded.
Afterwards, it seems some kind of file has been corrupted. I can no longer embed further files and I cannot remove files from any other workspaces, because I get this error message:

<img width="227" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/a3201202-e5ae-46b1-a4d2-252a20494d08">

**Comment by RahSwe** [comment]
OpenAI Large for embedding, PineCone as databaseMed vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.27 mars 2024 kl. 17:49 skrev Sean Hatfield ***@***.***>:﻿
Which embedding model and vector database provider are you using?

**Comment by timothycarambat** [comment]
Please open the docker container logs and attempt to move to a folder and put the error message here. Also ensure you are on the latest `mintplexlabs/anythingllm` docker image

**Comment by RahSwe** [comment]
Sounds like somerhing I would need a GUI to do =)Med vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.27 mars 2024 kl. 18:40 skrev Timothy Carambat ***@***.***>:﻿
Please open the docker container logs and attempt to move to a folder and put the error message here. Also ensure you are on the latest mintplexlabs/anythingllm docker image

**Comment by timothycarambat** [comment]
@RahSwe you marked this issue as using Docker(remote machine). Are you not on docker?

**Comment by RahSwe** [comment]
I’m on Railway, not sure what that translates to =)Med vänlig hälsningRichard SahlbergAdvokat/Partner Foyen Advokatfirma+46 737 19 51 ***@***.*** | LinkedIn Our services are subject to General Terms and Conditions, which are available on our website here.This communication is confidential and is only intended for the use of the individual or entityto which it is directed. It may contain information that is privileged and exempt from disclosureunder applicable law. Please find Privacy Policy here for information on how we process personal data.27 mars 2024 kl. 21:02 skrev Timothy Carambat ***@***.***>:﻿
@RahSwe you marked this issue as using Docker(remote machine). Are you not on docker?
