### ISSUE TITLE
How do I rebrand the embedded chat widget?

### ISSUE THREAD

**Issue by wallartup** [Mintplex-Labs/anything-llm#987]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I am trying to rebrand the chatwidget (embedded chat). I have gone through the steps in the readme:
yarn
yarn dev

yarn build
I have also built yarn build with a new logo in the assets folder but I still see the anythingLLM logo. 

After building I have moved the chat-widget-min to the frontend/embed folder

What am I doing wrong. Any indication on how to fix this? Does not look good on clients websites when the chatwidget is branded on someone else when it's supposed to be a "data secure" solution.

**Comment by timothycarambat** [comment]
See Style overrides for current data-attributes that can be changed to change the look and icon of the embedder
https://github.com/Mintplex-Labs/anything-llm/blob/master/embed/README.md#script-customization-options

**Comment by Leectan** [comment]
@wallartup I'm faced with the same issue, were you able to found a solution for this?

**Comment by moneyhan69** [comment]
Same issue. And, I cant find the .js and .css files in the docker image

**Comment by moneyhan69** [comment]
> See Style overrides for current data-attributes that can be changed to change the look and icon of the embedder https://github.com/Mintplex-Labs/anything-llm/blob/master/embed/README.md#script-customization-options

Hi, the link referenced is a dead link. Any ideas?  Thanks!

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anythingllm-embed/tree/main?tab=readme-ov-file#script-customization-options
