### ISSUE TITLE
An ability to select multiple files using one key combination

### ISSUE THREAD

**Issue by simonSlamka** [Mintplex-Labs/anything-llm#99]
Hey there,

I tried selecting multiple items from the file embed selector in the UI, but have not been able to do so. Usually, I would expect that something like clicking the first checkbox while holding shift and clicking the last desired checkbox would do the job, but since the UI is not using regular checkboxes, that doesn't work. When working with many documents, this is really important, esp. since PDFs are split page-by-page.

Thank you

**Comment by bibi-b** [comment]
Agree. 

I think, that in the first place it would help, if all files get activated by default within in the workspace you uploaded them. 
Now I am in a workspace and click "upload". After that I have to select those file in the workspace I am in all the time.

**Comment by timothycarambat** [comment]
Closed in redesign, can select multiple files now!
